### ISSUE TITLE
@JMSConnectionFactoryDefinition undeploys java:global defined connection factory when undeploying application

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara#1037]
It seems that when you define a globally shared connection factory via the annotations, for example:

`@JMSConnectionFactoryDefinitions(
    value = {
        @JMSConnectionFactoryDefinition(
            name = "java:global/jms/alcatras/connectionFactory",
            interfaceName = "javax.jms.ConnectionFactory",
            resourceAdapter = "jmsra"
        )
    }
)`

And use this connection factory in various different applications, then when the first application is undeployed, this resource is no longer available to the other applications, it seems to have been undeployed with the application, which should not be the case with java:global definitions. This was tested with payara 4.1.162. 
If you manually define the connection factory in the admin console, then the applications can find and continue to use it even after redeploying. Am I missing a certain concept here?

**Comment by OndrejM** [comment]
I think that definitions defined within the application assembly are meant to be available only while the application i deployed. No matter if the resource is global or not.

I didn't find anything stating that global resources should not be removed when the application that defines them is undeployed. The javadoc for [@JMSConnectionFactoryDefinition](https://docs.oracle.com/javaee/7/api/javax/jms/JMSConnectionFactoryDefinition.html) specifically states that the resource should be provisioned "...at the application's deployment" and is meant to be used by the application (not by other applications). It is only natural that such resources are removed from the server when the application is undeployed. I believe that defining global resources within an application assembly is not specified in any Java EE specification.

May I ask what is your usecase and why it is not convenient for you to define the JMS factory manually (or using a script)?

**Comment by dorpsidioot** [comment]
You have a point there, but my use case is the following:

I have 5 different modules:
- One core EAR which does all the heavy lifting/calculations
- Two communication war's which communicate with different devices on the field, each of the using different protocols
- One frontend web application war
- One EAR to communicate with an external system.

The first two run on server 1, the other on server 2(for communication purposes with office network etc). I'd simply want to define the same connection factory name for all my applications, so I don't have to worry about that, but using the default one should suffice as well.

What is strange however is that when I define a queue globally, it does not get undeployed when I undeploy an application which listens/sends to it. The other applications can still reach this queue(given that they use the same physicalname of course) and act like nothing happened.

**Comment by OndrejM** [comment]
You are right that the behavior with connection factories and queues should be at least consistent. AS it is not specified, it is hard to say which behavior is more appropriate.

I humbly suggest to define all global resources in a new separate WAR, which would always stay deployed. This way the lifecycle of any global resource would not be affected by a lifecycle of any core application.

**Comment by dorpsidioot** [comment]
Is it the application which first creates the connection factory that holds the instance? If that one gets undeployed, then everything will stop working too?

**Comment by OndrejM** [comment]
Yes, resources deined within the application archive, are available while the application is running. If it is stopped or undeployed, such resources are disposed. If you want to  define permanent resources, you need to define them either in the server configuration, or in a separate package, which will remain deployed all the time.
