### ISSUE TITLE
Regression since release 162 - HTTP response with transfer-encoding chunked for HTTP/1.0 request

### ISSUE THREAD

**Issue by michaelpaesold** [payara/Payara#1042]
I just reported this issue upstream: https://java.net/jira/browse/GRIZZLY-1864

The regression came with Grizzly 2.3.24 in Payara release 162.

**Problem description:**
- An HTTP/1.0 only client sends a request (GET or POST) with protocol HTTP/1.0.
- The Servlet (Axis2 in our case) does not specify a Content-length
- Grizzly's HttpServerFilter turns on chunking, adding a Transfer-encoding: chunked header and enables chunking
- The HTTP/1.0 only client fails because it does not understand the chunked transfer encoding

This work correctly before 2.3.24, see more details in the referenced Grizzly JIRA task.

While I excect that this will be fixed upstream, I wanted to report the issue here too, since I don't know how long it might take for you pull in a new version of Grizzly.

My suggested fix including an updated regression test is available as a [GIST](https://gist.github.com/michaelpaesold/3a6ea5522967c1219fe5ef9ae67e8f3d) as well as an attachment here: 
[HTTP_1_0_Chunking_regression.patch.txt](https://github.com/payara/Payara/files/424832/HTTP_1_0_Chunking_regression.patch.txt)

It would be great if you could include the fix in Payara.

**Comment by lprimak** [comment]
Voted

**Comment by michaelpaesold** [comment]
The fix has already been commited upstream, so it would be an option to upgrade to the upcoming Grizzly 2.3.27 version.

**Comment by smillidge** [comment]
When 2.3.27 is released we will incorporate it into the Payara build

**Comment by michaelpaesold** [comment]
2.3.27 has been released and is already on maven central, [changelog for 2.3.27](https://java.net/jira/browse/GRIZZLY/fixforversion/17730)

**Comment by mikecroft** [comment]
This is fixed by #1069 which should be available by the 164 release. Before then, this will get built into a nightly release as soon as it gets merged so will be available as a preview then.
