### ISSUE TITLE
Fail-Fast when attempting to build on JDK 8

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#1062]
I'm on https://github.com/payara/Payara/commit/4660a87c296768a77b9f562f3ad3fa08a750adc4 and when I tried to build Payara by invoking the `gfbuild.sh` script I've got this error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile (default-compile) on project rest-service: Compilation failure
[ERROR] error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.glassfish.admin.rest.annotation.processor.RestModelExtensionProcessor not found
[ERROR] -> [Help 1]
[ERROR] 
```

This is with `Oracle JDK 8u101`

When I set my `JAVA_HOME` to `Oracle JDK 7u80` then the build script finishes just fine. 

The build script should check the current Java version and fail-fast - with a descriptive error message - when an unsupported Java version is found. The current error is rather cryptic and does not give away what's wrong.

**Comment by smillidge** [comment]
actually the build script needs deleting as you should just be able to build Payara using

mvn install from the root.

**Comment by mikecroft** [comment]
We've got issue #338 to purge those old bits and pieces.

**Comment by mikecroft** [comment]
Fixed by #1151

**Comment by jerrinot** [comment]
so is Payara buildable on JDK 8?

**Comment by smillidge** [comment]
yes it's buildable on JDK8 with maven

**Comment by mikecroft** [comment]
Also, if you run `mvn clean install -PQuickBuild -DskipTests` you'll build almost everything you need very quickly. It's really handy for initial builds.

More detail here:
https://github.com/payara/Payara/pull/1073
