### ISSUE TITLE
Payara embedded: JVM System Properties overwritten

### ISSUE THREAD

**Issue by coiouhkc** [payara/Payara#1065]
Hello all,
currently Payara embedded overwrites JVM System Properties like 'javax.net.ssl.trustStore' if being started as in https://github.com/coiouhkc/payara-issue-959.
The reason for it is the code in SystemTaskImpl#setSystemProperty, where it gets overwritten with default domain values ($TEMP/gfembed/config/cacerts.jks).
Is there a way to avoid this behaviour?

**Comment by smillidge** [comment]
Payara Micro has code in it to prevent this happening. Could you try with Payara Micro instead?

**Comment by coiouhkc** [comment]
Hi Steve, what subset of EJB 3.1 does Payara's Micro EJB lite implementation support?

**Comment by smillidge** [comment]
Web profile so no MDB

**Comment by mikecroft** [comment]
Hi @coiouhkc how did you get on with Payara Micro?

**Comment by mikecroft** [comment]
Assuming this is resolved by using Payara Micro. If not, please reopen with more details.
