### ISSUE TITLE
Could not deploy simple war on cluster while Internet is off

### ISSUE THREAD

**Issue by fantaseour** [payara/Payara#1070]
Steps to reproduce:
1. download payara full, unpack, start-domain
2. create new config based on default
3. create new cluster (Clusters->create) based on new config
4. add single instance to cluster
5. start cluster
6. turn off internet connection!
7. try to deploy simple web application with glassfish-web.xml or sun-web.xml 
8. get error:  Unable to locate the DTD to validate your deployment descriptor file [WEB-INF/sun-web.xml] in archive [test]. 

What was expected: app should deploy normally

Notes. Apps could be deployed to das instance without a problem. Also deployment is successful if server has access to internet.

Payara v 161 and 163 was tested on jdk 8.0.91 64 bit. Linux Ubuntu 64 bit.

**Comment by mikecroft** [comment]
I've managed to reproduce this locally and in a virtual machine with NAT networking. I'll need to do a bit more testing to be sure of what's actually going on, but the warning in the console can be ignored. It's a valid warning, but the actual issue here isn't directly related to that.

**Comment by mikecroft** [comment]
Sorry it took a while to get back to this, but I've created internal issue `PAYARA-1277` for it.

I found different behaviour when I unplugged my ethernet cable compared to when I had disabled my network interface. If I disabled the network interface, it failed to deploy but a restart would deploy properly. This wasn't the case if my network cable was unplugged.
