### ISSUE TITLE
Is it possible to configure deployment for doesn't process each persistence unit?

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1074]
I have an webapp in Payara 4.1.1.162 + JPA + Hibernate 4.3.
My webapp has more than 20 PUs, because it needs to look for data in many databases.
But these databases aren't neeeded at the same time, there are options in the menu that
use one or other database at this time. I would like to know if it is possible to configure
Payara/JPA/Hibernate to doesn't do the initial check of databases at deploy time, leaving
it for a time it will be needed at running time, on demand of first user interaction.
Informações:   HHH000204: Processing PersistenceUnitInfo [
	name: myPU1
	...]
Informações:   HHH000204: Processing PersistenceUnitInfo [
	name: myPU2
	...]
 etc
This part of deployment is the main processing time, then the webapp is deployed
more than 4 minutes. If I disable the majority of the PUs, leaving just one, the deployment
is very fast.

**Comment by OndrejM** [comment]
This question is very specific to Hibernate and as Hibernate is not included in Payara Server, I can only provide general advice.

I would try using EntityManager lazily everywhere, injecting EntityManagerFactory first, and calling emf.createEntityManager only when needed. It may or may not help, because hibernate might be validating persistence units defined in persistence.xml even sooner than injection points are being processed.

I would also try to find out if hibernate provides an option (via properties in persistence.xml) to turn off validation of persistence unit completely. It makes little sense to validate PUs lazily, as it would throw a runtime error if an inconsistency happens anyway.

**Comment by edilmar** [comment]
I use JTA and not RESOURCE-LOCAL in persistence.xml for all databases.
The problem is not Hibernate specific, if I use EclipseLink, there is a initial startup time too.
But I will try to question Hibernate team for ideas.

**Comment by OndrejM** [comment]
I checked the behavior of Payara thorughly and it seems that every persistence unit that is injected through either EMF or EM, is being validated by Payara at deployment, at least when the bundled eclipselink is used. There is nothing that can be do about it other than request an enhancement to provide an option not to validate persistence units. 

A workaround that should work would be to retrieve EM dynamically using `SessionContext`, like this (copied from the JPA specification PDF):

```
@Stateless
@PersistenceContext(name="OrderEM")
public class MySessionBean implements MyInterface {
  @Resource SessionContext ctx;

  public void doSomething() {
    EntityManager em = (EntityManager)ctx.lookup("OrderEM");
     ...
  }
}
```

**Comment by edilmar** [comment]
@OndrejM I already use this "lookup" method, but with this method, it is needed to configure ejb-jar.xml and persistence.xml, no way to directly read the information from Payara Connection Polling.
The dream solution would be no ejb-jar/persistence config and an API to call Payara for a dinamic loading of the EntityManager, something like:
`
@Inject SomeConnectionPollClass poll;
public void aMethodThatNeedsAEntityManager() {
  EntityManager em = poll.getEntityManagerFromPoll("OrderEM");
}
`

**Comment by OndrejM** [comment]
I imagine you could implement the `SomeConnectionPollClass` yourself, if you have constant number of PUs with static names. I would do that by defining a session bean like `MySessionBean` above for every PU, it would mean 20 session beans, inject them all to `SomeConnectionPollClass` and then use switch in `getEntityManagerFromPoll` method to select the appropriate PU.

I don't get what you mean by Payara Connection Polling though.

**Comment by edilmar** [comment]
@OndrejM I dont have constant number of PUs.
I have a server where new enterprises are installed in the same webapp, just appending the config in ejb-jar.xml/persistence.xml about new PUs. But the problem is that, after each new enterprise installed, I need to undeploy/deploy the webapp, and the deploy time is slow because each PU has to be initialized by JPA/Hibernate. And in runtime, each PU consumes +- 100 Mb RAM.

**Comment by OndrejM** [comment]
@edilmar In that case I would go with completely dynamic setup and avoid updating persistence.xml/ejb-jar.xml at all. You can override almost everything in persistence.xml using properties, which you can pass to entitymanager using [EntityManagerFactory::createEntityManager](https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManagerFactory.html#createEntityManager-java.util.Map-)

For dynamic configuration of datasrouces, I would create a separate ejb-jar package for every datasource and create the datasource in global JNDI namespace, and then you don't need to redeploy whole application. You would only (re)deploy the ejb-jar that matches the datasource.

Have a look at [my blog post](https://itblog.inginea.eu/index.php/properties-and-config-in-persistence-xml/) for a list of standard properties to override what is in persistence.xml. If you override all properties, you can reuse the same persistence unit. The persistence unit would only define entities and optionally their mapping, the rest of the configuration (JTA datasource,...) would be provided dynamically via properties in map upon creation of the EM. it would also help you reduce the memory footprint.

I'd like to help you even more, e.g. by providing a functional example, but my free time is limited. Therefore, if you think it's worth it, I encourage you to look at the services provided by our company. Either [developer support](http://www.payara.fish/developer_support) or [ad hoc consultancy](http://www.payara.fish/consulting) could be interesting for you.

**Comment by edilmar** [comment]
@OndrejM one more question then I try to implement your idea.
I have one config like this in ejb-jar.xml for each enterprise:
`
      <persistence-context-ref>
        <description>enterpriseX</description>             
        <persistence-context-ref-name>persistence/enterpriseXPU</persistence-context-ref-name>        
        <persistence-unit-name>enterpriseXPU</persistence-unit-name>
        <persistence-context-type>Transaction</persistence-context-type>
      </persistence-context-ref>
`
and one per enterprise in persistence.xml:
`
  <persistence-unit name="enterpriseXPU" transaction-type="JTA">
    <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
    <jta-data-source>enterpriseXDS</jta-data-source>
    <exclude-unlisted-classes>false</exclude-unlisted-classes>
    <properties>
      <property name="hibernate.transaction.jta.platform" value="org.hibernate.service.jta.platform.internal.SunOneJtaPlatform"/>
      <property name="hibernate.archive.autodetection" value="class, hbm"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.FirebirdDialect"/>
    </properties>
  </persistence-unit>
`
Then, I get a EntityManager in this Java code:
`
  public EntityManager getEntityManager(String enterprise) {
    String jndiName = JNDI_ENV + enterprise + "PU";
    em = null;
    try {
      InitialContext ic = new InitialContext();
      em = (EntityManager) ic.lookup(jndiName);
    } catch (NamingException e) {
      genException(e);
    }
    return em;
  }
`
If I will remove the configs from persistence and ejb-jar, I havent a way to use "lookup" method.
You said about create a global JNDI ejb-jar, but I never see how to do this in GF/Payara. But, after to discover, do I get to use the same "lookup" method to search directly in Payara server? And will Payara know about to map the ejb-jar config to database pool configured into it?

**Comment by OndrejM** [comment]
You need to go one level deeper. Instead of getting the EntityManager via a JNDI name, you would create a datasource inside the server, and pass its JNDI name to the EntityManagerFactory to create the EntityManager.

See here how to define a datasource dynamically from within a deployent package (e.g. ejb-jar): https://blogs.oracle.com/enterprisetechtips/entry/datasource_resource_definition_in_java
You may define as many datasources like this dynamically and they will be managed by the server (the pool will be created automatically). I recommend to create a small ejb-jar for every enterprise, which would contain just the definition of the DS, registered under a generated JNDI name, so that the main app can pick it up easily. E.g you would generate the JNDI for enterpriseX like `java:global/env/enterpriseX/datasource` (`java:global` will put it into global namespace so that other apps can access it).

In the application, the code would look like this:

```
@PersistenceUnit(unitName = "multiTenantPU")
EntityManagerFactory emf;

public EntityManager getEntityManager(String enterprise) {
  String datasourceJndiName = "java:global/env/" + enterprise + "/datasource";
  Map properties = new HashMap();
  properties.put("javax.persistence.jtaDataSource", datasourceJndiName);
  return emf.createEntityManager(properties);
}
```

You would just need a single PU called `multiTenantPU` - just use the one you posted above and rename `enterpriseXPU` to `multiTenantPU` or whatever to match `@PersistenceUnit.unitName`

**Comment by OndrejM** [comment]
I forgot to add - you should also [close](https://docs.oracle.com/javaee/6/api/javax/persistence/EntityManager.html#close()) the created EntityManager at some point, ideally after request is completed. I believe that you can close it during the transaction and it gets closed only after the transaction is finished.
