### ISSUE TITLE
Script to automate config of a server without human interaction

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1077]
Hi,
I have a script to automate configuration of the Payara Server: define main password, update jvm-options, configure general options, create database pools, deploy apps.
The problems with my script are 2 initial steps that I don't need to do without human interaction:
1) change-admin-password
2) first update of options, when Server needs that I type Yes or No to the certificate.
Is there some way to run CLI commands for these 2 steps without human interaction?

**Comment by mikecroft** [comment]
Yes, for step 1 you will need to create a password file (text file) with the following values:

```
AS_ADMIN_PASSWORD=
AS_ADMIN_NEWPASSWORD={password}
```

The password can then be changed as follows:
`asadmin --passwordfile=myPasswordFile.txt --user admin  change-admin-password`

For the second step, what command(s) are you running?

**Comment by edilmar** [comment]
Hi,
1) it worked fine to change pass
2) when I run the first asadmin command after first startup, Payara gives a question to accept the certificate builtin SSL. For example, my first command is to remove PermSize and after create a new config:
$ASADMIN --user admin --passwordfile mypass.txt delete-jvm-options -XX\\:PermSize=64m

**Comment by edilmar** [comment]
The complete msg from first CLI command is:

[
[
  Version: V3
  Subject: CN=XXX.com.br
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus: 10169419313505232988537527672329857144740559410777881413558913297550928694444189755320438255515923513335334126375725109023640977577811208590707244606801843564722233378092972496394617004991546559143397323916490482458244902371408364284654769947505209849252983707198243510555477802773973344934792888433567576262087074990302473225140445062213110141918796687790741472407922460478085110982194486515671132945622435419583037555346991147728603921346770934975638937492708877237710674036728366203589971767224458387379929449117021197910288546638352266709298391271115045437321988567089807075881380361488633605598494701952543043181
  public exponent: 65537
  Validity: [From: Mon Jul 25 11:09:00 BRT 2016,
               To: Sun Oct 23 12:09:00 BRST 2016]
  Issuer: CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US
  SerialNumber: [    032dd012 df884106 a3bc2893 1e9f71a8 4aeb]

Certificate Extensions: 8
[1]: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: ocsp
   accessLocation: URIName: http://ocsp.int-x3.letsencrypt.org/
, 
   accessMethod: caIssuers
   accessLocation: URIName: http://cert.int-x3.letsencrypt.org/
]
]

[2]: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
1000: A8 4A 6A 63 04 7D DD BA   E6 D1 39 B7 A6 45 65 EF  .Jjc......9..Ee.
0010: F3 A8 EC A1                                        ....
]
]

[3]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:false
  PathLen: undefined
]

[4]: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.23.140.1.2.1]
[]  ]
  [CertificatePolicyId: [1.3.6.1.4.1.44947.1.1.1]
[PolicyQualifierInfo: [
  qualifierID: 1.3.6.1.5.5.7.2.1
  qualifier: 0000: 16 1A 68 74 74 70 3A 2F   2F 63 70 73 2E 6C 65 74  ..http://cps.let
0010: 73 65 6E 63 72 79 70 74   2E 6F 72 67              sencrypt.org

], PolicyQualifierInfo: [
  qualifierID: 1.3.6.1.5.5.7.2.2
  qualifier: 0000: 30 81 9E 0C 81 9B 54 68   69 73 20 43 65 72 74 69  0.....This Certi
0010: 66 69 63 61 74 65 20 6D   61 79 20 6F 6E 6C 79 20  ficate may only 
0020: 62 65 20 72 65 6C 69 65   64 20 75 70 6F 6E 20 62  be relied upon b
0030: 79 20 52 65 6C 79 69 6E   67 20 50 61 72 74 69 65  y Relying Partie
0040: 73 20 61 6E 64 20 6F 6E   6C 79 20 69 6E 20 61 63  s and only in ac
0050: 63 6F 72 64 61 6E 63 65   20 77 69 74 68 20 74 68  cordance with th
0060: 65 20 43 65 72 74 69 66   69 63 61 74 65 20 50 6F  e Certificate Po
0070: 6C 69 63 79 20 66 6F 75   6E 64 20 61 74 20 68 74  licy found at ht
0080: 74 70 73 3A 2F 2F 6C 65   74 73 65 6E 63 72 79 70  tps://letsencryp
0090: 74 2E 6F 72 67 2F 72 65   70 6F 73 69 74 6F 72 79  t.org/repository
00A0: 2F                                                 /

]]  ]
]

[5]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
]

[6]: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
  Key_Encipherment
]

[7]: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: sitesat1.intersite.com.br
]

[8]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: B0 27 F2 6C E6 CE 1B B9   8F 65 87 68 06 82 C1 A8  .'.l.....e.h....
0010: 59 32 83 47                                        Y2.G
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 5D 64 A6 A2 8E 99 67 3D   3B A1 FF 0B B3 67 AB 9B  ]d....g=;....g..
0010: B9 1D 1A DC EE 4D 7D A2   5D 06 DA 71 79 72 96 4D  .....M..]..qyr.M
0020: A1 6A 84 05 B1 AF 2B 3D   DA E2 BD 40 76 5B A4 86  .j....+=...@v[..
0030: 8D E9 2C 71 6F 81 1C FD   D7 AE CE D9 6E 10 A2 F5  ..,qo.......n...
0040: 13 2F D0 88 E7 C4 4F 1C   57 16 CB 63 E8 22 B7 CF  ./....O.W..c."..
0050: C1 20 F6 1B F8 CA 75 1B   1A A9 E8 B0 77 29 61 C7  . ....u.....w)a.
0060: EA EE 58 EE 48 F5 F4 BF   B1 D7 54 FB F5 2E 65 02  ..X.H.....T...e.
0070: 6B 25 A6 E4 00 07 A5 FE   59 61 EF 2A D4 58 1D 66  k%......Ya.*.X.f
0080: 20 FD 69 01 78 C0 A4 00   D7 B4 22 E4 A8 24 0D 17   .i.x....."..$..
0090: EA 02 43 0A CC 8F 00 20   5A 3F 2C 79 8F C5 09 D2  ..C.... Z?,y....
00A0: AE DD 08 3C 30 B4 75 10   FB 8E 64 CD 4C 62 CC C4  ...<0.u...d.Lb..
00B0: A1 2B 1A D1 0E 9F BB 1A   3C 2E 9C 6B 42 DE FF 84  .+......<..kB...
00C0: CF 90 BD AA 6F 39 D4 31   F6 11 6A 35 50 D8 99 AC  ....o9.1..j5P...
00D0: CE 43 35 7F FE 10 09 09   34 72 8F EF FF 32 BE 52  .C5.....4r...2.R
00E0: 60 78 7C 04 50 E9 78 22   48 B1 0B E3 FF 7A AD 88  `x..P.x"H....z..
00F0: 56 AA 28 73 7D F8 6A FD   B9 86 6A DA CB 8E E0 2A  V.(s..j...j....*

]
Do you trust the above certificate [y|N] -->y

**Comment by michaelpaesold** [comment]
Set the `AS_ADMIN_INTERACTIVE` environment variable to `false`.

On Windows you might use `SET AS_ADMIN_INTERACTIVE=false`, on Unix maybe `export AS_ADMIN_INTERACTIVE=false`.

**Comment by mikecroft** [comment]
Hi @edilmar has Michael's suggestion worked for you?

**Comment by edilmar** [comment]
Hi @mikecroft I didn't installed the new server. I'll do this next week.

**Comment by edilmar** [comment]
@michaelpaesold  and @mikecroft it worked fine, thanks!
