### ISSUE TITLE
Possible to Use Third Party Connection Pool?

### ISSUE THREAD

**Issue by ayedo** [payara/Payara#1088]
Hi,

I was wondering: is it possible to use a third party connection pool with Payara?

We are running some benchmarks, and I would like to see how the native connection pool compares to connection pools such as [Hikari CP.](https://github.com/brettwooldridge/HikariCP)

Thanks.

**Comment by ayedo** [comment]
Just to clarify: I am talking about the JDBC connection pool.

**Comment by mulderbaba** [comment]
@ayedo well that'd be a hard one to replace I guess but you can embed the connection pool config into your application. that's what I usually do when I use c3p0 for instance. I use it by bundling it with spring&hibernate and that makes it easy to configure.

**Comment by OndrejM** [comment]
@avedo, there's no official way to replace the internal connection pool implementation. But if you access the connection pool from JTA, you should be able to add your custom connection pool as a custom JNDI resource, and point JTA to use it via its JNDI name. I'm not sure though if it works, I never tried.

**Comment by mikecroft** [comment]
Hi @ayedo does @OndrejM's solution resolve your problem?

**Comment by ayedo** [comment]
Yes, thank you very much!


On Tue, Nov 15, 2016, at 10:02 AM, Mike Croft wrote:
> Hi @ayedo[1] does @OndrejM[2]'s solution resolve your problem?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
>


Links:

  1. https://github.com/ayedo
  2. https://github.com/OndrejM
  3. https://github.com/payara/Payara/issues/1088#issuecomment-260585131
