### ISSUE TITLE
JSF+ObjectDB: why might deployment of a large web app to Payara Server 4.1.1.163 takes 10 times longer than to Glassfish-4.1

### ISSUE THREAD

**Issue by webelcomau** [payara/Payara#1091]
Adapted from http://stackoverflow.com/questions/35681181/jsfobjectdb-why-might-deployment-of-a-large-web-app-to-glassfish-4-1-1-or-pay

```
Mac OS X: Yosemite 10.10.5
```

Until recently I have been using:

```
NetBeans8.1beta
Glassfish4.1
Mojarra 2.2.7
```

I have recently investigated using:

```
NetBeans8.1
Glassfish4.1.1
Mojarra 2.2.12.
```

With a very large JSF web app (with ObjectDB as JPA persistence provider) I am experiencing massively longer deployment times to both Glassfish4.1.1 (over 10 minutes) AND Payara Server 4.1.1.163 (over 20 minutes) than to Glassfish4.1 (around 2 minutes). That's about 10 times slower on Payara.

_I can't possibly reproduce here or provide examples of the large web app._

Q: Has anybody experienced any similar difference between Glassfish-4.1 and Glassfish-4.1.1 OR Payara Server 4.1.1.163, and where I might I look for the point of difference ?

I tried to investigate it by using the NetBeans Profiler, but could not find the cause.

I have also tried Glassfish logging (which I use frequently and command) and all I could see is the same steps taking painfully longer than usual.

Glad for any advice on:
- What changed since Glassfish4.1
- Other things I could diagnose to find the point of difference.

**Comment by mikecroft** [comment]
I don't know of anything that could make the deployment take so much longer. There's not a lot to go on here, particularly if we can't reproduce or see any examples.

Could you provide any data at all on this? Which steps were taking longer?

**Comment by webelcomau** [comment]
> Could you provide any data at all on this? Which steps were taking longer?

Preparing side-by-side comparison and measurements using screencasting video. More later.

**Comment by webelcomau** [comment]
@mikecroft I have performed careful side-by-side comparison using screencast recording and comparing with timings in the log.

In Payara41 (4.1.1.163) and Glassfish4.1.1 it gets "stuck" as shown below for about 10 minutes, and I have not found any log setting that gives a single line of output here where the problem occurs, and running the server in DEBUG mode also does not seem to give any additional information.

    [2016-09-14T23:02:53.450+1000] [Payara 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1473858173343] [timeMillis: 1473858173450] [levelValue: 800] [[
      Running Payara Version: Payara Server  4.1.1.163 #badassfish (build 215)]]

... runs ok through all steps and then through dozens of these EJB JNDI name declarations:

    [2016-09-14T23:03:48.823+1000] [Payara 4.1] [INFO] [AS-EJB-00054] [javax.enterprise.ejb.container] [tid: _ThreadID=74 _ThreadName=admin-thread-pool(2)] [timeMillis: 1473858228823] [levelValue: 800] [[
      Portable JNDI names for EJB BeanName: [java:global/app-name/BeanName!com.example.BeanName, java:global/app-name/BeanName]]]

Gives this WELD version message:

    [2016-09-14T23:03:48.875+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Version] [tid: _ThreadID=74 _ThreadName=admin-thread-pool(2)] [timeMillis: 1473858228875] [levelValue: 800] [[
      WELD-000900: 2.3.5 (Final)]]

... then takes about 8 seconds before this message ..

    [2016-09-14T23:03:56.666+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=74 _ThreadName=admin-thread-pool(2)] [timeMillis: 1473858236666] [levelValue: 800] [[
    WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]


... Then take many minutes (typically about 10 minutes) before resuming these otherwise harmless warnings ..

    [2016-09-14T23:11:33.387+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Bootstrap] [tid: _ThreadID=74 _ThreadName=admin-thread-pool(2)] [timeMillis: 1473858693387] [levelValue: 800] [[
    WELD-001125: Illegal bean type java.util.Comparator<javax.persistence.metamodel.EntityType<?>> ignored on [EnhancedAnnotatedTypeImpl] public static  class com.example.ElementManager$EntityTypeSorter]]

    [2016-09-14T23:11:59.736+1000] [Payara 4.1] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=74 _ThreadName=admin-thread-pool(2)] [timeMillis: 1473858719736] [levelValue: 900] [[
    The following warnings have been detected: WARNING: Parameter 1 of type T from public void com.example.NumberProperty.setDefaultValue(T) is not resolvable to a concrete type.
]]

Similar warning messages happen in the Glassfish4.1 log, but there is no long pause/holdup.

What else can I do to find out why it is pausing/stalling there for ages ?

**Comment by smillidge** [comment]
Can you  provide a thread dump when it is paused for 10 minutes to see what the threads are doing?

**Comment by webelcomau** [comment]
With Payara41 running in DEBUG mode I took the thread dump here:

```
Info:   WELD-000900: 2.3.5 (Final)
Info:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Info:   Listening to REST requests at context: /command/domain.
```

I can't recall seeing that line about `REST requests` before, it appeared some seconds after the  `WELD-000411: Observer method` line. In any case, it then "stalled" for some time then I took the attached thread dump using:

`$ ./asadmin generate-jvm-report --type=thread`

[2016-09-16-payara41-deployment-stall-thread-dump-1.txt](https://github.com/payara/Payara/files/475933/2016-09-16-payara41-deployment-stall-thread-dump-1.txt)

**Comment by smillidge** [comment]
Looks like it is in the middle of Weld code how long into the deployment was the dump taken?
It would be useful to have a series of dumps at intervals during the long deployment to diagnose better.

**Comment by webelcomau** [comment]
@smillidge 

>  It would be useful to have a series of dumps at intervals during the long deployment to diagnose better.

Thanks for your persistence with this matter, which has been (first with Glassfish4.1.1 and now with Payara41) an enormous headache and expense for me. Hopefully the following diagnosis and files will be enough now for you to find the underlying problem. To be clear, I do not have a sponsor of any kind for time spent investigating this, so I am relying on Payara as a commercial provider to address it (in the hope I can then become a customer and that it helps your other customers too). There is a limit on how much more time I can spend on this before I seek another server alternative, but getting Payara to work sensibly with this particular web app would be ideal.

I have taken 18 thread dumps, together with screencasting, and a screen clock and logs for exact timings.

It's for the following Payara version but not in DEBUG mode this time, and on a clean rebooted machine with bare minimum apps running, so it runs through the stages a few minutes faster than previously reported.

Running Payara Version: Payara Server  4.1.1.163 #badassfish (build 215)]]

[deployment_payara41_thread_2016-09-17_1948-27.txt](https://github.com/payara/Payara/files/478080/deployment_payara41_thread_2016-09-17_1948-27.txt)
Immediately after this log message:
[2016-09-17T19:48:27.086+1000] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=99 _ThreadName=admin-thread-pool(3)] [timeMillis: 1474105707086] [levelValue: 800] [[
  Listening to REST requests at context: /command/domain.]]

[deployment_payara41_thread_2016-09-17_1948-45.txt](https://github.com/payara/Payara/files/478081/deployment_payara41_thread_2016-09-17_1948-45.txt)
A few seconds after the 'Portable JNDI names for EJB' messages and the Weld version message.
[2016-09-17T19:48:34.430+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Version] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474105714430] [levelValue: 800] [[
  WELD-000900: 2.3.5 (Final)]]

That dump might also just correspond with this next log line:

[2016-09-17T19:48:46.399+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474105726399] [levelValue: 800] [[
  WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]

[deployment_payara41_thread_2016-09-17_1949-00.txt](https://github.com/payara/Payara/files/478082/deployment_payara41_thread_2016-09-17_1949-00.txt)
[deployment_payara41_thread_2016-09-17_1950-00.txt](https://github.com/payara/Payara/files/478083/deployment_payara41_thread_2016-09-17_1950-00.txt)
[deployment_payara41_thread_2016-09-17_1951-00.txt](https://github.com/payara/Payara/files/478084/deployment_payara41_thread_2016-09-17_1951-00.txt)
[deployment_payara41_thread_2016-09-17_1952-00.txt](https://github.com/payara/Payara/files/478085/deployment_payara41_thread_2016-09-17_1952-00.txt)
[deployment_payara41_thread_2016-09-17_1953-00.txt](https://github.com/payara/Payara/files/478086/deployment_payara41_thread_2016-09-17_1953-00.txt)
[deployment_payara41_thread_2016-09-17_1954-00.txt](https://github.com/payara/Payara/files/478087/deployment_payara41_thread_2016-09-17_1954-00.txt)
[deployment_payara41_thread_2016-09-17_1955-00.txt](https://github.com/payara/Payara/files/478088/deployment_payara41_thread_2016-09-17_1955-00.txt)
**No other logged activity for any of the above (for this run about 6 minutes "stalling" or "spinning wheels").**


[deployment_payara41_thread_2016-09-17_1955-36.txt](https://github.com/payara/Payara/files/478089/deployment_payara41_thread_2016-09-17_1955-36.txt)
A few seconds after this is logged:
[2016-09-17T19:55:27.819+1000] [Payara 4.1] [INFO] [] [org.jboss.weld.Bootstrap] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474106127819] [levelValue: 800] [[
  WELD-001125: Illegal bean type java.util.Comparator<javax.persistence.metamodel.EntityType<?>> ignored on [EnhancedAnnotatedTypeImpl] public static  class com.example.web.ElementManager$EntityTypeSorter]]

[deployment_payara41_thread_2016-09-17_1955-55.txt](https://github.com/payara/Payara/files/478090/deployment_payara41_thread_2016-09-17_1955-55.txt)
A few seconds after this is logged:
[2016-09-17T19:55:50.517+1000] [Payara 4.1] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474106150517] [levelValue: 900] [[
  The following warnings have been detected: WARNING: Parameter 1 of type T from public void com.example.entity.dynamic.NumberProperty.setDefaultValue(T) is not resolvable to a concrete type.
]]

[deployment_payara41_thread_2016-09-17_1956-00.txt](https://github.com/payara/Payara/files/478091/deployment_payara41_thread_2016-09-17_1956-00.txt)
A few seconds after this is logged:
[2016-09-17T19:55:58.945+1000] [Payara 4.1] [WARNING] [] [org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474106158945] [levelValue: 900] [[
  Class class Tmp has null package]]
[2016-09-17T19:56:02.813+1000] [Payara 4.1] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=73 _ThreadName=admin-thread-pool(2)] [timeMillis: 1474106162813] [levelValue: 900] [[
  The following warnings have been detected: WARNING: Parameter 1 of type javax.faces.model.DataModel<E> from public void com.corejsf.SortFilterModel.setModel(javax.faces.model.DataModel<E>) is not resolvable to a concrete type.
]]

[deployment_payara41_thread_2016-09-17_1956-53.txt](https://github.com/payara/Payara/files/478092/deployment_payara41_thread_2016-09-17_1956-53.txt)
[deployment_payara41_thread_2016-09-17_1957-04.txt](https://github.com/payara/Payara/files/478093/deployment_payara41_thread_2016-09-17_1957-04.txt)
[deployment_payara41_thread_2016-09-17_1957-40.txt](https://github.com/payara/Payara/files/478094/deployment_payara41_thread_2016-09-17_1957-40.txt)
[deployment_payara41_thread_2016-09-17_1958-00.txt](https://github.com/payara/Payara/files/478095/deployment_payara41_thread_2016-09-17_1958-00.txt)
[deployment_payara41_thread_2016-09-17_1958-37.txt](https://github.com/payara/Payara/files/478096/deployment_payara41_thread_2016-09-17_1958-37.txt)
All above interspersed with other various warnings, mostly about generics. I doubt they are relevant, but they take a minute or so longer (but not painfully longer) to run through than they did in Glassfish4.1 .

[deployment_payara41_thread_2016-09-17_1958-50.txt](https://github.com/payara/Payara/files/478097/deployment_payara41_thread_2016-09-17_1958-50.txt)
JSF app launches.

With thanks for your investigation,

Darren Kelly, Webel IT Australia

**Comment by smillidge** [comment]
The thread dump seems to indicate this is all in deployment on the admin-thread-pool(2) thread. However User cpu time for the offending thread while large is 106 seconds which is nowhere near the time you are seeing. Have you checked your garbage collection during deployment to make sure you are not doing many long stop the world garbage collections?

**Comment by webelcomau** [comment]
@smillidge Thanks Steve for your investigation. This is just some interim feedback:

> User cpu time for the offending thread while large is 106 seconds which is nowhere near the time you are seeing.

> Have you checked your garbage collection during deployment to make sure you are not doing many long stop the world garbage collections?

I am trying to use jvisualvm to analyse this. The mystery is that whatever it is (that might be causing 'long stop garbage collections) does not happen with Glassfish4.1, but does with GF4.1.1 and Payara Server 4.1.1.163. There is no difference in my web app code, which is to say that if there is a garbage collection problem it is triggered by some change between GF4.1 and G4.1.1. 

I am going to have to dedicate some time just to this problem, but it might not be for some days now.

Just so you know my interest in this issue won't wane.

**Comment by mikecroft** [comment]
Thanks @webelcomau, I'll leave this one here for now until we have a bit more clarity.

**Comment by webelcomau** [comment]
@smillidge Steve and @mikecroft Mike.

I have resumed active investigation of this because I have discovered that JRebel won't work  (prevents deployment of) my main web app when run with my "fallback" server Glassfish4.1 (as from NetBeans8.1beta, but run from NetBeans8.1) when I perform a full web app database model deployment.

So I have to get my deployment working reasonably with Payara41 (or live without JRebel most of the time), meaning this issue is now a very high priority for me (because I can't just keep using Glassfish4.1 any more, I need to move to Payara).

I have performed some JVisualVM analysis (all without JRebel activated) to compare a minimal deployment (meaning only part of my web app database model is built) against Glassfish4.1 and Payara 163 Full (Payara Server 4.1.1.163).

As Steve suspected there is a massive difference in the GC, as illustrated in the 2 attached annotated screenshots of JVisualVM during the deployments:

1st: vs Glassfish4.1. Deployment only about 2mins. Note higher peak heap usage about 1.1GB and low GC activity.

2nd: vs Payara 163 Full (Payara Server 4.1.1.163). Deployment about 10mins. Note lower peak heap usage about 500MB **and frequent GC activity** as suspected earlier by Steve:

_The screenshots are taken from a screencast video of the entire deployment process (which I can make available if you wish, although those screenshots tell most of the story)._

The very large project model of database entities for the web app is built using an extended persistence context in ObjectDB. On @Startup I create and persist each object, then I can perform the wiring up of entity relationships without any interim merge; a single merge is then performed on a top-level Project entity object at the end of the startup build and wiring, and the entire project model is written to database using cascading. This strategy has served me well so far and turned out to be much faster than using a regular persistence context.

Q1: Is there anything about using an extended persistence context that you can see might be problematic (for Glassfish4.1.1/Payara4.1, noting there is no problem with Glassfish4.1).

Q2: Is there anything else that might impact on the GC that I could investigate ?

This matter has clearly become a massive, time-consuming problem for me now and is very hard to diagnose, so I am most grateful for any help.

![greendesk-deploy-jvisualvm-glassfish41](https://cloud.githubusercontent.com/assets/7203231/19914045/a3da8b44-a0fb-11e6-9c79-2c88b676b0b1.png)

![greendesk-deploy-jvisualvm-payara41](https://cloud.githubusercontent.com/assets/7203231/19914050/ad226ed8-a0fb-11e6-8721-2b02dfa25d8c.png)

**Comment by webelcomau** [comment]
@smillidge @mikecroft  I tried reorganising the database population on deploy to not use PersistenceContextType.EXTENDED, the result is the same, massively longer deployment on Payara41 (or Glassfish4.1.1) than on Glassfish4.1. 

It still has very large project build (lots of entity creation and wiring) within a transaction and no explicit interim flush() or clear() at any stage. Not sure if that could provoke it.

**Comment by smillidge** [comment]
Max hwap size for the two servers is different. Try raising the configured max heap size on Payara to the same as on GlassFish.

**Comment by mikecroft** [comment]
You could also tune it a little by pinning your Xms (min heap) to the same value as your max heap (`-Xms2g -Xmx2g`) or to at least a minimum of 1250MB. The spikes of GC activity are your heap resizing itself, so you can save a lot of that CPU by giving your JVM all the heap it needs right away.

**Comment by webelcomau** [comment]
@smillidge wrote:

> Max heap size for the two servers is different. Try raising the configured max heap size on Payara to the same as on GlassFish ..

@mikecroft wrote:

> You could also tune it a little by pinning your Xms (min heap) to the same value as your max heap (-Xms2g -Xmx2g) ...

Thanks both of you, **that was it** !  Without JRebel running,  successfully deployed in 115,951 milliseconds, with JRebel running,  successfully deployed in 140,881 milliseconds (so about 2mins).

I already had these as run-time VMargs for the NetBeans web app project:

`-Xms2048m -Xmx2048m `

But on installing NetBeans8.1 (with Glassfish4.1.1), and then Payara41, I had neglected to also match this on the new servers to make room for it ! I have seldom felt so happy to discover I'm stupid.

@mikecroft  wrote:
> or to at least a minimum of 1250MB ...

That's indeed ok for a minimal project build (as shown in my previous JVisualVM graphs), but for a fresh build of my full database model I need the full 2G.

_I am most grateful to both of you and the Payara Team for your help._

**Comment by mikecroft** [comment]
Happy to help :)
