### ISSUE TITLE
Can't use jsf implemetation bundled with app

### ISSUE THREAD

**Issue by cyberoblivion** [payara/Payara#1100]
Because of some compatibility issues with my application and various Mojarra versions I need to maintain a specific JSF implementation version. I tried the recommended configuration in glassfish-web.xml

```
<glassfish-web-app error-url="">
  <class-loader delegate="false" />
  <property name="useBundledJsf" value="true" />
</glassfish-web-app>
```

This doesn't seem to have any effect.

**Comment by mulderbaba** [comment]
@cyberoblivion which JSF version you want to stick with? and how do you use the jsf jar, in war or ear?

**Comment by cyberoblivion** [comment]
We are stuck with support for only 2.1.3-2.1.6 and 2.1.18-2.1.24. We have deployments that use ears and wars but it is mostly for convenience. We could get by with just wars if makes fixing the issue simpler.

**Comment by lprimak** [comment]
@cyberoblivion has this ever worked or is this something you are trying for the first time?
Having some familiarity in that part of the code base, I would say that it doesn't support "downgrading" JSF, it is just for using other JSF implementations, such as Apache MyFaces.

I would say it would be a lot easier for you just to copy the appropriate javax.faces.jar into Payara modules/ directory

**Comment by cyberoblivion** [comment]
@lprimak I can't say 100% if I have ever used it to explicitly "downgrade" but I can tell you that you could bundle a specific jsf version in 3.1. 

I tried your suggestion of copying the 2.1.24 faces jar into the modules directory but Payara will not startup because OSGI requirements do not pass verification.
`Unable to resolve 185.0: missing requirement [185.0] osgi.wiring.package; (&(osgi.wiring.package=com.sun.faces.spi)(version>=2.2.0)`

I also tried bundling 2.2.12 jsf implementation in my webapp but it also has no effect. It looks those glassfish-web.xml properties are just ignored in 4.1+? 

I'm not sure if any of these are really "Bugs" or Documentation has not been updated or I'm still missing something. Maybe, I should file a feature request to support previous versions of JSF? Are there any other options at this point for us to get our application running on Payara?

**Comment by lprimak** [comment]
We will take a look at it as resources become available.  What s the exact issue with JSF 2.2.x that you are experiencing?  The compatibility (as far as my experience) is superb in JSF

**Comment by cyberoblivion** [comment]
Unfortunately that has not been my experience. The exact issue is that the component library we use, Icefaces 3.3.0 does not work with JSF 2.2. You end up with an exception:
`Cannot add the same component twice icefaces_config`

icefaces 4+ would work except we have invested a huge amount of time and testing into the current software and we are happy with it, there is no reason for us to spend the resources to rewrite the entire frontend in a new library.  

We could possibly sponsor this feature?

**Comment by smillidge** [comment]
Hi As Payara is derived from GlassFish 4.x it includes JSF 2.2 as that is the implementation specified by JavaEE 7. If you want to sponsor some work to create a downgraded bundled version that could be possible. Can you submit something via our contact form http://www.payara.fish/contact and we can pick it up from there to work out how feasible ot would be.

**Comment by cyberoblivion** [comment]
Sounds good will do

**Comment by mikecroft** [comment]
I'll close this issue here since we can follow up via the contact form.

Backported fixes are something we now provide under our **professional** support level (previously only **Enterprise** level). I'm not sure if we could do the initial downgrade under that (I'm not sure of the complexity - @smillidge ?) but we could maintain that version with backported fixes.

Here's our new pricing structure:
http://www.payara.fish/production-support-new-pricing
