### ISSUE TITLE
[Payara Micro] Context root defined in glassfish-web.xml file is override after the file is read during deployment

### ISSUE THREAD

**Issue by Prateek1215** [payara/Payara#1104]
Our team is using Payara-micro for the first time. We are making use of Uber-jar for deployment using maven as describer here [http://blog.payara.fish/creating-uber-jar-with-payara-micro]. Our war file name is **microapp.war**. The Web-INF/glassfish-web.xml file looked like this:
`<?xml version="1.0" encoding="UTF-8"?>`
`<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">`
`     <glassfish-web-app error-url="">`
               `<context-root>/test</context-root>`
               ` <class-loader delegate="true"/>`
`     </glassfish-web-app>`

## **Problem:**
The expected path is: http://localhost:8080/test/.....
But the web app is deploying at http://localhost:8080/microapp/.....

The context root defined in glassfish-web.xml file is overriden and the application uses the war file name as context-root.
We have tested that the glassfish-web.xml file is read during deployment.

## **Note**: This is only happening if we user uber-jar. If we deploy programatically, everything goes as expected.

Is anyone else also facing this issue.
Any help would be appreciated.
Thank you.

**Comment by smillidge** [comment]
This is a "feature" the problem with UberJar is that when deploying a war stored within the war by default the war filename will be some horrible temp filename. Therefore if a user does not explicitly specify a context root in their glassfish-web.xml they get a horrible temp context. Therefore UberJar explicitly uses the filename root of the embedded war file to determine the context root. I would suggest renaming your war file to test.war before packaging to get the /test context root.

If you rename the war file to ROOT.war it will be deployed at /

@mikecroft I guess this needs documenting.

**Comment by Prateek1215** [comment]
@smillidge Thanks for your comment. We have decided to go with renaming the war file as Root.war. I think future scope will be to check whether is there any context root defined in glassfish-web.xml. If yes, UberJar takes that context root otherwise take the war name as context root.
I will close the issue as of now.

**Comment by mikecroft** [comment]
Created `PYSVC-90` to get this documented.

**Comment by phillip-kruger** [comment]
Hi Mike.
Did the **<class-loader delegate="true"/>** part of the glassfish-web.xml work ? 
Thanks
