### ISSUE TITLE
NetBeans opens wrong URL when running EAR

### ISSUE THREAD

**Issue by dNhax** [payara/Payara#1108]
**Disclaimer**: As NetBeans in combination with GlassFish 4.1 seem to work correct, I guess this may be a GlassFish 4.1.1 (and thus a Payara) issue.

I'm developing a Maven Enterprise Application Project (attached) with NetBeans 8.1 on my Windows 10 Pro x64 machine. As server I tested GF 4.1.1 first, but after the problem occurred I switched to Payara 4.1.1.163; same problem.

So, when I want to run my application from within NetBeans, after deploying Firefox opens the wrong URL (`http://localhost:8181/xwars` that is) instead of expected `http**s**://localhost:8181/xwars`.
I disabled the unsecured `http-listener-1` so the application is only accessible through HTTPS, but that does not solve the problem.

As NetBeans with GF 4.1 opens the correct URL, I suspect there may be an issue with GF 4.1.1 (and Payara).

If you need any more information, please let me now. If this is not a Payara issue, please let me know if my project setup is wrong at some place.

Best regards,

dNhax

Server log:
> Launching GlassFish on Felix platform
> Sep 24, 2016 7:59:26 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
> INFORMATION: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
> Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@3cb6bd5c in service registry.
> Sep 24, 2016 7:59:30 PM com.sun.logging.LogDomains getResourceBundle
> INFORMATION: Cannot find the resource bundle for the name com.sun.logging.enterprise.system.container.ejb for class org.glassfish.kernel.javaee.MEJBService using org.glassfish.main.core.javaee-kernel [134]
> #!## LogManagerService.postConstruct : rootFolder=C:\Program Files\payara41\glassfish
> #!## LogManagerService.postConstruct : templateDir=C:\Program Files\payara41\glassfish\lib\templates
> #!## LogManagerService.postConstruct : src=C:\Program Files\payara41\glassfish\lib\templates\logging.properties
> #!## LogManagerService.postConstruct : dest=C:\Program Files\payara41\glassfish\domains\domain1\config\logging.properties
> Information:   Running Payara Version: Payara Server  4.1.1.163 #badassfish (build 215)
> Information:   Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter
> Information:   Network listener http-listener-1 on port 8080 disabled per domain.xml
> Information:   Authorization Service has successfully initialized.
> Information:   Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry
> Information:   Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
> Information:   Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
> Information:   Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.
> Information:   Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry
> Information:   Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast
> Schwerwiegend:   Application previously deployed is not at its original location any more: file:/C:/Users/Abakus/Documents/NetBeansProjects/XWars/XWars-ear/target/gfdeploy/XWars-ear/
> Information:   Grizzly Framework 2.3.25 started in: 63ms - bound to [/0.0.0.0:8181]
> Information:   Grizzly Framework 2.3.25 started in: 0ms - bound to [/0.0.0.0:4848]
> Information:   Grizzly Framework 2.3.25 started in: 16ms - bound to [/0.0.0.0:3700]
> Information:   Payara Server  4.1.1.163 #badassfish (215) startup time : Felix (5.466ms), startup services(4.422ms), total(9.888ms)
> Information:   Cleaning JarFileFactory Cache to prevent jar FD leaks
> Information:   HV000001: Hibernate Validator 5.1.2.Final
> Information:   Grizzly Framework 2.3.25 started in: 24ms - bound to [/0.0.0.0:7676]
> Information:   JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://kleinAbakus.fritz.box:8686/jndi/rmi://kleinAbakus.fritz.box:8686/jmxrmi
> Information:   Grizzly Framework 2.3.25 started in: 63ms - bound to [/0.0.0.0:8181]
> Warnung:   Originally deployed application at C:\Users\Abakus\Documents\NetBeansProjects\XWars\XWars-ear\target\gfdeploy\XWars-ear not found
> Information:   Listening to REST requests at context: /management/domain.
> Information:   Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@61f39bb as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@40e60ece.
> Information:   Created HTTP listener http-listener-2 on host/port 0.0.0.0:8181
> Information:   Created HTTP listener admin-listener on host/port 0.0.0.0:4848
> Information:   Created virtual server server
> Information:   Created virtual server __asadmin
> Information:   Setting JAAS app name glassfish-web
> Information:   Virtual server server loaded default web module 
> Information:   Java security manager is disabled.
> Information:   Entering Security Startup Service.
> Information:   Loading policy provider com.sun.enterprise.security.provider.PolicyWrapper.
> Information:   Security Service(s) started successfully.
> Information:   de.dnhax.xwars.persistence.entities.Player actually got transformed
> Information:   EclipseLink, version: Eclipse Persistence Services - 2.6.2.qualifier
> Information:   /file:/C:/Users/Abakus/Documents/NetBeansProjects/XWars/XWars-ear/target/gfdeploy/XWars-ear/XWars-ejb-1.0.0-SNAPSHOT_jar/_XWarsPU login successful
> Information:   Portable JNDI names for EJB PlayerAccess: [java:global/XWars-ear/XWars-ejb-1.0.0-SNAPSHOT/PlayerAccess, java:global/XWars-ear/XWars-ejb-1.0.0-SNAPSHOT/PlayerAccess!de.dnhax.xwars.persistence.PlayerAccess]
> Information:   Mojarra 2.2.13 ( 20160203-1910 unable to get svn info) für Kontext '' wird initialisiert.
> Information:   jts.startup_msg
> Information:   Portable JNDI names for EJB XWarsLogicImpl: [java:global/XWars-ear/XWars-ejb-1.0.0-SNAPSHOT/XWarsLogicImpl!de.dnhax.xwars.logic.XWarsLogic, java:global/XWars-ear/XWars-ejb-1.0.0-SNAPSHOT/XWarsLogicImpl]
> Information:   Glassfish-specific (Non-portable) JNDI names for EJB XWarsLogicImpl: [de.dnhax.xwars.logic.XWarsLogic#de.dnhax.xwars.logic.XWarsLogic, de.dnhax.xwars.logic.XWarsLogic]
> Information:   WELD-000900: 2.3.5 (Final)
> Information:   Loading application [__admingui] at [/]
> Information:   Loading application __admingui done in 30.143 ms
> Information:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
> Information:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
> Information:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
> Information:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
> Information:   Mojarra 2.2.13 ( 20160203-1910 unable to get svn info) für Kontext '/xwars' wird initialisiert.
> Information:   RewritePhaseListener starting up.
> Information:   Monitoring jndi:/server/xwars/WEB-INF/faces-config.xml for modifications
> Information:   Running on PrimeFaces 6.0
> Information:   RewriteFilter starting up...
> Information:   Loaded [4] org.ocpsoft.rewrite.servlet.spi.RewriteLifecycleListener [org.ocpsoft.rewrite.prettyfaces.PrettyFacesRewriteLifecycleListener<-100>, org.ocpsoft.rewrite.faces.FacesRewriteLifecycleListener<0>, org.ocpsoft.rewrite.servlet.config.lifecycle.JoinRewriteLifecycleListener<2147483647>, org.ocpsoft.rewrite.servlet.impl.DefaultRewriteLifecycleListener<2147483647>]
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.RequestCycleWrapper [org.ocpsoft.rewrite.servlet.impl.HttpRewriteRequestCycleWrapper<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.spi.RewriteProvider [org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.RewriteResultHandler [org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.InboundRewriteProducer [org.ocpsoft.rewrite.servlet.impl.HttpInboundRewriteProducer<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.OutboundRewriteProducer [org.ocpsoft.rewrite.servlet.impl.HttpOutboundRewriteProducer<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.ContextListener [org.ocpsoft.rewrite.prettyfaces.PrettyConfigContextListener<0>]
> Information:   Loaded [0] org.ocpsoft.rewrite.servlet.spi.RequestListener []
> Information:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.RequestParameterProvider [org.ocpsoft.rewrite.prettyfaces.PrettyFacesRequestParameterProvider<0>]
> Information:   Loaded [1] org.ocpsoft.rewrite.el.spi.ExpressionLanguageProvider [org.ocpsoft.rewrite.faces.FacesExpressionLanguageProvider<30>]
> Information:   Loaded [1] org.ocpsoft.rewrite.spi.InvocationResultHandler [org.ocpsoft.rewrite.faces.NavigatingInvocationResultHandler<100>]
> Information:   Loaded [0] org.ocpsoft.common.spi.ServiceEnricher []
> Information:   Loaded [1] org.ocpsoft.rewrite.spi.ConfigurationCacheProvider [org.ocpsoft.rewrite.servlet.impl.ServletContextConfigurationCacheProvider<0>]
> Information:   Loaded [2] org.ocpsoft.rewrite.config.ConfigurationProvider [org.ocpsoft.rewrite.annotation.config.AnnotationConfigProvider<100>, org.ocpsoft.rewrite.prettyfaces.PrettyFacesRewriteConfigurationProvider<1>]
> Information:   Loaded [0] org.ocpsoft.rewrite.spi.RuleCacheProvider []
> Information:   Loaded [1] org.ocpsoft.rewrite.spi.GlobalParameterProvider [org.ocpsoft.rewrite.instance.WildcardParameterProvider<0>]
> Information:   Rewrite 3.4.1.Final initialized.
> Information:   Loading application [XWars-ear#XWars-web-1.0.0-SNAPSHOT.war] at [/xwars]
> Information:   XWars-ear was successfully deployed in 50.779 milliseconds.

[XWars - Payara.zip](https://github.com/payara/Payara/files/491254/XWars.-.Payara.zip)
[domain.zip](https://github.com/payara/Payara/files/491766/domain.zip)

**EDIT**: Re-enabling the `http-listener-1` fixes the issue (NetBeans opens `http://localhost:8080/xwars` but it gets redirected to `http**s**://localhost:8181/xwars`, as expected). So this may be a NetBeans issue after all.

**Comment by mikecroft** [comment]
This sounds like a NetBeans issue. I checked their BugZilla and it looks like the issue hasn't been raised there:
https://netbeans.org/bugzilla/buglist.cgi?chfieldfrom=2013-09-01&chfieldto=Now&component=GlassFish&query_format=advanced

Paging @GeertjanWielenga - is the best thing to do from here to raise a bug on BugZilla?

**Comment by GeertjanWielenga** [comment]
Yes and then send me a mail here with a link to the issue so we can expedite it: geertjan.wielenga@oracle.com
Gj 

    On Wednesday, September 28, 2016 12:19 PM, Mike Croft <notifications@github.com> wrote:
 

 This sounds like a NetBeans issue. I checked their BugZilla and it looks like the issue hasn't been raised there:
https://netbeans.org/bugzilla/buglist.cgi?chfieldfrom=2013-09-01&chfieldto=Now&component=GlassFish&query_format=advancedPaging @GeertjanWielenga - is the best thing to do from here to raise a bug on BugZilla?—

**Comment by dNhax** [comment]
Hey,

thanks for answering!
I already filed a bug at NetBeans' Bugzilla ([https://netbeans.org/bugzilla/show_bug.cgi?id=268195](url)).

Regards.

**Comment by GeertjanWielenga** [comment]
Please use my work e-mail address from this point onwards: geertjan.wielenga@oracle.com
Gj 

    On Thursday, September 29, 2016 5:18 PM, dNhax <notifications@github.com> wrote:
 

 Hey,thanks for answering!
I already filed a bug at NetBeans' Bugzilla (https://netbeans.org/bugzilla/show_bug.cgi?id=268195).Regards.—

**Comment by mikecroft** [comment]
Closing under the assumption that it will be continued as a Netbeans issue
