### ISSUE TITLE
Authorization stops working after app redeploy

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#1115]
I have a simple web application packages as a war-file. It has a glassfish-web.xml file that describes mapping between principals and roles. I'm deploying the application on a remote server by copying the war-file to the domain autodeploy folder. On first deploy everything works fine, authorization is done according to configuration in glassfish-web.xml. When I change the principal to role mapping (e.g. add another principal to a role), build war, and redeploy, then authorization stops working. Every authenticated HTTP-request returns 403 Forbidden. If I then undeploy the application and deploy it again, authorization works as expected.
Running on Payara Server 163.

Extract from glassfish-web.xml:

```
<security-role-mapping>
    <role-name>user</role-name>
    <principal-name>a-user</principal-name>
    <principal-name>b-user</principal-name>
    <principal-name>c-user</principal-name>
  </security-role-mapping>
```

Extract from web.xml:

```
<security-constraint>
        <display-name>Constraint1</display-name>
        <web-resource-collection>
            <web-resource-name>all</web-resource-name>
            <description/>
            <url-pattern>/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <description/>
            <role-name>user</role-name>
        </auth-constraint>
    </security-constraint>
```

Payara server.log when redeploying with changed principal to role mapping:

```
[2016-09-28T12:32:05.427+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.system.core.security] [tid: _ThreadID=66 _ThreadName=AutoDeployer] [timeMillis: 1475058725427] [levelValue: 900] [[
  No Principals mapped to Role [user].]]
```

**Comment by mikecroft** [comment]
Do you have a simple test case which shows this behaviour?
http://sscce.org/

**Comment by peraxel** [comment]
[jaas-bug.zip](https://github.com/payara/Payara/files/499162/jaas-bug.zip)
Unzip jaas-bug.zip
Copy payara-4.1.1.163.zip into jaas-bug dir
./run.sh

**Comment by mikecroft** [comment]
Perfect! Thank you, that shows the error very clearly. I've created `PAYARA-1082` to track the issue.

**Comment by cghislai** [comment]
I also have this issue using default principal to role mapping with version >= 163 at least. Version 161.1 works fine.
