### ISSUE TITLE
Sources are not attached in Maven properly

### ISSUE THREAD

**Issue by gregrluck** [payara/Payara#1118]
I was having trouble getting IntelliJ to attach sources from 

<dependency>
                    <groupId>fish.payara.extras</groupId>
                    <artifactId>payara-embedded-all</artifactId>
                    <scope>test</scope>
                </dependency>

This is using 4.1.1.163.0.1. 

Instead of the -sources.jar contains the source code in a tree it contains a file called source.zip.

This is not the convention so far as I know.

The workaround is to go into your local .m2 repo and expand the jar to get at the zip then manually attach it in IntelliJ. This then works.

**Comment by mulderbaba** [comment]
created internal issue `PAYARA-1084` to track this request

**Comment by mikecroft** [comment]
Should be fixed from 164
