### ISSUE TITLE
Bug in parametrized log messages

### ISSUE THREAD

**Issue by rds76** [payara/Payara#1122]
For example:
Source: [LogUtils.java](https://github.com/payara/Payara/blob/master/appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/LogUtils.java#L289`)
correct: `message = "Invalid request scheme for Endpoint {0}. Expected ''{1}'', received ''{2}''.",`

Regarding [MessageFormat](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html), params must be escaped with double single quotes.

**There are many such a wrong escaped log messages in source tree!**

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1115`
