### ISSUE TITLE
Proposal: Use javax.cache.annotation.CacheDefaults when injecting JCache

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#1124]
Payara uses `CacheDefaults` for cache resolution in the CDI interceptor as the spec mandates. 

I believe it would make a lot of sense to use `CacheDefaults` as a cache resolution strategy when injecting JCache via `@Inject`. 

Currently it does use name of a declaring class as a cache name. There is also the `@NamedCache` but that creates a dependency on Payara-specific code.

**Comment by smillidge** [comment]
Do you fancy making a PR to demonstrate?

**Comment by jerrinot** [comment]
I'll have a look at it. 

The main issue I can foresee is a potential clash with the official Java EE - JCache integration. If the EG decided to not use the `@CacheDefaults` as a default name for caches injected via `@Inject`.

**Comment by gregrluck** [comment]
Lets cross that bridge when we get to it.

**Comment by Quix0r** [comment]
So there is currently no other way to `@Inject` JCache than with Payara's `@NamedCache`? I would like to write my WAR project independent (I may call it portable) rather than bounded to a (vendor-)specific container and maybe major/minor version number.
