### ISSUE TITLE
Question: How to enable Hazelcast when running Arquillian tests?

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#1127]
I apologize if this is not the right place to ask questions but I could not find any Payara forum. 

What's the best/recommended way to enable Hazelcast while running tests in an embedded Payara container driven by Arquillian? I managed to get it running with https://github.com/jerrinot/microprofile-conference/commit/a3fab608c46cffe789fbe1c6c1b9077ccfb544ad, but it does not feel very good. 

Is there any better way? Many thanks!

**Comment by mikecroft** [comment]
I don't really know how Arquillian works, but I know that Payara Micro has Hazelcast enabled by default. @mulderbaba do you know if it's possible to use Payara Micro with Arquillian?

**Comment by mulderbaba** [comment]
no it's not @mikecroft, arquillian is tightly integrated with glassfish-embedded, hence the payara-embedded. 
@jerrinot maybe we should implement an arquillian extension for configuring hazelcast and have it integrated with payara-embedded. it's too much domain.xml in your commit :) we should get it simplified somehow.

**Comment by mikecroft** [comment]
Created enhancement request `PAYARA-1198`. I'll close this issue now, because there's a workaround of using the domain.xml.
