### ISSUE TITLE
Blocking Cache annotation

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#1137]
I thought Payara could have a custom annotation to introduce a behavior described in https://github.com/jsr107/jsr107spec/issues/373

Something like `@Blocking` or `@Atomic` - when used together with `@CacheResult` it would behave as described at https://github.com/jsr107/jsr107spec/issues/373#issue-183403216

This is very useful in high throughput scenarios where the actual method execution is expensive.

**Comment by smillidge** [comment]
Do you fancy creating it?

**Comment by fturizo** [comment]
@jerrinot, is @smillidge suggestion's fine with you? Let us know what do you think.

**Comment by jerrinot** [comment]
@fturizo: Hi, I am rather busy nowdays. I don't expect to have time for this before end of the year.

**Comment by fturizo** [comment]
@jerrinot, considering that this feature is up to consideration for _JCache v2.0_, it might be a good idea to wait until a consensus is reached on how to handle blocking caches using annotations. Have you considered using a programmatic approach to solve you issue, using Java's concurrency utilities?

**Comment by jerrinot** [comment]
Hi @fturizo, thanks for your reply. 

Programmatic approach is certainly an option, however it forces a developer to deal with concurrency - and that's something developers are notoriously bad at. I thought Payara could provide a nice & easy-to-use abstraction here. 

My idea is to use Payara as sort of "playing ground" and explore various ways how to integrate JCache into the Java EE world, find integration issues. So when the JCache 2.0 Expert Group is eventually formed we will already have a clear-ish picture about what to do. This should be good for both Payara (=being able to deliver JCache 2.0 features quickly) and the JCache 2.0 spec (=no ivory tower design)

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.
