### ISSUE TITLE
The maximum number of payara clusters with Hazelcast session persistence.

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [payara/Payara#1161]
We are considering adoption of Payara server and would like to know the maximum number of payara clusters with Hazelcast session persistence.
http://blog.payara.fish/payara-server-4.1.151-sneak-preview-hazelcast-session-persistence

Is there a track record about maximum number of Payara server clusters with Hazelcast session persistence?

If inappropriate post, please let me know.

**Comment by lprimak** [comment]
@daisuke-yoshimoto 
Do you mean clusters or instances in a single cluster?

**Comment by daisuke-yoshimoto** [comment]
@lprimak 
Thank you for your reply.
We mean many instances in a single cluster.

**Comment by lprimak** [comment]
I don't have anything documented, but as far as I know it would be limited by Hazelcast itself, i.e. no limit

**Comment by daisuke-yoshimoto** [comment]
@lprimak 
Thank you for the information.

We are looking for the rough indication or the introduction example, not the rigorous and exact information.
And, we are considering adoption of Payara server with Hazelcast session persistence, not other application server with Hazelcast session persistence.

**Comment by OndrejM** [comment]
As @lprimak says, Payara Server does not impose any limit and there's no explicit limit by Hazelcast either. The only factor is that with too many nodes in the cluster, the performance of the distributed session degrades, as the nodes communicate with each other. But Hazelcast team claim that there's very little degradation even with 100+ nodes in the cluster.

**Comment by daisuke-yoshimoto** [comment]
@OndrejM
Thank you for the information.
We understood very well and will consider Hazelcast's degradation in the load test.

**Comment by OndrejM** [comment]
@daisuke-yoshimoto, we haven't done any performance testing ourselves. If you can, we would be very grateful if you inform us about your findings. 

Hazelcast provides various options to configure the cluster. One of them is to turn some nodes into lite nodes, which is also [supported by Payara Server](http://blog.payara.fish/payara-server-lite-nodes) Such nodes would not store the data but always ask other full nodes to retrieve the data - it might improve the performance in certain cases, as the distributed data is located on smaller number of nodes, possibly decreasing the communication overhead.

If you find any significant degradation, it is worth considering turning a portion of nodes into lite nodes. 

Another option provided by Hazelcast is to join cluster with client API, but this is not supported by Payara Server. Hazelcast cluster can have thousands of such clients without degradation, but clients don't store data and are limited compared to member nodes. There are currently no plans to support this kind of communication within Payara hazelcast-based cluster.

**Comment by daisuke-yoshimoto** [comment]
@OndrejM

Thank you very mach for telling us the turning point of Hazelcast.

> If you find any significant degradation, it is worth considering turning a portion of nodes into lite nodes.
