### ISSUE TITLE
Negative values for countopenconnections

### ISSUE THREAD

**Issue by fregatte** [payara/Payara#1176]
Hello.
I have an old problem that is described in the glassfish's bugtracker :
https://java.net/jira/browse/GLASSFISH-16843
I have exactly the same problem, but I use Payara Server 4.1.1.161 #badassfish (build 62).
I get the same result: negative values in line "count" on monitoring URL https://payara:4848/monitoring/domain/server/http-service/server/request/countopenconnections
Now, I have "-80" value when there is no connections. But this value can change from time to time.
How can I fix it?

**Comment by mulderbaba** [comment]
@fregatte I could reproduce this only by invoking
`./asadmin get -m server.http-service.__asadmin.request.countopenconnections-count`
invoking `./asadmin get -m server.http-service.server.request.countopenconnections-count` results with 0 for me.

**Comment by mulderbaba** [comment]
Created internal issue PAYARA-1188
