### ISSUE TITLE
JSON wrongly serialise long long values

### ISSUE THREAD

**Issue by jinahya** [payara/Payara#1184]
# Description #
----------

Payara generates wrong value for JSON, not XML.

## Expected Outcome

```java
public class Placement {

    @XmlAttribute
    private Long id;
}
```
```xml
<placement id="4611686018657026049">
</placement>
```
```json
{
"type": "placement",
"id": 4611686018657026049,
}
```

## Current Outcome

```json
{
"type": "placement",
"id": 4611686018657026000,
}
```

## Environment ##

- **Payara Version**:  4.1.1.163 #badassfish (build 215)
- **Edition**: Full
- **JDK Version**: 8 u101 - Oracle
- **Operating System**: Linux / Mac

**Comment by jinahya** [comment]
JavaScript has 64-bit double precision floats and doesn't have 64-bit integers.
I, apparently, have to serve those long `long` values as strings.

```java

    @XmlAttribute
    public String getIdAsString() {
        return ofNullable(getId()).map(Long::toString).orElse(null);
    }

    @XmlAttribute
    private Long id;
```

**Comment by mikecroft** [comment]
What are the steps to reproduce? Do you have a test case we can use?

**Comment by jinahya** [comment]
Sorry, as you might already know, it seems not a Payara's problem.
