### ISSUE TITLE
Payara removes the context root from glassfish-web xml

### ISSUE THREAD

**Issue by kahlon1005** [payara/Payara#1188]
# Description #
----------
When running or debuging application using Netbeans, the root context tag is getting removed from glassfish-web.xml. This issue is not replicated using glassfish 4.1.1

## Expected Outcome
The glassfish-web.xml shall not be modified and this shall result application named say sample shall open on browser from root context 
http:localhost:8080/index.xhtml

## Current Outcome
The context-root tag is getting removed from glassfish-web.xml enabling application say sample having context root sample 

tag removed 

`<context-root>/</context-root>`

Application named sample open with context sample 
localhost:8080/sample/index.xhtml

## Steps to reproduce (Only for bug reports) 
1. Download payara server 
2. Configure payara server in Netbeans
3.  Run or debug application. 
4. the context-root tag gets removed
5. application open in chrome browser with context-root sample

## Environment ##

- **Payara Version**: 4.1.1.164 #badassfish (build 28)
- **Edition**:  Full
- **JDK Version**: 1.8.0_101 - Oracle
- **Operating System**:  Windows 7 professional
- Netbeans 8.2

**Comment by smillidge** [comment]
Not reproducible

**Comment by mikecroft** [comment]
@kahlon1005 is the `context-root` actually being removed at all, or is it just being **_overridden_**? It would help to see your source code because this doesn't seem to be reproducable with any WAR file.

**Comment by kahlon1005** [comment]
This was happening on Window 10. But, I had added Payara server again and I am unable to reproduce it there after.
