### ISSUE TITLE
Migration from glassfish 4.0 to Glassfish 4.1.1 - JDBC Realm issue

### ISSUE THREAD

**Issue by kahlon1005** [payara/Payara#1189]
# Description #
----------
I have this security configuration in Glassfish domain.xml which works for 4.0 but fail in 4.1.1 can someone help to identify what is wrong. The only difference is the class package "ee"

GF 4.0 (with extra ee)

```
<auth-realm classname="com.sun.enterprise.security.ee.auth.realm.jdbc.JDBCRealm" name="authentication-realm">
<property name="jaas-context" value="jdbcRealm"></property>
<property name="password-column" value="password"></property>
<property name="datasource-jndi" value="jdbc/SomeDS"></property>
<property name="group-table" value="v_user_role"></property>
<property name="charset" value="UTF-8"></property>
<property name="user-table" value="v_user_role"></property>
<property name="group-name-column" value="rolename"></property>
<property name="digest-algorithm" value="SHA-256"></property>
<property name="user-name-column" value="username"></property>
<property name="digestrealm-password-enc-algorithm" value="SHA-256"></property>
<property name="encoding" value="Base64"></property>
</auth-realm>
```

GF 4.1.1

```
<auth-realm classname="com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm" name="authentication-realm">
<property name="jaas-context" value="jdbcRealm"></property>
<property name="password-column" value="password"></property>
<property name="datasource-jndi" value="jdbc/SomeDS"></property>
<property name="group-table" value="v_user_role"></property>
<property name="charset" value="UTF-8"></property>
<property name="user-table" value="v_user_role"></property>
<property name="group-name-column" value="rolename"></property>
<property name="digest-algorithm" value="SHA-256"></property>
<property name="user-name-column" value="username"></property>
<property name="digestrealm-password-enc-algorithm" value="SHA-256"></property>
<property name="encoding" value="Base64"></property>
</auth-realm>
```

insert into (username, password, rolename) v_user_role('test', 'A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=', 'Administrator');

password in database 
SHA256 converted password  : A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=

## Expected Outcome
Glassfish 4.0 : login successful
Glassfish 4.1.1./Payara : login successful

## Current Outcome
Glassfish 4.0 : login successful
Glassfish 4.1.1./Payara : login fail

## Steps to reproduce (Only for bug reports) 

1 -** Run web application on Payara web server from Netbeans

2 -**  Try login 
username: test
password: 1234

## Environment ##

- **Payara Version**:  <Payara Server 164 Full>
- **Edition**: <Full>
- **JDK Version**: < jdk1.8.0_101 oracle>
- **Operating System**: <Windows 7 professional>
- **IDE **: < Netbeans 8.2>

**Comment by smillidge** [comment]
You need to provide more information such as which database you are using and any error messages you receive. You also haven't provided how the web application is configured to use the roles etc. what role mapping you are doing in your glassfish-web.xml

I just set up a jdbcRealm using MySQL as the user database and did not experience a problem. See my file;
```xml
        <auth-realm name="AuthRealm" classname="com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm">
          <property name="jaas-context" value="jdbcRealm"></property>
          <property name="password-column" value="password"></property>
          <property name="datasource-jndi" value="jdbc/AuthDB"></property>
          <property name="group-table" value="auth_database.groups"></property>
          <property name="user-table" value="auth_database.users"></property>
          <property name="group-name-column" value="groupname"></property>
          <property name="digestrealm-password-enc-algorithm" value="SHA-256"></property>
          <property name="group-table-user-name-column" value="username"></property>
          <property name="digest-algorithm" value="SHA-256"></property>
          <property name="user-name-column" value="username"></property>
        </auth-realm>
```

And the web.xml
```xml
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_3_1.xsd"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
    
    <welcome-file-list>
        <welcome-file>index.xhtml</welcome-file>
    </welcome-file-list>
    
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>main</web-resource-name>
            <url-pattern>/auth/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>AUTHENTICATED_USERS</role-name>
        </auth-constraint>
    </security-constraint>
    <security-role>
        <role-name>AUTHENTICATED_USERS</role-name>
    </security-role>
    <login-config>
        <auth-method>BASIC</auth-method>
        <realm-name>AuthRealm</realm-name>
    </login-config>
</web-app>
```

The insert SQL was
```sql
insert into users values('steve',sha2('password',256));
insert into groups values ('steve','AUTHENTICATED_USERS')
```

**Comment by kahlon1005** [comment]
Thanks a lot, the problem was I copy-pasted the JDBC resource from glassfish 4.0 to 4.1.1. which failed because when JDBC resource is created from command line or admin console JDBC resource reference is also created, untill which the JDBC is not active. 

In order to resolve it I created the JDBC resource from the command line and it worked.   

this was missing in domain.xml
<resource-ref ref="jdbc/AuthDB"></resource-ref>

**Comment by Ignaciofincatti** [comment]
hello good, perform the realm as you detailed, and yet I can not make it work in Payara Server 4.1.2.174 the ma the following error

WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for nacho.

Below I detail my code
web.xml
`<context-param>
        <param-name>javax.faces.PROJECT_STAGE</param-name>
        <param-value>Development</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
    <session-config>
        <session-timeout>
            30
        </session-timeout>
    </session-config>
    <security-constraint>
        <display-name>admin</display-name>
        <web-resource-collection>
            <web-resource-name>admin</web-resource-name>
            <description/>
            <url-pattern>/protected/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <description/>
            <role-name>admin</role-name>
        </auth-constraint>
        <user-data-constraint>
            <transport-guarantee>NONE</transport-guarantee>
        </user-data-constraint>
    </security-constraint>
    <login-config>
        <auth-method>FORM</auth-method>
        <realm-name>GuiasRealm</realm-name>
        <form-login-config>
            <form-login-page>/login.xhtml</form-login-page>
            <form-error-page>/error.xhtml</form-error-page>
        </form-login-config>
    </login-config>
    <security-role>
        <description>Admin</description>
        <role-name>admin</role-name>
    </security-role>`

glassfish-web.xml
`<glassfish-web-app error-url="">
  <parameter-encoding default-charset="UTF-8"/>
  <security-role-mapping>
    <role-name>admin</role-name>
    <group-name>admin</group-name>
  </security-role-mapping>
  <class-loader delegate="true"/>
  <jsp-config>
    <property name="keepgenerated" value="true">
      <description>Keep a copy of the generated servlet class' java code.</description>
    </property>
  </jsp-config>
</glassfish-web-app>`

realm
`       <auth-realm classname="com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm" name="GuiaRealm">
          <property name="jaas-context" value="jdbcRealm"></property>
          <property name="password-column" value="password"></property>
          <property name="datasource-jndi" value="jdbc/guiasRentas"></property>
          <property name="group-table" value="guia.guiaseg_grupo"></property>
          <property name="user-table" value="guia.guiaseg_usuarios"></property>
          <property name="group-name-column" value="groupname"></property>
          <property name="digestrealm-password-enc-algorithm" value="SHA-256"></property>
          <property name="group-table-user-name-column" value="username"></property>
          <property name="digest-algorithm" value="SHA-256"></property>
          <property name="user-name-column" value="username"></property>
        </auth-realm>`

I could see that in the glassfish-web.xml from the visual part, nome finishes closing the icon of the role mapping, maybe it has something to do for lack of some configuration?
