### ISSUE TITLE
'Application Name' with space or accent marked character

### ISSUE THREAD

**Issue by hrotkogabor** [payara/Payara#1193]
# Description #
----------
When I deploy a war application, and the 'Application Name' contains space or accent marked characters, the deployment will fail, with this short message in the server log:
[Payara 4.1] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=43 _ThreadName=admin-thread-pool(1)] [timeMillis: 1479587901524] [levelValue: 800] [[
  Exception Occurred :Error occurred during deployment: null. Please see server.log for more details.]]

## Expected Outcome

The apllication should be deployed without an error, e.g.:
myApp was successfully deployed in xxx milliseconds.

## Current Outcome

Exception Occurred :Error occurred during deployment: null. Please see server.log for more details

## Steps to reproduce (Only for bug reports) 

Deploy a war app from the admin gui. At 'Application Name' enter: 'myApp 01'.
After clicking OK, the gui also displays: 'An error has occurred
Error occurred during deployment: null. Please see server.log for more details. '

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: oracle 1.8.0_111
- **Operating System**: ubuntu 14.04

**Comment by mikecroft** [comment]
Confirmed the bug; I've created internal issue `PAYARA-1234` for this.

**Comment by smillidge** [comment]
This is actually a bug in the error message. 

The error message should be 
```java
Exception Occurred :Error occurred during deployment: Constraints for this ApplicationRef configuration have been violated: on property [ ref ] violation reason [ Invalid application name. The name must start with a letter, number or underscore and may contain only letters, numbers, and these characters: hyphen, period, underscore, slash, colon, hash, and semicolon. ]. Please see server.log for more details.|#]
```

The application name must meet the following RegExp
```
"[\\p{L}\\p{N}_][\\p{L}\\p{N}\\-_\\./;:#]*"
```
