### ISSUE TITLE
pooling of External JNDI Resources of payara 

### ISSUE THREAD

**Issue by jmegha27** [payara/Payara#1197]
# Description #
Hi

How to do the connection pooling of external JNDI resources in payara server
does it come under ejb pooling?
can we do it as we do the settings for jdbc connection pooling?

# Environment #

- Payara Version: 4.1.1.x
- JDK Version: 8 
- Operating System: Windows

**Comment by mikecroft** [comment]
Can you give a few more details on your scenario? How are you trying to achieve this and with what?

**Comment by mikecroft** [comment]
Can you give an update on what you're trying to do here? What do you mean by external resources, specifically?

**Comment by mikecroft** [comment]
Closing since we don't have enough information to help. Feel free to reopen with some more details.
