### ISSUE TITLE
WebSockets with Hazelcast Cluster

### ISSUE THREAD

**Issue by stePrime** [payara/Payara#1198]
Hi Team,

I implemented a cluster with 3 Nodes (A, B & C) as Standalone Instances. 
I use HAproxy as load balancer and everything works fine.

I added WebSockets in my project and HAProxy switches automatically from HTTP to tunnel mode when the client request a websocket.

My problem is this : 
I need to retrieve websocket session regardless of connected node. For example: 
"I have 3 users connected to application. User 1 and User 2 are connected to the Node A. User 3 is 
connected to the Node B. An event occurs on the Node C  that requires user 1 and 3 to be notified. But I haven't on the Node C User 1 and User 2 sessions."

I tried to use a Hazelcast distributed List to store sessions at the User connection (OnOpen method). But when I called "add" method on the list, this throws a HazelcastSerializationException because Tyrus Session Object isn't Serializable.

How can I resolve my problem?

Thanks 

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8  - Oracle
- **Operating System**:  Linux

**Comment by smillidge** [comment]
You need to setup some distributed event between the nodes in the cluster. If you are on micro you could use the ClusteredCDIEvents. As you are not on Micro you could use some Payara Specific apis to generate a lightweight event. Or you could use lightweight Hazelcast topic listener. 

If you take the Hazelcast api approach you can use code like;

```java
@ApplicationScoped
Sender {
  @Inject HazelcastInstance hazelcast;

public void sendMessage(String message) {
  hazelcast.getTopic("notification").publish(message);
}
}
```

On the receiver
```java
@ApplicationScoped
Receiver implements MessageListener<String> {
   @Inject HazelcastInstance hazelcast;

  @Postconstruct
   public void postConstruct() {
       hazelcast.getTopic("notification").addMessageListener(this);
   }

@Override
  public void onMessage(Message<String> message) {
    System.out.println("Got message " + message);
  }
}
```

Please note I haven't compiled or tested this code and it is just an example to think about. Also it would be best not to use a class from your application to send as a message as you will likely run into classloader issues. 

Another more JavaEE alternative is to use a JMS topic which all the nodes listen to.

**Comment by smillidge** [comment]
Information on ClusteredCDI Events is below. Note: This is only in Micro until the 171 release where it will also be in Full Server. The clustered cdi events capability uses the underlying hazelcast api roughly in the way described. 

http://blog.payara.fish/microservice-choreography-with-the-payara-micro-clustered-cdi-event-bus 
https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/cdi-clustered-events 
http://blog.payara.fish/piyara-payara-micro-on-raspberry-pi-demo 

Take a look at https://github.com/payara/Payara/blob/master/appserver/extras/payara-micro/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/ClusteredCDIEventBus.java which is the implementation of the ClusteredCDIEventBus.

**Comment by stePrime** [comment]
After several tests, Hazelcast Topic seems work fine. I close the issue. 
Thank you for the support.

**Comment by lucianovct** [comment]
Can post the solution to the same problem
