### ISSUE TITLE
Plugin to analize/make statistics of webapp using (actual and historical)

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1201]
Hi,

I would like to know if there is something like this, or ideas for the future, to include a plugin to analize:
1) Actual users using the webapp at this moment (like browser users that communicated to the server in the last few seconds)
2) Reports/statistics/graphs to see: users, IPs, browsers, etc that acessed the webapp in a period of time (last hours, days, months, etc), where it would be possible to analyze all the webapp and a finer granularity of individual pages (index.jsf, menu.jsf, page1.jsf, page2.jsf, etc).
3) how many time each user, IP, browser stay using the webapp in a period of time. For example, the user1 interact to the webapp 36 hours/month, something like this.

**Comment by lprimak** [comment]
Would google analytics fit your bill?

**Comment by edilmar** [comment]
@lprimak no because I have a system with complex security to acess internal pages (page1, page2, etc). Google just gets access to index.

**Comment by lprimak** [comment]
@edilmar I have developed numerous web sites with google analytics that had secure pages counted there.  I would suggest another look, as it works with all types of secure pages.  They have a script that you can put on any page that will make it participate in google analytics.  This is the most advanced tool that I know for this kind of stuff.

**Comment by lprimak** [comment]
@edilmar have you tried google analytics, I think it will satisfy your need

**Comment by edilmar** [comment]
I will try some internal way for this.
Google Analytics doesnt get to process internal pages after user is logged.

**Comment by lprimak** [comment]
@edilmar I have personally used google analytics to analyze logged-in users.
You just need to insert the javascript piece that they provide on all your pages
