### ISSUE TITLE
Payara 164, javax.naming.NamingException

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#1202]
Hi there,
after migration from payara 161 to 164, my application gets an error during startup. This is the exception message:

`javax.naming.NamingException: Lookup failed for 'java:global/RedevoServer-ejb/MatchListsCleaner!it.redevogames.redevoserver.classes.timers.MatchListsCleaner' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.osjava.jndi.root=classpath://config, org.osjava.jndi.delimiter=/, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: MatchListsCleaner!it.redevogames.redevoserver.classes.timers.MatchListsCleaner not found]`

The code are causing this exception is:

`return (MatchListsCleaner) c.lookup("java:global/RedevoServer-ejb/MatchListsCleaner!it.redevogames.redevoserver.classes.timers.MatchListsCleaner");`

The file MatchListsCleaner.java is present in package it.redevogames.redevoserver.classes.timers.MatchListsCleaner.

There was someting different in naming convention between 161 and 164 versions?

Can you help me, please?

Thanks in advance.

Mephysto

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: 8 u121 - Oracle
- **Operating System**: Windows

**Comment by smillidge** [comment]
I'm not aware of any changes in this area of the code. When you deployed did it log the EJB name as you would expect?

**Comment by Mephysto666** [comment]
I am sorry. I forgot to close this issue because it's only a false alarm.

Please accept my apologies.

Best regards.

Meph
