### ISSUE TITLE
provide non-fatjar maven dependency

### ISSUE THREAD

**Issue by thomas-andres** [payara/Payara#1206]
Feature Request:

As far as I can see, you can currently get fat jars (payara-embedded-all, payara-web-all, payara-microprofile) of of payara and a distribution zip. But you can't get a dependency to parts of the server like you can for glassfish like e.g. 'org.glassfish.main.ejb:ejb-container:jar:4.1.1' that contains the ejb-container and also describes the used dependencies.
Having smaller parts as dependency also allows more fain grained control over what dependency to include for the build and what to exclude.
I recently tried to migrate this dependency to the payara server we use and ran into problems with test code that starts up a weld container, cause the payara-embedded-all brings along a lot more than the previous glassfish dependency.

**Comment by fturizo** [comment]
There's a new Payara Public API that has been released from version _4.1.1.171_. Official documentation for this API can be found [here](https://docs.payara.fish/documentation/extended-documentation/app-deployment/public-api.html).
