### ISSUE TITLE
Session Object replication with session.setAttribute

### ISSUE THREAD

**Issue by stePrime** [payara/Payara#1227]
# Description #
----------

Hi Team,

I have a Cluster as Standalone Instances with Hazelcast, I added a Session Replication and a Load Balancer with HAProxy. Everything works fine. 

When I use a Session Bean all global variables are replicated to the nodes of the cluster but when I try to share an object in a no-SessionBean a few times it doesn't work.  
This below is my simple example:

I have a simple page that retrieve 2 list of "String" (Hazelcast Distributed List and Session List):

![page](https://cloud.githubusercontent.com/assets/12546042/21108034/ef0d99dc-c093-11e6-8649-593f693d8220.PNG)

The Bean behind the page has a custom scope.

```java
    @Named
    @RomeoScoped  //this is my custom scope
    public class RomeoBean implements Serializable {
```

The "increase" method is called when I click on the "add" button:

```java
    public void increase(){
        FacesContext currentInstance = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) currentInstance.getExternalContext().getRequest();
        HttpSession session = request.getSession();
        
        String example  = Math.random() + "";
        
        if(session != null){
             CopyOnWriteArrayList<String> list = (CopyOnWriteArrayList<String>) session.getAttribute("List");
             list.add(example);
             session.setAttribute("List", list);
        }
        
        try {
            Context ctx = new InitialContext();
            HazelcastInstance instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
            IList<String> list = instance.getList("list");
            list.add(example);
        } catch (NamingException ex) {
            Logger.getLogger(RomeoBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
```

After 4 clicks on the button, the situazione is this:

![cattura](https://cloud.githubusercontent.com/assets/12546042/21108941/418a0dd2-c097-11e6-982d-e49398c28a9d.PNG)

Only 2 Strings are shared in Session List, while all Strings with Hazelcast. 
I need to use my custom scope and in same case the objects must be shared only in the session and not in application (as Hazelcast Distributed List).

Can I fix the problem with "setAttribute" method?

Thanks in advance for the support.

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8  - Oracle
- **Operating System**:  Linux

**Comment by OndrejM** [comment]
Have you tried debugging if you always go in the block in `if(session != null){` - that means, do you always have session? It seems that out of 4 clicks, only 2 times you have session and 2 times the session is null.

How is your custom scope working? When does it start and when does it end?

**Comment by OndrejM** [comment]
Can you attach your simple application so that I may try to reproduce the problem?

**Comment by OndrejM** [comment]
Have you added the `<distributable/>` element into the `web.xml`? Like here: [JBoss Clustering Guide] (https://docs.jboss.org/jbossas/docs/Clustering_Guide/beta422/html/clustering-http-app.html)

You also need to configure Web Container availability with Hazelcast. See this blog post about [Payara clustering with Hazelcast](http://blog.payara.fish/creating-a-simple-cluster-with-payara-server)

**Comment by lprimak** [comment]
Have you, by any chance deploying the app itself without availability enabled?
i.e. you need to use
`asadmin deploy --availabilityenabled`

Also, make sure you have this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app error-url="">
  <session-config>
    <session-manager persistence-type="hazelcast">
      <manager-properties>
        <property name="relaxCacheVersionSemantics" value="true"/>
      </manager-properties>
    </session-manager>
  </session-config>
</glassfish-web-app>
```

as described here:
http://blog.payara.fish/payara-server-rolling-upgrades

**Comment by stePrime** [comment]
I have same problem with Application,Session or Request Scope (I use CDI).

web.xml:

`

    <?xml version="1.0" encoding="UTF-8"?>
    <web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
        <distributable/>
        <context-param>
            <param-name>javax.faces.PROJECT_STAGE</param-name>
            <param-value>Development</param-value>
        </context-param>
        <servlet>
            <servlet-name>Faces Servlet</servlet-name>
            <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
            <load-on-startup>1</load-on-startup>
        </servlet>
        <session-config>
            <session-timeout>
                30
            </session-timeout>
        </session-config>
        <env-entry>
            <env-entry-name>jsf/ClientSideSecretKey</env-entry-name>
            <env-entry-type>java.lang.String</env-entry-type>
            <env-entry-value>OaHMhbhnoH7qZYA/AmGEBg==</env-entry-value>
        </env-entry>
        <context-param>
            <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
            <param-value>client</param-value>
        </context-param>
        <servlet-mapping>
            <servlet-name>Faces Servlet</servlet-name>
            <url-pattern>*.jsf</url-pattern>
        </servlet-mapping>
        <servlet-mapping>
            <servlet-name>Faces Servlet</servlet-name>
            <url-pattern>*.xhtml</url-pattern>
        </servlet-mapping>
        <welcome-file-list>
            <welcome-file>index.xhtml</welcome-file>
        </welcome-file-list>
    </web-app>

`
My Cluster has 3 Nodes named: n1.test.com, n2.test.com, n3.test.com.
glassfish-web.xml :

`

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
    <glassfish-web-app error-url="">
      <class-loader delegate="true"/>
      <jsp-config>
        <property name="keepgenerated" value="true">
          <description>Keep a copy of the generated servlet class' java code.</description>
        </property>
      </jsp-config>
      <session-config>
            <cookie-properties>
                <property name="cookieDomain" value="test.com"/>
            </cookie-properties>
            <session-manager persistence-type="hazelcast"> 
                <manager-properties>
                    <property name="relaxCacheVersionSemantics" value="true"/>
                </manager-properties> 
            </session-manager> 
        </session-config>
    </glassfish-web-app>

`

I have availability enabled

![av](https://cloud.githubusercontent.com/assets/12546042/21177940/89fb2d74-c1ed-11e6-8500-14ec8d73a63c.PNG)


You can retrieve my simple app [here](http://37.187.170.237:8080/ww/SimpleTest.zip).

**Comment by stePrime** [comment]
The problem occurs also if I don't use setAttribute but with a List as global variable in a Session Bean.

I replaced "TestBean" with this "SessionBean" ,but the problem is the same:

`

    @Named
    @SessionScoped
    public class SessionBean implements Serializable {

        private CopyOnWriteArrayList<String> lista;

        @PostConstruct
        public void init() {
            System.out.println("INIT SESSIONBEAN!!!!");
            if (lista == null) {
                lista = new CopyOnWriteArrayList<>();
            }
        }

        public void increase() {
            String example = Math.random() + "";
            lista.add(example);
        
            try {
                Context ctx = new InitialContext();
                HazelcastInstance instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
                IList<String> list = instance.getList("list");
                list.add(example);
            } catch (NamingException ex) {
                Logger.getLogger(TestBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        public void decrease() {
            if (lista != null && lista.size() > 0) {
                lista.remove(0);
            }
        
            try {
                Context ctx = new InitialContext();
                HazelcastInstance instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
                IList<String> list = instance.getList("list");
                if(list != null && list.size() > 0){
                    list.remove(0);
                }
            } catch (NamingException ex) {
                Logger.getLogger(TestBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
        public List<String> getHazelcastList() {
            List<String> lista = null;
            try {
                Context ctx = new InitialContext();
                HazelcastInstance instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
                lista = instance.getList("list");

            } catch (NamingException ex) {
                Logger.getLogger(TestBean.class.getName()).log(Level.SEVERE, null, ex);
            }
            return lista;
        }

        public CopyOnWriteArrayList<String> getLista() {
            return lista;
        }
    
        public String getSessionID() {
            FacesContext currentInstance = FacesContext.getCurrentInstance();
            ExternalContext externalContext = currentInstance.getExternalContext();
            HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
            HttpSession httpSession = request.getSession();
            return httpSession.getId();
        }

        public String getInstance() {
            try {
                String property = System.getProperty("com.sun.aas.instanceName");
                String hostName = java.net.InetAddress.getLocalHost().getHostName();
                return " " + property + ", " + hostName;
            } catch (UnknownHostException ex) {
                Logger.getLogger(TestBean.class.getName()).log(Level.SEVERE, null, ex);
                return "Error";
            }
        }

    }


`

**Comment by OndrejM** [comment]
I'll try to reproduce with the your app. Meantime, can you check how your requests are routed from the load balancer? I suspect that the session replication does not work and that each application has access only to the data it created. Can you check which nodes received which requests? If you connect directly to each node, can you see all expected strings on one or the other node?

**Comment by stePrime** [comment]
I tried to connect to each node and it seems to work (only string is replicated on all nodes). It can be a problem with a Load Balancer. Now, I try to check a requests from a Load Balancer.
 Do you use HAProxy?

**Comment by stePrime** [comment]
HAProxy is configured with sticky session:

`

     backend payara_cluster_nodes
             # balance with roundrobin
             balance roundrobin
	         cookie JSESSIONID nocache prefix
	         option httpchk
             # define backend servers
             server             n1.test.com 10.0.0.166:28080 check cookie n1
	         server             n3.test.com 10.0.0.107:28080 check cookie n3
	         server             n4.test.com 10.0.0.195:28080 check cookie n4

`
 
At the first response, the server will send the client the following header (i.e.):

    JSESSIONID=66fe5af202b0636ab6ce55c904c7

The cookie is modified by HAProxy like this:

    JSESSIONID=n1~66fe5af202b0636ab6ce55c904c7

Each following requests by this user is routed to server N1. 
The problem begins if I put down N1, Following requests bounce between the N3 and N4 
and sometimes occurs the problem described above.

**Comment by lprimak** [comment]
Might be related to #1689 which is fixed now
