### ISSUE TITLE
Context Injection of javax.ws.rs.container.ResourceInfo get null

### ISSUE THREAD

**Issue by harf18** [payara/Payara#1248]
# Description #
----------

```
@Provider
@Priority(Priorities.AUTHENTICATION)
public class JWTAuthFilter implements ContainerRequestFilter {

    @Context
    private ResourceInfo resourceInfo;
    ...
}
```

This code inject a "org.glassfish.jersey.server.internal.routing.UriRoutingContext" on Payara 4.1.1.163 Full but null on Payara 4.1.1.164 Full

I didn't change anything in my project.
I download payara 4.1.1.164, unzip it, create a domain (same name) and copy/past the domain.xml from payara 4.1.1.163 config folder to 4.1.1.163.
 

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: 8u111
- **Operating System**: Windows

**Comment by mikecroft** [comment]
Can you be a bit more descriptive? What do you expect to happen and what actually happens? What is the error from the logs?

**Comment by harf18** [comment]
Of course... sorry
All my REST methods are annotated with customs annotations to provide security mechanism.
So, in this filter, I inject a ResourceInfo to get the present annotations on method which is called.

I have 2 endpoint (/internal & /external)

After your remark, i noticed that it's ok on external endpoint, but, i have the issue on internal endpoint with in log file :

> [2016-12-20T11:05:25.867+0100] [Payara 4.1] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=97 _ThreadName=admin-thread-pool(2)] [timeMillis: 1482228325867] [levelValue: 900] [[
  The following warnings have been detected: WARNING: Cannot create new registration for component type class com.fasterxml.jackson.jaxrs.base.JsonParseExceptionMapper: Existing previous registration found for the type.
WARNING: Cannot create new registration for component type class com.fasterxml.jackson.jaxrs.base.JsonMappingExceptionMapper: Existing previous registration found for the type.
]]

**Comment by mikecroft** [comment]
Thanks for the update! That's interesting...is your code available on GitHub? I'd be interested to try and reproduce this

**Comment by harf18** [comment]
No sorry. My code is on a private repo.

**Comment by mikecroft** [comment]
Do you have a simple test case that we could use to reproduce it?

**Comment by mikecroft** [comment]
sscce.org

**Comment by harf18** [comment]
Can't reproduce with this https://github.com/harf18/test-payara-164

May be a dependencies conflict...

Sorry, you can close. 

It still does not work on my main projet, but i merged my 2 endpoints in one and it's going on.

**Comment by mikecroft** [comment]
OK, well I'll close it for now....if you find you can reproduce it, please come back and reopen this! We'll be more than happy to take a look.
