### ISSUE TITLE
Overriding ConstraintViolationException as application exception fails in case of using bean validation annotation on method parameters

### ISSUE THREAD

**Issue by PaulWasilewski** [payara/Payara#1250]
# Description #
----------
I have tried to define the `ConstraintViolationException` as application exception in the `ejb-jar.xml`. Unfortunately, the `ConstraintViolationException` is still fired as system exception, when constraint annotation (bean validation) on method parameters is used.

## Expected Outcome

`ConstraintViolationException` should be an application exception.

## Current Outcome

`ConstraintViolationException` is a system exception.

## Steps to reproduce (Only for bug reports) 

1. Define a pojo with constraint annotation.
```
public class Data implements Serializable {
      private static final long serialVersionUID = 8746899724972619830L;
      @NotNull
      private String text;
}
```
2. Define a business remote interface with constraint annotation.
```
@Remote
public interface IRemoteService {
	public void validate(@Valid Data data);
}
```
3. Implement the remote service
```
@Remote
public class RemoteService implements IRemoteService{
	//will throw an ConstraintViolationException if data is not valid
        public void validate(@Valid Data data) {
        }
}
```
4. Define `ConstraintViolationException` as application exception in `ejb-jar.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<ejb-jar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/ejb-jar_3_2.xsd"
	version="3.2">
	<assembly-descriptor>
		<application-exception>
			<exception-class>javax.validation.ConstraintViolationException</exception-class>
			<rollback>true</rollback>
		</application-exception>
	</assembly-descriptor>
</ejb-jar>
```
5. Deploy the service as ejb.

6. Call the remote business interface with an invalid `Data` instance
```
public class RemoteClient {
	public static void main(final String[] args) throws NamingException {
		final Properties props = new Properties();
		props.setProperty("java.naming.factory.initial", "com.sun.enterprise.naming.SerialInitContextFactory");
		props.setProperty("java.naming.factory.url.pkgs", "com.sun.enterprise.naming");
		props.setProperty("java.naming.factory.state", "com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl");
		props.setProperty("org.omg.CORBA.ORBInitialHost", "localhost");

		final InitialContext ctx = new InitialContext(props);
		//jndi name has to be adjusted
                final IRemoteService remoteService = (IRemoteService) ctx
				.lookup("java:global/exploration-ejb/RemoteService!com.examples.IRemoteService");
		final Data data = new Data();
		try {
			remoteService.validate(data);
		} catch (final Exception e) {
			System.out.println(e);
		}
	}
}
```
## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8 u51 - Oracle
- **Operating System**: Windows

**Comment by fturizo** [comment]
Hi @PaulWasilewski, I tested this configuration with some sample applications and your settings are correct. In my test samples when executing the remote business method, the exception thrown out by the EJB container is an **application exception**, whilst if I commented the code on the _ejb-jar.xml_ file, the exception thrown is indeed a **system exception** (logged out by the container, wrapped in a `javax.ejb.EJBException` object). 

What assembly configuration are you using for your application? **WAR**, **EJB-JAR**, **EAR**? Check the location of the _ejb-jar.xml_ deployment descriptor seems the EJB container is not applying the declared configuration.

**Comment by PaulWasilewski** [comment]
I tried EAR and EJB. In both cases I have placed the ejb-jar.xml in the resources folder. 

I also have tested firing the ConstraintVialotionException by myself inside a remote method with throw new ...  then the ConstraintVialotionException was indeed handled as application exception but not when I am using annotations on my method like shown in the example.

**Comment by fturizo** [comment]
@PaulWasilewski, I updated the test case again with both an **EJB-JAR** and **EAR** assemblies and still had no problems getting the **ConstraintViolationException** to work as an **application exception** following the described steps on Payara Server 4.1.1.163. How are you detecting that the exception is handled as a system exception? 

If possible also, try to upload a **[SSCCE](http://sscce.org/)** sample to Github  so we can have a closer look at the possible cause.

**Comment by fturizo** [comment]
@PaulWasilewski , had you had the chance to create a sample reproducer project for this issue? Let us know any progress made on it.

**Comment by fturizo** [comment]
Greetings @PaulWasilewski, had any luck with a sample reproducer for the issue?

**Comment by PaulWasilewski** [comment]
Hi @fturizo, sorry for my late response. The defintion of system exception as application exceptions works as expected. 

The cause of the problem is the missing serialization support of `ConstraintViolationException` and this raises a new system exception. Thanks, for taking care.
