### ISSUE TITLE
if EntityManager.flush() is manually called inside a CMT (JTA) transaction, the DB commits the changes

### ISSUE THREAD

**Issue by siaspa** [payara/Payara#1259]
It seems that the DB transaction is not well synchronized with the Container Managed Transaction
----------

EntityManager.flush() should live inside the JTA transaction. What happens is that the statements are physically commited on flush(). 

I described this on StackOverflow
http://stackoverflow.com/questions/41265662/cant-join-jdbc-transaction-with-jta-transaction-with-hibernate-4-hibernate-5-on

When I posted the question I didn't know about Payara. Yesterday I found it and I tried the example (a maven project is in the zip file attached)

It happens with Payara 4.1 or GlassFish 4.1 with Hibernate 4 or 5. 
It didn't happen with GlassFish 3 with Hibernate 3. 
It didn't happen with WildFly 9 with Hibernate 4 or 5. 

So, as far as I know, the problem can be:
1 - In the Hibernate Classes related to Payara
2 - In Payara classes involved in flush() 

To reproduce the error, I wrote a small example that demonstrates it. There's a TestClient class to test 
[hib-project.zip](https://github.com/payara/Payara/files/678491/hib-project.zip)
the behaviour I described.  

There are four constants to set if and when the setRollbackOnly method will be called, but the problem is visible even whitout the call.
 
 The zip file contains a xls file that summarize the test I've done
 
 Any ideas?
 
 Thanks in advance,
 David Obber

**Comment by mikecroft** [comment]
It is my understanding that this would be expected behaviour if your database was running something like autocommit in Derby. em.flush() is supposed to propagate the transaction to the DB.

**Comment by siaspa** [comment]
I agree. em.flush() should propagate the transaction to the DB. The SQL statements(INSERT/UPDATE…) are sent to the database.
It must not commit the DB transaction if it is contained in a CMT transaction.

It’s the CMT transaction commit that has the responsibility to commit the DB transaction.
I tried to set autocommit = false explicitally, same result.

I’m working with Oracle X/XI

David

**Comment by michaelranaldo** [comment]
Hi @siaspa,

We've had a few problems getting the attached test case working. 
There seems to be a number of unrelated dependencies within the files.

Have you made any progress yourself?

**Comment by siaspa** [comment]
Hi Michael,

I’m glad that you started watching my issue.
Unfortunately I didn’t find anything else.
What kind of problems did you have with the project? Maybe I can fix them or I can help you to set it up.
I built it just using the maven remote repository. What do you mean with “unrelated dependencies”?


Thank you,
David Obber

**Comment by siaspa** [comment]
Hi Micheal, did you compile the project? 
1 - The test case is in the web\src\test\java\com\sia\TestClient.java source.
2 - ejb\src\main\resources\META-INF\persistence.xml  should be changed according to your domain.xml 
<jta-data-source>{your datasource JNDI}</jta-data-source>
3 - The rest of persistence.xml should be ok if you're using Oracle.
4 - The statements.sql file contains the statements to create the table used in the example 

Let me know if you need more informations.

David Obber

**Comment by siaspa** [comment]
Hi Micheal, any news?
Thank you,
David

**Comment by michaelranaldo** [comment]
Hi David,

Sorry for the delay, 

I am still getting an issue I had before where Payara doesn't recognise the datasource as a valid resource. Was this something which you had encountered?

**Comment by siaspa** [comment]
Hi Micheal,

you should add a datasource named dsARAG in your domain XML as follows:


<resources>
...
    <jdbc-connection-pool datasource-classname="oracle.jdbc.pool.OracleDataSource" res-type="javax.sql.DataSource" steady-pool-size="4" name="aragSvilPool">
      <property name="URL" value="jdbc:oracle:thin:@193.43.48.188:1521:ORCL"></property>
      <property name="Password" value="S1A5P496LUNTIROLER"></property>
      <property name="User" value="TIROLER"></property>
    </jdbc-connection-pool>

    <jdbc-resource pool-name="aragSvilPool" jndi-name="dsARAG"></jdbc-resource>
...
</resources>
<servers>
               <server name="server" config-ref="server-config">
                              ....
                              <resource-ref ref="dsARAG"></resource-ref>
                              ...
               </server>
</servers>


The URL, Password and User of "jdbc-connection-pool" node should match your DB.


The statements.sql file I attached contains the following SQL statements:
CREATE TABLE PROCESSO (
ID_PROCESSO NUMBER(10, 0) NOT NULL,
TIPO_PROCESSO VARCHAR2(7) NOT NULL,
TP_ENTITA NUMBER(5, 0) NOT NULL,
ID_ENTITA NUMBER(10, 0) NOT NULL,
PROGR NUMBER(10, 0) NOT NULL,
DT_RIFERIMENTO_ORIGINALE DATE,
STATO VARCHAR2(7),
SUBSTATO VARCHAR2(7),
FL_ATTIVO VARCHAR2(1),
DT_STATO DATE,
DESCRIZIONE VARCHAR2(100),
ID_PRC_PERIF_1 VARCHAR2(250),
ID_PRC_PERIF_2 VARCHAR2(250),
ID_PRC_PERIF_3 VARCHAR2(250),
CHIAVE_1 VARCHAR2(10)
)

ALTER TABLE PROCESSO ADD CONSTRAINT PROCESSO_PK
PRIMARY KEY (ID_PROCESSO)


Let me know if you need more information.

Thanks in advance,

David Obber

**Comment by michaelranaldo** [comment]
Hi David,
I have run through the provided test client with Payara Server 164 and Oracle Database. In every instance of the container-managed transaction being rolled back, the database was not changed; when the exception was not thrown and the transaction was not set to rollback changes were propagated to the database. As such I have been unable to yet confirm the reported bug.

**Comment by siaspa** [comment]
Hi Michael and thank you.

This is interesting. Could you please send me a txt file list of the jars and if, possible, the domain.xml part in which you’ve defined the oracle connection? In this way I can check if there are some different versions of jdbc related jars.

Here the test fails with the same version of Payara Server (164).

Just to be sure, did you change anything in the project (persistence.xml, annotations)?
Which version of ojdbc.jar did you use? (21/03/2013  13:26        1.988.051 ojdbc6.jar)


David

**Comment by michaelranaldo** [comment]
Certainly; ojdbc6.jar was added to the lib directory to interface with the docker Oracle Database 11g image. 

A JDBC connection pool defined by:

    <jdbc-connection-pool datasource-classname="oracle.jdbc.pool.OracleDataSource" name="dsARAG" res-type="javax.sql.DataSource">
      <property name="user" value="system"></property>
      <property name="url" value="jdbc:oracle:thin:@localhost:49161:XE"></property>
      <property name="password" value="oracle"></property>
    </jdbc-connection-pool>

was added to Payara Server via the console.

The persistence.xml was changed from <property name="hibernate.hbm2ddl.auto" value="none"/> to <property name="hibernate.hbm2ddl.auto" value="create-drop"/> to avoid a persistent deployment issue.

This was all on hibernate 4 as deploying with hibernate 5 seemed to cause an unrelated issue. No extra jar files were added to Payara.

Was this similar to your own environment or were there changes I need to make?

**Comment by siaspa** [comment]
It’s exactly the same environment.  I’m not using the XE version of Oracle 11, but is still Oracle Database  11.
I’m working on Windows 7: do you use Ubuntu? Does it matter?

What changes did you make to persistence.xml?
Do you think it could be an oracle database configuration issue?

David

**Comment by michaelranaldo** [comment]
Only that single line change I believe:

<?xml version="1.0" encoding="UTF-8"?>
<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
  
  <persistence-unit name="test_pu" transaction-type="JTA">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <jta-data-source>jdbc/dsARAG</jta-data-source>
    <properties>
      <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.format_sql" value="false"/>
      <property name="hibernate.use_sql_comments" value="false"/>
      <property name="hibernate.generate_statistics" value="false"/>
      <property name="hibernate.ejb.metamodel.generation" value="disabled"/>
      <property name="hibernate.connection.release_mode" value="after_transaction"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
      <property name="hibernate.transaction.jta.platform" value="${jta.platform}"/>
    </properties>
  </persistence-unit>
</persistence>


I am using Debian, but I don't think that should cause any drastic changes...
Have you made any notable changes to your oracle database configuration?

It may be worth looking at your operations - if you are making minimal use of Hibernate specific features Payara Server does work better with eclipselink, though I appreciate that may be a pain to configure.

**Comment by michaelranaldo** [comment]
Only that single line change I believe:

<?xml version="1.0" encoding="UTF-8"?>
<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
  
  <persistence-unit name="test_pu" transaction-type="JTA">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <jta-data-source>jdbc/dsARAG</jta-data-source>
    <properties>
      <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.format_sql" value="false"/>
      <property name="hibernate.use_sql_comments" value="false"/>
      <property name="hibernate.generate_statistics" value="false"/>
      <property name="hibernate.ejb.metamodel.generation" value="disabled"/>
      <property name="hibernate.connection.release_mode" value="after_transaction"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
      <property name="hibernate.transaction.jta.platform" value="${jta.platform}"/>
    </properties>
  </persistence-unit>
</persistence>


If you are making minimal use of Hibernate specific features it may be worth trying your program with Eclipselink, which should provide the same base functionality.

Otherwise it may be worth having a look at your database configuration to double check whether or not you have made any changes from the default behaviour?

**Comment by michaelranaldo** [comment]
Only that single line change I believe - 

<?xml version="1.0" encoding="UTF-8"?>
<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
  
  <persistence-unit name="test_pu" transaction-type="JTA">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <jta-data-source>jdbc/dsARAG</jta-data-source>
    <properties>
      <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.format_sql" value="false"/>
      <property name="hibernate.use_sql_comments" value="false"/>
      <property name="hibernate.generate_statistics" value="false"/>
      <property name="hibernate.ejb.metamodel.generation" value="disabled"/>
      <property name="hibernate.connection.release_mode" value="after_transaction"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
      <property name="hibernate.transaction.jta.platform" value="${jta.platform}"/>
    </properties>
  </persistence-unit>
</persistence>


If you are making minimal use of Hibernate specific features it may be worth trying your program with Eclipselink, which should provide the same base functionality.

Otherwise it may be worth having a look at your database configuration to double check whether or not you have made any changes from the default behaviour?

**Comment by michaelranaldo** [comment]
Only that single line change I believe:

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
  <!-- 
from domain.xml

    <jdbc-resource pool-name="hibTestPool" jndi-name="dsARAG"></jdbc-resource>

    <jdbc-connection-pool datasource-classname="oracle.jdbc.pool.OracleDataSource" res-type="javax.sql.DataSource" steady-pool-size="4" name="hibTestPool">
      <property name="URL" value="jdbc:oracle:thin:{your:URL}"></property>
      <property name="Password" value="{your password}"></property>
      <property name="User" value="{your userName}"></property>
    </jdbc-connection-pool>


 -->
  <persistence-unit name="test_pu" transaction-type="JTA">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <jta-data-source>jdbc/dsARAG</jta-data-source>
    <properties>
      <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.format_sql" value="false"/>
      <property name="hibernate.use_sql_comments" value="false"/>
      <property name="hibernate.generate_statistics" value="false"/>
      <property name="hibernate.ejb.metamodel.generation" value="disabled"/>
      <property name="hibernate.connection.release_mode" value="after_transaction"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
      <property name="hibernate.transaction.jta.platform" value="${jta.platform}"/>
    </properties>
  </persistence-unit>
</persistence>
```

If you are making minimal use of Hibernate specific features it may be worth trying your program with Eclipselink, which should provide the same base functionality.

Otherwise it may be worth having a look at your database configuration to double check whether or not you have made any changes from the default behaviour?

**Comment by siaspa** [comment]
My mistake! I missed the resource-ref element!
It’s not clear to me why this causes the problem, but adding it solved it.

  <servers>
    <server config-ref="server-config" name="server">
  
      <resource-ref ref="dsARAG"></resource-ref>
    </server>
  </servers>

I apologize for this inconvenient.
Thank you for your help!

**Comment by michaelranaldo** [comment]
Happy to help!
