### ISSUE TITLE
password is in clear text in JDBC Connection Pool Properties

### ISSUE THREAD

**Issue by rsingareddy** [payara/Payara#1270]
Here are steps followed
1) Checked out Payara source code from git  repository https://github.com/payara/Payara.git
2) compiled using >> mvn clean install -DskipTests
3) extracted zip from Payara\appserver\distributions\payara\target\payara.zip\
4) started domain using >> asadmin.bat start-domain
5) created JDBC Connection Pool
6) Entered password displayed in clear text

I am totally shell shocked to see password in clear text.
Thanks

Ravi

**Comment by lprimak** [comment]
Hi, Ravi,
In Payara (as in GlassFish) there is no differentiation between passwords and other properties when setting up connection pools.

Secure information (including passwords, user IDs etc) can be encrypted using password aliases.

Please see https://docs.oracle.com/cd/E19798-01/821-1751/ghgqc/index.html for documentation.
Thank you!

**Comment by rsingareddy** [comment]
Hi lprimak,
Even though there is alternative way to hide password field but system must hide password. It should be enhancement request. 
Thanks

Ravi

**Comment by lprimak** [comment]
This would be a significant departure from the way GlassFish and Payara do things currently, and would touch many major components, and in my opinion, would not cause a measurable improvement in usability.

**Comment by rsingareddy** [comment]
Application servers has to be secured in all aspects for critical applications. In this cyber attacked prone environments, who will be opening up doors for attacks?

**Comment by lprimak** [comment]
Aliases should be used for passwords, works as designed
