### ISSUE TITLE
Payara Micro Deployment Messaage

### ISSUE THREAD

**Issue by doobrie** [payara/Payara#1273]
# Description #
----------

When Payara Micro deploys archives, it displays the message:

Deployed {0} archives

irrespective of the number of archives deployed.

## Expected Outcome

When 1 archive is deployed, it should log:

Deployed 1 archive(s)

## Current Outcome

Currently Payara Micro logs:

Deployed 1 archives

## Steps to reproduce (Only for bug reports) 

This can be reproduced by deploying a single archive to Payara Micro, for example:

java -jar payara-micro.jar --deploy singleArchive.war

## Environment ##

- **Payara Version**: 4.1.1.x (4.1.1.171-SNAPSHOT)
- **Edition**: Micro
- **JDK Version**: 1.8.0_111 - Oracle
- **Operating System**: Windows

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1321` to merge the PR
