### ISSUE TITLE
Add a dedicated role to REST Monitoring APIs

### ISSUE THREAD

**Issue by thx8411** [payara/Payara#1295]
# Description #
----------

Gathering metrics from the REST Monitoring APIs requires full admin credentials. Adding a dedicated role
to these APIs would avoid to give admin credentials to external monitoring tools.

## Expected Outcome

There is many ways to do this. In my mind, the best would be to add a 'monitoring' group in the admin realm, mapped on a 'monitoring' role. The 'admin' group would still have access to the whole APIs, and the 'monitoring' group could just use GET on the monitoring APIs.

## Current Outcome

We wrote a kind of webservice proxy. 

External tools ---(Basic auth, dedicated realm, user and role)---> Proxy ---(Admin credentials)---> Payara's REST APIs

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: FULL
- **JDK Version**: 8u112 - Oracle
- **Operating System**: Linux

**Comment by fturizo** [comment]
@thx8411, thanks for proposing this enhancement request. As you mention, currently only members of the `asadmin` group in the admin-realm security have access to the **REST** API on all endpoints. 

I'll propose to the developers the creation of a separate group that can access only the `/monitoring/domain/` endpoints to raise the proper discussion about implementing this feature.

**Comment by fturizo** [comment]
Created internal JIRA issue `PAYARA-1342`

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.
