### ISSUE TITLE
payara micro docker problem

### ISSUE THREAD

**Issue by kissoid** [payara/Payara#1307]
this is not your payara micro docker image. i try to run payara-micro in a docker container. everything work normally working but, when i try to pass a external config file parameter, i see the error on console. rum command and error are below.

when i start payara micro with command:

java -DgaiaSystemId=38 -cp "/gaia_client_home/server/payara-micro.jar:/gaia_client_home/driver/mysql-connector-java-5.1.23-bin.jar" fish.payara.micro.PayaraMicro --mcAddress 224.0.0.1 --mcPort 9998 --port 8111 --deploy "/gaia_client_home/application/iwa.war" --domainConfig "/gaia_client_home/temp/38/config/microdomain.xml"  

error :
Could not rename /gaia_client_home/temp/38/config/microdomain.xml to /tmp/gfembed8137673062955676670tmp/config/domain.xml.bak

environment:
on amazon ec2  ubuntu 16.04 docker container 

- **Payara Version**: 164
- **Edition**: Micro
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
                             OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

- **Operating System**: ubuntu 16.04

**Comment by kissoid** [comment]
i thought something and i will try. if i can't, i open again.

**Comment by mikecroft** [comment]
Duplicate of a Payara Examples issue. Resolution is here for future reference:
https://github.com/payara/Payara-Examples/issues/27#issuecomment-169267613

**Comment by smillidge** [comment]
Also you can package the JDBC driver in the war file along with a datasource definition. This may remove the need for 
```shell
 -cp "/gaia_client_home/server/payara-micro.jar:/gaia_client_home/driver/mysql-connector-java-5.1.23-bin.jar
```

See https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/datasource-example
