### ISSUE TITLE
Payara/Glassfish bug

### ISSUE THREAD

**Issue by kingprimex** [payara/Payara#1334]
# Description #
----------
The issue is with servers hostname: If the hostname contains **underscore** DAS wont start remote instances.
Steps:
1. Create 2 nodes, for each server.
2. Create a cluster with 2 instances: Ex. 
hostname1: application_server1 
hostname2: application_server2
3. Try to start instances. Bug occurs

## Issue

When trying to start cluster instance which contains **underscore** in hostname server is unable to perform giving the following error:

**cli802 synchronization failed for directory config, caused by http connection failed with code 503: Service Unavailable**
## Expected Outcome
Start the instance in the cluster.

-**Payara Version**: 4.1.1.163-164
-**Edition**: FULL
-**JDK Version**:  8 u102-121 - Oracle/
-**Operating System**:  Linux - Oracle Linux Enterprise 7

**Comment by mikecroft** [comment]
What version of Payara Server are you using? Could you include more of the server log, including any stack trace from the error?

**Comment by kingprimex** [comment]
Unfortunately, I reinstalled the server and deleted all logs without taking a screenshot. I will replicate the bug again and will post as soon as I get my hands on Test Env

**Comment by mikecroft** [comment]
OK, thank you!

**Comment by mikecroft** [comment]
I don't think that this is something we can fix. From, [IETF RFC1912](https://www.ietf.org/rfc/rfc1912.txt):

>    Allowable characters in a label for a host name are only ASCII
>    letters, digits, and the `-' character.  Labels may not be all
>    numbers, but may have a leading digit  (e.g., 3com.com).  Labels must
>    end and begin only with a letter or digit.  See [RFC 1035] and [RFC
>    1123].  (Labels were initially restricted in [RFC 1035] to start with
>    a letter, and some older hosts still reportedly have problems with
>    the relaxation in [RFC 1123].)  Note there are some Internet
>    hostnames which violate this rule (411.org, 1776.com).  The presence
>    of underscores in a label is allowed in [RFC 1033], except [RFC 1033]
>    is informational only and was not defining a standard.  There is at
>    least one popular TCP/IP implementation which currently refuses to
>    talk to hosts named with underscores in them. 

Apparently this behaviour has been seen elsewhere in testing on AIX when a hostname has contained an underscore and tests have failed because of the implementation of the JDK, so this behaviour is out of our hands

**Comment by kingprimex** [comment]
Haha. That is great. Was looking for an explanation for the whole day. This is very nice to know

**Comment by mikecroft** [comment]
No problem!
