### ISSUE TITLE
Cannot use built-in Hazelcast as a Hibernate 2nd level cache

### ISSUE THREAD

**Issue by zemiak** [payara/Payara#1389]
# Description #
----------

When I try to use the built-in Hazelcast as a Hibernate 4.3.11 2nd level cache (using **hazelcast-hibernate4** package), it throws an exception.

## Expected Outcome

The Hazelcast should either boot a new Hazelcast instance (if it's not enabled in the **domain.xml**) or join an existing instance, booted by **domain.xml** config.

## Current Outcome

1. Server throws **Exception while preparing the app : Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
java.lang.IllegalArgumentException: Type id must be positive! Current: -202, Serializer: com.hazelcast.hibernate.serialization.Hibernate4CacheKeySerializer@5518dca4** when Hazelcast is disabled (the default conf) in **domain.xml** and hazelcast-hibernate4 is in **lib** folder

2. Server throws **org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [com.hazelcast.hibernate.HazelcastCacheRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]** when Hazelcast is disabled (the default conf) in **domain.xml** and hazelcast-hibernate4 is in **modules** folder

## Steps to reproduce (Only for bug reports) 

Clone https://github.com/zemiak/hibernate-cache. Run:

mvn clean package

sh build.sh

sh run.sh

docker logs hibernate-cache

You can see the **Type id must be positive! Current: -202** exception.

## Context (Optional)

We are trying to use an existing Hazelcast backend cluster (running Payara) as a Hibernate 2nd level cache.

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: Oracle 1.8
- **Operating System**: Linux, CentOS 7.x

**Comment by michaelranaldo** [comment]
Reproducible, received -203

**Comment by michaelranaldo** [comment]
Created internal issue PAYARA-1538

**Comment by zemiak** [comment]
It's good to see a progress. Thanks for involving!

**Comment by smillidge** [comment]
Marked as Won't fix a long time ago in JIRA
