### ISSUE TITLE
Cannot create LDAP security realm: Invalid property syntax, "=" in value

### ISSUE THREAD

**Issue by Aketzu** [payara/Payara#1398]
# Description

When I try to create new LDAP security realm the create screen doesn't save values properly. Saving from edit screen afterwards works.

## Current Outcome

Base DN: cn=users,dc=example,dc=com

After pressing save I get error message
`Invalid property syntax, "=" in value: base-dn=\"cn=users,dc=example,dc=com\"`

Also the values get quoted again and again with every save button press.

Only way to go forward is to input invalid base dn (i.e. any string without =), go to edit screen and input correct values.

Additionally, base-dn and directory values get saved "quoted" to the domain.xml on the initial create
```xml
 <auth-realm classname="com.sun.enterprise.security.auth.realm.ldap.LDAPRealm" name="test">
   <property name="directory" value="&quot;ldap://1.2.3.4:389&quot;"></property>
   <property name="assign-groups" value="foo,bar"></property>
   <property name="base-dn" value="&quot;xx&quot;"></property>
   <property name="jaas-context" value="testctx"></property>
 </auth-realm>
```
## asadmin recorder

Initial try
```
create-auth-realm --classname=com.sun.enterprise.security.auth.realm.ldap.LDAPRealm --property=jaas-context=testctx:base-dn=\"cn=users,dc=example,dc=com\":directory=\"ldap\:\/\/1.2.3.4\:389\":assign-groups=foo,bar: --target=server-config test
```

Second try, only save button pressed again
```
create-auth-realm --classname=com.sun.enterprise.security.auth.realm.ldap.LDAPRealm --property=jaas-context=testctx:base-dn=\"\"cn=users,dc=example,dc=com\"\":directory=\"\"ldap\:\/\/1.2.3.4\:389\"\":assign-groups=foo,bar: --target=server-config test
```

Saving with invalid base-dn and fixing it afterwards
```
create-auth-realm --classname=com.sun.enterprise.security.auth.realm.ldap.LDAPRealm --property=jaas-context=testctx:base-dn=\"xx\":directory=\"ldap\:\/\/1.2.3.4\:389\":assign-groups=foo,bar: --target=server-config test
set configs.config.server-config.security-service.auth-realm.test.property.base-dn=cn=users,dc=example,dc=com configs.config.server-config.security-service.auth-realm.test.property.directory=ldap://1.2.3.4:389
```

## Related

Same as https://java.net/jira/browse/GLASSFISH-20744 and https://java.net/jira/browse/GLASSFISH-20693

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: 1.8.0_112
- **Operating System**: Linux

**Comment by kingprimex** [comment]
I subscribe to the same bug....

**Comment by fturizo** [comment]
Thanks for reporting this issue @Aketzu. I have brought these bugs to the developers for them to fix it (wrong validation of the **Base DN** field and _extra doubles quotes_ added to the **Directory** and **Base DN** fields each time the form is submitted). As a workaround is possible to create the LDAP realm using the following _asadmin_ command (with proper escaping for the special characters as well):

```shell
asadmin create-auth-realm --classname=com.sun.enterprise.security.auth.realm.ldap.LDAPRealm --property=jaas-context=ldapRealm:base-dn=\"dc\=payara,dc\=fish\":directory=\"ldap\:\/\/localhost\:1389\":assign-groups=admin,common: --target=server-config ldap-realm
```

**Comment by fturizo** [comment]
Raised internal JIRA issue `PAYARA-1571`

**Comment by kingprimex** [comment]
Another workaround is to create the Ldap real with nothing but only the DN(no equlals).
After you create it, you can modify as you wish.

**Comment by eduarddrenth** [comment]
No matter what I do, creating auth realm does not work:

```
# ALAS creating auth realm using asadmin is pretty hopeless
#
#./bin/asadmin create-auth-realm --classname=com.sun.enterprise.security.auth.realm.ldap.LDAPRealm \
#	--property=directory\=\"ldap\:\/\/192.168.8.41\:389\":\
#		assign-groups=gast:\
#		base-dn=\"OU\=FA,DC\=fryske-akademy,DC\=local\":\
#		jaas-context=ldapRealm:\
#		search-bin-dn=\"CN\=Eduard\ Drenth,OU\=Taalkunde,OU\=FA,DC\=fryske-akademy,DC\=local\":\
#		search-bind-password=$lpw:\
#		search-filter=userPrincipalName\=%s:\
#		group-search-filter=\"\(\&\(objectClass\=group\)\(member\=%d\)\)\" LdapRealm
#
```

I get:
```
remote failure: Illegal repetition near index 1
\${.+}
 ^
Illegal repetition near index 1
\${.+}
 ^
```

It looks like regex is being used. Perhaps writing a (javacc) parser would be a good idea here?

**Comment by kingprimex** [comment]
Try to create an empty auth realm,  and edit afterwards(on web or on cli )
