### ISSUE TITLE
Glassfish-ORB IIOP RMI Tunnel/Over Http2 by Grizzly Port Unification?

### ISSUE THREAD

**Issue by AngeloRubens** [payara/Payara#1406]
# Description #

This feature it's an entry point for Corba IIOP over Http/Http2 for a valid alternative to gRPC.

On grizzly jira there was this issue https://java.net/jira/si/jira.issueviews:issue-html/GLASSFISH-6371/GLASSFISH-6371.html

Thanks for your time.

----------

## Environment ##

- **Payara Version**: next release
- **Edition**: 
- **JDK Version**: 
- **Operating System**:

**Comment by mikecroft** [comment]
Hi @AngeloRubens - what is the issue here? Is the title a question or a bug report? Do you expect it to work? Have you tried it?

**Comment by AngeloRubens** [comment]
Hi Mike, yes the title is a question. There is a possible for this feature? It's an entry point for Corba IIOP over Http/Http2 for a valid alternative to gRPC?

Thanks for your time.

**Comment by mikecroft** [comment]
That's an interesting idea. The main blocker here is that CORBA does not use Grizzly in Payara, so the change would be fairly significant to add this feature. It's not likely to be done any time soon, but if you needed it you can always sponsor the feature

**Comment by AngeloRubens** [comment]
Hi Mike, many thanks for your response,
i think the EJB Component Model have more feature for a good alternative to gRPC or FinagleRPC.

In the EJB 1.1 Specification, Sun Microsystem in according to OMG integrate RMI over CORBA IIOP(Standard deFacto and more use in the years 80/90). Most corba client invoke Ejb method from c++, ada etc by Corba Client. 
The good base of RMI-IIOP based to OMG Corba(IDL+IIOP/GIOP Message) have most power.
With EJb Ecosystem if i want invoke method over http with binary protocol i'dont have a good choice.
gRPC or Finangle sponsored an rpc over http2(only efficient alternative for REST JSON+HTTP), but there are more work for developer. 
generate proto interface(on java there is OMG IDL), 
generate and populate stub code(on Ejb this is gratis with Runtime Stub Generation/Downloading  feature)
generate and populate skeleton code(on Ejb this is gratis with Runtime Skeleton Generation feature)

i found some blog for this argument:

https://blogs.oracle.com/ejcorba/entry/corba_and_grizzly

https://kenai.com/projects/gf-corba-v3-mirror

https://java.net/projects/glassfish-corba/pages/Home

Payara EJB RMI-IIOP over http2 is interesting feature like Payara CDI Remoting Events.

Thanks for your time.

**Comment by smillidge** [comment]
My thoughts are that remote EJBs over Websockets would be interesting to explore. What do you think?

**Comment by AngeloRubens** [comment]
Hi,

also sure, the main focus is GIOP over HTTP/HTTP2(feature Keep-Alive,Long Polling,Websocket) -> HTIOP

https://en.wikipedia.org/wiki/General_Inter-ORB_Protocol

Thanks for your time.

**Comment by AngeloRubens** [comment]
Or e vert language and easy invocation over http🤓🤓🤓

**Comment by AngeloRubens** [comment]
Some non standard protocol like  bea t3 or jboss River use proxyservlet on top of NIO Framework(xnio,  Netty, undertow) for invoke rmi on ejb

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1858` for this

**Comment by AngeloRubens** [comment]
Recently i discovered this WildFly Detail Implementation for EJB(and JNDI) over HTTP:
https://github.com/wildfly/wildfly-http-client/blob/master/docs/src/main/asciidoc/wire-spec-v1.asciidoc.

It's an interesting entry point for payara iiop(giop) over http

**Comment by smillidge** [comment]
Hi we are now working on Remote EJBs over HTTP and this was released in the latest Payara 5.191. This means this specific enhancement won't happen.
