### ISSUE TITLE
Enhancement: Allow separate log file for each deployed WAR/EAR

### ISSUE THREAD

**Issue by wargun02** [payara/Payara#143]
Just an enhancement suggestion, hopefully there could be an option to have a separate log file for each deployed WAR/EAR (during deployment).

Reason: there might be deployment of multiple WAR of the same application. Separating the log file for each deployment will promote better log trace.

For now, creating a new server instance or domain for each application deployment might be the choice for some, but that will require a lot of system resources.

Thank you.

**Comment by smillidge** [comment]
Hi 

Could you explain in a bit more detail what you are looking for. It is possible to create separate log files for an application by changing the logging configuration, however this would be on a per package basis.

Do you mean that each deployment would have its own log file for requests so that e.g.
war1-> war1.log
ear1 -> ear2.log

or something different?

**Comment by wargun02** [comment]
Hi Steve,

Yes, the war1-> war1.log, ear1 -> ear2.log will be great as default. Here's a suggestion for an improved log option:

1) Every time when a user/admin deploys the war of ear file through Applications -> Deploy -> Choose file (war, ear or type, etc.)...

2) In the lower portion of fill-ins where we could specify the Context Root manually and other deployment details, we could have a section to specify log file name with default option to follow the war/ear file name OR to a custom file name.

3) Once the log file option is entered, Payara should detect if there are log file names duplication. If so, ask the user/admin if the log should be appended to the existing log file OR to create an entirely new log file.

4) Could even have the option to the specify location which the log file which should be written to (instead of the <domain>/logs directory).

Of course, I believe Payara's development team has better discernment than me as to what deems fit.

I mean...these are just my thoughts. No hard and fast rule.

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-1070`
