### ISSUE TITLE
Add SNI SSL support

### ISSUE THREAD

**Issue by dfelixz** [payara/Payara#1431]
# Description #
----------

It would be nice to be able to configure/use SSL SNI (Server Name Identification).
## Expected Outcome
 

 Currently it's possible to have only one SSL certificate per IP address. With SNI, multiple SSL certificates (for different domains) can be used with the same IP address. 
This feature is already supported in Grizzly but I coudn't find a way to enable/configure it in Payara. 
## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: 
- **JDK Version**: 
- **Operating System**:

**Comment by mikecroft** [comment]
Internal enhancement issue raised with id `PAYARA-1528`
