### ISSUE TITLE
Ejb long processing causing software abort connection

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1434]
I am having a issue when calling the EJB method to get the yearly data report which take about 3 hours processing, But when data return from EJB. It is always causing this error shown as below. (I changed to CDI bean and it is totally working fine).
May I know how to solve this in payara41 server
javax.ejb.EJBException: Unable to complete container-managed transaction.

Caused by: javax.transaction.SystemException

at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:537)

at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:879)

at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:721)

... 39 more

Caused by: javax.transaction.xa.XAException: javax.resource.spi.LocalTransactionException: IO Error: Software caused connection abort: recv failed

at com.sun.enterprise.resource.ConnectorXAResource.handleResourceException(ConnectorXAResource.java:116)

at com.sun.enterprise.resource.ConnectorXAResource.commit(ConnectorXAResource.java:127)

at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:518)

... 41 more]]

**Comment by lprimak** [comment]
Hi, @Taymindis 
EJBs by design are part of a container-managed transaction, which have default timeouts.
You can either increase the timeout or disable the container-managed transaction.
Either of these methods are documented in Java EE documentation.
I would disable the CMT using javax.ejb.TransactionAttributeType.NOT_SUPPORTED for example

**Comment by smillidge** [comment]
It is also possible that the database has a transaction timeout or processing limits on the connection. When you use a CDI bean you do not have an active transaction and have likely placed the JDBC connection into autocommit mode. This may be fine if the transaction is read-only but not if the transaction updates data.

**Comment by Taymindis** [comment]
@lprimak I've set to around 1 day transaction timeout. I will try Transaction Not support.

@smillidge It only took 20 mins to load the query, once done, It copied the result to map and release connection then doing another process which took about 2-3 hours http call service. The error always occurring after the http call service done and return the result. 

aServlet -> ejbinstance.methodB ( loadQuery(), httpCall() ) -> return resultList

**Comment by smillidge** [comment]
OK it would be better to split out the http call as a transaction will be held open both on the database and in Payara if you do both operations in a single EJB method call. Given the length of the HTTP call you may also get firewall timeouts or other network timeouts closing connections if there is no network activity on the socket for 2 - 3 hours.

**Comment by Taymindis** [comment]
@smillidge There is no firewall between 2 server as there are internal. If it is the issue, then why CDI and ejb timer are working smoothly, one thing i can confirmed that if i use ejb method call and all the process done within 40 mins. It is working fine.

@smillidge However, i heard that CDI event is available on latest payara cluster full profile. I am thinking to migrate my reporting server all long process ejb to CDI, and migtate some JMS to CDI event :)

**Comment by Taymindis** [comment]
Bravo, 

Put TransactionAttributeType.NOT_SUPPORTED has fixed the issue. 

Thanks,
