### ISSUE TITLE
Support conditional Access Logs

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#1450]
# Description #
----------

Support condition on the Access Log in Payara. See https://tomcat.apache.org/tomcat-7.0-doc/config/valve.html#Access_Log_Valve/Attributes for the equivalent in Tomcat. The source code in PEAccessLog supports the conditrion attribute but there is no way to configure it in the domain.xml
See https://github.com/payara/Payara/blob/master/appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java#L593 

## Expected Outcome

Conditional access logging is supported.

## Current Outcome

This is a pretty simple fix and will extend the functionality of access logging to bring it into line with the Tomcat equivalent.

**Comment by mikecroft** [comment]
internal issue `PAYARA-1509`
