### ISSUE TITLE
Payara Micro Config Domain

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1451]
Where can I get the sample of payara micro domain file? is it same with Payara full profile config domain?

**Comment by mulderbaba** [comment]
@Taymindis yes it is, you can find the domain.xml under MICRO-INF/domain/domain.xml and if you execute the payara-micro w/ --rootDir option, you can define an external domain directory for holding the configurations. See [blogpost](http://blog.payara.fish/working-with-external-configuration-files-in-payara-micro) for details.

**Comment by Taymindis** [comment]
@mulderbaba Great! Thank you

**Comment by sknitelius** [comment]
For anybody else looking here is the full link:
[https://github.com/payara/Payara/blob/master/appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml](https://github.com/payara/Payara/blob/master/appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml)
