### ISSUE TITLE
'Deploy Application on startup' Feature for payara full profile 

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#1463]
Hi there. First of all : Thanks you for your great work on payara, it is a great product. 
However, I miss (or can't find)  a Feature in payara full Version which allows me to deploy my WAR on Server startup like it already works in payara micro. 
Something like asadmin --verbose --deploy myapp.war. 
Why Do I need this? Because when I use docker, I use asadmin --verbose for startup the server. Chaining the deployment after in a new Script and use this as docker Start Script like this :
asadmin --verbose
asadmin deploy App.war 

Will not work because the first command will not end. 
So there are 2 choices, which are both not very nice: 
1. Do it after in the deployment Pipeline. This seems to be very unsexy. Or
2. So it before in the docker build. This is not possible in my Environment, because I want to use one docker image for all my stages like test, prelive, live. On each Container start I have to patch the domain.xml to use the right database (each database matches to a stage). But this Information I only know on Container start, Not in the docker image build. 

So what is your opinion here? Let me know if you need more Information. 

Best regards 

Basti

**Comment by mikecroft** [comment]
We've actually been discussing exactly this in the past couple of days and that was prompted by using Payara Server in docker too. Some possibilities would be either:

1. Enhance the existing autodeploy feature.
    * Currently the autodeploy polling interval is a value in seconds and needs to be `>=1` - a value of 0 fails validation because the scanner would run constantly, using too much CPU.
    * We could add a special feature of a value of 0 whereby the scanner would stop scanning after it has deployed the contents of the directory. This would be a bit tricky since we don't know how long to wait before that only-once scan, so perhaps a better solution would be to implement the feature as a new property.
2. We add in a `--deploy` option which would work in the same way as Payara Micro.
    * This would work equally as well, but perhaps be more obvious in how it works.
3. We could do both

Functionally (from a user's perspective), these are both really similar - with either approach you just look at a file or directory and deploy it once and stop. I can't really think of any downsides which are unique to either approach.

This is a feature we'll do, I'm just not sure exactly how it will look right now. Your experiences and input are gratefully received!

**Comment by mikecroft** [comment]
Internal issue ID `PAYARA-1527`

**Comment by deratzmann** [comment]
Yes, 2nd solution would be great. Autodeploy feature was deactivated for Security reasons as we both wrote about on Twitter :)

**Comment by deratzmann** [comment]
Where can I check if and maybe when this Feature would be available?

**Comment by mikecroft** [comment]
Keep watching this issue, we'll keep it open until it's implemented :)

**Comment by smillidge** [comment]
Payara Micro always forces a redeployment on restart of the docker container because in standard usage no changes are persisted. If a --deploy was added to the command line options for Payara Server when restarted the application will already be deployed. Should it force a redeploy?

**Comment by deratzmann** [comment]
Good question. At least I would say it should behave the same way like micro. So, yes. Redeployment.

**Comment by AdamBien** [comment]
2. is important, 3. would be nice.

**Comment by OndrejM** [comment]
The option 1 is not very powerful, because the autodeploy mechanism doesn't allow specifying custom deployment options (e.g. it always deploys to all virtual servers on an instance called `server`).

We are inclined to support option 2. (adding  --deploy agument to start-domain, similar to what Payara Micro does), but we will probably also enable option 3. - scheduling a sequence of asadmin commands to execute during server bootstrap, which is also inspired by Payara Micro's --prebootcommandfile and --postbootcommandfile options. The option 3 would be even more powerful and would enable to exxecute any asadmin commands during bootstrap, including `deploy`.

**Comment by Cousjava** [comment]
#1537 implements pre- and post- boot command files. Is this suitable for you?

**Comment by deratzmann** [comment]
Ich think this sounds suitable.

**Comment by deratzmann** [comment]
Ich=I

**Comment by svendiedrichsen** [comment]
Is there a chance to have this feature in v172?

**Comment by mikecroft** [comment]
#1537 is currently milestoned to 172, so I expect it will be available there, pending test results.
