### ISSUE TITLE
inconsistency in version number for 4.1.1.171.0.1

### ISSUE THREAD

**Issue by domtro** [payara/Payara#1469]
The pom files from tag 4.1.1.171.0.1 contains a version 4.1.1.172-SNAPSHOT, while the jar issued from official download website indicate a 4.1.1.171.0.1 in the META-INF. 
As a consequence it is impossible to recompile 4.1.1.171.0.1 release from the tag

**Comment by Pandrex247** [comment]
Good catch - I'll look into correcting it.
I'll have to delete the tag and re-upload it to fix it though.

**Comment by Pandrex247** [comment]
I've redone the tag, there shouldn't be any poms with 172-SNAPSHOT now.
