### ISSUE TITLE
Apache pluto 3 on payara

### ISSUE THREAD

**Issue by phillip-kruger** [payara/Payara#1485]
# Description #
----------

I am trying to deploy the new apache pluto 3 with it's examples on payara 171 full.
I got it working on TomEE and Wildfly, and would like to get it running on Payara as well.
However I am getting a error with the CDI injection from portlet api.

## Expected Outcome
The CDI in portlet-api should be available for portlets to inject.

1. `git clone https://github.com/phillip-kruger/portals-pluto.git` (this is a fork from the apache master, that has some ant build files for TomEE, Wildfly and Payara)
2. in the portals-pluto (root) directory, run: `ant -f dist-payara-build.xml -DincludeDemos=true`
3. Get the tar.gz or zip distribution from target/dist/ and extract somewhere (eg. /opt) 
4. Start the payara server, example /opt/pluto-payara-3.0.1-SNAPSHOT/bin/asadmin start-domain
5. In your browser, go to [http://localhost:8080/pluto/](http://localhost:8080/pluto/)
6. You can log in with pluto / pluto

The libs is in `/opt/pluto-payara-3.0.1-SNAPSHOT/glassfish/domains/domain1/lib/`
The portal and portlets is in `/opt/pluto-payara-3.0.1-SNAPSHOT/glassfish/domains/domain1/autodeploy/`
## Current Outcome
So the normal JSR 168 and JSR 286 Test seems OK (although there are some errors). 
What I can not get working is the new V3.0 (JSR-362) tests/demos.
This is because the wars for those portlet get an error on deploy

## Steps to reproduce
If you redeploy one of the V3 portlet wars, example:
`touch /opt/pluto-payara-3.0.1-SNAPSHOT/glassfish/domains/domain1/autodeploy/PortletV3Demo.war`

Then you get this in the log:

> Exception during lifecycle processing
> org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Exception List with 4 exceptions:
> Exception 0 :
> org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type ActionParameters with qualifiers @Default
>   at injection point [UnbackedAnnotatedField] @Inject private basic.portlet.AuthSCPortlet.ap
>   at basic.portlet.AuthSCPortlet.ap(AuthSCPortlet.java:0)
> 

I have tried all sorts of things to get the CDI to inject. Played with the glassfish-web.xml and explicit scan. Tried to deploy the portlet-api as OSGi. Nothing seems to work.

Any help would be appreciated.
Thanks 

## Environment ##

- **Payara Version**: Payara Server 4.1.1.171 #badassfish (build 137)
- **Edition**: Full
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_121-b13)
- **Operating System**: Linux (Arch)

**Comment by smillidge** [comment]
As ActionParameters is an interface http://www.programcreek.com/java-api-examples/index.php?source_dir=portletspec3-master/portlet-api_3.0/src/main/java/javax/portlet/ActionParameters.java do you know which class is the CDI Producer?

**Comment by phillip-kruger** [comment]
Hi Steve.
Yes. see https://github.com/apache/portals-pluto/blob/master/pluto-container/src/main/java/org/apache/pluto/container/bean/processor/PortletArtifactProducer.java

line 471
`@Produces @PortletRequestScoped @Named("actionParams") @Typed(ActionParameters.class)
   public static ActionParameters getActionParameters() {
      PortletArtifactProducer pap = producers.get();
      assert pap != null;
      ActionParameters obj = null;
      if (pap.req instanceof ActionRequest) {
         obj = ((ActionRequest)pap.req).getActionParameters();
      }
      return obj;
}`

Thanks for your help :)

**Comment by smillidge** [comment]
I can get the PortletV3Demo application to deploy but only by modifying your PortletCDIExtension class. I added the following code.

```java
   
   void beforeBeanDiscovery(@Observes BeforeBeanDiscovery bbd, BeanManager bm) {
      LOG.debug("PortletCDIExtension - scanning.");
      AnnotatedType<PortletArtifactProducer> at = bm.createAnnotatedType(PortletArtifactProducer.class);
      bbd.addAnnotatedType(at);
   }
```

My theory is that Payara is not scanning libraries on the system classpath for beans and therefore does not pick up the producer. However it does detect your CDI Extension and calls it correctly.

**Comment by smillidge** [comment]
My view is this is a bug in the PortletCDIExtension class.

**Comment by phillip-kruger** [comment]
Hi Steve.
Thanks for spending time on this. 
I am unsure that we can call it a bug in PortletCDIExtension class. That same class is working in TomEE and Wildfly. Wildfly is also using Weld for CDI. 

Or am a missing something ?

**Comment by smillidge** [comment]
In Payara you are putting the bean archive jar into the lib directory of the server. This is not scanned for beans but is scanned for CDI extensions. If you packaged the jar with your application it would be scanned and the producer found. Payara does not scan all its System classpath for CDI beans.

**Comment by phillip-kruger** [comment]
Ok that make sense. And there is no way to tell payara to scan certain files in lib ? Or include the jars as osgi maybe ?

When writing portlets you typically end up with many war files (separate portlets) and I would not want to include the jar files in the wars ... keep the wars lite and thin...

**Comment by phillip-kruger** [comment]
Ok I'll try that and get back to you

**Comment by mikecroft** [comment]
Hi @phillip-kruger did that work for you?

**Comment by phillip-kruger** [comment]
Hi Mike.
Apologies - I have not yet tried. But we can close this and I will reopen if it did not work.
Thanks
