### ISSUE TITLE
Update underlying specification implementations

### ISSUE THREAD

**Issue by mamboking** [payara/Payara#149]
Many of the underlying specification implementations have newer releases than the ones that come with GF4.1.  I think it would be incredibly useful if your quarterly releases included the latest released versions of those projects.  For example:  both GF 4.1 & Payara 4.1.144 come with jersey 2.10.4 but there are bug fixes we need that were released with jersey 2.13 (The current release of jersey is 2.14).

**Comment by smillidge** [comment]
It's on the radar.

Jersey upgrade is scheduled for the next release at the end of the month.

**Comment by smillidge** [comment]
Lots of upgrades went into Payara as part of #152

**Comment by mamboking** [comment]
Thank you!
