### ISSUE TITLE
Clarify state of Java EE certification

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#1499]
Glassfish 4.x is Java EE 7 certified. Payara is forked from it. It'd be nice to have a clear statement what that means for the Java EE certification state of Payara - I guess it's not officially certified, but maybe there're changes/improvements  which clearly conflict with the certification. Imo it's worth to put that into `README`.

**Comment by fturizo** [comment]
Greetings @krichter722,

Payara Server is not **officially** certified as a Java EE server; however, Payara Server is **fully compatible** at a technical level with the complete JEE 7 specification, which means that for any bugs or unwanted behaviour that is not compliant with the specifications it's our responsibility to fix and patch them. All new releases will be compatible with the specifications as well.

I agree with the idea of adding more clarification on this matter, so thanks for the suggestion.

**Comment by OndrejM** [comment]
Hi @krichter722, @gilbertoca, our official statement is that Payara Server is an application server derived from GlassFish. We maintain compatibility with the latest version of GlassFish and will continue to maintain it as long as possible. Therefore as long as GlassFish behaves according to the specification, Payara Server should behave in the same way. If we see that Payara Server doesn't behave as specified, we will treat it as a bug and attempt to fix it. Payara Server provides optional features that conflict with the specification, but these are never turned on by default and are available mainly to ease migration of older applications or to optimize applications for production.

Would that be enough as an explanation? We can add something like that into the `README`, however, we will not make any official statements regarding Java EE for various legal reasons.

**Comment by krichter722** [comment]
> Hi @krichter722, @gilbertoca, our official statement is that Payara Server is an application server derived from GlassFish. We maintain compatibility with the latest version of GlassFish and will continue to maintain it as long as possible. Therefore as long as GlassFish behaves according to the specification, Payara Server should behave in the same way. If we see that Payara Server doesn't behave as specified, we will treat it as a bug and attempt to fix it. Payara Server provides optional features that conflict with the specification, but these are never turned on by default and are available mainly to ease migration of older applications or to optimize applications for production.

Great! Go for it, it's a huge contribution to Java EE!!

> Would that be enough as an explanation? We can add something like that into the README, however, we will not make any official statements regarding Java EE for various legal reasons.

Otherwise, people will just need to make unnecessary search engine queries instead of getting the information from a default location.
