### ISSUE TITLE
Add Payara to the list of Java EE server on Wikipedia

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#1502]
It'd be nice to see Payara in the [list of Java EE servers on Wikipedia](https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition) (the english one and probably all languages your staff supports) since it's quite hard to find out about your awesome project :)

**Comment by mikecroft** [comment]
I don't think we could do that, since the list there is of certified servers and we're not certified. We are on Wikipedia, though:
https://en.wikipedia.org/wiki/Payara_Server
