### ISSUE TITLE
Can't get a handle on running Payara Micro

### ISSUE THREAD

**Issue by realulim** [payara/Payara#1508]
# Description #
----------

I followed the tutorial under http://blog.payara.fish/the-health-check-service-in-depth-payara-micro

## Expected Outcome
That Payara would bring my application up and then start health checks. My application does run without trying to enable health checks, when my application starts.

## Current Outcome
I get this in the server.log:

java.lang.IllegalStateException: Payara Micro is not running
        at fish.payara.micro.impl.PayaraMicroImpl.getRuntime(PayaraMicroImpl.java:1027)
        at fish.payara.micro.impl.PayaraMicroImpl.getRuntime(PayaraMicroImpl.java:101)
        at fish.payara.micro.PayaraMicro.getRuntime(PayaraMicro.java:179)

## Steps to reproduce (Only for bug reports) 

I created a standard REST service and put the Payara initialisation code (see tutorial) in a @PostConstruct method in my ApplicationConfig class. But I also tried to execute it much later, when my service is first called, same result. Payara thinks it is not running, but it is, because my app works.

I can send the entire app, if this cannot be reproduced.

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Micro
- **JDK Version**: 1.8.0_121-b13
- **Operating System**: Linux

**Comment by mikecroft** [comment]
Hi @realulim it would be really useful if you could send a link to the source of your app, so we can reproduce things exactly. Could you create a GitHub repository for it please?

**Comment by OndrejM** [comment]
@realulim, here are some suggestions on what to try to find out what is working and what's not:

 - try with Payara Micro 164 (there was a heavy refactoring in 171, which might be causing the issues)
 - try setting up the healthcheck service via asadmin commands passed via the `--postbootcommandfile` option - it accepts a text file, which contains asadmin commands one by one on a separate line (if you post the code of your `@PostConstruct method`, I can send you the file with asadmin commands)

Finally, a question - how do you run your application? Do run it from command line (java -jar payara-micro.jar), as an uber jar built by --outputuberjar option, or from Maven or your IDE? We know that there are issues when Payara Micro is started from a maven project and we are working on solving them.

**Comment by realulim** [comment]
Here is the github repo:
https://github.com/realulim/payara-hazelcast-example

**Comment by realulim** [comment]
I start the application via java -jar payara-micro.jar --deploy my.war

**Comment by fturizo** [comment]
Greetings @realulim,

I've tested the sample application and can confirm that the bug you are experiencing is indeed present on Payara Micro 171. The same application can deploy without issues on Payara Micro 164. I've raised this issue for the developers to work on.

As a workaround, you can use the suggestion that @OndrejM made and transplant the health check service configuration instructions to a command file that can be executed after the instance has already booted using `--postbootcommandfile` option. Let's say you create the file **hc-service-configuration.txt** with the following contents:

```shell
#Configure health-check service
healthcheck-configure --enabled=true --dynamic=true
healthcheck-configure-service --serviceName=healthcheck-cpu --enabled=true --time=5 --unit=SECONDS --dynamic=true
healthcheck-configure-service-threshold --serviceName=healthcheck-cpu --thresholdCritical=90 --thresholdWarning=50 --thresholdGood=0 --dynamic=true
healthcheck-configure-service --serviceName=healthcheck-machinemem --enabled=true --dynamic=true --time=5 --unit=SECONDS
healthcheck-configure-service-threshold --serviceName=healthcheck-machinemem --thresholdCritical=90 --thresholdWarning=50 --thresholdGood=0 --dynamic=true
```

Then you can run your micro instance like this:

```shell
java -jar payara-micro-4.1.1.171.1.jar --postbootcommandfile hc-service-configuration.txt --deploy my.war
```

**Comment by fturizo** [comment]
Internal JIRA Issue `PAYARA-1565`

**Comment by realulim** [comment]
Thanks, the postbootfile strategy works fine.
