### ISSUE TITLE
Payara/glassfish overwrite resource adapter config when using ra.xml

### ISSUE THREAD

**Issue by zhangchi** [payara/Payara#1520]
# Description #
----------

We are using resourceAdapter in payara right now, which supposed to support the full JCA specification. But we noticed that some configurations are not working

## Expected Outcome

In JCA spec, we can implement ValidatingManagedConnectionFactory for our managedConnectionFactoryImpl, and we are expecting payara will call public Set getInvalidConnections(Set connectionSet) throws ResourceException method based on the frequency we defined in the ra configuration.

## Current Outcome

we specify two things, is-connection-validation-required and validate-atmost-once-period-in-seconds in our ra.xml, and the payara resource adapter config. However, those configurations don't seem to work.

## Root Cause

We checked the payara source code, in ConnectionPoolObjectsUtils.createSunRaConnectorPoolObject in connectors-runtime module, setDefaultAdvancedPoolAttributes method actually will simply set all the advanced attribute with the default value no matter what kind of config we provided. By simply changing the code over there and re-build a new connectors-runtiime.jar. We can get the getInvalidConnections start being called by connectionPool in payara. We haven't fixed the reading value from ra.xml issue yet. 

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8.0_121
- **Operating System**: Mac 10.10.5

**Comment by smillidge** [comment]
try setting the properties in the rar.xml with the names;
```xml
"org.glassfish.connector-connection-pool.is-connection-validation-required=true",  "org.glassfish.connector-connection-pool.validate-at-most-once-period-in-seconds=1"
```

**Comment by zhangchi** [comment]
@smillidge based on the source code, looks like payara will overwrite those configurations, can u confirm? 
` in ConnectionPoolObjectsUtils.createSunRaConnectorPoolObject in connectors-runtime module, setDefaultAdvancedPoolAttributes method actually will simply set all the advanced attribute with the default value no matter what kind of config we provided. `

**Comment by smillidge** [comment]
they do get through I tested with a rar deployment.

**Comment by zhangchi** [comment]
@smillidge when u talking about rar.xml, is that a typo? cause in our rar module, we only have ra.xml, and sun-ra.xml.

I edited my ra.xml as
`
<resourceadapter>
<config-property>
            <description>Enable background validation
            </description>
            <config-property-name>org.glassfish.connector-connection-pool.is-connection-validation-required</config-property-name>
            <config-property-type>java.lang.Boolean</config-property-type>
            <config-property-type>true</config-property-type>
        </config-property>
        <config-property>
            <description>Background validation interval
            </description>
            <config-property-name>org.glassfish.connector-connection-pool.validate-at-most-once-period-in-seconds</config-property-name>
            <config-property-type>java.lang.Integer</config-property-type>
            <config-property-value>1</config-property-value>
        </config-property>
</resourceadapter>
`

doesn't seem like working. Trying to change my payara resource adapter config from the admin console directly right now.

**Comment by smillidge** [comment]
yes a typo on rar.xml

You have a typo in the above xml you have config-property-type tag twice for the `org.glassfish.connector-connection-pool.is-connection-validation-required` property

**Comment by zhangchi** [comment]
@smillidge 
My fault, I have changed the config. so currently, I am having a hazelcast rar module in my ear, since our code is working as hazlecast client and connect with a standalone hazelcast cluster. I have done three things to verify the properties u mentioned.

1. in rar module ra.xml
`
<resourceadapter>
<config-property>
            <description>Enable background validation
            </description>
            <config-property-name>org.glassfish.connector-connection-pool.is-connection-validation-required</config-property-name>
            <config-property-type>java.lang.Boolean</config-property-type>
            <config-property-value>true</config-property-value>
        </config-property>
        <config-property>
            <description>Background validation interval
            </description>
            <config-property-name>org.glassfish.connector-connection-pool.validate-at-most-once-period-in-seconds</config-property-name>
            <config-property-type>java.lang.Integer</config-property-type>
            <config-property-value>1</config-property-value>
        </config-property>
</resourceadpter>
`
2. in sun-ra.xml
`
<sun-connector>
    <resource-adapter
            jndi-name="HazelcastCF" max-pool-size="1000"
            steady-pool-size="10" max-wait-time-in-millis="300000"
            idle-timeout-in-seconds="5000"
    org.glassfish.connector-connection-pool.is-connection-validation-required="true"
    org.glassfish.connector-connection-pool.validate-at-most-once-period-in-seconds="1">
    </resource-adapter>
</sun-connector> 
`

3. In payara domain.xml
`
<resource-adapter-config resource-adapter-name="hw-hazelcast-jca-rar">
      <property name="client" value="true"></property>
      <property name="configurationLocation" value="hazelcast-client.xml"></property>
      <property name="org.glassfish.connector-connection-pool.validate-at-most-once-period-in-seconds" value="1"></property>
      <property name="org.glassfish.connector-connection-pool.is-connection-validation-required" value="true"></property>
    </resource-adapter-config>
`

None of the above config worked..I don't see the logging info, my breakpoint in the getInvalidConnections method never got called.  Really appreciate if you can share your test rar setup, I will dig into it and see if there are anything I missed in our project.

In addition, it will be great if you can show me a place that I can debug in payara source code so that why your property values work, since my code debugging shows that no matter what value I have, the connectionPool will always go to ConnectionPoolObjectsUtils to setup the configurations.

Sorry to bug you so much, really appreciate your help!

**Comment by smillidge** [comment]
Is this still an issue?
If so we need a reproducible test case can you provide one?
If not please close.

**Comment by czhang-hw** [comment]
we have no updates on this ticket to reproduce it, closing the ticket

**Comment by zhangchi** [comment]
no more info about reproduce the issues. closing the ticket
