### ISSUE TITLE
No context help in Adminconsole

### ISSUE THREAD

**Issue by baztian** [payara/Payara#1525]
# Description #
----------

The online help in admin console is not context sensitive as it is in Glassfish.

## Expected Outcome

When I hit the help button in Glassfish I directly jump to the explanation of the aspects on the current view. Furthermore I'll find out about the keys for use with asadmin command. I really want to have this back in Payara too.

## Current Outcome

Currently Payara just opens a general help page.

## Steps to reproduce (Only for bug reports) 

Press help in the admin console.

**Comment by mikecroft** [comment]
I'm not sure where we stand on this from a legal perspective. The help docs don't seem to have any explicit license except pom.xml files which have the same CDDL license as the rest.

@smillidge - do you know if we can legally re-incorporate the contextual help?

**Comment by smillidge** [comment]
It's for licensing that it is not included. It is not clear what the license is for the help files. The pom says CDDL but CDDL is a file based license so each file must be declared to be subject to the CDDL.

If you look at an example file in the Oracle repository e.g. https://java.net/projects/glassfish/sources/svn/content/trunk/main-docs/help/jca/src/main/resources/en/help/docinfo.html?rev=64928  you can see it does not declare the files as subject to the CDDL.
