### ISSUE TITLE
[PayaraMicro] Log file name is not reflected

### ISSUE THREAD

**Issue by ahuglajbclajep** [payara/Payara#1527]
# Description #
Output file name of logToFile option of payara-micro is not reflected.
It will always be named `payara-server0.log.0`.

## Current Outcome
I read [this](https://payara.gitbooks.io/payara-server/documentation/payara-micro/logging-to-file.html) gitbook and tried to make uberJar like [this](https://github.com/ahuglajbclajep/hello-payara-micro/blob/master/build.gradle#L24) repository.
But the output log file name will always be `payara-server0.log.0`.

`PayaraMicro.setUserLogFile` method does not seem to work either.

### Samples
https://github.com/ahuglajbclajep/hello-payara-micro
```sh
git clone https://github.com/ahuglajbclajep/hello-pyra-micro.git
cd hello-payara-micro
./gradlew uberZip
```
Extract `./Build/distributions/hello-payara-micro-1.0.0.zip` and run the `launcher.sh` script.

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Micro
- **JDK Version**: 8u121 OracleJDK
- **Operating System**: Windows(7,8) / Linux(Ubuntu16.04.2LTS)

**Comment by smillidge** [comment]
I couldn't reproduce this. Using the option `--logtofile /home/steve/temp/test2.log` produced the file `/home/steve/temp/test2.log.0`

**Comment by ahuglajbclajep** [comment]
Thank you for trying!!
I will check it again well.

**Comment by ahuglajbclajep** [comment]
As a result of the verification, I discovered that the `--logtofile` option does not work when generating UberJar.
For example
```sh
java -jar payara-micro-4.1.1.171.1.jar --deploy ROOT.war --outputUberJar uber.jar
java -jar uber.jar --logtofile log  # produced the file 'log.0'
```
but
```sh
java -jar payara-micro-4.1.1.171.1.jar --deploy ROOT.war --outputUberJar uber.jar --logtofile log
java -jar uber.jar  # produced the file 'payara-server0.log.0'
```
Is this behavior specification?

**Comment by smillidge** [comment]
no sounds like a bug. I'll see if it can be reproduced.

**Comment by smillidge** [comment]
This is a confirmed bug internal issue number is  PAYARA-1586
