### ISSUE TITLE
@Priority Interceptor from external JAR not picked up

### ISSUE THREAD

**Issue by Pscheidl** [payara/Payara#1532]
# Description #
----------

here is a simple WAR file with one external dependency. The external dependency is a JAR with one CDI extension (working correctly) and one [interceptor annotated with @Priority annotation](https://github.com/Pscheidl/FortEE/blob/master/src/main/java/cz/pscheidl/fortee/FailsafeInterceptor.java). This interceptor is not activated in Glassfish 4.1.2 (and also in derived Payara 171). 

An attempt was made to enable the interceptor manually via beans.xml.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="all">

    <interceptors>
        <class>cz.pscheidl.fortee.FailsafeInterceptor</class>
    </interceptors>

</beans>
```

This leads to:
```text
java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : CDI deployment failure:WELD-001417: Enabled interceptor class <class>cz.pscheidl.fortee.FailsafeInterceptor</class> in file:/home/pavel/Software/application_servers/glassfish4/glassfish/domains/domain1/applications/payara-interceptor-bug-1.0/WEB-INF/beans.xml@8 does not match an interceptor bean: the class is not found, or not annotated with @Interceptor and still not registered through a portable extension, or not annotated with @Dependent inside an implicit bean archive. Please see server.log for more details.
```

## Expected Outcome

When a JAR library with an interceptor annotated with `@Priority` annotation is included in a web archive, it should be enabled by default.

## Current Outcome

Interceptor is not enabled. Manual interceptor registration and enbaling does result in an exception.

### Reproducing from scratch
1. Create a JAR with a Java EE interceptor class.
2. Annotate the interceptor with @Priority annotation with arbitrary priority.
3. Include the resulting JAR in a WAR.
4. Use the interceptor in the WAR application.
5. Deploy the WAR into Payara.
6. Observe the interceptor not being active.

### Reproducing with sample application
1. Start Payara 171/164
2. Build [the sample application](https://github.com/Pscheidl/InterceptorBug) by ./gradlew build
3. Deploy the sample application
4. Call the JAX-RS test endpoint http://{ip}:{port}/{application-context}/test. E.g. http://localhost:8080/payara-interceptor-bug-1.0/test

### Samples

There is a [sample application](https://github.com/Pscheidl/InterceptorBug) demonstrating the issue. Detailed description is in README.

## Context 
Creating a common library with an interceptor automatically handling exceptions and transforming them into an empty Optional.

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Full and Web
- **JDK Version**: JDK 8 (Oracle/OpenJDK).
- **Operating System**: Linux (Ubuntu 16.04).

## Related
The same issue was raised on GLASSFISH JIRA : https://java.net/jira/browse/GLASSFISH-21718

**Comment by lprimak** [comment]
Hi, Pavel,

Do you think this is a Weld issue by any chance?  You might be better off reporting it to them if it is.
For example, does this work in WildFly?

**Comment by Pscheidl** [comment]
Yes, it works in WildFly and also in TomEE . I am sorry I did not put the information here, but in the sample project, there is this info:

- GlassFish 4.1.2 not working
- Payara 171 not working
- WildFly final versions 8 - 10 working
- TomEE 7.0.2 (all the versions) - working

Weld versions inside:
- Glassfish 4.1.2: Weld 2.2.13.Final
- Payara 171: Weld 2.4.1.Final
- WildFly 10.1.0: Weld 2.3.5.Final
- No Weld in TomEE

**Comment by Pscheidl** [comment]
InterceptorManager does not know about the interceptor class.

![snimek obrazovky porizeny 2017-04-16 18-00-49](https://cloud.githubusercontent.com/assets/8769110/25072452/b5793d00-22ce-11e7-81f9-edafef5ea27d.png)

**Comment by lprimak** [comment]
Thanks for the info. It is helpful

**Comment by lprimak** [comment]
Internal issue PAYARA-1584

**Comment by smillidge** [comment]
Is the beans.xml file in the external dependency jar or the war?

**Comment by lprimak** [comment]
Whatever it is it should be the same in Weld, so it shouldn't be different with WildFly vs. Payara etc.  Just a guess though.

**Comment by jGauravGupta** [comment]
Bean.xml in external dependency : https://github.com/Pscheidl/FortEE/blob/master/src/main/resources/META-INF/beans.xml

**Comment by Pscheidl** [comment]
Beans.xml is in both. 
### JAR tree
beans.xml discovery mode is set to annotated. 

Structure of the resulting JAR:
```text
├── cz
│   └── pscheidl
│       └── fortee
│           ├── event
│           │   └── ExecutionError.class
│           ├── extension
│           │   └── FortExtension.class
│           ├── Failsafe.class
│           ├── FailsafeInterceptor.class
│           └── logging
│               ├── ForteeLogger.class
│               └── LoggerProducer.class
└── META-INF
    ├── beans.xml
    ├── MANIFEST.MF
    └── services
        └── javax.enterprise.inject.spi.Extension
```

### WAR tree
The sample WAR application has bean discovery mode set to "all". The real-world application I discovered the bug on has "annotated".

```text
.
├── META-INF
│   └── MANIFEST.MF
└── WEB-INF
    ├── beans.xml
    ├── classes
    │   └── cz
    │       └── pscheidl
    │           └── test
    │               ├── ApiConfig.class
    │               ├── Endpoint.class
    │               └── SomeBean.class
    └── lib
        ├── fortee-0.2.2.jar
        └── slf4j-api-1.7.25.jar
```

**Comment by Pscheidl** [comment]
I used a local SNAPSHOT version to test it with beans.xml discovery mode set to "ALL" in the JAR. **The problem remains**. 

Here is the exact beans.xml used:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="all">

</beans>
```

**Comment by Pscheidl** [comment]
The class itself does not seem to be loaded indeed. I tried to enable it in one more different way accordign to CDI spec:

```text
Interceptors enabled using @Priority are called before interceptors enabled using beans.xml.

An interceptor is said to be enabled if it is enabled in at least one bean archive or is listed in the final list of interceptors for the application, as defined in AfterTypeDiscovery event.
```

So I did:

```java
    public void observeAfterTypeDiscovery(@Observes AfterTypeDiscovery afterTypeDiscovery) {
        afterTypeDiscovery.getInterceptors().add(FailsafeInterceptor.class);
    }
```

To no avail. The interceptor is not enabled.

**Comment by Pscheidl** [comment]
The problem is resolved by using `bean-discovery-mode=all` in beans.xml in the JAR. This way, the interceptor is discovered and every single way of enabling it **starts to work**. 

Otherwise, the beans.xml in the JAR archive is completely empty. It looks exactly like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="all">

</beans>
```

Also, I discovered that the same way, a Producer method was not discovered and CDI (Weld) threw `UnsatisfiedDependencyException`. After using the `bean-discovery-mode=all`, the producer problem was solved as well.

This makes me think this could be an **issue of WELD**. However, the versions of Weld in other AS do not really confirm this (see my previous comments).

**Comment by ScoobyMax** [comment]
solve it with adding dependency

                 <dependency>
			<groupId>javax.interceptor</groupId>
			<artifactId>javax.interceptor-api</artifactId>
			<version>1.2</version>
		</dependency>
		
		<dependency>
			<groupId>net.bull.javamelody</groupId>
			<artifactId>javamelody-core</artifactId>
			<version>1.70.0</version>
		</dependency>
