### ISSUE TITLE
Payara x Linux SWAP

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1535]
Hi,

My app runs CentOS6 64 bits + JDK 1.8.112 + Payara 4 164 + JSF2.2 + RichFaces4 + CDI/Weld + DeltaSpike + Hibernate4 + PostgreSQL9.6. My server has 4 CPUs + 10 Gb RAM + 1 Gb SWAP (this SWAP is a restriction from the cloud provider).

I have these JVM options:
-server
-Xmx8192m
-XX:PermSize=512m
-XX:MaxPermSize=6144m
other default options.

The problem is with SWAP, I don't know why Payara process uses SWAP so rapidly, and sometimes I have RAM free, but it continues to use SWAP. For example, now using "htop" I see that Payara is using 5 Gb de RAM, using "free" I see the 5 Gb not used.

Using "smem -t -p": 921 root     /usr/java/jdk1.8.0_112/bin/   75.40%   53.16%   53.17%   53.24% (75.40% de SWAP used).

What is the JVM or other Payara config to do for better RAM using, without need to use SWAP?

**Comment by mikecroft** [comment]
Discussion continuing on Payara Forum:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/payara-forum/SQiSHgDnxJs
