### ISSUE TITLE
Timeout error on asadmin stop-domain

### ISSUE THREAD

**Issue by angtes** [payara/Payara#1547]
When I try to stop a domain, if it takes more than 1 minute, I receive the following error: "Timed out (60 seconds) waiting for the domain to stop.", but finally after a few seconds the domain stops.

I have seen the source code of com/sun/enterprise/admin/servermgmt/cli/StartDomainCommand.java and the timeout is harcoded to 1 minute: WAIT_FOR_DAS_TIME_MS = 60000

Would it be possible that this value will be configurable with an environment variable or with asenv.conf?

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 1.8.0_121 - Oracle
- **Operating System**: Linux (CentOS 6.9)

**Comment by MattGill98** [comment]
Hi @angtes,

This sounds strange. Do you have any more details about what might be causing this? Is it the same with other applications? Have you tried running the same application on the <code>payaradomain</code> template instead of the <code>domain1</code> template? I can make a task for configuring the timeout, but it would be good to get to the bottom of what's causing this error for you, as it's likely that something isn't shutting down correctly.

Kind regards,
Matt

**Comment by angtes** [comment]
Hi Matt Hill,
The DAS stop correctly. I run asadmin stop-domain and receive the timeout error, buf after a few seconds I see that the DAS has been stopped.
We have enabled Security Manager. If Security Manager is disabled the DAS stop in a few seconds.
I know it’s not the usual, but in our DAS we have more tan 700 applications. With fewer applications the DAS stop quickly.
I’ve seen that the 60 seconds of timeout is hardcoded in com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java file (WAIT_FOR_DAS_TIME_MS = 60000)
I’ve attached a simple war file so you can easily reproduce the case following these steps:
[test.zip](https://github.com/payara/Payara/files/1021571/test.zip)

* Do a clean install and start payaradomain
        asadmin start-domain payaradomain 

* Enable secutity manager:
        asadmin create-jvm-options "-Djava.security.manager" 

* Restart the DAS. 
        asadmin stop-domain; asadmin start-domain payaradomain

* Deploy the sample application
        for I in {1..800}; do  asadmin deploy --name test${I} --contextroot /test${I} test.war; done

* Create JDBC connection pool and resource
        for I in {1..800}; do asadmin create-jdbc-connection-pool --datasourceclassname=oracle.jdbc.pool.OracleConnectionPoolDataSource --restype=javax.sql.ConnectionPoolDataSource  --steadypoolsize=4 --maxpoolsize=10 --property "user=xxxx:password=xxxx:url=jdbc\\:oracle\\:this\\:@host\\:1521/test" test${I}; done

        for I in {1..800}; do asadmin create-jdbc-resource --target server --connectionpoolid test${I} jdbc/test${I}; done

* Stop DAS
       asadmin stop-domain payaradomain

Got this message:
Waiting for the domain to stop ...........................................................
Timed out (60 seconds) waiting for the domain to stop.
Command stop-domain failed.

**Comment by MattGill98** [comment]
Hi @angtes,

I do think the slow shutdown time is to do with having such a large number of deployed applications. Is there any potential workaround to having this many deployed, like maybe running them split amongst several clusters? If not, you've already drilled down enough to potentially make a pull request addressing this scenario! If you do want to do this, you can find more information here: https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md.

Kind regards,
Matt

**Comment by angtes** [comment]
Hi @MattGill98,

In our production environment we have the same applications with 33 clusters, 68 instances and 4 nodes and the DAS stop in 10 seconds.

The problem is in our development environment. We use "dynamic reloading"  so all the applications have to be running in the DAS to use dynamic reloading. We are planning to disable "dynamic reloading", use several clusters and use "dynamic reconfiguration". It's not the same but probably all go better.

Despite this, the error it's no critical. We can run a script to stop the domain, and check if the DAS has been stopped correctly and wait untill finished.

Thanks for all 
Best regards

**Comment by mikecroft** [comment]
Hi @angtes thanks for the update! That's a very interesting setup you have! I think your script workaround would be the best solution here, your use case is very unique so adding a feature like this is probably not something we would be able to schedule easily.

**Comment by MattGill98** [comment]
Hi @angtes,

Thank you for your response. As an alternative to a script, there is an option on <code>stop-domain</code> which is <code>--kill true</code>. This might provide the functionality you're looking for.

Hope this helps,
Matt
