### ISSUE TITLE
Servlet request is executed twice if timeout occurs while waiting for jdbc call

### ISSUE THREAD

**Issue by ionutursuleanu** [payara/Payara#1548]
# Description #
----------

Servlet request is executed twice if timeout occurs while waiting for jdbc call

## Expected Outcome

If a request takes too long to respond & timeout is reached then it shouldn't try to run the request second time.

## Current Outcome

If Payara has a 60 seconds request timeout & the request has to run for 100 seconds, for example, the following happens:
- initial request starts & runs for 100 seconds;
- a second identical request is dispatched & runs for 100 seconds

This is happening while running Payara NOT in debug mode. If the jdbc call is replaced with sleep the second request is not dispatched, as expected.

All the above could be tested with the attached eclipse project sample.
[Sample.zip](https://github.com/payara/Payara/files/947119/Sample.zip)
![requesttimeout](https://cloud.githubusercontent.com/assets/6136404/25279035/dd1e3198-26ad-11e7-8d7e-c8def543b656.png)

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8 - Oracle
- **Operating System**: Windows / Linux

**Comment by michaelranaldo** [comment]
Created internal issue PAYARA-1620

**Comment by bit-ionutursuleanu** [comment]
Do you have any progress on this one?

**Comment by michaelranaldo** [comment]
Hi @bit-ionutursuleanu , we have created internal issue PAYARA-1620 which will be looked at before the next release as we prioritise work on customer tickets. If you would be interested in purchasing support have a look at our site http://www.payara.fish/support

**Comment by smillidge** [comment]
Resolved by Grizzly upgrade in 5.182
