### ISSUE TITLE
Getting Started documentation should reference configuring domains and credentials

### ISSUE THREAD

**Issue by DaveJarvis** [payara/Payara#1549]
# Description #
----------

The [Getting Started Guide](https://github.com/payara/Payara/wiki/Getting-Started) is incomplete.

## Expected Outcome

Documentation shows how to create a domain and set the administrator account login and password.

## Current Outcome

After step 4 of the getting started guide, the user is greeted with:

![login](https://cloud.githubusercontent.com/assets/2131950/25293354/5cd6ec5a-268f-11e7-8354-9c8e3742f130.png)

However, the documentation neither describes nor links to additional information about how to:

- Create a domain
- Set the administrative account credentials
- Find the current admin account credentials

If these are assumptions that the person installing should already know, then that must be clearly stated in the documentation.

## Resolution

This could be as simple as adding another step for creating and configuring a domain.

```
./asadmin create-domain --adminport 4848 domainname
./asdamin start-domain domainname
```

It could also be as simple as stating that the default credentials for the default domain (`domain1`) are `admin` with no password.

Or reference the [Glassfish page](https://docs.oracle.com/cd/E19798-01/821-1751/ggoei/index.html). ;-)

## Additional Notes

Instructional videos are nice, but have a disadvantage: they typically require headphones so as not to disturb others in a professional work environment. If a person doesn't have headphones, or is deaf, then playing back the video (without sound) is not going to be helpful. Technical documentation (e.g., a web page or PDF) should have sufficient information to install and configure the application without having any previous knowledge of how the application works.

**Comment by mikecroft** [comment]
Hi @DaveJarvis thanks for raising this - the "getting started" guide was originally intended to serve brand new users of Payara Server, but I can see how this can all be very useful too.

The reason for the message is that, when a password is set, the admin console requires you to enter credentials. Because of this, it will not allow you to proceed without secure admin enabled, since that is how you force the admin console to use HTTPS rather than insecure HTTP.

Unfortunately we are not able to use "deep links" into Oracle documentation for legal/IP reasons, so we have to reproduce necessary documentation ourselves.

**Comment by DaveJarvis** [comment]
> Unfortunately we are not able to use "deep links" into Oracle documentation for legal/IP reasons, so we have to reproduce necessary documentation ourselves.

I highly doubt that would be legally enforceable. :-)

* http://www.linksandlaw.com/
* https://www.thoughtco.com/legalities-of-linking-3468972
* https://www.boutell.com/newfaq/creating/legallink.html

**Comment by OndroMih** [comment]
The Getting started guide linked in the description isn't available. Instead, information about getting started is available at https://www.payara.fish/documentation/getting-started-with-payara/ and in the reference documentation at https://docs.payara.fish/.

Information about how to create a domain is covered in https://docs.payara.fish/documentation/payara-server/production-ready-domain.html.

More information about securing Payara Server is on our blog: https://blog.payara.fish/topic/security
