### ISSUE TITLE
Issue with context lookup

### ISSUE THREAD

**Issue by baldodavi** [payara/Payara#1552]
# Description #
----------
Sometimes, without a specific pattern, payara stop response to any kind of request involve context lookup without any kind of error of exception. Sometimes server stop work definitively and stop to response also to simple request like images stored in docroot.

To restart application sometimes a reload is good. Sometimes a redeploy is needed. Sometimes a manual stop of server is mandatory. During one of these actions payara start to log many exceptions concering only context:

javax.naming.NamingException: Lookup failed for 'java:app/jdbc/redevodb' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.osjava.jndi.root=classpath://config, osjava.jndi.delimiter=/, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: bject bound to name java:app/jdbc/redevodb]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: Oracle build 1.8.0_121-b13
- **Operating System**: Linux

**Comment by fturizo** [comment]
Greetings @baldodavi. Can you provide more details about your application? The exception you posted refers to the use of JNDI lookups to managed resources. Does your application make heavy use of EJBs or special managed resources (JCA, JMS, Mail, JDBC, etc.)? Can you provide a sample reproducer to understand better the problem you are having?

**Comment by baldodavi** [comment]
Application has two EJB and one WAR joined in an Enterprise Application. WAR is an interface without any directly DB involving. EJBs deeply involve context usage.
Application use JNDI code by an our own external lib.
It's really not simple to produce a sample because external database is involved using not sharable configuration datas. Here [PgStoredExecutor.sample.txt](https://github.com/payara/Payara/files/970516/PgStoredExecutor.sample.txt) you can find a code sample used to call stored and so on from PostgreSQL DB.

Here you can find a more complete stacktrace.

`02-05-2017 14:49:50 WARN  [http-thread-pool(5)] (MatchManagement.java:289): RedevoServer-ejb -----> com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
javax.naming.NamingException: Lookup failed for 'java:app/jdbc/redevodb' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.osjava.jndi.root=classpath://config, org.osjava.jndi.delimiter=/, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: No object bound to name java:app/jdbc/redevodb]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at it.redevogames.redevolib.classes.PgStoredExecutor.getConnection(PgStoredExecutor.java:384)
        at it.redevogames.redevolib.classes.PgStoredExecutor.executeNoReturnFunction(PgStoredExecutor.java:595)
        at it.redevogames.redevolib.classes.database.DatabaseHelper.executeNoReturnFunction(DatabaseHelper.java:278)
`
Please let me know if something else is needed.
David.

**Comment by fturizo** [comment]
@baldodavi, how are you defining the JDBC resource on the server? Can you successfully do a ping using the connection pool to validate that the data source is correctly configured? If you can, attach an excerpt of the resource's configuration on your _domain.xml_ as well.

**Comment by Mephysto666** [comment]
Hi @fturizo, we have configured JDBC connection pool as application resouce by glassfish-resources.xml. This is its content:

```
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Resource Definitions//EN" "http://glassfish.org/dtds/glassfish-resources_1_5.dtd">
<resources>
  <jdbc-resource enabled="true" jndi-name="jdbc/redevodb" object-type="user" pool-name="RedevoDBPool">
    <description/>
  </jdbc-resource>
  <jdbc-connection-pool allow-non-component-callers="false" associate-with-thread="false" connection-creation-retry-attempts="0" connection-creation-retry-interval-in-seconds="10" connection-leak-reclaim="false" connection-leak-timeout-in-seconds="0" connection-validation-method="custom-validation" datasource-classname="org.postgresql.ds.PGConnectionPoolDataSource" fail-all-connections="false" idle-timeout-in-seconds="300" is-connection-validation-required="true" is-isolation-level-guaranteed="true" lazy-connection-association="false" lazy-connection-enlistment="false" match-connections="false" max-connection-usage-count="0" max-pool-size="32" max-wait-time-in-millis="60000" name="RedevoDBPool" non-transactional-connections="false" ping="false" pool-resize-quantity="2" pooling="true" res-type="javax.sql.ConnectionPoolDataSource" statement-cache-size="0" statement-leak-reclaim="false" statement-leak-timeout-in-seconds="0" statement-timeout-in-seconds="-1" steady-pool-size="8" transaction-isolation-level="read-uncommitted" validate-atmost-once-period-in-seconds="0" validation-classname="org.glassfish.api.jdbc.validation.PostgresConnectionValidation" validation-table-name="pg_catalog.pg_roles" wrap-jdbc-objects="true">
    <property name="User" value="${postgres_user}"/> 
    <property name="Password" value="${ALIAS=aptredevo_pwd}"/>
    <property name="databaseName" value="redevolution"/>
    <property name="serverName" value="${postgres_host}"/>
    <property name="PortNumber" value="${postgres_port}"/>
    <property name="applicationName" value="RedevoServer"/>
  </jdbc-connection-pool>
</resources>`
```

Ping are working done at the moment.

Very kind regards.

Meph

**Comment by fturizo** [comment]
Apologies for not revisiting this issue sooner, @Mephysto666. Is the problem still persisting on the current version of Payara Server? I'll try to reproduce with the sample configuration file that you have provided.

**Comment by Mephysto666** [comment]
Hi Fabio,
we no longer had experienced the issue.

So, thank you very much for your time.

Best regards.

Meph

**Comment by fturizo** [comment]
No problem @Mephysto666. I'll close this issue then.
