### ISSUE TITLE
Admingui get wrong url after reload an application

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1556]
Admingui get a wrong url (without host:port) after reload an application.

## Expected Outcome

After a successfull reload, automatically refresh the applications view.

## Current Outcome

An empty rectangle on the location of applications table.

## Steps to reproduce 

- Login to the secure admin in the browser
- Goto the applications menu
- In the applications table, click the "reload" link next to any application item

The net traffic in Firebug, after the reload process successfully completed:
- HTTP POST: https://host:port/common/applications/applications.jsf (302)
- HTTP GET: https://common/applications.jsf?alertType=success&alertSummary=Restart+request+sent+successfully.&alertDetail=&bare=true (infinite, no response)
- HTTP OPTIONS: https://common/applications.jsf?alertType=success&alertSummary=Restart+request+sent+successfully.&alertDetail=&bare=true (503)

You can see that missing the host (domain) and port from the last url-s.
To refresh the GUI, we need to refresh the browser again.
The deploy/redeploy link work normally.

## Context

Secure admin option switched on (I do not know if it's important).

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Full
- **JDK Version**: 8u121 - Oracle
- **Operating System**: Windows

**Comment by MattGill98** [comment]
Hi Zoltan,

You're in luck! This has recently been fixed in #1529, so the reload button should now work correctly. The fix is due to be released in Payara Server 172, but you can preview it by using one of our pre-release builds: http://www.payara.fish/upstream_builds. I'll close this issue as it's already been fixed.

**Comment by z-mathe** [comment]
Hi Matt,
Sorry, I was looking badly (not found this: #1522 about relative/absolute link problem)
Good to hear, it's not a big mistake, we can wait for Q2 public release until May.
