### ISSUE TITLE
Entity inherited fields not returned to remote session bean

### ISSUE THREAD

**Issue by kpenrose** [payara/Payara#1589]
# Description #
----------

Entity classes that extend an abstract base class annotated with `@MappedSuperclass` when returned to a remote client don't contain correct values for properties in the abstract base class.

## Expected Outcome

Calling a session bean on payara from a remote client, which successfully locates the bean through JNDI, and successfully running a query against a database, expect values in inherited class to be populated with the correct values from the database.  In this case, the inherited fields are the version number, annotated in the abstract class as `@Version` and a UUID value.

## Current Outcome

The current outcome is an object which has all of the entity properties correctly populated with values from the database, but the inherited properties are incorrect.  Since I am using the `@Version` annotation to take advantage of JPA's optimistic locking, I'm unable to do any updates to the fetched object since the version number returned is always **0**, and not the actual value in that column in the database. The values for the inherited base are correct on the server, but on return to the client, the base class values are wrong.

## Steps to reproduce (Only for bug reports) 
1 - Prepare an Enterprise App in your favourite IDE.
2 - Create a `@MappedSuperclass` as follows:

```java
@MappedSuperclass
public abstract class AbstractEntity {

    @Column(name = "UUID")
    @Basic
    private String uuid;

    @Version
    @Column(name = "Revision")
    @Basic
    private long revision;

    public AbstractEntity() {
        uuid = UUID.randomUUID().toString();
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * @return entity's database primary key if persisted
     */
    public abstract Long getId();

    public long getRevision() {
        return revision;
    }

    public void setRevision(long revision) {
        this.revision = revision;
    }

    /**
     * @return true if this entity is persisted to database, false otherwise.
     */
    public boolean isPersisted() {
        return getId() != null;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof AbstractEntity) {
            return this.uuid.equals(((AbstractEntity) obj).uuid);
        }
        return false;
     }

    @Override
    public int hashCode() {
        return uuid.hashCode();
    }
}
```
3 -  Create a new entity class which extends this abstract base and implements `Serializable`: 

```java
public class ShiplistItem extends AbstractEntity implements Serializable, Comparable<ShiplistItem> {

    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)
    //if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(unique = true, nullable = false)
    private Long id;
    .....
```

4 -  Create a remote session bean which implements an interface, annotate as `@Remote`:

```java
@Remote(ShiplistItemFacadeRemote.class)
@Stateless
@SuppressWarnings("unchecked")
public class ShiplistItemFacade extends AbstractFacade<ShiplistItem> implements ShiplistItemFacadeRemote {
.....
```
Include a method to query your database and a method to update.

5 - Build and deploy EAR file to Payara.

6 -  Create a client which connects to remote session bean through JNDI.  Call the query method.  Verify that the data is correct on the server, observe that the data returned to the client is incorrect.  It may take one query/update cycle to see the error since the version number will need to be incremented at least once.

### Samples

There are two StackOverflow topics related to this:

- [Stackoverflow topic 1](http://stackoverflow.com/questions/38084425/entity-inherited-fields-not-loaded-in-java-remote-session-bean)
- [Stackoverflow topic 2](http://stackoverflow.com/questions/43873808/remote-ejb-and-jpa-version?noredirect=1#comment74789503_43873808)

## Context (Optional)
As stated above, attempting to use optimistic locking via a `@Version` annotation on a property fails when the property is on an abstract `@MappedSuperclass`.  To be clear, the values in the super class are returned from the database correctly, but when they are marshaled to the client, the values become initialized to defaults.

## Environment ##

Name:  server
Status:  Running Running
JVM:  JVM Report
Configuration:  server-config
Installation Directory:  /opt/payara41/glassfish
Installed Version:  Payara Server 4.1.1.161.1 #badassfish (build 63)
Secure Administration:  Enabled
Debug:  Not Enabled
Up Time:  4 Days
HTTP Port(s):  4848,8080,8181
IIOP Port(s)  3820,3920,3700
OS:  Linux intrepid 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Database:  SQL Server
Java:  java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by fturizo** [comment]
Greetings @kpenrose,

Apologies for the late reply. I implemented your instructions into a sample WAR application and a standalone application and I couldn't reproduce the issue you mentioned. Whenever I updated entities before after querying them on the remote client (i.e. the standalone application), I got the correct values for the revision field after it was updated. Are you making sure that the entities are correctly defined, correctly updated on the appropriate business methods and the exact classes (both the abstract parent and the Entity class) are shared correctly between the application and the client?

I can share my example with you so you can compare and help us identify if this is an issue.

**Comment by kpenrose** [comment]
Hi @fturizo,
I appreciate that you got back to me.  I have solved my immediate problem by putting the @Version field in each derived class.  A bit of extra work, but it was necessary to get past an important milestone.
I would like to see your example, and try it out in my environment.
Let me know where I can find it and I'll report my findings.

-- Kevin

**Comment by fturizo** [comment]
Greetings @kpenrose, apologies for the late response. Attached you will find a sample Maven multi-module project that contains both the Web and standalone applications I used to try to reproduce the error. Feel free to compare it to your current codebase and ask any questions you think might be related to the problem you are experiencing:

[GH1589-EJBJPAVersionTest.zip](https://github.com/payara/Payara/files/1078215/GH1589-EJBJPAVersionTest.zip)

**Comment by fturizo** [comment]
@kpenrose, have you been able to compare the sample project I uploaded with your application? Let us know if you found out some hint that could be causing the problem you are experiencing.

**Comment by fturizo** [comment]
Any news on this issue, @kpenrose ?

**Comment by kpenrose** [comment]
Sorry, I've not been able to test further.
