### ISSUE TITLE
Definable user roles on Admin Console

### ISSUE THREAD

**Issue by disap4m** [payara/Payara#1600]
# Description #
----------

Would it be possible to have a similar function as Oracle's Web Logic where users can be created and given specific roles within the container?

## Expected Outcome

Give users the ability to only deploy applications, or read-only access to view container configurations and log files.

This functionality will allow for better security and delegation for tasks.

## Current Outcome

Currently only admin can login and perform tasks, this is an issue when you want to lock down certain functionality within the container and still give users access for read-only and less invasive tasks.

## Context (Optional)

We have 3 departments that need access to the DAS;
Operations - Deployments
Development - Read-only/view log files
IT - Everything/Administration

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Full
- **JDK Version**: 7 u80 - Oracle
- **Operating System**: Linux
- **Database**: SQL Server

**Comment by mikecroft** [comment]
Hi,

I was sure that this was something we already had an open enhancement request for, but it seems we didn't! I've created internal issue `PAYARA-`1680` for the enhancement.

**Comment by fturizo** [comment]
@mikecroft, take a look at issue #1295, which requested a specific role to access the monitoring endpoint, which is a similar request to this one

**Comment by mikecroft** [comment]
Ah, thanks @fturizo! I knew I'd seen it before! I'll link the two internal issues. (`PAYARA-1680` and `PAYARA-1342`).

There is a slight difference between the two issues, but the same enhancement could resolve both.

**Comment by disap4m** [comment]
Thanks guys

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.
