### ISSUE TITLE
[Payara_patchedProject]  EclipseLink patch request

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#1612]
# Description #
----------
We encounter two major issues with eclipselink.  Both are related to cache coordination. I submitted both bug to the eclipselink community but they do not show any interest in solving these problems.

Since payara already use a patched version of eclipselink I were wondering if it's possible to address our two problem in the payara patched version. (We currently use a patched version of  the patched version.)

Both issues are very easy to solve. The first one is a very stupid NullPointerException (patch here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=508974).  **(EDIT: fixed in eclipselink 2.7.1)**

The second one is also very easy to fix : https://bugs.eclipse.org/bugs/show_bug.cgi?id=517079

**Comment by OndrejM** [comment]
Thanks for reporting here. It's true that we have to maintain a patched version with some fixes because the Eclipselink project is slow to fix bugs. We've added your request into our todo as item PAYARA-1710 and hope to add those fixes into Payara Server soon.

**Comment by maxencelaurent** [comment]
EclipseLink finally addresses the first issue.

The fix will be available in the 2.7.1 release

**Comment by smillidge** [comment]
Closing as 5.183 includes EclipseLink 2.7.3
