### ISSUE TITLE
Add a sources artifact for payara-embedded-*

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#162]
We use the embedded-all jar to run integration tests for our suite of applications. It would be really nice if there was sources variants of the artifact available as it would make debugging much much easier.

**Comment by phillipross** [comment]
:+1:   +1

**Comment by smillidge** [comment]
Also javadocs are missing

**Comment by smillidge** [comment]
This is actually quite tricky. Would you want the whole of the Payara source zipped up into one flat directory structure?

Also a question about javadocs. Would people want just the GFEmbedded or Payara Micro public apis in the javadoc. Alternatively all the Payara/GF internal classes javadocs?

**Comment by phillipross** [comment]
It definitely is tricky... we've been wanting this from glassfish and mojarra forever, but it was too much work for anybody to justify doing amongst all of the other priorities they have had.

Traditionally, we've not seen any value to having any partitioned set of source code.  We've just needed to be able to debug our apps, and then debug further down into the appserver's code to get more insight into what's happening.  Starting with a flat structure and just having one big source bundle would be a good start.

And for the javadoc bundle... we would want everything... both publically exposed and anything that is documented internally as well.  We know that a good bit of internal code is not documented, but anything is better than nothing :)

**Comment by dashorst** [comment]
Frankly the javadoc is superfluous, as the javadoc comes with the source. At least Eclipse and IntelliJ know how to download the source jar, and use the embedded JavaDoc from there.
