### ISSUE TITLE
setHeader doesn't overwrite the existing one with the same name but works like addHeader

### ISSUE THREAD

**Issue by jasonthinks** [payara/Payara#1628]
# Description #
----------
I call setHeader() of the HttpServletResponse to set Expires, Cache-Control and Pragma headers but found it gave me duplicate headers rather than overwrite the existing ones

## Expected Outcome

Cache-Control:max-age=1498503231100
Content-Length:21738
Content-Type:image/png;charset=UTF-8
Date:Fri, 26 May 2017 18:54:15 GMT
Expires:Fri, 02 Jun 2017 18:54:00 GMT
Expires:2 June 2017 18:54:15 GMT
Pragma:cache
Server:Payara Server  4.1.1.171.1 #badassfish
X-Content-Type-Options:nosniff
X-Frame-Options:ALLOW-FROM DENY
X-Powered-By:Servlet/3.1 JSP/2.3 (Payara Server  4.1.1.171.1 #badassfish Java/Oracle Corporation/1.8)
X-XSS-Protection:1; mode=block

## Current Outcome

Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Cache-Control:max-age=1498503231100
Content-Length:21738
Content-Type:image/png;charset=UTF-8
Date:Fri, 26 May 2017 18:54:15 GMT
Expires:Fri, 02 Jun 2017 18:54:00 GMT
Expires:0
Pragma:no-cache
Pragma:cache
Server:Payara Server  4.1.1.171.1 #badassfish
X-Content-Type-Options:nosniff
X-Frame-Options:ALLOW-FROM DENY
X-Powered-By:Servlet/3.1 JSP/2.3 (Payara Server  4.1.1.171.1 #badassfish Java/Oracle Corporation/1.8)
X-XSS-Protection:1; mode=block

## Steps to reproduce (Only for bug reports) 

```java
public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain chain) throws IOException, ServletException {

        Calendar inOneMonth = Calendar.getInstance();
        inOneMonth.add(Calendar.MONTH, 1);
        long expiry = inOneMonth.getTimeInMillis();

        HttpServletResponse httpResponse = (HttpServletResponse)servletResponse;
        httpResponse.setHeader("Pragma", "cache");
        httpResponse.setDateHeader("Expires", System.currentTimeMillis() + 604800000L);
        httpResponse.setHeader("Cache-Control", "max-age="+ expiry);
        for(String name: httpResponse.getHeaderNames()){
            System.out.println(name);
        }
        chain.doFilter(servletRequest, servletResponse);
    }
```
```xml
<filter>
     <filter-name>CacheControl</filter-name>
     <filter-class>com...........web.filter.CacheControlFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>CacheControl</filter-name>
    <url-pattern>/avatar.html</url-pattern>
</filter-mapping>
```

## Environment ##

- **Payara Version**: 4.1.1.171.1 #badassfish
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Mac
- **Database**: MariaDB

**Comment by fturizo** [comment]
Greetings @jasonthinks. Apologies for the late reply. I tried to reproduce this duplicate header behaviour with the sample and I couldn't get the current outcome you are encountering. Could you upload a sample project that exhibits this behaviour? Does your application use other mechanisms to interact with the HTTP request that could be causing this error (Struts, JSF, other third-party libraries, etc.)?

**Comment by mikecroft** [comment]
Hi @jasonthinks - do you have a test case which reproduces this issue?

**Comment by mikecroft** [comment]
Since we can't reproduce, we'll close this issue. @jasonthinks if you can provide a test case which shows the problem, please feel free to reopen this issue.
