### ISSUE TITLE
Create a domain template that removes all development-oriented osgi cruft

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#163]
The default domain template includes a whole bunch of configuration for development oriented osgi features. One of the first things we do is strip out all of these settings before putting them out in production. It would be nice if a more "optimized for production" template and that could be used when creating domains.

**Comment by davewinters** [comment]
#250

**Comment by davewinters** [comment]
payara domain template contains this these parameters stripped out of the domain along with other changes  see #281
