### ISSUE TITLE
Application xxx has no deployed Jersey applications

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#1631]
# Description #
----------

Payara Micro says an empty .war does not contain any _Jersey_ applications. I assume that it meant to be _JAX-RS_ here, i. e. a standard vs. a product.

## Expected Outcome

`Application xxx has no deployed JAX-RS applications`

## Current Outcome

`Application xxx has no deployed Jersey applications`

## Steps to reproduce (Only for bug reports) 

* Build an empty .war file.
* Deploy it using `java -jar payara-micro-4.1.2.172.jar --deploy empty.war`

**Comment by fturizo** [comment]
Created Internal JIRA Issue `PAYARA-1718`

**Comment by smillidge** [comment]
Fixed by #1641
