### ISSUE TITLE
Jersey is outdated

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#1636]
**Please update Jersey!**

Current Payara Micro 4.1.2.172 bundles Jersey 2.22.1, which is a really outdated version released on 16-Feb-2016 ! The latest Jersey bug fix version currently is 2.25.1 from 19-Jan-2017 and contains about one year of additional bug fixes! To provide at-most stability, every release of Payara should _always_ come with the latest bug fix build of Jersey.

For the LTS stream (Payara Micro 4.1.1.171.2) this should be Jersey 2.25.1 then.

Following the same logic, Payara's bleading-edge stream should always come with the latest feature releases of Jersey, hence 2.26-b04 then.

**Comment by mulderbaba** [comment]
@mjarg we have already 2 PRs on updating HK2 and Jersey, actual we were waiting to HK2 to be finalized since 2.25.1 depends on a newer version of it. I think you'll be getting the bits very soon in nightly builds and the upcoming quarterly release.

**Comment by mkarg** [comment]
@mulderbaba Where can I download Payara nightly builds?

**Comment by lprimak** [comment]
http://www.payara.fish/upstream_builds

**Comment by mkarg** [comment]
@lprimak Thanks! :-)

**Comment by fturizo** [comment]
@mkarg, since your question has been asked and we are tracking this issue on the support portal, I'm closing the issue.
