### ISSUE TITLE
Wrong path in build instructions for Payara Micro

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#1637]
[Build-Instructions](https://github.com/payara/Payara/wiki/Build-Instructions) contain a wrong path to Payara Micro: `cd appserver/extras/embedded/payara-micro`. At least for Payara 4.1.2.173-SNAPSHOT it must be `cd appserver/extras/payara-micro` instead. Also, it says "After the build has completed the Payara Micro jar is in the `target` directory." which is wrong. Actually, the distributable is found in the `payara-micro-distribution/target` directory.

**Comment by mikecroft** [comment]
Hi Markus, thanks for pointing that out! That page is actually out-of-date. We originally left it there when we migrated our documentation, but it seems like it's well past time to remove it!

Here's the updated link to the build instructions:
https://docs.payara.fish/build-instructions/build-instructions.html#building-payara-micro

**Comment by mikecroft** [comment]
I've disabled the old wiki now.
