### ISSUE TITLE
Allow disabling of iiop-service when MDBs present

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#164]
Essentially the MessageBeanContainer fails to start unless iiop-service is configured. This seems like an undesirable dependency. We typically disable all uneeded elements when going to production but have found we can not disable iiop-service if we use MDBs. 

This was initially reported in

https://java.net/jira/browse/GLASSFISH-21156

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1199` for the enhancement
