### ISSUE TITLE
Build EclipseLink Cache Interceptor for Hazelcast

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#165]
Now that Hazelcast is built in to the core of Payara it would be great to use it as a 2nd Level Caching provider for Eclipselink.

**Comment by phillipross** [comment]
+1

**Comment by davewinters** [comment]
Hazelcast provides support for a distributed  L2 cache for hibernate. I assume we need to extend hazelcast to provide support for eclipselink as an L2 cache provider??

**Comment by jerrinot** [comment]
@davewinters: not really. Hazelcast Hibernate is just a glue between Hazelcast and Hibernate. There is no Hibernate-specific code in core Hazelcast. 

I assume you will have to create a similar glue for EclipseLink. See this: https://github.com/hazelcast/hazelcast/tree/master/hazelcast-hibernate

**Comment by davewinters** [comment]
ok will have a look at the above code for reference

**Comment by abhirockzz** [comment]
Just adding a few inputs/references. 
- [Hazelcast official documentation](http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#hibernate-second-level-cache) is a good place to start to get more insight into Hazelcast-Hibernate L2 cache implementation
- The core solution revolves around extending the [EclipseLink CacheInterceptor](http://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/sessions/interceptors/CacheInterceptor.html) class and leveraging the already existing Hazelcast-Payara integration pieces to implement the logic
- What would also be needed is some additional configuration metadata to activate the Payara L2 cache interceptor implementation for every JPA entity
- What I noticed tough is that the eclipselink CacheInterceptor class javadoc is limited in the sense that it does not provide too much insight into how its method will be intercepted (sequence, events etc.)

It's very much possible that this is already know/figured out, but I added these anyway :-)

**Comment by smillidge** [comment]
Thanks Abhi. Not known yet as it is not under development on our side yet.

**Comment by phillipross** [comment]
I actually began working on a prototype of this some time ago using eclipselink's cache interceptor and cache key interceptor.  The javadocs for the interceptor classes are pretty sparse in the information that they offer, and it took a lot of trial and error and tracing to understand the interactions of the cache interceptor invocations with what was happening with eclipselink persistence functions.  It's fairly intricate.

What I found inelegant to this approach is that the interceptors need to be specified in the persistence.xml of each persistence unit for eclipselink to activate and use them.  The persistence.xml also contains the custom properties that can be read by the interceptors for configuring the hazelcast instance and per-entity policies.  This places a lot of responsibility on the application developers who are writing persistence.xml configurations to do the right thing.

I think tighter integration into Payara itself would be better, but I'm not sure what integration points would make sense.

**Comment by abhirockzz** [comment]
@phillipross  That's precisely my feedback as well !

The CacheInterceptor javadocs offer little or no insight. Configuration is also something that needs some thought. Off the top of my head, this is what I can imagine
- Maybe using a CDI extension to add the @CacheInterceptor(CustomPayaraInterceptor.class) during bootstrap to every JPA entity. This needs to be configurable of course (in case custom interception needs to toggled per JPA entity)
- Hazelcast related config: Per entity/per PUnit etc. ? This needs to be hashed out as well

**Comment by OndrejM** [comment]
It might also be worth to explore the option of writing a custom cache coordination mechanism. It should be possible to extend `BroadcastTransportManager` and provide it via [eclipselink.cache.coordination.protocol](https://github.com/eclipse/eclipselink.runtime/blob/31f3f3b3d73cee80160edcb07338d57ab08660df/jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java#L2226) property (COORDINATION_PROTOCOL constant).

It should be easy to copy the behavior of `JMSPublishingTransportManager` to publish commands via Hazelcast.

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-223`

**Comment by vanuatoo** [comment]
I was not able to set up EclipseLink Cache Coordination using JMS.
If this is implemented as Hazelcast extension I guess it's achievable.
Is there any target period for this feature to be implemented?

**Comment by lprimak** [comment]
I have long implemented L2 cache w/EclipseLink and JMS for my other clients.
It was fairly simple and was working great, so Hz should be an easy addition

**Comment by vanuatoo** [comment]
Could you briefly describe the architecture of the cluster?
https://groups.google.com/forum/#!topic/payara-forum/45swSOsuvlg
This is my approach and I could not get it working.

**Comment by lprimak** [comment]
I aught to write a blog post about it, it's pretty complex to describe in isolation right now

**Comment by vanuatoo** [comment]
I would appreciate that very much. Thanks in advance.
