### ISSUE TITLE
Ship payara full also as tar gz

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#1663]
# Description #
----------

It would be nice for docker Images, if the payara-full.zip would also be available as tar.gz Archive.
Docker is automatically unzipping these archives.
with ZIP Files the developer has to install unzip and unzip manually in Dockerfile.
The docker image would be smaller also with tar.gz file, there is no unused zip file.

## Expected Outcome
payara-full.tar.gz as download
## Current Outcome
no payara-full.tar.gz as download

**Comment by mikecroft** [comment]
Created `PAYARA-1807` for the enhancement

**Comment by mikecroft** [comment]
Scheduled for next release
