### ISSUE TITLE
Cannot Disable "Dynamic" setting of Hazelcast Configuration

### ISSUE THREAD

**Issue by Pandrex247** [payara/Payara#167]
The "Dynamic" setting of the Hazelcast configuration cannot be disabled. 
* Unchecking the box in the Admin Console and saving does not work; navigating away and back to the page will show it as enabled again.
  * There will also be no change in the domain.xml
* Using the _set-hazelcast-configuration_ asadmin command does not make any change to the domain.xml
  * The Admin Console will also still show the setting as enabled
* Adding "dynamic="false"" or "dynamic="disabled"" to the domain.xml between the <_hazelcast-runtime-configuration_> tags does not change the behaviour listed above

**Comment by smillidge** [comment]
Dynamic is not a "stored" configuration setting it just means when you make a change do you want Hazelcast to be restarted immediately or do you want to wait for a whole Payara server restart before the change is applied.
