### ISSUE TITLE
evaluate Environment Variables in Postbootcommandfile

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#1671]
# Description #
----------

I tried to use the new feature (payara full version) with 
`ENTRYPOINT asadmin start-domain --verbose --postbootcommandfile /opt/deployApp.cli`
In general it works, but there is no evaluation in the Postbootcommandfile.
This is now the feature request, so that this works:

parent Dockerfile (preparing my payara):

FROM alpine:latest
ADD payara/payara-4.1.2.172.zip lib/ojdbc7.jar target/classes/de/otto/verfuegbarkeit/payara/setupPayara.cli /opt/
RUN apk update && apk upgrade && \
    apk --no-cache add --update openjdk8 curl unzip tzdata && \
    ln -s /usr/lib/jvm/java-1.8-openjdk /opt/java && \
    rm -rf /var/cache/apk/* && \
    cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone && \
    unzip /opt/payara-4.1.2.172.zip -d /opt/ && rm /opt/payara-4.1.2.172.zip && mv /opt/payara41 /opt/payara && \
    rm -Rf /opt/payara/glassfish/domains/domain1 && \
    mv /opt/ojdbc7.jar /opt/payara/glassfish/domains/payaradomain/lib && \
    chmod a+rwx -R /opt/
ENV JAVA_HOME=/opt/java PATH="$PATH":/opt/java/jre/bin/ DEPLOYMENT_DIR=/opt/

WORKDIR /opt/payara/bin/
RUN /opt/payara/bin/asadmin start-domain && \
    /opt/payara/bin/asadmin multimode --file /opt/setupPayara.cli && \
	rm -f /opt/setup_payara.cli && \
    /opt/payara/bin/asadmin stop-domain
ENTRYPOINT asadmin start-domain --verbose --postbootcommandfile /opt/deployApp.cli
EXPOSE 8080 8181

Application Dockerfile:

FROM my-microservice
ENV application="myapp"
ADD target/${application}.war ${DEPLOYMENT_DIR}

in setupPayara.cli is sth like "create-jdbc-connection-pool ..." and file deployApp.cli looks like this:
`deploy /opt/${application}.war`
## Expected Outcome
the file deployApp.cli evalueates the environment variable from Application Dockerfile and the myapp.war is deployed.

## Current Outcome
File /opt/${application}.war cannot be found.

## Steps to reproduce (Only for bug reports) 
see above

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: full
- **JDK Version**: 8
- **Operating System**: alpine (Docker)
- **Database**: does'nt matter

**Comment by MattGill98** [comment]
Hi @deratzmann,

The post boot commands currently don't support the inclusion of environment variables, I'll make an enhancement request to add this feature. In the meantime, if you want to automatically deploy files from a directory on startup, look at the way it is done in the official Payara Server Full Docker image: https://github.com/payara/docker-payaraserver-full. Alternatively, it may be easier to use the official image unless your use case demands otherwise! 😄

I hope this helps,

Matt
