### ISSUE TITLE
ORBServerHost JVM option ignored

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1673]
Hi,

In our corba client-server communication model, important criteria, that based on hostname instead of IP address. We have a "-Dcom.sun.corba.ee.ORBServerHost=${ORB_SERVER_HOST}" JVM option, that ensures this.
This option in Glassfish v3.1.2 works good, but in Payara versions (171/172) there's no effect, in lookup process the reply GIOP message of the server contains the IP address in the private network (eg. 192.168.104.92) and not the expected hostname.

IP address not exists in the domain.xml, how to enforce the hostname usage?

The console output of a test lookup j2se application from client (192.168.0.67) side with -Dcom.sun.CORBA.ORBDebug=giop option:
```
corbaname:iiop:{IIOP_HOST}:{IIOP_PORT}#ejb/TestSFBean
+++++++ Output Buffer ++++++++

Current position: 304
Total length : 1024

47 49 4f 50 01 00 00 00 00 00 01 24 00 00 00 03 GIOP.......$....
00 00 00 11 00 00 00 02 00 02 00 00 4e 45 4f 00 ............NEO.
00 00 00 02 00 14 00 00 00 00 00 06 00 00 00 aa ...............?
00 00 00 00 00 00 00 28 49 44 4c 3a 6f 6d 67 2e .......(IDL:omg.
6f 72 67 2f 53 65 6e 64 69 6e 67 43 6f 6e 74 65 org/SendingConte
78 74 2f 43 6f 64 65 42 61 73 65 3a 31 2e 30 00 xt/CodeBase:1.0.
00 00 00 01 00 00 00 00 00 00 00 6e 00 01 02 00 ...........n....
00 00 00 0d 31 39 32 2e 31 36 38 2e 30 2e 36 37 ....192.168.0.67
00 00 e1 9c 00 00 00 19 af ab cb 00 00 00 00 02 ..??....???.....
9d 1f 51 e4 00 00 00 08 00 00 00 00 00 00 00 00 ?.Q.............
14 00 00 00 00 00 00 02 00 00 00 01 00 00 00 20 ................
00 00 00 00 00 01 00 01 00 00 00 02 05 01 00 01 ................
00 01 00 20 00 01 01 09 00 00 00 01 00 01 01 00 ................
00 00 00 26 00 00 00 02 00 02 00 00 00 00 00 05 ...&............
01 00 00 00 00 00 00 0b 4e 61 6d 65 53 65 72 76 ........NameServ
69 63 65 00 00 00 00 06 5f 69 73 5f 61 00 00 00 ice....._is_a...
00 00 00 00 00 00 00 28 49 44 4c 3a 6f 6d 67 2e .......(IDL:omg.
6f 72 67 2f 43 6f 73 4e 61 6d 69 6e 67 2f 4e 61 org/CosNaming/Na
6d 69 6e 67 43 6f 6e 74 65 78 74 3a 31 2e 30 00 mingContext:1.0.
++++++++++++++++++++++++++++++
MessageBase(SelectorThread): .readGIOPHeader: 1/GIOPReply
MessageBase(SelectorThread): .readGIOPHeader: GIOP header is: 
----- Input Buffer -----

Current position: 0
Total length : 12

47 49 4f 50 01 00 00 01 00 00 01 ca             GIOP.......?
------------------------
MessageBase(SelectorThread): .readGIOPHeader: Message GIOP version: 1.0
MessageBase(SelectorThread): .readGIOPHeader: ORB Max GIOP Version: 1.2
MessageBase(SelectorThread): .readGIOPHeader: creating ReplyMessage
MessageBase(SelectorThread): .readGIOPHeader: header construction complete.
MessageBase(p: default-threadpool; w: Idle): .readGIOPBody: received message:
----- Input Buffer -----

Current position: 0
Total length : 470

47 49 4f 50 01 00 00 01 00 00 01 ca 00 00 00 02 GIOP.......?....
4e 45 4f 00 00 00 00 02 00 14 00 00 00 00 00 06 NEO.............
00 00 00 c8 00 00 00 00 00 00 00 28 49 44 4c 3a ...........(IDL:
6f 6d 67 2e 6f 72 67 2f 53 65 6e 64 69 6e 67 43 omg.org/SendingC
6f 6e 74 65 78 74 2f 43 6f 64 65 42 61 73 65 3a ontext/CodeBase:
31 2e 30 00 00 00 00 01 00 00 00 00 00 00 00 8c 1.0............?
00 01 02 00 00 00 00 0f 31 39 32 2e 31 36 38 2e ........192.168.
31 30 34 2e 39 32 00 00 83 a4 00 00 00 00 00 19 104.92..??......
af ab cb 00 00 00 00 02 00 00 00 64 00 00 00 08 ???........d....
00 00 00 00 00 00 00 00 14 00 00 00 00 00 00 04 ................
00 00 00 01 00 00 00 20 00 00 00 00 00 01 00 01 ................
00 00 00 02 05 01 00 01 00 01 00 20 00 01 01 09 ................
00 00 00 01 00 01 01 00 00 00 00 26 00 00 00 02 ...........&....
00 02 00 00 00 00 00 1f 00 00 00 04 00 00 00 03 ................
00 00 00 20 00 00 00 04 00 00 00 01 00 00 00 05 ................
00 00 00 03 00 00 00 2b 49 44 4c 3a 6f 6d 67 2e .......+IDL:omg.
6f 72 67 2f 43 6f 73 4e 61 6d 69 6e 67 2f 4e 61 org/CosNaming/Na
6d 69 6e 67 43 6f 6e 74 65 78 74 45 78 74 3a 31 mingContextExt:1
2e 30 00 00 00 00 00 01 00 00 00 00 00 00 00 a6 .0.............?
00 01 02 00 00 00 00 0f 31 39 32 2e 31 36 38 2e ........192.168.
31 30 34 2e 39 32 00 00 83 a4 00 00 00 00 00 4d 104.92..??.....M
af ab cb 00 00 00 00 20 00 00 00 64 00 00 00 09 ???........d....
53 31 41 53 2d 4f 52 42 00 00 00 00 00 00 00 02 S1AS-ORB........
00 00 00 08 52 6f 6f 74 50 4f 41 00 00 00 00 0d ....RootPOA.....
54 4e 61 6d 65 53 65 72 76 69 63 65 00 00 00 00 TNameService....
00 00 00 08 00 00 00 01 00 00 00 01 14 00 00 00 ................
00 00 00 02 00 00 00 01 00 00 00 20 00 00 00 00 ................
00 01 00 01 00 00 00 02 05 01 00 01 00 01 00 20 ................
00 01 01 09 00 00 00 01 00 01 01 00 00 00 00 26 ...............&
00 00 00 02 00 02                               ......
------------------------
+++++++ Output Buffer ++++++++ 
```
In Glassfish v3.1.2 the 'ReplyMessage' contains the hostname instead of the upper IP address.

In the level of JVM, we tried the next options too (without success):
-Dcom.sun.CORBA.ORBInitialHost=${ORB_SERVER_HOST}
-Dorg.omg.CORBA.ORBInitialHost=${ORB_SERVER_HOST}

Any idea?
Thank you in advance for the quick response.

## Environment ##

- **Payara Version**: 4.1.1.171, 4.1,2.172
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Windows

**Comment by lprimak** [comment]
We have changed CORBA behavior to support multi-homed hosts
This may have some impact on your situation, but not sure yet.
In latest versions of Payara, the GIOP address is taken from the actual client address that server sees it's connecting from

**Comment by z-mathe** [comment]
From which lastest versions exactly? As i wrote, it also appears in v171 community stream version (2017.02.20). Is it worth revisiting even earlier versions?
I just now upgraded an old Glassfish v3.1.2 dev system to the lastest Payara v172 (only with minimal changes in the original domain.xml to get started), the situation was same (phisical address instead of ORBServerHost).

**Comment by lprimak** [comment]
Added PAYARA-1753 to track this issue

**Comment by z-mathe** [comment]
I was looking at the org.glassfish.enterprise.iiop.impl.GlassFishORBManager class in Payara sources, and I wanted to log the "Setting orb server host to {serverHost}" sentence. Unsucessfully.
```
if (processType.isServer()) {
    validateIiopListeners();
    orbInitProperties.put(ORBConstants.NO_DEFAULT_ACCEPTORS, "true");
    // 14734893 - IIOP ports don't bind to the network address set for the cluster instance
    // GLASSFISH-17469   IIOP Listener Network Address Setting Ignored
    checkORBServerHost(orbInitProperties);
}
...
// Server host property is used only for ORB running in server mode
// Return host name (or ip address string) if the SERVER_HOST PROPERTY is set or
// network-address attribute is specified in iiop-listener element
// Return null otherwise.
private String checkORBServerHost(Properties props) {
...
if (serverHost != null) {
    // set the property, to be used during ORB initialization
    // Bug 14734893 - IIOP ports don't bind to the network address set for the cluster instance
    props.setProperty(ORBConstants.SERVER_HOST_PROPERTY, serverHost);
    if (logger.isLoggable(Level.FINE)) {
        logger.log(Level.FINE, "Setting orb server host to {0}", serverHost);
    }
}
...
```
logging.properties (what I was trying to do):
org.glassfish.enterprise.iiop.impl.GlassFishORBManager.level=FINE
org.glassfish.enterprise.iiop.impl.level=FINE
org.glassfish.enterprise.iiop.level=FINE

What have I done wrong? Am I looking for good or not?

Thank you.

**Comment by lprimak** [comment]
@z-mathe unfortunately none of this code is going to do you any good.
I believe I know where the sideffect happened and will get something out to fix this in the next couple of weeks

**Comment by z-mathe** [comment]
@lprimak I understand, this is some information for me. I'll look elsewhere. Thank you, have a nice work...

**Comment by z-mathe** [comment]
I replaced the glassfish-corba-orb.jar from Payara version 164 and so the corba orb ReplyMessage contains again the hostname (instead of IP address) configured by com.sun.corba.ee.ORBServerHost JVM option.  I will looking for the exact difference on the source level (compare v164 with the v171 and v172). I feel like I'm in the straight line...

**Comment by lprimak** [comment]
Yes, that will work.  There have been a lot of changes since .164 in CORBA to support multi-homed environments

**Comment by lprimak** [comment]
CORBA PR https://bitbucket.org/payara/glassfish-corba/pull-requests/11 will fix this issue in future releases of Payara
(patched CORBA) -p7 and subsequent

**Comment by lprimak** [comment]
for now, .164 CORBA module is a good workaround

**Comment by z-mathe** [comment]
Yes, we did it, but all 4 CORBA jars (the glassfish-corba-orb.jar itself was not enough stable):
- glassfish-corba-csiv2-idl.jar
- glassfish-corba-internal-api.jar
- glassfish-corba-omgapi.jar
- glassfish-corba-orb.jar

Thank you.

**Comment by lprimak** [comment]
Thanks, @z-mathe good to know.
This will be fixed in the next release
