### ISSUE TITLE
High Avaibility for jsf application

### ISSUE THREAD

**Issue by abdoinfopayara2017** [payara/Payara#1676]
Hi team,
I just started using payara server  4.1.2.172 because it is It is better than GlassFish 3.1.2 and I want to implements High Avaibility by deploy an JSF 2.1 application in cluster with two instances of payara server  4.1.2.172 in different machines.

I have seen this link: **http://mjremijan.blogspot.com/2017/04/high-availability-ha-session-replicated.html**  and it works fine if I deploy a page in jsp, but my problem, if I deploy a simple application developed with JSF 2.1 and if I launch the application in two tabs Navigator for example:

1. http://node1:280280/myapplication 
2. http://node2:28281/myapplication

I have this error message like:

>**javax.faces.application.viewexpiredexception viewid could not be restored**

I do not understand what happen but if I deploy simple Servlet it works fine.

**Comment by abdoinfopayara2017** [comment]
Environment:

Payara Version: 4.1.2.172
Edition: Full
JDK Version: 7 u 45
Operating System: Windows

**Comment by mikecroft** [comment]
What error message are you getting, exactly? What steps do you take to reproduce the error? How is your application configured? Can you share your simple application so we can see what's going wrong?

There is a very good overview of this exception on StackOverflow which might help:
https://stackoverflow.com/a/3642969/212224

**Comment by abdoinfopayara2017** [comment]
Hi ,
Ok ,so I have developed a simple application with glassfish 3.1.2 and I have used its library of  Mojarra 2.1.6 Which implements JSF 2.1 . 
For web page I have created once with PrimeFaces 5.1 and ViewScoped ManagedBean to control the view.
the page contains two elements : 
1. **p:commandeButton** : that implement a simple  function It is a matter of incrementing a variable type Integer for each click on the button (i++)
2. **p:outputLabel** to display the value incremented after click
When I finished reading this link: **http://mjremijan.blogspot.com/2017/04/high-availability-ha-session-replicated.html**  I have created successfully the cluster withe two instances in different machines and the replication between instances worked well if I deploy a simple page .jsp (I have the same ID session)
but if I deploy the jsf application (Which I have just mention on top) to test the High Availability after launching firstly the first link :  http://instance-1:280280/myapplication  and secondly the second link :  http://instance-2:282281/myapplication on two tabs Navigator The scenario is as follows:
so if I click on the button in the second link the value is incremented and is displayed on the page but if I click on the button in the first link no change occurs and in the log file I have this error : javax.faces.application.viewexpiredexception viewid=/Page.xhtml could not be restored.

Now I refresh the  first link and I click on the button the value is incremented and is displayed on the page but if I click on the button in the second link no change occurs and in the log file I have the same error : javax.faces.application.viewexpiredexception viewid=/Page.xhtml could not be restored and **Reciprocally** if I refresh the second like I have the same Scenario 

so  If you want more explanations you ask me
thanks.

**Comment by abdoinfopayara2017** [comment]
Hi,
I forgot to add this detail:
Just after the deployment I have this error message in the logs of two instances of payara server (instance-1 and instance-2)
**[[  Invalid Session Management Configuration for non-distributable app [test] - defaulting to memory: persistence-type = [replicated] / persistenceFrequency = [web-method] / persistenceScope = [session]]]**
 although I have added these lines to the file glassfish-web.xml:
`<session-manager persistence-type="replicated">
		<manager-properties>
		<property name="persistenceFrequency" value="web-method" />
		</manager-properties>
		<store-properties>		
		<property name="persistenceScope" value="session" />
		</store-properties>
   </session-manager>`

thanks

**Comment by smillidge** [comment]
Make sure you have the ```<distributable/>``` tag in your web.xml

**Comment by abdoinfopayara2017** [comment]
Yes l have add this tag in Web XML

**Comment by lprimak** [comment]
Payara 172 comes with JSF 2.2 and works with PrimeFaces 6 for distributed sessions correctly.

If your test is  using 
```
http://node1:280280/myapplication
http://node2:28281/myapplication
```

then it won't work because they will have different session cookie paths.

You need to create a "real" system, i.e. with a load balancer in front of it to correctly test your scenario

**Comment by abdoinfopayara2017** [comment]
Hi
About cookie paths I have add this tag to glassfish-Web.XML :  
**<cookie-properties>
      <property name="cookieDomain" value=".internal.dev"/>
    </cookie-properties>** 
But I will try to developpe My application with primefaces 6
Thanks

**Comment by abdoinfopayara2017** [comment]
' **<cookie-properties>
      <property name="cookieDomain" value=".internal.dev"/>
    </cookie-properties>**'

**Comment by abdoinfopayara2017** [comment]
cookie-properties
      
property name="cookieDomain" value=".internal.dev"
    
cookie-properties

**Comment by lprimak** [comment]
Also, in Payara is preferred to use hazelcast cluastering, 
and I would remove all the 
```
<session-manager>
```
sections from glassfish-web.xml

We've had customers where too many 'legacy' settings there would mess up clustering

**Comment by lprimak** [comment]
Also if you post a simple project here, it would make a lot easier to help you out
thanks!

**Comment by OndrejM** [comment]
Hi @abdoinfopayara2017,

@lprimak is correct, try to do what he suggested.

Especially, the suggestion of accessing the applications via a load-balancer is crucial. I'll explain. 

To make session replication work, both applications have to have access to the same session cookie so that they access the same session. Cookies are bound to URLs (without port number) in browsers, therefore application deployed at http://node1 will have a different session cookie than the one at http://node2. What happens is that each page would have a session on its own. That alone wouldn't cause the JSF error, it would just create 2 distinct sessions which don't replicate data.
You need a load balancer and access the applications via the same URL to connect to the same session and replicated data. 

Alternatively, you can deploy both applications on different cluster instances on localhost - in that case, the cookie will be the same (remember that port is ignored when matching a cookie to a URL), but applications would still be running on different JVMs (on the same system). Session replication would then work even without a load balancer.

The error received from JSF is another problem. I would say the reason behind it is that the first session is invalidated when you access the 2nd link, therefore the 1st link blows up. Do you sign in as a user? Does your application have some session invalidation logic, e.g. to enforce a single session for a user?

**Comment by abdoinfopayara2017** [comment]
Hi,
I have developed again my application with primefaces 6.1 and I have used JSF 2.2 Mojarra 2.2.14 witch implemented in payara server 4.1.2.172 . I have also installed nginx-1.12.0  on windows to create a "real" system, i.e. with a load balancer .
So the load balancer works fine but when nginx switch to the other instance that it was launched firstly in navigator I still have the same error : **javax.faces.application.viewexpiredexception viewid=/NewFile.xhtml could not be restored**
below the source code of my application :   

**NewFile.xhtml:**
```
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:p="http://primefaces.org/ui"
xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
</h:head>
<h:body>
<h:form id="form">
<p:panelGrid columns="3">
<p:commandButton value="add" actionListener="#{bean.add()}" update="form" />
<p:outputLabel value="#{bean.count}"/>
</p:panelGrid>
</h:form>
</h:body>
</html>
```

**ViewScoped ManagedBean:**
```
`package managed_bean;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
@ManagedBean
@ViewScoped
public class bean {	
	private int count=0;
	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}	
	public void add()
	{
		count=count+1;
		System.out.println(count);
	}
}
`
```
**Web.xml:**
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" id="WebApp_ID" version="3.0">
  <display-name>test_</display-name>
  <welcome-file-list>   
    <welcome-file>faces/NewFile.xhtml</welcome-file>
  </welcome-file-list>
  <servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
  </servlet-mapping>
  <distributable/>     
</web-app>
```

**glassfish-web.xhtml :** 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
    <context-root>/test_</context-root>    
     <session-config>			 
		 <cookie-properties>
					      <property name="cookieDomain" value=".internal.dev"/>
	     </cookie-properties>	    
	 </session-config> 
</glassfish-web-app>
```

**nginx.conf:**
```
upstream  cluster_1{
    server ezm.internal.dev:28080;
    
    server app-prod-backup.internal.dev:28081;
   
  } 
location / {
            root   html;
            index  index.html index.htm;
            proxy_connect_timeout   10;
            proxy_send_timeout  15;
            proxy_read_timeout  20;
            proxy_pass http://cluster_1;
        }
```

**the file hosts in two instances :** 
```
127.0.0.1 localhost
192.168.104.23 EZM.internal.dev EZM
::1 localhost
192.168.104.29 APP-Prod-Backup.internal.dev APP-Prod-Backup
192.168.121.57 K-DSI-B215-PC1.internal.dev K-DSI-B215-PC1
```

**the file hosts in the DAS :**
```
192.168.104.29   APP-Prod-Backup.internal.dev
192.168.104.23   EZM.internal.dev
192.168.121.57   K-DSI-B215-PC1.internal.dev

192.168.104.29   APP-Prod-Backup
192.168.104.23   EZM
192.168.121.57   K-DSI-B215-PC1
```

**Comment by smillidge** [comment]
Your bean needs to implement Serializable to enable replication.

**Comment by abdoinfopayara2017** [comment]
Hi
I have already tired this solution but did not Work

**Comment by abdoinfopayara2017** [comment]
Hi ,

wwwwooooooooooooooow, finally it is work fine the it is exactly explain by  **robelcik**  It should not be added librarys to folder WEB-INF/lib and the replication will works fine I have tested but now another problem appears : How to added librarys to our applications if we need because if we place in folder lib of instance that will be removed after restart this instance ?
thanks a lot for yours contributions team .

**Comment by lprimak** [comment]
Opened PR #1692 that solves this problem

**Comment by mikecroft** [comment]
Internal Payara issue `PAYARA-1765`
