### ISSUE TITLE
Update the default-web.xml to to set "xpoweredBy" init param to false for JspServlet

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#168]
There is rarely any other parameter in that configuration file that is regularly changed so it would be nice to be able a good out of the box experience

**Comment by smillidge** [comment]
Issue #31 fixed a bug with  X - powered - by not being honoured when disabled in the console. So you should no longer need to set it in the web.xml.
You can set it via as admin scripts and it should work as expected.

**Comment by davewinters** [comment]
#250 sets the x-powered header in the new domain payaradomain..the same will be set for domain1
