### ISSUE TITLE
Logging service hungs on first change of logging levels

### ISSUE THREAD

**Issue by sgerr** [payara/Payara#1680]
# Description #
----------

When saving changes on Configurations -> server-config -> Logger Settings -> Log Levels page of Admin console logging hungs because this operation adds property

com.sun.enterprise.server.logging.GFFileHandler=OFF

to ${DOMAIN_DIR}/config/logging.properties

When Switching to INFO logging resumes.

## Steps to reproduce (Only for bug reports) 

1. Navigate to Admin console -> Configurations -> server-config -> Logger Settings -> Log Levels page
2. Press "Save" button

## Environment ##

- **Payara Version**: payara-4.1.2.172
- **Edition**: Full
- **JDK Version**: 8 uXX - Oracle
- **Operating System**: Linux

**Comment by mikecroft** [comment]
can you give a bit more detail please? What changes do you make? When you say "console logging" do you mean starting Payara Server in verbose mode?

**Comment by sgerr** [comment]
No changes. Just press "Save" button on Log Levels page on fresh payara installation (downloaded today a hour ago), no config changes, just defaults.

This adds line 

com.sun.enterprise.server.logging.GFFileHandler=OFF

to ${DOMAIN_DIR}/config/logging.properties

in my case:

/opt/payara41/glassfish/domains/domain1/config/logging.properties

Switching com.sun.enterprise.server.logging.GFFileHandler to INFO resumes logging as expected.

**Comment by sgerr** [comment]
Saying Admin console I meant "Admin console" ;)
i. e. web interface on https://localhost:4848

**Comment by mikecroft** [comment]
Looking in to it, I can see that the default logging.properties has changed between 171 and 172. I'm not sure what brought the change in, yet, but it seems like GFFileHandler is set to OFF by default, but ignored until the save button is pressed.

**Comment by sgerr** [comment]
Anyway a simple workaround exists, but such a behaviiour is a bit confusing to customers.

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1759`

**Comment by sgerr** [comment]
Thank you!
