### ISSUE TITLE
Documentation for configuring Payara and HTTPS website.

### ISSUE THREAD

**Issue by robertjliguori** [payara/Payara#1681]
I deploy to glassfish (and maybe one day payara) and need it to be configured for SSL (that is, the website should always use https). On my own website, I update httpd.conf and the change resolves.

e.g.,: Forcing HTTPS (http://robertjliguori.blogspot.com/2017/04/forcing-https.html)

However, on my AWS machine for work, I need to configure alike... but http.conf isn't setup...

Is this httpd setup what I need to do?

e.g.,
sudo yum update –y
sudo yum install -y httpd24 php56 php56-mysqlnd
sudo service httpd start

or can i configure it all in the payara/glassfish webconsole?  If so, how?

The reason for this as an issue... this should be a somewhat common task?!? so it would be nice if you guys had this process documented. 

If you can document this... please send me the URL for it thanks... I've tried to figure this out but am still stuck.

Thanks,
Robert

**Comment by mikecroft** [comment]
Do you have Apache installed already? Your Yum commands there look like they are including PHP and MySQL modules as well, which you don't need for Payara.

How are you trying to access your Payara instance? Directly or via Apache?

**Comment by mikecroft** [comment]
Hi @robertjliguori can you expand on what your problem actually is here? Are you having problems with Apache or with Payara Server? I'm also not clear on exactly what your goal is - are you trying to get your application to be visible over HTTPS or the admin console?

The default SSL port for the DAS is 8181, so you should be able to visit https://your-host.com:8181/your-app without any issue or any set up. Can you already do that?

**Comment by mikecroft** [comment]
Hi @robertjliguori I'm not sure your original question related to Payara Server (you were talking about Apache httpd) so I'm going to close this issue. There are many guides on enabling HTTPS through Apache online which will probably be of help to you.

If you had any Payara Server specific problem, then we could help with that.
