### ISSUE TITLE
Enabling Hazelcast causes redeployment issues with Timer Service

### ISSUE THREAD

**Issue by bravo2zero** [payara/Payara#1696]
# Description #
----------

Having Payara full setup with MariaDB for TimerService persistence and Hazelcast enabled causes Schedule issues when redeploying applications.

## Expected Outcome
Timer Service should be working correctly after application is redeployed. All registered schedules must receive timeouts as planned.

## Current Outcome
After redeployment schedule is being registered, but is never triggered (receive no timeouts) until cluster is restarted.

## Steps to reproduce (Only for bug reports) 
1 - Having Payara full setup (171, java8, MariaDB, Hazelcast, test cluster with a node and 2 instances)
2 - Start cluster with Hazelcast enabled
3 - Deploy test artefact containing TimerService schedules
4 - Schedule is registered and receives timeouts correctly (check EJB__TIMER_TBL table record, logs)
5 - Undeploy test artefact, check schedule is unregistered
6 - Deploy the same artefact again, timer gets re-registered in EJB__TIMER__TBL but never receives timeouts (LASTEXPIRATIONRAW is always 0) until cluster is restarted completely 

### Samples
Full Docker-based test suite is available on: https://github.com/bravo2zero/docker-payara-timer

## Context (Optional)
Along with provided docker test environment, the issues was also tested and is reproducible on the actual development environment with different jdk openjdk/oracle and SLES/Debian configurations. Switching Hazelcast for the cluster will make the issue disappear.

## Environment ##
- **Payara Version**: 4.1.1.171
- **Edition**: Full
- **JDK Version**: Oracle/OpenJDK 8
- **Operating System**: Debian (jessie) / SLES 12
- **Database**: MariaDB

**Comment by bravo2zero** [comment]
also reproducible on v172 with the newer GF version

**Comment by fturizo** [comment]
@bravo2zero, thanks for the detailed reproducer sample. We have confirmed this is a bug present on Payara Server and have opened JIRA issue `PAYARA-1810` so our developers can work on a fix.

**Comment by mikecroft** [comment]
Hi @bravo2zero can you try running this command before the **_redeploy_**?

`asadmin clear-cache --target <cluster-name> --name payara.micro.applications.store`

In the interim, before the fix for `PAYARA-1810` is released in 173, that should be an acceptable workaround.

**Comment by bravo2zero** [comment]
Hi @mikecroft, sorry for the late answer, a bit overloaded right now. I'll try out your workaround as soon as I get time and post result here. Anyways, since the original cause is fixed, I assume the problem should be a history with the next release.
