### ISSUE TITLE
Payara 5's version number should adapt to the naming strategy

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara#1702]
# Description #
----------
**This issue is only related to 'Payara-5-173' branch**

Now on 'Payara-5-173' branch, the version number is set '5.1.2.173-SNAPSHOT'. But the current GlassFish 5's version number is '5.0-SNAPSHOT' (see https://github.com/javaee/glassfish/blob/master/pom.xml, _et al._), thus the number should be '5.0.173-SNAPSHOT' to adapt the naming strategy described on https://payara.gitbooks.io/payara-server/content/general-info/general-info.html .

Please see also the pull request I'll sent soon after.

**Comment by mikecroft** [comment]
Thanks for sending #1704 - I agree with your points about the numbering. It certainly shouldn't begin `5.1.2....`.

**Comment by khasunuma** [comment]
Even if 'Payara-5-173' is working branch, I can't understand set it the version number not 5.0.0.173-SNAPSHOT but 5.1.2.173-SNAPSHOT against the naming strategy of Payara. Because it's unprecedented. For example, 'Payara-5' branch, previous working branch for Payara 5 used '5.0.0.163-SNAPSHOT'.

When I wrote this issue first, I thought which version number should be chosen in working branch. Then I judged 'Payara-5-173' because I seemed it aims at Payara 5.

If this problem is not solve, perhaps we have to a new versioning rule for working branches such as 'Payara-5-173'.

**Comment by mikecroft** [comment]
Hi @khasunuma - the version will change, but it's not a priority yet. We're still a little way off providing snapshot builds and the final version will not be released for a few months. The main priorities for Payara 5 are bringing in support for the latest APIs and there is still more work to do on that.
