### ISSUE TITLE
can't remove the value in Redirect Port field

### ISSUE THREAD

**Issue by FiruzzZ** [payara/Payara#1707]
I was trying to configure a redirect from http to https when I found this article: [link](https://stackoverflow.com/questions/22382585/how-to-redirect-http-to-https-with-glassfish-v4)
----------

After noticed that wasn't the solution (or not working) I tried to remove (leave it empty) the value 8181 the configured field "Redirect Port" but when I press SAVE its previous value is setted again.

## Environment ##

- **Payara Version**: 4.1.2.172 #badassfish (build 235)
- **JDK Version**: 8 u31 - Oracle
- **Operating System**: Windows

**Comment by MattGill98** [comment]
Hi Jose,

This field certainly should be able to reset. I've created internal issue 1787 to address this. In the meantime, you should be able to reset the field with the following command: `set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.redirect-port=`

Hope this helps,

Matt
