### ISSUE TITLE
Godaddy SSL Certificate did not imported in Payara

### ISSUE THREAD

**Issue by sandeshvnaik** [payara/Payara#1710]
# Description #
----------

I am trying to run SSL web application inside payara. I did all steps and followed instruction. But SSL is not getting imported inside Payara. it says connection refused.

I also followed blog present in following link
http://blog.payara.fish/securing-payara-server-with-custom-ssl-certificate 

## Expected Outcome

Default website run under http protocol however when same is requested under https it says connection refuse.

## Environment ##

- **Payara Version**: Payara Server 4.1.2.172 #badassfish (build 235)
- **Edition**:  Full 
- **JDK Version**:  java.version = 1.8.0_131
- **Operating System**: Linux 
- **Database**: Mysql 5.6

**Comment by mikecroft** [comment]
There's not enough detail here to know what you did or where you might have gone wrong. "Connection Refused" is not what the browser would report if there were a problem with an SSL certificate.

If you have just changed your URL to begin with https while keeping the port the same, then it won't work.

We need to know the actual steps you did to be able to help you.

**Comment by mikecroft** [comment]
Closing because of the lack of detail.

Please describe more clearly what you have done and what things you have tried already so that we can verify the problem.
