### ISSUE TITLE
Add explicit javax.faces.SEPARATOR_CHAR = : on admingui web.xml [PAYARA-1816]

### ISSUE THREAD

**Issue by albfernandez** [payara/Payara#1724]
# Description #
----------

include this section  in web.xml for admingui (appserver/admingui/war/src/main/webapp/WEB-INF/web.xml)
```
<context-param>
    <param-name>javax.faces.SEPARATOR_CHAR</param-name>
    <param-value>:</param-value>
</context-param>
```

## Context (Optional)

I have a lot of JSF apps deployed on Payara (about 30). I want to provide some context-param for all of them, so I put them on default-web.xml.
One of that params is javax.faces.SEPARATOR_CHAR  (-) . It breaks admin-gui, I've tested the suggested solution and all works fine (admingui and my JSF apps).

 

## Environment ##

(Any, but i provide my current system)

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Windows
- **Database**: Oracle

**Comment by lprimak** [comment]
Have you tested with versioned applications?
```
asadmin deploy --name myapp:1.0 myapp.war
```

**Comment by albfernandez** [comment]
I've not tested versioned applications

**Comment by lprimak** [comment]
Can you please do so you can confirm that this functionality isn't broken?
Thanks

**Comment by albfernandez** [comment]
I've tried with a (very) small app and all works fine

**Comment by lprimak** [comment]
Fantastic, thanks for checking.  If the versioned app deploys via admin console it should be fine
