### ISSUE TITLE
Jaas session replication on Payara with nginx

### ISSUE THREAD

**Issue by abdoinfopayara2017** [payara/Payara#1781]
Hi team,

It is possible to replicate in application secured with JAAS on payara server ?
because when application is deployed on cluster without **JAAS security mechanism** the replication in all instances works fine but if I want secure my application with JAAS I can't get the JAAS session replicated. When load balancer switches me to different server, I have to log on again (however the jsf session state is not lost, it's gets replicated with no problem). How can I get Jaas to replicate its session over several servers? Is it possible in a stright way?   

Thanks.
Environment:

Payara Version: 4.1.2.172
Edition: Full
JDK Version: 7 u 45
Operating System: Windows

**Comment by fturizo** [comment]
Hi, @abdoinfopayara2017. It is possible to load balance sticky sessions with Payara, by configuring the load balancer to correctly re-supply the correct cookies to redirected instances. Here's a [good article on our blog](http://blog.payara.fish/payara-server-load-balancing-with-nginx) with instructions on how to configure Nginx as a load balancer that maintains sticky sessions across instances. For other load balancers or web servers, you'll have to apply a similar configuration.

**Comment by abdoinfopayara2017** [comment]
Hi, @fturizo  ,
thank you  a lot for your response for my question ,but Can you confirm my If the following scenario can be happen when we use sticky sessions : 
1. the cluster contain two instances : **instance-1** , **instance-2** are running.
assuming that the **instance-1**  of cluster receive all requests coming from the same client and at one point I stop **instance-1** and only **instance-2** of cluster is running ,Is the same client obliged to authenticate a second time ? Or is incorrectly configured the cluster with Nginx ?

thanks a lot.

**Comment by smillidge** [comment]
Can you move this to the [forum](https://groups.google.com/forum/#!forum/payara-forum) as it is not really a GitHub issue?

**Comment by abdoinfopayara2017** [comment]
Hi all,
Finally I found the solution more efficient than load balance sticky sessions ,that is Single Sign On solution inherited from GlassFish [Explained by this link](http://blog.payara.fish/migrating-away-from-the-oracle-access-manager-integration) 
thanks a lot for your contributions.

**Comment by fturizo** [comment]
Glad to know that your use case is clear @abdoinfopayara2017. I'm closing this issue then.
