### ISSUE TITLE
MDB: Connection factory is ignored when using remote JMS with resource adapter

### ISSUE THREAD

**Issue by hudac** [payara/Payara#1817]
# Description
----------

I'm using Payara4 and have a JMS broker (IBM MQ8) running on a remote host. The resource adapter is installed and works. When deploying an MDB, I've added following deployment descriptor (`glassfish-ejb-jar.xml`):

```xml
<glassfish-ejb-jar>
    <enterprise-beans>
        <ejb>
            <ejb-name>MyMDB</ejb-name>
            <mdb-connection-factory>
                <jndi-name>jms/myConnFactory</jndi-name>
            </mdb-connection-factory>
            <mdb-resource-adapter>
                <resource-adapter-mid>ibmmq-jmsra</resource-adapter-mid>
            </mdb-resource-adapter>
        </ejb>
    </enterprise-beans>
</glassfish-ejb-jar>
```
The `mdb-connection-factory` above points to a valid connection pool with env specific settings. That connection pool also links to the same resource-adapter as configured above.

I have multiple connection pools with different settings (env specific, e.g. host:port). I'd like to connect to different endpoints, using the same resource-adapter but different connection pools, while keeping env specific settings on connection-pool level within Payara (which is owned by an admin).
 
## Expected Outcome

When MyMDB is deployed Payara associates the correct resource adapter and uses the provided `mdb-connection-factory` to retrieve correct connection settings.

Ideally, the definition of a `mdb-resource-adapter` should not be even necessary as it is already configured via the connection pool exposed by the `mdb-connection-factory`.

## Current Outcome

The provided resource adapter is associated with the MDB as expected.
The `mdb-connection-factory` setting is ignored which results in connection errors as I did not define any host:port on resource adapter level, but connection pool level.

Basically, you can define anything within `mdb-connection-factory` (even a wrong one), it will be ignored.

### Workaround
When I move host:port to resource adapter level, or define additional `activation-config-property` elements which contain required host:port, it works. It also works when I implement a JMS client which looks up the connection factory manually.

## Steps to reproduce

Not sure if this is really a bug, or works as expected. This is what I did:

1. Write a simple MDB (define JEE relevant details only, e.q. destination, type, ...)
1. Install a remote JMS broker (also reproducible with ActiveMQ)
1. Start Payara
1. Deploy JMS broker's resource adapter
1. Configure a connection pool pointing to the remote JMS broker (via additional properties, e.g. host, port...) and a connection factory resource
1. Add a `glassfish-ejb-jar.xml` to your MDB's ejb.jar, example see above, pointing to the just configured/deployed connection factory and resource adapter.
1. Deploy your MDB
1. If it does not fail during deployment (could be lazy init), send a message to the JMS queue MDB is listening on

## Context

I'd like to keep env specific settings (e.g. host:port) within Payara to avoid having those params within deployment descriptors. In some deployment environments (e.g. live), I don't even know these details.

For JMS, I'd like to utilize connection pools setup to configure different endpoints, while using the same resource adapter. Basically, same approach as JDBC driver vs. data-source. Having multiple resource adapters  (same rar with different names) is also not a nice option, but it's a potential workaround.

## Environment

- **Payara Version**: Server 4.1.2.172
- **Edition**: Full
- **JDK Version**: 1.8.0_101-b13 - Oracle
- **Operating System**: Linux and Mac
- **Database**: Oracle, Postgres, H2
- **JMS Broker**: IBM MQ 8.0 (also tested with ActiveMQ 5.15)

**Comment by MattGill98** [comment]
Hi Hüda,

As far as I can see this does seem to be a bug. The `<mdb-connection-factory>` tag seems to be getting ignored. I've raised internal issue 1989 to track this bug. In the meantime the best I can suggest is declaring the properties as `@ActivationConfigProperty`s. Alternatively, you could try specifying a different connection pool in the ejb-jar.xml deployment descriptor.

Hope this helps,

Matt

**Comment by lprimak** [comment]
Both ejb-jar.xml and annotations support variable substitution in Payara so you can utilize that to switch between environment I.e. ${variables}
Hope that will resolve your immediate issue

**Comment by hudac** [comment]
Hi,

Sorry for my late response. Finally got some time to summarize my findings based on your recommendations.

Variable substitution definitely helps and reduced the dependency to env specific details within the deployment descriptor.
Additionally, IBM MQ's resource adapter now supports connectionFactoryLookup and destinationLookup since version 8.0.0.6. We can now offload all env specific attributes to the connection factory and queue within Payara.

If now Payara did not ignore the `<mdb-connection-factory>` (or the `@ActivationConfigProperty connectionFactoryLookup`) we would not even need a `glassfish-ejb-jar.xml`, as the required resource-adapter can be resolved via the connection factory.

As the name of this resource adapter can be client/env specific, too, we are using variable substitution, so here is my updated descriptor:

```xml
<glassfish-ejb-jar>
    <enterprise-beans>
        <ejb>
            <ejb-name>MyMDB</ejb-name>
            <mdb-resource-adapter>
                <resource-adapter-mid>${com.myapp.jms.resourceAdapter}</resource-adapter-mid>
            </mdb-resource-adapter>
        </ejb>
    </enterprise-beans>
</glassfish-ejb-jar>
```

Hope that helps.

Thanks,
Hüda

**Comment by smillidge** [comment]
So I am slightly confused by this issue.
Is the outcome an enhancement request to support ${ENV} for the resource-adapter-mid tag?
There is an ActivationConfigProperty that can be used to set that without using the xml file.
Below is an example for ActiveMQ
```java
@ActivationConfigProperty(propertyName = "resourceAdapter", propertyValue = "activemq-rar-5.12.0")
```

**Comment by hudac** [comment]
That's correct, you can use the ActivationConfigProperty instead. But then you introduce a compile-time dependency to a Payara specific feature which we don't want. Correct me if I'm wrong, but variable substitution is not part of JEE spec, rather a Payara feature. That would not work if we wanted to deploy same MDB code to another container. Hence, we kept this workaround still in the glassfish-ejb-jar, for Payara only.

The original expected outcome is utilizing the already existing configuration within Payara itself.
MDB knows what connection factory to use (JNDI name only). And Payara knows what resource adapter to use based on the configuration of the connection factory referenced. Ideally, the MDB should reference a connection factory (and destination+type) only and does not need to know what concrete resource adapter (or what provider) is running under the hood.

**Comment by smillidge** [comment]
OK thanks to help clarity for me can you paste the resource adapter configuration and connection factory definition so I can have some view of the configuration you would like Payara to derive from there?

**Comment by smillidge** [comment]
Closed due to lack of activity
