### ISSUE TITLE
MultiByteCode (charset = cp 932) is included in domain.xml.

### ISSUE THREAD

**Issue by sf019jp** [payara/Payara#1827]
# Description #
----------
MultiByteCode (charset = cp 932) is included in domain.xml.

in ..

&lt;domain&gt;
  &lt;configs&gt;
    &lt;config name="server-config"&gt;
      &lt;system-property name="JMS_PROVIDER_PORT" description="...([cp932] MultiByteCode)."&gt;

.and.

&lt;domain&gt;
  &lt;configs&gt;
    &lt;config name="default-config"&gt;
      &lt;system-property name="JMS_PROVIDER_PORT" description="...([cp932] MultiByteCode)."&gt;

This problem has been around since GlassFish 4.0.

## Current Outcome

1) There is no problem with standard usage
2) When trying to execute an EJB unit test using
EJBContainar.createEJBContainer() The following message appears and the execution stops.

javax.ejb.EJBException: Failed to create a temporary domain.xml file.
Use log level FINE for more details.

3) Create a new standalone server instance,
The following message will appear when starting it and it will not start.

Caused by: org.glassfish.config.support.DomainXmlPreParser$DomainXmlPreParserException:
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[89,40]

It is possible to deal by deleting the corresponding part, but when domain.xml is regenerated
It is necessary to do it every time.

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: 1.8 U112
- **Operating System**: Windows 4
- **Database**: n/a
- **Language**: Japanease

**Comment by sf019jp** [comment]
additional information.

With the deployed payara-ml-4.1.1.164.zip expanded,
Not yet multi byte code, it was in the following state.

<system-property name="JMS_PROVIDER_PORT" value="7676" description="Port Number that JMS ..." />

.and.

<system-property name="JMS_PROVIDER_PORT" value="27676" description="Port Number that JMS ..." />


However, if execute the following,

> asadmin delete-domain domain1
> asadmin create-domain --nopassword domain1

<system-property name="JMS_PROVIDER_PORT" description="...([cp932] MultiByteCode).">

It becomes.

During the development period, run delete-domain / create-domain will be implemented frequently,
This is inconvenient.

**Comment by smillidge** [comment]
Could you tell me the language the domain.xml is generated in?
It could be a problem with one of these files https://github.com/payara/Payara/tree/32f9e683cf01ed0b96de79648dafefa0a6087aa2/appserver/jms/gf-jms-connector-l10n/src/main/resources/com/sun/enterprise/connectors/jms/config 
Also could you tell me what the description text is after creating the domain?

**Comment by smillidge** [comment]
Oops just seen it is Japanese

**Comment by smillidge** [comment]
Created PAYARA-1920 to resolve
