### ISSUE TITLE
Add "Enable Secure Admin" like functionality for all http listeners

### ISSUE THREAD

**Issue by bit-ionutursuleanu** [payara/Payara#1830]
If I want to redirect trafic from http to https (now a common behaviour) automatically it's quite difficult. See below commands. For the admin listener there is a simple button in the admin console. Could you add something similar for every http listener?

asadmin create-protocol --securityenabled=false http-redirect

asadmin create-http-redirect --redirect-port 443 --secure-redirect true http-redirect

asadmin create-protocol --securityenabled=false http-pu-protocol

asadmin create-protocol-filter --protocol http-redirect --classname org.glassfish.grizzly.config.portunif.HttpRedirectFilter redirect-filter

asadmin create-protocol-finder --protocol http-pu-protocol --targetprotocol http-listener-2 --classname org.glassfish.grizzly.config.portunif.HttpProtocolFinder http-finder

asadmin create-protocol-finder --protocol http-pu-protocol --targetprotocol http-redirect --classname org.glassfish.grizzly.config.portunif.HttpProtocolFinder http-redirect

asadmin set configs.config.server-config.network-config.network-listeners.network-listener.http-listener-1.protocol=http-pu-protocol

**Comment by fturizo** [comment]
Considering that a **HTTP-to-HTTPS** redirect feature can be simply implemented by following the list of commands you mentioned, we find that there's no need to divert development efforts into this. We can direct you with a minor assistance in case you want to contribute to the project with your own implementation.
