### ISSUE TITLE
Make JAX-RS resources @RequestScoped CDI beans

### ISSUE THREAD

**Issue by ggam** [payara/Payara#1840]
Extended CDI integration for JAX-RS was on the table for 2.1 and was lately discussed on the EG mailing list (https://javaee.groups.io/g/jaxrs-spec/topic/cdi_integration/5113885?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,5113885) but was finaly postponed to a later release (https://javaee.groups.io/g/jaxrs-spec/topic/cdi_integration_decision/5154827?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,5154827).

Nevertheless, vendors could always improve integration on their way to provide earlier and better feedback for the next release. A first step would be to make all @Path annotated resources @RequestScoped beans.

Since Jersey depends on `ServletContainerInitializer` for resource discovery, this is not as simple as creating a CDI extension and registering the new types from the JAR. That's the reason I'm requesting the feature here on Payara instead of going directly to the Jersey tracker.

WildFly supports this feature via a Weld SPI on the application server side (RestEasy then depends on that integration provided by the application server). There seems to be some Weld SPI that allows to register new bean defining annotation classes, that in WildFly are detected on https://github.com/wildfly/wildfly/blob/11.0.0.Beta1/jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsAnnotationProcessor.java

**Comment by smillidge** [comment]
I think this is a Jakarta EE issue so will close here
