### ISSUE TITLE
Proposal: start-domain and create-domain could use payaradomain on Payara 5

### ISSUE THREAD

**Issue by ggam** [payara/Payara#1843]
`create-domain` uses the default template inherited from GlassFish. That makes sense for backward compatibility purposes, but I doubt noone really wants to create new domains based on the original GlassFish one, given that `payaradomain` is better configured for production.

The same applies to the `start-domain` command. Preserving `domain1` is logical for BC reasons, but new Payara users will just execute `start-domain` as they did in GlassFish, ignoring there's a better configuration available.

Since Payara 5 is not really based on GlassFish 5, but on Payara, and some years have passed since the introduction of the payaradomain, I think it might be time to change the default values of these commands.

**Comment by smillidge** [comment]
Payara 5 will come with 2 domains `domain1` which is suitable for development and `production` which is tuned for production. `start-domain` without args will still run `domain1` by default.

**Comment by OndrejM** [comment]
It makes sense to use the `production` domain as default in the docker images. I've raised an issue for the docker image: https://github.com/payara/docker-payaraserver-full/issues/36

**Comment by johnmanko** [comment]
Can you point a page detailing the differences between `domain1` and `production`?  I'm assuming it's more than a difference in `domain.xml`.
