### ISSUE TITLE
error when deploy application in cluster

### ISSUE THREAD

**Issue by abdoinfopayara2017** [payara/Payara#1849]
Hi,
I have always this error when I deploy in application in cluster from the DAS Although I have increase the default value of Buffer Size by 131072 bytes in **tcp transport** : 

**https://localhost:4848/management/domain/applications/application/SYGEF created successfully. WARNING: Command _deploy did not complete successfully on server instance instance_9: I/O Error: Error writing request body to server WARNING: Command _deploy did not complete successfully on server instance instance_29: I/O Error: Error writing request body to server WARNING: Command _deploy did not complete successfully on server instance instance_9: I/O Error: Error writing request body to server WARNING: Command _deploy did not complete successfully on server instance instance_29: I/O Error: Error writing request body to server**

I think I forgot to configure a parameter in payara server !!? 

thanks.

Environment:

Payara Version: 4.1.2.172
Edition: Full
JDK Version: 7 u 45
Operating System: Windows

**Comment by MattGill98** [comment]
Hi,

I can't seem to reproduce this error, is there any more information in the server log? Alternatively, do you have a simple application and scenario which consistently reproduces this error?

Kind regards,

Matt
