### ISSUE TITLE
Resource Pool size exceeds even though # of thread open connection < max-connection

### ISSUE THREAD

**Issue by gokhanoner** [payara/Payara#1852]
When using`hazelcast-ra`, have an issue causing `com.sun.appserv.connectors.internal.api.PoolingException: In-use connections equal max-pool-size and expired max-wait-time. Cannot allocate more connections`. We use transactional resources.

I find those issues/pull requests. 
https://github.com/payara/Payara/issues/769
https://github.com/payara/Payara/pull/770

Pool size is 3x greater than number of threads that open connection so we won't expect any pool size related issues. Could this be related to above issues, that cause pool to hold broken connections ? Or is it just apply to JDBC ?

**Comment by MattGill98** [comment]
Hi Gökhan,

I'm struggling to reproduce this issue, do you have a simple set of steps or an application to reproduce it? It's possible that connections aren't being closed in the application code, so you could check this in using a JMXmonitoring application. Alternatively, try setting the connection-leak-timeout property for the connection pool.

Hope this helps,

Matt

**Comment by gokhanoner** [comment]
Hi Matt,

I'm creating a producer, hopefully. I'll submit here the link once I have it.
