### ISSUE TITLE
Couldn't find cache config with name rest-jcache

### ISSUE THREAD

**Issue by bradvido** [payara/Payara#1855]
## Environment ##

- **Payara Version**: 172
- **Edition**: full
- **JDK Version**: Open JDK 8
- **Operating System**: Ubuntu

I have a simple 2 node Hazelcast cluster set up, and it seems to be working, but sessions do not replicate.

I see this error in the server.log:

> [2017-08-12T11:11:46.952-0500] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=89 _ThreadName=hz._hzInstance_1_production.cached.thread-4] [timeMillis: 1502554306952] [levelValue: 1000] [[
> com.hazelcast.cache.CacheNotExistsException: **Couldn't find cache config with name rest-jcache**
> at com.hazelcast.cache.impl.AbstractCacheService.checkCacheSimpleConfig(AbstractCacheService.java:213)
> at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:193)
> at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:174)
> at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
> at com.hazelcast.spi.impl.proxyservice.impl.operations.PostJoinProxyOperation$1.run(PostJoinProxyOperation.java:63)
> at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
> at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
> ]]

I think it could be related to PAYARA-1876 and PAYARA-196

I have detailed the problem in the forum here:
https://groups.google.com/forum/?__hssc=229474563.7.1502549015929&__hstc=229474563.739b51a5654a14e91a017bff222de3ff.1502134185930.1502474936491.1502549015929.9&__hsfp=2159263305&hsCtaTracking=ee96a587-4450-4296-b986-ac67f6da0574%7Cff3c7a3b-1cde-4e52-b2ad-e162643b9683#!topic/payara-forum/1Ll5e0WehuE

**Comment by smillidge** [comment]
Resolution is on the google group
