### ISSUE TITLE
Within Netbeans, I no longer can create a glassfish server entry with payara-4.1.155

### ISSUE THREAD

**Issue by codetackler** [payara/Payara#186]
Within Netbeans I no longer can create a glassfish server entry with payara-4.1.155.
Netbeans reports the error "Not a valid glassfish server installation".
If I point glassfish to my payara-4.1.144 install it works fine.

I'm using the Payara 4.1.151 (Full Java EE) version.

**Comment by smillidge** [comment]
Hi as a workaround you need to rename a jar as follows (on linux from your payara41 directory)
mv glassfish/lib/install/applications/__admingui/WEB-INF/lib/console-core-4.1.151.jar glassfish/lib/install/applications/__admingui/WEB-INF/lib/console-core-4.1.jar

Netbeans will now detect Payara as a GlassFish 4.1 instance

**Comment by AdamBien** [comment]
This issue is nasty. Could you do something about it?

**Comment by delabassee** [comment]
I would log a ticket against NB

**Comment by AdamBien** [comment]
Done: https://netbeans.org/bugzilla/show_bug.cgi?id=250165

Please vote for the ticket :-)

**Comment by smillidge** [comment]
We are also working on renaming the jar during the packaging of Payara

**Comment by Pandrex247** [comment]
We've edited and re-uploaded the release versions of the payara, payara-web, payara-ml, and payara-web-ml distributions on the website to include the workaround Steve gave above, so you won't have to do this yourself any more.

We've also edited the Jenkins build to include this workaround for any of the new pre-release builds.

**Comment by shoikot** [comment]
@Pandrex247  I've faced this issue today, I download the latest version  `payara-4.1.1.171.1` from the official site , but my NetBeans 8.0.2 reports the error "Not a valid glassfish server installation", had to rename the  `console-core-4.1.jar`

**Comment by lprimak** [comment]
@shoikot NetBeans 8.2 resolves this error, please upgrade  your NB installation
