### ISSUE TITLE
DAS Server fails to sync with local instance

### ISSUE THREAD

**Issue by bradvido** [payara/Payara#1867]
# Description #
----------
A local intance does not get updated "lib" folder from DAS after restart. In DAS server.log, I see an error.

## Expected Outcome
lib folder should sync with DAS

## Steps to reproduce (Only for bug reports) 

restart a local instance

### Samples

I see this in the logs when setting `javax.enterprise.system.tools.admin=FINE`

> 
> [2017-08-15T12:12:41.964-0500] [Payara 4.1] [FINE] [] [javax.enterprise.system.tools.admin.security.authorization] [tid: _ThreadID=143 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1502817161964] [levelValue: 500] [CLASSNAME: com.sun.enterprise.admin.util.CommandSecurityChecker] [METHODNAME: checkAccessRequired] [[
>   
> AccessCheck processing on com.sun.enterprise.v3.admin.cluster.SynchronizeFiles
>   Unguarded access control on com.sun.enterprise.v3.admin.cluster.SynchronizeFiles
>     AccessCheck admin:%252Funguarded%252F_synchronize-files=execute, isSuccessful=true, isFailureFatal=true//
> 
> ...final result: true
> ]]
> 
> [2017-08-15T12:12:42.013-0500] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=229 _ThreadName=stdout] [timeMillis: 1502817162013] [levelValue: 800] [[
>   Warning: Synchronization with DAS failed, continuing startup...]]
> 
> 

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: Full
- **JDK Version**: OpenJDK 8
- **Operating System**: Linux Ubuntu

**Comment by bradvido** [comment]
Also of note is that I have enabled secure admin for the DAS via `asadmin enable-secure-admin`, and that _may_ have been when this started to fail...

This is a similiar issue: https://github.com/payara/Payara/issues/911
But the problem in that one was $JAVA_HOME was not correctly set.
I have verified it is **correct** on my server:
![image](https://user-images.githubusercontent.com/884611/29327512-01b8e7f2-81b5-11e7-81ff-3f22bcb25b54.png)

**Comment by bradvido** [comment]
I tested today, and found that doing `start-local-instance --sync ful` **works**
Obviously this is not desirable, but a short term workaround.

How can I troubleshoot the "normal sync" failure?

**Comment by Cousjava** [comment]
@bradvido I have confirmed this is a bug with restart-instance when secure admin is enabled, currently stop-instance and start-instance work, raised internal issue PAYARA-2116

**Comment by smillidge** [comment]
Fixed by #2423
