### ISSUE TITLE
Missing Beans validation API?

### ISSUE THREAD

**Issue by chukmunnlee** [payara/Payara#1878]
# Description #
----------

I noticed that the beans validation API seems to be missing from ver 172 and 173. I'm editing a project in NetBeans. NetBeans flagged all the javax.validation as missing packages. Saw that beans-validator.jar missing from the modules directory.

Fixed it by copying the jar file from GF.

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by lprimak** [comment]
Please post your question to the Payara google group.
Bean validation API is part of the javaee 7 APIs (and not part of Payara)
Bean validation certainly tested and works in Payara 172 and 173

**Comment by chrjohn** [comment]
Seems there already is one: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/payara-forum/GVzQk2twHGM/sP3D2afUAAAJ

**Comment by smillidge** [comment]
validation-api.jar contains the bean validation apis and is in the glassfish/modules directory.
