### ISSUE TITLE
BUG: logs flooded by [WARNING] [AS-WEB-CORE-00230] despite correct error-page

### ISSUE THREAD

**Issue by kbachl** [payara/Payara#1886]
# Description #
----------

Logs get flooded by 
[2017-08-21T18:01:44.932+0200] [Payara 4.1] [WARNING] [AS-WEB-CORE-00230] [javax.enterprise.web.core] [tid: _ThreadID=34 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1503331304932] [levelValue: 900] [[
  The error-page /home/kbachl/dev/servers/payara41/glassfish/domains/domain1/applications/error-1.0-SNAPSHOT/code-404 or /code-404 does not exist]]

despite the config in web.xml beeing done:

 	<filter-mapping>
		<filter-name>wicket.error</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>REQUEST</dispatcher>
		<dispatcher>ERROR</dispatcher>
	</filter-mapping>

	<error-page>
		<error-code>404</error-code>
		<location>/code-404</location>
	</error-page>

and having a valid error page under that location path; It happens when the location is satisfied by a wicket page. Error page however is correctly shown. A quickstart to demonstrate is available.

Glassfish 3 didnt show this behaviour. After upgrade to payara it happens to us (payara 4.1.172 and 4.1.173 affected - others not tested by me)

## Expected Outcome
no warning should be logged as the error page is used as expected

## Steps to reproduce (Only for bug reports) 

grab the quickstart error war and deploy it under / in a fresh payara; Open the browser at localhost:payaraport and then click on the link - watching the logfiles; You see the correct error page but still warning logged

All code is supplied in the error-w7-quickstart-maven-project.tar.gz file;

[error-1.0-SNAPSHOT.war.zip](https://github.com/payara/Payara/files/1239438/error-1.0-SNAPSHOT.war.zip)
[error-w7-quickstart-maven-project.tar.gz](https://github.com/payara/Payara/files/1239441/error-w7-quickstart-maven-project.tar.gz)

**Comment by kbachl** [comment]
Workaround: 
add in "Module Log Levels" in "Logger Settings"
javax.enterprise.web.core 
with Log Level: SEVERE
for it to not be displayed in logs

That way no more Warnings will be shown - its still a bug that shouldnt be there :)

**Comment by kbachl** [comment]
PS: after more investigation it seems payara/ glassfish related; It worked as expected in Jetty9, Tomcat 8.5, Wildfly 10.1

**Comment by lprimak** [comment]
I have seen something similar to this as well.

**Comment by Cousjava** [comment]
Confirmed bug, internal issue PAYARA-2111 created
