### ISSUE TITLE
Edit JMS Physical Destination - field doesn't represent current setting

### ISSUE THREAD

**Issue by mb-dbc-dk** [payara/Payara#1888]
# Description #
----------

Admin page: Edit JMS Physical Destination, has "Validate XML Schema" set to "true" even when it isn't enabled

## Expected Outcome

When editing a physical jms destination.
On the loaded page the element "Validate XML Schema" is always set true not false as the configuration is.
Not altering anything on the page shouldn't enable schema validation on save.

## Current Outcome

Schema validation is enabled, and posting messages on new connections fails with a SAX exception

## Steps to reproduce (Only for bug reports) 

1 - Open the admin console (http://localhost:4848)
2 - navigate to "Edit JMS Physical Destination"
2.1 - Click: server (Admin Server)
2.2 - Click: JMS Physical Destinations
2.3 - Click: [destination]
3 - Check that "Validate XML Schema" = true (should be false)
4 - Click: save
5 - connect to messagequeue and send a (text) message, and see a schema validation error

## Environment ##

- **Payara Version**:  4.1.1.164
- **Edition**: Full
- **JDK Version**: Oracle jdk 1.8.0_131
- **Operating System**: Linux

**Comment by MattGill98** [comment]
Hi @mb-dbc-dk,

I've found the same problem, but after checking on the REST console page (http://localhost:4848/management/domain/servers/server/server/__get-jmsdest?id=QUEUE-NAME&destType=queue), it seems that the values are being submitted correctly. This means that although the admin console displays the wrong values for the true/false dropdowns, they are being submitted correctly. I've created an internal issue PAYARA-2040 to address this problem.

In the meantime you can use the link above to check the actual values for the JMS physical destination.

Hope this helps,

Matt

**Comment by smillidge** [comment]
Fixed by #2013
