### ISSUE TITLE
JAX-RS 2.1 support in Payara Micro 5 snapshot

### ISSUE THREAD

**Issue by abhirockzz** [payara/Payara#1892]
Trying JAX-RS SSE capability in Payara Micro 5 (as per http://blog.payara.fish/whats-new-in-payara-server-payara-micro-173). Injecting `Sse` using `@Context` results in a NPE. Wanted to check whether JAX-RS 2.1 support is included in Payara Micro 5 ?

**Comment by smillidge** [comment]
Hi @abhirockzz did you close it because it works?

**Comment by abhirockzz** [comment]
Well, the NPE happened when I injected `Sse` using `@Context` in a `@Singleton` EJB decorated with `@Path` .. but it worked for the basic case i.e. method injection of `Sse` in a plain old JAX-RS endpoint
