### ISSUE TITLE
Payara micro does not inject correct ManagedExecutorService

### ISSUE THREAD

**Issue by clive-jevons** [payara/Payara#1914]
# Description #
----------

When using a custom domain.xml configuration which contains a custom resource definition for a ManagedExecutorService and then injecting that into an EJB via `@Resource(name = "...")`, the container does not inject the custom service, but the default managed executor service instead.

## Steps to reproduce

I've attached a sample project with the setup described above. You can start the project using `./gradlew startService -Dcli-debug=true` from the command line, or, if using IntelliJ, you can right-click the gradle task in the Gradle view and choose 'Debug'.

Set a breakpoint in the `BeanWithExecutor` class in the `submitSomething()` method. Then trigger the call with `curl -X POST http://localhost:8080/managed-executor-service-test/api/test`. When the breakpoint is reached, then inspect the reference of the executor service, and you can see that it's the default executor, not our own one.

### Samples

(see comments below)

* `managed-executor-service-test.zip` -> small project which can be built with Gradle to demonstrate the problem
* `amx-bean-showing-custom-executor.png` -> screenshot showing that the custom executor service from the `domain.xml` is created at runtime.
* `debug-inspect-injected-executor.png` -> screenshot showing the IntelliJ debugger inspecting the injected executor service. You can see it's the wrong one.
* `injection-point.png` -> screenshot showing the code snippet with the injection and the IntelliJ debugger having annotated it with the object reference which was injected.

## Context (Optional)

We stumbled upon this while migrating some older full-stack based projects over to Payara micro which were using custom executor services. The tasks were not able to start, because by default only one can be submitted to the default. The workaround for now is to increase the core-pool-size of the default executor service to accommodate the needs of the service.

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**: Linux / Mac / Windows

**Comment by clive-jevons** [comment]
<img width="831" alt="injection-point" src="https://user-images.githubusercontent.com/16413215/29882407-3275e620-8dad-11e7-803d-80415ddc0c80.png">
<img width="627" alt="debug-inspect-injected-executor" src="https://user-images.githubusercontent.com/16413215/29882409-328eeef4-8dad-11e7-9242-57497bdf6375.png">
<img width="365" alt="amx-bean-showing-custom-executor" src="https://user-images.githubusercontent.com/16413215/29882408-32812d8c-8dad-11e7-959c-b7053ac817ff.png">

**Comment by clive-jevons** [comment]
[managed-executor-service-test.zip](https://github.com/payara/Payara/files/1264267/managed-executor-service-test.zip)

**Comment by MattGill98** [comment]
Hi Clive,

When injecting a Resource like a ManagedExecutorService, the `name` property specifies where to bind the resource for the local component. So when you define:
`@Resource(name = "concurrent/myExecutor"`
it is actually finding the first ManagedExecutorService it can, and binding it to the component on `java:comp/env/concurrent/myExecutor`.

To specify the global JNDI name, you need to change `name` to `lookup`, which defines where to look for the JNDI resource.

To test this, you can try the following lines:
```
@Resource(lookup = "concurrent/myExecutor", name = "concurrent/boundExecutor")
private ManagedExecutorService customExecutorService;

@Resource(lookup = "java:comp/env/concurrent/boundExecutor")
private ManagedExecutorService boundExecutorService;
```
You'll see when debugging that they both resolve to the same ManagedExecutorService.

I hope this clarifies things, and of course let me know if you have any problems.

Kind regards,

Matt

**Comment by clive-jevons** [comment]
@MattGill98 thank you very much for the clarification :)

**Comment by clive-jevons** [comment]
@MattGill98 not to hark on about it too much, but the official JEE API specifies that the 'name' parameter of `@Resource` is used to specify the 'JNDI name': https://docs.oracle.com/javaee/7/api/javax/annotation/Resource.html#name-- ... hence the confusion, because in the domain.xml I specify the JNDI name, then use that exact value in the 'name' parameter of the Resource annotation, and it doesn't get injected. In my humble opinion this could well be worth adding into the reference documentation somewhere.

**Comment by MattGill98** [comment]
Hi Clive,

I agree it's a little confusing. Think of it more like a 'push' value than a 'pull' value. There's quite a good explanation on a StackOverflow comment here: https://stackoverflow.com/questions/6180144/declaring-resource-and-ejb-at-the-class-level-in-java-ee6/6185960#6185960. Unfortunately we don't own the reference documentation, but I'll suggest it as a potential blog topic or addition to our own documentation.

Kind regards,

Matt
