### ISSUE TITLE
Certain documented system properties seem not to override their command line equivalents

### ISSUE THREAD

**Issue by ljnelson** [payara/Payara#1953]
# Description #
----------

Documented system properties referenced [here](https://docs.payara.fish/v/172/documentation/payara-micro/configuring/config-sys-props.html) do not appear to serve as replacements for their command line equivalents.

## Expected Outcome

I was expecting that if I had a `system.properties` file like this:

    payaramicro.name=foo

...supplied like this:

    --systemProperties system.properties

...then output/behavior should be identical to what would happen if all I supplied instead was this:

    --name foo

...in accordance with the documentation.

## Current Outcome

Supplying just `payaramicro.name=foo` in `system.properties` as above (i.e. no `--name` option) does not in fact cause the instance name to be set.

This seems to be true as well for the `payaramicro.disablePhoneHome` property (only the `--disablePhoneHome` option, which turns (under the covers) into an `asadmin set` operation, works).

## Environment ##

- **Payara Version**: 4.1.1.172
- **Edition**: Micro
- **JDK Version**: payara/micro:172 JVM
- **Operating System**: payara/micro:172 OS
- **Database**: N/A

Thanks for a great product and timely help out there in the world!

**Comment by smillidge** [comment]
Looks like this is a bug. It should work as you describe. In fact setting it via -Dpayaramicro.name=foo does work. I've created internal bug PAYARA-2063 to resolve this.
