### ISSUE TITLE
Not correct status icon for the enabled application in the application manager if having more than 1 applications

### ISSUE THREAD

**Issue by Lanzjess** [payara/Payara#1959]
# Description #
----------

Upon having 2 applications deployed, then 1 will be enabled and the other 1 disabled
then both the icons are "x" or disabled although the notification message is correct.

## Expected Outcome
Should show check mark meaning  Enabled for the enabled or active application(currently running)
Should show cross mark meaning Disabled for the disabled or not running application

## Current Outcome
Both the status icon of application 1 and application 2 are cross icon meaning Disabled

## Steps to reproduce (Only for bug reports) 
1. Start the Payara server as is.
2. In the application manager, deploy application 1(Automatically enabled...correct this time)
3. Disable the application 1(Correct)
4.. Deploy application 2 (Automatically enabled...correct this time)
5. Disable application 2(Correct)
6. Enable application 1(The icon is not changed to **check mark** or enabled although the running application is correct as application 1. See that both status icon are disabled. This is problematic for the admin because he/she will be confused which application is running.)
7. Doing the switching again and still both the status icon are disabled or cross icon. This is now confusing which application is currently running unless investigated thoroughly.

## Context (Optional)
The admin wants to select from list of available deployed applications 
example is to select an application to present a demo to a business client.

## Environment ##
- **Payara Version**: 4.1.2.172
- **Edition**: Ful
- **JDK Version**: 1.8.0_131  - Oracle
- **Database**: MySQLSQL Server

The 2 applications are both JSF-PrimeFaces project

**Comment by Cousjava** [comment]
Hello @Lanzjess 
I tried following your instructions with a JSF project but was unable to reproduce it, the tick/cross marks in the enabled column were correct.

Does anything appear in the log to indicate why it might not be working?

**Comment by Lanzjess** [comment]
Both application are listening to port 8080. So they should switch in using it.
