### ISSUE TITLE
Application deploy throws java.lang.ClassNotFoundException: fish.payara.cdi.jsr107.CacheResultInterceptor

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#201]
I'm trying to make use of some fancy JSR107 functionality and created a simple app with an EJB method annotated with javax.cache.annotation.CacheResult (@CacheResult). When I try to deploy it to Payara 4.1.151, it thows:
java.lang.ClassNotFoundException: fish.payara.cdi.jsr107.CacheResultInterceptor

I'm using JDK 1.8.0_25 on Mac OS X.

**Comment by smillidge** [comment]
Take a look at this issue as it explains you need to copy a jar into the lib directory and reference it in your deployment to use the interceptor with EJBs. There's a screenshot in the issue showing where to reference the library. We need to add this to the documentation.

"you must copy payara-jsr107.jar from glassfish/modules to domains/domain1/lib/applibs and reference it as a library during deployment to get injection to work in an EJB Session Bean. This is part of the EJB spec."

https://github.com/payara/Payara/issues/196

**Comment by smillidge** [comment]
Also make sure you enable Hazelcast in the administration console 
https://github.com/payara/Payara/wiki/Hazelcast-(Payara-4.1.151)#31-enabling-hazelcast-through-the-admin-console

**Comment by peraxel** [comment]
Thanks, copying payara-jsr107.jar did the trick.
