### ISSUE TITLE
Please add validation-api.jar reference to gf-client.jar

### ISSUE THREAD

**Issue by nishisan** [payara/Payara#2011]
# Description #
----------
Please add validation-api.jar reference to gf-client.jar,
the gf-client.jar of new payara does not reference the the validation-api.jar and when migrating from an older verstion to a new one it complains about the javax.validation.constraints.

**Comment by smillidge** [comment]
I just looked at the gf-client.jar manifest of a newly built server and it contains the correct Classpath entry.
```
../modules/hibernate-validator-payara-p1.jar 
 ../modules/validation-api.jar
```
