### ISSUE TITLE
Standalone instances are marked as "Restart Required"

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#2019]
# Description #
----------
Standalone instances are marked as "Restart Required" after clicking to instance detail in administration GUI.

## Expected Outcome

All instances are green when no modification in configuration was made.

## Current Outcome

Some instances are marked as "Restart Required", even when no configuration has been changed.

## Steps to reproduce (Only for bug reports) 
In admin GUI:
1) click on "Standalone instances"
2) click on name of an instance
3) click again on "Standalone instances"
4) instance's status is "Restart Required" (orange triangle)

## Context (Optional)
It does not matter, whether the instance is local or remote SSH.

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full 
- **JDK Version**: 8u144 Oracle 
- **Operating System**: Linux 
- **Database**: Informix 11.70

**Comment by Cousjava** [comment]
I tried to reproduce your issue but did not get the restart required after following your steps. Is there anything in the logs? If there is an Unprocessed Change Event in them then that will be the cause of the restart required message.

**Comment by sgflt** [comment]
I tried it too and found that it is a little bit complicated to reproduce. Clean installation with only standalone instance is behaving correctly.

The minimal set up, that is broken is following:
1) asadmin create-domain test
2) asadmin start-domain test
3) asadmin enable-secure-admin
4) asadmin restart-domain test
5) in admin GUI create a new standalone instance with a new configuration as copy of default-config
6) in admin GUI go to Configurations -> test-config -> System properties
7) uncheck dynamic reconfiguration and save
8) instance is marked as "Restart Required"

After this steps it is clearly reproducible. Stop and start of the instance marks instance as OK, but the reported steps marks instance again as "Restart Required".

Logs are without errors and warnings.

**Comment by Cousjava** [comment]
Thank you for the reproduction instructions, I was able to replicate it. Created internal issue PAYARA-2162.
