### ISSUE TITLE
Easy integratable GlassFish for Operators

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#202]
One thing that makes GlassFish difficult operate at even moderate scale or in a cloud environment is that it takes on too much responsibility. GlassFish includes "solutions" for clustering, load balancing, deploying/installing/running on remote nodes etc. None of these solutions are anywhere near as performant, easy to operate etc. as the stand alone variants. 

I notice a recent change wrt Hazelcast made it possible to cluster GlassFish without using being a GlassFish cluster. I would like to see this taken a step further and a variant of Payara/GlassFish that removed the components that are unnecessary or get in the way of operating as part of a cluster. The idea that a lower surface area would reduce the complexity of managing the app and increase security.

These include;

* Removal of load balancer - these are best done with HA proxy, ELB or similar technology
* Removal of SSL - SSL should be terminated prior to reaching GlassFish you want to limit where your certificates are stored and move load off appserver. Also plenty of other tools to perform this
* Removal of the whole dcom/ssh node infrastructure. Nodes should be provisioned using a configuration management tool ike chef/puppet/ansible/salt or as part of an immutable infrastructure ala docker/vm images.
* If shared sessions are needed, delegate to Hazelcast os some other similar tech and remove the builtin mechanisms
* Removal of many of the built-in  services (i.e. remove mq, db, and any extraneous osgi stuff). Typically these will need to a separate service
* Default to  having a single listener for each capacity (HTTP, OSGI)

Actually listing this out it seems like it is essentially stripping it down to a micro-service like system except with all of the EE APIs present.

Note, in  http://payara.co.uk/the_year_of_the_vampire_fish you put out a call for feature requests so this  a response to that.

**Comment by smillidge** [comment]
Thanks for this some great stuff there I'll respond in more detail later, maybe in a blog, and split some issues out.

This is the same direction we want to head. Simple "self discovering" peer-peer clustering utilizing modern deployment techniques. With single management interface for deploying to many "domains" or groups of servers. We are currently messing with Payara embedded web-profile, utilising Hazelcast as the basis of a microservices edition.

**Comment by smillidge** [comment]
Have a read of this blog for a simple microservice on Payara embedded 
http://www.payara.co/building_restful_javaee_microservices_with_paya

**Comment by realityforge** [comment]
I had not thought about starting from that direction with a custom launcher. However that could certainly work.

**Comment by smillidge** [comment]
Needs splittung into multiple issues by the Payara team

**Comment by smillidge** [comment]
Payara Micro will be out at the end of the month which will be the first step to achieving some of this. 
It is currently on the pre-release download page with docs and blog to follow http://www.payara.fish/upstream_builds 

It will enable running of war files via;

```
java -jar payara-micro.jar --deploy test.war
```
with full hazelcast web session clustering.

Unfortunately it will have the Derby DB as JavaEE 7 mandates a default datasource.

**Comment by realityforge** [comment]
Great work!

**Comment by smillidge** [comment]
I'm going to close this with the release of Payara Micro. Please raise additional Payara Micro requirements as separate issues as we always want ideas :-)
