### ISSUE TITLE
Logical transaction tracing

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#203]
It would be nice to enable tracing of logical "transactions" through the system. The simplest way to do this is to associated a request or transaction ID with a request when it enters the system. Then every time the request crosses a boundary (i.e. Servlet, EJB, JaxRS, JMS, JaxWS etc), the transaction ID is copied from the old context to the new context in whatever way makes sense (i.e. Headers, request properties, message properties etc). 

This makes it possible to identify the initial request that triggered an action, regardless of where it initiated. i.e. Imagine the flow where a Servlet, invokes a Stateless EJB (and thus in separate thread), which sends a JMS message, which triggers an MDB, which invokes a JaxWS services. The JaxWS service implementation should be able to retrieve the appropriate header and determine what the initial request ID was. For bonus points you could store the input/output messages/parameters at each layer so you see a trace of the request as it progresses through the system. 

Looking at GlassFish it seemed that it may have had a similar facility at one stage (2.x?) or at least that had been the intent.

This may be something that you are already thinking about but I thought I would add it just in case you are not.

**Comment by smillidge** [comment]
Definitely something we want to do. It will likely come in phases.

**Comment by phillipross** [comment]
+1

**Comment by realityforge** [comment]
I remember someone starting to integrate GlassFish/Payara with Zipkin to provide this functionality. Does anyone have a pointer to this?

**Comment by mikecroft** [comment]
There is a ***tech preview*** of request tracing coming in 163 which will address some of this. It's a big feature, so there's still some extra things to add from the epic, but it looks like the bulk of the work is done. Keep an eye on our blog in the weeks after the new release, we'll try and highlight the current capabilities of it.

**Comment by mikecroft** [comment]
The request tracing service has been released and the upcoming 164 release has even more interceptors which will be traced when turned on.

@OndrejM wrote a comprehensive blog on how to use it here:
http://blog.payara.fish/request-tracing-service-in-payara-server-payara-micro
