### ISSUE TITLE
Vaadin CDI 3.0.0alpha1 does not work

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2034]
Latest release of vaadin cdi 3.0.0.alpha1 does not work on latest official payara. However it does work on latest widlfly server.

**Comment by mikecroft** [comment]
What do you mean by "does not work"? How does it not work? What are the steps to reproduce, expected and actual outcomes?

**Comment by scrmtrey91** [comment]
1) deploy an app with payara-4.1.2.173 and vaadin cdi 3.0.0.alpha1 (lets say one UI and one simple inject with one method returning string type. 
2) Click button to fire ejb method
3) session expired message instead of working app, UI (as soon you click on button)
** so it must be something with inject problem

The same app is working on wildfly server.

**Comment by mikecroft** [comment]
Do you have a sample application that will show the error? http://sscce.org/ It's not clear from your description what kind of application will reproduce the error. Is there anything in the server.log?

**Comment by scrmtrey91** [comment]
No, there is no error in server.log. You can take memleaks-cdi sample application and just update the cdi and vaadin version.

**Comment by fturizo** [comment]
As mentioned by @mikecroft, we won't be able to help unless we have more details on how to reproduce the error you are encountering. Can you provide a sample web application or project that helps us to identify the exact issue? Otherwise, we cannot do much.

**Comment by scrmtrey91** [comment]
Example here : https://github.com/tmattsso/devday-memleaks

Just change the vaadin version to the 8.2.0.alpha2 and CDI to 3.0.0alpha1 (check the version on vaadin directory, just to be sure).

Then click the button and session expired as soon you click the button (cause cdi inject).

**Comment by smillidge** [comment]
Is this still valid? Is Vaadin still an issue with Vaadin released versions?

**Comment by scrmtrey91** [comment]
Its working as excpected with latest normal 3.0.0 official version.

**Comment by smillidge** [comment]
Thanks
