### ISSUE TITLE
Project deploying problem

### ISSUE THREAD

**Issue by fahimferoje** [payara/Payara#2036]
While deploying the project then it says `/home/fahim/Payara_Server/glassfish/domains/payaradomain/autodeploy/bundles does not exist, please create it. `

then it does not do anything. I am using `Payara Server 5.0.0.173-SNAPSHOT` version
Netbeans version : 8.2

**Comment by lprimak** [comment]
```
/home/fahim/Payara_Server/glassfish/domains/payaradomain/autodeploy/bundles does not exist, please create it.```

You can simply ignore the above message, it doesn't cause any issues.
Deployment should work despite this message.  Do you have any other messages that could be the culprit of your issue?

**Comment by lprimak** [comment]
I do realize this message is confusing

**Comment by fahimferoje** [comment]
@lprimak Unfortunately I did not see anything. Yeap it might be due to some misconfiguration. I will check that. I will post here if i see anything.
