### ISSUE TITLE
Review table names for Jbatch

### ISSUE THREAD

**Issue by davewinters** [payara/Payara#206]
Oracle has a restriction of table names whereby the tables names can be 30 bytes long. The longest existing JBatch table name is 26 characters in length so if one uses table prefixes and suffixes with JBatch then the relevant Jbatch tables will not be created and one will receive the exception below

Oracle documentation on identifier restrictions:

http://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements008.htm#SQLRF00223

[2015-02-11T12:06:50.096+0000] [Payara 4.1] [SEVERE] [] [fish.payara.jbatch.persistence.rdbms.OraclePersistenceManager] [tid: _ThreadID=29 _ThreadName=http-listener-1(1)] [timeMillis: 1423656410096] [levelValue: 1000] [[
  ORA-00972: identifier is too long
]]

[2015-02-11T12:06:50.098+0000] [Payara 4.1] [SEVERE] [] [fish.payara.jbatch.persistence.rdbms.OraclePersistenceManager] [tid: _ThreadID=29 _ThreadName=http-listener-1(1)] [timeMillis: 1423656410098] [levelValue: 1000] [[
  ORA-00972: identifier is too long
]]

We should change the existing table names used by JBatch as they are too long:

Existing table names:

JOBSTATUS
STEPSTATUS
CHECKPOINTDATA
JOBINSTANCEDATA
EXECUTIONINSTANCEDATA
STEPEXECUTIONINSTANCEDATA

Possible new tables names to use whereby the longest table name is 14 characters in length:

JOBSTATUS
STEPSTATUS
CKPOINTDATA
JOBINSTDATA
EXECINSTDATA
SPEXECINSTDATA

Thoughts??

**Comment by davewinters** [comment]
This is solely an Oracle constraint.

**Comment by smillidge** [comment]
I don't recommend changing the table names as this will cause backward compatibility issues and will require an upgrade step to rename the tables in the next release.

Can we just check the table length including prefix and suffix in the asadmin command and reject long tables.

**Comment by davewinters** [comment]
Ok will put in place a check that when the datasource is an Oracle to check the table length name if prefix or suffix values are specified.

**Comment by davewinters** [comment]
pull request to resolve this issue whereby we check in asadmin and in the admin console batch configuration page the table name length on Oracle before setting the relevant batch properties. If the table length is over 30 characters then we notify the user.

https://github.com/payara/Payara/pull/211
