### ISSUE TITLE
Payara Micro start parameter addjars not working on windows

### ISSUE THREAD

**Issue by cluxig** [payara/Payara#2070]
# Description #
----------

It's impossible to specify --addjars using an absolute path on windows platform. This is caused by `fish.payara.micro.impl.PayaraMicroImpl`, which splits the String on `:`. Path specifications like `c:\Developement\external` to specify a folder or even a jar directly is impossible.

## Expected Outcome

Windows Path must be parseable as well.

## Current Outcome

Booting fails with the message: "File c does not exist".

## Steps to reproduce (Only for bug reports) 

`java -jar payara-micro.jar --addjars c:\external\any-jar-or-directory`

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Micro
- **JDK Version**: Oracle 8
- **Operating System**: Windows 10

**Comment by mikecroft** [comment]
Created `PAYARA-2215` for  this issue

**Comment by smillidge** [comment]
Fixed by #2073
