### ISSUE TITLE
Feature: need for a mechanism to read content from files into domain.xml (Usecase: docker secrets)

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#2078]
# Description #
----------
Hi guys.
I request a new Feature: 
Currently we ship a docker image with a connectionpool, which has some property-references to environment variables, like this:
`create-jdbc-connection-pool --datasourceclassname oracle.jdbc.pool.OracleDataSource --restype javax.sql.DataSource --isconnectvalidatereq true --validationmethod table --validationtable dual --steadypoolsize 1 --maxpoolsize 20 --poolresizequantity 3 --idletimeout 10 --leakreclaim true --statementtimeout 340 --leaktimeout 200 --statementleakreclaim=true --statementleaktimeout 170 --failconnection true --property **user="${ENV\=jdbcUser}":password="${ENV\=jdbcPassword}":url="${ENV\=jdbcURL}**" MYCONNPOOL`

So we have an immutable image, which can connect to different databases for staging (test, production,...).

As you may have noticed, the password is passed as a environment variable, which is not a very good idea. So far I can't find a good solution for this in payara.
As docker solution we discovered a functionality named "docker secrets" where passwords are stored in a /run/secrets/my_secret_data file.
So we need a funtionality in payara, that can parse the domain.xml and replaces vars with the content of a file.
It would be like the ${ENV=myenvvar} pattern:
${FILECONTENT=/run/secrets/my_secret_data} or sth. like that.

Thx, guys.

Best regards

Bastian

**Comment by deratzmann** [comment]
I noticed, that the "docker config" works in the same way. so we could reuse this new feature.

**Comment by mikecroft** [comment]
You could probably work around this with a script in your Dockerfile to parse the file and set passwords as environment variables.

Is this Payara Server? If so, the best solution would probably be using an alias:
https://docs.payara.fish/documentation/core-documentation/password-aliases/password-aliases-overview.html

**Comment by deratzmann** [comment]
Yes, using passwords from environment variables works (and we do it so far), but it is not a good idea, see https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/ . 
We use payara full profile.
We also discussed the approach of aliases in glassfish, but this has one drawback: We can do it only in the entrypoint of docker, because with immutable docker immages you only know at startup time which database you will connect. This will increase the startup time and probably will cause problems when using "docker start" which would retry to install an alias that already exists.

**Comment by smillidge** [comment]
Fixed by #2203

**Comment by deratzmann** [comment]
we found another Solution for this case: we create a password alias in the starting entrypoint from docker. this works fine for us.

**Comment by smillidge** [comment]
This is provided via MP Config and docker secrets support
