### ISSUE TITLE
Payara 5 Alpha3 not working with Java 9

### ISSUE THREAD

**Issue by CSchulz** [payara/Payara#2110]
# Description #
----------

## Steps to reproduce (Only for bug reports) 

```
bin/asadmin start-domain --debug domain1
Waiting for domain1 to start .Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

-Xbootclasspath/p is no longer a supported option.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Command start-domain failed.
```
## Environment ##

- **Payara Version**: 5.0.0.Alpha3
- **Edition**: Full
- **JDK Version**: Oracle 9.0.1+11
- **Operating System**: Mac

**Comment by smillidge** [comment]
try with the payaradomain?

**Comment by CSchulz** [comment]
Hum, too bad I didn't check it.

Yes it works with payaradomain. But nevertheless the error message should be different. 😃

**Comment by lprimak** [comment]
The issue is that we cannot touch ```domain1``` really because of our pledge to be compatible with GlassFish.  The errors come from incompatible options, which is what payaradomain is there to overcome

**Comment by smillidge** [comment]
We don't support Java9 yet. Payara domain was renamed to production in Payara 5

**Comment by CSchulz** [comment]
Are there any plans to support Java 9 or an ETA?
