### ISSUE TITLE
Thread "logging output pump" keeping a cpu core 100% busy: LoggingOutputStream infinitely writing/flushing to itself

### ISSUE THREAD

**Issue by stijnkliemesch** [payara/Payara#2117]
# Description #
----------

At some point during the lifecycle of a Payara server, 2 things happen:

1. An instance of com.sun.common.util.logging.LoggingOutputStream is created, with a java.util.logging.Logger object argument with the name "javax.enterprise.logging.stderr". 
1. The System.err is replaced with the an instance of a com.sun.common.util.logging.LoggingOutputStream.LoggingPrintStream, which is an inner instance member class of the LoggingOutputStream.

In the constructor call of the LoggingOutputStream, a private method "initializePump" is called which starts a thread that infinitely calls "log()" on this LoggingOutputStream instance. During this log() call the following happens.

1. The wrapped Logger's method "log(...)" is called
1. The Logger iterates through a parent chain
    1. this = "javax.enterprise.logging.stderr"
    1. this.parent = "javax.enterprise.logging"
    1. this.parent.parent = "javax"
    1. this.parent.parent.parent = "" <- different class, namely java.util.logging.LogManager.RootLogger
1. The logger iterates over the handlers (java.util.logging.Handler) of the current parent iteration (the RootLogger) and calls the method "publish(...)"
1. An instance of java.util.logging.ConsoleHandler is encountered during iterating over these handlers
1. During the "ConsoleHandler.publish(...)" call, the handler calls "super.publish(...)" which is the parent class java.util.logging.StreamHandler's implementation
1. During this "publish(...)" call, "write(...)" calls are done on a wrapped OutputStreamWriter instance of the handler, with a subsequent "flush(...)" call
1. This bubbles through a sun.nio.cs.StreamEncoder, to an instance of org.apache.felix.gogo.runtime.threadio.ThreadPrintStream
1. This ThreadPrintStream delegates all calls to a threadlocal PrintStream instance that is obtained from calling "ThreadPrintStream.getCurrent()"
1. This "getCurrent()" call returns the same object as System.err, an instance of  an instance of a com.sun.common.util.logging.LoggingOutputStream.LoggingPrintStream, which has as its outer instance the exact LoggingOutputStream that started this sequence.
1. The ThreadPrintStream's field "dflt" is set to this LoggingPrintStream instance, my assumption would be that "getCurrent()" always returns this as probably "setStream(...)" is never called to override this.

Because of this, when using System.err you will inevitably invoke an infinite loop of the LoggingOutputStream writing its message queue content to itself, which consequently gets flushed back into its own queue.

## Expected Outcome

Unsure. It is (for now) unknown to me whether there's Handler instances in the Logger parent chain that send the messages to somewhere useful.

Aside from this, there should never be the case that the LoggingOutputStream ends up logging to its own message queue.

## Current Outcome

Anywhere in any application where System.err is written to, messages get added to the queue in the LoggingOutputStream. But the stream Eventually writes these messages to itself, and flushes them to it's own message queue, effectively never emptying the queue.

I don't know to which degree the appropriate behaviour of stderr logging has been disturbed by this sequence.

## Steps to reproduce (Only for bug reports) 

The steps to reproduce this are uncertain.

I have yet to determine through which course of action the ThreadPrintStream is introduced into the system. 

## Context (Optional)

This has also happened to us on a GlassFish server.

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**:  OpenJDK 64bit Server VM 1.8.0_144-b01
- **Operating System**: Linux CentOS 7.4.1708 (core)

**Comment by smillidge** [comment]
Can you provide a stack dump of the infinite loop?

Are you writing to System.err directly in your code?

Have you tried disabling "Log to Console" in the Logger Settings of the relevant configuration?
