### ISSUE TITLE
Random UnsatisfiedDependencyException on startup in Payara  4.1.2.173

### ISSUE THREAD

**Issue by JoonasVali** [payara/Payara#2119]
# Random UnsatisfiedDependencyException on startup in Payara  4.1.2.173 #
----------

Randomly an UnsatisfiedDependencyException is thrown and server startup fails.

## Expected Outcome

Server should startup normally

## Current Outcome

Server crashes and won't startup.

## Steps to reproduce (Only for bug reports) 

There are no specific steps to reproduce, as it just fails on normal startup sometimes when done enough times.

### Stacktrace and server log

[UnsatisfiedDependencyException.log](https://github.com/payara/Payara/files/1437284/UnsatisfiedDependencyException.log)

## Environment ##

- **Payara Version**: 4.1.2.173 #badassfish (build 24)
- java.version=1.8.0_144
- os.name=Linux
- os.version=4.4.0-97-generic
- sun.java.command=com.sun.enterprise.glassfish.bootstrap.ASMain -debug false -domaindir /opt/containers/payara-4.1.2.173/glassfish/domains/domain1 -instancename server -verbose true -domainname domain1

Not sure if important, but the server is run from Jenkins environment.

**Comment by smillidge** [comment]
This has been reported a few times now in various conditions by various people including me!

**Comment by smillidge** [comment]
Internal Bug ID PAYARA-2255

**Comment by smillidge** [comment]
A workaround is to add the microprofile-config tag to your server-config config in domain.xml like...
```xml
  <configs>
    <config name="server-config">
     <microprofile-config></microprofile-config>
```
This should be written automatically if missing but there seems to be a race condition.
