### ISSUE TITLE
Can't quiet JDBC stack traces in Logs

### ISSUE THREAD

**Issue by rickgonzalez** [payara/Payara#2127]
# Description #
----------
4.1.2.173 deployed as jelastic environment 
I have a war deployed that runs Jersey services that call a separately deployed Stateless EJB which makes JDBC calls using a connection pool.  I've tried just about everything to turn off the enormous number of  stack traces that are thrown in the server.log

example:
[2017-11-03T13:17:11.798+0000] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=108 _ThreadName=connector-timer-proxy] [timeMillis: 1509715031798] [levelValue: 1000] [[ Fri Nov 03 13:17:11 UTC 2017 INFO: Profiler Event: [FETCH]   ** BEGIN NESTED EXCEPTION **   java.lang.Throwable  STACKTRACE:  java.lang.Throwable at com.mysql.jdbc.log.LogUtils.expandProfilerEventIfNecessary(LogUtils.java:47)
.... on and on

I get one of these for both [fetch] and [query] for every connection it seems even though there is nothing wrong with the data access or the pool.

## Expected Outcome
Things I've tried:
Ensured that there were no settings in the advanced section of the jdbc pool configuration that enabled extended jdbc monitoring

-1 for slow query monitoring and 
log jdbc calls unchecked

I've turned off monitoring - although it is unclear as to where the desired "extra logging" should be configured based on the documentation

I've also tried turning down/off logging levels - 

I would expect that by turning these settings off I would not see all of the stack traces at a severe level that I can't turn off making it far more difficult to debug an application.

Please let me know and add to documentation if there is a certain log level I can just turn off.

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by smillidge** [comment]
The stack trace you have indicates the log message is coming from MySQL do you have profiling enabled on the MySQL Driver by adding the property below to your connection URL or datasource?
```
profileSQL=true  
```
