### ISSUE TITLE
Upgrade Hazelcast to 3.4.1

### ISSUE THREAD

**Issue by dmatej** [payara/Payara#213]

**Comment by smillidge** [comment]
Is there a specific thing you need in 3.4.1 or shall we just upgrade to the latest Hazelcast minor in the next release.

**Comment by dmatej** [comment]
Nothing specific, only some bugfixes - it seems to me that this technology is a bit young and some fixes could be important, but at this time I'm not affected by any bug. Changelog:
https://github.com/hazelcast/hazelcast/issues?q=milestone:3.4.1
