### ISSUE TITLE
payara micro domainconfig command line option not working

### ISSUE THREAD

**Issue by ringmaster217** [payara/Payara#2134]
# Description #
----------

When running payara micro, the documentation says that I should be able to provide a configuration file by using the --domainconfig flag. This does not appear to be working.

## Expected Outcome

Using the --domainconfig flag to specify an alternative domain.xml should result in payara micro loading configuration from that domain.xml. 

## Current Outcome

Using the --domainconfig flag to specify an alternative domain.xml results in payara micro still using the default domain.xml included in the payara micro jar. Replacing the domain.xml inside the jar file with a new domain.xml does produce the desired changes.

## Steps to reproduce (Only for bug reports) 

1 -**  Create a new domain.xml

2 -**  Run payara micro with the new domain.xml

    java -jar payara-micro.jar --domainconfig domain.xml --deploy project.war

## Environment ##

- **Payara Version**: 4.1.1.173
- **Edition**: Micro
- **JDK Version**: 8 u151 - OpenJDK 
- **Operating System**: Linux
- **Database**: n/a

**Comment by sunny433** [comment]
Try to deploy any application with the new domain.xml. With this, the necessary configurations would be loaded from the domain.xml for the application you want to deploy. Run the following command with the path of the war file at the end.

java -jar payara-micro.jar --domainconfig domain.xml --deploy project.war

**Comment by ringmaster217** [comment]
@sunny433 That's what I'm trying to do, but the provided domain.xml isn't being loaded by payara micro.

**Comment by Cousjava** [comment]
I tried to replicate this but Payara Micro used the provided domain.xml file. What are you putting into your domain.xml file?

**Comment by ringmaster217** [comment]
I'm adding a `jdbc-connection-pool` and an `auth-realm`. The domain.xml looks like this:

```
<domain>
  ...
  <resources>
    ...
    <jdbc-connection-pool datasource-classname="com.mysql.jdbc.jdbc2.optional.MysqlDataSource" name="SecurityPool" res-type="javax.sql.DataSource">
      <property name="password" value="password1234"></property>
      <property name="databaseName" value="database1"></property>
      <property name="serverName" value="db.foo.bar"></property>
      <property name="user" value="dbuser"></property>
      <property name="portNumber" value="3306"></property>
    </jdbc-connection-pool>
    <jdbc-resource pool-name="SecurityPool" jndi-name="jdbc/security"></jdbc-resource>
  </resources>
  ...
  <configs>
    <config name="server-config">
      ...
      <security-service activate-default-principal-to-role-mapping="true" jacc="simple">
        <auth-realm classname="com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm" name="jdbcRealm">
          <property name="jaas-context" value="jdbcRealm"></property>
          <property name="encoding" value="Hex"></property>
          <property name="password-column" value="PASSWORD"></property>
          <property name="datasource-jndi" value="jdbc/security"></property>
          <property name="group-table" value="database1.USERS_GROUPS"></property>
          <property name="user-table" value="database1.USERS"></property>
          <property name="group-name-column" value="gGROUP_NAME"></property>
          <property name="digestrealm-password-enc-algorithm" value="SHA-256"></property>
          <property name="digest-algorithm" value="SHA-256"></property>
          <property name="user-name-column" value="USERNAME"></property>
        </auth-realm>
        ...
      </security-service>
      ...
    </config>
  </configs>
</domain>
```

**Comment by sunny433** [comment]
Hello,

I am trying to connect to some third party service and added the authentication details in the domain.xml file. This is working for me.

```
<servers>
      <server name="server" config-ref="server-config">
      <system-property name="username" value="XXXXX"/>
      <system-property name="password" value="XXX"/>
          <resource-ref ref="jdbc/__default"/>
      </server>
</servers>
```

**Comment by Cousjava** [comment]
@sunny433 is correct, for creating a reference to a resource you must also add a resource-ref under the server tag. So for your original issue you need to have


```
<servers>
        <server name="server" config-ref="server-config">
            <resource-ref ref="jdbc/__default" />
            <resource-ref ref="jdbc/security" />
        </server>
</servers>
```
