### ISSUE TITLE
Provide a gradle plugin for Payara

### ISSUE THREAD

**Issue by mweisshaupt1988** [payara/Payara#214]
It would be great if it was possible to use Payara and Payara Embedded with the gradle build system. Maby it is possible to integrate Payara with the gretty plugin which already provides support for Jetty and Tomcat: https://github.com/akhikhl/gretty

**Comment by mikecroft** [comment]
Isn't it possible to use the Gradle Cargo plugin?
http://stackoverflow.com/a/32949793/212224

I know that the Maven Cargo plugin works with Payara Server when specifying `glassfish4x`, though it doesn't work with embedded.

Payara Micro does have a Maven deployer now, though I don't know how good the interoperability is between Maven and Gradle
http://blog.payara.fish/payara-micro-maven-deployer-demo

**Comment by mikecroft** [comment]
Do you think there is still a need for Gradle specific tooling, @mweisshaupt1988 given the above?

**Comment by mikecroft** [comment]
Closing as no longer an issue. If there is still a need for more tooling beyond what is already available, I would suggest creating a new issue.
