### ISSUE TITLE
Arquillian and Payara 5

### ISSUE THREAD

**Issue by CSchulz** [payara/Payara#2145]
# Description #
----------
It should be possible to use Payara 5 together with Arquillian.

I am not sure if it should be created here or in the arquillian-container-glassfish.

## Current Outcome

```
Nov. 10, 2017 8:08:49 NACHM. org.jvnet.hk2.config.ConfigParser handleElement
SCHWERWIEGEND: Ignoring unrecognized element jms-service at Line number = 101
Column number = 72
System Id = null
Public Id = null
Location Uri= null
CharacterOffset = 5783

Nov. 10, 2017 8:08:49 NACHM. com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findDerbyClient
INFORMATION: Cannot find javadb client jar file, derby jdbc driver will not be available by default.
Nov. 10, 2017 8:08:49 NACHM. org.glassfish.security.services.impl.authorization.AuthorizationServiceImpl initialize
INFORMATION: Authorization Service has successfully initialized.
Nov. 10, 2017 8:08:49 NACHM. org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator null
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.408 sec <<< FAILURE! - in com.github.cschulz.payaraarquillian.CustomerTest
com.github.cschulz.payaraarquillian.CustomerTest  Time elapsed: 6.407 sec  <<< ERROR!
java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)


Results :

Tests in error: 
  JUnit4Provider.invoke:161->executeTestSet:238->executeWithRerun:274->execute:367 » NoSuchMethod
```

## Steps to reproduce (Only for bug reports) 

https://github.com/CSchulz/payara5-arquillian

Execute `mvn test`

## Environment ##

- **Payara Version**: 5.0.0.Alpha3
- **JDK Version**: Oracle 8, Oracle 9
- **Operating System**: Linux, Mac

**Comment by smillidge** [comment]
Have you tried one of these?

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22fish.payara.arquillian%22

**Comment by CSchulz** [comment]
I have tried the embedded one, yes. The result is the same.

**Comment by arjantijms** [comment]
Arquillian itself should definitely work now, as we test the Payara-5 branch using Arquillian all the time. Also see https://github.com/javaee-samples/javaee8-samples This uses Arquillian and Payara 5.

Closing for now, but it anything still doesn't work, don't hesitate to open again.

**Comment by CSchulz** [comment]
It seems there is an issue with Java 9 see https://github.com/javaee-samples/javaee8-samples/issues/20
