### ISSUE TITLE
Excessive number of JAR scanner threads leads to high JVM native memory usage

### ISSUE THREAD

**Issue by lreimer** [payara/Payara#2150]
# Excessive number of JAR scanner threads leads to high JVM native memory usage #
----------

When running Payara server full on large OpenShift cluster installations with cluster nodes with a lot of CPU cores (like 128 cores or more) we are seeing a high number of `deployment-jar-scanner` and `dol-jar-scanner` threads being started and waiting. Depending on the configured thread stack size of the JVM (1MB per default) this will lead to a high JVM native memory usage.

## Expected Outcome

Once the server is up and running and all applications are deployed these threads should not be required anymore (?) and could be stopped and released again. Thus reducing the JVM native memory usage of the Docker container.

## Current Outcome

Currently, we are seeing a large number of `deployment-jar-scanner` and `dol-jar-scanner` threads WAITING and thus waisting JVM native memory.

## Steps to reproduce (Only for bug reports) 

Basically, all you need to do is to start the default Payara server on an OpenShift cluster with cluster nodes that have a lot of CPU cores (like 128 and more).

1 -** Use the default `payara/server-full`. Deploy any sample app (or none).

2 -** Deploy the image to an OpenShift cluster. Beware: the cluster nodes need to have a lot of CPU cores to show the behaviour.

3 -** Log into one of the pods of the OpenShift deployment.

   $ oc rsh <pod-name>

4 -** Get the stack trace and count the numbers of `deployment-jar-scanner` and `dol-jar-scanner` threads using `jstack 1 | grep jar-scanner | wc -l

### Samples

Any Payara example will suffice and should show the described behaviour. The problem is, that you will need a really large OpenShift cluster setup with cluster nodes with 128 cores or more. 

## Context (Optional)

Currently, I am seeing excessive native memory usage for all our Payara server pods on OpenShift. Due to the high number of JAR scanner threads this leads, depending on the the configured thread stack size, to a lot of native memory being occupied by the JVM.

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Full
- **JDK Version**: OpenJDK 8_141
- **Operating System**: Linux
- **PaaS**: OpenShift 3.5

**Comment by lreimer** [comment]
The relevant classes that cause the described behaviour are in `com.sun.enterprise.v3.server.ApplicationLifecycle` line 2258 ff

```java
private ExecutorService createExecutorService() {
        Runtime runtime = Runtime.getRuntime();
        int nrOfProcessors = runtime.availableProcessors();
        return Executors.newFixedThreadPool(nrOfProcessors, new ThreadFactory() {
            ...
        });
    }
```

and in `com.sun.enterprise.deployment.annotation.impl.ModuleScanner` lines 351 ff.

```java
protected synchronized ExecutorService getExecutorService() {
        if (executorService != null) {
            return executorService;
        }
        Runtime runtime = Runtime.getRuntime();
       int nrOfProcessors = runtime.availableProcessors();
        executorService = Executors.newFixedThreadPool(nrOfProcessors, new ThreadFactory() {
            ...
        });
        return executorService;
    }
```

**Comment by lreimer** [comment]
Suggested improvement: usage a cached thread pool executor service instead.

```java
executorService = Executors.newCachedThreadPool(new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                ...
            }
        });
```

**Comment by lprimak** [comment]
Fixeed in #2151
