### ISSUE TITLE
How to close JSESSIONID only

### ISSUE THREAD

**Issue by sf019jp** [payara/Payara#2158]
# Description #
----------

Is there a way to close JSESSIONID only, in an environment using both JSESSIONIDSSO and JSESSIONID?

## Detail

Currently, we are exploring ways to establish different JSF sessions in a single browser multi view (TAB) environment.
As means, authentication is performed by SSO, and implementation is proceeded by establishing multiple view (sessions) by single authentication by making different JSESSIONID for each view.

The authentication processing part by SSO already exists.

## Task

When we close view, we do not destroy JSESSIONIDSSO and we do not know how to close JSESSIONID only.
Currently, JSF session close is done by HttpSession.invalidate ();
However, with this method, both JSESSIONIDSSO and JSESSIONID are closed, so if you perform [close] with a single view, all views will log out.

When closing view, closing the tab without doing [close] is not a problem, but in that case, I think that resources related to JSESSIONID will remain.

Because we plan to set a long timeout time for internal work, resource leak is concerned.
Therefore, I would like to close JSESSIONID without destroying JSESSIONIDSSO, but unfortunately I do not know how to do it.

**Comment by smillidge** [comment]
This is very much a usage question. Can you move the question over to the Payara Forum https://groups.google.com/forum/#!forum/payara-forum.
Thanks

**Comment by sf019jp** [comment]
Thank you for your advice.

I posted the ticket to groups.google.com again.
