### ISSUE TITLE
Clarifications on Embedded Payara 

### ISSUE THREAD

**Issue by arcuri82** [payara/Payara#2178]
Hi,
  I am a frustrated Wildfly user, and was planning to give a try to Payara before giving up and spend the next weeks rewriting everything in Spring.

Not sure if this is the right place to report it (maybe a developer mailing list could had been more appropriate?), but currently the information that I find online are not enough to make a decision to invest time in trying out Payara. The following link was very useful, but not enough:

[1] http://blog.payara.fish/using-payara-embedded-as-an-arquillian-container-inside-intellij-idea

 What I need to know is (and I would recommend to make it clear in the documentation):

1) is Payara Embedded a real, full blown JEE container like Payara Server? Or is it a watered-down version? (like it is for the "embedded" versions of other JEE containers). 

2) How to run an Arquillian test with Embedded Payara like in [1], but on an ephemeral port? in [1], it was hardcoded to 7070, which makes it useless in CI and parallel builds. 

many thanks

**Comment by Cousjava** [comment]
In answer to your first question, Payara Embedded is a full application server that you can run Java EE applications on. The difference between embedded and full is that full is stand-alone while embedded is for being embedded within your application. See http://blog.payara.fish/using-payara-embedded-and-payara-micro-with-maven.

In answer to your second question, to run Arquillian on a different port change the bindhttpport in the arquillian.xml file.

**Comment by arcuri82** [comment]
many thanks for the quick answer ;)

> In answer to your second question, to run Arquillian on a different port change the bindhttpport in the arquillian.xml file.

thx, but that does not fully answer my question though. Yes, I can change it, but that does not make it ephemeral. I could set it to "0" to have it ephemeral, but then how to read the actual bound port used/chosen by Payara?

**Comment by smillidge** [comment]
There has been a lot of change since this issue was created.
We have an arquillian connector for Payara Micro now
Also you can read the port Payara Micro is bound to by using the Microprofile Config api using
```java
@Inject
ConfigProperty(name="payara.instance.http.port")
int port;
```
