### ISSUE TITLE
[payaya-embedded-all 174] EJBContainer fails to load EJB modules

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#2188]
# Description #
----------

container = EJBContainer.createEJBContainer(properties) fails to load modules if the underlying ejb-jar archive contains files other than java classes or zip archives.

This bug has been introduced in PR #1790 

In few words, the container detects whether or not the module to deploy is an EJB module by scanning annotations of classes, but `GenericAnnotationDetector#scanArchive` crash when it try to read a XML file as an archive... 

Here is a stack trace : 
```
java.lang.RuntimeException: java.io.IOException: invalid zip file: file:/path/to/exploded-jar/config.xml
	at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:205)
	at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:182)
	at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:162)
	at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:98)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:336)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:381)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:368)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:267)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:130)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
```

As @Cousjava argues in response to @smillidge (https://github.com/payara/Payara/pull/1790#discussion_r129087895), the code stands within a try statement, catching all IOExceptions.

It seems legit, but `com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:205)` catch all IOExceptions to re-throw Runtime ones. Hence, the exception is not catch by the inner catch block but the outer one, skipping all next entries.

## Expected outcome ##
EJB container start and load EJB modules 

## Current outcome ## 
EJB container start without error but do not contains any modules 

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full (embedded-all maven artifact)
- **JDK Version**: openjdk 8
- **Operating System**: Linux

**Comment by maxencelaurent** [comment]
to reproduce:
```
git clone https://github.com/maxencelaurent/payara_2188.git
cd payara_2188/
mvn test
```
no problem with payara 173: 
```
git checkout payara-173
mvn test 
```

**Comment by smillidge** [comment]
I ran your test case and I got;
```
INFO: embed-classes was successfully deployed in 1,355 milliseconds.
Hello, World!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.28 sec
JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]
JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by maxencelaurent** [comment]
Since GenericAnnotationDetector#scanArchive only needs one positive match, It may actually depends on the underlying jar entries order

It seems, your system process MySingleton.class first, not event trying to scan the XML file. 

I'll update my test case

**Comment by maxencelaurent** [comment]
btw: 
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by maxencelaurent** [comment]
First new use case on "withLog" branch.
```
git clone https://github.com/maxencelaurent/payara_2188.git
cd payara_2188/
git checkout withLog
mvn test
```

I removed all EJB annotations, but I turned scanArchive logging on.

This test will never fails but one can "read" some useful informations in the logs:
```
Dec 04, 2017 9:01:49 AM org.glassfish.deployment.common.GenericAnnotationDetector scanArchive
WARNING: NCLS-DEPLOYMENT-00009
Dec 04, 2017 9:01:49 AM org.glassfish.ejb.embedded.EJBContainerProviderImpl createEJBContainer
SEVERE: ejb.embedded.no_modules_found
```
(don't know why but the log message is not interpolated it should be 
`NCLS-DEPLOYMENT-00009 => Failed to scan archive for annotations: java.io.IOException: invalid zip file: file:/home/maxence/Projects/payara_2188/target/embed-classes/someConfig.xml`
This line indicates that the whole archive is being skipped.


In the withLog branch, there is two XML files. So I expect to read two NCLS-DEPLOYMENT-00008 lines in the log, one for each files:
```
Dec 04, 2017 9:01:49 AM org.glassfish.deployment.common.GenericAnnotationDetector scanArchive
WARNING: NCLS-DEPLOYMENT-00008
WARNING: NCLS-DEPLOYMENT-00008
Dec 04, 2017 9:19:57 AM org.glassfish.ejb.embedded.EJBContainerProviderImpl createEJBContainer
SEVERE: ejb.embedded.no_modules_found
```

`NCLS-DEPLOYMENT-00008` means `Error in jar entry: java.io.IOException: invalid zip file: file:/home/maxence/Projects/payara_2188/target/embed-classes/someConfig.xml`
Which indicates a specific entry is invalid. This error will only discard the current entry, not the whole archive

**Comment by maxencelaurent** [comment]
This issue depends on the internal order of the filesystem. On my system (ext4) this order is not defined and there is no way to set it by hand.

So, I updated my test case by adding even more XML files.
The test will only pass if the "ch" directory stands at the first position in the embed-classes directory:
```
$ ls -1U src/main/resources/embed-classes/
```
shell script with user friendly output : 
```
#!/bin/sh
if  [ `ls -1U src/main/resources/embed-classes/ | head -n 1` = "ch" ] ; then  echo "OK"; else echo "NOT OK"; fi
```

After removing all XML files, the test run fine: 
```
rm src/main/resources/embed-classes/*.xml
mvn clean test
git reset --hard
```

**Comment by smillidge** [comment]
I get the error now. Thanks for the detailed test case.
