### ISSUE TITLE
Provide cmd line recall and editing in asadmin

### ISSUE THREAD

**Issue by mamboking** [payara/Payara#219]
It would be nice if we had command history and the ability to recall/edit previous commands in asadmin.  You could use something like [JLine](http://jline.sourceforge.net/).

**Comment by dmatej** [comment]
JLine is unsupported old project, but it seems it has a successor: https://github.com/jline/jline2

**Comment by phillipross** [comment]
+1

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-1066`

**Comment by Cousjava** [comment]
Fixed by #3096
