### ISSUE TITLE
Override environment entries

### ISSUE THREAD

**Issue by vanuatoo** [payara/Payara#2194]
# Description #
----------

I have a web application in which I have defined environment variable

```
<?xml version="1.0" encoding="UTF-8"?>

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
     version="3.1">
    <env-entry>
        <description>Test Variable</description>
        <env-entry-name>env.name</env-entry-name>
        <env-entry-type>java.lang.String</env-entry-type>
        <env-entry-value>env.value</env-entry-value>
    </env-entry>
</web-app>
```

In my Stateless session bean I use this variable using

```
@Resource(name="env.name")
 private String envVar;

```
I want to override this value in production. One way is to replace web.xml during deployment build, but I discovered that asadmin has commands for it: list-web-env-entry, set-web-env-entry
When I run list-web-env-entry for my application it shows nothing.
Also If I run set-web-env-entry it's not picked up my application either.

## Expected Outcome

set-web-env-entry should override the value

## Current Outcome

set-web-env-entry does not override the value

## Steps to reproduce (Only for bug reports) 

- **Payara Version**: 4.1.173
- **Edition**: Full
- **JDK Version**: Oracle 8
- **Operating System**: Linux
- **Database**: PostgreSQL

**Comment by lprimak** [comment]
Have you tried
```name="${ENV=env.name}"``` for environment variables or
```name="${env.name}"``` for system properties?
It should work

**Comment by mikecroft** [comment]
Hi @vanuatoo, have you tried correcting your annotation?

**Comment by vanuatoo** [comment]
I have tries every combination with Payara 5.181 but nothing works
