### ISSUE TITLE
If an error occurres while generating the default domain, the build process does not stop

### ISSUE THREAD

**Issue by aojava** [payara/Payara#220]
The marked ( ==> ) error in the following log snippet from the build process should stop the build process, but it doesn't.

       [INFO]
       [INFO] ------------------------------------------------------------------------
       [INFO] Building Payara Web Distribution 4.1.152-SNAPSHOT
       [INFO] ------------------------------------------------------------------------
       [INFO]
       [INFO] --- glassfishbuild-maven-plugin:3.2.20:echo (echo) @ payara-web ---
       [INFO] ------------------------------------------------------------------------
       [INFO] Building in C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web
       [INFO] ------------------------------------------------------------------------
       [INFO]
       [INFO] --- maven-enforcer-plugin:1.0-beta-1:enforce (enforce-versions) @ payara-web ---
       [INFO]
       [INFO] --- maven-dependency-plugin:2.6:unpack-dependencies (default-unpack-dependencies) @ payara-web ---
       [INFO]
       [INFO] --- maven-assembly-plugin:2.3:single (default-single) @ payara-web ---
       [INFO] Reading assembly descriptor: src/main/assembly/payara-web.xml
       [INFO] Copying files to C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target\stage
       [INFO]
       [INFO] --- glassfishbuild-maven-plugin:3.2.20:exec (create-domain) @ payara-web ---
       [INFO] executable: C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target/stage/payara41/bin/asadmin.bat
       [INFO] commandLineArgs: --user admin create-domain --template=C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target/stage/payara41/glassfish/common/templates/gf/appserver-domain.jar --nopassword --savelogin=true --checkports=false --adminport 4848 --instanceport 8080 --keytooloptions CN=localhost domain1
       [INFO] [exec] Der Befehl "java" ist entweder falsch geschrieben oder
       [INFO] [exec] konnte nicht gefunden werden.
    ==>[INFO] [exec] Result: 1
       [INFO]
       [INFO] --- glassfishbuild-maven-plugin:3.2.20:zip (default-zip) @ payara-web ---
       [INFO] duplicate: preserve
       [INFO] file set : C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target\stage (excludes: [], includes: [**/bin/*, **/bin/*.bat, **/lib/nadmin*])
       [INFO] file set : C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target\stage (excludes: [**/bin/*, **/bin/*.bat, **/lib/nadmin*], includes: [])
       [INFO] [zip] Building zip: C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target\payara-web.zip
       [INFO]
       [INFO] --- maven-install-plugin:2.4:install (default-install) @ payara-web ---
       [INFO] Installing C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\target\payara-web.zip to C:\Java\NetBeansProjects\3rdParty\Payara\4.1\maven\repo\org\glassfish\main\distributions\payara-web\4.1.152-SNAPSHOT\payara-web-4.1.152-SNAPSHOT.zip
       [INFO] Installing C:\Java\NetBeansProjects\3rdParty\Payara\4.1\appserver\distributions\payara-web\pom.xml to C:\Java\NetBeansProjects\3rdParty\Payara\4.1\maven\repo\org\glassfish\main\distributions\payara-web\4.1.152-SNAPSHOT\payara-web-4.1.152-SNAPSHOT.pom
       [INFO]
       [INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ payara-web ---

**Comment by smillidge** [comment]
Apologies but can you translate the German error message 
Der Befehl "java" ist entweder falsch geschrieben oder  konnte nicht gefunden werden.

My bad German translation is Java can't be found or is written incorrectly.

Is this error due to JAVA_HOME not being set?

**Comment by aojava** [comment]
Your translation is correct, but this is not related to the JAVA_HOME property. JAVA_HOME is set correct, otherwise maven wouldn't run. At this point in the build script, JAVA_HOME is not used. Instead the script calls "java" without a path. So java.exe would be only found, if it is in the search path of the os, what isn't the case on my system.

**Comment by Pandrex247** [comment]
Fixing this would require that we create a _failOnError_ type parameter for the `glassfishbuild-maven-plugin`, in a similar vein to the `maven-antrun-plugin`. As this isn't affecting Payara itself, and we believe this is going to be an uncommon development setup (where Java isn't on the Path), we're going to leave this for now.

For the time being, we'll create some build instructions, and state that you have to have Java on the PATH environment variable as a requirement.
