### ISSUE TITLE
Using Payara 5 Beta 1 results in ssl handshake_failure when executing rest calls to cloudflare

### ISSUE THREAD

**Issue by Erates** [payara/Payara#2241]
# Description #
----------

I'm trying to write a small application that executes Rest calls to some Cloudlfare hosted websites. When executing the call, the webserver (Cloudflare) sends a SSL alert stating no more than handshake_failure.
Running the same application on Payara 4.1.2.173 gives the expected result (the response from the Rest call).

## Expected Outcome

The REST call should be executed as expected.

## Current Outcome

The webserver returns an SSL handshake_failure.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Deploy an application that executes Rest calls

3 -**  Test the Rest calls

## Environment ##

- **Payara Version**: 5.0.0.Beta1
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8.151
- **Operating System**: Windows 10

**Comment by michaelranaldo** [comment]
Hi @Erates,

Have you imported the certificate into Payara?

**Comment by smillidge** [comment]
Can you send us a test case?

**Comment by smillidge** [comment]
Close due to inactivity
