### ISSUE TITLE
Last two rows have correct foreign key - remaining not

### ISSUE THREAD

**Issue by trondarild-lode-tobiassen-heidelberg** [payara/Payara#2243]
# Description #
----------
Please see description here: 
https://groups.google.com/forum/?__hssc=229474563.5.1513864580267&__hstc=229474563.86541000e505ac969516f6301ea8e343.1513539804925.1513539804925.1513864580267.2&__hsfp=3676874165&hsCtaTracking=ee96a587-4450-4296-b986-ac67f6da0574%7Cff3c7a3b-1cde-4e52-b2ad-e162643b9683#!topic/payara-forum/jbfSrO-e9vQ

## Expected Outcome

All rows should have foreign key 

## Current Outcome

only last two rows (or only last in glassfish 4.1 and 5.0) have the foreign key.

## Steps to reproduce (Only for bug reports) 
Hard to reproduce. Code consists of a thousand classes. Recommend jpa code review.

## Context (Optional)

Trying to log SIP messages to database.

## Environment ##

- **Payara Version**: 4.1.1.174
- **Edition**: Full
- **JDK Version**: 8 u151 - Oracle
- **Operating System**: Windows7
- **Database**: Oracle 12c ojdbc7

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
Actually the foreign key is missing as you will see from the description behind the link.

**Comment by smillidge** [comment]
Hi we will need a simple self-contained test case that demonstrates the issue to help diagnose any problem. There is not enough information in the bug report or forum posting to know how to reproduce the issue.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
I am afraid it is the complexity which causes this to happen. It happens 
when I use a third-party client towards my server. It attempts 
logon/registration while I log every message. I still don't know if this 
is an eclipselink or database problem. I am investigating with 
mariadb/mysql as an alternative to oracle. Also tried hibernate on 
Wildfly but run into other problems (failing on code that goes well with 
glassfish and payara). If you can't check out if there might be issues 
with many conscutive requests I will report back when I know more about 
how hibernate performs.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
Hibernate behaves the same way. MySql behaves the same way. I tried updatable=true. I will try bidirectional.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
Sorry for not responding. I have learned that unidirectional works just fine for several parents so it should not cause any trouble.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
The problem is unresolved.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
The only common denominator is JPA as far as I can see.
