### ISSUE TITLE
Weird master password update

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#2255]
# Description #
----------

After the master password update on a domain, remote nodes asks for old masterpassword, that is actually new.

## Expected Outcome
For message "Enter the old master password" I have to enter an old password.

## Current Outcome
For message "Enter the old master password"  I have to enter a new password.

## Steps to reproduce (Only for bug reports) 
1) download payara 174
2) unzip archive
3) asadmin start-domain domain1
4) create test-cluster
5) create test-node
6) create test-instance on test-node
7) start instance
8) asadmin change-master-password --savemasterpassword=true domain1
9) asadmin stop-domain domain1
10) asadmin change-master-password --savemasterpassword=true domain1
    old="changeit"
    new="newchangeit"
    new2="newchangeit"
11) asadmin start-domain domain1
12) stop test-instance from gui
13) try to start test instance from gui
14) on node server run: asadmin change-master-password --savemasterpassword=true test-node
    old="changeit"
    Fails with message: 
      "Incorrect old master password. You will not be able to change it.
       Command change-master-password failed."
15) 
  a) retry asadmin change-master-password --savemasterpassword=true test-node
    enter three times the new password "newchangeit"
    Command change-master-password executed successfully.
 
  b) sometimes a new password cannot be set even with the new password as the old
     This problem occurs, if there are more instances in single node directory. The only known workaround for case b) is removal of node from GUI and creation of a new node. I didn't test, whether removal of other instances solves this problem too.

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full 
- **JDK Version**: 1.8.0_144 
- **Operating System**: RHEL 7 
- **Database**:

**Comment by smillidge** [comment]
Please try Payara 5 and see if it is still a problem there.

**Comment by sgflt** [comment]
Tested 5.191 and the described behavior is still present.

**Comment by rdebusscher** [comment]
Hi @sgflt,

The issue is solved as part of the Payara Server 5.193 release. See https://github.com/payara/Payara/pull/4133

Regards
Rudy
