### ISSUE TITLE
"An error occured" during editing of JDBC Connection Pool Properties

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#2259]
# Description #
----------

During editing of JDBC connection pool properties the error message "An error occured" is displayed after pressing "Save".

## Expected Outcome

Never ever make you application print "An error occured". All error messages of all possible inputs, configuration values or states of all applications need to provide helpful self-explanatory feedback!

## Current Outcome

![grafik](https://user-images.githubusercontent.com/4369372/34901119-b04c8fb8-f806-11e7-9ade-5da5a229f331.png)

and

    SCHWERWIEGEND:   RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/jdbc-connection-pool/project1/property.json'; attrs = '[{"name":"Password","description":"","value":"a"},{"name":"PortNumber","description":"","value":"1527"},{"name":"Host","description":"","value":"localhost"},{"name":"User","description":"","value":"b"},{"name":"DatabaseName","description":"","value":"c"}]'

in `server.log` of `payaradomain`.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Create the Connection pool (all default properties are missing btw)

3 - ** Edit the properties as shown on the screenshot and click save

## Environment ##

- **Payara Version**: 5.0-beta2-20180112.004301-21
- **Edition**: Full
- **JDK Version**: 8 u151 - OpenJDK
- **Operating System**: Linux
- **Database**: Apache Derby 10.12.1.1

**Comment by afrunt** [comment]
it is a known issue [2149](https://github.com/payara/Payara/issues/2149)

**Comment by mikecroft** [comment]
Thanks @krichter722 - as @afrunt points out, this is a known issue, but I will keep this open since the error message could use some extra generic instructions to debug the problem
