### ISSUE TITLE
HTTP access logging of asynchronous JAX-RS methods leads to Weld warnings

### ISSUE THREAD

**Issue by jo-ka** [payara/Payara#2261]
# Description #
----------

If HTTP access logging is turned on, resuming JAX-RS AsyncResponses on a different thread leads to various Weld warnings.

## Expected Outcome

There should be no warnings, as is the case with Payara before 4.1.2.172, as warnings indicate an underlying problem.

## Current Outcome

I observed these warnings:

- `WARN: WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.`
- `WARN: WELD-000225: Bean store leak detected during org.jboss.weld.context.http.HttpSessionContextImpl association: org.apache.catalina.connector.RequestFacade@30cec`
- `WARN: WELD-000335: Conversation context is already active, most likely it was not cleaned up properly during previous request processing: org.apache.catalina.connector.RequestFacade@30cec`

The first one even occurs in a minimalistic setup as outlined below, whereas I encountered the other two only in an existing, complex application with different asynchronous JAX-RS calls.

## Steps to reproduce
Turn on HTTP access logging on Payara and make a request to an asynchronous JAX-RS method.

### Samples

A minimalistic setup to trigger at least one of the warnings:

```
@Path( "async" )
public class AsyncResource
{
   @Inject
   private AsyncService service;

   @GET
   @Produces( { MediaType.TEXT_PLAIN } )
   public void getAsyncResource( @Suspended final AsyncResponse asyncResponse )
   {
      service.asyncMethod( asyncResponse );
   }
}
```

```

@Singleton
public class AsyncService
{
   @Asynchronous
   public void asyncMethod( AsyncResponse response )
   {
      response.resume( "Hello world!" );
   }
}
```

Deploy a module consisting of these two classes (and possibly configuration like beans.xml), turn on HTTP access logging on Payara, and make a request to the resource ("async").

## Context

I strongly suspect that this is related to https://github.com/payara/Payara/issues/1401, which I had reported, respectively the internal issue https://github.com/payara/Payara/pull/1571. Unfortunately, I could only now (attempt to) migrate to a new Payara release from the 4.1.1.171.0.1 I was using back then. I tried with 4.1.2.174 initially and after witnessing the warnings, I tried 4.1.2.173 and 4.1.2.172, all of which are affected. The bugfix from https://github.com/payara/Payara/pull/1571 was applied to 4.1.2.172.

There's also a specific mention of those three warnings in the Weld documentation, cf. http://weld.cdi-spec.org/documentation/#8.

Note that the warning(s) does *not* occur in the mininmalistic sample above if in `AsyncResource` instead of `service.asyncMethod( asyncResponse );` this is used: `asyncResponse.resume( "Hello world!" );`. So this must have to do with the processing on a different thread.

## Environment ##

- **Payara Version**: 4.1.2.172 - 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8u131 OpenJDK
- **Operating System**: Debian Linux
- **Database**: PostgreSQL

**Comment by smillidge** [comment]
Internal issue number PAYARA-2212

**Comment by smillidge** [comment]
Fixed by #2379

**Comment by jo-ka** [comment]
Thanks a lot guys!

**Comment by roberto-cisternino** [comment]
WELD-000714: HttpContextLifecycle guard leak detected. The Servlet container is not fully compliant. The value was 1

Detected on Payara 6.2023.10 using Jakarta 10.0.0 and a basic REST resource configuration.
It happens immediately after startup. No other errors are present.
