### ISSUE TITLE
Inclusion of Soteria leads to warnings on module deployment

### ISSUE THREAD

**Issue by jo-ka** [payara/Payara#2266]
# Description #
----------

With the inclusion of Soteria in Payara 4.1.2.174, there are warning log messages concerning Soteria implementation classes on every module deployment.

## Expected Outcome

There should be no warnings, especially as I didn't (mis-)configure anything related to Soteria but used a stock Payara installation.

## Current Outcome

These two warnings appear (which look all the more menacing due to the coloured font of the "WARNING" in the middle of the line):

- `Warning: The following warnings have been detected: WARNING: Parameter interceptedBean of type javax.enterprise.inject.spi.Bean<?> from private javax.enterprise.inject.spi.Bean<?> org.glassfish.soteria.cdi.RememberMeInterceptor.interceptedBean is not resolvable to a concrete type.`
- `Warning: The following warnings have been detected: WARNING: Parameter interceptedBean of type javax.enterprise.inject.spi.Bean<?> from private javax.enterprise.inject.spi.Bean<?> org.glassfish.soteria.cdi.LoginToContinueInterceptor.interceptedBean is not resolvable to a concrete type.`

## Steps to reproduce

Deploy any module.

## Context

When searching for the log message, I found at least two different recent posts that exhibit the same behaviour: https://github.com/javaserverfaces/mojarra/issues/4264 and https://stackoverflow.com/questions/48074073/how-to-use-omnifaces-eager-annotation-with-primefaces.

As the potential consequences don't seem to be so dire from the log messages as long as one does not use Soteria in the first place, it would be fine if Soteria could just be completely disabled. The release notes say it's optional, so I assume this would be possible somehow, maybe someone could tell me how?

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8u131 OpenJDK
- **Operating System**: Debian Linux
- **Database**: PostgreSQL

**Comment by michaelranaldo** [comment]
Hi @jo-ka,

Thanks for reporting this, created internal issue PAYARA-2364.

**Comment by smillidge** [comment]
Fixed by #2407

**Comment by HeinBloed** [comment]
Thanks guys!

**Comment by AllenConquest** [comment]
Is this fix available in Payara 4 ?

**Comment by smillidge** [comment]
There are no more Payara 4 community releases. It will be backported into customer releases of 4.x which have a 10 year support lifecycle.

**Comment by AllenConquest** [comment]
I believe our company has a support contract with Payara, would that entitle us to customer releases?

**Comment by smillidge** [comment]
Yes raise a ticket on support.payara.fish
