### ISSUE TITLE
Support war and ear scoped Hazelcast Instances

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#227]
Currently to store complex objects in the embedded Hazelcast Instance you need to either add the classes to the system classpath or manually create a new Hazelcast Instance in your war/ear file that defines the classes. In which case CDI does not work.

This enhancement request is to find a solution to this problem.

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-1062`

**Comment by smillidge** [comment]
Not going to happen given the likely design of Payara 5.
