### ISSUE TITLE
Payara Server 4.1.2.174 - NoClassDefFoundError: javax/cache/spi/CachingProvider

### ISSUE THREAD

**Issue by andreas-gilbert** [payara/Payara#2274]
# Description #
----------

Using the glassfish/lib/embedded/glassfish-embedded-static-shell.jar a NoClassDefFoundError: javax/cache/spi/CachingProvider is thrown.

## Expected Outcome

Starting of embedded glassfish without exceptions.

## Current Outcome

NoClassDefFoundError: javax/cache/spi/CachingProvider

## Context (Optional)

Inspecting the glassfish/modules directory i found a missing cache-api.jar from 171 to 174.
After copying the cache-api.jar from 171 the error is gone.

Interesting detail: payara-embedded-all-4.1.2.174 contains missing class files...
(same as cache-api.jar)

## Environment ##

- **Payara Version**: Payara Server 4.1.2.174 (Full)
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Linux
- **Database**:

**Comment by smillidge** [comment]
we think this is an upgrade issue. Can you reproduce this on a clean installation of 174 or later?

**Comment by andreas-gilbert** [comment]
yep, reproducible with a clean installation of 174

**Comment by andreas-gilbert** [comment]
cache-api.jar seems to be missing in the 181 too ...

**Comment by smillidge** [comment]
the class is in the jar file `jsr107-repackaged.jar`
