### ISSUE TITLE
Environment variable substitution happens too late for @Startup annotated singleton EJB 

### ISSUE THREAD

**Issue by jbndbc** [payara/Payara#2283]
# Description #
----------
Environment variable substitution happens too late for use in singleton EJB when the bean is also annotated with @Startup.

## Expected Outcome
Using

@Resource(lookup = "java:app/env/url/myenv")
private String myEnv;

with associated mapping in glassfish-resources.xml

<custom-resource ...>
    <property name="value" value="${ENV=MY_ENV}"/>
  </custom-resource>

I expect the myEnv field to be set to whatever value the MY_ENV environment variable has at server startup.

## Current Outcome
myEnv.equals("${ENV=MY_ENV}") == true

### Samples
https://github.com/DBCDK/payara-micro-missing-env-var-subst

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Micro
- **JDK Version**: 1.8.0_151-b12
- **Operating System**: Linux

**Comment by smillidge** [comment]
I'm not sure if this is supposed to work. Thanks for the test case I can experiment.

**Comment by smillidge** [comment]
One thing you could do is use the Microprofile config api and replace the code with;

```
// Example injection the standard environment variable home
    @Inject
    @ConfigProperty(name = "MY_ENV", defaultValue = "MY_ENV environment variable not set")
    String myEnv;
```
See https://github.com/payara/Payara-Examples/tree/master/microprofile/config-injection/src/main/java/fish/payara/examples/microprofile/configinjection 

That should do similar to what you are trying to do

**Comment by smillidge** [comment]
or even simpler ;-)
```
String myEnv = System.getEnv("MY_ENV");
```
the microprofile way would allow you to override the environment variable by setting a config property at the server, domain, config etc. level in the admin console.

**Comment by jbndbc** [comment]
Thx for the reply, the @ConfigProperty approach works fine in this case, and I will indeed be switching over to that, but I guess I would still run into trouble if I had a @Startup bean making use of a persistence.xml or ejb-jar.xml containing substitution variables?

**Comment by smillidge** [comment]
I don't know if you would run into trouble with a start up EJB bean for persistence.xml. Env replacement isn't global just in key places. I'm not sure (I haven't tried) to see if it works in general for JNDI string properties.

**Comment by smillidge** [comment]
Please try Payara 5 and see if it is still a problem there.

**Comment by rdebusscher** [comment]
Hi,

I'm closing this as the recommended approach for reading ENV variables is using MicroProfile Config.

Regards
Rudy
