### ISSUE TITLE
Provide an option to create a missing directory with the restore-domain command /CUSTCOM-84

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara#2285]
# Description #
----------

A user got in touch via email to suggest that the restore-domain command should succeed if a directory does not exist.

> The commands from the blog were helpful, but did not work for me. What did work was:
> 
>  ```bash
> mkdir -p /opt/payara5/glassfish/domains/isd
> cd /opt/payara5/glassfish/bin
> ./asadmin restore-domain --backupdir /root/backup isd
> ```
>  
> The first command (mkdir) is not obvious. If the directory doesn’t exist, create it. If you want to be safe about it, prompt the user, “Would you like to create this directory?” and offer a “--interactive false” option, which is fairly POSIX-ish.

The current behaviour is for the following exception to print:
`com.sun.enterprise.backup.BackupException: The domain directory doesn't exist.  Expected: ...`

## Expected Outcome

In our discussion, I disagreed that silently creating the directory would be the correct course of action due to the potential for misspellings causing unpredictable behaviour, however I want to leave this suggestion as a potential enhancement since others may disagree with me.

The suggestion to add a prompt has the potential to break compatibility with existing scripts, so this is probably not a good idea.

A third option would be to add an option to enable this feature (like, for example `mkdir` vs `mkdir -p`). There is already a `--force` option which has a behaviour attached to it; I would avoid adding further behaviour to that command since it may surprise people who are unaware of the change (despite the semantics of the option making sense).

## Current Outcome

If the directory does not exist, asadmin prints out a message saying that it doesn't exist and fails.

## Steps to reproduce (Only for bug reports) 

1.  Run the `restore-domain` command with a directory that does not exist

    ./asadmin restore-domain --backupdir /root/backup isd

## Environment ##

Any Payara or GlassFish

**Comment by rdebusscher** [comment]
Tracked by CUSTCOM-84

**Comment by fturizo** [comment]
As this is an internal enhancement, we'll close this issue and track it internally.
