### ISSUE TITLE
[org.glassfish.enterprise.concurrent] [[ java.lang.NullPointerException]]

### ISSUE THREAD

**Issue by afrunt** [payara/Payara#2302]
# NPE after submitting runnable task to ManagedScheduledExecutorService
----------

## Expected Outcome
Everything should work fine as it works on glassfish 5

## Current Outcome

[org.glassfish.enterprise.concurrent] [[ java.lang.NullPointerException]]

## Steps to reproduce (Only for bug reports) 

1 - Deploy this example to payaradomain https://github.com/afrunt/examples/tree/master/java-ee-8-examples/cdi-managed-scheduling

## Environment ##

- **Payara Version**: 5 Beta 1
- **Edition**: Full
- **JDK Version**: 8 u152 - Oracle
- **Operating System**: Mac
- **Database**:

**Comment by michaelranaldo** [comment]
Hi @afrunt ,

This does appear to be linked to #2305 .

Created internal issue PAYARA-2230

**Comment by afrunt** [comment]
@michaelranaldo yep, I also mentioned this assumption under that ticket, thanks

**Comment by mikecroft** [comment]
Closing this as a duplicate of #2305
