### ISSUE TITLE
Upgrade Weld to 2.2.10.Final or newer

### ISSUE THREAD

**Issue by pdurbin** [payara/Payara#234]
We are suffering from a bug at https://github.com/IQSS/dataverse/issues/1516 and would be interested in seeing Payara update Weld to 2.2.10.Final:

http://search.maven.org/#artifactdetails|org.jboss.weld|weld-osgi-bundle|2.2.10.Final|jar

Please note that there is a Glassfish4-specific version: weld-osgi-bundle-2.2.10.Final-glassfish4.jar

**Comment by smillidge** [comment]
Does it fix your bug?

Do you know what's "special" about the GlassFish specific version of Weld?

**Comment by pdurbin** [comment]
I don't expect Weld 2.2.10 to fix our bug, but it should provide extra debug information that will be useful for Weld developers since in includes https://issues.jboss.org/browse/WELD-1896

From what I understand Glassfish 4 compatibility was implemented by @mkouba in https://github.com/weld/core/commit/f83324ee131627d8ce86682ef05d0fc2e0099d21

For earlier versions of Weld such as 2.2.9, a special jar for Glassfish 4.1 was uploaded to a ticket like this: https://issues.jboss.org/browse/WELD-1857

What's new is that a special Glassfish jar is on Maven Central. See also discussion with @jharting at http://transcripts.jboss.org/channel/irc.freenode.org/%23weld-dev/2015/%23weld-dev.2015-03-23.log.html

**Comment by smillidge** [comment]
OK for GlassFish looks like they are messing with the OSGI bundle for backwards compatibility with an existing GF 4.1 server. We'll ensure next Payara release end of April can work with the standard jar.

**Comment by smillidge** [comment]
Now in upstream will be picked up via Cherrypick

**Comment by Pandrex247** [comment]
#235

**Comment by pdurbin** [comment]
> Now in upstream

Ah ha. Sure enough: https://java.net/projects/glassfish/lists/dev/archive/2015-03/message/5 . Thanks.

**Comment by smillidge** [comment]
This was applied in #235
