### ISSUE TITLE
payara-micro hazelcast kubernetes session replication problem

### ISSUE THREAD

**Issue by kissoid** [payara/Payara#2351]
# Description #
----------
I created a kubernetes cluster in google cloud kubernetes engine. My application server is payara-micro. I want to replicate session between instancea with hazelcast. I user hazelcast-kubernetes plugin. I did everything on [https://github.com/MeroRai/payara-hazelcast-kubernetes](url) and all instances when i look at logs, everything looks great.

## Expected Outcome

i want http sessions to replicate between payara-micro instances.

## Current Outcome

i am logging in my application, adding my user info to session.  sometimes first and second request is working as expected, sometimes none of theme is working and my application can not find object in session and send me not logged in message back.

## Steps to reproduce (Only for bug reports) 

Jars

[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/dnsjava-2.1.7.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/hazelcast-kubernetes-1.1.0.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jackson-annotations-2.6.0.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jackson-core-2.6.3.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jackson-databind-2.6.3.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jackson-dataformat-yaml-2.6.3.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jackson-module-jaxb-annotations-2.6.3.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/jul-to-slf4j-1.7.12.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/kubernetes-client-3.1.8.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/kubernetes-model-2.0.8.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/logging-interceptor-3.9.1.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/mysql-connector-java-5.1.23-bin.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/okhttp-3.9.1.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/okhttp-ws-3.4.2.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/okio-1.13.0.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/slf4j-api-1.7.12.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/snakeyaml-1.15.jar](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/validation-api-1.1.0.Final.jar](url)

1 -**  Configuration Files

[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/config_files/Dockerfile](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/config_files/domain.xml.txt](url)
[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/config_files/kubernetes-service.yaml.txt](url)

2 -**  Logs

[https://storage.googleapis.com/iwaport/iwa_container/iwa_home/lib/config_files/payara-hazelcast-kubernetes-logs.txt](url)

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: 
- **JDK Version**: 8 Oracle
- **Operating System**: Google Cloud Cluster Optimized OS
- **Database**: MySQL

**Comment by lprimak** [comment]
Hi,

None of your links provided are accessible.
Please fix them so we can see the errors

**Comment by kissoid** [comment]
thanks.
i resolved the problem 5 minutes ago you write answer and deleted all links. Now it is working very well on google cloud kubernetes engine. i am closing the issue

**Comment by lprimak** [comment]
Glad to hear it, thanks
