### ISSUE TITLE
JNDI Looukp problem during deployment

### ISSUE THREAD

**Issue by tkernstock** [payara/Payara#2387]
# Description #
----------
In december I upgraded from version 171 to 174 and didn't reinstall my applications (my domain including the applications is in a extra directory). Since then everything was running fine. Now I wanted to reinstall an application (.war) but now I get the following error everytime I want to install any of my applications:

2018-02-10 14:00:49,671 ERROR [admin-thread-pool::admin-listener(3)] javax.enterprise.system.tools.deployment.dol - JNDI lookup failed for the resource: Name: java:module/env/BewerbungZurueckziehen, Lookup: com.zzz.portal.boundary.aktionsmodule.Zurueckziehen#com.zzz.portal.boundary.aktionsmodule.Zurueckziehen, Type: Session.
2018-02-10 14:00:49,673 ERROR [admin-thread-pool::admin-listener(3)] javax.enterprise.system.core - Exception while deploying the app [PortalTest]
2018-02-10 14:00:49,675 ERROR [admin-thread-pool::admin-listener(3)] javax.enterprise.system.core - Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/Zurueckziehen], Lookup: [com.zzz.portal.boundary.aktionsmodule.Zurueckziehen#com.zzz.careerportal.boundary.aktionsmodule.Zurueckziehen], Type: [Session]
    at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:874)
    at com.sun.enterprise.deployment.util.ResourceValidator.validateResources(ResourceValidator.java:736) .......

The @Stateless @EJB com.zzz.portal.boundary.aktionsmodule.Zurueckziehen exists in the war file. What I realized is, that Payara tries to find [java:module/env/Zurueckziehen] now, but when I look at the logs of old installations the EJB is/was registered under /global/Zurueckziehen !!

Since this is a rather huge apllication I cannot provide a simple example for reproduction.

EDIT: I now installed the server version payara 4.1.1.171, payara 4.1.2.172, 4.1.2.173, 4.1.2.174 and 4.1.2.181 and deployed the same war file. The last version this works is 4.1.2.173. so either in 174 something broke or I have to update the domain.xml since this file stays always the same in my separated domaindirectory.

## Environment ##

- **Payara Version**: 4.1.1.174
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Windows7 & Linux 
- **Database**: MySQL

**Comment by smillidge** [comment]
Can you show the code snippet referencing the resource?

**Comment by tkernstock** [comment]
Hi Steve,
it is simply stateless ejb: 
`@Stateless
@EJB(name="Zurueckziehen", beanInterface=Zurueckziehen.class)
public class Zurueckziehen implements IAktionModul {`
that is instantiated at runtime:
`	private IAktionModul createModule(String name) {
		try{
			InitialContext ctx = new InitialContext();
			IAktionModul module = (IAktionModul) ctx.lookup("java:module/"+name);
			return module;
		} ......
`
This works perfectly on every payara version up to 173. (on which it is installed now)

I guess that the problem is how the new version tries to find the EJB. This is what I see in my logfiles on payara 4.1.2.173 when I deploy the bundle:
`Portable JNDI names for EJB Zurueckziehen: [java:**global**/portal/Zurueckziehen, java:global/portal/Zurueckziehen!com.zzz.portal.service.aktionsmodule.IAktionModul]`
the new versions tries this:
`java:module/env/Zurueckziehen`

br
Thomas

**Comment by smillidge** [comment]
Possible duplicate of #2430 
Please try setting the system property  ```-Ddeployment.resource.validation=false ``` to see if the error goes away?

**Comment by gbuckholtz** [comment]
> Possible duplicate of #2430
> Please try setting the system property `-Ddeployment.resource.validation=false ` to see if the error goes away?

I was having this problem too and using this switch made it go away.  Is that a symptom of a problem with my app or a workaround for a Payara Micro problem.  I am using the latest release version of the dockerized Payara Micro from hub.docker.com (5.183)

**Comment by andi-huber** [comment]
> Please try setting the system property `-Ddeployment.resource.validation=false` to see if the error goes away?

Ran into same issue on Payara 5.183 Web-Profile. Setting the mentioned switch solved it for me as well.
