### ISSUE TITLE
Unexpected behaviour when changing admin port using asadmin and restarting domain

### ISSUE THREAD

**Issue by sfeigl** [payara/Payara#2392]
# Description #
----------

When the admin port of a domain is changed by asadmin command line tool, the payara domain cannot be restarted by asadmin restart-domain command because the domain is not reported to be running.

## Expected Outcome

After changing the admin port, the DAS should still listen on the old port and you should be able to restart the DAS through asadmin "restart-domain" command. After the restart, the DAS should listen on the new admin port.

This is the expected behaviour, because it is the same behaviour like changing the admin port through the admin web interface.

## Current Outcome

After setting the admin port by asadmin, the DAS still listens on the old admin port, but you are unable to restart the domain by asadmin "restart-domain" as the domain is reported to be not running. Using "domain-restart", the asadmin command tries to start (not restart) the domain a second time, while the first instance is still running.

If the admin web UI was not yet initialized before changing the port, opening the admin web UI fails (showing Status: The Admin Console application is loaded. for an infinite time)

## Steps to reproduce

1. start with a unmodified "payaradomain"
2. start the DAS using "asadmin start-domain"
3. change the admin port e.g.:
 asadmin set configs.config.server-config.network-config.network-listeners.network-listener.admin-listener.port=12345
4. Try to restart domain using "asadmin restart-domain"

## Context

I am trying to configure a payara domain semi-automatically using the recorded asadmin commands of the asadmin recorder.

## Environment ##

- **Payara Version**: 4.1.2.181 (Payara 5 Beta 2 seems to be affected too)
- **Edition**: Full
- **JDK Version**: Oracle Java SE 8u161
- **Operating System**: Linux

**Comment by smillidge** [comment]
Created internal issue PAYARA-2580

**Comment by smillidge** [comment]
Fixed by #2722
