### ISSUE TITLE
Payara_PatchedProjects missing

### ISSUE THREAD

**Issue by aojava** [payara/Payara#240]
Hi!

It looks like someone has the repository deleted. So I can't build Payara (neither V4.1.151 nor V4.1.152-SNAPSHOT) anymore.

**Comment by davewinters** [comment]
This has been removed but will restore since there were many patched versions which are no longer used in Payara. Apologies.

**Comment by smillidge** [comment]
It's back

**Comment by aojava** [comment]
thanks
