### ISSUE TITLE
Checksums and digital signatures should be provided for releases

### ISSUE THREAD

**Issue by haqer1** [payara/Payara#2414]
## Expected Outcome
It should be possible to verify the downloads' (SHA1) checksum, & ideally also a (GPG) digital signature.

## Current Outcome
These seem to not be provided anywhere.

**Comment by phillipross** [comment]
technically, these are provided via maven central:
https://repo1.maven.org/maven2/fish/payara/distributions/payara/5.184/

**Comment by rdebusscher** [comment]
As indicated, checksums are available within Maven Central repo.

**Comment by haqer1** [comment]
The point of this bug report was avoiding a) networking issues/quirks & b) ensuring security of downloads.
IMHO, the current process is far from giving one a warm and fuzzy sentiment about these aspects.

A) Even though checksums are on maven i believe checksums (preferably with signatures) should be listed on the provider's site (e.g., something i'm personally used to: http://commons.apache.org/proper/commons-lang/download_lang.cgi). 
B) Maven artifacts are signed, but i think at the very list the public keys should be downloadable/listed on your website. And, especially if download from your site is not identical to what's on maven, its checksum (preferably with signature) should be listed as well.

It's not hard to add this stuff, & would make reassure security-conscious folks. Hopefully, you'll re-consider this.

P.S.
1) For my payara 4.1.2.181 download from a couple of years ago (for some reason no longer listed on your site):
$ gpg --verify payara-4.1.2.181.zip.from_maven.org.asc payara-4.1.2.181.zip
gpg: Signature made Sal 06 Fev 2018 20:23:37 +06
gpg:                using RSA key 18648801E6367A19
gpg: Can't check signature: No public key

$ gpg --keyserver pgp.mit.edu --recv-key 18648801E6367A19
gpg: key 18648801E6367A19: public key "Andrew Pielage (Payara GPG Key) <andrew.pielage@payara.fish>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify payara-4.1.2.181.zip.from_maven.org.asc payara-4.1.2.181.zip
gpg: Signature made Sal 06 Fev 2018 20:23:37 +06
gpg:                using RSA key 18648801E6367A19
gpg: Good signature from "Andrew Pielage (Payara GPG Key) <andrew.pielage@payara.fish>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 21BC F564 DEFE 9A95 3A47  0008 1864 8801 E636 7A19

1.a) But the download on your site was .tar.bz2, whereas on maven.org it was a .zip
1.b) There's no info about the key if one searches the Internet.

2) For v5:
$ gpg --verify payara-5.2021.2.zip.from_maven.org.asc payara-5.2021.2.zip
gpg: Signature made Caq 01 Apr 2021 15:07:55 +06
gpg:                using RSA key B158F9887A99E404BD3163434253E9F0B0556B98
gpg: Can't check signature: No public key

$ for keyserver in pgp.mit.edu pgp.key-server.io keys.gnupg.net keyserver.pgp.com keyserver.ubuntu.com; do echo $keyserver && gpg --keyserver $keyserver --recv-key B158F9887A99E404BD3163434253E9F0B0556B98; done
pgp.mit.edu
gpg: keyserver receive failed: No data
pgp.key-server.io
gpg: keyserver receive failed: No data
keys.gnupg.net
gpg: keyserver receive failed: No data
keyserver.pgp.com
gpg: keyserver receive failed: Connection timed out
keyserver.ubuntu.com
gpg: key 4253E9F0B0556B98: public key "Payara CI <payara-ci@payara.fish>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify payara-5.2021.2.zip.from_maven.org.asc payara-5.2021.2.zip
gpg: Signature made Caq 01 Apr 2021 15:07:55 +06
gpg:                using RSA key B158F9887A99E404BD3163434253E9F0B0556B98
gpg: Good signature from "Payara CI <payara-ci@payara.fish>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B158 F988 7A99 E404 BD31  6343 4253 E9F0 B055 6B98

2.a) The only mention of this key on the Internet is, which apparently is not related to Payara directly/officially:
https://github.com/pzlc/brandon
