### ISSUE TITLE
GlassFish HASSOFactory hardcoded replicated

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#242]
The GlassFish HASSOFactory is hardcoded to use replicated as its persistence type this needs to become configurable so that hazelcast can be specified.

https://github.com/payara/Payara/blob/master/appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASSOFactory.java

**Comment by smillidge** [comment]
https://github.com/payara/Payara/blob/master/nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/VirtualServer.java

Needs extending to add persistence type as a configurable attribute

**Comment by dmatej** [comment]
Yes, and the SSO replication is not nice code at all ... methods with many parameters, bugs, weird processing, no javadoc. I think it needs some refactoring and cleanup (and tests).
Currently I noticed some bug occuring in my Payara version with my cleaned Shoal snapshot (old released version is incompatible with the new Grizzly), I will try to find the cause and fix it this week (users cannot logout from clustered SSO session).

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-1060`

**Comment by lprimak** [comment]
You can use 
```
 @Inject
 private ServerConfigLookup serverConfigLookup;
 serverConfigLookup.getPersistenceTypeFromConfig();
```

to get the configure persistence type
