### ISSUE TITLE
Possibly duplicated jar inside payara-micro: jackson-module-jaxb-annotations-MAYOR.MINOR.PATCH.jar

### ISSUE THREAD

**Issue by Diego1977** [payara/Payara#2427]
# Description #
----------
I've found a possibly duplicated file inside payara-micro-4.1.2.172.jar and payara-micro-4.1.2.181.jar:
Both have 
jackson-module-jaxb-annotations.jar and 
jackson-module-jaxb-annotations-2.8.5.jar (or jackson-module-jaxb-annotations-2.9.4.jar in 181)

in directory MICRO-INF/runtime

- **Payara Version**: payara-micro-4.1.2.172 and 4.1.2.181
- **Edition**: Micro 
- **JDK Version**: 8 Oracle
- **Operating System**: Linux

**Comment by smillidge** [comment]
Good catch thanks.

**Comment by smillidge** [comment]
Fixed by #2434
