### ISSUE TITLE
Payara BOMs for downloads

### ISSUE THREAD

**Issue by mwnorman** [payara/Payara#243]
On the payara.co.uk/downloads website, that are various 'footprint' packages (too big, too small, just right!) for Payara
 - full
 - web profile
 - minimal
 - embedded

I mentioned this in a twitter exchange with @Payara_Fish and was told to raise it on Github - so ..o

There should be maven BOMs for these packages

**Comment by smillidge** [comment]
We don't currently have a maven bom  for any of the packages. All of the packages are self contained so what would you like to see in a bom? 
For example it could be a list of all the dependencies provided by the download with "provided" set?

**Comment by mwnorman** [comment]
Similar to (for example) the Jersey BOMs, specifies dependencies as well as core modules - enable very 'lightweight' Maven project - specify a single dependency and start writing the main() method ...

**Comment by smillidge** [comment]
OK. In the case of embedded everything is packaged in the single jar so you only need to specify that jar in your dependencies.

For full server versions (full, web profile) you should only need to use JavaEE 7 apis ;-)

**Comment by smillidge** [comment]
For development is http://repo2.maven.org/maven2/javax/javaee-api/7.0/javaee-api-7.0.pom enough? For core JavaEE development you shouldn't need much more than this.

**Comment by smillidge** [comment]
Embedded and Micro artefacts are now on Maven as they are self contained there is no BOM

**Comment by mwnorman** [comment]
Yeah!

**Comment by smillidge** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cfish.payara

**Comment by MarkWareham** [comment]
Payara has a BOM as of 5.194: https://docs.payara.fish/documentation/ecosystem/maven-bom.html
