### ISSUE TITLE
Connection Leak leads the login to be unavailable

### ISSUE THREAD

**Issue by aweinitschke** [payara/Payara#2440]
# Description #
----------
A long running database procedure is causing a connection leak, which cannot be reclaimed.

## Expected Outcome

Other Users were expected to be able to login.

## Current Outcome

[2018-02-21T13:54:16.165+0100] [Payara 4.1] [INFO] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.pool] [tid: _ThreadID=203 _ThreadName=connector-timer-proxy] [timeMillis: 1519217656165] [levelValue: 800] [[
Reclaiming the leaked connection of pool [ myPool ] and destroying it so as to avoid both the application that leaked the connection and any other request that can potentially acquire the same connection from the pool end up using the connection at the same time]]

## Steps to reproduce (Only for bug reports) 

1 -**Build a Query (in my case in Oracle) which is running longer then the time set up in "Connection Leak Timeout" and enable the reclaim.

2 -** Run the Query and the described outcome will occure when reclaming the connection and no other users are able to login or act in any way with the connection pool.

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: Full
- **JDK Version**: 8 u144 
- **Operating System**:  Windows / Linux
- **Database**: Oracle XE 11c / Oracle Standard 12c Standard Edition 2

**Comment by lprimak** [comment]
Interesting... Does closing the connection manually fix the problem?
The "leak connection" is the last back-stop in the process, as the application is supposed to close connections themselves

**Comment by OndrejM** [comment]
@aweinitschke does it help if you switch the connection leak reclaim off? This is a feature intended to be used mostly in development. In production, you would be safer to just set connection leak timeout to get warning messages but turn the reclaim off to avoid any unwanted side-effects.

**Comment by aweinitschke** [comment]
Thanks for your replies. 
To fix the problem, we have currently turned off the reclaim. 
Since the Application was supposed not to close the connection during the process, we have not tried to close it manually.
But if there are no advantages in live-system for reclaiming a leak detected connection because it is an development setting, we will leave it turned off.
