### ISSUE TITLE
Docker  Payara Server  4.1.2.181 vs CentOS 7.4: -postbootcommandfile commands can't copy domain.xml to domain.xml.bak

### ISSUE THREAD

**Issue by webelcomau** [payara/Payara#2447]
# Description #
----------
Payara Server  4.1.2.181 vs CentOS 7.4

asadmin commands encapsulated in a file for -postbootcommandfile need (sometimes) to be able to copy ../domain1/domain.xml to ../domain1/domain.xml.bak but can't, gives 'Could not rename' error.

Following works brilliantly (and indeed on Mac OS X) for setting JVM parameters required by deployed WAR, and running context etc, but setting JVM param seems to need to change domain.xml, which triggers a backup to domain.xml.bak:

```
FROM payara/server-full
...
COPY Test.war $DEPLOY_DIR

COPY mycommands.asadmin .
USER root
RUN chown payara:payara mycommands.asadmin
USER payara

ENTRYPOINT ${PAYARA_PATH}/generate_deploy_commands.sh && cat ${DEPLOY_COMMANDS} >> mycommands.asadmin && ${PAYARA_PATH}/bin/asadmin start-domain -v --postboo
tcommandfile mycommands.asadmin ${PAYARA_DOMAIN}

```

Where mycommands.asadmin contains, for example (use with an ObjectDB JVM var setting):

```
create-jvm-options '-Dobjectdb.home=/usr/local/objectdb/external'
deploy --contextroot test /opt/payara41/deployments/Test.war
set-web-context-param --name=javax.faces.PROJECT_STAGE --value=Production Test

```

## Expected Outcome

No warnings or errors.

## Current Outcome

Non-blocking warnings/error reports (but web app still runs):

```
IOException while saving the configuration, changes not persisted
java.io.IOException: Could not rename /opt/payara41/glassfish/domains/domain1/config/domain.xml to /opt/payara41/glassfish/domains/domain1/config/domain.xml.bak
	at com.sun.enterprise.v3.server.DomainXmlPersistence.save(DomainXmlPersistence.java:204)

```

Variations on the following brute force (and probably highly insecure) permissions changing in the Dockerfile did not help:

```
USER root
..
RUN chmod a+rwX -R /opt/payara41/glassfish/domains/domain1/config
USER payara

```

## Steps to reproduce (Only for bug reports) 

_A reproducer app may be provided soon._

Related (but not exactly the same) issues include:

- https://github.com/payara/Payara/issues/1307
- https://github.com/payara/Payara/issues/1671
- https://github.com/payara/Payara-Examples/issues/27

And related/relevant external links:

- https://wwija.com/computer-internet-technology/1785050_canand-39-t-overwrite-file-in-docker-compose.html

- https://wwija.com/computer-internet-technology/1785050_canand-39-t-overwrite-file-in-docker-compose.html

None of the solutions provided there seem to apply directly or require major reworking of a postbootcommandfile approach that otherwise works well. I assert that the ability to change a JVM option via asadmin command in  a postbootcommandfile should be supported directly.

## Environment ##

- **Payara Version**: Payara Server  4.1.2.181 (as Docker image)
- **Edition**:  server full
- **JDK Version**:  openjdk version "1.8.0_161"
- **Operating System**: Centos 7.4
- **Database**: n/a ObjectDB

**Comment by smillidge** [comment]
@mikecroft can your team take a look. Many commands will need to update the domain.xml.

**Comment by smillidge** [comment]
Closing as old and on the wrong repo
