### ISSUE TITLE
Payara Micro is missing a keyfile

### ISSUE THREAD

**Issue by hindsholm** [payara/Payara#2466]
# Description #

It should be possible to use asadmin commands _create-file-user_, _list-file-users_ etc in a postbootcommandfile e.g. to create some users in the file realm. This fails however because there is no keyfile in MICRO-INF/domain.

## Expected Outcome

The server should start up without errors.

## Current Outcome

The server gives an error message:
`[2018-02-26T12:43:17.864+0000] [] [WARNING] [] [fish.payara.micro.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519648997864] [levelValue: 900] Boot Command list-file-users failed PlainTextActionReporterFAILUREThe specified physical file /tmp/payaramicro-rt4565975793201558163tmp/config/keyfile associated with the file realm file does not exist.`

## Steps to reproduce

1. Create a post-boot.txt file containing:
`list-file-users`

2. Run 
`java -jar payara-micro-4.1.2.181.jar --postbootcommandfile ./post-boot.txt`

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**: Linux
- **Database**: N/A

**Comment by arjantijms** [comment]
If you deploy an application at the same time, and use post deploy, it should work. E.g.

```
java -jar payara-micro-4.1.2.181.jar --deploy some.war --postdeploycommandfile ./post-boot.txt
```

**Comment by hindsholm** [comment]
That's strange, because I have tried it, and deployment doesn't change anything in my case. But if I add an empty keyfile to the payara micro jar, everything works as expected.

**Comment by arjantijms** [comment]
Good to hear that it works! :)

We'll be looking at the option for an empty key file. Just curious though, if you don't deploy a .war to Payara Micro, what do you use the instance for?

**Comment by hindsholm** [comment]
I do deploy a .war, but I just wanted to create a few users before the .war is deployed. My integration test will kick in as soon as the app is ready, and it needs the users to be in place.
Right now I do the following in my Dockerfile as a workaround:
```
FROM payara/micro
# keyfile is missing from payara/micro
RUN mkdir -p /tmp/MICRO-INF/domain &&\
    touch /tmp/MICRO-INF/domain/keyfile &&\
    jar uf /opt/payara/payara-micro.jar -C /tmp MICRO-INF/domain/keyfile
...
```
This just inserts an empty keyfile in payara-micro.jar and then the --postbootcommandfile option works.

**Comment by smillidge** [comment]
Created PAYARA-2579 to add the file
