### ISSUE TITLE
RememberMeAnnotationLiteral issue in javaee/security-soteria

### ISSUE THREAD

**Issue by sgomanf** [payara/Payara#2479]
When I use the RememberMe annotation, and specifying an EL in the isRememeberMeExpresion property, the expression is invoked twice from the RememberMeAnnotationLiteral class (from javaee / security-soteria) lines 117 and 118. The first call expects a boolean return value and the second a String, generating the latter an exception java.lang.ClassCastException: java.lang.Boolean can not be cast to java.lang.String.
I know it's not a Payara problem but I do not know where to report it.

## Environment ##

- **Payara Version**:5.Beta2
- **Edition**:  Full
- **JDK Version**: 8u162 - Oracle
- **Operating System**: Windows 7

**Comment by arjantijms** [comment]
Thanks for the report. Pending the transfer of Soteria it's perhaps indeed a bit unclear where to report issues regarding Soteria. Sorry for that. But you can certainly report them here.

I wonder, which variation of the EL expression did you use? The `#` or `$` variant? As I did add a test for RememberMe which uses EL. See here:

https://github.com/javaee/security-soteria/blob/master/test/app-custom-rememberme/src/main/java/org/glassfish/soteria/test/TestAuthenticationMechanism.java#L64

If you could tell me what's different there from your situation, that would be a great help.

A reproducer is always welcome too, of course.

**Comment by sgomanf** [comment]
arjantijms, thanks for the replay.
The code I used to test is this link:

https://github.com/payara/Payara-Examples/tree/master/Java-EE/security-jwt-example/src/main/java/fish/payara/examples/security

The original code had the EL in raw format, which prevents that expression from being invoked. I tried using the  '${self.isRememberMe(httpMessageContext)}' variant.

**Comment by sgomanf** [comment]
When I use deferred expressions (# {}) it does not throw the exception.

**Comment by rdebusscher** [comment]
Since the test code uses # {} which does work (confirmed by reporter) This is not an immediate problem and should be handled at the Jakarta EE Soteria repo (https://github.com/eclipse-ee4j/soteria)
