### ISSUE TITLE
Start and stop pages use old template on Payara 5 admin console

### ISSUE THREAD

**Issue by ggam** [payara/Payara#2516]
Stopping or restarting the server from the admin console redirects you to the following pages, which use the old template (Payara 5):

![captura de pantalla de 2018-03-10 15-50-03](https://user-images.githubusercontent.com/2109040/37243527-1f282848-247b-11e8-92f9-ac62766dbb56.png)
![captura de pantalla de 2018-03-10 15-52-10](https://user-images.githubusercontent.com/2109040/37243528-1f4665ec-247b-11e8-9384-78d2a3d414c0.png)

Also note there's a strange button on the upper left corner that I guess should be hidden.

fixed by #2524

**Comment by smillidge** [comment]
Thanks for the bug report. 
Internal issue PAYARA-2591 created.

**Comment by smillidge** [comment]
Fixed by #2524
