### ISSUE TITLE
"payara.instance.https.port" not working in payara-micro-4.1.2.174 with microprofile-config-api.version 1.2.1

### ISSUE THREAD

**Issue by platzerg** [payara/Payara#2521]
Currently I use payara-micro-4.1.2.174 and microprofile-config-api.version 1.2.1 and injected follow:

but always get the http Port and not the https port.

"@Inject @ConfigProperty(name="payara.instance.https.port") int httpsPort;"

i always getting the http port and not the https port.

**Comment by smillidge** [comment]
Looks like a simple bug https://github.com/payara/Payara/blob/master/nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PayaraServerProperties.java#L87

**Comment by platzerg** [comment]
is there some quick fix to resolve this bug?

**Comment by smillidge** [comment]
Patch the source?

Alternatively set the ssl port by setting the system property `payaramicro.sslPort` rather than using  `--sslport` and then inject that system property instead.

```java
@Inject
@ConfigProperty(name="payaramicro.sslPort")
int httpsPort;
```

**Comment by smillidge** [comment]
Internal issue number PAYARA-2590
