### ISSUE TITLE
backend not accessable / asdmin-time-outs afte updating from 4.1.2.174 to 4.1.2.181

### ISSUE THREAD

**Issue by md-mg** [payara/Payara#2527]
# Description #
----------

after updating payarafish the web-backend behind 127.0.0.1:4848 isn't accessable any more after some time (~ 1h) under production-load.
Then also asadmin-commands time out (stop-domain, deploy, undeply) - payarafish can be only shut-down via a kill on the linux-konsole then.
On our test-environment we noticed this also after "some days".

Sometimes even the login-screen of the backend doesn't appear.

Directly after a start-domain everything is fine.

Our deployed applications are not affected.

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
- **Operating System**: CentOS6, CentOS7

**Comment by smillidge** [comment]
Can you provide some information there is nothing to go on here. What is stopping your server from responding, memory? stuck threads? eating CPU? Deadlocks etc.?

**Comment by md-mg** [comment]
I try to get some information - at the moment I rolled back our production-cluster but set up some test-systems.
At the moment everything is working fine - maybe it was a side-effect of the broken logging via the upgrade-process (#2400) - internal overflow of what-ever or so...

**Comment by md-mg** [comment]
I can't reproduce the issue any more.

-> May be closed.
