### ISSUE TITLE
Customizable JAX-RS authentication and authorization responses

### ISSUE THREAD

**Issue by tofflos** [payara/Payara#2542]
# Description #
----------

If you perform an unauthenticated or unauthorized request to a JAX-RS endpoint with a RolesAllowed annotation then Payara will respond with a standardized HTML response.

## Expected Outcome

I would like to be able to alter that behavior so that Payara responds like this:

```
{
  "status": 401,
  "message": "This request requires HTTP authentication."
} 
```

## Current Outcome

The current response is this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara Micro #badassfish - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - Unauthorized</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Unauthorized</p><p><b>description</b>This request requires HTTP authentication.</p><hr/><h3>Payara Micro #badassfish</h3></body></html>
```

## Steps to reproduce (Only for bug reports) 

1 -**  Create a JAX-RS Application that contains a BasicAuthenticationMechanismDefinition annotation and JAX-RS Resource that contains a RolesAllowed Annotation:

```
@BasicAuthenticationMechanismDefinition(realmName = "My realm")

@ApplicationPath("/api/v1")
public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        Map<String, Object> map = new HashMap();

        return map;
    }
}
```

```
@Path("/items")
@RequestScoped
@Transactional(Transactional.TxType.REQUIRED)
public class ItemResource {

    private static final List<Item> ITEMS = Arrays.asList(new Item(1L, "Item 1"), new Item(2L, "Item 2"));

    public ItemResource() {
        // Required by RESTEasy
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed("Administrator")
    public Response doGet() {
        return Response.ok(ITEMS).build();
    }
}
```

2 -**  Deploy the project in Payara Micro:

`java -jar .\payara-micro-5.181.jar --deploy .\target\mavenproject73-1.0-SNAPSHOT.war`

3 -**  Request all the items from the items resource but leave out the authentication details:

```
$ http http://localhost:8080/mavenproject73-1.0-SNAPSHOT/api/v1/items
HTTP/1.1 401 Unauthorized
Content-Language:
Content-Length: 1054
Content-Type: text/html
Server: Payara Micro #badassfish
WWW-Authenticate: Basic realm="My realm"
X-Frame-Options: SAMEORIGIN

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara Micro #badassfish - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - Unauthorized</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Unauthorized</p><p><b>description</b>This request requires HTTP authentication.</p><hr/><h3>Payara Micro #badassfish</h3></body></html>
```

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Micro
- **JDK Version**:8 u161 - Oracle/OpenJDK
- **Operating System**: Windows

**Comment by ggam** [comment]
As a workaround, does it work if you define the error page for 401 on
web.xml?

**Comment by tofflos** [comment]
Minimal project that reproduces the behavior:
[mavenproject73.zip](https://github.com/payara/Payara/files/1822485/mavenproject73.zip)

Note that project also contains  a non-working attempt to override the built-in behavior by adding a customized ExceptionMapper:

```
@Provider
public class NotAuthorizedExceptionMapper implements ExceptionMapper<NotAuthorizedException> {

    @Override
    public Response toResponse(NotAuthorizedException ex) {
        return Response.status(401)
                .type(MediaType.APPLICATION_JSON)
                .entity(new ErrorMessage(401, "This request requires HTTP authentication."))
                .build();
    }
}
```

**Comment by tofflos** [comment]
Thank you! The error page trick worked surprisingly well!

**Comment by tofflos** [comment]
Minimal project that contains the working workaround suggested by @ggam:
[mavenproject73-with-custom-error-pages-in-webxml.zip](https://github.com/payara/Payara/files/1822536/mavenproject73-with-custom-error-pages-in-webxml.zip)

Hopefully it'll be useful to someone. ;-)

**Comment by smillidge** [comment]
The error page is the correct way of doing it. I'm not sure if JAX-RS specifies a different way of handling error pages.

**Comment by ggam** [comment]
Interesting. JAX-RS doesn't need to be run on a Servlet container (although
all actually do it).

Perhaps it's an issue to report to JAX-RS to capture NotAuthorizedException
on ExceptionMappers?

**Comment by tofflos** [comment]
I do believe JAX-RS allows you to catch a NotAuthorizedException using an ExceptionMapper provided that you throw the exception from within a JAX-RS resource. But in this case something is responding before the request gets that far. In other words this strikes me as an integration issue between Jersey and Payara.

I think the provided solution is good because it solves the most important problem of returning a structured response that is parseable for API consumers. On the other hand it feels like a workaround because it's a big departure from the JAX-RS programming model and one additional hump that developers have to get over. So while I'm good if the issue gets closed I think an enhancement here would make things easier for future developers.

**Comment by cghislai** [comment]
Would be great to be able to use the jax-rs exception mappers for all exceptions - like when the parsing of the authorization header fails with an ArrayIndexOutOfBoundsException

**Comment by rdebusscher** [comment]
Closed as using error page solved the requirement.
