### ISSUE TITLE
payara upgrade from 4.174 to 4.181 fails with domains in external folder

### ISSUE THREAD

**Issue by vikramalvaj** [payara/Payara#2571]
# Description #
----------

We have configured the domains external to the payara server to enable easy upgrade to new streams of payara server

Upgrade from 4.171 to 4.172/173/174 works

However upgrade to 4.181 fails with timeout error of 600 seconds. 

The verbose option on asadmin start command displays the logs with application deployment pinned at  **eclipselink Weaved fetch groups (FetchGroupTracker) on an entity class**

## Expected Outcome

Already deployed application should continue deployment on an upgraded server

## Current Outcome

The verbose option on asadmin start command displays the logs with application deployment pinned at  **eclipselink Weaved fetch groups (FetchGroupTracker) on an entity class**

org.eclipse.persistence.default|_ThreadID=24;_ThreadName=RunLevelControllerThread-1522131275762;_TimeMillis=1522131361176;_LevelValue=300;|
  Weaved fetch groups (FetchGroupTracker) [com/EntityClass].|#]

## Steps to reproduce (Only for bug reports) 

./asadmin start-domain --verbose --domaindir domainDir domainName

## Environment ##

JDK8
payara4.174 to payara4.181

**Comment by OndrejM** [comment]
Are you sure that's the last log message? There should be another log message "End weaver class transformer processing class" right after this one, with nothing to delay it.

**Comment by smillidge** [comment]
There's no real information on this issue I will close it. If you have problems in the future on the latest release please create a new issue.
