### ISSUE TITLE
@Remote bean can't be accessed from a different app, when using Payara5

### ISSUE THREAD

**Issue by Scoty** [payara/Payara#2581]
# Description #
----------

With the latest version of Payara 4 I am able to deploy the following two apps:

1. App1 has the following code(the below interface has single implementation):
```
import javax.ejb.Remote;

@Remote
public interface EmailNotificationManagerRemote {

	public void sendMail(String[] recipientsTo, String[] recipientsCC, String[] recipientsBCC, String subject,
            String body, String senderName, String senderMail, String mimeType, String mailSession, Boolean isSMS)
            throws InvalidInputException;
	
	 public void sendSupportMail(String errorCode, String subject, String body, String logLevel)  throws InvalidInputException;
}
```

App2 has the following code:

```
@EJB(mappedName="EmailNotificationManager")
private EmailNotificationManagerRemote emailNotificationManagerRemote;
```

When deploying App2(after App1 has already been successfully deployed), I get the following exception:

```
Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/com.***.KeyLicenseNotifierBean/emailNotificationManagerRemote], Lookup: [EmailNotificationManager#com.***.EmailNotificationManagerRemote], Type: [Session]
...
Caused by: javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is java.lang.RuntimeException: Cant copy Serializable object:]
...
Caused by: java.lang.RuntimeException: Cant copy Serializable object:
...
Caused by: java.lang.IllegalArgumentException: Illegal null argument to ObjectInputStreamWithLoader
```

## Expected Outcome

If App1 is successfully deployed, App2 should be deployed without exceptions.

## Current Outcome

App2 deployment fails.

## Steps to reproduce (Only for bug reports) 

Create two wars/jars one with a @Remote EJB definition and one which uses this remote bean. Check that when deploying the app, which uses the bean, the bean can't be found...

## Context (Optional)

The same two wars are deployable and are working on Payara4.

## Environment ##

- **Payara Version**: 5
- **Edition**:  Full
- **JDK Version**:  1.8.0_151
- **Operating System**:  Windows 10.0.15063 Build 15063

**Comment by smillidge** [comment]
Have you got the full stack traces?

**Comment by Scoty** [comment]
Sorry, those log files are deleted. Since I am out of the office till Monday, I won't be able to provide them before 02/04/2018

**Comment by smillidge** [comment]
Can you create a simple test case project we can use to reproduce the behaviour?

**Comment by aruille31** [comment]
I have the same issue with Payara5. 
No pb with Payara 4, Glassfish 4 and GlassFish 5

**Comment by smillidge** [comment]
Can you provide a test case?

**Comment by aruille31** [comment]
Yes i will try asap, maybe tomorrow

Le lun. 9 avr. 2018 à 19:31, Steve Millidge <notifications@github.com> a
écrit :

**Comment by aruille31** [comment]
A simple test case (Hello World) :
test-ejb : ejb stateless (local and remote)
test-ejb-api : interfaces for ejb
test-ejb-war : war container
test-web : ws rest to use HelloWorld ejb in "remote mode"

Regards,

[test-ejb-remote.zip](https://github.com/payara/Payara/files/1893465/test-ejb-remote.zip)

**Comment by aruille31** [comment]
Hi,

did you reproduce the bug with me test case ?

Regards,

Antoine

**Comment by smillidge** [comment]
We haven't had time to review yet.

**Comment by aruille31** [comment]
I investigate on my side, and for me the pb comes from the fact the contextClassLoader of a DefaultWorkerThread is not correctly initialized or injected (with com.sun.enterprise.util.Utility.setContextClassLoader) after loading ejb remote classe.

stacktrace :

Caused by: java.lang.IllegalArgumentException: Illegal null argument to ObjectInputStreamWithLoader
	at org.glassfish.common.util.ObjectInputStreamWithLoader.<init>(ObjectInputStreamWithLoader.java:69)
	at org.glassfish.common.util.OSGiObjectInputOutputStreamFactoryImpl$OSGiObjectInputStream.<init>(OSGiObjectInputOutputStreamFactoryImpl.java:150)
	at org.glassfish.common.util.OSGiObjectInputOutputStreamFactoryImpl.createObjectInputStream(OSGiObjectInputOutputStreamFactoryImpl.java:136)
	at com.sun.enterprise.naming.util.NamingUtilsImpl.makeCopyOfObject(NamingUtilsImpl.java:130)
	... 47 more


Regards,

**Comment by lprimak** [comment]
I was able to reproduce this.  I don't think it's the same as #2604 however this is some other regression I do believe

**Comment by lprimak** [comment]
create internal issue ```PAYARA-2691```
