### ISSUE TITLE
Payara Micro needs Hazelcast JBatch Job Store

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#260]
Payara Micro should by default store all JBatch data into the Hazelcast Cluster as its job store. With a configuration option to use a specified datasource.

This will remove the need to use the in-built Derby DB for storing JBatch persistent information.

**Comment by realityforge** [comment]
Could the same approach be taken with Timers?

**Comment by smillidge** [comment]
Could do, great idea.

**Comment by smillidge** [comment]
#265 created for the Hazelcast EJBTimer store idea

**Comment by mikecroft** [comment]
Internal issue `PAYARA-187`

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.

**Comment by OndroMih** [comment]
I'm closing this as it's a very old issue and we now plan new features in a different way.
