### ISSUE TITLE
JPA datasource example not working with 5.182-SNAPSHOT micro/full

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#2612]
# Description #
----------

Can't get the JPA datasource example to work with Payara 5 micro (current master)

https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/jpa-datasource-example

The datasource doesn't seem to be registered with JNDI or the resource validation fails.

## Expected Outcome

PersistenceContext can be injected into @Stateless bean.

## Current Outcome

Depending on the JNDI name used the datasource is determined to be invalid on startup or the JNDI resource can't be looked up on first usage.

## Steps to reproduce (Only for bug reports) 

Deploy example.

- **Payara Version**: 5.182-SNAPSHOT (current master)
- **Edition**: Full/Micro
- **JDK Version**: Oracle 1.8_161
- **Operating System**: Mac
- **Database**: external H2

**Comment by smillidge** [comment]
Is this a regression in current master or does this fail in released 5.181?

**Comment by svendiedrichsen** [comment]
No, it works in 5.181. Must have been my fault. I'm currently working on #165  and must have made a mistake. I can't see any errors in the log though. Sorry.

**Comment by smillidge** [comment]
Working on #165 now that will be cool
