### ISSUE TITLE
Payara 5.181 Servlet Parameters (ServerName, ServerPort, ...) broken when HTTP 2 is used

### ISSUE THREAD

**Issue by sfeigl** [payara/Payara#2614]
Payara 5.181 Servlet Parameters (ServerName, ServerPort, ...) broken when HTTP 2 is used

----------

When using getRequestURL() of HttpServletRequest for a HTTP/2 request, the host name is not filled correctly. It looks like the "Host" header is not parsed, so the system host name is used.

I found a Glassfish bug for exact the same problem:

https://github.com/javaee/glassfish/issues/22390

## Expected Outcome

Using  getRequestURL() I expect to get the URL, that was used for the request by the browser.

If the browser requests "https://192.168.1.150:8181", i expect "https://192.168.1.150:8181"

## Current Outcome

It seems like the Host header is not used when HTTP/2 is used. For "https://192.168.1.150:8181" I get "https://nameoflocalhost:8181"

Using HTTP/1.1, the URL is filled correctly. (either by using a browser with HTTP/2 disabled or disabling HTTP/2 support in the listener)

## Steps to reproduce

1 -**  Start the domain
2 -**  Configure an HTTPS network listener with HTTP/2.0 enabled (standard http-listener-2 should do)
3 -**  Deploy an application which calls getRequestURL() or similar
4 -**  Make a HTTP/2 request containing the IP address (or a host name not matching the host name of the server)
5 -**  Check  getRequestURL() of the request

### Samples

You might be able to use the sample webapp of the Glassfish bug

https://github.com/gessnerfl/glassfish-servlet-test

## Context

The application needs to create absolute URIs which are using the same host as the browser requested.

## Environment ##

- **Payara Version**:  5.181
- **Edition**: Full
- **JDK Version**: Oracle 8u162
- **Operating System**: Debian Linux 8.10
- **Database**: None

**Comment by smillidge** [comment]
This should be fixed by PR https://github.com/payara/Payara/pull/2561 which patches Grizzly. This therefore should be fixed in prerelease builds.

**Comment by smillidge** [comment]
For reference https://github.com/payara/patched-src-grizzly/pull/4
 https://github.com/eclipse-ee4j/grizzly/pull/2002
