### ISSUE TITLE
@EJB or @Inject do not work with @Webservice

### ISSUE THREAD

**Issue by eduarddrenth** [payara/Payara#2615]
# Description #
----------

EJB not injected using either EJB or CDI in combination with Webservice annotation.
Injection in REST class succeeds.

Here @EJB fails: https://bitbucket.org/fryske-akademy/superlemma-list/src/148c77ce88474919ad44af90473b7e9b25df8dce/superlemma-list-ws/src/main/java/org/fa/superlemmalist/ws/SuperlemmaServiceImpl.java?at=master

Here it succeeds:  https://bitbucket.org/fryske-akademy/superlemma-list/src/148c77ce88474919ad44af90473b7e9b25df8dce/superlemma-list-ws/src/main/java/org/fa/superlemmalist/rest/SuperlemmaRestService.java?at=master

## Expected Outcome

EJB injected

## Current Outcome

nullpointerexception

## Steps to reproduce (Only for bug reports) 

install the app and call one of the wsdl methods
app needs a database though, if desired can provide, but I expect this to be a known issue

### Samples

I have to use this as workaround: https://bitbucket.org/fryske-akademy/crudapi/src/68e336078006543336bd9e4f43ed66027c9f261b/ejbCrudApi/src/main/java/org/fryske_akademy/ejb/EJBHelper.java?at=master

## Environment ##

- **Payara Version**: 5.181
- **Edition**: full
- **JDK Version**: openjdk version "1.8.0_162"
- **Operating System**: Linux eduard-X756UB 4.4.0-119-generic
- **Database**: MySQL

**Comment by lprimak** [comment]
Can you try 
@Stateless @WebService and see if the problem is resolved?

I am not sure if the injection mechanism is even supposed to work otherwise

**Comment by eduarddrenth** [comment]
I'll try

**Comment by eduarddrenth** [comment]
no, that does not help

**Comment by eduarddrenth** [comment]
maybe something similar to https://stackoverflow.com/questions/11579706/how-to-inject-ejb-in-java-web-service-soap?

**Comment by lprimak** [comment]
Can you create a simple self-contained reproducer?  I have a hard time believing this because it’s basic functionality. Something else must be going on

**Comment by eduarddrenth** [comment]
That's what I've thinking as well, this should just work... I'll work out a
reproducer

**Comment by lprimak** [comment]
Thank you!

**Comment by lprimak** [comment]
I would remove all sun-* stuff and non-standard configurations in web.xml and glassfish-web.xml
Many times the articles on the web refer to old and no-longer-applicable situations from years and years ago.

If you remove all the "old stuff" and it still doesn't work, and you can't figure it out, you can try posting the stack trace here, as there is definitely not enough information here to take any action, even to confirm that there is any problem at all on Payara side

**Comment by eduarddrenth** [comment]
Yeah, I'll try that first. Thanks for thinking along

**Comment by eduarddrenth** [comment]
working...

**Comment by lprimak** [comment]
That's good news
