### ISSUE TITLE
Make the monitoring REST API compatible with Jolokia

### ISSUE THREAD

**Issue by kvalev** [payara/Payara#2617]
# Description #
----------

While the current payara version exposes monitoring statistics similarly to Jolokia, the REST access is structured differently, which makes it impossible to use already existing open source monitoring tools out of the box (e.g. metricbeat).

## Expected Outcome

Jolokia works by sending a POST request with the body describing what data should be retrieved, e.g:
```
[{"type":"read","mbean":"java.lang:type=Memory"}]
```

## Current Outcome

When sending the same POST request to the monitoring REST API it either returns a 405 (when querying the `rest-monitoring/rest/` endpoint) or 404 (when querying the `rest-monitoring/rest/read/`). Instead the current implementation expects a GET request describing the data to be collected, e.g. `rest-monitoring/rest/read/java.lang:type=Memory`

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full

**Comment by smillidge** [comment]
Get interface is also part of the Jolokia "protocol" https://jolokia.org/reference/html/protocol.html#get-request. We haven't implemented POST.

**Comment by kvalev** [comment]
I was thinking of contributing this feature, but I have issues getting the REST monitoring API to run with the latest payara5 version. The rest monitoring requests seem to be timing out both with the latest master version, as well as 5.181, while it works for both 4.18 and the Payara4 branch. Can you reproduce the issue?

Steps to reproduce:
- either build or download payara5
- ./asadmin start-domain
- Enable the REST API in the admin console (http://localhost:4848/common/monitor/monitoringPage.jsf?configName=server-config)
- GET http://localhost:4848/rest-monitoring/

This leads to the following entry in the server log:
```
[Payara 5.181] [SEVERE] [] [fish.payara.appserver.monitoring.rest.service.adapter.RestMonitoringAdapter] [tid: _ThreadID=183 _ThreadName=admin-thread-pool::admin-listener(4)] [timeMillis: 1523468770981] [levelValue: 1000] [[
  Timed out processing a rest monitoring request]]
```

**Comment by smillidge** [comment]
If you contribute on the Payara4 branch it will easily port across once fixed. I've raised an internal bug to get the 5 issue fixed.

**Comment by smillidge** [comment]
PR #2660 fixed the underlying Payara Server 5 issue
