### ISSUE TITLE
tried to port from payara4 to 5: Mass printing in payara log

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#2618]
# Description #
----------

We tried to port out WAR File to payara5 and had some problems with it (others are following)
This output is generated approx. 10-20 times per second and masses the log file.
`
[#|2018-04-11T11:39:45.754+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=203;_ThreadName=__ejb-thread-pool8;_TimeMillis=1523439585754;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.754+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=190;_ThreadName=__ejb-thread-pool1;_TimeMillis=1523439585754;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.798+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=199;_ThreadName=__ejb-thread-pool5;_TimeMillis=1523439585798;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.798+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=202;_ThreadName=__ejb-thread-pool6;_TimeMillis=1523439585798;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.843+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=207;_ThreadName=__ejb-thread-pool11;_TimeMillis=1523439585843;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.843+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=198;_ThreadName=__ejb-thread-pool2;_TimeMillis=1523439585843;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.889+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=209;_ThreadName=__ejb-thread-pool13;_TimeMillis=1523439585889;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.889+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=210;_ThreadName=__ejb-thread-pool14;_TimeMillis=1523439585889;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.938+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=200;_ThreadName=__ejb-thread-pool4;_TimeMillis=1523439585938;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.938+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=201;_ThreadName=__ejb-thread-pool3;_TimeMillis=1523439585938;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.990+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=208;_ThreadName=__ejb-thread-pool12;_TimeMillis=1523439585990;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]

[#|2018-04-11T11:39:45.990+0200|WARNING|Payara 5.181|javax.xml.soap|_ThreadID=205;_ThreadName=__ejb-thread-pool9;_TimeMillis=1523439585990;_LevelValue=900;|
  Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.|#]
`
We are using the SOAP Client Implementation from javax.xml.soap and parse it with javax.xml.xpath
It is no real problem, just annoying.
Any Ideas?

## Expected Outcome
less log output.

## Environment ##

- **Payara Version**: 5.1.8.1
- **Edition**: Full
- **JDK Version**: 8 (docker image openjdk:8-jdk-alpine)
- **Operating System**: alpine

**Comment by colangelo-david** [comment]
@deratzmann You may want to go into the admin console and check your log levels. You can find them in server-config -> Logger Settings -> Log Levels. its possible the Log Level for everything is set to "All" which would result in what you are seeing. Bumping most down to "Info" should quiet your logs.

**Comment by deratzmann** [comment]
As you can see, this seems to be a warning, so INFO loglevel would not work. Our logger settings are the standard settings of production domain from payara 5, nearly all is INFO, some are fine, just com.sun.enterprise.server.logging.GFFileHandler is ALL

**Comment by deratzmann** [comment]
I prepare a project. Give me some hours

**Comment by deratzmann** [comment]
Ok, In a fresh project there is only one WARNING, obviously I we try to call the SOAP massively. For creating my example I need a public SOAP API...Any ideas? Our internal service will not work for you...

**Comment by deratzmann** [comment]
If you just put these lines SOAP sample code 
`            SOAPConnectionFactory soapConnectionFactory = SOAPConnectionFactory.newInstance();
            SOAPConnection soapConnection = soapConnectionFactory.createConnection();
`
in a plain project, the warning occurs in payara 5. A javax.xml.soap.MetaFactory property is not directly used, but oviously inside the java SE (1.8.0_162). Will a jdk update get rid of this warning?

the last solution can also be setting the loglevel for javax.xml.soap to ERROR, but I think I want to solve the issue :)

**Comment by deratzmann** [comment]
[mavenproject2.zip](https://github.com/payara/Payara/files/1906950/mavenproject2.zip)
I made a test project

**Comment by smillidge** [comment]
Thanks for the test case we will try to reproduce the issue

**Comment by carlosromero68** [comment]
Hi Steve - Is there any update on this issue?

**Comment by mikatrash** [comment]
Hi,
We're experiencing the same issue on Payara 5.182 / Java Oracle 1.8.0_171.
Might be linked to https://github.com/javaee/metro-saaj/issues/95 ?

**Comment by carlosromero68** [comment]
Hi @smillidge - Is there any update on this issue?

**Comment by marcreichman** [comment]
Have seen a similar issue with 5.183 on java 8u171 in windows. Our app in question just has some soap services with `@WebService`. I'm not sure what else would be triggering this. I see a few warnings on startup.

**Comment by kulwinderjit** [comment]
`System.setProperty("javax.xml.soap.SAAJMetaFactory",
                "com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl");`
should make this warning go away

**Comment by smillidge** [comment]
I tried the test case attached and didn't get any log messages. I need a test case that demonstrates the issue.

**Comment by smillidge** [comment]
This is an upstream metro bug https://github.com/eclipse-ee4j/metro-saaj/issues/95

**Comment by smillidge** [comment]
Requires upgrade to https://github.com/eclipse-ee4j/metro-saaj/releases/tag/1.5.1

**Comment by rdebusscher** [comment]
Fixed in 5.191 as Metro is updated to version 2.4.3.
