### ISSUE TITLE
Measure coverage

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#2646]
Sonarqube is up & running (https://github.com/payara/Payara/issues/150), Jenkins as well, but coverage is not yet measured/published (AFAIK).
Putting coverage against complexity helps targetting test efforts effectively.

**Comment by Cousjava** [comment]
@ratcashdev The reason for coverage being 0% is that we have very little in the way of unit tests in the Payara project, our tests are in their own repository at https://github.com/payara/PayaraTests

**Comment by rdebusscher** [comment]
There are various test repositories, also internal ones, so a global coverage is not published.
