### ISSUE TITLE
Create an EJB Timer Store in Hazelcast

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#265]
Enhancement request to create an EJBTimer store using Hazelcast.

**Comment by abhirockzz** [comment]
It would be nice to have some stage related 'meta' information about the enhancement items e.g. work in progress, under review, open for contributions etc. :-)

**Comment by smillidge** [comment]
Good idea. We are always open for contributions though ;-)

**Comment by abhirockzz** [comment]
Absolutely. That's great. And I think that having this 'meta' information might help community members pick (enhancement) items they want to work on, at the same time ensuring that efforts are not duplicated (just like any other OSS project really)

As far as contributions to this particular item are concerned - just want to confirm whether this is already in the works by internal Payara team or other community folk(s) ? If not, I am definitely interested in pitching in. Let me know and we can take it from there :-)

Thanks!
