### ISSUE TITLE
Payara NetBeans Plugin 8.2

### ISSUE THREAD

**Issue by Michel0001** [payara/Payara#2652]
# Description #
----------

Payara NetBeans Plugin not available in plugin list

## Steps to reproduce (Only for bug reports) 

Go to Tools → Plugins.
Under the Available Plugins tab, search for Payara in the search box.
Payara are not listed

Plugin is configured with : 
Java DB = 201609300101
J2EE Support Utilities = 201609300101
Java SE Platforms and Libraries = 201609300101

but  plugins are updated since to : 
Java DB = 201705191307
J2EE Support Utilities = 201705191307
Java SE Platforms and Libraries = 201705191307

Configure payara plugin with greater than rather equals

Download and manual install is not possible

![image](https://user-images.githubusercontent.com/38522910/38979848-9eb5a3d8-43bb-11e8-81a4-0faae3ec0d89.png)

**Comment by jGauravGupta** [comment]
Hi @Michel0001 ,
Can you share you IDE Build version :  Help > About > Product Version
May you also confirm the installation result for NetBeans IDE v8.2 (Build 201609300101) **(Lang: English)**

**Comment by Michel0001** [comment]
Product Version: NetBeans IDE 8.2 (Build 201705191307)
Mises à jour : l'IDE NetBeans a été mis à jour vers la version NetBeans 8.2 Patch 2
Lang: French

I've download Netbeans 8.2 at 14/04/2017 and apply update when netbeans ask me.
Thanks.

**Comment by dorelo** [comment]
I am experiencing the same issue as @Michel0001 describes.

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2

Any ideas @jGauravGupta?

**Comment by jGauravGupta** [comment]
Hi @dorelo , 

Can you please share the error message.

**Comment by dorelo** [comment]
Hi @jGauravGupta,

I apologise, I was referring to the fact that the Payara plugins are not present in the plugin manager search, with the build I stated above.

However I have successfully installed them via http://plugins.netbeans.org/plugin/72263/payara-server .

**Comment by jGauravGupta** [comment]
Closing the ticket, If you are facing any other issue, please report it here : https://github.com/payara/ecosystem-netbeans-plugin

**Comment by hectorggp** [comment]
I have the exact same issue here with my netbeans Product Version: NetBeans IDE 8.2 (Build 201610071157)
Simply by doing this tuto from payara: https://www.payara.fish/documentation/getting-started-with-payara/
How I can fix this?
@Michel0001

**Comment by Mustafa-Halimeh** [comment]
I have the same response message from netbeans.
This my netbeans product information:
Product Version: NetBeans IDE 8.2 (Build 201610071157)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_212; Java HotSpot(TM) 64-Bit Server VM 25.212-b10
Runtime: Java(TM) SE Runtime Environment 1.8.0_212-b10
System: Linux version 4.12.14-lp150.12.48-default running on amd64; UTF-8; en_US (nb)

Is there a way to resolve this for the give netbeans 8.2 (201610071157)), or what?
Thanks
