### ISSUE TITLE
Console admin - blank screen on payara 4.1.2.181 linux

### ISSUE THREAD

**Issue by ezequielgaggioli** [payara/Payara#2654]
# Console admin - blank screen on payara 4.1.2.181 linux #
----------

## Expected Outcome

Display login screen

## Steps to reproduce (Only for bug reports) 

1 - Start the domain

    ./asadmin start-domain domain1

2 - Open browser and type localhost:4848

[server.log](https://github.com/payara/Payara/files/1929789/server.log)

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**:8 (1.8.0_172-b11) - Oracle
- **Operating System**:  Linux

**Comment by smillidge** [comment]
Which Linux?

**Comment by ezequielgaggioli** [comment]
Development : ubuntu 14.04.5 (3.13.0-144-generic #193-Ubuntu x86_64 x86_64 x86_64 GNU/Linux).

Production : Red Hat Enterprise Linux Server release 6.8 (Santiago) (2.6.32-642.4.2.el6.x86_64 #1 x86_64 x86_64 x86_64 GNU/Linux). In production jdk version is 1.8.0_121 - Oracle

The same problem occurs in both operating systems.

**Comment by smillidge** [comment]
Possible duplicate #2630

**Comment by smillidge** [comment]
I can't reproduce this.

**Comment by smillidge** [comment]
Can you try with a new installation from a clean unzip?

**Comment by smillidge** [comment]
That maven link is for Payara Blue which is for an AIX version only. You should be using https://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara-ml/4.1.2.181/payara-ml-4.1.2.181.zip on Linux.

**Comment by ezequielgaggioli** [comment]
Excuse me. That was the problem. Now everything works fine.
Thanks.
