### ISSUE TITLE
SonarQube findings: Unclosed resources

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#2674]
SonarQube indentified ~200 blockers: https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&resolved=false&severities=BLOCKER&types=BUG

Many of them are about unclosed resources, and many of them are false positives. However, there seem to be a couple that are legitimate, like the following:

* https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWJyLExk1B6WA4TgWEIK&resolved=false&severities=BLOCKER&types=BUG
* https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWJyK_291B6WA4TgV8PK&resolved=false&severities=BLOCKER&types=BUG
* https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWJyLEtZ1B6WA4TgWEAC&resolved=false&severities=BLOCKER&types=BUG (even though the socket GETS closed in the finalize() method, but that may be a bit too late sometimes)

Fixing some of them may even resolve some classloader leaks or resource leaks.

**Comment by lprimak** [comment]
Looks like this is fixed
