### ISSUE TITLE
Unable to build Payara from latest pull

### ISSUE THREAD

**Issue by Acidcrawl** [payara/Payara#2675]
# Description #
----------

When I attempt to build the latest pull of Payara I get errors as it is trying to do the priming build.

## Current Outcome

I am attaching the output from maven

## Steps to reproduce (Only for bug reports) 

mvn clean install

## Environment ##

- **Payara Version**: 5.182
- **JDK Version**: 1.8.171
- **Operating System**:  Windows 7
[payara_build_output.txt](https://github.com/payara/Payara/files/1949038/payara_build_output.txt)

**Comment by smillidge** [comment]
The error is related to your SSL configuration of Maven

**Comment by Acidcrawl** [comment]
I saw some posts indicating that, I tried importing certificates but nothing seemed to work.  Do you have any advice on how to fix it?

**Comment by smillidge** [comment]
I have seen it before but I don't remember how to fix it. I suggest you post on the forum for advice. https://groups.google.com/forum/#!forum/payara-forum

**Comment by Acidcrawl** [comment]
I figured this out, my company proxy server was corrupting the certificates.  I just had to bypass the proxy and now all is well.
