### ISSUE TITLE
Payara-Micro 5.181 - auto cluster does not work

### ISSUE THREAD

**Issue by Daniel-Dos** [payara/Payara#2690]
# Description #
----------
I was testing this new version and went to make use of the auto-cluster, but when I start two instances of payara-micro with different ports, nothing happens, unidentified 'membres' as it was in the 5-snapshot version.

I read something about deployment group, but how does this work on payara-micro?

## Environment ##

- **Payara Version** 5: 181
- **Edition**: micro
- **JDK Version**: 8 u162 - OpenJDK 
- **Operating System**: Linux Mint

**Comment by smillidge** [comment]
I've just ran two Payara Micros and they auto-cluster what do you see different?
` java -jar payara-micro.jar --autobindhttp &
java -jar payara-micro.jar --autobindhttp
`

**Comment by smillidge** [comment]
The log message on 5 looks like;
```
  Data Grid Status 
Payara Data Grid State: DG Version: 35 DG Size: 2
Instances: {
Address: /192.168.2.128:6900 UUID: 059803ad-e428-4afe-921c-e4f8a744c7a6 Lite: false This: false Name: Amused-Skate Group: MicroShoal
Address: /192.168.2.128:6901 UUID: 2c79c2d6-9e00-4878-aa61-0b264976bbb7 Lite: false This: true Name: Sardonic-Sardine Group: MicroShoal
}]]
```

**Comment by Daniel-Dos** [comment]
Hi @smillidge ,

thanks very much, I had done that yesterday and for some reason it did not capture the other instance at first, but now it works.
