### ISSUE TITLE
Payara 5 can not add managed resources to Deployment Group PAYARA-2701

### ISSUE THREAD

**Issue by mtk4ntewmjq** [payara/Payara#2699]
# Description #
----------

Deployment group can not be specified as a target for deployment of resources.

## Expected Outcome

Like Clusters, I would like to add resource targets as well in the Deployment Group.

## Current Outcome

I attempted to set the Deployment Group as a JDBC resource target from the management console, but the following error occurred and it could not be set.

  Resource ${resource-name} has Invalid target to create resource-ref on ${deployment-group}.

In addition, I attempted to make settings from the following URL, but it also failed.

  http://localhost:4848/management/domain/deployment-groups/deployment-group/${deployment-group}/resource-ref

## Steps to reproduce (Only for bug reports) 

The procedure performed in the management console is as follows.

1. Select any JDBC Resource (in Resources> JDBC> JDBC Resources)
2. Select Target tab
3. Select Manage Targets, add Deployment Group to Selected target and save.

The following error has been displayed on the management screen.
(The following is displayed when adding the Resource "jdbc/default" as a target of the Deployment Group "cluster-deployment-group".)

![resource-ref-error](https://user-images.githubusercontent.com/38527641/39518138-f432ef38-4e3c-11e8-8cd2-1364d5d46519.png)

## Environment ##

- **Payara Version**: 5.182-SNAPSHOT
- **Edition**: FULL
- **JDK Version**: 8 u162 - Oracle
- **Operating System**: Windows 7
- **Database**: NONE

**Comment by smillidge** [comment]
Fixed by #2721
