### ISSUE TITLE
Replace GMS implementation

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#27]
Replace the current Shoal based implementation of the GMS with Hazelcast.

Likely files impacted are;

appserver/ha/ha-file-store/src/main/java/org/glassfish/ha/store/adapter/file/FileBackingStore.java:  
appserver/ha/ha-file-store/src/main/java/org/glassfish/ha/store/adapter/file/FileBackingStore.java:  
appserver/ha/ha-shoal-store/src/main/java/org/shoal/ha/store/ReplicatedBackingStoreFactory.java:
appserver/ha/ha-shoal-store/src/main/java/org/shoal/ha/store/GlassFishKeyMapper.java
appserver/ha/ha-shoal-cache-bootstrap/src/main/java/org/glassfish/ha/store/adapter/cache/ReplicationStoreProxy2.java  
appserver/ha/ha-shoal-cache-bootstrap/src/main/java/org/glassfish/ha/store/adapter/cache/ShoalBackingStoreProxy.java
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IiopFolbGmsClient.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ValidateMulticastCommand.java
nucleus/cluster/gms-bootstrap/src/main/java/org/glassfish/gms/bootstrap/GMSAdapterService.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/GMSAdapterImpl.java
appserver/admin/admin-core/src/main/java/com/sun/enterprise/admin/UpgradeService.java
appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/GMSTest.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/DistributedEJBTimerService.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulContainerFactory.java
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IiopFolbGmsClient.java
appserver/payara-admingui/devtests/src/test/java/org/glassfish/admingui/devtests/GMSTest.java
appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/distributed/ReadOnlyBeanMessageCallBack.java
appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecIORInterceptor.java
appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/Lookups.java
appserver/tests/admingui/auto-test/src/test/java/org/glassfish/admingui/devtests/GMSTest.java
appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java
appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/RecoveryLockFile.java
appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/GMSCallBack.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASSOFactory.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationWebEventPersistentManager.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/HAUtilImpl.java
appserver/webservices/metro-glue/src/main/java/org/glassfish/webservices/metroglue/MetroContainer.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/GroupManagementService.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Cluster.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/FailureDetection.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/util/ConfigApiLoggerInfo.java
nucleus/cluster/gms-bootstrap/src/main/java/org/glassfish/gms/bootstrap/GMSAdapterService.java
nucleus/cluster/gms-bootstrap/src/main/java/org/glassfish/gms/bootstrap/HealthHistory.java
nucleus/cluster/gms-bootstrap/src/main/java/org/glassfish/gms/bootstrap/GMSAdapter.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/GMSConfigUpgrade.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/admin/GMSAnnounceBeforeStartClusterCommand.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/admin/GMSAnnounceAfterStartClusterCommand.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/admin/GMSAnnounceBeforeStopClusterCommand.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/admin/GMSAnnounceSupplementalInfo.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/admin/GMSAnnounceAfterStopClusterCommand.java
nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/GMSAdapterImpl.java
nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/GetHealthCommand.java
nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/LocalStrings.properties
nucleus/common/common-util/src/main/java/com/sun/logging/LogDomains.java
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBFactoryImpl.java
appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/GMSCallBack.java

**Comment by dmatej** [comment]
Ok, I'm curious ... but at this time I have to fix it because we use clustered instances ... Shoal sources downloaded and I'm trying to do some cleaning to get clean interface for Glassfish/Payara ... and then it can be thrown away :+1:

**Comment by fturizo** [comment]
@smillidge, since **Hazelcast** is now a viable to replace **Shoal** for clustering, can we close this issue? Or the idea is to completely remove **Shoal** from Payara?
