### ISSUE TITLE
Support rolling updates

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#270]
There are traces here and there about the support of concurrent versions (a.k.a rolling updates) of a single application inside Glassfish (3.1 and later) and thus achieving zero-downtime deployment.
More info:
* https://wikis.oracle.com/display/GlassFish/ProductionRedeploymentOnePager
* http://stackoverflow.com/questions/19292654/rolling-upgrade-application-glassfish-3-1-2-2

**Comment by phillipross** [comment]
:+1:   +1

**Comment by gulbinas** [comment]
:+1: +1

**Comment by ratcashdev** [comment]
Checked in 4.1.153. I can confirm, rolling updates in standalone instance works. issue can be closed.
For more info, see #433
