### ISSUE TITLE
Deployment issues with timers and create-application-ref between DAS and Nodes

### ISSUE THREAD

**Issue by calumgardiner** [payara/Payara#2700]
# Description #
----------
There appears to be an issue with the create-application-ref command causing issues with the timer service on nodes/DAS under certain circumstances. 

We have a number of Payara clusters which use an external SQL Server as the EJB Timer Service datasource. 

If an application with non-persistent timers is deployed to both the DAS (server target) and then an application reference created to the nodes (cluster target), it appears to corrupt the timer service configuration in some way.

## Expected Outcome

Unsure of what the expected outcome should be, but the current outcome doesn't seem right.

## Current Outcome

External EJB timer database ends up with hanging references, unable to deploy applications with timer jobs and/or timer jobs not executing. 

## Steps to reproduce (Only for bug reports) 

In order to recreate the issue you will need to setup a Payara DAS with some nodes as part of a cluster configuration. Create a datasource to an external database which is available to the cluster configuration and set this datasource as the EJB Timer Service datasource. 

I have created some applications to help recreate the issue.

timerstest - https://github.com/calumgardiner/timerstest
timercreateissue - https://github.com/calumgardiner/timercreateissue

The timertest war contains 4 timers; 2 created using @Schedule (one persistent and one non-persistent) and 2 created using the TimerService resource (again, one persistent and one non-persistent). The timercreateissue war contains a non-persistent timer created using the TimerService resource (there may be other ways to create the issue but this is how it happens for me).

After the test cluster is setup you can deploy the timertest war and observe that the 4 timers are running in your nodes, there should be some messages in the node logs:
`[2018-05-02T09:23:15.000+0100] [Payara 4.1] [INFO] [] [scot.gov.seemis.timerstest.NonPersistentScheduleTimer] [tid: _ThreadID=297 _ThreadName=__ejb-thread-pool16] [timeMillis: 1525249395000] [levelValue: 800] [[
  RUN NON-PERSISTENT SCHEDULE TIMER TEST @ Wed May 02 09:23:15 BST 2018]]`

`[2018-05-02T09:23:15.012+0100] [Payara 4.1] [INFO] [] [scot.gov.seemis.timerstest.PersistentScheduleTimer] [tid: _ThreadID=267 _ThreadName=__ejb-thread-pool3] [timeMillis: 1525249395012] [levelValue: 800] [[
  RUN PERSISTENT SCHEDULE TIMER TEST @ Wed May 02 09:23:15 BST 2018]]`

`[2018-05-02T09:23:21.067+0100] [Payara 4.1] [INFO] [] [scot.gov.seemis.timerstest.PersistentTimerService] [tid: _ThreadID=265 _ThreadName=__ejb-thread-pool1] [timeMillis: 1525249401067] [levelValue: 800] [[
  RUN PERSISTENT TIMER SERVICE TEST @ Wed May 02 09:23:21 BST 2018]]`

`[2018-05-02T09:23:21.128+0100] [Payara 4.1] [INFO] [] [scot.gov.seemis.timerstest.NonPersistentTimerService] [tid: _ThreadID=266 _ThreadName=__ejb-thread-pool2] [timeMillis: 1525249401128] [levelValue: 800] [[
  RUN NON-PERSISTENT TIMER SERVICE TEST @ Wed May 02 09:23:21 BST 2018]]`

And the external timer database should contain data now for the timers created.
[Database contains timer info](https://raw.githubusercontent.com/calumgardiner/timercreateissue/master/timercreateissue/1%20-%20Timer%20Database%20working.PNG)

Undeploy the application, this should stop the messages being printed in the log and the database should now by clear from the timers, as expected.

### Creating the Issue
In order to recreate the issue we are seeing firstly redeploy the timertest war to only the cluster. Again you should see the EJB_TIMER_TBL contains the timer information and the server logs should contain the relevant messages. Now deploy the timercreateissue war to the DAS (server-config), and use the create-application-ref command to create the application reference to the cluster target. Now stop the cluster and domain, start the domain and start the cluster instances with sync full. 

After the server is started and nodes re-synced everything will look like its running fine, the log will contain the correct timer entries and the external timer database will still contain the correct rows. Now undeploy the timertest war from the cluster. At this point we are seeing that the persistent @Schedule timer from the timertest war is still in the external timer database.

[Scheduled Timer Remains in Database After Undeploy](https://raw.githubusercontent.com/calumgardiner/timercreateissue/master/timercreateissue/2%20-%20Corrupted%20Timer%20Table.PNG)

When we now redeploy the timertest war to the cluster an error is displayed that indicates the EJB Timer Service is unavailable.

[Error on Deployment](https://raw.githubusercontent.com/calumgardiner/timercreateissue/master/timercreateissue/3%20-%20Deployment%20Error.PNG)

Undeploying the applications and restarting and re-syncing the nodes appears to fix the issue sometimes but leaves the corrupted row in the external timer database. On occasions this was also not fixing the issue and resulted in deployed applications not executing there @Schedule persistent timer jobs. Although I was not able to reliably reproduce this part.

### Samples

timerstest - https://github.com/calumgardiner/timerstest
timercreateissue - https://github.com/calumgardiner/timercreateissue

## Context (Optional)

In our actual application we require some non-persistent timers to run on both the DAS and nodes in order to keep files which are synchronised to the nodes up to date on both sets of servers.

## Environment ##

- Payara 4.1.2.181
- Full Edition
- JDK 8: 
- Windows + Linux tested (likely affects all OS)
- SQL Server (only tested with SQL server so far)

**Comment by calumgardiner** [comment]
I should note that our workaround for the time being was to also assign the server-config EJB Timer Service datasource to the external datasource. But unsure of why the issue was occurring, as it appears to be non-persistent timers which are triggering it.

**Comment by smillidge** [comment]
This is confusing but by design and your workaround is correct. The DAS needs to be configured to use the same datasource as the cluster nodes. That way it has visibility of the persistent timers and can manage them correctly. The entries in the timer database are usually created by the DAS on deployment not by the individual servers that make up the cluster.  This also allows the DAS to control fail over of the timers.

Do you experience issues when the DAS is configured to use the external datasource?

**Comment by calumgardiner** [comment]
After the DAS is configured to use the external datasource everything works as expected. Thanks for the info, we will continue to use the changed configuration. If I've not missed anything (which I admit is unlikely) then the documentation could probably be clearer in this area.
