### ISSUE TITLE
Setting --minHttpThreads seems not work properly in Payara Micro.

### ISSUE THREAD

**Issue by I2Qi** [payara/Payara#2714]
I find a typo at [here](https://github.com/payara/Payara/blob/7c6ea3578adb8a5e22162f126638da2f1ec2332a/appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java#L1764).

And try to set via command line flag "--minHttpThreads", but the number I specified was not reflected in domain.xml.

In addition, I set "--maxHttpThreads" and the number I specified was reflected in domain.xml.

**Comment by Cousjava** [comment]
Internal issue number PAYARA-2735
