### ISSUE TITLE
Cannot log in to Admin Console of Domain created from payara-domain.jar Template

### ISSUE THREAD

**Issue by Pandrex247** [payara/Payara#272]
It is not possible to log into the Admin Console of a domain created from the payara-domain template. Attempting to causes the log in screen to appear, and any username/password will be rejected.

This is true of domains created with the default username of "admin" and a blank password, as well as those created with non-default values.

Steps to Reproduce:
* Download latest build
* Create a new domain from the payara-domain.jar template - `./asadmin create-domain --template ../glassfish/common/templates/gf/payara-domain.jar domain2`
* Start the domain
* Attempt to access the Admin Console

**Comment by Pandrex247** [comment]
The problem seems to stem from secure admin being enabled in the payara-domain template.
Creating a password for the admin user, and then running "enable-secure-admin" seems to allow you to log in.

Alternatively, removing `enabled="true"` from the _secure-admin_ options in the template fixes the issue.

As a side note, is there a particular reason the secure admin details and administrative domain name are hard-coded? 

    <property name="administrative.domain.name" value="payaradomain"></property>
    <secure-admin enabled="true" special-admin-indicator="88ca53a0-0e86-4e88-83d6-8f0110bb94eb">
        <secure-admin-principal dn="CN=localhost,OU=GlassFish,O=Oracle Corporation,L=Santa Clara,ST=California,C=US"></secure-admin-principal>
        <secure-admin-principal dn="CN=localhost-instance,OU=GlassFish,O=Oracle Corporation,L=Santa Clara,ST=California,C=US"></secure-admin-principal>
    </secure-admin>


Having it hard-coded like this means that any domain created from this template will list itself as _payaradomain_ when starting and stopping even if it is called something else. For example:

    ./asadmin create-domain --template ../glassfish/common/templates/gf/payara-domain.jar domain2
    ./asadmin start-domain domain2

Returns:

    Waiting for payaradomain to start .......
    Successfully started the domain : domain2

**Comment by AlphaJuliettOmega** [comment]
So there is no default password, you just can't log into the web interface of a newly created domain?

**Comment by mikecroft** [comment]
The default is whatever you set it to be when you create the domain. If there is no password, you are not prompted to log in.

**Comment by AlphaJuliettOmega** [comment]
I apologize for the necromancy, I had not set it so 'secure-admin' was not enabled so login with the blank password was not possible,
I set a password and it worked as expected :)
