### ISSUE TITLE
security using RolesAllowed not always working

### ISSUE THREAD

**Issue by eduarddrenth** [payara/Payara#2729]
# Description #
----------

## Context

same application (exact same war), same payara version, same java version, identical, automated payara configuration

## Problem

on one machine RolesAllowed works on the other I am allowed updates without the correct role.

## Expected Outcome

When I do not have the correct role I am not allowed to execute annotated method 

## Current Outcome

When I do not have the correct role I am allowed to execute annotated method

## Steps to reproduce (Only for bug reports)

No steps yet, but relevant snippets:

```
In Controller:

    @Inject
    @Override
    protected void initCrudWriteService(@StdwCrudBean Auditing crudWriteService) {


@Local({CrudReadService.class, Auditing.class, StdwCrudService.class})
@Stateless
@StdwCrudBean
public class CrudServiceBean extends AbstractCrudServiceEnvers implements StdwCrudService {
.
.
    @Transactional
    @RolesAllowed(EDITORROLE)
    @Override
    public <T extends Serializable> T update(T t) {
.
.
        return super.update(t); // super code see below
    }
.
.
    @Transactional
    @TransactionAttribute
    @Override
    @RolesAllowed(value = {EDITORROLE})
    public <T extends Serializable> T update(T t) {
            return getEntityManager().merge(t);
    }


```

[servlet setup](https://github.com/payara/Payara/files/2009496/servlet.zip)

## Environment ##

- **Payara Version**: 5.181
- **Edition**: full
- **JDK Version**: 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
- **Operating System**: both environments ubuntu 16.04
- **Operating System**: linux 4.4.0-119-generic for working environment
- **Operating System**: linux 2.6.32-042stab128.2 for not working environment
- **Database**: MySQL

**Comment by eduarddrenth** [comment]
The file realm:

![screenshot from 2018-05-16 16-31-35](https://user-images.githubusercontent.com/10200360/40123513-b2f74e52-5926-11e8-88b3-de3b40a793d6.png)

**Comment by eduarddrenth** [comment]
Now, after again a lot of testing on the problematic server, deploying the same war that did not work before, all of a sudden it works as expected. Caching server side of some form?

**Comment by smillidge** [comment]
Can you provide a reproducible test case?

**Comment by eduarddrenth** [comment]
No, that's the frustrating thing, all I can do is upload the war that I saw the problem with and scripts to make it run, it will be like the reproducer in #2625. If that's ok I can provide that, but I suspect it will just run fine.

**Comment by eduarddrenth** [comment]
Ok, sorry I left it open, haven't seen anything unusual anymore...

**Comment by smillidge** [comment]
glad to hear it is working.
