### ISSUE TITLE
Injecting Claim values of MP JWT Auth is not supported?

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara#2742]
# Description #

Adding the following code to a JAX-RS Resource make the deployment fails.

      @Inject   
      @Claim("custom-value")   
      private String custom;   

Not only a custom value injection fails, but any injection with @Claim or JsonWebToken.
Tried with Payara Micro 5.181

## Expected Outcome

Application should start and value from custom claim of JWT should be available.

## Current Outcome

`
org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
`

`
Caused by: java.lang.NullPointerException
        at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:463)
        at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:314)
        at com.sun.enterprise.container.common.impl.managedbean.ManagedBeanManagerImpl.createManagedBean(ManagedBeanManagerImpl.java:476)
`
## Example ## 

Add the Inject into the example `https://github.com/javaee-samples/microprofile1.2-samples/blob/master/jwt-auth/jaxrs/src/main/java/org/eclipse/microprofile12/jwtauth/jaxrs/Resource.java`

## Environment ##

- **Payara Version**: 5
- **Edition**: Micro
- **JDK Version**: Oracle Java 8
- **Operating System**: MAC
- **Database**: none

**Comment by smillidge** [comment]
The NPE is due to a deployment error. The bug whereby a deployment error results in a NPE is fixed in current master. Can you try on a nightly and see what deployment error is being masked. https://www.payara.fish/upstream_builds

**Comment by rdebusscher** [comment]
This is the error

`WELD-001408: Unsatisfied dependencies for type ClaimValue<String> with qualifiers @Claim
`

So there are missing CDI producers (or equivalent) for this information within Payara.

According to the spec, these type of injections are required to be supported.

**Comment by smillidge** [comment]
I know it passes the TCK and there is some setup required https://docs.payara.fish/documentation/microprofile/jwt.html. Could you try modifying https://github.com/javaee-samples/microprofile1.2-samples/tree/master/jwt-auth 

Otherwise @arjantijms any ideas?

**Comment by rdebusscher** [comment]
I investigated this a bit more.

When updating the microprofile-1.2-samples, there is a mentioning in the server.log that Injection is not allowed within @ApplicationScoped beans. (other implementations don't enforce this requirement)

This is another exception than the one I receive. (already using RequestScoped)

Within attachment, a demo project to reproduce the problem

    mvn clean package -Ppayara-micro
    java -jar target/demo-microbundle.jar

Thx
[demo.zip](https://github.com/payara/Payara/files/2034979/demo.zip)

**Comment by arjantijms** [comment]
@smillidge @rdebusscher 

I was surprised about this too reading the spec, but 7.1.2. of the JWT spec says:

> This specification requires support for injection of claims from the current JsonWebToken using the org.eclipse.microprofile.jwt.Claim qualifier: [code] with **@dependent** scoping.

See also: https://github.com/eclipse/microprofile-jwt-auth/issues/45

**Comment by rdebusscher** [comment]
I dived into the Payara JWT Auth integration and debugged why I get the error.

I found out that LoginConfig, which triggers the integration and creation of all required Beans, must be set on a CDI bean.

Since I have a beans.xml file with `bean-discovery-mode="annotated"` my JAX-RS application class isn't scanned unless I explicitly annotate it with something like `@ApplicationScoped`.

**Comment by rdebusscher** [comment]
Can the documentation be updated (https://docs.payara.fish/documentation/microprofile/jwt.html, section "Activating JWT Authentication") to cover this usage scenario?

**Comment by smillidge** [comment]
JAX-RS annotations aren't bean defining is that the problem?

**Comment by rdebusscher** [comment]
In a sense yes (Payara JWT Auth integration checks only for @LoginConfig on CDI beans)

**Comment by smillidge** [comment]
Can you raise a documentation bug on the Payara-Server-Documentation repo?
