### ISSUE TITLE
payara 5.181 has eclipselink issue re TIMESTAMP columns with TIMEZONE

### ISSUE THREAD

**Issue by ke5stl** [payara/Payara#2746]
# Description #

eclipselink used in version 5.181 of payara has a bug which affects postgresql timestamp with timezone column types.

there is an eclipselink bug opened about the issue.  it needs to be addressed.

here is the link to the forum posting about this issue

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/payara-forum/AjLhbC9th4c/u9uKsorYAwAJ

here is the link to the eclipselink issue about this problem:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=522408

## Expected Outcome

fixing the eclipselink bug and updating the eclipselink version used by payara should resolve the this issue.

## Current Outcome

any application that uses postgresql timestamp fields with timezone are going to fail reliably.

## Steps to reproduce 

create a project that has postgresql data entity with TIMESTAMP column which has TIMEZONE.

eg: entity having column as:

@Column(name = "verified")
    @Temporal(TemporalType.TIMESTAMP)
    private Date verified;

and in the database, have:

       verified timestamp with time zone

for the column definition.

## Context (Optional)

no application that uses TIMESTAMP columns with TIMEZONE will function.  they will always fail.

## Environment ##

- **Payara Version**: 5.181
- **Edition**: full
- **JDK Version**: 8 Oracle (but should not matter)
- **Operating System**: all
- **Database**: definitely PostgreSQL, perhaps others?

**Comment by sgflt** [comment]
We use Informix server and Eclipselink in Payara 5 is incompatible too. We encountered problems with Date columns instead of Timestamps.

Eclipse link does some magic with resultSet.getString("column"), where column is type of DATE.

**Comment by svendiedrichsen** [comment]
I have offered a fix for this bug at the eclipselink project. https://github.com/eclipse-ee4j/eclipselink/pull/113

**Comment by svendiedrichsen** [comment]
... and a backport to branch 2.7: https://github.com/eclipse-ee4j/eclipselink/pull/117

**Comment by svendiedrichsen** [comment]
... and both have been merged just now.

**Comment by smillidge** [comment]
Should be fixed in 5.183
