### ISSUE TITLE
JDBC connection pool for MYSQL Database is not working

### ISSUE THREAD

**Issue by mohamed-taman** [payara/Payara#2747]
# Description #
----------
I am just at the beginning of configuring Payara server, for my Java EE 8 application to run probably on it.

First is simple I just wanted to create a JDBC connection pool, that connects to MySQL server on my local machine, after creation and save the connection pool. trying to ping the server it gives this error:

`An error has occurred
Ping Connection Pool failed for MySqlPool. Connection could not be allocated because: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. Please check the server.log for more details.`

And this what appears on the admin console.

## Expected Outcome
Connection pool should be created successfully and able to ping the database successfully in order to create, JDBC resource correctly.

## Current Outcome
Server log reports the following error:

```
[2018-05-20T16:18:42.121+0200] [Payara 5.181] [SEVERE] [] [] [tid: _ThreadID=50 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1526825922121] [levelValue: 1000] [[
  Sun May 20 16:18:42 CEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.]]

[2018-05-20T16:18:42.131+0200] [Payara 5.181] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=50 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1526825922131] [levelValue: 900] [[
  RAR8054: Exception while creating an unpooled [test] connection for pool [ MySqlPool ], Connection could not be allocated because: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]]

[2018-05-20T16:18:42.135+0200] [Payara 5.181] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=177 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1526825922135] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/ping-connection-pool.json'; attrs = '{id=MySqlPool}']]
```

## Steps to reproduce (Only for bug reports) 

1. Copy MySQL driver to domain lib folder.
2. Start the domain

`    ./asadmin start-domain domain1`

3. Configure JDBC connection pool in the admin console for MySQL database.

4. Save and ping to will give you this error.

## Context (Optional)

This is a production project for our company WebCentric, that will serve 10 million transactions per day for clients from around the world as well as our internal system as it is the data lake project for the company, that will connect to MySQL Cluster, and uses Java EE 8 technologies.

## Environment ##

- **Payara Version**: 5.181
- **Edition**:  Full
- **JDK Version**: 8 u172 - Oracle
- **Operating System**: Windows 10 / macOS Siera
- **Database**: MySQL Server 8.0.11

**Comment by smillidge** [comment]
The error message is coming from the MySQL driver. Are you sure you configured your datasource properties correctly for your MySQL Server?

**Comment by dmatej** [comment]
What version of mysql driver do you use? Version 8 comes with many changes in parameters. 
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html

**Comment by mohamed-taman** [comment]
Thanks for the reply, I already connect to the database from main application and using JPA local persistence unit connected to the database and it succeeds, with the following properties with are the same when trying to create a MySQL connection pool using Payara:

**Resource Type:** java.sql.DataSource
**Datasource Classname:** com.mysql.cj.jdbc.MysqlDataSource
_Aditional properties:_
**portNumber**: 3306
**user**:root
**password**:pass
**serverName**: localhost or 127.0.0.1
**databaseName**: taman

Those are the configuration I use, if you able to make the connection just give me the correct parameters.

**Comment by mohamed-taman** [comment]
I tried these configurations:

**user**:root
**password**:pass
**url**: jdbc:mysql://127.0.0.1:3306/taman

It doesn't work too.

**Comment by mohamed-taman** [comment]
tried these configurations as per provided URL (@dmatej) for connector/j v8.0.11:
[Configuration Properties](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html)

**user**:root
**password**:pass
**localSocketAddress**: localhost or 127.0.0.1
**useSSL**: false
**socksProxyPort**: 3306
**socksProxyHost**: localhost or 127.0.0.1

> It doesn't work too the same error.

**Comment by dmatej** [comment]
I think that "shotgun debugging" does not help too much. You have to know the database configuration for connection. I'm not sure with this database version, I still use MySql 5.7.22 with jdbc driver version 8.
The most trivial connection to mysql database is something like this (copy from my asadmin command updated with your properties):
``
create-jdbc-connection-pool --ping --restype javax.sql.DataSource --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource --property user=root:password=pass:DatabaseName=taman:ServerName=127.0.0.1:port=3306:useSSL=false:zeroDateTimeBehavior=CONVERT_TO_NULL:useUnicode=true:serverTimezone=UTC:characterEncoding=UTF-8:useInformationSchema=true:nullCatalogMeansCurrent=true:nullNamePatternMatchesAll=false MySqlPool
``
When I look again on your experiments, I would try the original properties and added useSSL=false. I don't think you use proxy ...?

Did you try telnet? Server should respond; if it hangs before Connected to localhost, it is network problem. But if you can successfuly connect from the application, this is not probably the problem.
```
telnet localhost 3306
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Y
5.7.22-0ubuntu18.04.1�FAj"p     :i`gL*wJmysql_native_password

!#08S01Got packets out of orderConnection closed by foreign host.
```
And one final thing - in which directory did you put the JDBC driver?

**Comment by mohamed-taman** [comment]
1. I have pinged the server and `telnet` it, and it responds correctly.
2. To add the driver to Payara I have used this command from `asadmin` :
`asadmin> add-library 'C:\Program Files (x86)\MySQL\Connector J 8.0\mysql-connector-java-8.0.11.jar' `
3. And I checked the driver location and it was added to the following location:
`C:\Work\Utils\Servers\Payara\5.181\full\glassfish\domains\domain1\lib\mysql-connector-java-8.0.11.jar`
4. I am using the JUnit to test my business from JPA local environment and it connects successfully and test cases for all CRUD operations successfully run.

**Comment by mohamed-taman** [comment]
Look dear @dmatej I have tried this command from `asadmin`:

`create-jdbc-connection-pool --ping --restype javax.sql.DataSource --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource --property user=root:password=pass:DatabaseName=taman:ServerName=127.0.0.1:port=3306:useSSL=false:zeroDateTimeBehavior=CONVERT_TO_NULL:useUnicode=true:serverTimezone=UTC:characterEncoding=UTF-8:useInformationSchema=true:nullCatalogMeansCurrent=true:nullNamePatternMatchesAll=false MySqlPool`

And it is created successfully and I have used the following command 
`asadmin> ping-connection-pool MySqlPool`
and it runs successfully too which wasn't before when I created the database connection from GUI.

All I have seen here is different configurations I will try to add them to my old connection to see if it will work or really there is a problem in GUI when created the connection, and will let you know.

**Comment by dmatej** [comment]
Also be careful with other my properties (unicode, timezone, characterEncoding, etc.) - these correlate to the database configuration. So if you have iso-8859-1 database, UTF-8 in jdbc driver may cause data corruption or exceptions (not sure now).
As @smillidge wrote, I don't think the problem is with Payara, so I believe you can close this issue. I configured the pool from GUI and my command here is based on my Arquillian+JUnit test configuration.

**Comment by mohamed-taman** [comment]
I have copped the all the configurations from the newly created pool to my old one and it is work successfully. 

> So you are right there is no problem with Payara at all.

Thanks, @smillidge, and @dmatej really for your help and thanks for configurations that solve the problem.

**Comment by igorzg** [comment]
It's not connecting while using glassfish-resources.xml

```xml
  <!--  EU CLUSTER -->
    <jdbc-connection-pool
            datasource-classname="com.mysql.cj.jdbc.MysqlDataSource" name="at"
            res-type="javax.sql.DataSource"
            steady-pool-size="1"
            is-connection-validation-required="true"
            connection-validation-method="meta-data"
            max-pool-size="10">
        <property name="password" value="dev123"/>
        <property name="user" value="dev"/>
        <property name="databaseName" value="dev"/>
        <property name="serverName" value="localhost"/>
        <property name="portNumber" value="3306"/>
        <property name="zeroDateTimeBehavior" value="convertToNull"/>
        <property name="useUnicode" value="true"/>
        <property name="characterEncoding" value="UTF-8"/>
        <property name="sessionVariables" value="time_zone='Europe/Vienna'"/>
    </jdbc-connection-pool>
    <jdbc-resource pool-name="at" jndi-name="jdbc/at"/>
```

Only message I got is 
```
[2018-06-06T15:56:22.497+0200] [] [WARNING] [] [javax.enterprise.web.util] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1528293382497] [levelValue: 900] The web application [unknown] registered the JDBC driver [com.mysql.cj.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
```

**Comment by UweBretschneider** [comment]
I had the same problem, it seems to be really weird behavior. I was using the terminal to issue this command to create a new connection pool:
./asadmin create-jdbc-connection-pool --ping --restype javax.sql.DataSource --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource --property user=root:password=xxx:DatabaseName=rvm_jsf:ServerName=127.0.0.1:port=3306:useSSL=false:zeroDateTimeBehavior=CONVERT_TO_NULL:useUnicode=true:serverTimezone=UTC:characterEncoding=UTF-8:useInformationSchema=true:nullCatalogMeansCurrent=true:nullNamePatternMatchesAll=false mysqlpool

Then the ping succeeded. I have the feeling that **there must be a property that causes this issue**. After using the command I have exactly 13 properties for the connection. Before I had over 60. Maybe the URL property is ignored or the encoding property is required. However, this is just guessing.

**Comment by rvega77** [comment]
When created a mysql connection pool, the datasource classname "com.mysql.jdbc.jdbc2.optional.MysqlDataSource " has a blank space in the end.

**Comment by SpartanYX** [comment]
The property that I added to make sure it works was useSSL =false which let me ping successfully.

**Comment by msdousti** [comment]
Notice that since Connector/J version 8.0.13, `useSSL` is deprecated in favor of `sslMode`. Please see
[this StackOverflow response](https://stackoverflow.com/a/58808566/459391) for further information.

**Comment by fzepeda009** [comment]
this work perfectly for me
create-jdbc-connection-pool --ping --restype javax.sql.DataSource --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource --property user=root:password=pass:DatabaseName=taman:ServerName=127.0.0.1:port=3306:useSSL=false:zeroDateTimeBehavior=CONVERT_TO_NULL:useUnicode=true:serverTimezone=UTC:characterEncoding=UTF-8:useInformationSchema=true:nullCatalogMeansCurrent=true:nullNamePatternMatchesAll=false MySqlPool

then i typed this:
asadmin> add-library 'C:\DriverMysql\current\mysql-connector-java-8.0.18\mysql-connector-java-8.0.18.jar'
Windows 10
And I checked the driver location and it was added to the following location:
C:\Program Files\glassfish-4.1.1\glassfish\domains\domain1\lib\mysql-connector-java-8.0.18.jar

Works fine!

**Comment by xvart** [comment]
The payara pool creation WEB GUI seems to use an incorrect "Datasource Classname" which when replaced with "com.mysql.cj.jdbc.MysqlDataSource" works, so thanks to fzepeda009

**Comment by ck7up** [comment]
i just change these follower propriety and all working good :) 
```
**User** : root
**pass** : qwerty123
**DatabaseName** : db_name
**useSSL** : false
**ServerName**: localhost
**characterEncoding** : UTF-8
**ZeroDateTimeBehavior** : CONVERT_TO_NUL
**useInformationSchema** : true
**nullCatalogMeansCurrent** : true
**SslMode** : DISABLED
**allowPublicKeyRetrieval** : true
**nullNamePatternMatchesAll** : false
```

#ck7up #paraya #paraya-mysql #server
