### ISSUE TITLE
lib/ext does not exist in domains created by 4.1.152 resulting in failure during add-library

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#276]
In earlier versions of Payara lib/ext was created when the domain was created. Thus when you do something like `asadmin add-library --type ext jtds.jar` you get an error like: "Attempt to rename /srv/glassfish/batch/applications/xfer-4410603376690190895/DEFAULT/jtds-1.3.1.jar to /srv/glassfish/batch/lib/ext/jtds-1.3.1.jar failed after 21 retries"

To address this, payara/glassfish should either create the directory as part of the add-library command or come with a pre-configured empty directory.

**Comment by davewinters** [comment]
applibs and classes directories also missing from the domains\<domain_name>\lib directory. These exist in Glassfish 4.1 GA. These also did not exist in payara 4.1.151. 

Glassfish 4.1 defaiult domain directory contains these subdirectories out of the box:

applibs
classes
databases
ext

**Comment by phillipross** [comment]
+1
