### ISSUE TITLE
Command start-domain failed.

### ISSUE THREAD

**Issue by paragsahu** [payara/Payara#2780]
i try to start payara server so many i m unable to start server 
![log _sever](https://user-images.githubusercontent.com/33711745/40640473-d08cdc54-6333-11e8-98ff-257ff2842839.png)

![server fail](https://user-images.githubusercontent.com/33711745/40640512-f5de6c16-6333-11e8-9e40-ccdef5fe7b0b.png)

**Comment by smillidge** [comment]
There is no information to go on here.
