### ISSUE TITLE
LocalDate and LocalDateTime fields are not mapped to correct database types

### ISSUE THREAD

**Issue by vanuatoo** [payara/Payara#2807]
Using Payara 5.181 with PostgreSQL 9.5
My Entities define fields with types LocalDate and  LocalDateTime which should be supported out of the box. For Java EE 7 I use AttributeConverter.

It's expected that when table is generated corresponding fields will have timestamp without time zone types in the table

Instead table columns are generated with varchar types.
There is a line in the log
Config:   The default table generator could not locate or convert a java type (class java.time.LocalDate) into a database type for database field (<tablename>.<fieldname>). The generator uses "java.lang.String" as default java type for the field.

If I change table column type manually afterwards data conversion back and fourth is working except one case.

When the field type is LocalDateTime and the value is null, exception is thrown when persisting the Entity

Caused by: org.postgresql.util.PSQLException: ERROR: column "<column_name>" is of type timestamp without time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.

**Comment by lprimak** [comment]
Looks like an EclipseLink issue.  Have you tried to ask on their forums or file a bug with them?

**Comment by vanuatoo** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=535431
https://www.eclipse.org/forums/index.php/t/1093539/

**Comment by dmatej** [comment]
No problem with EclipseLink and MySql, it might be problem with platform support ...?
https://www.eclipse.org/eclipselink/documentation/2.6/concepts/app_tl_ext001.htm
I use this without any problem:
```
@Table(name = "ImportBatch")
@Entity
public class ImportBatch implements Serializable {
  private static final long serialVersionUID = 1L;
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;
  private Integer idSenderUnit;
  private LocalDateTime timestamp;
...
```

**Comment by smillidge** [comment]
Can you create a test case we can use to recreate the issue and fix if necessary?

**Comment by smillidge** [comment]
This may have been fixed in the latest release as we upgraded EclipseLink which has some specific fixes in this area. As we do not have a test case we can't validate therefore closing this issue.

**Comment by spligo** [comment]
This is still happening for LocalDate
