### ISSUE TITLE
Packaged README.txt is outdated

### ISSUE THREAD

**Issue by StefanKock** [payara/Payara#2836]
# Description #
----------

The packaged README.txt is outdated.

## Expected Outcome

At least the correct version number and updated infos about prerequisites.

## Current Outcome

>  Thank you for downloading Payara Server 4.1.2.181!
> ...
> Payara Server currently requires on of the following JDKs:
> 
> * Oracle JDK 7/8 Update 5+
> ...

## Steps to reproduce (Only for bug reports) 

See Payara/appserver/packager/appserver-base/src/main/docs/README.txt or available downloads of 5.181 and 5.182

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full

**Comment by smillidge** [comment]
Thanks not sure how we missed that one

**Comment by smillidge** [comment]
Fixed by #2889
