### ISSUE TITLE
JAX-RS @RolesAllowed throw 401 - Unauthorized 

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2841]
# Description #
----------
Simple JAX-RS resource with @RollesAllowed enabled feature and also ContainerRequestFilter with priority  AUTHENTICATION. So this "filter" is invoked before RolesAllowedDynamicFeature to fill in the custom security context. I debug through RolesAllowedDynamicFeature  class and it gets the principal and correct rolles from the principal.

The method with annotation @RollesAllowed get invoked, returning the response.ok() but in reality it is returning 401 - Unauthorized  to the jersey client (or any other app for rest testing).

Method with @PermitAll is working correctly.

The application work fine on previous payara 4 (173 version). 

## Expected Outcome

Response should be the correct one from JAX-RS resource.

## Current Outcome

Instead of true response from the JAX-RS method, it return 401 - Unauthorized.

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: oracle 1.8_172
- **Operating System**: Windows
- **Database**: MySQL

**Comment by smillidge** [comment]
Do you have a test case we could use to confirm the issue?

**Comment by scrmtrey91** [comment]
This is the result log for simple jax-rs web resource, secured with @RolesAllowed:

[2018-06-14T20:03:36.790+0200] [Payara 5.182] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=51 _ThreadName=http-thread-pool::http-listener-2(5)] [timeMillis: 1528999416790] [levelValue: 900] [[
  WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for .]]

[2018-06-14T20:03:36.790+0200] [Payara 5.182] [INFO] [] [si.tadej.backend.SecureResource] [tid: _ThreadID=51 _ThreadName=http-thread-pool::http-listener-2(5)] [timeMillis: 1528999416790] [levelValue: 800] [[
  Access to secured JAXRS granted]]



The second log is actualiy logger.info from secured jax rs method with @RolesAllowed.

**Comment by scrmtrey91** [comment]
I see what is the problem. REALM in payara server-config -> security.

If i choose admin realm, and use only "admin" for username when it asked for web login, it is all ok, without 401 response. 

It is weird still, that method get invoked but still throws 401.

**Comment by scrmtrey91** [comment]
Test project: 

[payara5testapp.zip](https://github.com/payara/Payara/files/2103581/payara5testapp.zip)

**Comment by vargusz** [comment]
Maybe your `ContainerRequestFilter` is clashing with Payara's new out-of-the-box [`@RolesAllowed` support](https://docs.payara.fish/documentation/payara-server/app-deployment/descriptor-elements.html#jaxrs-roles-allowed-enabled)?

**Comment by scrmtrey91** [comment]
First of all thanks for your answer. Yes, it is clashing for sure.

So you suggest i "disable" this feature in the glassfish descriptor. Will custom JAX-RS security @RolesAllowed still work ?

**Comment by vargusz** [comment]
Yes, the `jaxrs-roles-allowed-enabled` tag only [controls](https://github.com/payara/Payara/blob/master/appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedAutoDiscoverable.java#L84) whether the default JSON Web Token `@RolesAllowed` filter is registered or not.

**Comment by scrmtrey91** [comment]
Ok that could be fix than. Thanks for the answer. Will try this later today after some tasks.

**Comment by silvafabio** [comment]
Hi.

Sorry for the reopen, but i face this same problem even using <jaxrs-roles-allowed-enabled>false</jaxrs-roles-allowed-enabled> in my application. 

Everything works fine when i deploy the application, but if i restart the payara (start / stop ) it's stop to work!

What's happen is that payara configuration override the application configuration and the only way to get it working again is to open the admin console and reload de application.

I'am using Payara Server 5.182 #badassfish (build 303)

**Comment by smillidge** [comment]
Have you tried Payara 192?

**Comment by silvafabio** [comment]
Can't update right now :-(

**Comment by thinkgear** [comment]
Hi, 
I am using the latest version 5.2022.4 of Payara.
I am facing the same issue, even after setting jaxrs-roles-allowed-enabled to false in payara-web.xml.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE payara-web-app PUBLIC "-//Payara.fish//DTD Payara Server 4 Servlet 3.0//EN"
        "https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-web-app_4.dtd">

<payara-web-app>

    <context-root>/</context-root>

    <!-- disable default security @RolesAllowed on payara for realm -->
    <jaxrs-roles-allowed-enabled>false</jaxrs-roles-allowed-enabled>

</payara-web-app>
```
Everything works fine when I deploy the application, but if I restart the payara (start/stop ) it's stop to work!
The below message is returned.
```
[2022-11-28T11:04:36.262+0000] [Payara 5.2022.4] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=69 _ThreadName=http-thread-pool::http-listener-1(1)] [timeMillis: 1669633476262] [levelValue: 900] [[
  WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for .]]
```
Requesting you to please reopen and look into this issue.
