### ISSUE TITLE
Netbeans 8.2 Deploy to Payara 5

### ISSUE THREAD

**Issue by HipDragon** [payara/Payara#2843]
After you compile a simple JEE 8 project in Netbeans 8.2. When you attempt to deploy it through Netbeans 8.2 you get the following error message "Error: Could not find or load main class Files\Payara".

If you manually start Payara 5 and deploy it via asadmin it deploys just fine and works as expected. 

Location of Payara 5 install is C:\Program Files\Payara 5, Payara 4 does not have this issue and is installed at C:\Program Files\Payara 4

## Environment ##
- **Payara Version**: 5-182
- **Edition**: Full
- **JDK Version**: Oracle JDK 8.172
- **Operating System**: Windows 10 64 Bit

**Comment by HipDragon** [comment]
I tried the NetBeans regular way first, and then went and found the Payara
plugin. Which gave me the same error message, but change the icon to a
payara icon.

**Comment by smillidge** [comment]
Please can you report the issue on this repository https://github.com/payara/ecosystem-netbeans-plugin
