### ISSUE TITLE
Payara mirco 5.182 SSL certificate expired PAYARA-2875

### ISSUE THREAD

**Issue by HMMurdock** [payara/Payara#2849]
# Description #
----------

Payara micro keystore contains expired SSL certificate

mintyfresh
 Validity: [From: Sat Mar 17 12:36:15 GMT 2018,
   |                To: Fri Jun 15 12:36:15 GMT 2018]
 
## Expected Outcome

No severe log for The SSL certificate has expired

## Current Outcome

[1;94mjavax.enterprise.system.security.ssl[0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1529089241098] [levelValue: 1000] [[
    |   The SSL certificate has expired: [
    | [
    |   Version: V3
    |   Subject: CN=mintyfresh, OU=dev, O=Payara, L=Malvern, ST=Worcestershire, C=UK
   |   Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11
   | 
   |   Key:  Sun RSA public key, 2048 bits
   |   modulus: 20585631393795508469028334768493909532486479673619339642625314351705895340880046596932319370517557775449110966207786452854204633760975934825238882939524588850849815063697559385118011666082347195550117817812181349641852626347595053441313321813957833458749661380857904681820222262377542677344327806626300350401201168710873632866500746756625738073289633734512552334726536207627487620295194912342964765210962883460858991785951331130382932502381455937116548566935160400734029184930727508709244367101714130132563759609397003204671686972347196529295550071448390887866889783362747609111352462048006919427546420802886875124767
   |   public exponent: 65537
    |   Validity: [From: Sat Mar 17 12:36:15 GMT 2018,
   |                To: Fri Jun 15 12:36:15 GMT 2018]
   |   Issuer: CN=mintyfresh, OU=dev, O=Payara, L=Malvern, ST=Worcestershire, C=UK
    |   SerialNumber: [    7c02bbfd]

## Steps to reproduce (Only for bug reports) 

deploy war file 

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Micro 
- **JDK Version**: 8  OpenJDK 
- **Operating System**:  Offical Docker images
- **Database**:

**Comment by smillidge** [comment]
Not sure how that got in there. Is this only in the docker image?

**Comment by HMMurdock** [comment]
No it's also  the download jar 
check  
payara-micro-5.182\MICRO-INF\domain\keystore.jks

**Comment by OndrejM** [comment]
@HMMurdock how to you start the docker container or plain payara-micro.jar? I started payara-micro:5.182 container with an app deployed from a mounted directory and I don't see any SSL exceptions.

Do you enable HTTPS?

**Comment by HMMurdock** [comment]
For example 
dowload this simple ping.war
https://github.com/AdamBien/docklands/tree/master/payara-micro-ping
download payara-micro-5.182.jar 
exec java -jar payara-micro-5.182.jar --deploy ping.war 

[2018-06-21T17:59:50.519+0200] [] [SEVERE] [NCLS-SECURITY-05054] [javax.enterprise.system.security.ssl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1529596790519] [levelValue: 1000] [[
  The SSL certificate has expired: [
[
  Version: V3
  Subject: CN=mintyfresh, OU=dev, O=Payara, L=Malvern, ST=Worcestershire, C=UK
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus: 20585631393795508469028334768493909532486479673619339642625314351705895340880046596932319370517557775449110966207786452854204633760975934825238882939524588850849815063697559385118011666082347195550117817812181349641852626347595053441313321813957833458749661380857904681820222262377542677344327806626300350401201168710873632866500746756625738073289633734512552334726536207627487620295194912342964765210962883460858991785951331130382932502381455937116548566935160400734029184930727508709244367101714130132563759609397003204671686972347196529295550071448390887866889783362747609111352462048006919427546420802886875124767
  public exponent: 65537
  Validity: [From: Sat Mar 17 13:36:15 CET 2018,
               To: Fri Jun 15 14:36:15 CEST 2018]
  Issuer: CN=mintyfresh, OU=dev, O=Payara, L=Malvern, ST=Worcestershire, C=UK
  SerialNumber: [    7c02bbfd]

Certificate Extensions: 1
[1]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 4F 3F 66 75 AB 0E D9 1D   01 AF F9 D2 D3 E0 DB FE  O?fu............
0010: D5 6C 94 14                                        .l..
]
]

just check keyStore
keytool -list -v payara-micro-5.182\MICRO-INF\domain\keystore.jks

**Comment by OndrejM** [comment]
I can confirm that, I just missed it the first time I tried. We'll try to fix that.

**Comment by smillidge** [comment]
Should be fixed in 183
