### ISSUE TITLE
Question: which deployment artifact types does payara-micro support?

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#287]
I tried swapping out embedded-all for micro thinking it would be seamless, but discovered payara-micro doesn't appear to like ear archives.  I'm assuming this is a "micro" thing and not a bug?

Which deployment artifact types does payara-micro actually support?  Thanks!

**Comment by smillidge** [comment]
Payara Micro is web profile + some extras so it only supports war files. 

You can still get full embedded here. http://www.payara.co.uk/payara_embedded
