### ISSUE TITLE
JSONLogFormatter to console and payara in foreground

### ISSUE THREAD

**Issue by mb-dbc-dk** [payara/Payara#2871]
JSONLogFormatter doesn't seem to be detected/enabled when running payara-5.182 in the foreground.
----------

When configuring JSON logging to console (useful when running Docker environment to ELK) by modifying the logging.properties, then there's no JSON output only ULF.

## Expected Outcome

JSON log

## Current Outcome

ULF log

## Steps to reproduce

1.  Unpack the payara

    `unzip payara-5.182.zip` 

2.  Start the default domain

    `./payara5/bin/asadmin start-domain --verbose`

3.  Enable JSON console log

    `./payara5/bin/asadmin set-log-attributes. java.util.logging.ConsoleHandler.formatter='fish.payara.enterprise.server.logging.JSONLogFormatter'`
    This produces JSON Log on the console.

4.  Restart the default domain

    Press `^C` to break.
    `./payara5/bin/asadmin start-domain --verbose`
    This produces ULF log.

5.  Try to reenable JSON console log

    `./payara5/bin/asadmin set-log-attributes java.util.logging.ConsoleHandler.formatter='fish.payara.enterprise.server.logging.JSONLogFormatter'`
    This does not enable JSON log, only if you set it to something else first.
    It seems like there's no change to the content of logging.properties, hence logging system doesn't reload its configuration.

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**:  1.8.0_172 - Oracle
- **Operating System**: Linux

**Comment by MattGill98** [comment]
Hi @mb-dbc-dk,

I've reproduced the issue, it seems that the ConsoleHandler doesn't respect the formatter specified. I've created internal issue `PAYARA-2870` to fix it.

Kind regards,

Matt

**Comment by smillidge** [comment]
Fixed by #2873
