### ISSUE TITLE
Unsupported operation at Microprofile Config

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#2876]
Because the below method is not implemented?

https://github.com/payara/Payara/blob/43cf0c68d2d38fa6f308fd1c62fa9c3525f5aaa2/nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/InjectedPayaraConfig.java#L72-L75

**Comment by smillidge** [comment]
PAYARA-2880
