### ISSUE TITLE
Handle invalid authentication response

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#2877]
The jwt security use HttpServletRequest and HttpServletResponse directly, then when the passed token is invalid the below code sends immediately the 401 error code, using something like `HttpServletResponse response...; response.sendError(401)`.

https://github.com/payara/Payara/blob/2a2d3d997bf9320cdadc60e2a8d87431728a4794/appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTAuthenticationMechanism.java#L64-L85

Invoking `response.sendError(401)` directly i cannot do some handling in the response, using a `ContainerRequestFilter`, per example.

Now, when a `ContainerRequestFilter` invoke
```
requestContext.abortWith(Response.status(UNAUTHORIZED);
```
The server not send the response immediately, making possible the remaining filters  `ContainerRequestFilter` do some handling in the response, as add a header, per example.

Is possible do the same behavior of a `requestContext.abortWith(Response.status(UNAUTHORIZED)` in the `HttpAuthenticationMechanism` class?

**Comment by arjantijms** [comment]
Postprocessing can be done by (dynamically) adding an interceptor to the `HttpAuthenticationMechanism` bean. You can either intercept the `validateRequest` or the `secureResponse` method.

There's a bit of code needed for this, unfortunately. See

https://arjan-tijms.omnifaces.org/2017/08/dynamically-adding-interceptor-to-build.html

A future version of Payara as well as a future version of EE security (with help from an also future version of CDI) should make this easier. See for instance

* https://issues.jboss.org/browse/CDI-723
* https://github.com/eclipse-ee4j/security-api/pull/80

**Comment by arjantijms** [comment]
As a followup, in a next version of Payara we'll likely support decorators for authentication mechanisms, making that task even easier.
