### ISSUE TITLE
payara embedded/micro artifacts unresolvable in maven central repo

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#288]
It looks as if there is a slight problem with resolving the payara embedded/micro artifacts in the central repo.  While it's possible to search, find, and download the artifacts from central via the web interface, it doesn't seem possible to resolve them in maven.  I believe the issue is that the modules point to glassfish artifacts as parents, but the glassfish artifacts are not versioned the same as payara's artifacts.

To illustrate, here's an excerpt from [the full gist](https://gist.github.com/phillipross/0b0c1a71d43b3a037992):

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:get (default-cli) on project standalone-pom: Couldn't download artifact: Unable to get dependency information for fish.payara.extras:payara-micro:jar:4.1.152.1: Failed to process POM for fish.payara.extras:payara-micro:jar:4.1.152.1: Non-resolvable parent POM for fish.payara.extras:payara-micro:4.1.152.1: Could not find artifact org.glassfish.main.extras:extras:pom:4.1.152.1 in central (https://repo.maven.apache.org/maven2)`

**Comment by dmatej** [comment]
Same problem. The problem is with the parent of these artifacts - it has "Oracle's" identifiers, but Payara's version and it is not in public repos. Other dependencies can be excluded, but not the parent (and it's parents).

**Comment by pejomstd** [comment]
Same with embedded-web:
[ERROR] Failed to execute goal on project gf-runner: Could not resolve dependencies for project se.ironic:gf-runner:jar:1.0-SNAPSHOT: Failed to collect dependencies at fish.payara.extras:payara-embedded-web:jar:4.1.152.1: Failed to read artifact descriptor for fish.payara.extras:payara-embedded-web:jar:4.1.152.1: Could not find artifact org.glassfish.main.extras:extras:pom:4.1.152.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by smillidge** [comment]
We are working on it should be fixed in maven central soon

**Comment by pejomstd** [comment]
Thanks, just wanted to let give you the maven ERROR. also for the [payara-embedded-all], but you probably know that :)

**Comment by Pandrex247** [comment]
We've uploaded a new POM to maven central, so if someone can try it again and report back if it succeeds or fails we would appreciate it.

We've removed the dependencies and parent, as they shouldn't be needed (they're only needed to build the JAR).

I've tested it myself by removing my maven repository and running a project with _payara-embedded-all_ as a dependency, and it worked, but a second test by someone outside of the Payara team would be appreciated.

Thanks

**Comment by pejomstd** [comment]
Hi, just tried it out. Still the same error:
```
mvn clean install -U
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gf-runner 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/glassfish/main/extras/extras/4.1.152.1/extras-4.1.152.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.515 s
[INFO] Finished at: 2015-05-22T19:02:13+01:00
[INFO] Final Memory: 6M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gf-runner: Could not resolve dependencies for project se.ironic:gf-runner:jar:1.0-SNAPSHOT: Failed to collect dependencies at fish.payara.extras:payara-embedded-all:jar:4.1.152.1: Failed to read artifact descriptor for fish.payara.extras:payara-embedded-all:jar:4.1.152.1: Could not find artifact org.glassfish.main.extras:extras:pom:4.1.152.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by pejomstd** [comment]
My dependency is:
```
<dependency>
            <groupId>fish.payara.extras</groupId>
            <artifactId>payara-embedded-all</artifactId>
            <version>4.1.152.1</version>
            <type>jar</type>
        </dependency>
```

**Comment by pejomstd** [comment]
Had to remove ./fish/ under "repository/org" in my local repository, then it seams to work.
Thanks for a quick solution to this :)

**Comment by smillidge** [comment]
yeah we haven't changed the version number so you will need to delete any locally downloaded artefacts.

**Comment by phillipross** [comment]
It resolves perfectly now.  Thanks!
