### ISSUE TITLE
create-jms-resource fails with exception on Linux

### ISSUE THREAD

**Issue by tivanacc** [payara/Payara#2880]
# Description #
----------

The asadmin create-jms-resource command fails to create the JMS Connection Factory and topic resource in Payara 4.1.2.181 on Linux.
Note: the same command runs successfully on Windows.

## Expected Outcome

The asadmin commands should run successfully on Linux too and the resources JMS should be created in the Payara domain.

## Current Outcome

The asadmin create-jms-resource commands are failing with exceptions. See below.

## Steps to reproduce (Only for bug reports) 

**1 Download and extractPayara 4.1.2.181**

[Maven Central](http://search.maven.org/remotecontent?filepath=fish/payara/blue/distributions/payara/4.1.2.181/payara-4.1.2.181.zip)
    
Side-note: the Payara v4.1.2.181 README.txt starts as "Thank you for downloading Payara Blue 4.1.2.174!".  --> Wrong version number.

**2 Start the domain**

    ./asadmin start-domain payaradomain

**3 Try creating the JMS resource**

    ./asadmin create-jms-resource --restype javax.jms.ConnectionFactory jms/exampleCF
    remote failure: Unable to create connection pool.
    java.lang.ExceptionInInitializerError
    Command create-jms-resource failed.

Following I would like to create a topic JMS resource too, which then fails with another exception.

    ./asadmin create-jms-resource --restype javax.jms.Topic TOPIC
    remote failure: Unable to create admin object.
    java.lang.NoClassDefFoundError: Could not initialize class com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar
    Could not initialize class com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar
    Command create-jms-resource failed.

See the attached [server.log](https://github.com/payara/Payara/files/2123947/server.log).

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full/Blue
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
- **Operating System**: Linux

**Comment by smillidge** [comment]
Payara Blue is only for AIX environments running on IBM JDK. Can you try the normal version of Payara Server?

**Comment by tivanacc** [comment]
Could you please provide the download link to the suggested, non-Blue version of Payara 4.1.2.181?
Thank you!

**Comment by smillidge** [comment]
It's on maven central like the blue version you linked to above.

**Comment by Cousjava** [comment]
http://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/4.1.2.181/payara-4.1.2.181.zip

**Comment by tivanacc** [comment]
It works (with the non-Blue version)! Thank you for the hint!!

Further notes:
1. As I wrote above, the version is wrong in both the Blue and non-Blue README.txt.
2. I don't know how to find the non-Blue version on Maven central. Starting from the Payara site [Previous Releases](https://www.payara.fish/previous_releases), only the Blue 4.1.2.181 version can be found.
However I could download it by removing "/blue" from the above URL: http://search.maven.org/remotecontent?filepath=fish/payara/blue/distributions/payara/4.1.2.181/payara-4.1.2.181.zip -> http://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/4.1.2.181/payara-4.1.2.181.zip
