### ISSUE TITLE
Can the eclipselink  bundled with Payara be the drop in replacement of the eclipselink bundled in glassfish?

### ISSUE THREAD

**Issue by drupalspring** [payara/Payara#289]
Official glassfish 4.1 is bundled with eclipselink 2.5.2 . I upgrade the eclipselink to 2.6.0 but it has this bug (https://bugs.eclipse.org/bugs/show_bug.cgi?id=463169). 

I then try to download **Payara 4.1.152 Patch 1** and copying the following files in Payara  modules folders to the glassfish4.1 modules folder in order to upgrade to eclipselink 2.6 . Are there any side-effects if I upgrade the eclipselink in this way? I try it and it seems to work but I would like the Payara 's expert would confirm this. Thanks so much.

   org.eclipse.persistence.antlr.jar
   org.eclipse.persistence.asm.jar
   org.eclipse.persistence.core.jar
   org.eclipse.persistence.dbws.jar
   org.eclipse.persistence.jpa.jar
   org.eclipse.persistence.jpa.jpql.jar
   org.eclipse.persistence.jpa.modelgen.processor.jar
   org.eclipse.persistence.moxy.jar
   org.eclipse.persistence.oracle.jar

**Comment by smillidge** [comment]
We haven't tested it explicitly but I don't believe any core changes were made to work with EclipseLink 2.6 other than the patches we made to EclipseLink for the bug you reference and a couple of others.
