### ISSUE TITLE
Test failure "java.lang.Exception: Method testConstructorsLocation should have no parameters" on Docker image maven:slim

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#2895]
# Description #
----------

Building Payara with `mvn install` inside the Docker image `maven:slim` fails because of test failures.

## Expected Outcome

Building with `mvn install` on Docker image `maven:slim` based on a quite minimal Debian image should work, ...

## Current Outcome

... but currently fails due to

```
[INFO] Running org.glassfish.diagnostics.context.impl.ContextImplUnitTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in org.glassfish.diagnostics.context.impl.ContextImplUnitTest
[ERROR] initializationError(org.glassfish.diagnostics.context.impl.ContextImplUnitTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.Exception: Method testConstructorsLocation should have no parameters

[ERROR] initializationError(org.glassfish.diagnostics.context.impl.ContextImplUnitTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.Exception: Method testDelegationOfGet should have no parameters

[ERROR] initializationError(org.glassfish.diagnostics.context.impl.ContextImplUnitTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.Exception: Method testDelegationOfPut should have no parameters

[INFO] Running org.glassfish.diagnostics.context.impl.ContextManagerImplUnitTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s - in org.glassfish.diagnostics.context.impl.ContextManagerImplUnitTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] org.glassfish.diagnostics.context.impl.ContextImplUnitTest.initializationError(org.glassfish.diagnostics.context.impl.ContextImplUnitTest)
[ERROR]   Run 1: ContextImplUnitTest.initializationError »  Method testConstructorsLocation sho...
[ERROR]   Run 2: ContextImplUnitTest.initializationError »  Method testDelegationOfGet should h...
[ERROR]   Run 3: ContextImplUnitTest.initializationError »  Method testDelegationOfPut should h...
[INFO] 
[INFO] 
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0
```

## Steps to reproduce (Only for bug reports) 

```
sudo docker run -i -t maven:slim /bin/bash
apt-get update && apt-get install --yes git
https://github.com/payara/Payara && cd Payara
mvn --batch-mode install
```

### Samples

example output can be found at https://gitlab.com/krichter/Payara/-/jobs/76944964. There's no difference to expect between local runs of the above script or run on GitLab CI since they're both Docker based.

## Context (Optional)

Trying to track down build issues on different system in order to make Payara source builds more portable (not absolutely necessary because of snapshots, but a more diverse CI infrastructure allows to spot more issues earlier).

## Environment ##

- **Payara Version**: 5.183-SNAPSHOT
- **Edition**: ---
- **JDK Version**: OpenJDK 8
- **Operating System**: Linux
- **Database**: ---

**Comment by krichter722** [comment]
Yes, this allows to integrate into GitLab CI which uses Docker images for every CI build which makes the build much more portable (in comparison to Travis and Jenkins) and allows to detect more issues. It's not my aim to get you to use GitLab CI, it's more of a backup to investigate issues and build failures. The intention of this issue report is to bring this to the attention of the staff.

**Comment by smillidge** [comment]
I'll close this as no action is required.
