### ISSUE TITLE
Roles are lost when overriding HttpServletRequestWrapper#getUserPrincipal

### ISSUE THREAD

**Issue by ggam** [payara/Payara#2898]
# Description #
----------

When a filter sets a `HttpServletRequestWrapper` that overrides the `getUserPrincipal` method, roles are lost before entering the Servlet.

## Steps to reproduce (Only for bug reports) 

Create a dummy `HttpServletRequestWrapper` and register it via a Filter:
```
public class TestHttpServletRequestWrapper extends HttpServletRequestWrapper {

    public TestHttpServletRequestWrapper(HttpServletRequest request) {
        super(request);
    }

    @Override
    public Principal getUserPrincipal() {
        Subject subject = JACC.getSubject();
        
        return new CallerPrincipal("¿¿¿¿????");
    }

}
```

J2EEInstanceListener will detect the User principal has changed and will try to propagate the change to the Subject:
https://github.com/payara/Payara/blob/master/appserver/web/web-glue/src/main/java/com/sun/web/server/J2EEInstanceListener.java#L219

A new Subject will be created, with only the user principal!
https://github.com/payara/Payara/blob/master/nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java#L462
https://github.com/payara/Payara/blob/master/nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java#L353

Any other Principals, like roles, are lost. Not even a JACC query will be able to handle it since the Subject has been replaced.

### Samples

Attached is a reproducer application
[reproducer.zip](https://github.com/payara/Payara/files/2134335/reproducer.zip)

## Environment ##

- **Payara Version**: 5.1.182
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Fedora

**Comment by ggam** [comment]
@arjantijms I found it while answering your mail on the EE Security list ;)

In fact, I was about to make a PR for Soteria `SubjectParser` to search for the user `Principal` on the **base** request, instead of the CDI injected one, which can be wrapped.

This is a very interesting behaviour. I was convinced JACC wouldn't see the user principal change. Is this really what we should expect from wrapping the request?

**Comment by fturizo** [comment]
@ggam, can you verify if this issue is present on the current release of Payara Server 5.x with the same reproducer sample that you provided?

**Comment by fturizo** [comment]
@ggam, can you verify that this issue is still present in the current release of Payara Server 5.x? We'll proceed to close it if we do not receive any updates soon

**Comment by fturizo** [comment]
Closing this issue as there's no response from the original user.
