### ISSUE TITLE
Logback console output wrapped by JUL

### ISSUE THREAD

**Issue by mb-dbc-dk** [payara/Payara#2899]
Output from logback (to console) is wrapped in jul log lines.
----------

When using slf4j/logback log messages lose log-level, since they're wrapped as "System.out." with level INFO.

## Expected Outcome

`{org.slf4j.Logger}.warn("tock")`
I would expect a log line formatted as defined in logback.xml. i.e.
```
2018-06-26 07:37:40.001,WARN,Ticker,__ejb-thread-pool5,Ticker,tick tock
```
sent to logstash

## Current Outcome

Output is wrapped by JUL, hence losing it's log-level (everything is INFO) when asking logstash
```
[#|2018-06-26T07:37:40.002+0200|INFO|Payara 5.182||_ThreadID=164;_ThreadName=__ejb-thread-pool5;_TimeMillis=1529991460002;_LevelValue=800;|
  2018-06-26 07:37:40.001,WARN,Ticker,__ejb-thread-pool5,Ticker,tick tock
|#]
```

## Steps to reproduce

1 -**  Build the supplied app

    unzip payara-error.zip && cd payara-error && mvn package

2 -**  Start the domain

    ./payara5/bin/asadmin start-domain --verbose

3 -**  Deploy the application 

    ./payara5/bin/asadmin deploy --contextroot / --name payara-error --force payara-error/target/payara-error-1.0-SNAPSHOT.war

4 -** Look at console output

Every 5 seconds a log line should occur

### Samples

[payara-error.zip](https://github.com/payara/Payara/files/2135718/payara-error.zip)

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: Oracle - 1.8.0_172
- **Operating System**: Linux

**Comment by mb-dbc-dk** [comment]
Having tried the same setup I used upon payara4 with

`logging.properties`: `handlers=org.slf4j.bridge.SLF4JBridgeHandler`

and a similar `logback.xml`, that logs to stdout, produces no output.

It seems like (and this is just a guess) the output of logback is then wrapped by JUL, and sent back to slf4j, and then logged to stdout, and then wrapped by JUL, and...

A flag that tells the logging system not to wrap stdout/stderr would be able to remedy this situation (I think). Or special output stream (a bypassed System.out) that can be referenced by `logback.xml` like:

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <target>Payara.realStdout</target>
        ...
    </appender>

Could also be a solution

**Comment by pdudits** [comment]
You can have a look at https://github.com/goodees/goodees/tree/master/payara-logback

That's what's working for me on Payara 4. I've also published post on [Payara blog](https://blog.payara.fish/log-directly-to-logstash-from-payara-server) that explains our logstash setup as well

**Comment by mb-dbc-dk** [comment]
I've tried the @pdudits version, which is a variant of what we did on payara4. It works great, as long as you log to a file. However our cluster environment expects log to stdout.

When enabling both the slf4j bridge and the console like this:

    asadmin set-log-attributes "handlers=org.slf4j.bridge.SLF4JBridgeHandler,java.util.logging.ConsoleHandler"

I (no surprise here) get to both the lines in a file and on the console. However if I enable console-logging in logback I get lines like these on the console (from jul.ConsoleHandler):

      10:34:24,705 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
      2018-06-28 10:34:24.939,INFO,unknown.jul.logger,RunLevelControllerThread-1530174864430,NativeMethodAccessorImpl,invoke0 10:34:24,705 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
      2018-06-28 10:34:24.946,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.939,INFO,unknown.jul.logger,RunLevelControllerThread-1530174864430,NativeMethodAccessorImpl,invoke0 10:34:24,705 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
      2018-06-28 10:34:24.958,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.946,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.939,INFO,unknown.jul.logger,RunLevelControllerThread-1530174864430,NativeMethodAccessorImpl,invoke0 10:34:24,705 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
      2018-06-28 10:34:25.005,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.958,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.946,INFO,unknown.jul.logger,logging output pump,LoggingOutputStream,log 2018-06-28 10:34:24.939,INFO,unknown.jul.logger,RunLevelControllerThread-1530174864430,NativeMethodAccessorImpl,invoke0 10:34:24,705 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
     ...pattern continues

Lines logged by logback are caught by jul, then printed and sent back into slf4j and loops back now embedded in another logback line.

**Comment by pdudits** [comment]
Ah, I see. I found this hijack System.out into j.u.l here:

https://github.com/payara/Payara/blob/c3f398b5129a943eb4a5aaa7fef922fdbf03c00f/nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java#L411

And the workaround appears to be to specify non-default j.u.l configuration via system property `java.util.logging.config.file`

https://github.com/payara/Payara/blob/c3f398b5129a943eb4a5aaa7fef922fdbf03c00f/nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java#L294

It looks that this deserves more explicit feature switch, though.

**Comment by mb-dbc-dk** [comment]
Thanks for the hint.

Your grep/find skills were obviously better than mine.

It's feels quite odd that setting the logging.properties, to the file that payara uses pr default, changes behavior... But I've managed to to get logback to send something to the console. Now I just have to deploy jars so that they're ready for logging (I'm going for the bridge solution) when logback is initialized.

Thanks for the help in locating a workaround - I agree with you a feature switch would be nice.

**Comment by smillidge** [comment]
What sort of switch would you like? Something in the admin console to not redirect System.out and System.err?

**Comment by pdudits** [comment]
Yes, I think a checkbox in Logger settings would help those people who need custom logging to console.

First attempt at naming it would be "Redirect system outputs to log", and it'd be turned on by default.

**Comment by pdudits** [comment]
@snukone yes, of course, logging.properties is the first, and mostly sufficient step - that's what Logger settings page is actually controlling.

**Comment by hcoona** [comment]
The workaround is about Payara. @pdudits, may I ask for your help on Payara Micro?

**Comment by pdudits** [comment]
@hcoona I don't experience this behavior (logback output hijacked by logger) when using Payara Micro 5.184. 

But Command line option [--logproperties](https://payara.gitbooks.io/payara-server/documentation/payara-micro/appendices/cmd-line-opts.html) can be used to set non-default logging.properties file. 

If you want to handle all of logging via logback, it will be more involved -- you need to have slf4j api, bridge and logback expanded in resulting .jar file along the bootstrap code.
