### ISSUE TITLE
Payara CDI Remote Events in EAR

### ISSUE THREAD

**Issue by mreppe** [payara/Payara#2927]
# Description #

EAR projects does not receive payara cdi remote events. War files without any ejb in the project also does not receive payara cdi remote events. If i test the same projects in Payara 4 all events are received.

## Expected Outcome
Info:   Sending payload: \<uuid>
Info:   ReceiverWarWithEJB - RemoteEventReceiver.receiveEvent payload: \<uuid>
Info:   ReceiverWarWithoutEJB - RemoteEventReceiver.receiveEvent payload: \<uuid>
Info:   ReceiverEAR - RemoteEventReceiverWeb.receiveEvent payload: \<uuid>
Info:   ReceiverEAR - RemoteEventReceiverEjb.receiveEvent payload: \<uuid>

## Current Outcome
Info:   Sending payload: \<uuid>
Info:   ReceiverWarWithEJB - RemoteEventReceiver.receiveEvent payload: \<uuid>

## Steps to reproduce
Clone git repository: https://github.com/mreppe/payara5-remote-cdi-events
Deploy applications:
* RemoteEventSender
* ReceiverWarWithEJB
* ReceiverWarWithoutEJB
* ReceiverEAR

Execute command: curl http://localhost:8080/RemoteEventSender/resources/test

## Environment ##

- **Payara Version**: 5.182 (standard configuration, domain production)
- **Edition**: Full
- **JDK Version**: 1.8.0_171
- **Operating System**: Ubuntu 16.04

**Comment by smillidge** [comment]
Thanks for the test case. I can't reproduce this on the latest master. I ran the RemoteEventSender in Payara Micro the ReceiverEAR on the DAS and ReceiverWAR on another Payara Micro
```
Sending payload: 5ac7610d-2858-4914-8103-647732d57dbe
ReceiverEAR - RemoteEventReceiverWeb.receiveEvent payload: 5ac7610d-2858-4914-8103-647732d57dbe
ReceiverWarWithoutEJB - RemoteEventReceiver.receiveEvent payload: 5ac7610d-2858-4914-8103-647732d57dbe
```

**Comment by smillidge** [comment]
I also deployed all the applications on the same DAS server
```
[#|2018-09-02T21:40:03.345+0100|INFO|Payara 5.184-SNAPSHOT||_ThreadID=43;_ThreadName=http-thread-pool::http-listener-1(4);_TimeMillis=1535920803345;_LevelValue=800;|
  Sending payload: 1de05e78-e8a3-45f0-966c-8d4aa95c9bae|#]

[#|2018-09-02T21:40:03.353+0100|INFO|Payara 5.184-SNAPSHOT||_ThreadID=320;_ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-4;_TimeMillis=1535920803353;_LevelValue=800;|
  ReceiverEAR - RemoteEventReceiverEjb.receiveEvent payload: 1de05e78-e8a3-45f0-966c-8d4aa95c9bae|#]

[#|2018-09-02T21:40:03.353+0100|INFO|Payara 5.184-SNAPSHOT||_ThreadID=321;_ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-5;_TimeMillis=1535920803353;_LevelValue=800;|
  ReceiverWarWithoutEJB - RemoteEventReceiver.receiveEvent payload: 1de05e78-e8a3-45f0-966c-8d4aa95c9bae|#]

[#|2018-09-02T21:40:03.353+0100|INFO|Payara 5.184-SNAPSHOT||_ThreadID=320;_ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-4;_TimeMillis=1535920803353;_LevelValue=800;|
  ReceiverEAR - RemoteEventReceiverWeb.receiveEvent payload: 1de05e78-e8a3-45f0-966c-8d4aa95c9bae|#]

[#|2018-09-02T21:40:03.355+0100|INFO|Payara 5.184-SNAPSHOT||_ThreadID=319;_ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-3;_TimeMillis=1535920803355;_LevelValue=800;|
  ReceiverWarWithEJB - RemoteEventReceiver.receiveEvent payload: 1de05e78-e8a3-45f0-966c-8d4aa95c9bae|#]
```

**Comment by mreppe** [comment]
@smillidge: I can't reproduce this issue on Payara 5.183. Something changed in this release that solved the issue.

**Comment by smillidge** [comment]
Thanks for confirming.
