### ISSUE TITLE
Payara docker configuration http-service error 

### ISSUE THREAD

**Issue by kdthanvi** [payara/Payara#2929]
# Description #
----------
Hello, 
I am trying to run payara-server (full, version: 171.1) in docker container.
Until now I can run payara default domain(domain1) inside the container. 
But when I am trying to enable access-logging I get error regarding "http-service".
I get the error "remote failure: No configuration found for configs.config.server-config.http-service"

asadmin command I am running : `asadmin set configs.config.server-config.http-service.access-logging-enable=true`

Also, by default this configuration is present. (can be confirmed by running `asadmin get "*" | grep access-loggin-enabled` -> this outputs `configs.config.server-config.http-service.access-logging-enabled=false` (inside container).

Also running this asadmin utility in VM(centOS 6.6) (without docker) works fine!

## Expected Outcome
After running `asadmin get configs.config.server-config.http-service.access-logging-enabled` & `asadmin set configs.config.server-config.http-service.access-logging-enabled`
it should output : 
`Command set executed successfully.`

## Current Outcome
When running the above asadmin utilities inside container(docker), gives error _remote failure: No configuration found for configs.config.server-config.http-service_

## Steps to reproduce (Only for bug reports) 
1 - change passwd, start domain, enable-secure-admin, restart-domain
`asadmin --user $ADMIN_USER --passwordfile=/opt/tmpfile change-admin-password
asadmin start-domain domain1
asadmin --user $AS_ADMIN_USER --passwordfile=/opt/.aspasswd  enable-secure-admin
asadmin  restart-domain domain1
asadmin list-domains --long`

> works fine

2 - access log config
`asadmin set configs.config.server-config.http-service.access-logging-enable=true`

> gives error

## Environment ##

- **Payara Version**: payara-server-4.1.1.171.1
- **Edition**: Full
- **JDK Version**:  java:8-jdk

**Comment by MattGill98** [comment]
Hi @kdthanvi,

I notice that the command you posted has several different spellings. Just to confirm, is this the exact spelling of the command you're entering?

~~~
asadmin set configs.config.server-config.http-service.access-logging-enabled=false
~~~

Kind regards,

Matt

**Comment by kdthanvi** [comment]
hello @MattGill98 ,
Thank you!
It was my silly mistake. "access-logging-enable**d**" is the correct one.
Thank you~
