### ISSUE TITLE
Context Propagation

### ISSUE THREAD

**Issue by Enigamitsuj** [payara/Payara#2936]
# Context Propagation
----------

HI, we are trying to migrate From WL to Payara and looking into implementing the Context propagation, need to be able to send something under the working context while calling EJB's

Looking into the source code I can see the ContextMap interface and few tests around it that are commented out.

Is there a way we can send something in the context while calling EJB's remotely?

**Comment by smillidge** [comment]
I see you've possibly asked this on the forum https://groups.google.com/forum/#!topic/payara-forum/gu4XtZPnqsM . I will close this as an issue
