### ISSUE TITLE
Behaviour of Auth Pass Through and ProxyHandler in EJB Container

### ISSUE THREAD

**Issue by dhutchison** [payara/Payara#2951]
# Description #
----------

Our infrastructure is such that we have: 
client -> Apache HTTPD Proxy/Load Balancer (SSL, requires Client Cert) -> GlassFish Cluster (Retaining Client Cert authentication for role based security). Currently we are required to use AJP for the link between Apache and Glassfish (soon to be Payara) to enable this. 

The "Auth Pass Through" and "Proxy Handler" settings allow a client certificate to be supplied as headers by a proxy server to an HTTP listener, which should allow us to drop the requirement for AJP. 
These settings only appear to have an effect on services running in the "Web" container, and not the "EJB" container. Most of our endpoints use the latter as they are "@Stateless" "@WebService"s.

The initial testing we did to find this was against Glassfish 3, but is still the case in the most recent Payara 4.x versions. 

I was wondering if there was a specification reason that this functionality is only available in the web container, or if it is just a long standing omission/bug? There is nothing in the documentation to indicate is a web container only feature. If it is the latter, I have traced through the code to find where the different code paths for the two containers end up and have identified at least one approach to fixing the issue. 

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full

**Comment by smillidge** [comment]
Hi I am not sure what you are trying to achieve. Do you think there is a bug in Payara? Alternatively raise the question on the forum https://groups.google.com/forum/#!forum/payara-forum or provide a test case.

**Comment by dhutchison** [comment]
Basically the “auth-pass-through-enabled” setting appears to have no effect when dealing with EJB web services. Client certificate authentication is not passed through over http. It does work however for servlets. 

To me it sounds like a bug, but it has been there since GlassFish 3 so I wondered if it was by design and just not clearly documented. 

I’ll try to knock up a test case that does not depend on having additional Apache servers in play.

**Comment by dhutchison** [comment]
This had kind of got stuck on the back of the TODO list. As it involves showing differences between how the AJP, Grizzly HTTPS and Coyote HTTPS protocol handling works I can't see any easy way to get a self contained example together (which not require lots of different server types). 

As far as I can tell that area doesn't really have much in the way of test cases that I can just piggy back on.

Before I leave this, I'll just highlight in the code what I am seeing. 

When a HTTPS request to the servlet container is processed, the code falls in to the method "org.apache.catalina.connector.CoyoteAdapter:doService" in order to use the defined "Proxy Handler". In this method there is a block commented "// START S1AS 6188932" which implements the Proxy Handler support. 

As far as I can see there is nothing to support this for code path which ends up going through the org.glassfish.webservices.EjbWebServiceServlet:service method, so when the "com.sun.enterprise.security.webservices.SecurityServiceImpl.doSecurity" method is called the Proxy Handler has not been called to pick up the proxied client certificates.

AJP however works with this code path as Grizzly has some additional logic in "org.glassfish.grizzly.http.ajp.AjpHttpRequest:getAttribute" to make the request look like it had client certificates, when in reality these have been proxied through.

I was trying to hook in to how the Grizzly Filter Chain was configured, but I found that the custom class set through "create-protocol-filter" if ignored if http settings are present for the listener.
