### ISSUE TITLE
Unsupported deployment descriptors element jaxrs-roles-allowed-enabled value false

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2955]
# Description #
----------

Documentation says it should support this deployment descriptor element.
https://docs.payara.fish/v/181/documentation/payara-server/app-deployment/descriptor-elements.html
<jaxrs-roles-allowed-enabled>
Since Payara Server 4.1.2.181; 5.181

But when i deploy the app with this glassfish-web.xml:

`<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
    <context-root>BassUtils</context-root>
    <jaxrs-roles-allowed-enabled>false</jaxrs-roles-allowed-enabled>
</glassfish-web-app>
`

## Expected Outcome

It should recognize the element and make the feature enabled / disabled. 

The same app with this element works on 5.182 payara.

## Current Outcome

`[2018-07-12T08:29:59.250+0200] [Payara 4.1] [WARNING] [AS-DEPLOYMENT-00015] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=71 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1531376999250] [levelValue: 900] [[
  Unsupported deployment descriptors element jaxrs-roles-allowed-enabled value false.]]`

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: Oracle 1.8_172
- **Operating System**: Windows / Linux
- **Database**: MySQL

**Comment by scrmtrey91** [comment]
bump

**Comment by smillidge** [comment]
Closing as this works on the latest release
