### ISSUE TITLE
openapi.scan.disable overrides servers.url

### ISSUE THREAD

**Issue by baztian** [payara/Payara#2966]
# Description #
----------

Payara together with Microprofile OpenAPI automatically introduces a section

    servers:
    - url: http://localhost:8080/
      description: Default Server.

to my openapi.yml that I'm providing directly in `META-INF` folder. I've configured

    mp.openapi.scan.disable = true

in `microprofile-config.properties`.

My service runs on port 15080 though. (Set up using `--portbase 15000`).

This bug also has an effect in SwaggerUI as it uses the port for interactive requests.

## Expected Outcome

Payara should either not add a `server` section or set the port correctly. I would prefert to not have that section automatically especially when working behind a loadbalancer etc. I would not like to have non matching ports.

## Current Outcome

Payara uses Port 8080.

## Steps to reproduce (Only for bug reports) 

1 -**  Create a domain with a different portbase

    ./$ asadmin create-domain --user admin --portbase 15000 my-domain

2 -**  Deploy the application

3 -**  Open `http://localhost:15080/openapi` in the browser.

### Samples

A sample project can be found in [Documenting RESTful APIs (by Open Liberty](https://openliberty.io/guides/microprofile-openapi.html). Clone the repo https://github.com/openliberty/guide-microprofile-openapi.git and do a `mvn package` in the `finish` folder to build the war file.

## Environment ##

- **Payara Version**: 5.182.0
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Linux

**Comment by MattGill98** [comment]
Hi @baztian,

I've created issue `PAYARA-2920` to address the hard coded value.

The `scanDisable` property is intended to disable scanning the JAX-RS annotations, so unfortunately is unable to help you in this regard. The servers block is required, so the intended way of removing the default server is unfortunately to specify a new one in your static `openapi.yml`. This will override the default server.

Kind regards,

Matt

**Comment by MattGill98** [comment]
Hi @baztian,

You're right in that the OpenAPI says the servers block is optional. However, the [MicroProfile OpenAPI spec](https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc) explicitly tests for an existing servers block. I can make an enhancement request to add a Config API option to disable adding the servers block?

Kind regards,

Matt
