### ISSUE TITLE
Severe:   http://javax.ws.rs .ProcessingException: Error deserializing object from entity stream.

### ISSUE THREAD

**Issue by AbhideepChakravarty** [payara/Payara#2971]
# Description #
Getting "Severe:   http://javax.ws.rs .ProcessingException: Error deserializing object from entity stream." on Payara 5.182

## Expected Outcome

I wrote a code which uses java ee 8 (recently made it to 8 from 7) as dependency. Works perfectly fine when I run it on Payara 4.1.2. 

The moment I run the exact same thing on Payara 5.182, it gives two problems:
1- a warning which says that it could not find  some init() in the ApplicationConfig class. But it still deploys the application.
2- The get and list flows are all working fine. But the moment I run some POST or PUT flow, which contains some JSON in the request, it fails with error: Severe:   http://javax.ws.rs .ProcessingException: Error deserializing object from entity stream.

While the same is working all fine with the Payara 4.1.2. Whats going on wrong here ??

## Steps to reproduce (Only for bug reports) 

<!-- 

Its a propriety code base. I can provide the WAR file/source code, if requested but not here as it is a public forum. 

## Environment ##

- **Payara Version**: 4.1.2 and 5.182
- **Edition**: Full and Micro
- **JDK Version**: Oracle JDK 8
- **Operating System**: Windows
- **Database**: NA

**Comment by smillidge** [comment]
Can you provide a test case?

**Comment by AbhideepChakravarty** [comment]
What do you want as test case? I can get you the WAR file if you want. But would that help?

**Comment by smillidge** [comment]
See advice here on what makes a good test case http://sscce.org we aren't going to debug your application. A simple maven project that demonstrates the Payara bug you believe to be there.

**Comment by AbhideepChakravarty** [comment]
I am not certain if a simple maven project would be able to demonstrate the issue. I will upload the WAR. Try deploying it on two different version of Payara and see the behavior. I will also attach the super pom of the web project. Let me prepare these stuffs and get back.

**Comment by smillidge** [comment]
Closed due to lack of activity

**Comment by AbhideepChakravarty** [comment]
I did some more observation and I am little more lost.

Here is the link to download the WAR: https://drive.google.com/open?id=1AYRsVRo62wwAsaSO6hmwCx57jCymqTwf

You can try running it on 5.182 and any of the post/put flow will not work. As DB is not connected, even the get flows wont work, but it will not give the error if you run it on 4.1.2.

Question is 4.1.2.181 is only available in BLUE version. I am running it on Oracle JDK, instead of IBM JDK and it works. While I wrote another EclipseLink based code, which fails and there I got to know that because it is expecting IBM JDK.

Do we have anything lower that 5.182, because this not working, which works on Oracle JDK and also has Micro version of it?

**Comment by AbhideepChakravarty** [comment]
Here is the better one.... I have added the code at https://github.com/AbhideepChakravarty/aawp-api

Its a maven project. Run it on 5.182 and run the post method.

**Comment by smillidge** [comment]
I had a quick look your war file includes many jars that are also in the server can you clean up your war dependencies in your test repo and see if you can reproduce the issue.

**Comment by AbhideepChakravarty** [comment]
Thanks for the tip. I will investigate and exclude the available jars. Did a bit and found few are coming from swagger dependency. You can ignore the WAR file as its my whole project. To make it easier and simpler. I wrote a sample app to reproduce the issue i.e. the git location I shared. Basically in case of generic bases object wrapping it is failing. Though it works fine in lower versions. Please suggest.

**Comment by smillidge** [comment]
I built the github project and it contained a lot of server jars from jersey etc.

**Comment by AbhideepChakravarty** [comment]
If you look at the pom file, I have mentioned java-ee jar dependency at with scope as PROVIDED. I think few Jersey things are coming in due to swagger dependency. Would this impact anything? Things work perfectly fine in 4.1.1.164.

**Comment by smillidge** [comment]
Yes it will impact things as Jersey is part of the server and Jersey was updated between 5.x and 4.x as Payara 5 is based on the Java EE 8 RI for JAX-RS and Payara 4.x is based on the Java EE 7 RI.

**Comment by AbhideepChakravarty** [comment]
But the problem which I am facing, looks like has nothing to do with Java EE version. Its just a simple JSON to Java object conversion. Now I have added one extra REST controller and in that there is put2Json. This one works fine but the putJson does not. Please try it after running the app to observe the behavior.

**Comment by smillidge** [comment]
However your test case still contains server jars. Can you create a test case using pure JavaEE apis?

**Comment by AbhideepChakravarty** [comment]
It was difficult for me to find and remove the jars. So I have removed the Swagger itself. Rest other dependencies I have are given with scope as PROVIDED. Now I have no jars at all in the WAR file. Still there is no difference in the behavior of the bug. Its still the same.

Now for you to simulate the bug you need to make a CURL like this:
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "job": { \ 
     "dept": "string" \ 
   }, \ 
   "name": "string" \ 
 }' 'http://localhost:8080/aawp-api/api/generic'

While the other curl which will work would be like this:
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "lastName": "string", \ 
   "firstName": "string" \ 
 }' 'http://localhost:8080/aawp-api/api/another' 

Also what is this error: Caused by: java.lang.NoSuchMethodException: com.fastserve.aawp.api.ApplicationConfig.<init>()

**Comment by felipe-alves-moraes** [comment]
I think that you are adding a new constructor in `ApplicationConfig` class, and not calling `super()`. Maybe calling super, or adding a no-arg constructor solves your problem.

**Comment by AbhideepChakravarty** [comment]
Ok. I'll try that.

**Comment by AbhideepChakravarty** [comment]
Could you guys identify the bug? Please confirm on this. This is the only reason I am stuck at 4.1.1.164 and not able to upgrade.

**Comment by felipe-alves-moraes** [comment]
Oh, I see. I tested the way you told, and could reproduce the error.
Reading the entire stack trace, I could find the problem: 
```
Caused by: javax.json.bind.JsonbException: Can't create instance of a class: class com.fastserve.aawp.api.Person, No default constructor found.
	at org.eclipse.yasson.internal.ReflectionUtils.lambda$createNoArgConstructorInstance$1(ReflectionUtils.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.yasson.internal.ReflectionUtils.createNoArgConstructorInstance(ReflectionUtils.java:202)
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:93)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:63)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:52)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:85)
	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.readFrom(JsonBindingProvider.java:99)
	... 60 more
```

I was missing the default constructors of both `Person` and `Human` classes. I added those and it worked:
```
Request:
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
"job": {
"dept": "string"
},
"name": "string"
}' 'http://localhost:8090/aawp-api-1.0.0-SNAPSHOT/api/generic'

Response
{"job":{"dept":"string"},"name":"string"}
```
Hope it helps :)

**Comment by AbhideepChakravarty** [comment]
This makes sense. But in my case I have intentionally removed the default
constructor because I do not want my b developers to create object using
default constructor. My object must be created by passing a particular
object. What can be done in this case?

**Comment by felipe-alves-moraes** [comment]
This is a question more related to the design of your application, but you can make then protected so that only class that are related to then in the hierarchy can have access to the no-arg constructor. I just tested and it works.

I tried also with the `package-private` access level, but the application complains that it cannot be found, maybe this can be achieved changing the way the default behavior of JSON-B serializes and deserializes the objects, but I didn't try it.

**Comment by AbhideepChakravarty** [comment]
Ok. How it is working in your previous version of application server. Try
deploying it on 4.1.1.164 and it will work like charm.

Why is this difference?

**Comment by felipe-alves-moraes** [comment]
Probably because of the new JSON-B Api, the way that Json are serialized and deserialized now is responsibility of JSON-B, at least that's my thought.

**Comment by AbhideepChakravarty** [comment]
Who is writing the json B implementation for payara?

As an end user, my code can only be upgraded if I compromise on my design.
Older version works smarter than the newer version.

Or should the bug be raised against json B ??

**Comment by smillidge** [comment]
Yes it is using Yasson. 

See the Yasson documentation here about how to specify a custom constructor http://json-b.net/docs/user-guide.html#custom-instantiation

**Comment by romaneguen** [comment]
As a noob on this extended world... on my case, it was just create an empty constructor... 
then the required information is null and you could add all you wanted ( care about what you add). advanced apologies if I just add usefulness stuff... I'm learning ;)
**class**
package mispruebas.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import mispruebas.database.DatabaseClass;
import mispruebas.model.Profile;

public class ProfileService {

	
	private Map<String, Profile> profiles = DatabaseClass.getProfiles();	 
	 
	public ProfileService() {
		profiles.put("koushik", new Profile(1L,"koushik","KOUSHIK","Kothagal"));
	}

	public List<Profile> getAllProfiles(){
		return new ArrayList<Profile>(profiles.values());
	}
	
	public Profile getProfile(String profileName) {
		return profiles.get(profileName);
	}
	
	public Profile addProfile(Profile profile) {
		profile.setId(profiles.size()+1);
		profiles.put(profile.getProfileName(), profile);
		return profile;
	}
	
	public Profile updateProfile(Profile profile) {
		if(profile.getProfileName().isEmpty()) {
		return null;
		}
		profiles.put(profile.getProfileName(), profile);
		return profile;
	}
	
	public Profile removeProfile(String profileName) {				
		return profiles.remove(profileName);
	}
}
