### ISSUE TITLE
Maven -source and -javadoc release artifacts are broken

### ISSUE THREAD

**Issue by dashorst** [payara/Payara#298]
The releases of at least the payara-embedded-all and payara-embedded-web artifacts for 4.1.152.1 have empty -sources and -javadocs jar files. This hinders adoption of these artifacts as one cannot see the javadocs or step through the sources while debugging.

So for example, http://search.maven.org/remotecontent?filepath=fish/payara/extras/payara-embedded-web/4.1.152.1/payara-embedded-web-4.1.152.1-javadoc.jar is empty.

**Comment by phillipross** [comment]
+1 for this request which appears to be a duplicate of  issue  #162

**Comment by smillidge** [comment]
Hi closing as a duplicate. We'll work from #162 and I'll add javadoc to that issue.
