### ISSUE TITLE
Combining metrics annotations leads to exception

### ISSUE THREAD

**Issue by schoeffm** [payara/Payara#2991]
[metricstest.zip](https://github.com/payara/Payara/files/2231706/metricstest.zip)
# Description #
----------

Annotating a managed bean with more than one metrics annotation (i.e. `@Metered` and `@Timed`) causes a `ClassCastException`.

## Expected Outcome

My expectation was to have both types registered - one metrics-measurement for each annotation.

## Current Outcome

Well, when calling the annotated bean this leads to a `ClassCastException`.

## Steps to reproduce (Only for bug reports) 

Take the attached archive - unpack it - build and start it using:
```
mvn clean install && docker-compose build && docker-compose up -d
```
After the app was started, hit the defined endpoint:
```
curl http://localhost:8080/metricstest/api/ping
[metricstest.zip](https://github.com/payara/Payara/files/2231701/metricstest.zip)

```

### Samples

```
import org.eclipse.microprofile.metrics.annotation.Metered;
import org.eclipse.microprofile.metrics.annotation.Timed;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@ApplicationScoped
@Path("ping")
public class PingResource {

    @GET
    @Metered
    @Timed
    public String ping() {
        return "Hello World";
    }
}
```
## Context (Optional)

What I wanted to accomplish is to measure different aspects of a method execution - thus I've placed two types of metrics-annotations on top of a REST-Resource to get
1. it's execution time
2. the number of calls during app-runtim

## Environment ##

- **Payara Version**: 5.182, 4.181
- **Edition**:  Micro 
- **JDK Version**: 8 u152 - OpenJDK
- **Operating System**: Linux / Mac 
- **Database**: no DB involved

**Comment by jGauravGupta** [comment]
Issue already fixed in master PR #2886
