### ISSUE TITLE
Using metrics annotations with (Stateless) EJBs is not possible

### ISSUE THREAD

**Issue by schoeffm** [payara/Payara#2992]
# Description #
----------

Apparently, the usage of annotations like `@Metered` or `@Timed` is not possible when placing 'em on classes annotated with `@Stateless`. In some cases it's possible to replace `@Stateless` with a non-EJB annotation like i.e. `@ApplicationScoped` - that works. 
Unfortunately, for EJBs it doesn't work.

## Expected Outcome

Actually, I'm not sure if my expected behavior is backed by the [microprofile spec](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/app-programming-model.adoc#annotations):
> That implies only managed beans whose bean types are proxyable can be instrumented using the Metrics annotations.

Since in my perception an EJB is a managed bean I thought it would/should be possible to use metrics annotations with EJBs as well.

## Current Outcome

Currently calling such an EJB will cause an Exception:

```
test_1  |       ... 64 more
test_1  | Caused by: java.lang.NoSuchMethodError: fish.payara.microprofile.metrics.cdi.interceptor.MetricsInterceptor: method <init>()V not found
test_1  |       at fish.payara.microprofile.metrics.cdi.interceptor._MetricsInterceptor_Serializable.<init>(Unknown Source)
test_1  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
test_1  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
test_1  |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
test_1  |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
test_1  |       at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
test_1  |       ... 78 more

```
## Steps to reproduce (Only for bug reports) 

Load the attached archive - unpack - build and start:
```
mvn clean install && docker-compose build && docker-compose up -d
```

When the application was started - hit the endpoint using:
```
curl http://localhost:8080/metricstest/api/ping
```

### Samples
```
import org.eclipse.microprofile.metrics.annotation.Metered;

import javax.ejb.Stateless;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Stateless
@Path("ping")
public class PingResource {

    @GET
    @Metered
    public String ping() {
        return "Hello World";
    }
}
```

## Environment ##

- **Payara Version**: 4.181, 5.182
- **Edition**: Micro
- **JDK Version**: 8 u152 - OpenJDK
- **Operating System**: Linux / Mac
- **Database**: no DB involved

[metricstest.zip](https://github.com/payara/Payara/files/2234559/metricstest.zip)

**Comment by jGauravGupta** [comment]
"Metrics support for @Stateless JAX-RS resource" already fixed in master PR #2830
