### ISSUE TITLE
log4j initalization error when use log4j logging in entities

### ISSUE THREAD

**Issue by redpiranha** [payara/Payara#301]
We are using payara 4.1.151 in production for our services and having the following
log4j error in server.log:
```
SEVERE:   log4j:ERROR A "org.apache.log4j.xml.DOMConfigurator" object is not assignable to a "org.apache.log4j.spi.Configurator" variable.
SEVERE:   log4j:ERROR The class "org.apache.log4j.spi.Configurator" was loaded by
SEVERE:   log4j:ERROR [WebappClassLoader (delegate=true; repositories=WEB-INF/classes/)] whereas object of type
SEVERE:   log4j:ERROR "org.apache.log4j.xml.DOMConfigurator" was loaded by [WebappClassLoader (delegate=true; repositories=WEB-INF/classes/)].
SEVERE:   log4j:ERROR Could not instantiate configurator [org.apache.log4j.xml.DOMConfigurator].
```
When this error occures the log4j log file is never created and no log4j messages are in server.log present.
This error does not happen when we don't use log4j logging in JPA Entites.
We have created a example project without any real functionality to reproduce this error.
You can it checkout here: https://github.com/redpiranha/testservice

**Comment by davewinters** [comment]
Hi,

Thanks for the test project which I managed to use to reproduce your issue on. To prevent the log4j classloader issue above, I moved the log4j you use into the directory <PAYARA_HOME>/glassfish/domains/domain1/lib on payara 4.1.151 which is directory used to load common libraries used by your domain. Of course you should change the scope of the log4j dependency in your pom.xml to the below and rebuild the project.

 <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
            <scope>provided</scope> 
        </dependency>

Is this workaround feasible in your case??

**Comment by redpiranha** [comment]
Hi,
thank you for your reply. At the moment our solution is to avoid logging in entities. It is okay for us and we can wait for a fix. 
We had tried the possibility to move the log4j lib to the domain lib directory and we can confirm that the scope provided for log4j dependency in pom is important.
