### ISSUE TITLE
Ports ignored in deployment group

### ISSUE THREAD

**Issue by roytotal** [payara/Payara#3023]
I have a strange problem with payara 5.182 (build 303) on two independend installations. The port assignments for the HTTP-Listeners on a configuration copy are ignored. Instead I get always default values: 8080 and 8181 on my server instances. Sometimes even  twice the same port, eg 8080, 8181, 8181 on a signle instance and exactly the same values on a second instance.
(However the number of ports changes with the number of listeners.)

I expected this to behave the same as in glassfish: I set the ports in the listeners as constant values or variables and the ports on the instances are changed.

Maybe a problem with port auto assignment, that does overrun the values. Is there a way to make sure it's disabled?

Steps to reproduce:
In Admin console:
- create new Deployment group dg1
- create new Instance  i1
- change in the created configuration "i1-config" ports to 1111, 2222, etc
- add new listener with port 7777
- look at instance i1, HTTP Port(s): Still default ports (even after server restart)

**Comment by smillidge** [comment]
I think this is just an admin console bug if you are refferring to the  display in the admin console. The servers will be running on different ports.

Can you confirm that the servers are actually listening on the correct ports?

**Comment by smillidge** [comment]
Fixed by #3060
