### ISSUE TITLE
Instance System Properties

### ISSUE THREAD

**Issue by HipDragon** [payara/Payara#3033]
# Description #
----------
Adding a system property to an instance doesn't allow an application deployed to that instance to see the variable reference for that instance system property. It instead attempts to find the domain system property instead.

## Expected Outcome
Configuring a system property on an instance should over write the system property for the domain. It should also be available to reference. Link to Payara documentation that explains system property references, https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/types-of-variables.html

## Current Outcome
The domain system property is used instead of the instance system property.

## Steps to reproduce
1. Start the domain
2. Create an instance for the domain
3. Start the instance
3. Create a system property on the instance
4. Deploy an application that views a the system property, I used the <jta-data-source>${CLIENT_JTA_DATA_SOURCE}</jta-data-source> in persistence.xml which will fail to deploy when the property is improperly configured.

## Context
Trying to use ${CLIENT_JTA_DATA_SOURCE} in persistence.xml and the instance system property to define which database to connect to without recompiling the source code. Attempting to have the deployment on difference instances dictate which database the application uses.

## Environment ##

- **Payara Version**: 4.1.2.181 #badassfish (build 220)
- **Edition**: Full
- **JDK Version**: Oracle JDK 8.181
- **Operating System**:  Windows

**Comment by smillidge** [comment]
This is not reproducible.
To do what you are trying to achieve you need to go to the JVM Options for configuration used by your instance and add a JVM Option with ```-DCLIENT_JTA_DATA_SOURCE=foo``` then restart the instance
