### ISSUE TITLE
letsencrypt.py fails deploying empty war with question of whether server is up and running

### ISSUE THREAD

**Issue by Koriel** [payara/Payara#3054]
# Description #
----------

In trying to run the new Payara script to obtain a LetsEncrypt certificate, it fails immediately with a message that the deployment of an empty war has failed and questions if the server is up and running. This occurs on running the script with and without `sudo`, as shown below. 

## Expected Outcome

The expected outcome is for the Payara script to deploy the empty war and continue in the process of obtaining a LetsEncrypt certificate for installation. 

## Current Outcome

```
root@Jak:~/payara5/bin# ./asadmin start-domain
Waiting for domain1 to start .....................
Successfully started the domain : domain1
domain  Location: /root/payara5/glassfish/domains/domain1
Log File: /root/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
root@Jak:~/payara5/bin# ./letsencrypt.py -c anydomain.com
Attempting to deploy an EMPTY WAR to the ROOT context: [FAIL] Is the server up and running?
 Command '['./asadmin', 'deploy', '--name', 'le', '--force', '--contextroot', '/', PosixPath('/tmp/payara_le_war')]' returned non-zero exit status 1.
root@Jak:~/payara5/bin# sudo ./letsencrypt.py -c anydomain.com
Attempting to deploy an EMPTY WAR to the ROOT context: [FAIL] Is the server up and running?
 Command '['./asadmin', 'deploy', '--name', 'le', '--force', '--contextroot', '/', PosixPath('/tmp/payara_le_war')]' returned non-zero exit status 1.
root@Jak:~/payara5/bin# 
```
```
root@Jak:~/payara5/bin# ./asadmin list-domains
production not running
domain1 running
Command list-domains executed successfully.
```

## Steps to reproduce (Only for bug reports) 
This is currently a vanilla installation on Ubuntu 18.04, using the pre-release build of Payara from August 11th.

The war directory is not correctly create; so it is failing because the directory is empty, it is then not able to create the "WEB-INF" subdirectory, and derails the process. If I manually create the directories and skip the war creation and on failure deletion, then it correctly processes:

``` #create_le_war()
        #if deploy_war() != 0:
        #    exit(1)
``` 

```#shutil.rmtree(WEB_ROOT_PATH)```

## Environment ##

- **Payara Version**: 5.1
- **Edition**: Full 
- **JDK Version**:  8 Oracle
- **Operating System**: Linux - Ubuntu 18.04

**Comment by smillidge** [comment]
Does the script work with the domain running?
