### ISSUE TITLE
Unable to open the Server

### ISSUE THREAD

**Issue by anurag0591** [payara/Payara#3063]
Hi,

I am facing below errors after patch upgrade of our UNIX application due to which I am unable to open my server.

These errors were found while server monitoring after starting the application.
The SSL certificate has expired
Exception while loading the app
Undeployment failed for context /webdav
Undeployment failed for context /contentserver
Undeployment failed for context /sapmsg-maintenance

Please suggest here.

Thanks,
Anurag

**Comment by smillidge** [comment]
This isn't a general support forum. If you feel there is a bug in Payara Server or Payara Micro please follow the instructions for raising a GitHub issue https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

If you want support with an SLA I recommend purchasing a support contract https://www.payara.fish/support
