### ISSUE TITLE
Payara-micro 5.182 - Fail with configuration via a Java -D system property

### ISSUE THREAD

**Issue by Daniel-Dos** [payara/Payara#3080]
# Description #
when I try to run my app with Payara-micro 5.182 using microprofile config 1.3 and passing a property of the same system displays the following message in "Current Outcome" .

the same works with the 5.15 payara-micro with Microprofile 1.2

## Current Outcome

```
 java -jar --add-modules=java.se.ee MVC1.0.Ozark-microbundle.jar -Dbr.org.soujava.mongoHost=mongo
Aug 23, 2018 1:21:25 AM fish.payara.micro.impl.PayaraMicroImpl scanArgs
SEVERE: Argument(s) provided are invalid: -Dbr.org.soujava.mongoHost=mongo. Try --help for valid command options
```
## Steps to reproduce (Only for bug reports) 

 java -jar --add-modules=java.se.ee MVC1.0.Ozark-microbundle.jar -Dbr.org.soujava.mongoHost=mongo

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Micro
- **JDK Version**: 10
- **Operating System**:Linux Mint

**Comment by smillidge** [comment]
Couple of things. Payara Micro is not supported on JDK 10 yet. Second the -D system property option should become before -jar on the Java command line.

**Comment by Daniel-Dos** [comment]
wonder, thanks, I had looked at the microprofile config doc and it was after -jar.

any prediction for working for java 10?

thank you so much .
