### ISSUE TITLE
Docker secrets and @DataSourceDefinitions in Payara Micro

### ISSUE THREAD

**Issue by tofflos** [payara/Payara#3085]
# Description #
----------

I'm using the Payara Micro Docker image and injecting a Docker secret into the file `/run/secrets/database-password`. I would like to use that secret in a `@DataSourceDefinition` annotation.
```Java
@DataSourceDefinition(name = "java:app/MyDataSource",
        minPoolSize = 4,
        maxPoolSize = 8,
        className = "org.postgresql.ds.PGPoolingDataSource",
        url = "${dataSource.url}",
        user = "${dataSource.user}",
        password = "${ALIAS=dataSource.password}"
```
If I was using Payara Server I would run `asadmin --passwordfile /run/secrets/database-password create-password-alias dataSource.password` but I don't believe any of the --postbootcommandfile, --postdeploycommandfile and --prebootcommandfile options support the --passwordfile option?

I noticed there was a --secretsdir option but it seems restricted to Microprofile Config and I'm unsure how to get it from there into my `@DataSourceDefinition`.

## Expected Outcome

Perhaps make `${ALIAS=dataSource.password}` look in the --secretsdir or if it's already possible provide an example in the Payara Micro Docker image description at https://hub.docker.com/r/payara/micro?

## Current Outcome

Without a mechanism in place it becomes difficult to use Dockers recommended practices for managing secrets when connecting to datasources. All of the examples I've seen so far are either using hardcoded credentials or passing environment variables.

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Micro
- **JDK Version**: 8 u151 - OpenJDK
- **Operating System**: Linux
- **Database**:

**Comment by tofflos** [comment]
Another solution I've seen floating around is providing a non-standard CDI producer class that simplifies the mapping from Microprofile Config. Both Hammock https://github.com/hammock-project/hammock/wiki/JPA-Support and Meecrowave http://openwebbeans.apache.org/meecrowave/meecrowave-jpa/index.html do this but I'm unsure how well this would fit in with Payara.

**Comment by lprimak** [comment]
You can use environment variable instead of ```ALIAS=``` you can use ```password = "${ENV=dataSource.password}"``` or something similar

**Comment by tofflos** [comment]
I'm aware and I was able to make that work but it's less secure.

> Note: Docker secrets do not set environment variables directly. This was a conscious decision, because environment variables can unintentionally be leaked between containers (for instance, if you use --link).

Source: https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

**Comment by edthorne** [comment]
@smillidge your fix states:
> Does not support replacement using application deployed ConfigSources or properties.
Am I interpreting this correctly that I cannot use ${MPCONFIG=foo} in a `glassfish-resources.xml` file inside my WAR? I want to set data source properties based on the secrets picked up in the microprofile config.

I've got the latest bits locally and I've produced a `payara-micro.jar` for testing. The values that should be coming from the microprofile config don't appear to be used. When stepping through the code I observe a null pointer exception:
> fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getAppInfo(ConfigProviderResolverImpl.java:202)
> fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:242)
> fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:156)
> org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:93)
> org.glassfish.config.support.TranslatedConfigView.getTranslatedValue(TranslatedConfigView.java:120)

The value of the `appClassloader` of `testInfo` is `null`. This causes the second half of the check on 202 to fail with the NPE.

**Comment by smillidge** [comment]
The intention was to be able to do what you say although it was tested against an annotation rather than GlassFish resources. Looks like the PR may need more testing. The comment relates to properties also defined in the mp-config.properties file in the war or a config source defined in the war. As the secrets directory config source is built in it should work.

**Comment by smillidge** [comment]
Any chance you can point me to a github repo that demonstrates the problem?
