### ISSUE TITLE
Admin REST API: specify instance name for command: _stop-instance

### ISSUE THREAD

**Issue by bradvido** [payara/Payara#3107]
I see there is a command in the admin api:
`GET /management/domain`
shows this command available:
![image](https://user-images.githubusercontent.com/884611/44857649-df09b680-ac35-11e8-9d05-50220f8616e2.png)

But it's unclear how i specify which instance to stop.  I have two instances named:
`dev-app-node1-instanceA`
`dev-app-node1-instanceB`

Simply executing 
`POST /management/domain/_stop-instance`
Returns 400 Bad Request

I've also tried:
`POST /management/domain/_stop-instance/dev-app-node1-instanceA`
`POST /management/domain/dev-app-node1-instanceA/_stop-instance`
Both return 404 not found

I've read the docs, but they are not clear...
https://docs.payara.fish/v/181/documentation/payara-server/rest-api/rest-api-documentation.html

Any help is appreciated!

**UPDATE:**
I think the correct command is this:
`POST /management/domain/servers/server/dev-app-node1-instanceA/stop-instance`
But this also returns 400 Bad Request with no extra error info...

**UPDATE 2:**
The problem was that i was sending an empty form-data POST in Postman, which caused the 400 Bad Response.  Once i added a parameter "force=false" to the form data, it worked at this url:
`POST /management/domain/servers/server/dev-app-node1-instanceA/stop-instance`

This issue can be closed.

**Comment by smillidge** [comment]
Thanks for the information. For reference commands that start with _ tend to be internal commands
