### ISSUE TITLE
Web Admin Log details don't show Complete Message

### ISSUE THREAD

**Issue by silvafabio** [payara/Payara#3117]
# Description #
----------

On the Web Admin: Server -> General -> View Log files -> Click on details in any message -> "Complete Message" is always empty. 

## Expected Outcome

The "Complete Message" of the log entry.

## Current Outcome

The field "Complete Message" is always empty. 

## Steps to reproduce (Only for bug reports) 

1 -**  Download a fresh copy.

2 -**  Start the domain

    ./asadmin start-domain production

3 -**  Access http://localhost:4848 

4 -**  Server -> General -> View Log files -> and click on details in any message

### Samples

![screenshot_2018-09-03 log entry detail](https://user-images.githubusercontent.com/3480949/44998326-fd9be480-af8a-11e8-9174-9b3edbed1519.png)

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: java-1.8.0-openjdk-1.8.0.181-3.b13.el6_10.x86_64
- **Operating System**: CentOS release 6.4 (Final)
- **Database**: NA

**Comment by MattGill98** [comment]
Hi @silvafabio,

I can confirm this is a bug. I've created internal issue `PAYARA-3079` to address it.

Kind regards,

Matt
