### ISSUE TITLE
NoClassDefFoundError AlpnServerNegotiator

### ISSUE THREAD

**Issue by omidshapouri** [payara/Payara#3138]
Hi,
I am trying to migrate from Payara 4.181 to 5.183 by using "backup and restore domain" commands. Everything works fine, we can deploy our application on Payara 5 without any issue. 
Just noticed on startup Payara throw the following error "java.lang.NoClassDefFoundError: org/glassfish/grizzly/npn/AlpnServerNegotiator"

is there any plan to fix this issue in upcoming versions? is there any temporary workaround for fixing this issue?

Thanks

**Comment by omidshapouri** [comment]
I just upgraded JDK to 8.181, it still throws the error on startup.

**Comment by lprimak** [comment]
Then please see the -Xbootclasspath suggestion above

**Comment by mayerw** [comment]
I guess the problem is that your JRE version is not covered in the **domain.xml**.
So if you add a line like:

**<jvm-options>-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>**

it should work

**Comment by omidshapouri** [comment]
@mayerw 
Thanks for your solution.
It works and the error is gone!
