### ISSUE TITLE
unexpectedly message "No valid EE environment for injection ..."

### ISSUE THREAD

**Issue by aauras** [payara/Payara#3155]
# Description #
----------

There is a unexpectedly message "No valid EE environment for injection of org.glassfish.cdi.transaction.TransactionScopedCDIEventHelperImpl]]" in server.log when using
@TransactionScoped CDI beans within asynchronous stateless EJB.
Message is produced after execution of asynchrounous function at the end of the request.

## Expected Outcome

No such message.

## Current Outcome

 "No valid EE environment for injection of org.glassfish.cdi.transaction.TransactionScopedCDIEventHelperImpl]]" in server.log 

### Samples

I have attached a simple Eclipse project based EJB module sample application that
runs immediatly using a @Startup EJB reproducing the unexpected message.

## Context (Optional)

Wan't to use @TransactionScoped Beans for things like consistent transaction timestamps etc.

## Environment ##

- **Payara Version**: 5.182, 5.183
- **Edition**: Full
- **JDK Version**: 8 u172 OpenJDK
- **Operating System**: Windows, Linux
- **Database**:  IBM Informix 12

**Comment by lprimak** [comment]
I don't see a project attached to this... can you please attach one?

**Comment by aauras** [comment]
Here is the missing attachment:
[jee-txscope-error.zip](https://github.com/payara/Payara/files/2376031/jee-txscope-error.zip)

**Comment by MattGill98** [comment]
Hi @aauras,

Thank you for your reproducer. I can confirm this is a bug. I've created issue `PAYARA-3120` to address it.

Kind regards,

Matt

**Comment by marcreichman** [comment]
I just want to confirm this is the same bug I see? I have a CDI bean (injected with `@Inject @New`) which finds its way into a non-container managed resource (for Elasticsearch bulk processor listening). The instance itself works fine and injections are fine, but every time this non-container-managed path uses it, I see a message like the above in the log. As far as I know, what I'm doing is legal, and I'm personally involving nothing regarding transaction scoping or CDI events myself here. It's just a CDI bean instance being provided to a non-container-managed class, with methods called on it. This has worked without warning in GF 3.1.2, all Payara 4.x lines, and here in 5.183 (Oracle JDK 8u177, Windows) it's the first time we're getting a warning.

Thanks!

**Comment by lprimak** [comment]
@marcreichman Not sure your bug is the same.  Depends on the context where you use the beans.
If you are indeed doing the "legal" thing which is only to use bean instances in the threads that are managed by Payara, then it's the same bug.  However, if you are using the beans from threads started by elasticsearch or any others not started by Payara, then it's illegal and the warning is correct.
