### ISSUE TITLE
master password file locations are inconsistent

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#316]
There are various issues with the way that master passwords are handled, but addressing them requires revisiting some design goals and security guidelines.  The adherence to one of these guidelines ("never pass the master password over the wire") has created a lot of issues in the design of how the master password is managed.

Currently there are places where the asadmin documentation and glassfish security guide for v4.0 are out of sync... and thusly some source code follows one spec while other parts of the source follow the other spec.

The first actionable bug that people encounter is the following:

**BACKGROUND**

When a new domain is created, the keystore and truststore are created with the "master password" which is a well-known and documented string: changeit

When a domain or instance starts up... it validates the master password against the keystore and truststore.  It checks to see if a master-password file exists, and if it is not found, it will use the default "changeit" string for validation.  If a master password file does NOT exist, and the "changeit" validation fails, the user will be prompted to enter the master password.  The purpose of the master-password file is to provide the master password to the server (in the case where it has been changed form the default)  but without prompting the user.

The master-password file may be created during domain creation or by issuing the change-master-password command from asadmin.  The problem is that the actual assumed location of the master-password file is not the same in the case of server startup and writing to the master password file.

**SOLUTION**

Modify the source code to synchronize the location of the master-password file.

**Comment by realityforge** [comment]
+1

Fixing this would make a lot of automation tasks easier

**Comment by smillidge** [comment]
fixed by #331
