### ISSUE TITLE
Using environment variable in logging.properties

### ISSUE THREAD

**Issue by jwieser** [payara/Payara#3161]
# Description #
----------
Using environment variables in logging.properties does not work as expected.

## Expected Outcome
${ENV=...} is replaces by specified variable

## Current Outcome

Seems that the variables are ignored. Replaced ConsoleHandler with environemt variable produces ClassNotFoundExcepetion.

Setting env variables this way works great for domain.xml (using --domainconfig ...)

1 -**  Change logging.properties
handlers=${ENV=CONSOLE}

2 -**  Set variable and start payara
set CONSOLE=java.util.logging.ConsoleHandler
java -jar payara-micro-5.183.jar --logproperties ...

2 -**  Output
Can't load log handler "${ENV=CONSOLE}"
java.lang.ClassNotFoundException: ${ENV=CONSOLE}

## Context (Optional)

Like to set the log-level for my app from the env variable provided by a CI-Pipeline/Container.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Micro
- **JDK Version**: Oracle 8.172
- **Operating System**: Windows

**Comment by smillidge** [comment]
This is an enhancement request. Environment variable replacement doesn't happen everywhere in the server.

**Comment by jwieser** [comment]
Alright, thank you. Should it work with system properties?

https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html

**Comment by Ykus** [comment]
Hi,

I added into Payara this possibility to use environment variables in logging.properties.
There is a pull request.

Kind regards,

Zdeněk Soukup

**Comment by smillidge** [comment]
Thanks for the contribution
