### ISSUE TITLE
Auth realm with deployment group not used

### ISSUE THREAD

**Issue by beachmountain** [payara/Payara#3173]
# Description #
----------

An application running on an instance in a deployment group (using a specific config) cannot use a specific auth realm. It always tries to use the File Realm.

## Expected Outcome

The application should use the auth realm configured in the web.xml, or the realm set as default realm in the payara config.

## Current Outcome

The application tries to use the File realm and the instance log file gives the error message:

WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for .

## Steps to reproduce (Only for bug reports) 

A full sample is provided in the "Samples" section. Below are the main steps described.

1 -**  Create a database with tables and data for JDBC-authentication
2 -**  Create a JDBC resource and connection pool
3 -**  Create a new configuration by copying the "default-config"
4 -**  Create a JDBC auth realm in the new config
5 -**  Set the JDBC auth realm as the default realm in "Security"
6 -**  Create a resource-ref to the JDBC resource in the new configuration
7 -**  Create a new deployment group
8 -**  Create a new instance, add it to the deployment group and the local node
9 -**  Start the deployment group and instance
10 -** Deploy an application that authenticates by using the JDBC auth realm (configured in the web.xml file) to the deployment group 
11 -** Try to authenticate through the application. Authentication fails and the log shows that the File realm is used.

### Samples

[This sample](https://www.dropbox.com/s/bngfgqyvo1ck0cb/redundant-playground.zip?dl=1) contains:

* "create_and_initialize_database.sql" - Created and initializes the mysql database for JDBC authentication (mysql needs to be installed manually)
* The Maven project to build the application war for "Redundant-playground"
* "install_redundant_playground" - Bash script that sets up Payara on Ubuntu and performs all configuration and deploys the application

To authenticate go to: http://{YOUR-SERVER}/redundant-playground/ and login with user "admin" and pw "adminpassword".

Please just let me know if anything is missing or if you require more information.

## Context (Optional)

Trying to implement redundancy of our application by using two instances on different nodes and a deployment group. I am following the guide ["Creating a Simple Deployment Group"](https://blog.payara.fish/creating-a-simple-deployment-group)

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode) - Oracle
- **Operating System**: Linux (Ubuntu 18.04.1)
- **Database**: MySQL

**Comment by MattGill98** [comment]
Hi @beachmountain,

Thank you for your detailed reproducer. I ran the setup script you linked after removing the Ubuntu update and locale lines, and everything seems to work fine for me. Is there some other environment specific setting that is not included in the reproducer? Alternatively if you haven't already, try restarting the instance at the end of the script; does it work after that?

Kind regards,

Matt

**Comment by beachmountain** [comment]
Hi @MattGill98,

Thank you for taking the time to investigate this. As far as I know, I did not make any other configurations to the server. However, after creating an all-new server and running my scripts exactly as before it now (to my big surprise) works! I still do not understand what the problem was, but nevermind.

I do apologize for taking up your time with this, but I really thought it was a bug. I am relieved to find out it is not.

Best Regards
Fredrik

**Comment by MattGill98** [comment]
Hi @beachmountain,

No worries, I'm glad it's sorted for you! I'll close this issue, although feel free to reopen it if something similar occurs again.

Kind regards,

Matt
