### ISSUE TITLE
Application provided REST ExceptionMapper ist not called aynmore (perhaps due to new OpenTracing module)

### ISSUE THREAD

**Issue by jowe** [payara/Payara#3184]
# Description #
----------

Application provided REST ExceptionMapper ist not called aynmore (perhaps due to new OpenTracing module)

We use an ExceptionMapper<Throwable> and we see since 4.1.2.182 that this mapper
isn't called any more, which breaks our complete Error/Exceptionhandling.

Looking at the Payara Code Repo we see a new class: 
JaxrsContainerRequestTracingExceptionMapper implements ExceptionMapper<Throwable>
which may intefere with application exception mappers.

JAX-RS does not specify the semantic if several Mappers are available for the same type,
but I think that OpenTracing should not intefere how an application maps exceptions to Responses.

## Expected Outcome

If we define an ExceptionMapper ist must be called and exception must not be mapped
and by an internal Mapper.

## Current Outcome
Our ExceptionMapper is not called,

## Steps to reproduce (Only for bug reports) 
TBD

### Samples

TBD

## Environment ##

- **Payara Version**: 4.1.2.182
- **Edition**:  Full
- **JDK Version**: <8 OpenJDK 
- **Operating System**:  Linux 
- **Database**: Oracle

**Comment by MattGill98** [comment]
Hi @jowe,

I'm afraid that 4.1.2.182 is a customer only release, so support isn't available from GitHub. The forum for this support is through our Zendesk.

Kind regards,

Matt

**Comment by jowe** [comment]
OK – we will open a support ticket through customer.
BTW: But the issue is also existing in 5.182+
Reproducer: https://github.com/jowe/reproducer
