### ISSUE TITLE
master-password file is not created with secure file permissions on cluster nodes

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#319]
When the change-master-password command with the --savemasterpassword parameter is used on the DAS, the master-password file is created with secure file permissions:

`[payara@web01 ~]$ ls -al /home/payara/payara41/glassfish/domains/domain1/config/master-password
-rw------- 1 payara other 508 Jun  7 01:26 /home/payara/payara41/glassfish/domains/domain1/config/master-password`

But when the command is used on a cluster node, the master-password file is not created with secure permissions :broken_heart: :

`[payara@web02 ~]$ ls -al /home/payara/payara41/glassfish/nodes/web02/agent/master-password
-rw-r--r-- 1 payara other 508 Jun  7 00:35 /home/payara/payara41/glassfish/nodes/web02/agent/master-password`

**Comment by smillidge** [comment]
fixed by #331
