### ISSUE TITLE
Include dependencies in OpenAPI Document

### ISSUE THREAD

**Issue by ringmaster217** [payara/Payara#3192]
# Description #
----------

Include dependencies in OpenAPI document

## Expected Outcome

If I include a dependency that has OpenAPI-annotated classes, those should be included in the OpenAPI document that Payara creates.

## Current Outcome

Including a dependency that has OpenAPI-annotated classes does not include them in the OpenAPI document.

## Steps to reproduce (Only for bug reports) 

Deploy an application with a dependency that has OpenAPI-annotated classes

## Context (Optional)

I have a library that is shared between several applications. The only thing the library contains is a few POJOs that all of my applications use. Several of these POJOs are returned by APIs that my applications expose. I want to be able to annotate these POJOs with @Schema annotations and have them included in the OpenAPI document for each of my applications.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full/Micro
- **JDK Version**: 8 u181 - OpenJDK
- **Operating System**: Linux

**Comment by MattGill98** [comment]
Hi @ringmaster217,

Can you provide a small reproducer for this?

Kind regards,

Matt

**Comment by smillidge** [comment]
Closed due to inactivity
