### ISSUE TITLE
CDI Events in Data Grid using Payara Micro > 181 PAYARA-3143

### ISSUE THREAD

**Issue by galatent** [payara/Payara#3198]
# Description #
----------

In my application, I send/receive CDI events across a cluster of identical nodes, similar to the example given here:https://blog.payara.fish/microservice-choreography-with-the-payara-micro-clustered-cdi-event-bus
This worked under Payara Micro up to version 5.181, but the same code no longer works when deployed on versions 182 and 183.
I am using the default configuration for domain1 with each version.

## Expected Outcome

CDI Events should be sent/received across the cluster, same as in version 181, and using the default domain1 configuration.

## Current Outcome

I have not yet determined if it is the @Outbound event not being sent or the @Inbound not being received, however somewhere it no longer works as before.

## Steps to reproduce

Create an application with an Application Scoped Bean, deploy it and trigger the sendNotification method. 

```
package com.example;
import java.io.Serializable;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Event;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.RemoteEvent;

import fish.payara.micro.cdi.Inbound;
import fish.payara.micro.cdi.Outbound;

@Named
@ApplicationScoped
public class PushBean implements Serializable {
	
	private static final long serialVersionUID = 1L;
    
    @Inject
    @Outbound
    private Event<RemoteEvent> event;
    

    
    /**
     * On new local notification.
     * @param urn The URN
     */
    public void sendNotification( String urn) {
        
    	try {
        	RemoteEvent remoteEvent = new RemoteEvent();
            remoteEvent.setUrn(urn);
            
            event.fire(remoteEvent);
        }
        catch (Exception exception) {
        	
        }
        
    }
    
    /**
     * On new remote event.
     * @param remoteEvent The RemoteEvent 
     */
    public void onNewRemoteEvent(@Observes @Inbound RemoteEvent remoteEvent) {
        
    System.out.println(remoteEvent);
    }
}
```

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Micro
- **JDK Version**:  8 OpenJDK
- **Operating System**:  Linux
- **Database**:  MariaDB

**Comment by smillidge** [comment]
Can you provide a simple reproducer application that demonstrates the issue?
Have you tried with simple string events rather than POJOs?

**Comment by galatent** [comment]
[payara-micro-remote-cdi-event-demo.zip](https://github.com/payara/Payara/files/2419095/payara-micro-remote-cdi-event-demo.zip)

Hi,
Yes I have tried with string events, in the example I posted it is a simple serializable object as there is another method in the application which @Observes a string.

I have attached a sample application, it is simply a case of starting 2 instances of payara micro using mvn exec:exec. Note that in the pom.xml, the version of payara is 5.1.81, which works fine. Change this to 5.182 or 5.183 to see the issue.

**Comment by galatent** [comment]
I have tried this sample application on some of the old nightly builds to see if I could work out when this became an issue.

payara-micro-5.182-20180529.000111-67 - **throws null pointer exception on both servers**

`[2018-09-27T11:16:27.363+0100] [] [[1;91mSEVERE[0m] [] [[1;94morg.glassfish.enterprise.concurrent[0m] [tid: _ThreadID=135 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1538043387363] [levelValue: 1000] java.lang.NullPointerException`

payara-micro-5.182-20180601.000232-70 **does not work at all, no exceptions thrown** This is the behaviour in 182 and 183 releases.

**Comment by smillidge** [comment]
Thanks for the test case this is reproducible the error is because of the custom POJO a ClassNotFoundException is occurring in the depths of the CDI Event Bus and being logged at FINE level.

**Comment by galatent** [comment]
I previously said I was using a serializable object for the cluster event, as there was already an existing @Observes String event in the application which is a local (non-cluster) event and there can only be one event per type.
So I attempted refactoring the existing event, which functions correctly when using a serializable object.
This therefore meant I could change the cluster event to be a String, which worked fine. I did state earlier that this did not work, but it does now I have re-tried it.

So this is a simple workaround for me which will be fine for now, only use String for the cluster event.
Presumably using eventName might also help in my scenario, if I needed to have both events just use a Stirng.

**Comment by skonx** [comment]
I'm observing the same problem with Payara's [cdi-clustered-events](https://github.com/payara/Payara-Examples/tree/master/payara-micro/cdi-clustered-events) example. 

It works with **4.1.1.171** (micro and full) but updating the dependencies with **5.183**, the Event is sent/received only if it is a `String` and not the POJO `CustomMessage`. It's weird because `CustomMessage` implements `Serializable` ...

**Comment by skonx** [comment]
...added `--addlibs ../eventdata/target/eventdata-1.0-SNAPSHOT.jar` after `--autoBindHttp`and it works 👌

**Comment by carlbradwell17** [comment]
I have confirmed that the example application I uploaded previously does indeed work as expected on 5.184 without making any changes.
