### ISSUE TITLE
Add option to disable the Server Header

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#32]
See GLASSFISH-21160 Currently GlassFish exposes the Server: Header on all web requests with the value GlassFish Server Open Source Edition 4.1. This can only be disabled by setting the system property product.name to an empty value. Disabling of this option should be available in the administration console just like for x-PoweredBy

**Comment by smillidge** [comment]
Tentative for 4.1.152

**Comment by davewinters** [comment]
Change made for new payaradomain in #250, set to false

**Comment by OndrejM** [comment]
Still not resolved.

**Comment by MeroRai** [comment]
@OndrejM @smillidge Fix on https://github.com/payara/Payara/pull/913

**Comment by MeroRai** [comment]
In added option to disable Server Header on HTTP settings for the protocol.
