### ISSUE TITLE
Support all attribute names in set-log-attributes

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#321]
The set-log-attributes and set-log-levels is almost enough to manage the logging properties for payara instance. Unfortunately set-log-attributes restricts the allowable keys to a set of known values, thus hindering the ability to use new logging properties (i.e. we route our messages over GELF to Logstash). To set these properties we need to modify the logging properties directly on the filesystem and restart payara. It would be much easier if set-log-attributes could allow the setting of any key. As then the logging could be completely configured via asadmin.

**Comment by smillidge** [comment]
How about an asadmin command to reread logging.properties?

**Comment by realityforge** [comment]
Also possible - but it would mean that you could not remotely administer the domain unless you had ssh access to the host or at least direct access to the filesystem.

**Comment by smillidge** [comment]
Very true
