### ISSUE TITLE
MQ-JMSRA pooled connection validation broken

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#3218]
# Description #
----------

I have filed a bug with OpenMQ that the MQ-JMSRA connectors `com.sun.messaging.jms.ra.ManagedConnectionFactory` does not implement `javax.resource.spi.ValidatingManagedConnectionFactory`. This leads to pooled connections which are deemed to be valid when they may be not. The connectors-runtime `com.sun.enterprise.resource.allocator.AbstractConnectorAllocator` method shows the problem:
```
    public Set getInvalidConnections(Set connectionSet)
            throws ResourceException {
        if (mcf instanceof ValidatingManagedConnectionFactory) {
            return ((ValidatingManagedConnectionFactory) this.mcf).
                    getInvalidConnections(connectionSet);
        }
        return null;
    }
```
In case of a JMS Server restart this leads to broken connection pooled which in our case mainly hinders the JMS cache synchronization which slowly breaks application functionality.

OpenMQ-Bug: https://github.com/eclipse-ee4j/openmq/issues/422

You might want to work around this.

## Expected Outcome

Pooled JMS connections are validated.

## Current Outcome

Broken connections are kept in pool unless used.

## Steps to reproduce (Only for bug reports) 

Restart an external JMS server and watch the logs when i.e. producing eclipselink cache sync messages.

## Environment ##

- **Payara Version**: 4.x/5.x
- **Edition**: any that uses OpenMQ MQ-JMSRA
- **JDK Version**: doesn't matter
- **Operating System**: doesn't matter
- **Database**: doesn't matter

**Comment by fturizo** [comment]
@svendiedrichsen is this issue still present in the current release of Payara Server 5.x? Are you able to provide a reproducer with the correct instructions to encounter the problem?

**Comment by fturizo** [comment]
@svendiedrichsen, have you verified that the issue is still present in the current release of Payara Server 5.x? If we do not receive any updates soon we'll close this issue.

**Comment by svendiedrichsen** [comment]
Yes, please close.
