### ISSUE TITLE
Can't login to admin console with new domain

### ISSUE THREAD

**Issue by theandrewbailey** [payara/Payara#3226]
# Description #

After creating a new domain, and setting an admin username and password for it, logging into the admin server console doesn't work.

## Expected Outcome

Logging into the server console should authenticate the user and load the server console.

## Current Outcome

An HTTP 403 Forbidden page is rendered, and it is impossible to get in.

## Steps to reproduce (Only for bug reports) 

1. Open asadmin.
1. Create a domain.
1. Set an admin username and password (do not accept the defaults for this).
1. Start the domain.
1. Navigate to http://localhost:4848/ and login.

## Workaround

Accepting the default username and password will cause the console to load. This has the downsides of using the default credentials (!) and having no remote administration.

## Environment ##

- **Payara Version**: Payara Server 5.183
- **Edition**: Full
- **JDK Version**: openjdk version "1.8.0_181"
    OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
    OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- **Operating System**: Ubuntu 16.04.5 LTS

**Comment by MattGill98** [comment]
Hi @theandrewbailey,

This has been fixed in https://github.com/payara/Payara/pull/3157. I'll close this issue since it's been merged.

Kind regards,

Matt
