### ISSUE TITLE
Payara Blue download

### ISSUE THREAD

**Issue by ahamana** [payara/Payara#3238]
Please let me have a question.
At the "Supported JDKs and OSs" section of the README, it is described that IBM J9 is supported On only Payara Blue.
Where can Payara Blue be downloaded?

**Comment by khasunuma** [comment]
Payara Blue is currently available from Maven Central:
https://search.maven.org/search?q=g:fish.payara.blue.distributions

Note that Payara Blue is distribution for IBM J9 on AIX. (not for Intel x86 platform)

**Comment by ahamana** [comment]
@khasunuma Many thanks for your quick reply. I got it.
