### ISSUE TITLE
The host / application transmits sensitive information (username, passwords) in cleartext via HTTP.

### ISSUE THREAD

**Issue by guogang1990** [payara/Payara#3244]
# Description #
----------
The Openvas scan result
Summary
The host / application transmits sensitive information (username, passwords) in cleartext via HTTP.

Vulnerability Detection Result
The following input fields where identified (URL:input name):

http://172.16.42.21:4848/:j_password
Impact
An attacker could use this situation to compromise or eavesdrop on the HTTP communication between the client and the server using a man-in-the-middle attack to get access to sensitive data like usernames or passwords.

Solution
Solution type: Workaround Workaround

Enforce the transmission of sensitive data via an encrypted SSL/TLS connection. Additionally make sure the host / application is redirecting all users to the secured SSL/TLS connection before allowing to input sensitive data into the mentioned functions.

Affected Software/OS
Hosts / applications which doesn't enforce the transmission of sensitive data via an encrypted SSL/TLS connection.

Vulnerability Detection Method
Evaluate previous collected information and check if the host / application is not enforcing the transmission of sensitive data via an encrypted SSL/TLS connection.

The script is currently checking the following:

- HTTP Basic Authentication (Basic Auth)

- HTTP Forms (e.g. Login) with input field of type 'password'

Details: Cleartext Transmission of Sensitive Information via HTTP (OID: 1.3.6.1.4.1.25623.1.0.108440)

Version used: $Revision: 10726 $

Other: | https://www.owasp.org/index.php/Top_10_2013-A2-Broken_Authentication_and_Session_Management
-- | --
  | https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
  | https://cwe.mitre.org/data/definitions/319.html

## Environment ##

- **Payara Version**: 5.138
- **Edition**:  Full
- **JDK Version**: 8  1.8.0_181 - OpenJDK
- **Operating System**: Linux 
- **Database**: Oracle

## Question ##
Excuse me, I use The security problem scanned by openvas can be ignored. If you can't ignore it, you can only enable SSL. Can you disable HTTP access?
Thank you!

**Comment by MattGill98** [comment]
Hi @guogang1990,

By default, an insecure admin console only allows local connections. When secure administration is enabled, remote connections are allowed, but over a secure SSL connection. As far as I can tell, this eliminates any potential security risk. Is this conclusion mislead?

Kind regards,

Matt

**Comment by guogang1990** [comment]
thanks very much ! Matt!
