### ISSUE TITLE
@Operation(deprecated = true) is not included in yaml file

### ISSUE THREAD

**Issue by jcrochavera** [payara/Payara#3266]
Steps to reproduce it:
@GET
@Operation(deprecated = true)
public Response someEndpoint(){
....
}

The yaml file doesn't contains 
    /resource/{endpoint}:
      get:
        deprecated: true  <---- missing

Payara Micro: 5.183

**Comment by rdebusscher** [comment]
Hi Julio,

Thank you for this bug report. A fix will be available in the next release.

Best regards
Rudy

**Comment by MattGill98** [comment]
Hi Julio,

This has been fixed in https://github.com/payara/Payara/pull/3318.

Kind regards,

Matt
