### ISSUE TITLE
Netbeans Plugin creates domain having admin page that fails after login attempt.

### ISSUE THREAD

**Issue by ke5stl** [payara/Payara#3279]
I'm using NetBeans 8.2 with JDK 8 161.

I have installed the plugin for payara successfully.

I downloaded payara-5.183 and expanded the zip to a location.

I then use the NetBeans 'servers' to 'add' a new server, and populate the dialog box so that I am creating a new local domain, named domain3 (for example) (not using one of the existing domain names), and, after unchecking use the default ports, I specify both the admin and http port numbers.

I also provide an admin user / password value.

click the 'finish' button to build the domain, and i get the prompt asking whether I'd like to see the results.  it doesn't matter what you do here.  you end up with the server being added to the tree of servers, as expected.

if I then right click on the new server, and start it in debug mode, I see that the ports that it's running on are not those that I specified in the dialog box.

then, i see a dialog box asking about the login credentials, needed to check the status.  it seems that the password from the dialog is not making it to the creation process, as, it stops complaining when I blank out the password.

now, I right-click on the node in the server tree, and have it bring up the admin console web page.

the admin web page appears, and it churns around for a while, showing the initial page (before the login prompts), and after a while, I see an: http status 403 - Forbidden.

I don't even get to see the page that prompts for the login name or password.  this is true even from within a chrome incognito browser window.

now, if I stop and delete the domain, and use a command line prompt to create the domain, and then use netbeans to add the newly created domain to NetBeans Servers list, it will work fine.  I can use the netbeans functionality to bring up the server log, and, the admin web console.

so, it seems there is something getting messed up in the populating of the command line to build the domain.

I'm using windows 10, by the way, latest patches installed.

**Comment by smillidge** [comment]
Can you raise this on this repo please https://github.com/payara/ecosystem-netbeans-plugin?

Thanks
