### ISSUE TITLE
Sonar analysis stopped with nightly build on april 17th

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#3292]
# Description #
----------

The upload of sonar analysis results stopped with the nightly build on april 17th.

## Expected Outcome

Nightly builds do upload sonar analysis results to sonarcloud.io.

## Current Outcome

Nightly builds don't upload analysis results to sonarcloud.io.

## Steps to reproduce (Only for bug reports) 

Look at sonarcloud.io: https://sonarcloud.io/dashboard?id=org.glassfish.main%3Aglassfish-main-aggregator

The latest analysis result is from october 16th.

## Environment ##

Current nightly build.

**Comment by MarkWareham** [comment]
sonar machine was offline. Brought it back up. I'll keep an eye on it. Thanks for the heads up

**Comment by svendiedrichsen** [comment]
@MarkWareham Thank you for taking care of this. But it still didn't upload any analysis results since you fixed it.

**Comment by svendiedrichsen** [comment]
Found new analysis results just now. Thanks again.

**Comment by MarkWareham** [comment]
Yes, for some reason sonarcloud shows the job as cancelled, but our internal Jenkins shows a success, but luckily, it's a daily thing (on weekdays)

**Comment by svendiedrichsen** [comment]
@MarkWareham The sonarcloud build again stopped after the 17th of april.

**Comment by MarkWareham** [comment]
Thanks @svendiedrichsen . I'm looking in to it.

**Comment by MarkWareham** [comment]
Had a look at this recently. It is working again now. It was the version of maven plugin used causing the problem.
