### ISSUE TITLE
glassfish-ha module uses incorrect groupId for ha-hazelcast-store dependency

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#330]
Somewhere along the line the ha-hazelcast-store module was changed to have a different groupId but the glassfish-ha module was not updated to use the new groupId in its dependency declaration.

I'm guessing the continuous build infrastructure does not delete the local repo between builds, and, as a result, the build will happily use the already-existent artifact with the old groupId rather than failing the build.  In contrast, building from scratch with a new local repo will fail.

The pom.xml in the glassfish-ha module needs to be changed to point to the new groupId of the ha-hazelcast-store module.

A followup suggestion would be to change the continuous build process to start with a new local repo for each build so that it can catch problems like this.  The disadvantage is that each build will take longer, but it's nice to be able to catch these problems sooner than later.

**Comment by smillidge** [comment]
fixed by #331
