### ISSUE TITLE
Payara 5 with Java 11

### ISSUE THREAD

**Issue by davidmoten** [payara/Payara#3382]
I'm planning a migration to Payara (from Glassfish) once Java 11 is supported. The [support lifecycle page](https://www.payara.fish/support/support-lifecycle/) suggests that it will be supported from late 2018. Where are we at and how can I monitor progress?

**Comment by smillidge** [comment]
This is a duplicate issue #2296. Java 9 or newer is not supported currently.

Long term Java 8 support for Payara 4 and Payara 5 is available through a Payara Enterprise subscription which also includes support for Azul Zulu Open JDK.

Java 11 support also requires Java 11 support for upstream Jakarta EE components in the Eclipse EE4J project.
