### ISSUE TITLE
PAYARA 5.181 FREEZE

### ISSUE THREAD

**Issue by davidandradeb** [payara/Payara#3386]
# Description #
----------
My Application freeze after login action.

I have a JSF 2.0 Application in my server, the application works fine, but unexpectedly the application not response and not throw any error. server.log or my own log not show the exception.

Only works again if I restart payara server.

I have this code on my sessionController:

faces-config.xml
```
<managed-bean>
        <description>Session controller</description>
        <managed-bean-name>sc</managed-bean-name>
        <managed-bean-class>com.dyalogo.web.controllers.SessionController</managed-bean-class>
        <managed-bean-scope>session</managed-bean-scope>
    </managed-bean>
```

Login page:
`<p:commandButton ajax="true" value="#{msg.login}" action="#{sc.login}" update="msj"  icon="fa fa-sign-in" styleClass="" />`

Java code on SessionController.java

```
public String login() {

//Bi for login an autenticate 

if(validUser){
FacesContext.getCurrentInstance().getExternalContext().redirect("/dy/pages/ops/mainagent.jsf?faces-redirect=true");
}
}
```

The problem are in the redirect, unexpectedly the application not redirect anymore and the freeze, but if change the url manually ("/dy/pages/ops/mainagent.jsf?faces-redirect=true) the application work fine.

I try:

- No ajax.
- Set the navigation case in faces-config
- the void login method.
- with javascript.
- Change button for link.

But doesn't work !!!!!

I have other server with the same application, the same enviroment and concurrence * 3 and the issue not throw.

Please help me.

## Context 
[2018-11-06T10:22:13.177-0500] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1541517733177] [levelValue: 800] [[
  JVM invocation command line:
/usr/java/jdk1.8.0_181-amd64/bin/java
-cp
/opt/payara5/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:MaxPermSize=1g
-Xbootclasspath/p:/opt/payara5/glassfish/lib/grizzly-npn-bootstrap.jar
-Xmx4g
-Xms1g
-server
-javaagent:/opt/payara5/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/opt/payara5/glassfish/domains/domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/opt/payara5/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/opt/payara5/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/opt/payara5/glassfish/modules/endorsed:/opt/payara5/glassfish/lib/endorsed
-Djava.security.policy=/opt/payara5/glassfish/domains/domain1/config/server.policy
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/opt/payara5/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/opt/payara5/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/opt/payara5/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/java/jdk1.8.0_181-amd64/lib/ext:/usr/java/jdk1.8.0_181-amd64/jre/lib/ext:/opt/payara5/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/opt/payara5/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/opt/payara5/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara5/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/opt/payara5/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]

## Environment ##

- **Payara Version**: 5.1.8.1
- **Edition**: FULL
- **JDK Version**: jdk1.8.0_181
- **Operating System**: Linux CentOS7
- **Database**: 5.6.42-log MySQL Community Server (GPL)

**Comment by smillidge** [comment]
This is not a general support forum. You could try the Payara forum instead https://groups.google.com/forum/#!forum/payara-forum.

If you feel you have identified an issue in Payara please create a suitable test case that demonstrates the issue.
