### ISSUE TITLE
Unable to bind data grid to IP address added as loopback additional address (alias)

### ISSUE THREAD

**Issue by nopsenica** [payara/Payara#3388]
# Description #
----------

It is not possible to bind data grid to IP address added as loopback additional address (alias), like in this case:

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.9.250.160/32 brd 255.255.255.255 scope global lo:160
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

MemberAddressPicker.findAppropriateInterfaces() ignores whole loopback interface, not only 127.0.0.1/8 and ::1/128 addresses, so Payara picks other interface although "10.9.250.160" is specified in "Data Grid / Configuration / Network Interfaces".
When the same address is added as alias on other interface (like eth0), it is being picked up properly.

## Expected Outcome

To be possible to use additional IP address assigned to lo device as IP address hazelcast binds to.

Generally, MemberAddressPicker.findAppropriateInterfaces() skips virtual interfaces, too, so it is a pure luck that underlying Java class is not treating additional IP address on eth0 as "virtual interface" to skip it. I cannot see why should Payara skip virtual interfaces? 

In my opinion it is perfectly sensible to skip "ususal" IP addresses on loopback interface, but not all of them / skip complete interface.

## Current Outcome

IP address added to lo interface is ignored.

## Steps to reproduce (Only for bug reports) 

1. add any address to loopback,

ip addr add 10.0.0.1/32 dev lo

2. try to use it as hazelcast network interface address, "Data Grid / Configuration / Network Interfaces".

## Context (Optional)

In complex server scenarios, it is not uncommon to add physical network independent /32 IP addresses as aliases on loopback interface. Loopback device as destination for additional IP addresses is often preferred over physical interface because state of additional IP address does not depend on state of underlying physical interface's state. Traffic routing is solved separatelly, either by static or dynamic routes. So, server would be accessible on additional /32 address even in case that some of physical networks are down, physically or administrativelly, in case server is multi-homed (has several interfaces).

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: 8 u181 - Oracle
- **Operating System**: Linux
- **Database**: n/a

**Comment by smillidge** [comment]
I'm not sure what to do with this request. Loopback interfaces are explicitly removed from the list of interfaces to be bound to. I'm afraid the underlying Hazelcast technology is very sensitive to the IP used to create the grid. The request to join the cluster must be for the same IP address as Hazelcast is listening on. It is not enough just that the socket can be established as the routing is correct the IP names also have to match. I'm not sure even if we support what you wanted from a filtering point of view that the cluster would form.

**Comment by smillidge** [comment]
Have you explicitly set in the Data Grid configuration the IP address you wish to use?

**Comment by smillidge** [comment]
I'm going to close this as I don't think we can support this in the underlying Hazelcast implementation.
