### ISSUE TITLE
Add possibility to override provided MicroProfile io.opentracing.Tracer instance

### ISSUE THREAD

**Issue by lreimer** [payara/Payara#3405]
# Description #
----------

While trying the MicroProfile OpenTracing functionality provided by Payara, I realized that currently there is no way of plugging in a different OpenTracing tracer implementation, like Jaeger for example.

The current implementation in combination with the log or slack notifier is nice, but I really want to send the trace info to one of the currently supported tracers (see https://opentracing.io/docs/supported-tracers/) like Jaeger.

## Expected Outcome

Trace and span info can be send to any supported tracer. Alternatively, have the possibility to override the Payara internal `Tracer` implementation using an application supplied CDI `@Alternative` or `@Spezializes` tracer instance.

## Current Outcome

The internal `Tracer` instance can not be overridden via CDI , because most OpenTracing code does not use CDI but the internal lookup mechanism. The trace info can only be send to log or slack.

## Steps to reproduce (Only for bug reports) 

None. This is an enhancement request.

### Samples

A small tracing demo can be found here: https://github.com/lreimer/mp-tracing-payara-demo

## Context (Optional)

I was trying to override the internal `io.opentracing.Tracer` instance using a CDI alternative bean.
Creating a Jaeger tracer using CDI works, but the internal OpenTracing implementation basically ignores the `@Alternative` instance and always uses the internal instance.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Micro
- **JDK Version**: Zulu 8u181
- **Operating System**: CentOS base image

**Comment by rdebusscher** [comment]
Hi Mario-Leander,

An internal JIRA ticket is created for such a support. We keep you informed about the progress.

Thanks
Rudy

**Comment by lreimer** [comment]
👍 Thanks for the info.

**Comment by smillidge** [comment]
@rdebusscher what's the JIRA number I can't find it?

**Comment by rdebusscher** [comment]
@smillidge it is PAYARA-3263

**Comment by smillidge** [comment]
Thanks

**Comment by charleech** [comment]
Do we have any updated on this? Is it in any roadmap?

**Comment by rdebusscher** [comment]
@charleech It is still in the backlog, not assigned to any sprint yet.

**Comment by andrewcheelightstep** [comment]
Hi, is there any update on this? Is there any plan to do this?

**Comment by rdebusscher** [comment]
Hi @andrewcheelightstep,

This feature is in the current sprint so you can expect it to be part of 5.194 which will be released by the end of November.
