### ISSUE TITLE
@RunAs declaration in stateless session EJB ignored when triggered by an CDI Event ?

### ISSUE THREAD

**Issue by rsoika** [payara/Payara#3415]
I am using serveral EJBs in my project. Some use the @RunAs declaration like

    @Stateless
    @LocalBean
    @DeclareRoles({ "org.imixs.ACCESSLEVEL.MANAGERACCESS" })
    @RunAs("org.imixs.ACCESSLEVEL.MANAGERACCESS")
    public class MyService {
    ...
    }

I also use  the glassfish-web.xml file for  mapping a principal-name:

    <glassfish-web-app>
     ....
	<security-role-mapping>
		<role-name>org.imixs.ACCESSLEVEL.MANAGERACCESS</role-name>
		<group-name>IMIXS-WORKFLOW-Manager</group-name>
		<principal-name>WorkflowManager</principal-name>
	</security-role-mapping>
     ....
    </glassfish-web-app>

and I use the "default-role-mapping"  in the glassfish-ejb-jar.xml

	<property name="default-role-mapping" value="true">
		<description>Enable default group to role mapping</description>
	</property>
        <enterprise-beans>
          <ejb>
			<ejb-name>MyService</ejb-name>
			<principal>
				<name>WorkflowManager</name>
			</principal>
		</ejb>
        .....

Now everything works as expected - the rolemapping is fine and runas works correctly. 

but: I have one EJB which uses CDI Events like this:

    	public void onSave(@Observes MyEvent event) {
       ....

And in this case the EJB is triggered by an Event, the @runAs declaration seems to be totally ignored . So my bean does no run with the expected role.

Do you think it is possible that the CDI event ignores the princial propagation? 

The same code runs for example fine in Wildfly so it may be something in the EJB container?

## Environment ##
I am using the docker image payara/server-full:181

**Comment by rsoika** [comment]
A view month ago we hat this issue #2508 with a longish discussion. Also there CDI was the problem... It was the reason why I switched from EAR deployments to simple WAR deployments... 

But it seems like the problem of EJBs with CDI has already caught up with me again. This time in a different context.

**Comment by rdebusscher** [comment]
Hello Ralph,

The @RunAs is not used by the CDI container, only by EJB container.

When the CDI event system calls the onSave method, it is from a pure CDI context and thus does not know the EJB nature and annotations.

A possible workaround is that you put the onSave method in a CDI bean (annotated with @ApplicationScoped for example) which has the MyService injected. When you call the MyService method from this CDI bean, security should kick in as expected.

Regards
Rudy

**Comment by rsoika** [comment]
Yes the idea with a separate cdi bean is maybe the best solution. I have had also think about this way. For now, I disabled the @Runas definition by overwriting the EJB in the ejb-jar.xml descriptor when deploying on payara/glassfish. 

The thing is, that the same code runs fine on wildfly. I guess the spec is not too clear about such details in behavior. And I hope that EJB and CDI will soon become one concept and all application server deal in the same way with these concpets....

**Comment by smillidge** [comment]
I don't know what to classify this as is this a bug or a misunderstanding? @rdebusscher

**Comment by rdebusscher** [comment]
@smillidge  Not clear for me either but maybe runas should be honored by CDI, see https://docs.jboss.org/cdi/spec/1.1/cdi-spec.html#observer_method_invocation_context

> Otherwise, the observer method is called in the same transaction context, client security context and lifecycle contexts as the invocation of Event.fire() or BeanManager.fireEvent(). 

This indicates the security context is the one from the 'caller'. But

> Of course, the transaction and security contexts for a business method of a session bean also depend upon the transaction attribute and @RunAs descriptor, if any.

Indicates the runas should be honored.

**Comment by rsoika** [comment]
I will test this issue with Jakarta EE 8 and the new security annotations. I am hopeful that this Issue will disappear.

**Comment by rdebusscher** [comment]
Hi Ralph,

We have created the internal ticket PAYARA-4077 to solve the issue. Within the TCK, there is a test which verifies that the @RunAs annotation has precedence over the context at the moment of the invocation of Event.fire().

Regards
Rudy

**Comment by smillidge** [comment]
Fixed by #4210
