### ISSUE TITLE
Upgrade to latest Mojarra 'cause of mojarra Bug 4262

### ISSUE THREAD

**Issue by leeloo1** [payara/Payara#3448]
# Description #
----------

Unfortunately the following dependent mojarra bug hinders us to upgrade to the latest 5.x version of Payara:

Bug 4262 - don't restore rowIndex in UIData#invokeOnComponent, if it was not modified

https://github.com/eclipse-ee4j/mojarra/pull/4508

pull request was already merged into eclipse-ee4j:master:

https://github.com/payara/Payara/pull/3104/files

Could you please merge / update the used (payara patched) mojarra version, so that this patch is included? Hopefully 5.184 or lately 5.191 will contain this patch and allows us to do our upgrade.

- **Payara Version**: 5.18x or later
- **Edition**: Full
- **JDK Version**: JDK8
- **Operating System**: Mac

**Comment by arjantijms** [comment]
Thanks for the report. Consolidation of Mojarra 2.3.9 with the patched Mojarra 2.3.3.x Payara is currently using is definitely on the radar. The waiting is for running the TCK and the official release of 2.3.9 to Maven central.

I just integrated 2.3.9 in GF 5.1, see https://github.com/eclipse-ee4j/glassfish/commit/040dbeef11bcea599ca8fb697e7f20ce8b8a4375

The next run of the TCK should, if I'm not mistaken, test 2.3.9, which is the one but final step.

**Comment by leeloo1** [comment]
Thx Arjan...just for clarification: as far as I can see the mojarra fix is part of the 3.x milestone release and unfortunately not for 2.3.9. Or it will be picked? Or do you see the consolidation with 2.3.9 as an intermediate step and afterwards 3.x has to been done. What means probably more waiting time for Payara rollout including this fix, or? To ask even more specific; it is likely that payara 5.191 contains the fix?

**Comment by leeloo1** [comment]
Hi @arjantijms any status update on this? see my questions in my last comment.

**Comment by smillidge** [comment]
This is scheduled for 5.191 under ID PAYARA-3361

**Comment by leeloo1** [comment]
@smillidge @arjantijms just saw release 5.191. Unfortunately without very urgent and important jsf fix. Now only mojarra 2.3.9 was picked. But fix was not taken. And thus this issue remains.

**Comment by OndroMih** [comment]
@leeloo1, I see that the fix is included in Mojarra 2.3.9, which is part of Payara Server release 5.191: https://github.com/eclipse-ee4j/mojarra/compare/2.3.9-RELEASE...master

I'm closing this issue. If you think I'm wrong, please let me know.

**Comment by leeloo1** [comment]
@OndroMih yes, unfortunately I think, you are wrong. As I mentioned. You cmp. it to the Master branch. Yes, it's exists in the Mojarra master branch, but it does not exists in the Mojarra 2.3.9 version and release. And unfortunately only Mojarra 2.3.9 is included in the Payara 5.191 version. But not the fix. So this issue remains. Please reopen because its not yet fixed.

**Comment by leeloo1** [comment]
@OndroMih: please reopen.
FYI: @smillidge @arjantijms
