### ISSUE TITLE
JMS resources from glassfish-resources.xml not usable - JNDI lookup fails

### ISSUE THREAD

**Issue by poikilotherm** [payara/Payara#3449]
# Description #
----------

While trying to build a docker image for IQSS/dataverse, I experienced difficulties to deploy application scoped JMS resources. JNDI lookup fails, see logs below.

This seems to be a bug, as I am pretty sure I created a configuration inline with the Glassfish docs. Couldn't find specific docs for Payara, only some issues, that didn't seem related.

## Expected Outcome

The application should deploy (maybe fail at later stages when creating the db tables - this is a WIP).

## Current Outcome

Deployment fails with the following error:
```
dv> [#|2018-11-26T13:11:38.751+0000|SEVERE|Payara 5.183|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1543237898751;_LevelValue=1000;_MessageID=NCLS-CORE-00026;|
dv>   Exception during lifecycle processing
dv> org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/edu.harvard.iq.dataverse.ingest.IngestServiceBean/factory], Lookup: [jms/IngestQueueConnectionFactory], Type: [javax.jms.QueueConnectionFactory]
dv>     at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:896)
dv>     at com.sun.enterprise.deployment.util.ResourceValidator.validateResources(ResourceValidator.java:742)
dv>     at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:146)
dv>     at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
...
```

## Steps to reproduce (Only for bug reports) 

You can simply run `mvn -Pcontainer -DskipTests clean package docker:build docker:run` to reproduce:

```bash
git clone https://github.com/poikilotherm/dataverse.git -b 5292-small-container dataverse
cd dataverse
mvn -Pcontainer -DskipTests clean package docker:build docker:run
```
(You obviously need to be on Mac/Linux and have Git, Maven plus Docker readily available.)

## Context (Optional)

This is an effort to create a ready-to-use Docker image of Dataverse, see IQSS/dataverse#5292. I try to make the current installer obsolete and it seemed a good idea to put the JMS config within the application code.

Some links to relevant parts:

* [`IngestServiceBean.java`](https://github.com/poikilotherm/dataverse/blob/3bdb9576045078c1ece92d697f24a7d3cbc958ae/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java#L135) where the resource is looked up to be injected
* Original configuration was domain-scoped, see [`glassfish-setup.sh`](https://github.com/poikilotherm/dataverse/blob/3bdb9576045078c1ece92d697f24a7d3cbc958ae/scripts/installer/glassfish-setup.sh#L93)
* Test configuration file: [`glassfish-resources.xml`](https://github.com/poikilotherm/dataverse/blob/5292-small-container/src/main/webapp/WEB-INF/glassfish-resources.xml)

Please be aware that this Docker image already integrates payara/docker-payaraserver-full#61.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: 8 u171 OpenJDK (see Payara Docker Full)
- **Operating System**: Linux + Docker
- **Database**: PostGres

**Comment by smillidge** [comment]
try setting the system property -Ddeployment.resource.validation=false

**Comment by poikilotherm** [comment]
@smillidge that was the issue! Thank you very much, it would have taken me ages to find this.

Would you like me to add some text about this [to the docs](https://github.com/payara/Payara-Server-Documentation/tree/master/documentation/payara-server/app-deployment)? Happy to create a PR.

**Comment by smillidge** [comment]
Sorry missed your update yes please make a PR we will merge it.

**Comment by johnmanko** [comment]
> try setting the system property -Ddeployment.resource.validation=false

Can you add some clarification as to why this is needed?  What does setting this flag to `false` actually do in Payara?  In the Payara source I noticed references to both `glassfish-resources.xml` and `payara-resources.xml`; does this flag only affect the those files?  etc, etc.

I'm just trying to better understand what's happening here.  Thanks.

**Comment by johnmanko** [comment]
I've been trying to get resources in glassfish-resources.xml / payara-resources.xml to register, but even setting that flag I can't get it to work. I don't want to duplicate my problem here, but if you're interest I have to Stackoverflow question at https://stackoverflow.com/questions/56365417/payaramicro-is-not-adding-jdbc-details-in-glassfish-resources-xml-from-war

**Comment by smillidge** [comment]
It stops the check during deployment that all resources referenced by the deployment are available. The implementation is currently simplistic in that it tries to look up the referenced resource in the JNDI tree and if not present fails deployment. In the case of application scoped resources then this check can be too aggressive as the resource has not been fully deployed yet..

**Comment by rdebusscher** [comment]
Documentation PR made. https://github.com/payara/Payara-Server-Documentation/pull/686
