### ISSUE TITLE
Problems with payara-micro clustering across two different hosts.

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#348]
Following [@Pandrex247's clustering article](http://www.payara.co.uk/payara_micro_clustering) the clusterjsp.war seems to work with two different instances deployed on the same host, but attempting to deploy across two different hosts doesn't seem to work.

I've tried this across two different VMs as well as two different physical hosts (both w/o firewalling or filtering of any kind) and the instances all see the clustering join/leave activity as well as the cluster membership list which shows both instances are join.  Example:
<pre>
Members [3] {
	Member [10.1.1.148]:5901
	Member [10.1.1.148]:5902
	Member [10.1.1.146]:5901 this
}
</pre>

Unfortunately, the session replication appears to function across the instances colocated on the same host, but not to the instance on remote host.  According to netstat, the listeners all appear to be listening on all IPs (as opposed to only loopback).

I've tried both payara-micro-4.1.152.1.jar as well as a snapshot build from master branch of github repo at change 2e4e2f3d28729fc2b2fb60641ef943d7e2929287 and both exhibit the same behavior.

Is there some extra parameter that needs to be specified at the commandline?  Might this be a bug?  Any suggestion of what else to do to narrow down the problem?  Maybe should throw together a quick test that will exercise hazelcast distributed map functionality to see if the distributed cache functions across all instances.

**Comment by phillipross** [comment]
I've confirmed that hazelcast distributed collections DO function across the cluster.
I'm not sure what I'm missing, but I'll work to implement my own test for http sessions and see if maybe the problem is with clusterjsp.war.

**Comment by smillidge** [comment]
You need to use either hostnames with a common domain root to access or put a load balancer in front. Otherwise the browser won't send the jsessionid cookie.

**Comment by phillipross** [comment]
doh!  of course!  I'll try with a proxy in front so that the hostname is the same and open another issue after I can verify the cookie is being sent every time.  thanks!

**Comment by phillipross** [comment]
Just to follow up and record for posterity... I put [HAProxy](http://haproxy.org) and configured for Layer3 round robin load balancing and payara-micro carries out the session replication flawlessly.
