### ISSUE TITLE
Don't make me think about payaradomain vs. domain1 (have `asadmin start-domain` "just work")

### ISSUE THREAD

**Issue by pdurbin** [payara/Payara#349]
I just downloaded Payara for the first time (payara-4.1.152.1.zip) and ran `asadmin start-domain` like I'm use to with Glassfish.

Payara barked (maybe snapped, since it's a fish) at me with this:

```
[payara@dvn-vm1 ~]$ /home/payara/payara41/glassfish/bin/asadmin start-domain
The domains directory /home/payara/payara41/glassfish/domains
contains multiple domains.  Please specify a domain.
Available domains: payaradomain, domain1
Command start-domain failed.
```

Quickly enough I found more about "payaradomain" at http://www.payara.co.uk/whats_new_in_payara_41152 (and maybe I'll try it) but I think it would be nice to give new customers the [Don't Make Me Think](https://www.sensible.com/dmmt.html) experience of letting `asadmin start-domain` "just work" out of the box.

**Comment by phillipross** [comment]
I had similar thoughts... but not because I didn't want to think, but more to follow the "payara as a drop-in replacement for glassfish" philosophy.  I suspect that shops that have existing config management and deployment infrastructure may rely on the fact that out-of-the-box glassfish only has one domain by default... and their scripts rely on that assumption.

**Comment by peteral** [comment]
Upvote

I agree with phillipross - was exactly my case. Although it is quite simple to incorporate the new domain in the configuration scripts (delete-domain payaradomain), it gives up a (imho) huge benefit of payara - out-of-the box alternative for glassfish.

Maybe a script which would create the payaradomain on demand? Or just make payaradomain the only default domain?

**Comment by smillidge** [comment]
Need to modify the start-domain command to start domain1 if two or more domains present. Given the principals of convention over configuration.
