### ISSUE TITLE
Injection of Java EE resource in skinny EAR lib does not work

### ISSUE THREAD

**Issue by cbasener** [payara/Payara#3504]
# Description #
----------

I would like to open a new issue because I can't reopen #587.
I used the linked  [Maven project](https://drive.google.com/drive/folders/0BwKHHk1eqZaca3R3cU4xX3RDbUk) and changed small parts at a time.
Then I built the whole project and deployed both to Payara and WildFly and recorded the outcome.

## Expected Outcome

Injecting EJB resources into a EAR lib project should work according to [15.2. Injecting Java EE resources into a bean](http://docs.jboss.org/weld/reference/latest/en-US/html_single/#_injecting_java_ee_resources_into_a_bean).
This only seems to work in some cases and is quite dependent on the used application server.

### Original cleaned

- Payara -> WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [EntityManager] with qualifiers [@Any @Default]
- WildFly -> Deployment error due to non present Persistence Unit

### Original cleaned with Persistence Unit

- Payara -> org.jboss.weld.exceptions.IllegalProductException: WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [EntityManager] with qualifiers [@Any @Default]
- WildFly -> works (NewSessionBean gets loaded twice?)

### Original cleaned with Persistence Unit and newest `maven-ear-plugin`

Set version from `maven-ear-plugin` to 3.0.1
Set configuration version from 6 to 7

- Payara -> works
- WildFly -> works

### Original cleaned with Persistence Unit and newest `maven-ear-plugin` and skinnyWars

EJB-Project still present in WAR's WEB-INF/lib directory

- Payara -> works
- WildFly -> works

### Original cleaned with Persistence Unit and newest `maven-ear-plugin` and skinnyWars and extracted EJB-Interface

Extraced interface from `NewSessionBean` (renamed to `NewSessionBeanImpl`) to interface `NewSessionBean` -> `public class NewSessionBeanImpl implements NewSessionBean`.
Interface is part of `payara-587-jpaemproducer`.
Import in web project changed from ejb to lib.

- Payara -> WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [EntityManager] with qualifiers [@Any @Default]
- WildFly -> works

### Original cleaned with Persistence Unit and newest `maven-ear-plugin` and NOT skinnyWars and extracted EJB-Interface

- Payara -> org.jboss.weld.exceptions.IllegalProductException: WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [EntityManager] with qualifiers [@Any @Default]
- WildFly -> Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type NewSessionBean with qualifiers @Default
  at injection point [UnbackedAnnotatedField] @Inject test.payara._587.Payara587REST.sb

## Steps to reproduce (Only for bug reports) 

1.  Add datasource `jdbc/test` to application server and start the application server
2.  Clone the git repository
3.  cd into cloned git repo, open shell and exceute `mvn clean package`
4.  copy `payara-587-ear\target\payara-587-ear-1.0.ear`  to the corresponding autodeploy folder and wait for successful deployment
5.  Open http://localhost:8080/payara-587-web/payara/587 in a browser

### Samples

Sample project based on the original Maven project can be found here: https://github.com/cbasener/payara-587
Please notice that the project uses a real JDBC connection to a correct data source with the JNDI name jdbc/test has to be present.

## Context (Optional)

I'm trying to make the EntityManager injectable in an big EAR project which contains several WARs and EJBs.
In addition to that I want wrap the original injected EntiyManager within a proxy to perform different tasks like changing the SQL if a native query is created.

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: 8 u191 Oracle
- **Operating System**: Windows
- **Database**: SQL Server

**Comment by smillidge** [comment]
Note CDI is not well specified in behaviour when it comes to EAR files.

**Comment by fturizo** [comment]
Closing this issue as it was reported on an old unsupported version of Payara Server. Please, raise a new issue if this problem is still present in the latest release of Payara Server 5.x and provide a detailed reproducer use case so that we can analyze it.
