### ISSUE TITLE
[docs] admingui help has a small mistake

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara#352]
admingui help, specially, '/resource/common/ja/help/ref-ldaprealmprop.html' has a mistake.
It contains a following description;

> The JAAS (Java Authentication and Authorization Service) context (the identifier for the login module to use for this realm). The only valid value is `solarisRealm`.

That is a description of LDAP Realm, so it should not `solarisRealm` but `ldapRealm`. It exists not only English but also all L10N resources. 

Some Japanese GlassFish users notice me this issue and I reported GlassFish JIRA as [GLASSFISH-20877](https://java.net/jira/browse/GLASSFISH-20877). But it has not been resolved yet and used by Payara.

**Comment by khasunuma** [comment]
If admingui help files are hosted on Payara repository, please tell me where it exists. Then I will collect a mistake and send pull-request.

I have been prepared patches (Both English and all L10N resoures) to resolve this issue (when I report [GLASSFISH-20877](https://java.net/jira/browse/GLASSFISH-20877) at the same time). And I wish to adapt it to the repository if I can do.

Prease suggest me how resolve this issue.

**Comment by mikecroft** [comment]
Related internal issue `PAYARA-1004` to clone the help repo, so we can then correct it
