### ISSUE TITLE
Unable to set activate-default-principal-to-role-mapping=true in payara micro with postbootcommandfile script

### ISSUE THREAD

**Issue by maddin79** [payara/Payara#3525]
# Description

Hi payara team,

i try to get a payara micro in docker running with setting activate-default-principal-to-role-mapping to true. When i write it directly into the domain.xml it works nice, but with the --postbootcommandfile it will not be set. The fun thing is during the start the log output shows:

`[2018-12-12T14:10:17.912+0000] [] [INFO] [] [fish.payara.micro.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1544623817912] [levelValue: 800] [[`
  `Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull`
    `configs.config.server-config.security-service.activate-default-principal-to-role-mapping=true`
`]]`

The asadmin command succeed, but sets not the value in the domain.xml.
 
## Expected Outcome

`<security-service jacc="simple" activate-default-principal-to-role-mapping="true">`
`...`
`</security-service>`
## Current Outcome

`<security-service>`
`...`
`</security-service>`

## Steps to reproduce (Only for bug reports) 
Run a docker container with following command:

`docker run -v /path/to/postbootscript:/opt/postbootscript payara/micro --postbootcommandfile /opt/postbootscript`

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Micro 
- **JDK Version**: 8 u181 - OpenJDK
- **Operating System**: Linux
- **Docker Version**: 18.09.0

**Comment by maddin79** [comment]
I played around a bit and I was wrong in my initial message. The Option "activate-default-principal-to-role-mapping" is also deleted when I set it manually in a domain.xml and start the micro with this file. So it seems to be impossible to set this option. Do I miss something? Is this option not available in micro?

Best regards Martin

**Comment by smillidge** [comment]
This setting should be on by default in Payara Micro. See https://github.com/payara/Payara/blob/master/appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml#L112

**Comment by maddin79** [comment]
Thank you for the hint, I didn't know that. But it does not matter what i do, in the running configuration is the property "activate-default-principal-to-role-mapping" never set. 
When i start the server without --rootdir and look into the domain.xml in the created temp folder than the entry is missing. 
The same is when i use --rootdir and configure the domain.xml by hand. Then while starting the server, the configuration is removed. I find no possible way to start the payara micro with this option set to true. 
For trying this run the command line:
`java -jar payar-micro[Version].jar`
or 
`java -jar payara-micro[Version].jar --rootdir path/to/dir`

Any hint to a solution or a workaround would be nice.

**Comment by rdebusscher** [comment]
Hi,

The reason why the `activate-default-principal-to-role-mapping` isn't written to the domain.xml file is that the default value for this attribute is true.

When the value is equal to the default one, it is not written out in the XML.

The reason why the feature is not working as expected for you (the value for _activate-default-principal-to-role-mapping_ is true but you seem to get another result then you expected), I can't tell from the supplied info.

**Comment by maddin79** [comment]
Hello, 

sorry for the late reply and thank you for the hints. The shown error was a bit misleading, but your hint pointed us in the right direction. We are new to payara micro and still learning. 

Best regards Martin
