### ISSUE TITLE
TimerService.getAllTimers() returns Timers with nulls

### ISSUE THREAD

**Issue by atilli** [payara/Payara#3526]
# Description #
----------

@Startup
@Singleton
public class EventLogBean {
...
@Resource
TimerService timerService;
...
public List<Timer> getEJBTimers() {
        
        Collection<Timer> allTimers = timerService.getAllTimers();
        List<Timer> timerList = new ArrayList<Timer>(allTimers);
        return timerList;
 }

Fails, in null pointer (called from JSF) . 
This is little bit different from Timer Creation fails bug, that actually the timers are created and running (defined in XML), just the page to print them crashes.

Related issue:
Payara 5.184: Nonpersistent timer creation fails at startup #3491
## Expected Outcome

Should return list of timers.

## Current Outcome

Nullptr.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Ful
- **JDK Version**: 8 u181 - OpenJDK 
- **Operating System**: Linux
- **Database**: PostGres

**Comment by atilli** [comment]
Little bit jumped "the gun" but is not getAllTimers that returns null, but Timers returned are 
"some yystical instances"

ejb bean...

 public List<Timer> getEJBTimers() {
        
        Collection<Timer> allTimers = timerService.getAllTimers();
        
        List<Timer> timerList = null;
        
        if(allTimers!=null)
        {
            timerList = new ArrayList<Timer>(allTimers);
        }
        else
        {
            timerList = new ArrayList<Timer>();   
        }
        return timerList;
    }

Session bean...

 public DataModel<Timer> getTimers() {
        
        List<Timer> timerList = eventLog.getEJBTimers();
         
        DataModel<Timer> currentSnapShot = new ListDataModel<Timer>(timerList);
        
        return currentSnapShot;        
    }

and only way to get page not to crash is to remove some EL expressions...

Not even this 

#{ejbTimer != null and ejbTimer.info != null}

guards from crash in View.xhtml.

All was working fine with 5.183, otherwise I would think this is some 
mystical case of illegal sharing of objects from EJB-comain to JSF.

So Had to make this in EL code to render  array with ""NOT WORKING ON 5.184"


 <p:dataTable id="timersList" value="#{maintenanceController.timers}" var="ejbTimer" tableStyle="width:100%" styleClass="table table-nonfluid table-striped table-hover">
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.TimerListHeaderTimerInfo}"/>
                    </f:facet>
                    <h:panelGroup id="timerInfo">                        
                        <ui:remove>
                        <h:outputText rendered="#{ejbTimer != null and ejbTimer.info != null}" value="#{ejbTimer.info}"/>
                        </ui:remove>
                            <h:outputText value="NOT WORKING ON 5.184"/>                        
                    </h:panelGroup>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.TimerListHeaderNextTimeOut}"/>
                    </f:facet>
                    <h:panelGroup id="timerNext">
                        <ui:remove>
                        <h:outputText rendered="#{ejbTimer != null and ejbTimer.nextTimeout != null}" value="#{ejbTimer.nextTimeout}"/>
                        </ui:remove>
                        <h:outputText value="NOT WORKING ON 5.184"/> 
                    </h:panelGroup>
                </p:column>
             </p:dataTable>

**Comment by atilli** [comment]
Ok after really checking (sorry about above) , null comes from here, only 
option is to temporary catch it in code.

 com.sun.ejb.containers.TimerWrapper.getInfo(TimerWrapper.java:139)

**Comment by smillidge** [comment]
Thanks for the report. Any chance you could check on a pre-release build to see if the same fix for #3491 also works for this.
