### ISSUE TITLE
GlassFish/Payara L10N maintenance

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara#353]
GlassFish and Payara support L10N mesages well. Unfortunally,  some of them are not localization yet. 

GlassFish aimed at full-L10N support such as WebLogic and WebSphere. Although L10N support of GlassFish 4.x regressed from GlassFish 3.x.

I can collect L10N messages about only Japanese becaue of I'm Japanese. But I cannot collect and review other languages resoures. I hope someone translate and review L10N resource excepted Japansese (especially German).

Now I found untranslate messages JBatch configuration of admingui, and I'll collect them soon. For other languages, I want to help other members.

**Comment by khasunuma** [comment]
- Task No.1 - collect admingui L10N is almost done. I send pull request as https://github.com/payara/Payara/pull/361 .
- Task No.2 - collect admin-cli (a.k.a. asadmin) L10N is not collect it. About admin-cli, the L10N module exists complete styles. But the module, named 'server-mgmt-l10n.jar' should not in glassfish/modules but glassfish/lib. Then asadmin L10N works well. 
- Task No.3 - It is not only server-mgmt-l10n.jar, but also other module; cli-optional-l10n.jar and cli-optional.jar. We may modify process to package.

I done Task No.1, and do Task No.2 and No.3 continuously.

**Comment by mikecroft** [comment]
Fixed by #361
