### ISSUE TITLE
Memory Leak with http2 enabled on Payara 5.184 and latest glassfish

### ISSUE THREAD

**Issue by iriikoad** [payara/Payara#3537]
# Description #
----------
The Heap memory size increase until reaching the Out Of Heap Memory on default configuration on HTTS. 
Note that I have disabled "http-listener-1" for my project.

I experience this error testing the 5.183 version with different JDK 1.8 (172, 181, 191), and the latest glassfish 5 version.

## Expected Outcome

Stable memory usage

## Current Outcome

After few hours of just GET request on an text/plain resource, I have an Out Of Memory.

## Steps to reproduce

Create a java ee WAR with a simple Resource and make in running in <security-constraint> in web.xml.
@Path("test")
public class TestResource {
    @GET
    @Path("hello")
    public String getHello() {
        return "hello";
    }
}

Create a HTML/Javascript and loop to get the string on url "/myapp/webresource/test/hello" for hours!
Run "visualvm" on the JDK to see th Heap Memory increase, then the CPU reach 100% for few minutes then the server won't work anymore without crashing.

After monitoring the JVM and searching only I realised that Grizzly on HTTP2 might be the source of the bug.
Disable the HTTP2 (enable by default) with the command "asadmin" (or directly in the domain.xml) seems to fix the error:

asadmin> set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.http2-enabled=false

Maybe changing this line in the domain.xml will fix the problem too?
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: Oracke JDK 1.8 191, but confirmed on Open/Zulu JDK 1.81
- **Operating System**: WIndows 10/Ubuntu 18.10
- **Database**: MariaDB

**Comment by iriikoad** [comment]
Note that I didn't notice this error in Payara 4.1

**Comment by svendiedrichsen** [comment]
@iriikoad Could you provide some memory dump please? There is not enough information to discuss this without it.

**Comment by iriikoad** [comment]
Note: I can't be related to session as I have the issue with only 1 or 2 clients sessions max.

**Comment by svendiedrichsen** [comment]
> Note: I can't be related to session as I have the issue with only 1 or 2 clients sessions max.

This depends on how you create the requests. If you don't send send the JSESSIONID provided by the previous request you will create new sessions with every request.

**Comment by iriikoad** [comment]
Here is a simple example.
Yes, i think i had to create a session to reproduce it, with a RequestFilter, but the number of instance of HttpSession does not increase, but Http2Stream and DefaultInputBuffer do increase does.

Here is a screen shot + test war app. The HeapDump is too big to I put a snapshot.

[snapshot-1546099166828.zip](https://github.com/payara/Payara/files/2716524/snapshot-1546099166828.zip)

[domain.zip](https://github.com/payara/Payara/files/2716523/domain.zip)

![capture d ecran de 2018-12-29 16-50-55](https://user-images.githubusercontent.com/46171505/50540032-a00b5380-0b8a-11e9-9bf1-daf4a5853d1f.png)
[TestWar.zip](https://github.com/payara/Payara/files/2716522/TestWar.zip)

I hope it's enough for you.

**Comment by lprimak** [comment]
I am working on Grizzly right now (HTTP2 issues) and I can take a look at this while I am doing the HTTP2 server push work

**Comment by svendiedrichsen** [comment]
I have opened a PR to fix mentioned grizzly bug https://github.com/eclipse-ee4j/grizzly/issues/2020

**Comment by lprimak** [comment]
fantastic @svendiedrichsen 
thanks

**Comment by smillidge** [comment]
Fixed by #3897
