### ISSUE TITLE
jaxrs-roles-allowed-enabled flag does not work in .war inside .ear

### ISSUE THREAD

**Issue by fobbyal** [payara/Payara#3581]
# Description #
----------
We current have and JAX-RS .war with custom ContainerRequestFilter that utilized the @RollesAllowed feature. We need to turn off the out-of-box payara jwt authentication in order for our implementation to work. The `glassfish-web.xml` below worked when the .war is deployed by itself. However it does not work when we package the .war file inside a .ear file. 
```
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD
GlassFish Application Server 3.1 Servlet 3.0//EN"
        "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
    <!-- disable default security @RolesAllowed on payara for realm -->
    <jaxrs-roles-allowed-enabled>false</jaxrs-roles-allowed-enabled>
</glassfish-web-app>
```

## Expected Outcome
jaxrs-roles-allowed-enabled works (meaning the feature turns off when the flag is set to false) in both standalone .war file deployment as well as .ear file deployment

## Current Outcome
jaxrs-roles-allowed-enabled does not take affect if it is configured inside a .war file that is a part of a .ear file

## Environment 

- **Payara Version**: 5.x
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Ubuntu 16.04.5 LTS

**Comment by arjantijms** [comment]
I'll take a look. Not that the interpretation of `@RolesAllowed` is Payara is not really tied to JWT.

It just calls whatever authentication mechanism is installed instead. It's possible that @RolesAllowed is going to do exactly this is in JAX-RS 2.2/3.0 and/or Jakarta EE 9 as well (it was once on the roadmap for JAX-RS 2.1/EE 8).

**Comment by fobbyal** [comment]
@arjantijms Thank you for looking into this.
There are quite a few articles out there that guides towards using ContainerRequestFilter to inject custom SecurityContext and the Jersey 2 docs also mentions such method. Does this mean that it will no longer work in the future? We want the ability to deploy our code in EE containers as well as something like Grizzly.(preferably without additional configuration). Is there anything you can recommend based on these information?

**Comment by smillidge** [comment]
Can you create a test case application on GitHub that demonstrates the issue?

**Comment by fobbyal** [comment]
@smillidge yeah i'll work on it and get back here

**Comment by smillidge** [comment]
thanks

**Comment by smillidge** [comment]
Closed due to inactivity feel free to comment if you create a test case

**Comment by OndroMih** [comment]
Hi @mkarg, I've verified that the reproducer confirms the issue. We'll look into fixing this.

**Comment by mkarg** [comment]
Great, thanks! :-)
