### ISSUE TITLE
RememberMe functionality

### ISSUE THREAD

**Issue by OrestVasylyshyn** [payara/Payara#3600]
# Description #
----------

RememberMe functionality using Security API

## Expected Outcome

Creating RememberMe HTTP-cookie

## Current Outcome

When using Security API on context root of deployed application, it's working ok.
If we are addressing application over domain defined in Payara virtual server, RememberMe HTTP-cookie do not creating

### Samples

package com.jitex.security;

import java.text.MessageFormat;
import java.util.logging.Logger;
import javax.inject.Inject;
import javax.enterprise.context.ApplicationScoped;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.authentication.mechanism.http.AutoApplySession;
import javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism;
import javax.security.enterprise.authentication.mechanism.http.HttpMessageContext;
import javax.security.enterprise.authentication.mechanism.http.LoginToContinue;
import javax.security.enterprise.authentication.mechanism.http.RememberMe;
import javax.security.enterprise.credential.Credential;
import javax.security.enterprise.identitystore.IdentityStoreHandler;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import com.jitex.crm.bean.ConfigBean;

@AutoApplySession // For "Is user already logged-in?"
@RememberMe(
				cookieName = "#{self.getRememberMeCookieName(httpMessageContext)}",
				cookieMaxAgeSecondsExpression = "#{self.getRememberMeDuration(httpMessageContext)}",
				cookieSecureOnly = false,
				isRememberMeExpression = "#{self.isRememberMe(httpMessageContext)}"
)
@LoginToContinue(
				loginPage = "/signIn.xhtml?continue=true", // specify your login url
				errorPage = "",
				useForwardToLogin = false
)
@ApplicationScoped
public class FormAuthenticationMechanism implements HttpAuthenticationMechanism {
	
	private final Logger LOG = Logger.getLogger(getClass().getName());
	
	@Inject
	ConfigBean configBean;				

	@Inject
	IdentityStoreHandler identityStoreHandler;

	@Override
	public AuthenticationStatus validateRequest(HttpServletRequest req, HttpServletResponse res, HttpMessageContext context) {

		Credential credential = context.getAuthParameters().getCredential();

		if (credential != null) {
			LOG.fine(() -> MessageFormat.format("Credential {0}", credential));
			return context.notifyContainerAboutLogin(this.identityStoreHandler.validate(credential));
		} else {
			return context.doNothing();
		}	
	}
	
	@Override
	public void cleanSubject(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) {
		HttpAuthenticationMechanism.super.cleanSubject(request, response, httpMessageContext);
	}
	
	// this was called on @RememberMe annotations
	public int getRememberMeDuration(HttpMessageContext httpMessageContext) {
		return configBean.getRememberMeDuration();
	}
	
	public String getRememberMeCookieName(HttpMessageContext httpMessageContext) {
		return configBean.getRememberMeCookieName();
	}

	// this was called on @RememberMe annotations
	public Boolean isRememberMe(HttpMessageContext httpMessageContext) {
		return httpMessageContext.getAuthParameters().isRememberMe();
	}
}

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 u191 - OpenJDK
- **Operating System**: Linux
- **Database**: PostgreSQL

**Comment by smillidge** [comment]
Can you create a test case on GitHub that will make it easier to try and reproduce the issue.

**Comment by smillidge** [comment]
Closed due to inactivity. Please post again if you have a testcase and the issue will be reopened.
