### ISSUE TITLE
Repatch and Incorporate EclipseLink 2.6.1 when released

### ISSUE THREAD

**Issue by Pandrex247** [payara/Payara#363]
The GlassFish upstream Cherry-Pick #362 will bring in eclipselink 3.6.1-RC1.
We will need to reapply our patches over it.

**Comment by smillidge** [comment]
I think we should hold out for the actual 2.6.1 release as the moxy fix has been committed into the 2.6 branch but is not in this Release Candidate. Taking out of 4.1.153.release
