### ISSUE TITLE
Grizzly Version 2.3.21

### ISSUE THREAD

**Issue by tdcgithub** [payara/Payara#367]
Grizzly Version 2.3.21 contains a fix I need. Do you have any plans in integrating it to payara?

**Comment by smillidge** [comment]
It's been incorporated into the current code base and will be in the release at the end of the month.

**Comment by tdcgithub** [comment]
Great! Thanks!

**Comment by smillidge** [comment]
The latest prerelease build should have Grizzly 2.3.21 in if you want to try it out. http://www.payara.co.uk/upstream_builds
