### ISSUE TITLE
[RFE] deploy-remote-archive should support data integrity verification /CUSTCOM-102

### ISSUE THREAD

**Issue by ancoron** [payara/Payara#3670]
# Support data integrity information (at least checksums) #
----------

## Expected Outcome

The artifact downloaded from a remote source (either direct link or using Maven GAV coordinates) must be exactly the same as provided by the server and as originally uploaded to the remote server.

With Maven repositories, this is usually made available by the repository server calculating checksums at artifact upload time and follows the best-practices of checksum file naming (appending `.md5` or `.sha1` to the file name).

As a result, I would expect that the availability of these checksums be checked by the command and - if available - the downloaded data being verified for data integrity.

In case no checksums are available, a warning should be printed.

In case the integrity verification fails, any downloaded data will be deleted, no actual deployment will take place and the command fails with an appropriate error message.

## Current Outcome

The downloaded artifact may not be the one intended and is subject to at least the following unexpected modifications:

1. silent data corruption of the data stored at the server-side
2. data corruption/modification at the transport level (accidentally by a proxy or intentionally by a man-in-the-middle attack)

In the best case, this may __just__ lead to a failing deployment without any information about the reason.

In the worst case, someone deploys a malicious application instead or along with the intended one, potentially leading to arbitrary backdoors and a big security risk for whole company server environments (in many cases, server-networks __still__ trust each other at the network/IP-range level).

## Context (Optional)

As an application deployer, I want to ensure that the application version I am going to deploy is exactly the one as intentionally provided to me by the developement team/build system so that I can make sure that our application server clusters do not get compromised.

## Environment ##

- **Payara Version**: __all__
- **Edition**: __all__
- **JDK Version**: __any__
- **Operating System**: __any__
- **Database**: __n/a__

**Comment by rdebusscher** [comment]
I have created `CUSTCOM-102`.

**Comment by AlanRoth** [comment]
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
