### ISSUE TITLE
Add option for no-new-lines Base64 encoding in jdbcRealm

### ISSUE THREAD

**Issue by thorvatg** [payara/Payara#3671]
# Description #
----------
In jdbcRealm, when using `SHA-512` (or "longer") as `digest-algorithm` and `Base64` for `Encoding`, Payara uses a Base64 encoder with MIME type encoding scheme. This yields a different result from the Base64 encoder used by Wildfly, which uses the Base64 encoding scheme. The difference lies in the line breaks the MIME type encoding scheme inserts after every 76 or so characters.
To facilitate seamless migration from Wildfly, an option to use non-Mime type Base64 encoding and decoding would be welcome.

A new option in the `auth-realm` called, say, `base64-encoding-line-length` defaulting to 76 would keep backward-compatibility and add the required functionality while requiring very little code change to implement (instead of `java.util.Base64.getMimeEncoder()`, the two-parameter `java.util.Base64.getMimeEncoder(int lineLength, byte[] lineSeparator)` could be used with the corresponding decoders). A value <=0 would denote non-MIME encoding/decoding scheme, just as the first parameter is interpreted in mentioned two-param instance provider methods.

## Expected Outcome

Below is a list of examples showing how the empty string would be stored with corresponding values for the proposed new property, assuming SHA-512 is used as `digest-algorithm` :

`base64-encoding-line-length`:  default (option not mentioned)
would store the Empty String as 
`z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGl\r\nODJ6+SfaPg==`

`base64-encoding-line-length`: 76
would store the Empty String as
`z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGl\r\nODJ6+SfaPg==`

`base64-encoding-line-length`: -1
would store the Empty String as
`z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==`

`base64-encoding-line-length`: 0
would store the Empty String as
`z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==`

Not very realistic, but not hurting either:
`base64-encoding-line-length`: 20
would store the Empty String as
`z4PhNX7vuL3xVChQ1m2A\r\nB9Yg5AULVxXcg/SpIdNs\r\n6c5H0NE8XYXysP+DGNKH\r\nfuwvY7kxvUdBeoGlODJ6\r\n+SfaPg==`

## Current Outcome

Without the proposed option, the empty string password is always stored as `z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGl\r\nODJ6+SfaPg==` , assuming SHA-512 is used as `digest-algorithm` , thus it is impossible to effortlessly migrate from Wildfly with a jdbc realm with `SHA-512` (or "longer") digest algorithm, where all the password hashes are stored base64-encoded without newlines.
Migration currently requires updating the identity store and eliminating newlines from the stored password hash values.

NB: This is no issue with digest algorithms producing strings whose Base64 encoding is shorter than 76 characters as the default java.util.Base64.getMimeEncoder() currently used by Payara produces no line breaks under 76 characters.

## Environment ##

- **Payara Version**: 5.184 #badassfish (build 89)
- **Edition**: Full
- **JDK Version**: 8 u171 - Oracle
- **Operating System**: Windows
- **Database**: Oracle

**Comment by smillidge** [comment]
Thanks for the detailed description of the enhancement. We would welcome a PR.

**Comment by fturizo** [comment]
Considering that the requester fell unresponsive a while ago, we'll proceed to close this issue. Due to the nature of the enhancement, we'd recommend doing a PR with the recommended changes. Otherwise, we are afraid that we can't accomodate this reuest.
