### ISSUE TITLE
The @CircuitBreaker does not support the RequestScoped CDI bean.

### ISSUE THREAD

**Issue by charleech** [payara/Payara#3673]
# Description #
----------

The RequestScoped CDI  bean method which is annotated with `@CircuitBreaker` , the circuit state always closed.

## Expected Outcome

When the failure exceed the number identified by `requestVolumeThreshold` and `failureRatio`, the `CircuitBreakerOpenException` must be thrown.

## Current Outcome

The `CircuitBreakerOpenException` has been never thrown for RequestScoped CDI  bean.

## Steps to reproduce (Only for bug reports) 

N/A

### Samples

```java
import javax.enterprise.context.RequestScoped;
import javax.ws.rs.core.Response;

@RequestScoped
public class MyFautlTolerace implements Serializable {
    @CircuitBreaker(
        requestVolumeThreshold = 3,
        failureRatio = 0.5,
    )
    public Response alwaysFail() {
        throws new IllegalStateException("This always fails.");
    }
}
```

```java
import javax.inject.Inject;
import javax.ws.rs.GET;

@Path("/ft")
public class MyApi  implements Serializable {
    @Inject
    private MyFautlTolerace myFautlTolerace;

    @GET
    public void myCircuitBreaker() {
        this.myFautlTolerace.alwaysFail()
    }
}
```
```curl
curl -v -X GET \
http://localhost:8080/myweb/myapi/ft

# Even I try to execute the above curl for 10 times the response will be
# "java.lang.IllegalStateException: This always fails."
# The CircuitBreakerOpenException has never been thrown.
```

### The Payara Interceptors comparing

* `fish.payara.microprofile.faulttolerance.interceptors.CircuitBreakerInterceptor`

It uses the `invocationContext.getTarget()` to determine the current instance class name which will contain `$Proxy$_$$_WeldSubclass@<hashedcode>`. It will be different for every RequestScoped CDI bean invocation.

* `fish.payara.microprofile.faulttolerance.interceptors.TimeoutInterceptor`

It uses `FaultToleranceCdiUtils.getFullAnnotatedMethodSignature(...)` which split the `$Proxy$_$$_WeldSubclass` out.

## Context (Optional)

I'm trying to learn the Eclipse Microprofile Fault Tolerance with Payara Micro.

## Environment ##

From Docker `payara/micro:latest`

- **Payara Version**: `Payara Micro  5.184 #badassmicrofish (build 89)`
- **Edition**: `Micro`
- **JDK Version**: 
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (Alpine 8.181.13-r0)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
- **Operating System**: 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"
```
- **Database**:  N/A

**Comment by smillidge** [comment]
I'm not sure this makes sense as a new Request Scoped bean is created for every request so it is tricky to maintain state?

**Comment by smillidge** [comment]
You need to annotate your JAX-RS service with a CDI annotation for this to work. By default a JAXRS class is not a CDI bean t make it a CDI bean you can add `@ApplicationScoped` to your JAX-RS service.
