### ISSUE TITLE
Payara won't start in Eclipse Luna & Mars - hangs at 69%

### ISSUE THREAD

**Issue by arjantijms** [payara/Payara#370]
Using the latest version of Payara, latest version of Eclipse (Mars) and latest version of GlassFish tools at the time of writing, on e.g. OS X Yosemite, Payara won't start on Eclipse. It hangs at 69%.

Additionally, a Payara that's externally started is not recognised as being started by Eclipse (this used to be the case with older GlassFish tools versions and GlassFish 4.1)

See also https://java.net/jira/browse/GLASSFISHPLUGINS-376

**Comment by smillidge** [comment]
See https://community.oracle.com/thread/3729030 is this the same issue?

**Comment by mikecroft** [comment]
I tested with the current release of Mars and GlassFish tools on Ubuntu with no problems, so it does seem to be specific to OS X like they say in the Oracle thread.

**Comment by arjantijms** [comment]
>See https://community.oracle.com/thread/3729030 is this the same issue?

Likely, peculiar that there are comments in the forum thread but not the JIRA one, specifically this one:

>We have a fix for this issue. It will be included in the next release, which will likely go out sometime in July.

**Comment by arjantijms** [comment]
>I tested with the current release of Mars and GlassFish tools on Ubuntu with no problems, so it does seem to be specific to OS X like they say in the Oracle thread.

I'll try soon on my Ubuntu box as well. From previous incarnations of this problem I remember that it happened on some systems (independent of them being OS X or any flavour of Linux) and not on others, making it a bit difficult to reproduce.

**Comment by smillidge** [comment]
I can't speak for Oracle or it's organisation and I'm speculating a bit but I think GLASSFISHPLUGINS project was subsumed into OEPE (Oracle Enterprise Pack for Eclipse) which includes all the WebLogic tooling as well. Maybe it will be split out again. Tools is an area where we are deciding whether to find the open source projects e.g. the maven plugin and synch them onto our github or just to write our own tooling.

**Comment by arjantijms** [comment]
>Tools is an area where we are deciding whether to find the open source projects e.g. the maven plugin and synch them onto our github or just to write our own tooling.

I guess this is a tough decision. Netbeans based tooling for GlassFish has always been good from what I've heard. Excellent even. But Eclipse tooling has always been sub-optimal. It's not just the fact that it often hangs at 69%, but if it starts at all the debugger frequently doesn't work. Where "doesn't work" means a break point may be hit, but then you can't advance and it looks like the debugger either hangs or is disconnected.

On StackOverflow the main suggestion is to do everything manual (start/stop/deploy GF from command line) and then just attach Eclipse via a remote debugger. Clearly this is a very sub-optimal way of working from an IDE perspective.

**Comment by mlb1141** [comment]
Are there any updates on this issue?

**Comment by arjantijms** [comment]
@mlb1141 after the latest update upstream it seems to work again. For now.

**Comment by mlb1141** [comment]
latest update upstream of what???

**Comment by mlb1141** [comment]
I am using eclipse Mars with glassfish tools 8.2; windows 8.1; java 8.

**Comment by arjantijms** [comment]
@mib1141 The upstream of GlassFish tools. Buy maybe it just broke again if you are already using the latest version.

**Comment by mlb1141** [comment]
Sorry, I ran Glassfish instead of Payara.  It is working.  Thanks.

**Comment by mlb1141** [comment]
I am now running Payara 4.1,eclipse Mars with glassfish tools 8.2, WINDOWS 10; and java 8.  It is stopping at 69% again.

**Comment by mikecroft** [comment]
@mlb1141 Does the tooling work with earlier versions? So the only thing that's changed to make it break is that you're using the latest Payara 4.1.153?

**Comment by mlb1141** [comment]
I have never used earlier versions.  I migrated to Payara because I was having this same issue with Glassfish 4.1.  It seems to me to be intermittent.  It will work for awhile and then quit working ... back and forth. if it is going to show the problem, it always hangs at 69%.   I did change to Windows 10.

**Comment by mikecroft** [comment]
Internal issue related to this is `PAYARA-837`.

This may not be something we can do anything about, since GlassFish Tools for Eclipse is part of the OEPE suite and (apparently) no longer open.

**Comment by arjantijms** [comment]
>This may not be something we can do anything about, since GlassFish Tools for Eclipse is part of the OEPE suite and (apparently) no longer open.

That sounds somewhat troublesome, but it depends on how much GlassFish Tools is still going to be updated. I have to say that I personally haven't experienced the issue for some time, but then again it was always something that came and go anyway.

Perhaps eventually a "Payara tools" for Eclipse would be the way to go?

**Comment by mikecroft** [comment]
Yes, I think that could be the only viable way forward for this. We're keen to support the ecosystem around Payara Server, but also wary of spreading ourselves too thin and overcommitting ourselves.

The most recent sources I found were here:
https://java.net/projects/glassfishplugins/sources/svn/show/trunk/eclipse-support?rev=1607

I'm not sure how close they are to something that's even worth forking, so this could be a lot of work, unfortunately!

**Comment by arjantijms** [comment]
@mikecroft 

There's a source bundle for the most recent GlassFish tools here: http://www.oracle.com/technetwork/developer-tools/eclipse/downloads/index.html

Specifically: http://download.oracle.com/otn_software/oepe/12.2.1.3.1/neon/glassfish-tools-source-16.1.1.zip

**Comment by mikecroft** [comment]
Thanks @arjantijms! @smillidge - FYI. The source is distributed under the EPL and you don't need to accept any license terms to download.

**Comment by mikecroft** [comment]
Closing this issue since Eclipse IDE support will be worked on as part of the Jakarta EE move. It's probably not possible to give estimates at this stage since this is dependent on the transfer of GlassFish tools to Eclipse.
