### ISSUE TITLE
Getting absolute path is actually calling getCanonicalPath()

### ISSUE THREAD

**Issue by bradvido** [payara/Payara#3706]
This seems wrong, is it intentional that the absolutePath is using the canonicalPath?
https://github.com/payara/Payara/blob/5400417c32378c72477ab10e8b89f159d5b06775/nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java#L196

Related to https://github.com/payara/Payara/issues/2591

**Comment by smillidge** [comment]
Not sure does it fix #2591 if you change it?

**Comment by OndroMih** [comment]
Hi, since this is not a bug report or request for an improvement, I’m going to close this issue. Feel free to raise your suggestions as a pull request and we’ll review them there.
