### ISSUE TITLE
WeakHashmap enters into infinite loop in com.sun.xml.ws.api.streaming.XMLStreamWriterFactory.get()

### ISSUE THREAD

**Issue by clairechan0** [payara/Payara#3709]
We noticed that our application was using too much of CPU. 

On capturing the thread dump we saw that large number of threads were in the running state and had the following stacktrace - these threads were further verified via threaddumps every 5 minutes to remain in this loop for many hours  after all service calls were switched to another node :

at java.util.WeakHashMap.get(WeakHashMap.java:403)
at com.sun.xml.ws.api.streaming.ContextClassloaderLocal.get(ContextClassloaderLocal.java:60)
at com.sun.xml.ws.api.streaming.XMLStreamWriterFactory.get(XMLStreamWriterFactory.java:190)
at com.sun.xml.ws.api.streaming.XMLStreamWriterFactory.create(XMLStreamWriterFactory.java:214)
at com.sun.xml.ws.server.SDDocumentImpl.writeTo(SDDocumentImpl.java:286)
at com.sun.xml.ws.transport.http.HttpAdapter.publishWSDL(HttpAdapter.java:931)

----------

Thus we conclude this is an infinite loop.
We found this similar problem: 
https://issues.apache.org/jira/browse/BEANUTILS-509?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16633945#comment-16633945

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**:  Full 
- **JDK Version**:  Oracle jdk1.8.0_201 
- **Operating System**:  Linux  
[gf_threaddump_2019-02.zip](https://github.com/payara/Payara/files/2845292/gf_threaddump_2019-02.zip)

**Comment by clairechan0** [comment]
The file gf_threaddump_2019_02.zip  contains one threaddump per line (separated by newlines ) one for every 5 Minutes. 

linebreaks with a single thread-dump were replaced by carriage returns.

**Comment by smillidge** [comment]
That code is from upstream metro please raise an issue there.

https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/spi/ContextClassloaderLocal.java
