### ISSUE TITLE
[RFE] Using Fortuna RNG as replacement for java.security.SecureRandom

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#3717]
# Description #
----------

As a request for enhancement would it be of interest to replace the current usage of `java.security.SecureRandom` provided by `org.glassfish.security.common.SharedSecureRandomImpl` with an implementation of the Fortuna algorithm? If this makes sense at all.

Fortuna: https://www.schneier.com/academic/fortuna/
Implementation: https://github.com/grunka/fortuna

I would like to contribute if it is something the Payara project is interested in.

**Comment by smillidge** [comment]
Sounds interesting. Please feel free to add an enhancement. Logical place to store the config to enable/disable the Fortuna RNG may be the Security Service https://github.com/payara/Payara/blob/master/nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/SecurityService.java. 

It looks though that lots of the code does not use SharedSecureRandomImpl so it may be a bigger refactor

**Comment by svendiedrichsen** [comment]
Ok, I'm on it.

**Comment by fturizo** [comment]
As the requester fell unresponsive a while ago, we'll proceed to close this issue. @svendiedrichsen, feel free to make a PR with the recommended changes if you are still interested in implementing them.
