### ISSUE TITLE
creating programatically non-persistent timer throws NPE

### ISSUE THREAD

**Issue by ciment7** [payara/Payara#3721]
# Description #
----------

Hello,

I tried to create programatically NON-persisted EJB Timer following:

@Resource
    private TimerService timerService;

.....
timerService.createCalendarTimer(getSomeScheduleExpression(), new TimerConfig(this.getClass().getSimpleName() + "_timer", false));

but I got NPE exception. When I tried to create programatically persisted EJB Timer, It works perfectly.
timerService.createCalendarTimer(getSomeScheduleExpression(), new TimerConfig(this.getClass().getSimpleName() + "_timer", true));

## Expected Outcome

EJB Timer will created without NPE exception.

## Current Outcome
Calling method throws NPE. The stracktrace:

java.lang.NullPointerException
	at com.sun.ejb.containers.EJBTimerServiceWrapper.createTimerInternal(EJBTimerServiceWrapper.java:396)
	at com.sun.ejb.containers.EJBTimerServiceWrapper.createCalendarTimer(EJBTimerServiceWrapper.java:198)

## Environment ##

- **Payara Version**: 5.184
- **Edition**:  Full
- **JDK Version**: 8 u171 - Oracle
- **Operating System**: Mac

**Comment by jGauravGupta** [comment]
Fixed by #3502

**Comment by rdebusscher** [comment]
The fix for this issue will be included in the following community release 5.191.
