### ISSUE TITLE
Cleanup of randomly named files in "config" folder of domain

### ISSUE THREAD

**Issue by MartinSchmid2409** [payara/Payara#3740]
# Description #

This is rather a question or feature request.

I have one payara server in production. In the folder mydomain/config I discover lots of files named randomly with 8 characters, e.g. "ymrkiquh". Their size ranges from several kilobytes up to several megabytes (which in total can get up to several gigabytes). 

1. Can anyone please tell what´s the purpose of these files? (I searched the docs, but didn´t find anything.)

2. Is there any way of automatically deleting these files (those that are no longer needed)? Deleting them by hand seems dangerous since there are other important files in the same folder (this could be enhanced by storing these files in another separate folder).

Thx in advance.

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Windows
- **Database**: MySQL

**Comment by rdebusscher** [comment]
Hi Martin,

The Payara Server doesn't write anything within the config directory by default. I'm not even aware that it writes out files with random names.

I see 2 options where these files come from
- Your application as it writes maybe to the "current" directory
- MySQL database related files when the path to a database is set within the Payara Home directory.

Regards
Rudy

**Comment by MartinSchmid2409** [comment]
Hi Rudy,

thank you very much, your input was indeed very helpful.

You were right with option 1. To process images I temporarily store them in files. The thing is, I never delete these temporary files. Problem solved :)
