### ISSUE TITLE
EJB Timer Service - Timing out early

### ISSUE THREAD

**Issue by ettaramesh** [payara/Payara#3742]
Hi,
I have created a sample code to timeout on 25 Feb 2019 At 18:30 Hours, but the timeout is happening well before ie on 19 Feb 2019 at 18:30 Hours. 
Below is the code.

`@Startup
@Singleton
public class TestScheduler {
    public TestScheduler() {
        super();
      }
    @Resource
    private TimerService timerService;
    
    @PostConstruct
    void init() {
      createCalendarTimer();
    }
    
    
    private void createCalendarTimer() {
        Timer timer = timerService.createCalendarTimer(makeSchedule(), new TimerConfig(null, true));
        try {
            Date nextTimeout = timer.getNextTimeout();
            System.out.println("The next Timeout for the Timer with Schedule "+ timer.getSchedule()+" is at "+nextTimeout);
        } catch (NoMoreTimeoutsException e) {
            //Do Nothing.
            System.out.println("No more timeouts exceptions");
        }
    }

    private ScheduleExpression makeSchedule() {
        ScheduleExpression schedule = new ScheduleExpression();
        schedule.second("0");
        schedule.minute("30");
        schedule.hour("18");
        schedule.dayOfMonth("25");
        schedule.month("2");
        schedule.dayOfWeek("2");
        schedule.year("2019");
        return schedule;
    }
    
    @Timeout
    public void scheduleTimer(final Timer timer) {
        System.out.println("Timeout happened at "+new Date());
    }
}`

After the server is started below is the log  
"  The next Timeout for the Timer with Schedule ScheduleExpression [second=0;minute=30;hour=18;dayOfMonth=25;month=2;dayOfWeek=2;year=2019;timezoneID=null;start=null;end=null] is at Tue Feb 19 18:30:00 IST 2019|#]

And the timeout happens exactly at **"Tue Feb 19 18:30:00 IST 2019"** but expecting to happen at  **"Mon Feb 25 18:30:00 IST 2019"**

Also the EJB__TIMER__TBL record is below..
1550494211324	0xACED0005737200326F72672E676C617373666973682E656A622E70657273697374656E742E74696D65722E54696D6572537461746524426C6F6245B42025117023F80200025B000A696E666F42797465735F7400025B425B00107072696D6172794B657942797465735F71007E000178707070	7@@1550492287161@@server@@JFA	101613057641689629	server	0	0	0	**1550581200000**	0	0 # 30 # 18 # 24 # 2 # 2 # 2019 # null # null # null # false	101613057641676800

The highlighted one is INITIALEXPIRATIONRAW which suggests that the timeout is going to happen on 
"Tue Feb 19 18:30:00 IST 2019".

Not sure if this is an issue or i am missing any other parameters to be included.
Please review.

Environment Details:

Payara Version : 4.1.2.174 (also same issue with 5.184 as well)
JDK Version: 1.8.0_60

**Comment by dhubbard-ag** [comment]
Just an observation - you have set `schedule.dayOfWeek("2");` - is it possible that that is getting actioned over the other settings? 19th Feb 2019 is a Tuesday.

From [javadoc](https://docs.oracle.com/javaee/6/api/javax/ejb/ScheduleExpression.html)

> If the dayOfMonth attribute has a non-wildcard value and the dayOfWeek attribute has a non-wildcard value, then any day matching either the dayOfMonth value or the dayOfWeek value will be considered to apply.

**Comment by ettaramesh** [comment]
Thanks @dhubbard-ag. Looks like I shouldn't be setting the dayOfWeek value, if i want to timeout in the date given.
Looks to be working as expected.
