### ISSUE TITLE
Please add the HTTP Load Balancer Tab on the GUI as it was on GF 3.1.2.2 (build 5)

### ISSUE THREAD

**Issue by benjamin-Ndugga** [payara/Payara#375]
I have come to love Payara, however I have noticed that on the interface we do not have the HTTP Load Balancer Tab like it was on Glassfish version 3.1.2.2. Is it possible to have this added to the Payara Fish GUI as well

**Comment by mikecroft** [comment]
Looking into this just now, it looks like the load balancer plug-in was a commercial feature. If the feature never made it to the open source edition, then we would need to reimplement it

**Comment by mikecroft** [comment]
This feature is a significant amount of work to reimplement, so not something we can commit to at this time.

This was a commercial-only feature, but we have not had any customer raise this as an issue. If it is a feature you need, you could get in touch with our commercial department and request a quote to have it implemented.
