### ISSUE TITLE
Please upgrade guava module

### ISSUE THREAD

**Issue by grommitz** [payara/Payara#376]
The current version in Payara appears to be 13.0.1.jar but the latest release is 18.0.

My specific issue is that the implementation of com.google.common.net.InternetDomainName.toString() has changes since v 13 which caused one my domain name validator to fail.

**Comment by smillidge** [comment]
Guava is in Weld. We are dependent on a Weld upgrade of guava. See https://github.com/payara/Payara/pull/313 for background

**Comment by grommitz** [comment]
Thanks Steve. Do you think it would be safe to just swap the guava jar in the modules folder? I tried it and it appears to work but I guess there could be subtle problems.This https://issues.jboss.org/browse/WELD-1966 suggests it is fixed for weld 2.3, do you think that might be in the next release?

**Comment by trajano** [comment]
I would rather that guava should not be exposed to the applications.  It is implementation specific and applications should not use the one that comes with the container.

**Comment by TheodorRichard** [comment]
@grommitz Have you had any issues with replacing the guava.jar? It looks like that's the only option we have right now. Even the newly released GF 4.1.1 ships with Guava 13.0.1.

**Comment by grommitz** [comment]
@TheodorRichard that's disappointing. Looks like it still contains weld 2.2.x which uses guava 13, whereas weld 2.3.x uses guava 18. Hopefully the next glassfish update will give us a newer weld and therefore guava 18. No I haven't had any issues with just swapping the jar, but the payara version of our app isn't yet in production so I can't say for sure there won't be any.

**Comment by drupalspring** [comment]
I just swap guava in modules folder with guava 18 and does not encounter any problems so far.
Also , I run all the test cases of weld which the version is the same as payara using guava18 and all test cases pass .

**Comment by smillidge** [comment]
Fixed by #641

**Comment by trajano** [comment]
I take it there's no trivial way of just removing guava from the classpath of the modules (WAR, EJB) themselves?

**Comment by smillidge** [comment]
For war files yes add a glassfish-web.xml with delegate="false". For EJBs no we need to build an isolating classloader for EJBs that loads from the EAR first and then delegates to the aplication server classloaders.

**Comment by trajano** [comment]
It really should be the default, even in their docs it says so

> The Java Servlet specification recommends that a web module's class loader look in the local class loader before delegating to its parent. You can make this class loader follow the delegation inversion model in the Servlet specification by setting delegate="false" in the class-loader element of the glassfish-web.xml file. It is safe to do this only for a web module that does not interact with any other modules. For details, see class-loader in Oracle GlassFish Server 3.1 Application Deployment Guide.

https://docs.oracle.com/cd/E18930_01/html/821-2418/gfqpi.html
