### ISSUE TITLE
[microprofile] Fault Tolerance annotation cannot set the  java.time.temporal.ChronoUnit via the configuration file.

### ISSUE THREAD

**Issue by charleech** [payara/Payara#3763]
# Description #
----------

I've tried to set the fault tolerance annotation time unit via the `META-INF/microprofile-config.properties`, but have no luck to success with the following exception: -

```java
java.lang.ClassCastException: java.lang.String cannot be cast to java.time.temporal.ChronoUnit
	at fish.payara.microprofile.faulttolerance.interceptors.CircuitBreakerInterceptor.circuitBreak(CircuitBreakerInterceptor.java:220)
	at fish.payara.microprofile.faulttolerance.interceptors.CircuitBreakerInterceptor.intercept(CircuitBreakerInterceptor.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.NonTerminalAroundInvokeInvocationContext.proceedInternal(NonTerminalAroundInvokeInvocationContext.java:66)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
```

## Expected Outcome

Able to configure the `java.time.temporal.ChronoUnit` via the  `META-INF/microprofile-config.properties`.

## Current Outcome

There is an exception as `java.lang.ClassCastException: java.lang.String cannot be cast to java.time.temporal.ChronoUnit`.

## Steps to reproduce (Only for bug reports) 
1. Annotate the method with empty `@CircuitBreaker`
2. Set the CircuitBreaker attribute via the `META-INF/microprofile-config.properties` as 
    * `/CircuitBreaker/delayUnit=java.time.temporal.ChronoUnit.MILLIS` or 
    * `/CircuitBreaker/delayUnit=MILLIS`
3. Access the service via cURL, the exception shown at the log.

### Samples
```properties
# META-INF/microprofile-config.properties
my.service.MyService/alwaysFail/CircuitBreaker/failOn=java.lang.Throwable.class
my.service.MyService/alwaysFail/CircuitBreaker/requestVolumeThreshold=4
my.service.MyService/alwaysFail/CircuitBreaker/failureRatio=0.75d
my.service.MyService/alwaysFail/CircuitBreaker/successThreshold=2
my.service.MyService/alwaysFail/CircuitBreaker/delay=1000
my.service.MyService/alwaysFail/CircuitBreaker/delayUnit=java.time.temporal.ChronoUnit.MILLIS

# or
# my.service.MyService/alwaysFail/CircuitBreaker/delayUnit=MILLIS
# 

```
```java
package my.service;
@ApplicationPath("/myapi")
public class MyApplication extends Application {
}
```
```java
package my.service;
@Path("ft")
@ApplicationScoped
public class MyResource {
    @GET
    @CircuitBreaker
    public Response alwaysFail() {
        throws new IllegalStateException("This always fails.");
    }
}
```

```bash
curl -v -X GET \
http://localhost:8080/myweb/myapi/ft

# The exception 
# java.lang.ClassCastException: java.lang.String cannot be cast to java.time.temporal.ChronoUnit 
# shown at the log.
```

Furthermore, I also have a chance to look at [CircuitBreakerInterceptor](https://github.com/payara/Payara/blob/bc93c5e8948d3cb4a94c321a407d2589cf9cf074/appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java#L218) and found that it use `String.class` for looking up the value and then cast it to `ChronoUnit` as the following: -

```java
ChronoUnit delayUnit = (ChronoUnit) FaultToleranceCdiUtils.getOverrideValue(
                config, CircuitBreaker.class, "delayUnit", invocationContext, String.class)
                .orElse(circuitBreaker.delayUnit());
```

This may be the root cause.

## Context (Optional)
I've tried to learn the Microprofile: Fault Tolerance and tried to config them via the `META-INF/microprofile-config.properties`.

## Environment ##

From Docker `payara/micro:latest`

- **Payara Version**: `Payara Micro  5.184 #badassmicrofish (build 89)`
- **Edition**: `Micro`
- **JDK Version**: 
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (Alpine 8.181.13-r0)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
- **Operating System**: 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"
```
- **Database**:  N/A

**Comment by smillidge** [comment]
This is a bug Fixed by #3765
