### ISSUE TITLE
Confusing Prometheus metric types

### ISSUE THREAD

**Issue by danieltrautmann** [payara/Payara#3771]
# Description #
----------

First of all, I have to say, that I'm not very familiar with Payara and Java at all.
I'm trying to create a Grafana dashboard for Payara Micro using Prometheus as datasource.

I am a bit confused about the type of the following metrics provided by Payara Micro.

- base:thread_count
- base:classloader_current_loaded_class_count
- base:thread_daemon_count

The endpoint `/metrics` returns that each of them are of type `counter`, but the help message tells me that it returns the current value, so I would say that this should be a [Gauge](https://prometheus.io/docs/concepts/metric_types/#gauge). According to the [Prometheus docs](https://prometheus.io/docs/concepts/metric_types/#counter), a counter can only be increasing.

**Example**

```
# TYPE base:thread_count counter
# HELP base:thread_count Displays the current number of live threads including both daemon and non-daemon threads.
base:thread_count 650
# TYPE base:classloader_current_loaded_class_count counter
# HELP base:classloader_current_loaded_class_count Displays the number of classes that are currently loaded in the JVM.
base:classloader_current_loaded_class_count 22255
# TYPE base:thread_daemon_count counter
# HELP base:thread_daemon_count Displays the current number of live daemon threads.
base:thread_daemon_count 609
```

However, I can see that the values for `base:thread_count` and `base:thread_daemon_count` are going up and down.

<img width="652" alt="screen shot 2019-02-22 at 16 13 55" src="https://user-images.githubusercontent.com/4022138/53251596-525c2480-36bd-11e9-953a-d6d0ea35a8b5.png">

I've used the following queries to get the data from Prometheus.

- Current: `base:thread_count{env=~"[a-z]+", instance=~"$server"}`
- Max: `base:thread_max_count{env=~"[a-z]+", instance=~"$server"}`
- Daemon: `base:thread_daemon_count{env=~"[a-z]+", instance=~"$server"}`

Normally Prometheus counters are often used together with the [rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) or [irate](https://prometheus.io/docs/prometheus/latest/querying/functions/#irate) function, which doesn't make sense when the value goes up and down.

I'm not really sure if this is a bug or not. I'm just wondering how I can use them correctly in my Grafana dashboard.

## Environment ##

I'm using the Payara Micro Docker image:

```
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
payara/micro        5.184               01a4341711b5        2 months ago        177MB
```

- **Payara Version**: 5.184
- **Edition**: Micro
- **Operating System**: Linux

**Comment by khasunuma** [comment]
This is an issue of MicroProfile Metrics 1.1 that is compatibility problem with Prometheus text format. See https://github.com/eclipse/microprofile-metrics/issues/307.

Payara 5.184 is currently compatible with MicroProfile Metrics 1.1, so those metrics are still defined as `Counter`. When the issue is correct and new version of Metrics released, Payara will also correct.

For your information, there are current and new version of `Counter` class as follows:

* `Counter` class in Metrics 1.1: https://github.com/eclipse/microprofile-metrics/blob/1.1/api/src/main/java/org/eclipse/microprofile/metrics/Counter.java
* `Counter` class in Metrics 2.0 (under development): https://github.com/eclipse/microprofile-metrics/blob/master/api/src/main/java/org/eclipse/microprofile/metrics/Counter.java

**Comment by danieltrautmann** [comment]
Okay, thanks for the information. Feel free to close this issue, if you don't want to keep it open as some kind of reminder.

**Comment by rdebusscher** [comment]
In the latest version of the MicroProfile Metrics specs, those metrics are defined as Gauge now (see for example about thread count https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/required-metrics.adoc#thread-jvm-stats) and also within Payara.
