### ISSUE TITLE
NullPointerException when running batch process in Payara Micro

### ISSUE THREAD

**Issue by gustoneves** [payara/Payara#3776]
# Description #
----------

When running a simple chunk job the first it runs perfectly, but the next executions throw an exception stating that it can't find the given execution.

## Current Outcome

`Caught throwable in main execution loop with Throwable message: null, and stack trace: java.lang.NullPointerException at com.ibm.jbatch.container.impl.BaseStepControllerImpl.updateBatchStatus(BaseStepControllerImpl.java:287) at com.ibm.jbatch.container.impl.BaseStepControllerImpl.markStepFailed(BaseStepControllerImpl.java:243) at com.ibm.jbatch.container.impl.BaseStepControllerImpl.markJobAndStepFailed(BaseStepControllerImpl.java:248) at com.ibm.jbatch.container.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:133) at com.ibm.jbatch.container.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:112) at com.ibm.jbatch.container.impl.JobThreadRootControllerImpl.originateExecutionOnThread(JobThreadRootControllerImpl.java:110) at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:80) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:143) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) ]] [2019-02-22T09:24:00.145+0000] [] [WARNING] [] [com.ibm.jbatch.container.util] [tid: _ThreadID=157 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [timeMillis: 1550827440145] [levelValue: 900] [[ Caught throwable from run(). Stack trace: java.lang.IllegalStateException: Couldn't find entry to update for id = 8 at com.ibm.jbatch.container.services.impl.JobStatusManagerImpl.updateJobBatchStatus(JobStatusManagerImpl.java:82) at com.ibm.jbatch.container.impl.JobThreadRootControllerImpl.persistJobBatchAndExitStatus(JobThreadRootControllerImpl.java:214) at com.ibm.jbatch.container.impl.JobThreadRootControllerImpl.endOfJob(JobThreadRootControllerImpl.java:200) at com.ibm.jbatch.container.impl.JobThreadRootControllerImpl.originateExecutionOnThread(JobThreadRootControllerImpl.java:128) at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:80) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:143) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) ]]`

## Steps to reproduce (Only for bug reports) 

the Job configuration is
`<?xml version="1.0" encoding="UTF-8"?> <job id="importJob" xmlns="http://xmlns.jcp.org/xml/ns/javaee" version="1.0"> <step id="firstChunkStep" > <chunk item-count="100"> <reader ref="reader"/> <processor ref="processor"/> <writer ref="writer"/> </chunk> </step> </job>`

And I haven't defined any data source.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Micro

**Comment by smillidge** [comment]
Can you provide a test case that demonstrates the issue?

**Comment by gustoneves** [comment]
You can find the test case in here `https://github.com/gustoneves/simplejbatch`

**Comment by gustoneves** [comment]
> Can you provide a test case that demonstrates the issue?

You can find the test case in here https://github.com/gustoneves/simplejbatch

**Comment by smillidge** [comment]
I tried this on the latest of build of Payara Micro and couldn't reproduce the issue. 

I got log messages like
`
[2019-04-25T20:51:30.062+0100] [] [INFO] [] [global] [tid: _ThreadID=139 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1556221890062] [levelValue: 800] Item written: Item99

[2019-04-25T20:51:30.062+0100] [] [INFO] [] [global] [tid: _ThreadID=139 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1556221890062] [levelValue: 800] Item written: Item100

[2019-04-25T20:51:30.064+0100] [] [INFO] [] [global] [tid: _ThreadID=139 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1556221890064] [levelValue: 800] ReadItem: 

[2019-04-25T20:51:30.065+0100] [] [INFO] [] [global] [tid: _ThreadID=139 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1556221890065] [levelValue: 800] ReadItem: 

[2019-04-25T20:51:30.065+0100] [] [INFO] [] [global] [tid: _ThreadID=139 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1556221890065] [levelValue: 800] Item written: Item101
`
