### ISSUE TITLE
Documentation request: setting version number

### ISSUE THREAD

**Issue by skiedrowski** [payara/Payara#3788]
## Description

Please enhance the documentation regarding how to set the version of a new Payara release.

I currently need to maintain a tailored own Payara version and figured that the version (currently 5.184) appears more than 600 times in various places (see commit e6b6001df8ee93be48b9545c52dec8837a82a784 and others). 

Do I just have to search across the whole repo and replace 5.184 with my own version-String? Or is there a maven plugin used for this purpose?

## Expected Outcome

Enhanced documentation (maybe here: https://payara.gitbooks.io/payara-server/content/build-instructions/build-instructions.html)

Thanks

**Comment by svendiedrichsen** [comment]
@skiedrowski You problably can use versions-maven-plugin to set the version throughout the whole Payara project. http://www.mojohaus.org/versions-maven-plugin/

**Comment by skiedrowski** [comment]
I tried using the versions-maven-plugin (http://www.mojohaus.org/versions-maven-plugin/):
Calling `mvn versions:set -DnewVersion=5.184.my` from the repo root directory just changes the main `pom.xml`, but not the sub-pom.xmls. 
Calling `mvn versions:set -DnewVersion=5.184.my` from the `appserver` directory results in a failure
`Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:set (default-cli) on project payara-parent: Project version is inherited from parent. -> [Help 1]`

Maybe it is possible using the versions plugin, but not that straigtforward, this is why I was asking for documentation.

**Comment by rdebusscher** [comment]
Hi @skiedrowski,

We use a bash script to search and replace version numbers within the pom.xml files (through sed)

Regards
Rudy
