### ISSUE TITLE
Error while deploying exploded war with payara micro (InvocationTargetException or context-root truncated)

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#3800]
# Description #
----------

Context-root are badly inferred from exploded war name. 

## Expected Outcome

context-root should match the exploded war name

## Current Outcome

context-root is truncated (in case the name is long enough) or java.lang.reflect.InvocationTargetException (in case the name is less than 4 characters long)

## Steps to reproduce

1. fetch Payara-Examples (https://github.com/payara/Payara-Examples.git)
1. `cd Payara-Examples/javaee/hello-world-rest/`
1. `mvn package`
1. `cd target`
1. deploy the exploded war:
   - `java -jar /path/to/payara-micro-prerelease.jar --deploy hello-world-rest-1.0-SNAPSHOT`
     - context-root has been truncated to "/hello-world-rest-1.0-SNAP"
1. deploy the exploded war, but with a very short name:
   1. `ln -s hello-world-rest-1.0-SNAPSHOT Hel  # create a short name`
   1. `java -jar /path/to/payara-micro-prerelease.jar --deploy Hel`
      - InvocationTargetException

In some cases that I have not been able to identify well, the context-root becomes correct again after a "touch .reload".

## Hint ##
fish.payara.micro.impl.PayaraMicroImpl.java:[1540](https://github.com/payara/Payara/blob/master/appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java#L1540)

## Environment ##

- **Payara Version**: prerelease (191), does not affect 184
- **Edition**: 
- **JDK Version**: OpenJDK 8u191
- **Operating System**:Linux
- **Database**: none

**Comment by khasunuma** [comment]
It's a bug, so I raised internal JIRA (PAYARA-3541).

Currently, there's no concern with deploying exploded war (a.k.a. directory deployment). Therefore, it assumes to deploy war file and remove suffix (e.g. ".war"). 

GlassFish Deployer (`org.glassfish.embeddable.Deployer`) can loads application as either file archive and directory by same API (`org.glassfish.embeddable.Deployer.deploy()` method).

**Comment by smillidge** [comment]
oops a pretty major bug. We will get this mixed in master.
