### ISSUE TITLE
Unable to save Default Principal  through admin panel UI

### ISSUE THREAD

**Issue by alexvinok** [payara/Payara#3815]
# Description #
----------
Configuration->server-config->Securities
I am unable to save Default Principal through admin panel. I see the message 
New values successfully saved.
But no changes made to domain.xml file and the fields on the Security form are empty.

## Expected Outcome
older version of glassfish 2,1,1  I am migrating from would have saved values and show them on the screen.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: 
 java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
- **Operating System**: Linux 
- **Database**:

**Comment by lprimak** [comment]
Does this work via asadmin commands?

**Comment by alexvinok** [comment]
I believe I was able to run the commands but see no impact

[......@svr1 bin]$ ./asadmin set server-config.security-service.default-principal=......
Enter admin user name>  admin
Enter admin password for user "admin">
server-config.security-service.default-principal=......
Command set executed successfully.
[......@svr1 bin]$ ./asadmin set  server-config.security-service.default-principal-password=......
Enter admin user name>  admin
Enter admin password for user "admin">
server-config.security-service.default-principal-password=......
Command set executed successfully.
[......@svr1 bin]$ ./asadmin set server-config.security-service.activate-default-principal-to-role-mapping=true
Enter admin user name>  admin
Enter admin password for user "admin">
server-config.security-service.activate-default-principal-to-role-mapping=true
Command set executed successfully.

UI still shows empty fields post server restart
![capture](https://user-images.githubusercontent.com/48260198/53838764-d044e900-3f63-11e9-90b9-bc3550d19076.PNG)

**Comment by lprimak** [comment]
What I am trying to say do you think it's an issue with the UI or functionality?
i.e. can you work around the issue by using asadmin commands?

**Comment by smillidge** [comment]
This is a UI bug it can be set by the management REST interface.

**Comment by smillidge** [comment]
PAYARA-3686 created to track this

**Comment by smillidge** [comment]
Fixed by #3848
