### ISSUE TITLE
SLOW STARTUP With MQJMSRA_RA1101 GlassFish MQ JMS Resource Adapter starting broker is EMBEDDED connection mode is Direct

### ISSUE THREAD

**Issue by davidandradeb** [payara/Payara#3818]
# Description #
----------

Hy everyone, I have a problem with my server and JMS Service. The payara server production works fine, but when I active a JMS Queue the startup of my server is very affected by slow or delayed service JMS.

The configuration of my JMS QUEUE:
```
<resources>
  <admin-object-resource res-adapter="jmsra" res-type="javax.jms.Queue" jndi-name="dyalogoQ">
      <property name="Name" value="dyalogoQ"></property>
    </admin-object-resource>
</resources>

<servers>
<resource-ref ref="dyalogoQ"></resource-ref>
</servers>
```

When I startup the payara server say:

[2019-03-07T21:53:19.561-0500] [Payara 5.181] [INFO] [AS-JMS-CORE-00002] [javax.enterprise.resource.jms] [tid: _ThreadID=152 _ThreadName=pool-29-thread-1] [timeMillis: 1552013599561] [levelValue: 800] [[
  ADDRESSLIST in setJmsServiceProvider : mq://localhost:7676/]]

[2019-03-07T21:53:19.565-0500] [Payara 5.181] [INFO] [AS-JMS-CORE-00001] [javax.enterprise.resource.jms] [tid: _ThreadID=152 _ThreadName=pool-29-thread-1] [timeMillis: 1552013599565] [levelValue: 800] [[
  JMS Service Connection URL is : mq://localhost:7676/]]

[2019-03-07T21:53:19.720-0500] [Payara 5.181] [INFO] [] [javax.resourceadapter.mqjmsra.lifecycle] [tid: _ThreadID=152 _ThreadName=pool-29-thread-1] [timeMillis: 1552013599720] [levelValue: 800] [[
  MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter: Version:  5.1.1  (Build 6-a) Compile:  September 16 2017 1710]]

**[2019-03-07T21:53:19.721-0500]** [Payara 5.181] [INFO] [] [javax.resourceadapter.mqjmsra.lifecycle] [tid: _ThreadID=152 _ThreadName=pool-29-thread-1] [timeMillis: 1552013599721] [levelValue: 800] [[
  MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter starting: broker is EMBEDDED, connection mode is Direct]]

**[2019-03-07T21:55:03.866-0500]** [Payara 5.181] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=114 _ThreadName=Thread-14] [timeMillis: 1552013703866] [levelValue: 800] [[
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi]]

This take several minutes (3 or 4)

## Context (Optional)

I need queue operations of my database, so I need a JMS queue for this requirement. but I need more velocity on startup of my server when this queue is activated.

## Environment ##

- **Payara Version**: 5.181
- **Edition**: FULL
- **JDK Version**: JDK 1.8.0_201
- **Operating System**: Linux CentOS 7
- **Database**: MySQL

**Comment by smillidge** [comment]
We need a test case or a detailed description of how to reproduce this issue.

**Comment by davidandradeb** [comment]
> We need a test case or a detailed description of how to reproduce this issue.

What do you need?

**Comment by davidandradeb** [comment]
The configuration its in the original post, my code in EJB is:

```
@MessageDriven(
        activationConfig = {
            @ActivationConfigProperty(propertyName = "destination", propertyValue = "dyalogoQ"),
            @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue")
        },mappedName = "dyalogoQ")
public class JMSDyalogo implements MessageListener {
}
```

When I deploy EJB its very slow.

**Comment by smillidge** [comment]
Ideally a GitHub project in your GitHub account that can be cloned and built with maven that demonstrates the issue. 
Reality is that will make it much quicker for somebody to look at this.

**Comment by davidandradeb** [comment]
Hi smillidge I cant post my project on GitHub, but I found the follow:

I have EJB application with bussines inteligence, when I deploy this application its very very slow.

The code of my resource are:
@MessageDriven(
        activationConfig = {
            @ActivationConfigProperty(propertyName = "destination", propertyValue = "dyalogoQ"),
            @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue")
        },mappedName = "dyalogoQ")
public class JMSDyalogo implements MessageListener {
}


If I detele this lines of my code this ejb application deploy very quickly.

Please helpme.

**Comment by davidandradeb** [comment]
Sorry, the deploy command its very quickly too, the problem is when I disable and after enable.

**Comment by davidandradeb** [comment]
Look this:

[2019-03-27T22:06:36.726-0500] [Payara 5.181] [INFO] [AS-JMS-CORE-00001] [javax.enterprise.resource.jms] [tid: _ThreadID=163 _ThreadName=pool-30-thread-1] [timeMillis: 1553742396726] [levelValue: 800] [[
  JMS Service Connection URL is : mq://localhost:7676/]]

[2019-03-27T22:06:36.908-0500] [Payara 5.181] [INFO] [] [javax.resourceadapter.mqjmsra.lifecycle] [tid: _ThreadID=163 _ThreadName=pool-30-thread-1] [timeMillis: 1553742396908] [levelValue: 800] [[
  MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter: Version:  5.1.1  (Build 6-a) Compile:  September 16 2017 1710]]

[2019-03-27T22:06:36.909-0500] [Payara 5.181] [INFO] [] [javax.resourceadapter.mqjmsra.lifecycle] [tid: _ThreadID=163 _ThreadName=pool-30-thread-1] [timeMillis: 1553742396909] [levelValue: 800] [[
  MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter starting: broker is EMBEDDED, connection mode is Direct]]

FROM 22:06 to 22:08 two minutes

[2019-03-27T22:08:21.050-0500] [Payara 5.181] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=117 _ThreadName=Thread-14] [timeMillis: 1553742501050] [levelValue: 800] [[
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi]]

**Comment by davidandradeb** [comment]
How to create test case ???? I need help please

**Comment by davidandradeb** [comment]
@smillidge look 
![Captura de Pantalla 2019-10-16 a la(s) 1 01 38 p  m](https://user-images.githubusercontent.com/5994937/66945707-1e9b8980-f015-11e9-8d00-9deee95bb2af.png)
Very expensive time

**Comment by davidandradeb** [comment]
I can publish opt/payara folder. this works?

**Comment by lprimak** [comment]
No, a github project that is maven buildable and deployable to payara and simple step-by-step instructions on how to configure payara from scratch. ideally a set of asadmin commands. Think about it this way:
"What can I do to help someone new to my project reproduce the issue from scratch with minimum thought?"

**Comment by lprimak** [comment]
And yes, it will require some work on your part. It can be hard to isolate the specific issue in a self-contained reproducible example. However this is the work Payara would have to do anyway to reproduce your example, so it should be easier done by you rather than Payra.

**Comment by davidandradeb** [comment]
Ok step by step:

1. Dowload payara 
wget https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/5.181/payara-5.181.zip

2. Unzip payara
unzip payara-5.181.zip -d PS

3. Move payara
/usr/bin/cp -fr PS/payara5 /opt/

4. Create user for service.
adduser payara
chown -R payara:payara /opt/payara5

5. Install script DAEMON
wget https://www.dropbox.com/s/qi0ske2i0ca32sf/payara_service
/usr/bin/cp payara_service /etc/systemd/system/payara.service
systemctl enable payara

6. Set JMS Resource into configuration
nano /opt/payara5/glassfish/domains/production/config/domain.xml

```
<resources>
  <admin-object-resource res-adapter="jmsra" res-type="javax.jms.Queue" jndi-name="dyalogoQ">
      <property name="Name" value="dyalogoQ"></property>
    </admin-object-resource>
</resources>

<servers>
<resource-ref ref="dyalogoQ"></resource-ref>
</servers>
```
7. Start payara
/opt/payara5/glassfish/bin/asadmin start-domain production

8. Enable secure admin
/opt/payara5/glassfish/bin/asadmin change-admin-password
admin/admin

/opt/payara5/glassfish/bin/asadmin --port 4848 enable-secure-admin

/opt/payara5/glassfish/bin/asadmin restart-domain production

9. Restart:
/opt/payara5/glassfish/bin/asadmin restart-domain production

10. Deploy 

/opt/payara5/glassfish/bin/asadmin --user admin deploy JMSExample.jar

https://www.dropbox.com/s/2fhdweugp1eby4t/JMSExample.jar

11. /opt/payara5/glassfish/bin/asadmin restart-domain production

12. Search in log:
/opt/payara5/glassfish/domains/production/logs/server.log
--> GlassFish MQ JMS Resource Adapter starting

**Comment by chrjohn** [comment]
@davidandradeb Hmm, I have never experienced such a long delay when starting up the broker. Must be something specific to your environment maybe. To me it sounds like some lookup (DNS or general network) is taking place. Is your server running on bare metal or is it running "in the cloud"?

- At first I would check if your /etc/hosts file contains strange entries for localhost (sometimes it is mapped to 127.0.1.1 instead of 127.0.0.1).

After all I don't think this is a general problem in Payara but rather something specific to your environment.

**Comment by davidandradeb** [comment]
Hi @chrjohn  mi /etc/hosts file are:

127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 dy-cc-produccion.c.dyalogocc.internal dy-cc-produccion
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.142.0.2 bpo.dyalogo.cloud
10.142.0.2 dy-cc-produccion.c.dyalogocc.internal dy-cc-produccion


169.254.169.254 metadata.google.internal

its wrong?
And yes mi system run in GCP virtual machine.

Thanks.

**Comment by chrjohn** [comment]
LGTM. To rule out any problems with IPv4/IPv6 I would try to put `127.0.0.1` as `default_JMS_host` into `domain.xml` and restart. Does this change anything?

Also could you please check the broker log in `imq/instances/imqbroker/log/log.txt` of your domain directory. Are there any delays when starting up? Compare the time stamps to the time stamps in the Payara log.

**Comment by davidandradeb** [comment]
```
cat /opt/payara5/glassfish/domains/production/config/domain.xml | grep JMS
      <system-property name="JMS_PROVIDER_PORT" description="Port Number that JMS Service will listen for remote clients connection." value="7676"></system-property>
      <jms-service default-jms-host="default_JMS_host" type="EMBEDDED">
        <jms-host port="${JMS_PROVIDER_PORT}" name="default_JMS_host" host="127.0.0.1"></jms-host>
      <jms-service addresslist-behavior="priority" default-jms-host="default_JMS_host" type="EMBEDDED">
        <jms-host port="${JMS_PROVIDER_PORT}" name="default_JMS_host" host="127.0.0.1"></jms-host>
      <system-property name="JMS_PROVIDER_PORT" description="Port Number that JMS Service will listen for remote clients connection." value="27676"></system-property>
```

I put 127.0.0.1 in domain configuration but the result its same

**Comment by davidandradeb** [comment]
![Captura de Pantalla 2019-10-21 a la(s) 8 28 48 p  m](https://user-images.githubusercontent.com/5994937/67254198-6a996480-f441-11e9-92be-d1d653fb9c36.png)


[imqbroker_log.txt](https://github.com/payara/Payara/files/3753526/imqbroker_log.txt)

**Comment by chrjohn** [comment]
It seems that the startup delay is coming from starting the jmxrmi connector in OpenMQ:

```
[#|2019-10-21T20:22:22.325-0500|INFO|5.1.1|imq.log.Logger|_ThreadID=58;_ThreadName=pool-8-thread-1;|RMI Registry started on port 7776
|#]
[#|2019-10-21T20:24:29.591-0500|INFO|5.1.1|imq.log.Logger|_ThreadID=58;_ThreadName=pool-8-thread-1;|[B1234]: JMX Connector Server jmxrmi started successfully with url service:jmx:rmi://dy-dev/jndi/rmi://localhost:7776/localhost/7676/jmxrmi
|#]
```

What is a little strange is that there is a hostname in the service url that is not listed in your hosts file: `dy-dev`. I don't know where that is coming from. Did you copy the Payara installation over from some other system? If yes, then I would suggest to install a fresh domain.
However, maybe it helps adding `dy-dev` to your hostfile to the `127.0.0.1` line.

Otherwise I would play around with the options in the file `imq/instances/imqbroker/props/config.properties` of your Payara domain. There are some related to JMX.
https://docs.oracle.com/cd/E18930_01/html/821-2438/geofd.html

Hope that helps.

**Comment by davidandradeb** [comment]
Sorry @chrjohn the previous hosts file are from other server, the correct file are:


127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 dy-dev.c.dyalogocc.internal dy-dev
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.142.0.7 gdev.dyalogodev.com
10.142.0.7 dy-dev.c.dyalogocc.internal dy-dev

169.254.169.254 metadata.google.internal
10.142.0.7 dy-dev.c.dyalogocc.internal dy-dev  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google

**Comment by davidandradeb** [comment]
Hi @chrjohn the final solution:

`nano /opt/payara5/glassfish/domains/production/imq/instances/imqbroker/props/config.properties`

In the final of file add a line:

`imq.jmx.hostname=localhost`

OR

`echo "imq.jmx.hostname=localhost" >> /opt/payara5/glassfish/domains/production/imq/instances/imqbroker/props/config.properties`

Now works fine !!!!!

Thanks very much
