### ISSUE TITLE
[embedded] JVM Memory options ignored (-Xmx)

### ISSUE THREAD

**Issue by ctabin** [payara/Payara#3823]
# Description #
----------

When starting Payara programmatically with a specified `domain.xml`, the JVM option `-Xmx` is ignored. 

Here is the content of my `domain.xml` (only the config part):
```xml
<java-config classpath-suffix="" system-classpath="" debug-options="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009">
  <jvm-options>-Xmx1024m</jvm-options>
  <!--
    follows, all the other options, as defined in the domain.xml of the production environment
  -->
</java-config>
```

A enterprise application (ear) is deployed and I have a Bean with the following piece of code: 
```java
MemoryMXBean mmBean = ManagementFactory.getMemoryMXBean();
MemoryUsage hmem = mmBean.getHeapMemoryUsage();
System.out.println("MAX: "+humanReadable(hmem.getMax()));
```

## Expected Outcome

The printed value should be relative to the `-Xmx` value. If I specify the value in a simple program executed with `java -Xmx1024m Test`, it prints 910.5m.

## Current Outcome

When invoked in the running embeded payara server (through a servlet), the printed value is 3536.0m. This is exactly the printed value of my simple program when the `-Xmx` is not specified (ie it is the default system value).

## Other details

To validate that my `domain.xml` and the `jvm-options` are read correctly, I changed the `-Djava.security.auth.login.config` value to a non-existing file, resulting in a login failure. This shows that the properties are read correctly.

I tried different values for the `-Xmx` (ie `-Xmx2g`, `-Xmx1024M`, ...) and to move it around the `jvm-options`, but still I have always had the same wrong output (3536.0m).

I also put some very small values in the `-Xmx` so generate an OOM, but it seems that the latter is always ignored.

## Context

I use the Payara embedded server through maven:
```xml
<dependency>
  <groupId>fish.payara.extras</groupId>
  <artifactId>payara-embedded-all</artifactId>
  <version>5.191</version>
</dependency>
```

The server is then started programmatically and the EAR is also deploy through the API.
```java
GlassFishProperties gfprops = new GlassFishProperties();
gfprops.setConfigFileURI(domainFile);

BootstrapProperties bsprops = new BootstrapProperties();
GlassFishRuntime runtime = GlassFishRuntime.bootstrap(bsprops);
GlassFish glassfish = runtime.newGlassFish(gfprops);
glassfish.start();

Deployer deployer = glassfish.getDeployer();
deployer.deploy(earFile);
```

## Environment

- **Payara Version**: 4.1.2.181 and 5.191
- **Edition**: Full embedded
- **JDK Version**: OpenJDK 8
- **Operating System**: Linux Debian

**Comment by smillidge** [comment]
Hi Embedded can not use domain.xml JVM options because by its nature it is embedded in your JVM and you can't change JVM parameters after the JVM has started. To apply JVM parameters when using Payara Embedded you must set them on the command line of your application.
