### ISSUE TITLE
java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms 

### ISSUE THREAD

**Issue by ettaramesh** [payara/Payara#3847]
# Description #
----------
java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms 
 when trying to access using SSL
My application run on http-listener-1 8080 but fails on http-listener-2 8081 (default domain)
The following is the error i see in the logs..

`java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:770)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:226)
`

I am not sure if i would be using higher version of JDK, if so which version should i be using?

Any help would be appreciated.

## Environment ##

- **Payara Version**: 5.191
- **Edition**:  Full
- **JDK Version**:  1.8.0_60

**Comment by lprimak** [comment]
You are correct. Your JDK isn’t up to date. Please update to latest and it’l work

**Comment by ettaramesh** [comment]
Thanks @lprimak, I have updated JDK to the latest version 1.8.0_192 and it worked.
