### ISSUE TITLE
WELD-000715 warnings logged when using AsyncContext

### ISSUE THREAD

**Issue by meliora** [payara/Payara#3851]
# Description #
----------

We have a push notification system in our application implemented with AsyncContext. We have a 60s timeout for sockets which we use to push notifications to applicable clients.

For some reason our servers regularly log these WELD related warnings:

..
[2019-03-15T10:09:21.090+0200] [Payara 5.191] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=42 _ThreadName=http-listener-1-expirer(1)] [timeMillis: 1552637361090] [levelValue: 900] [[
  WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.]]
...

By the look of it, it might be related to expiring asynchronous contexts for which timeouts have exceeded.

## Expected Outcome

WELD warnings should not be logged.

## Current Outcome

Log file is written with WELD warnings as described.

## Steps to reproduce (Only for bug reports) 

For a HTTP request, start asynchronous operation with startAsync, let it expire or call expicit complete on it.

### Samples

None available.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
- **Operating System**: Mac
- **Database**: -

**Comment by smillidge** [comment]
Can you provide a test case as a maven project in your GitHub account that can be cloned and built that demonstrates the issue.

**Comment by meliora** [comment]
I have to say that I tried but with little success.

Though, I got the problem fixed. In the AsyncListener which we register to the context when we start it, we did not call "complete()" in the onTimeout-callback. When we added the complete() call to onTimeout, the problem disappeared. As far as I've understood, completing the context manually via the onTimeout callback is not mandatory. The side-effect is that the request goes through the error processing pipeline which might have something to do this.

I inspected the request with a debugger and noticed that when the complete() call is not present in the onTimeout callback, the HttpContextLifecycle.requestDestroyed(...) method gets called twice in the row by the same -expirer thread. The latter one causes the warning as the "nestedInvocationGuard" thread local is already removed by the first call. By looking at the call stack, the latter one comes from the Request.errorDispatchAndComplete method's "hostValve.postInvoke(...)" call which again, calls the requestDestroyed method and Weld is not happy with this.

I did not look deeper into what is different in the error handling configuration in our real application and my tester application (which did not produce these warnings). But yes, the situation is bit obscure and the warnings are probably quite rare as it probably is a good idea to complete the contexts on timeout.

**Comment by rdebusscher** [comment]
Hi,

This is in the JavaDoc of AsyncContext regarding the timeout

```
In the event that an asynchronous operation has timed out, the container must run through these steps:

- Invoke, at their onTimeout method, all AsyncListener instances registered with the ServletRequest on which the asynchronous operation was initiated.
- If none of the listeners called complete() or any of the dispatch() methods, perform an error dispatch with a status code equal to HttpServletResponse.SC_INTERNAL_SERVER_ERROR.
- If no matching error page was found, or the error page did not call complete() or any of the dispatch() methods, call complete().
```

It looks reasonable to me (as also hinted in the javadoc) to call the complete() method yourself in the onTimeout() method since you know at that point the async context can be closed.
The addition of the error page and closing the context automatically is there in case the developer forgot (or did not do) it.

**Comment by meliora** [comment]
You are right, we added the complete() call as we noticed it was missing. 

The async logic has always worked though, probably because all timeouts have been completed anyway (but in the "return 500 error page & complete" code path) and for some reason, the WELD warnings were then logged.

**Comment by rdebusscher** [comment]
Can this issue be closed then?

**Comment by meliora** [comment]
I really have no idea if the warning reported is harmless or not (I still think it probably should not be logged out as calling complete() on timeout is not mandatory by the spec) but as said, the situation is probably very rare. If the warning can be assessed as technically harmless, I personally would close this issue and move on to things more important.
