### ISSUE TITLE
Shouldn't OpenIdContext extend SecurityContext?

### ISSUE THREAD

**Issue by amihaiemil** [payara/Payara#3877]
Coming from [this article](https://blog.payara.fish/openid-connect-in-the-payara-platform-5.183?ee-security), I've started digging into the [sample code](https://github.com/javaee-samples/vendoree-samples/tree/master/payara/openid) and found the [OpenIdContext](https://github.com/payara/Payara/blob/4bd636cb9a9d693c0a3e7eabc94a96db0d41c83c/api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdContext.java) interface. 

According to [this](https://javaee.github.io/tutorial/security-intro001.html) Java EE 8 Security Tutorial, there is the interface [javax.security.enterprise.SecurityContext](https://javaee.github.io/javaee-spec/javadocs/javax/security/enterprise/SecurityContext.html) which "provides an access point for programmatic security". It is also stated that "You can use the built-in implementations of these APIs, or define custom implementations."

Thus, I believe the OpenIdContext interface should extend SecurityContext and, for instance, method ``OpenIdContext.getCallerName()`` should be replaced by ``OpenIdContext.getCallerPrincipal().getName()`` (inherited from ``SecurityContext``).

Also, other logic about authentication should probably be integrated with ``SecurityContext.authenticate(...)`` if it's not done so already. 

What do you think?

**Comment by fturizo** [comment]
Closing this issue as questions should be directed to the [official Payara Forum](https://groups.google.com/forum/#!forum/payara-forum). Please raise a topic there with the contents of your question.
