### ISSUE TITLE
Redeploy of EAR does not work

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#3882]
# Description #
----------

An attempt to redeploy application fails with error.

`[2019-04-06T10:13:29.625+0200] [Payara 5.191] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=407 _ThreadName=admin-thread-pool::admin-listener(11)] [timeMillis: 1554538409625] [levelValue: 1000] [[
  Exception while loading the app : java.lang.Exception: Virtual server server already has a web module static.war loaded at / therefore web module test-case-07164454221128210962#static.war cannot be loaded at this context path on this virtual server]]

[2019-04-06T10:13:29.632+0200] [Payara 5.191] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=410 _ThreadName=admin-thread-pool::admin-listener(14)] [timeMillis: 1554538409632] [levelValue: 800] [[
  Exception Occurred :Error occurred during deployment: Exception while loading the app : java.lang.Exception: Virtual server server already has a web module static.war loaded at / therefore web module test-case-07164454221128210962#static.war cannot be loaded at this context path on this virtual server. Please see server.log for more details.            ]]`

## Expected Outcome
Application is successfuly deployed on server instance.

## Current Outcome
Redeploy of the application fails. Only undeploy and deploy as separate steps is possible.

## Steps to reproduce (Only for bug reports) 
1.  Start the domain

   ./asadmin start-domain domain1

2. deploy https://github.com/sgflt/payara-test-case

3. confirm that the application is loaded

4. click on redeploy and select the same ear

5. error message is present

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full 
- **JDK Version**: Open JDK8 
- **Operating System**: Linux

**Comment by lprimak** [comment]
I have seen this issue before, and re-reploying the app for the second time will work. Can you confirm this?

**Comment by smillidge** [comment]
This is reproducible and only redeployment is affected.
The application can be undeployed and then deployed just redeploy is failing. 
Reload also works as expected.

**Comment by rdebusscher** [comment]
Hi,

is this with any ear file or only a specific one.

I tried it on Payara 5.194 and redeployment of ear was successful.

Regards
Rudy

**Comment by OndroMih** [comment]
Please, can you please provide us a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. Otherwise we’ll have to close this issue.

**Comment by sgflt** [comment]
Seems to be fixed at least since 5.194.
