### ISSUE TITLE
EJBTimer Error timer no longer exists

### ISSUE THREAD

**Issue by TinusJ** [payara/Payara#3884]
# Description #
----------
We have multiple timers created on startup, but when we try to view the timers it throws 
javax.ejb.NoSuchObjectLocalException: timer no longer exists
	at com.sun.ejb.containers.TimerWrapper.getNextTimeout(TimerWrapper.java:120)
	at com.sun.ejb.containers.TimerWrapper.getTimeRemaining(TimerWrapper.java:101)

## Expected Outcome
List all the running schedulers

## Current Outcome

javax.ejb.NoSuchObjectLocalException: timer no longer exists
	at com.sun.ejb.containers.TimerWrapper.getNextTimeout(TimerWrapper.java:120)
	at com.sun.ejb.containers.TimerWrapper.getTimeRemaining(TimerWrapper.java:101)

## Steps to reproduce (Only for bug reports) 

1. Create a non persistent timer 
2. Create a list which will get all the timers from the TimerService
3. Source code attached

### Samples

    @Resource
    private TimerService timerService;

    public Collection<Timer> getTimers() {
        return timerService.getAllTimers();
    }

    @Schedule(minute = "*", hour = "*", persistent = false, info = "First Schedule")
    private void firstSchedule() {
        System.out.println("Running first Scheduler");
    }

## Context (Optional)

We are trying to see the running schedulers.  It is possible to call the toString on the timer but if we try to call anything else on the timer like getInfo() it says the timer does not exist
![image](https://user-images.githubusercontent.com/16685359/55791980-fc520d80-5abf-11e9-811f-3e14dc9dd7b0.png)

## Environment ##

- **Payara Version**:  Payara Server 5.191 #badassfish (build 94)
- **Edition**:  Full
- **JDK Version**: openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview2-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)
- **Operating System**:Windows 
- **Database**: PostGres
[NonPersistentTimer.zip](https://github.com/payara/Payara/files/3058326/NonPersistentTimer.zip)

**Comment by TinusJ** [comment]
@rdebusscher Any news on this?

**Comment by rdebusscher** [comment]
Hi @TinusJ 

A bug issue is created internally to fix this. It is not yet scheduled for a fix version.
