### ISSUE TITLE
Http Status 401 with Spring Security

### ISSUE THREAD

**Issue by conting** [payara/Payara#3889]
# Description #
----------

## Current Outcome
Im currently trying to get a Spring Boot application working in Payara. 
Im using jwt for authentication and the login works correctly. But on every other request I am getting a "401 This request requires HTTP authentication error". With Tomcat everything is working correctly.

This is my Spring Boot Http configuration

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and().csrf().disable().httpBasic().disable().
                authorizeRequests()
                .antMatchers("/api/auth/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .exceptionHandling().authenticationEntryPoint(unauthorizedHandler)
                .and()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .addFilterBefore(authenticationJwtTokenFilter(), UsernamePasswordAuthenticationFilter.class);
    }

Unauthorized handler

    @Override
    public void commence(HttpServletRequest request,
                         HttpServletResponse response,
                         AuthenticationException e)
            throws IOException, ServletException {

        logger.error("Unauthorized error. Message - {}", e.getMessage());
        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, e.getMessage());
    }

I also removed 

     <login-config>
        <auth-method>BASIC</auth-method>
      </login-config>

from default-web.xml.

I can provide the Payara logs if needed.
## Environment ##

- **Payara Version**: 5.191 Build 94
- **Edition**:  Full
- **JDK Version**: OpenJDK 8
- **Operating System**:  Ubuntu
- **Database**:  Postgres 10

**Comment by mulderbaba** [comment]
@conting a self contained example would be a great, care to share a github repo?

**Comment by conting** [comment]
I'm very sorry, but I'm afraid that's not possible. But I was able to solve the problem myself. 

I searched a bit in the Spring documentation and found this here: 
https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#delegating-filter-proxy

I created a web.xml in my WEB-INF Folder and added a DelegatingFilterProxy.

This is how my web.xml looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         metadata-complete="true"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         id="WebApp_ID" version="3.0" >
    <filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>
            org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSecurityFilterChain</filter-name>
        <url-pattern>/**</url-pattern>
    </filter-mapping>
</web-app>
```

**Comment by smillidge** [comment]
OK thanks for letting us know

**Comment by eduardo-zavala** [comment]
Hello !
Could you give me more information on how to solve this problem?

Thank you

**Comment by vishnuvuyyur1** [comment]
You need to add the following to your configure method /error is the default fall back when error occurs to the application due to any exception and it is secured by default.

    protected void configure(HttpSecurity httpSecurity) throws Exception {
    //disable CRSF
    httpSecurity
            //no authentication needed for these context paths
            .authorizeRequests()
            .antMatchers("/error").permitAll()
            .antMatchers("/error/**").permitAll()
            .antMatchers("/your Urls that dosen't need security/**").permitAll()
Also the below code snippet

 @Override
 public void configure(WebSecurity webSecurity) throws Exception
   {
     webSecurity
    .ignoring()
        // All of Spring Security will ignore the requests
        .antMatchers("/error/**")
     }  
Now you will not get 401 and get 500 exception with details when an exception occurred for permitAll Urls

**Comment by AndreasPatsimas** [comment]
The solution with web.xml does not work for me. Any other suggestions??
Thank you.

**Comment by fturizo** [comment]
@AndreasPatsimas, to get advice on your situation go to the [Payara Forum](https://forum.payara.fish/c/technical-discussion) and raise a topic describing it in detail.
