### ISSUE TITLE
Problems with security-constraint and resources

### ISSUE THREAD

**Issue by mikraus94** [payara/Payara#3907]
# Description #
----------
**Only while using Firefox**
Error is occurred if is accessed xhtml that contains `<ui:composition template="#{resource['templates:layout.xhtml']}"` and **security-constraint** is set in _web.xml_ for this xhtml.

## Expected Outcome

ajax.xhtml page should be loaded without error.

## Current Outcome

Error on ajax.xhtml:

`/ajax.xhtml @6,62 <ui:composition template="#{resource['templates:layout.xhtml']}"> Invalid path : file:/app/domains/cis-krausm/applications/test-case-0/core_jar/META-INF/resources/templates/layout.xhtml;jsessionid=05249b0ef3fbec3f0173f3e86e16`

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -** Create test user on file realm

    ./asadmin create-file-user --groups AJAX_VIEW --authrealmname file testuser
    Then choose any password and remember it.
     
3 -** Deploy https://github.com/mikraus94/payara-test-case

4 -**  Access web app  (e.g. http://localhost:8080)
  
    You should be redirected to http://localhost:8080/login/login

5 -**  Delete all cookies for localhost

6 -** Login with user created in step 2

7 -** Access http://localhost:8080/bug/ajax.xhtml

     The error should appear.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: 8u212 - OpenJDK
- **Operating System**: Linux
- **Browser**: Mozilla Firefox

**Comment by mikraus94** [comment]
Same issue on Payara Version: 5.192

**Comment by mikraus94** [comment]
Same issue on Payara 5.194. Issue is related with https://github.com/eclipse-ee4j/faces-api/issues/1011

**Comment by fturizo** [comment]
@mikraus94, unfortunately, your reproducer is not working correctly. When trying to access the login page at http://localhost:8080/login/login I get the following error:

    javax.servlet.ServletException: Wrapper cannot find servlet class cz.i.LoginServlet or a class it depends on
    root cause
    java.lang.ClassNotFoundException: cz.i.LoginServlet

It seems that there is a classloading issue with the Servlet configuration on your reproducer. Can you check that your reproducer is working as intended, or provide a simpler reproducer that showcases the issue?

**Comment by mikraus94** [comment]
@fturizo , there is new repository. I've recorded screen for simplicity.
[Youtube link](https://youtu.be/Zm6qGM2MUR4)
[GitHub link](https://github.com/mikraus94/payara-test-case-3907)

Use step by step guide or follow youtube movie.

Step by step:
1. 
./asadmin create-domain test-case

2.
./asadmin start-domain test-case

3.
./asadmin create-file-user --groups AJAX_VIEW --authrealmname file testuser
Then choose any password and remember it.

4.
deploy ear

5.
enable SSO at HTTP service

6.
go to http://localhost:8080

7.
login with  testuser and chosen password

8.
delete cookies

9.
go to http://localhost:8080/login/login

10.
go to http://localhost:8080/bug/jsf.xhtml

**Comment by fturizo** [comment]
@mikraus94, many thanks for submitting a valid reproducer. I have examined it locally and found the problem on your application: The problem in general is caused by classloading issues that prevent the custom resource resolver defined in your `core` module.  I see that you are defining multiple shared components and resources (Servlet Filters, Resource Resolvers, Facelet templates) in this module, but you are defining that module as an EJB-JAR (which makes no sense) and configuring it as a sub-module for the entire EAR assembly. JSF configuration won't actually read the `faces-config.xml` configuration file in this way since this structure is not supported:

> You can have more than one application configuration resource file for an application. The JavaServer Faces implementation finds the configuration file or files by looking for the following.
> *A resource named /META-INF/faces-config.xml in any of the JAR files in the web application’s /WEB-INF/lib/ directory and in parent class loaders. If a resource with this name exists, it is loaded as a configuration resource. This method is practical for a packaged library containing some components and renderers. In addition, any file with a name that ends in faces-config.xml is also considered a configuration resource and is loaded as such.
> * A context initialization parameter, javax.faces.application.CONFIG_FILES, in your web deployment descriptor file that specifies one or more (comma-delimited) paths to multiple configuration files for your web application. This method is most often used for enterprise-scale applications that delegate to separate groups the responsibility for maintaining the file for each portion of a big application.
> * A resource named faces-config.xml in the /WEB-INF/ directory of your application. Simple web applications make their configuration files available in this way.

To make your application work correctly, you have to define the `core` module as an included library in either the `/lib` folder of the EAR assembly or in the `/lib` folder of each WAR module. Also, the module should be a simple JAR file instead. I have tested both solutions and your scenario works without problems so I'll proceed to close this issue since it is a configuration issue.
