### ISSUE TITLE
5.191 System Properties not saved to SSH Node Instances

### ISSUE THREAD

**Issue by justindavidcotton** [payara/Payara#3913]
# Description #
----------

Payara Server 5.191, RedHat 7, JDK 8

System Properties are not being dynamically configured/saved on SSH Node Instances.  Instance restart is required to reflect the added/updated System Properties.

## Expected Outcome

If Dynamic Reconfiguration is checked, System Property changes made in the DAS Admin UI should be immediately reflected in the Instances that share the Configuration.  Restart should not be required.

## Current Outcome

When System Properties are added or changed in the DAS Admin UI for a specific Configuration, the UI reflects that the changes were saved successfully.  The changes are being saved to the DAS domain.xml, but they are not reflected in the Instance domain.xml files.  Instances require restarting for the changes to be reflected.  Dynamic Reconfiguration is checked, and the Data Grid is enabled.  The Instances are associated to the Configuration being modified, and the Instances are members of the same Deployment Group.  There is no issue with SSH connectivity between the DAS and Nodes.

We have two identical (5.191) environments - 1 x DAS -> 2 SSH Nodes each with 2 Instances.  This issue persists on both.

## Steps to reproduce (Only for bug reports) 

1. Login to DAS Admin UI.
2. Modify or Add a System Property in Configuration.
3. Validate change in DAS domain.xml.
4. Validate change in Instance domain.xml.

## Context (Optional)

We recently migrated from GF 4.1.2.  We did not experience this issue with GF.

We update System Properties during deployments to manipulate the behavior of our applications.  It is time consuming to restart Instances in the middle of a deployment cycle.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Server
- **JDK Version**: JDK 8
- **Operating System**: RedHat 7

**Comment by rdebusscher** [comment]
Hi, 

I tried to reproduce the behavior on version 5.194 and I was unable to. I created a domain with 2 SSH nodes and deployed an application that reads a certain System Property.

When the System property is written to the config used by the instances, it is immediately picked up by the deployed application.

So the problem is solved.

Regards
Rudy
