### ISSUE TITLE
Payara Micro --interfaces option does not support wildcard

### ISSUE THREAD

**Issue by edthorne** [payara/Payara#3914]
# Description #
----------

I recently enabled clustering of Payara Micro on Docker Swarm and noticed a peculiar issue when trying to get the containers to work together. When specifying the `--interfaces` value to be used, the command line help suggests wildcards can be used and that the values are comma separated. _I believe the second address below being comma separated is an error._

> --interfaces                                   Specifies the Interfaces that the data grid discovery mode should use to listen can be comma separated e.g. 127.0.0.1,192,168,0,*

The [Hazelcast documentation](https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#interfaces) indicates that wildcards (192.168.0.*) and ranges (192.168.0.0-15) are supported.

The other issue is that the [MemberAddressProvider](https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#member-address-provides-spi) is likely unnecessary when `--interfaces` has been specified. I'm not 100% certain of this but my growing Hazelcast knowledge suggests that MemberAddressPicker is in place to identify the public and bind addresses. The public address is already being set directly in the network configuration at [HazelcastCore.java:400](https://github.com/payara/Payara/blob/master/nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java#L400). If `--interfaces` tells Hazelcast what interfaces to use, then the bind address should come from that list of addresses (wildcarded, ranged, or single address). I'm hoping @smillidge has more context.

## Expected Outcome

Specifying `--interfaces` should result in the Hazelcast instance using the interfaces specified and not a random interface selection.

## Current Outcome

If interfaces is specified as a range, `192.168.0.2-15`, the matching interface is **not** selected. The bind address returned from `MemberAddressPicker` is used.

If interfaces is specified as a wildcard, `192.168.0.*`, the matching interface is **not** selected. The bind address returned from `MemberAddressPicker` is used.

To get the proper interface to be selected, every IP address in the range **must** be enumerated in the configuration without whitespace: `192.168.0.2,192.168.0.3,...,192.168.0.15`

## Steps to reproduce 

See the sample `docker-compose.yml` file for a simple deployment example that demonstrates the workaround as well as the expected solution.

### Samples

Deploy the [docker-compose.yml](https://gist.github.com/edthorne/bb3621db9e30b2b4e9eba0db8d018fd4) to a single node Docker Swarm.

## Context

The linked Docker compose file defines a reverse proxy and a set of clustered micro instances. The goal is to have the micro instances communicate with each other only over the cluster network. It uses the stock `payara/micro:5.191` image.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Micro
- **JDK Version**: OpenJDK 1.8.0_191
- **Operating System**: Linux

**Comment by edthorne** [comment]
@smillidge I just posted a PR that is working for me locally for review.

**Comment by peterpz1** [comment]
Why you specify IP addresses in interfaces list? In my opinion (and I asked 3 my colleagues) interface is the interface name. So on Linux e.g. eth0, eth1, etc.

**Comment by edthorne** [comment]
@peterpz1 you'd have to ask the Hazelcast team why they called this configuration parameter interfaces. The Payara team has simply reused the same naming, I assume for clarity. The Hazelcast documentation, linked above, identifies what can be put in the configuration. The interface name is not one of them. 

In my particular use case, how can I know what network the orchestrator will assign to which network interface inside the container? The reality is I can't. I do know the addressable address space for the desired network and would prefer to enumerate that space as a range or wild card, especially when the network space is large.

In the linked configuration example, you'll note I constrained the network to `192.168.0.0/29`. The non-functioning configuration in the example, `192.168.0.1-6` and `192.168.0.*`, demonstrate valid Hazelcast mechanisms for specifying an interface that are currently not working with Payara micro.

The problem could be that mixing `MemberAddressProvider` and Interfaces configuration is incorrect or that the logic in `MemberAddressPicker` needs to take into account the additional valid configuration values for interfaces when matching the available network interfaces when selecting a bind address. The currently submitted PR assumes the former.

**Comment by smillidge** [comment]
Thanks for the PR
