### ISSUE TITLE
isUserInRole not always working with Payara 5.184 /CUSTCOM-252

### ISSUE THREAD

**Issue by richard-grin** [payara/Payara#3918]
In one of my projects request.isUserInRole is not working
----------

In another projects, it is working but in this projects it is not. The only significant difference is the way the users are registered but I don't know if it is the reason.

I use the Security API of Java EE 8. The code of the configuration:
```
@DatabaseIdentityStoreDefinition(
        dataSourceLookup = "java:app/jdbc/login_javaEE8",
        callerQuery = "select password from login where login=?",
        groupsQuery = "select group.name from group join login_group on group.id = login_group.id_group where login=?")
@CustomFormAuthenticationMechanismDefinition(
        loginToContinue = @LoginToContinue(
                loginPage = "/login/login_custom.xhtml",
                errorPage = ""
        )
)
@ApplicationScoped
@FacesConfig(version = FacesConfig.Version.JSF_2_3)
public class Config {
}
```

I enter as an administrator (group admin) and I can get the JSF pages for the administrators but, if the page contains `#{request.isUserInRole("admin")}`, false is printed. It should be true.

The same if I use isUserInrole("admin") in a backing bean. 

If I use JPA to know if a user is an administrator, **it works**:
```  
public boolean isAdmin() {
    List<String> nomsGroupesUtilisateur 
       = loginFacade.findNomsGroupesUtilisateur(principal.getName());
    return nomsGroupesUtilisateur.contains("admin");
  }
```
with
```
public List<String> findNomsGroupesUtilisateur(String nomLogin) {
    TypedQuery<String> query = em.createNamedQuery("Login.findNomsGroupesUtilisateur", String.class);
    query.setParameter("nomLogin", nomLogin);
    return query.getResultList();
  }

```
and the request Login.findNomsGroupesUtilisateur is defined by
```
@NamedQuery(name = "Login.findNomsGroupesUtilisateur",
        query = "select g.nom from Login l join l.groupes g where l.login = :nomLogin")
```
which is the same request as the request given in the configuration of the class Config if I am not mistaken.

## Steps to reproduce
I enter the application.
I choose one of the option of the menu and I am asked my login and password; I enter the login of an administrator. Then I choose another option reserved for administrators.
The page is displayed (so I am considered as an administrator) but in the page, isUserInRole displays false instead of true.

GIT repository: https://github.com/richard-grin/testisuserinrole
Sorry, it is not a Maven project.

If you use NetBeans, I join a zip file of my project exported from NetBeans 9.0.
Take care, an initialization is made in a database at the beginning (EJB init).
[testisuserinrole.zip](https://github.com/payara/Payara/files/3126540/testisuserinrole.zip)

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 1.8
- **Operating System**: Windows 
- **Database**: Java DB (provided with NetBeans 9.0)

**Comment by smillidge** [comment]
Thanks for the test case we will try to reproduce.

**Comment by richard-grin** [comment]
Hi smillidge,
Did you try to reproduce the problem?

**Comment by smillidge** [comment]
Not yet

**Comment by OndroMih** [comment]
This might be related to #4596, maybe even the same issue as it also reports that the user is authenticated but with no roles.

**Comment by OndroMih** [comment]
Hi @richard-grin, I was able to reproduce on Payara Server 5.194 when I added the following libraries to your project in Netbeans:

* Instead of Validation I added Java EE 8 API library
* PrimeFaces_7.0 - I downloaded Primefaces 7.0 from Maven and created a new library in Netbeans
* Driver_Java_DB - I removed this library as Derby exists in Payara Server.

Since Derby DB is removed in Payara Server 5.201, I reproduced on 5.194. However, I suspect that this isn't specific to the DatabaseIdentityStore and I believe I'll be able to reproduce this with much simpler example without a database.

When I debugged the DatabaseIdentityStore, it correctly retrieves groups and adds them to the created `CredentialValidationResult`.

**Comment by OndroMih** [comment]
As I expected, when I removed the `@DatabaseIdentityStoreDefinition` definition and added a test IdentityStore similar to [this one](https://github.com/javaee/tutorial-examples/blob/master/security/security-api/custom-identity-store/src/main/java/javaeetutorial/custom_identity_store/TestIdentityStore.java), the application still behaves the same and doesn't show user's roles.

**Comment by OndroMih** [comment]
Hi @richard-grin, it seems this isn't a bug but it doesn't work because the `admin` role is defined as an application role. If you want to use roles to restrict access, it's not enough to define the restriction in a `<security-constraint>` element but you also need to define that the role is used by the applications.

You can do it by 2 ways:

* in web.xml, add the `security-role` element for every role your application uses. E.g. for `admin`:

```
  <security-role>
      <role-name>admin</role-name>
  </security-role>
```

* or you can define the roles in the Java code using `@DeclareRoles`. So in your `Config` class, you can add the following to declare all the roles used in your web.xml:

```
@DeclareRoles({"admin", "enseignant", "etudiant"})
```

**Comment by richard-grin** [comment]
Thanks a lot Ondro for your help and your research on this point.

Right now, I am on another project but as soon as possible I will go 
back to the project that had the problem you studied, and test it with 
the information you give me.

Sorry for the inconvenience if it's just this oversight that caused the 
problem.

Regards,

Richard

Le 07/04/2020 à 14:35, Ondro Mihályi a écrit :

**Comment by richard-grin** [comment]
Hello Ondro,

I have added the declaration of the roles in web.xml and everything's 
going well now. I tested with Payara 5.201 and MySQL.

I don't know why I forgot this declaration of the roles. I did'nt forget 
it in my other projects; hence the title "is not **always** working...".:-(

Would it be possible to add a message for this kind of error (not so 
easy to find out), saying that some roles have not been defined, when a 
not defined role is used in a configuration file or elsewhere?

Once again, I would like to thank you.

Richard

Le 07/04/2020 à 14:36, Ondro Mihályi a écrit :

**Comment by Impesud** [comment]
@OndroMih 

> Hi @richard-grin, it seems this isn't a bug but it doesn't work because the `admin` role is defined as an application role. If you want to use roles to restrict access, it's not enough to define the restriction in a `<security-constraint>` element but you also need to define that the role is used by the applications.
> 
> You can do it by 2 ways:
> 
>     * in web.xml, add the `security-role` element for every role your application uses. E.g. for `admin`:
> 
> 
> ```
>   <security-role>
>       <role-name>admin</role-name>
>   </security-role>
> ```
> 
>     * or you can define the roles in the Java code using `@DeclareRoles`. So in your `Config` class, you can add the following to declare all the roles used in your web.xml:
> 
> 
> ```
> @DeclareRoles({"admin", "enseignant", "etudiant"})
> ```

@OndroMih , a thousand thanks!
I am working with Payara 6.2023.12 and I had the same problem.
It works with the first solution, but not with the second:
   <security-role>
       <role-name>admin</role-name>
   </security-role>
