### ISSUE TITLE
Payara not sending Sec-WebSocket-Protocol to Client when using Spring Websockets

### ISSUE THREAD

**Issue by conting** [payara/Payara#3933]
# Description #
----------
I am currently trying to implement Spring Websockets in Payara. I've done this so far, but when I try to connect, the server doesn't return a Sec-WebSocket-Protocol. In Google Chrome I get the following error: 

    Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received.

Request and Response as Image shown in Google Chrome: 

![CKV0s](https://user-images.githubusercontent.com/11525385/57352590-21d94200-7166-11e9-861a-2274831a335f.png)

As a Stomp Client, I am using ng2-stompjs in Angular.

I tried on Tomcat 9.0.17 and WildFly 16 and everything is working as expected.

WebSocket Configuration:

```
@Configuration
@EnableWebSocketMessageBroker
@EnableWebSocket
public class WebSocketConfiguration implements WebSocketMessageBrokerConfigurer {

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry
                .addEndpoint("/ws")
                .setAllowedOrigins("*");
    }

    @Override
    public void configureMessageBroker(MessageBrokerRegistry registry) {
        registry.setApplicationDestinationPrefixes("/app");
        registry.enableSimpleBroker("/topic");
    }
}
```

glassfish-web.xml:
```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
    <context-root>/monitoring</context-root>
    <classloading-delegate>false</classloading-delegate>
    <parameter-encoding default-charset="UTF-8"/>
</glassfish-web-app>
```

build.gradle:
```
plugins {
    id 'org.springframework.boot' version '2.1.4.RELEASE'
    id 'java'
    id 'war'
}

apply plugin: 'io.spring.dependency-management'

group = 'de.conting'
version = '0.0.1'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}
configurations {
    compile.exclude module: 'spring-boot-starter-tomcat'
    compile.exclude group: 'org.apache.tomcat'
}

war {
    enabled = true
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jersey'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-quartz'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    implementation 'org.hibernate:hibernate-core:5.4.2.Final'
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    runtimeOnly 'org.postgresql:postgresql'
    providedCompile group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'
    compileOnly 'org.projectlombok:lombok:1.18.6'
    annotationProcessor 'org.projectlombok:lombok:1.18.6'
}

```
## Steps to reproduce
1 -**  Build .war with Gradle from repository below.
2 -**  Deploy in Payara
3 -**  Install Client Packages with ```npm install```
4 -**  Run Client with ```ng serve```

### Samples
Example Github Repository: https://github.com/conting/StompGlassfishExample

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: Java 8u212
- **Operating System**: Windows 10 Build 17763
- **Database**: Postgres 10

EDIT: Provided more Information on the issue

**Comment by fturizo** [comment]
As Spring-Websockets is not a standard technology that is part of the technology stack of Payara Server, we can offer much assistance on how to correctly making them work in your reproducer scenario.  If you require further assistance on this issue, we'd recommend you getting expert assistance with Payara Enterprise.
