### ISSUE TITLE
OpenAPI Generation refers to the base class instead of the extending class

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#3937]
# Description #
----------

## Expected Outcome
We have a REST service with a response object inheriting from a base class. I expect that when I generate the service specification with OpenAPI that in the response section (response code 200) the extending class is referred.

## Current Outcome

In the response section (response code 200) the base class is referred (see txt file).

## Steps to reproduce (Only for bug reports)
We build a simple project to reproduce.

## Environment ##
- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: OpenJDK8
[testopenapi.zip](https://github.com/payara/Payara/files/3157301/testopenapi.zip)
[generated_openapi.txt](https://github.com/payara/Payara/files/3157302/generated_openapi.txt)

**Comment by jbee** [comment]
Thanks for reporting the problem. 

Had a quick look and based on the example and output given I am fairly sure this is a defect. Since we updated OpenAPI after 5.184 we should first see if the problem still exists in 5.192.

**Comment by jbee** [comment]
Made the example into a test. Problem still present in 5.192.

**Comment by jbee** [comment]
Created internal ticket https://payara.atlassian.net/browse/PAYARA-3816

**Comment by jbee** [comment]
@deratzmann I am no longer sure this is a defect. If a schema is referenced using `implementation` the schema created for the annotation uses the `implementation` class as basis of the created schema. This class inherits from `FooResponseBase` wherefore it has a `allOf` reference to that base class. 

To literally refer to  the schema `FooResponse` I think the annotation should use `ref`:
```java
@Schema(ref = "FooResponse")
```

**Comment by jbee** [comment]
@deratzmann Please have a look at my comment above - do you still think this is a defect or does this clarify why you get the results and how to fix it?

**Comment by deratzmann** [comment]
Yes, that fixes our issue. Thank you, very much.
