### ISSUE TITLE
EJBContainer settings are omitted

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#3948]
# Description #
----------

EJB Container can be configured from asadmin WEB GUI, which results in change in domain.xml configuration file, like that:
`
      <ejb-container max-pool-size="120" pool-resize-quantity="16" steady-pool-size="10">
        <ejb-timer-service></ejb-timer-service>
      </ejb-container>
`
But those settings are not taken into account:

`[2019-05-14T15:47:20.616+0200] [Payara 5.184] [FINE] 
  Created EjbThreadPoolExecutor with thread-core-pool-size 16 thread-max-pool-size 32 thread-keep-alive-seconds 60 thread-queue-capacity 2147483647 allow-core-thread-timeout false ]]`

But configuring container manually like that:
      `<ejb-container max-pool-size="120" pool-resize-quantity="16" steady-pool-size="10">
	    <property name="thread-core-pool-size" value="128"></property>
		<property name="thread-max-pool-size" value="128"></property>
        <ejb-timer-service></ejb-timer-service>
      </ejb-container>`

The new values (128) are taken into account properly:
`[2019-05-14T15:53:49.028+0200] [Payara 5.184] [FINE] 
  Created EjbThreadPoolExecutor with thread-core-pool-size 128 thread-max-pool-size 128 thread-keep-alive-seconds 60 thread-queue-capacity 2147483647 allow-core-thread-timeout false ]]`

## Expected Outcome

Proper configuration of EJB container according documentation.

## Current Outcome

Configuration inputted in web gui is doing nothing. You think you've reconfigured server for production, but it still has only 16 EJB threads.

## Steps to reproduce (Only for bug reports) 

Change EJB Container config, increase log levels on javax.enterprise.system.container.ejb.com.sun.ejb.containers and check if changes in config are visible in the log after domain restart.

### Samples

Mentioned above.

## Environment ##

- **Payara Version**: Payara Server 5.184 #badassfish (build 89)
- **Edition**:  Full
- **JDK Version**:  jdk1.8.0_191 (oracle)
- **Operating System**: Linux
- **Database**: not important

**Comment by peterpz1** [comment]
For us this issue was critical, causing huge problems on the production environment. I'm wondering - are we wrong or nobody is deploying Payara on production?

**Comment by smillidge** [comment]
There is no way to configure the thread pool size settings from the web gui. What you are changing is the bean pool size which is different. There are many people deploying Payara successfully in production. We also provide production support if you need assistance in production environments.

**Comment by OndroMih** [comment]
You can set the `thread-core-pool-size` property and other properties in the Admin console as properties of the EJB container. Don't confuse this with setting the EJB pool settings, which are for pools of EJB Java objects and not threads.

Details in our forum: https://groups.google.com/d/msg/payara-forum/_uDL9uXCh1s/xGysEY7FCAAJ
