### ISSUE TITLE
Payara + JCache + Hazelcast + JDK8 (JDK7 works)

### ISSUE THREAD

**Issue by trajano** [payara/Payara#397]
It seems that Payara is using Hazelcast to do session clustering based on https://github.com/payara/Payara/wiki/Hazelcast-%28Payara-4.1.151%29#5-using-hazelcast-in-your-applications which is well and good.

However, it seems it is using a Payara specific JCache API and is causing a 

    <dependency>
    <groupId>fish.payara.appserver</groupId>
    <artifactId>payara-jsr107</artifactId>
    <version>4.1</version>
    <type>jar</type>
    <scope>provided</scope>
    </dependency>

And not the one from the spec which is what Hazelcast is using according to https://github.com/hazelcast/hazelcast/blob/master/pom.xml#L925

    <dependency>
    <groupId>javax.cache</groupId>
    <artifactId>cache-api</artifactId>
    <version>1.0.0</version>
    </dependency>

On a *fresh* install JDK8 it seems to fail, but if I switch to JDK7 then stop and then switch to JDK8 it seems to start working which is a bit.  Not sure why it had that pattern.

I will reference the code that is causing this issue shortly.

**Comment by smillidge** [comment]
Our payara-jsr107 module is just the standard one with some additional OSGI exports in the jar. The standard cache-api jar does not have the correct OSGI exports.https://github.com/jsr107/jsr107spec/issues/326

**Comment by trajano** [comment]
I can't seem to find the payara modules in maven central
http://search.maven.org/#search|ga|1|payara-jsr107

**Comment by trajano** [comment]
Trying to use the provided scope like the example in the wiki as follows

    <dependency>
    <groupId>javax.cache</groupId>
    <artifactId>cache-api</artifactId>
    <version>1.0.0</version>
    <scope>provided</scope>
    </dependency>

Gives this
<pre>
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of org/glassfish/web/loader/WebappClassLoader) previously initiated loading for a different type with name "javax/cache/spi/CachingProvider"
</pre>

**Comment by trajano** [comment]
Hmm now it's not even starting up correctly.  Oh well :(

Maybe if Payara made it so that rather than using JCache API and embed hazelcast as is, it can be shaded so that the implementation of the session cache does not add to the class path that may not have been unintended.

Though I think that would be a bit of rework on the core and upstream to make it so.

I'll stick with Glassfish core for the time being as I need to have a JCache implementation that I can access on my app.  I'll revisit this issue later.

**Comment by smillidge** [comment]
Payara provides full JCache support. Rather than just using Hazelcast for session persistence. You can inject the CacheManager using @CacheManager you can also inject a cache using @Cache. You can also use the standard JCache annotations directly.

I would need to see a test case to understand what is happening in your case.

**Comment by trajano** [comment]
Ok let me try that one, the full test case is hard to put in because it is in the proprietary portion of the app.  I was thinking maybe exposing JCache to apps on Payara should be optional rather than implicit.  Or at least can be toggled off without resorting to "PARENT_LAST"

**Comment by trajano** [comment]
Anyway the reason I am using a cache isn't for improving performance per se.  It's more of a "non-important" data store for security e.g. one-time-use codes or nonces.  I don't care much about persisting it, but I need to make sure it works on a distributed environment.  All JavaEE provides is session replication which is not enough because the data I am dealing with is application wide.  In theory I can use a database but I thought that would be way overkill for something I don't need to store in the long term.

**Comment by trajano** [comment]
So what I have done to get my app working correctly in Payara was to remove the use of JCache in my application and also change my hazelcast dependency to `provided`.  At least there's a work around in case I have to deploy on this AS.  Though there was no need to do those work around in Glassfish.

**Comment by mikecroft** [comment]
Is this still an issue? Just for reference, we have an example which uses the `javax.cache` dependency with no problems:
https://github.com/payara/Payara-Examples/blob/master/rest-examples/rest-jcache/pom.xml#L24

**Comment by trajano** [comment]
Haven't been working on it. But you should be able to close if you have a working example now. 

--
trajano.net




On Mon, Sep 12, 2016 at 5:33 AM -0400, "Mike Croft" <notifications@github.com> wrote:












Is this still an issue? Just for reference, we have an example which uses the javax.cache dependency with no problems:

https://github.com/payara/Payara-Examples/blob/master/rest-examples/rest-jcache/pom.xml#L24

**Comment by mikecroft** [comment]
Thanks @trajano!
