### ISSUE TITLE
Default deployment group name should not contain Shoal since it is no longer used

### ISSUE THREAD

**Issue by jbee** [payara/Payara#3977]
## Summary

If I understand correctly the previous cluster tech was named "shoal" wherefore I assume the default name for deployment groups became "MicroShoal". This seems no longer appropriate. 

## Expected Outcome
```
Instances: {
 DataGrid: development Instance Group: ??? Name: server Lite: false This: true UUID: cbb0834d-a4b9-48c9-baea-512935bff696 Address: /192.168.1.100:4900
}
```

## Current Outcome
```
Instances: {
 DataGrid: development Instance Group: MicroShoal Name: server Lite: false This: true UUID: cbb0834d-a4b9-48c9-baea-512935bff696 Address: /192.168.1.100:4900
}
```

## Environment ##

- **Payara Version**: 5.192

**Comment by smillidge** [comment]
Feel free to create a PR

**Comment by OndroMih** [comment]
Shoal also means a group of fish in English. So the name is still relevant and it doesn't specifically relate to the Shoal technology.
