### ISSUE TITLE
Eclipselink bytecode weaving breaks remote EJBs via RMI/IIOP

### ISSUE THREAD

**Issue by AleksNo** [payara/Payara#3996]
# Description #
----------
Hello, we have an Eclipse RCP application which communicates with the Payara server over RMI/IIOP. The problem is, the Eclipselink bytecode weaving feature deletes the data in the JPA entity which is transferred from the client to the server over RMI/IIOP. All attributes in the JPA entity are set to null.

## Expected Outcome
When the client makes a remote procedure call to the server and the procedure has a JPA entity as a parameter then after deserialization all attributes in JPA entity should have the same values like the JPA entity in the client.

## Current Outcome
All attributes in the JPA entity are null after deserialization.

## Steps to reproduce (Only for bug reports)

1. Create a remote EJB project whith a client, which can make remote procedure calls on the server.
2. Create a simple JPA entity with all neccesary annotations.
3. Enable bytecode weaving in the persistence.xml. The parameter is: name="eclipselink.weaving" value="true"
4. Create a procedure which can be called from the client on the server. This procedure should have the JPA entity from point 2 as a parameter.
5. Instantiate the JPA entity in the client and assign some values to the attributes in the entity.
6. Make the remote procedure call from the client to the server.
7. Check the values of the JPA entity in the server. Now they will be null.

Providing unit test will be hard. :/

## Workarounds

There are three possible workarounds for this problem. But they have all some drawbacks.

1. Disable bytecode weaving. The drawback is that all OneToOne/ManyToOne-assotiations will be fetched eagerly. Even if they are annotated with FetchType.LAZY.

2. Implement Externalizable. See drawback 1 + also all OneToMany-assotiation will be also fetched eagerly. This is much worse.

3. Use Hibernate. 

## Environment ##

- **Payara Server 4.1.1.164** #badassfish (build 28) and Payara Server 5.192 #badassfish (build 115)
- **JDK Version**: 1.8.212 Hotspot and OpenJ9
- **Operating system:** Linux and Windows
- **Database:** Should be independent. But we use IBM DB2 LUW 10.5 

Greetings

**Comment by svendiedrichsen** [comment]
I have found a third option from this post https://www.eclipse.org/lists/eclipselink-users/msg05745.html

Use static weaving and use the woven entities on both sides of the RMI communication.

**Comment by AleksNo** [comment]
Hi, 

thank you. "eclipselink.weaving.fetchgroups=false" fixed it for me. Since we do not use the fetch group feature it has no negative side effects.

A side note, this bug is very old:
https://github.com/eclipse-ee4j/glassfish/issues/16164

It would be nice when this behavior would be documented somewhere. I can imagine that other users will run into this issue too and spend hours for debugging.

Thanks.

Greetings

**Comment by OndroMih** [comment]
@AleksNo can you help us fix this by creating a simple reproducer that uses the embedded H2 database?

**Comment by AleksNo** [comment]
Hi and sorry for the late answer. I have made a small remote EJB project and i hope it is usable for you.

I have also tried the "weaving on both sides" thing and the behavior is still strange. Almost all additionally weaved properties and attributes are null after deserialization in the EJB client. And i don't know whether it is broken and has negative impacts or it is intention or something else. 

Greetings

[weaving_tests.zip](https://github.com/payara/Payara/files/3757712/weaving_tests.zip)

**Comment by OndroMih** [comment]
Hi @AleksNo , thank you for an example project. Can you please add instructions how to use it to reproduce the problem?

**Comment by OndroMih** [comment]
Hi @AleksNo, can you explain how I can build and deploy your example project? I see the source code but I struggle to understand how to use it to reproduce the problem.

**Comment by khasunuma** [comment]
Hi @AleksNo, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.
