### ISSUE TITLE
FormParam do not work by using a Request-Filter with a ConversationScoped bean

### ISSUE THREAD

**Issue by geopossachs** [payara/Payara#3997]
# Description #3968 
----------

We have simple Jax-Rs Resource with a POST Method and a FormParam in it. It works without problems. Then we add a Jax-Rs Filter. We inject into this Filter a ConversationScoped Bean.

## Expected Outcome

I would expect the default behavior. We get the submitted value by the FormParm in the POST Method

## Current Outcome

But now the FormParm ist NULL. We have tried a lot. The Bug happens by accessing the ConversationScoped Bean in the Filter. I circumnavigate the Bug by using a SessionScoped Bean. By using a SessionScoped Bean we get the submitted FormParam in the POST Method

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: 8 u162 - Oracle
- **Operating System**: Windows
- **Database**:

**Comment by smillidge** [comment]
Can you provide a test case application hosted on GitHub or somewhere else that we can use to easily reproduce the problem?

**Comment by geopossachs** [comment]
yes, i have set up an example maven project with netbeans here https://github.com/geopossachs/payara-demo

in this commit i have add a filter to trigger the bug
https://github.com/geopossachs/payara-demo/commit/fdaed651a4c75f4d1bbfa6f6122387105fd97fec
the line 40 is active there to trigger the bug

**Comment by smillidge** [comment]
Just noticed you mentioned `ConversationScopedBean` a `ConversationScopedBean` doesn't make sense in the context of a REST call.

**Comment by geopossachs** [comment]
You are right in a stateless RESTfull API it doesn't make sense to use a ConversationScoped-Bean. 

But your customer would like to have support for a multiple-tab Application. 
So you can start the Application in different tab's and you can interact with the same API parallel. 
Over the ConversationScoped-Bean we can store the data of each tab separated.

[https://www.knitelius.com/2015/07/22/cdi-conversations-for-jax-rs-with-jee-6/](url)

**Comment by smillidge** [comment]
I don't know from the test case how to run the test case. Can you provide a curl command to reproduce the issue?

**Comment by geopossachs** [comment]
if the project https://github.com/geoposs achs/payara-demo is running you can submit via curl to the demo rest endpoint

curl "http://localhost:8080/rest" -H "Content-Type: application/x-www-form-urlencoded" --data "cit"%"C3"%"BD=valueA&zip=valueB"

this first request will fail. 
if you disable the source-code in line 40 in _boundary.filter.JaxRsFilter_ the request will work

**Comment by rdebusscher** [comment]
Reproducer code no longer accessible.

**Comment by rdebusscher** [comment]
Closing as reproducer code not accessible and no response.
