### ISSUE TITLE
Payara 5.192 - default JPA provider not supporting java.time.LocalDateTime

### ISSUE THREAD

**Issue by pkumar72** [payara/Payara#4009]
# Description #
----------

I tried to deploy a war file which contained an entity with java.time.LocalDateTime . During deployment , payara server 5.192 failed deployment with error message  "....is not a valid type for a temporal mapping. The attribute must be defined as java.util.Date or java.util.Calendar."

Looks like  the default persistence provider "Eclipse Persistence Services - 2.7.4.payara-p2" in payara 5.192 is not fully supporting LcoalDateTime.  

Error message on payara 5.192 server console:

[2019-06-04T09:11:08.380-0700] [Payara 5.192] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=51 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1559664668380] [levelValue: 1000] [[
  Exception during lifecycle processing
javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [AmsPU] failed.
Internal Exception: Exception [EclipseLink-7165] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The type [class java.time.LocalDateTime] for the attribute [createdDate] on the entity class [class net.neology.ams.entity.BaseEntity] is not a valid type for a temporal mapping. The attribute must be defined as java.util.Date or java.util.Calendar.
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2106)

## Steps to reproduce (Only for bug reports) 

1. create war file with entity as below

import javax.persistence.Id;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "ASSET_TYPE")
public class AssetType  {
    
    @Id
    private Long assetTypeOrd;

    @Column(name = "CREATED_DATE", nullable = false, updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private LocalDateTime createdDate;
    
    @Column(name = "UPDATED_DATE", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private LocalDateTime updatedDate;

}

2. compile and build war file 

3.   Start the domain

    ./asadmin start-domain 

4.  ./asadmin deploy  ~/test/ams/target/asset.war

5. check server log at ~/payara5/domains/domain1/logs/server.log

Deployment fails with error message shown above

## Environment ##

- **Payara Version**: 5.192 (build 115)
- **Edition**:  Full

- **JDK Version**: 
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
(oracle JDK)

- **Operating System**:  Linux

- **Database**:  H2DB  (h2-2019-03-13.zip)

**Comment by scrmtrey91** [comment]
You dont need this annotation: 
@Temporal(TemporalType.TIMESTAMP)

Also you have updatable set to false.

It is working without this. We use LocalDate and LocalDateTime without converters on Payara5 since JPA 2.2 knows how to handle this type by default.

**Comment by phillipross** [comment]
@scrmtrey91 which database platforms are you using where this works w/o converters?

**Comment by scrmtrey91** [comment]
MySQL 8.0.16 server

**Comment by phillipross** [comment]
I suspect this could be database or jdbc driver dependent where eclipselink is concerned.
Late last year when I tried with postgres, I still needed to use converters to get it to work properly... I believe due to some problems with the postgres platform in eclipselink.  I don't believe I had tried it with H2DB though.

**Comment by scrmtrey91** [comment]
JPA 2.2 is supported by Payara5 (first time), before it was not (payara4 i think).

**Comment by khasunuma** [comment]
Supporting Data and Time API is depend on JDBC driver for each database. To use Data and Time API in JPA, you should use JDBC API version 4.2 or later (included JDK 8 or later) and suitable JDBC driver that fully supports JDBC 4.2 API. According to https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/jdbc/JdbcResultSet.java, JDBC driver for H2 database does not fully support JDBC 4.2. (If supports, ResultSet#getObject() should be implemented to handle Date and Time API.)

**Comment by smillidge** [comment]
@pkumar72 do these answers help?

**Comment by pkumar72** [comment]
Hi Steve and scrmtrey91,

Sorry was off the grid last few days. 

Based on scrmtrey91 comments, I tried removed "@Temporal(TemporalType.TIMESTAMP)"  and that did the trick.  It works now on H2DB.  

@scrmtrey91 ,
The updatable = false is not a problem. It is used to indicate that the field should never be updated. This is a audit tracking field (created_date). 

Anyway i need to readup on the @Temporal .

I accept the answers and this works for me now.

**Comment by pkumar72** [comment]
Found some documentation on a blog jeejava.com about this issue.  Let us close this issue.

**Comment by scrmtrey91** [comment]
@pkumar72 great news :)

Ok, i did not know the context of this entity. But if it is for audit , it makes sense not to update when the record is already persisted.
