### ISSUE TITLE
Can't run preboot command add-pkcs8 with Micro /CUSTCOM-120

### ISSUE THREAD

**Issue by johnmanko** [payara/Payara#4010]
# Description #
----------

I'm trying to add a Let's Encrypt private key/cert to a Payara Micro instance with the `add-pkcs8` command in `--prebootcommandfile` file.  The log output doesn't provide any information other than the following:

> [2019-06-04T20:15:36.341+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1559679336341] [levelValue: 900] Boot Command add-pkcs8 failed Exception while executing command. 

The full command in the preboot script is:

`add-pkcs8 --domain_name production --destalias le_mydomain --priv-key-path /opt/payara/cert/privkey.pem --cert-chain-path /opt/payara/cert/fullchain.pem`

and I'm starting via docker:

```
docker run -p 8765:8090 \
 --mount type=bind,src=$(pwd)/deployments,dst=/opt/payara/deployments \
 --mount type=bind,src=$(pwd)/lib,dst=/opt/payara/lib \
 --mount type=bind,src=$(pwd)/cert,dst=/opt/payara/cert \
 --mount type=bind,src=$(pwd)/scripts,dst=/opt/payara/scripts \
 --mount type=bind,src=$(pwd)/logs,dst=/opt/payara/logs \
 --env-file payara.env \
 --restart=always \
 payara/micro:5.192 \
 --prebootcommandfile /opt/payara/scripts/preboot.asadmin \
 --postbootcommandfile /opt/payara/scripts/postboot.asadmin \
 --logToFile /opt/payara/logs/payara.log \
 --addlibs /opt/payara/lib \
 --deploy /opt/payara/deployments/my-app.war \
 --sslport 8090 \
 --sslcert le_mydomain \
 --contextroot ROOT
```

There are two issues here:

First, the failed `asadmin` should actual report/log the error returned from the command execution, like we would see running locally.  Currently, it only reports that it failed.

Second, either `add-pkcs8` doesn't exist, or I suspect there is a problem with `--domain_name production`.  When running locally against a FULL server, the command does succeed:

```
$ ./bin/asadmin add-pkcs8 --domain_name production --destalias le_mydomain --priv-key-path /samepath/privkey.pem --cert-chain-path /samepath/fullchain.pem
/payara5-full-path/glassfish/domains/production/config/keystore.jks
Private key with alias [le_mydomain] added to keystore /payara5-full-path/glassfish/domains/production/config/keystore.jks.
Command add-pkcs8 executed successfully.
```

So there isn't anything wrong with the *.pem files.  However, it doesn't look like Micro has a **domains** folder, and when you specify an invalid domain with `--domain_name` on a FULL server, you get it's looks for `domains/DOMAIN_NAME`:

```
./bin/asadmin add-pkcs8 --domain_name server --destalias le_mydomain --priv-key-path /samepath/privkey.pem --cert-chain-path /samepath/fullchain.pem
There is no such domain directory: /payara5-full-path/glassfish/domains/server
Command add-pkcs8 failed.
```

## Expected Outcome

`add-pkcs8`  should execute without problems, importing the cert into Micro's keystore.

## Current Outcome

> [2019-06-04T20:15:36.341+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1559679336341] [levelValue: 900] Boot Command add-pkcs8 failed Exception while executing command. 

## Steps to reproduce (Only for bug reports) 

Generate a new Let's Encrypt certificate and try to import it into Micro.

## Environment ##

- **Payara Version**: 5.192 (Docker image)
- **Edition**: Micro
- **JDK Version**: Oracle
- **Operating System**: Linux

**Comment by smillidge** [comment]
Have you tried postboot?

**Comment by johnmanko** [comment]
> Have you tried postboot?

Failed:

`[2019-06-10T15:47:53.175+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1560181673175] [levelValue: 900] Boot Command add-pkcs8 failed Exception while executing command.`

**Comment by OndroMih** [comment]
There's no domain "production" in Payara Micro. Try removing "--domain_name production" from the script.

**Comment by johnmanko** [comment]
> There's no domain "production" in Payara Micro. Try removing "--domain_name production" from the script.

ok, I removed the domain:
`add-pkcs8 --destalias le_mydomain --priv-key-path /opt/payara/cert/privkey.pem --cert-chain-path /opt/payara/cert/fullchain.pem`

with preboot:

> [2019-06-12T15:30:28.696+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1560353428696] [levelValue: 900] Boot Command add-pkcs8 failed Exception while executing command. 

with postboot:

> [2019-06-12T15:32:07.204+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1560353527204] [levelValue: 900] Boot Command add-pkcs8 failed Exception while executing command. 

Is there any way to log the actual error from the `add-pkcs8` command?  The bootstrap is masking that.

**Comment by johnmanko** [comment]
I can't get `micro` to work with cert registration, so I'm trying `web`, but that also results in an error.  Perhaps it's a problem with the Docker images or keystore?  

**Dockerfile**
```
FROM payara/server-web:5.192

COPY cert/privkey.pem $HOME_DIR
COPY cert/fullchain.pem $HOME_DIR
COPY lib/mssql-jdbc-7.0.0.jre8.jar ${PAYARA_DIR}/glassfish/domains/production/lib
COPY deployments/my-app.war $DEPLOY_DIR
COPY scripts/pre-boot-commands.asadmin $CONFIG_DIR
COPY scripts/post-boot-commands.asadmin $CONFIG_DIR

EXPOSE 8080 8181
```
**pre-boot-commands.asadmin**
```
add-pkcs8 --domain_name production --destalias le_mydomain --priv-key-path /opt/payara/privkey.pem --cert-chain-path /opt/payara/fullchain.pem

set configs.config.server-config.network-config.protocols.protocol.https-listener-2.ssl.cert-nickname=le_mydomain
```
**Result**
> Reading in commandments from /opt/payara/config/pre-boot-commands.asadmin
> **Jun 13, 2019 7:07:48 PM fish.payara.boot.runtime.BootCommand execute
> WARNING: Boot Command add-pkcs8 failed Exception while executing command.**
> 
> **Jun 13, 2019 7:07:49 PM fish.payara.boot.runtime.BootCommand execute
> WARNING: Boot Command set failed PlainTextActionReporterFAILURENo configuration found for configs.config.server-config.network-config.protocols.protocol.https-listener-2.ssl**

**Log (removed post boot logging)**
```
> docker container logs 626e35da2437
[Entrypoint] running /opt/payara/scripts/init_1_generate_deploy_commands.sh
touch: cannot touch '/opt/payara/config/post-boot-commands.asadmin': Permission denied
touch: cannot touch '/opt/payara/config/pre-boot-commands.asadmin': Permission denied
Adding deployment target /opt/payara/deployments/my-app.war to post boot commands

/opt/payara/scripts/init_1_generate_deploy_commands.sh: line 48: /opt/payara/config/post-boot-commands.asadmin: Permission denied
[Entrypoint] ignoring /opt/payara/scripts/init.d/*

touch: cannot touch '/opt/payara/config/post-boot-commands.asadmin': Permission denied
touch: cannot touch '/opt/payara/config/pre-boot-commands.asadmin': Permission denied
Executing Payara Server with the following command line:
/docker-java-home/bin/java
-cp
/opt/payara/appserver/glassfish/modules/glassfish.jar
-XX:+UnlockExperimentalVMOptions
-XX:+UnlockDiagnosticVMOptions
-XX:MetaspaceSize=256m
-XX:+UseStringDeduplication
-XX:MaxMetaspaceSize=2g
-XX:+UseCGroupMemoryLimitForHeap
-XX:MaxRAMFraction=1
-XX:+UseG1GC
-XX:MaxGCPauseMillis=500
-Xbootclasspath/p:/opt/payara/appserver/glassfish/lib/grizzly-npn-bootstrap-1.8.jar
-javaagent:/opt/payara/appserver/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djava.security.auth.login.config=/opt/payara/appserver/glassfish/domains/production/config/login.conf
-Djavax.net.ssl.trustStore=/opt/payara/appserver/glassfish/domains/production/config/cacerts.jks
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dcom.sun.aas.instanceRoot=/opt/payara/appserver/glassfish/domains/production
-Dcom.sun.aas.installRoot=/opt/payara/appserver/glassfish
-Djava.security.policy=/opt/payara/appserver/glassfish/domains/production/config/server.policy
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true
-Djavax.net.ssl.keyStore=/opt/payara/appserver/glassfish/domains/production/config/keystore.jks
-Djava.library.path=/opt/payara/appserver/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-prebootcommandfile
/opt/payara/config/pre-boot-commands.asadmin
-upgrade
false
-read-stdin
true
-postbootcommandfile
/opt/payara/config/post-boot-commands.asadmin
-domainname
production
-domaindir
/opt/payara/appserver/glassfish/domains/production
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--user,,,admin,,,--passwordfile,,,/opt/payara/passwordFile,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara/appserver/glassfish/domains,,,production
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/opt/payara/appserver/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false

Launching Payara Server on Felix platform
Jun 13, 2019 7:07:42 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@1408e750 in service registry.
Reading in commandments from /opt/payara/config/pre-boot-commands.asadmin
Jun 13, 2019 7:07:48 PM fish.payara.boot.runtime.BootCommand execute
WARNING: Boot Command add-pkcs8 failed Exception while executing command.
Jun 13, 2019 7:07:48 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.0.16.Final
Jun 13, 2019 7:07:49 PM fish.payara.boot.runtime.BootCommand execute
WARNING: Boot Command set failed PlainTextActionReporterFAILURENo configuration found for configs.config.server-config.network-config.protocols.protocol.https-listener-2.ssl

```

Attempting `add-pkcs8` on a clean machine with new JVM (Oracle 1.8.0_212) and Payara (5.192) installations (server is not running):
```
PS C:\payara\payara-5.192\payara5> .\bin\asadmin add-pkcs8 --domain_name production --destalias le_mydomain --priv-key-path C:\mydomain\cert\privkey.pem --cert-chain-path C:\mydomain\cert\fullchain.pem
C:\payara\payara-5.192\payara5\glassfish\domains\production\config\keystore.jks
Private key with alias [le_mydomain] added to keystore C:\payara\payara-5.192\payara5\glassfish\domains\production\config\keystore.jks.
Command add-pkcs8 executed successfully.
PS C:\payara\payara-5.192\payara5>
```

**Comment by johnmanko** [comment]
@smillidge @OndroMih Were either of you able to confirm this is an issue?  For me, it's still outstanding and I'm unable to use the docker image and this utility command.

**Comment by smillidge** [comment]
Have you thought about just importing the certificate directly into the keystore using keytool when building your docker image?

**Comment by johnmanko** [comment]
> Have you thought about just importing the certificate directly into the keystore using keytool when building your docker image?

I'm not building a docker image.  Also, that would still leaves this as an open issue.

**Comment by OndroMih** [comment]
This is the same issue as https://github.com/payara/docker-payaraserver-full/issues/93. The exception is the same as reported there:

```
org.glassfish.api.admin.CommandException: Command lookup failed for command add-pkcs8
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:106)
```

It's very easy to reproduce, just by creating a postbootcommandfile with a single line that contains "add-pkcs8" and running a plain Payara Micro with it:

```
java -jar payara-micro.jar --postbootcommandfile postboot.asadmin
```
When started in debug mode with suspend=y and a breakpoint before the warning message is logged from BootCommand.java, I could see the exception details. A very recent commit in Payara adds logging of the exception (not yet in a released version): https://github.com/payara/Payara/commit/89be95a8601dfe02c5bf3a5dbdf16c239d084aad#diff-1a1b999aea180bc7d39143f1ec7ae4fb

**Comment by smillidge** [comment]
@OndroMih  is there a JIRA number?

**Comment by rdebusscher** [comment]
I have created `CUSTCOM-120`

**Comment by AlanRoth** [comment]
Hi, this command has now been deprecated. Adding certfificates with post boot commands is not supported, and asadmin commands are not avaliable in pre-boot. The preffered method is to use system properties to add custom certificates to the Micro keystore. I will close this issue now. Thank you.

**Comment by johnmanko** [comment]
> Hi, this command has now been deprecated. Adding certfificates with post boot commands is not supported, and asadmin commands are not avaliable in pre-boot. The preffered method is to use system properties to add custom certificates to the Micro keystore. I will close this issue now. Thank you.

Can you reference/link documentation to support those claims?  Thanks.

**Comment by rdebusscher** [comment]
Hi John,

I have update the documentation to make it more explicitly, see https://github.com/payara/Payara-Community-Documentation/pull/105.

The Java SSL System Properties are described on this page https://docs.payara.fish/community/docs/5.2020.5/documentation/payara-micro/configuring/config-keystores.html.

Regards
Rudy
