### ISSUE TITLE
admin console blank 

### ISSUE THREAD

**Issue by wayne-zhang** [payara/Payara#4019]
When I installed Paray 5 and start the domain, then I try to logon the admin console (http://localhost:4848) but it never redirect to the login page. A spinner is turning forever; When I refresh the page, it turns to blank.

I have tried server version of Parya4 actually, including the latest 5.192. My server/PC is Windows 10, Java 8 64 bit (see server log).

It similar to issue https://github.com/payara/Payara/issues/2654

**Comment by wayne-zhang** [comment]
[server.log](https://github.com/payara/Payara/files/3264775/server.log)

**Comment by wayne-zhang** [comment]
OK, I found the problem. I may be caused by Windows directory links. I create a link c:\apps that links to e:\apps and I install Payara5 in to c:\apps\payara5. It fails when it was run from c:\apps\payara5 but it works when it starts in e:\apps\payara5.

I have installed Glassfish (5 & 5.1) too in the same folder but Glassfish works. Not sure why Payara fails due to directory links.

**Comment by smillidge** [comment]
Thanks for the info. I will close this.
