### ISSUE TITLE
The domain.xml java-home is not honored in version-specific jvm-options PAYARA-3911

### ISSUE THREAD

**Issue by vlumi** [payara/Payara#4025]
# Description #
----------

On domain.xml, all the jvm-options are filtered according to the JDK used to run asadmin -- not the one configured to be used with the domain. This will result in errors if the arguments are not valid for the JDK set for the domain, especially using JDK before and after 9.

## Expected Outcome

Using JDK 1.8 to run asadmin, and JDK 11 configured in domains.xml, the domain should start normally, running on JDK 11.

## Current Outcome

The execution will fail with the following output:

    Waiting for domain1 to start .Error starting domain domain1.
    The server exited prematurely with exit code 1.
    Before it died, it produced the following output:
    
    -Xbootclasspath/p is no longer a supported option.
    Error: Could not create the Java Virtual Machine.
    Error: A fatal exception has occurred. Program will exit.
    
    Command start-domain failed.

## Steps to reproduce (Only for bug reports) 

1. Update the domain.xml, pointing the java-home to a JDK 11 installation, e.g.

    <java-config classpath-suffix=""
        debug-options="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009"
        java-home="/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home"
        system-classpath="">

2. Make sure to use JDK 1.8 for asadmin

    $ java -version
    java version "1.8.0_211"
    Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

3. Leave the AS_JAVA unset (default value on glassfish/config/asenv.conf)

4. Use JDK 1.8 to start the domain

    ./asadmin start-domain domain1

## Context (Optional)

This issue came up when trying to start Payara 5.192 with JDK 11 from IntelliJ IDEA, with the system default JDK still being 1.8 (set on .bash_properties).

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: 1.8.0_211 and 11.0.1
- **Operating System**: Mac

**Comment by OndroMih** [comment]
I confirm the behavior with a fresh domain1 domain on v5.192:

1. install both JDK 8 and 11, JDK 8 is the default system Java version
2. start domain
3. run the following to set path to JDK 11:
```
asadmin set configs.config.server-config.java-config.java-home=/path/to/jdk11
```
4. stop domain
5. starting domain results in an error as described

**Comment by OndroMih** [comment]
@vlumi, can you create a pull request with your changes in https://github.com/vlumi/Payara/commit/b1b21c5316571a63d136ad38cf0dd02111f0778b?

**Comment by smillidge** [comment]
#4034 is the PR?

**Comment by vlumi** [comment]
Yes, I created the pull request #4034 is for this already.
