### ISSUE TITLE
JAXB does not generate correct JSON output

### ISSUE THREAD

**Issue by tfeilhauer** [payara/Payara#4059]
# Description #
I found some issues on the latest Payara Server 5.192 #badassfish (build 115)regarding JAXB.
The following JaxrsClient class addresses a RESTful Web service:

```
package jaxrs;

import javax.ws.rs.client.*;
import javax.ws.rs.core.*;
//import java.time.LocalDate;
import javax.xml.bind.JAXB;
import javax.xml.datatype.*;
import java.util.GregorianCalendar;
import generated.*;

public class JaxrsClient {
  private static final String BASE_URI = "http://localhost:8081/jaxrs4/ageSvc/xmlpost";

  public static void main(String[] args) {
    Client client = ClientBuilder.newClient();
    WebTarget webTarget = client.target(BASE_URI);

    JaxbInBean inBean = new JaxbInBean();
    inBean.setLastname("Bond");
    GregorianCalendar born = new GregorianCalendar(1977,7,7);
    try {
      XMLGregorianCalendar bornXml = DatatypeFactory.newInstance().newXMLGregorianCalendar(born);
      inBean.setBirthday(bornXml);
    }
    catch (DatatypeConfigurationException e) {
      throw new RuntimeException(e);
    }
    JAXB.marshal(inBean, System.out);

    JaxbOutBean result = (JaxbOutBean) webTarget
// both .request work!!!
//             .request()
             .request(MediaType.APPLICATION_JSON)
//             .request(MediaType.APPLICATION_XML)
             .accept("application/xml")
// both .post work!!!
             .post(Entity.json(inBean), JaxbOutBean.class);
//             .post(Entity.entity(inBean, MediaType.APPLICATION_JSON), JaxbOutBean.class);
//             .post(Entity.entity(inBean, MediaType.APPLICATION_XML), JaxbOutBean.class);
    System.out.println(result.getSurname() + " is " + result.getAge() + " years old");
  }
}
```

This JaxRS client produces a request with JSON input based on a Java class JaxbInBean.java generated by xjc on the following JaxbInBean.xsd:

> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
> 
>   <xs:complexType name="jaxbInBean">
>     <xs:sequence>
>       <xs:element name="lastname" type="xs:string" minOccurs="0"/>
>       <xs:element name="birthday" type="xs:dateTime" minOccurs="0"/>
>     </xs:sequence>
>   </xs:complexType>
> </xs:schema>
> 

And the JaxRS client expects a response with XML payload based on a Java class JaxbOutBean.java generated by xjc on the following JaxbOutBean.xsd:

> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
> 
>   <xs:element name="jaxbOutBean" type="jaxbOutBean"/>
> 
>   <xs:complexType name="jaxbOutBean">
>     <xs:sequence>
>       <xs:element name="surname" type="xs:string" minOccurs="0"/>
>       <xs:element name="age" type="xs:long"/>
>     </xs:sequence>
>   </xs:complexType>
> </xs:schema>

The JAX-RS client (JaxrsClient.java) sends out the following request:

> POST /jaxrs4/rest/ageSvc/xmlpost HTTP/1.1
> Accept: application/json,application/xml
> Content-Type: application/json
> User-Agent: Jersey/2.29.payara-p2 (HttpUrlConnection 1.8.0_151)
> Host: 127.0.0.1:8081
> Connection: keep-alive
> Content-Length: 69
> 
> {"birthday":"1977-08-07T00:00:00+01:00[GMT+01:00]","lastname":"Bond"}

And receives the following response:

> HTTP/1.1 200 OK
> Server: Payara Server  5.192 #badassfish
> X-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.192 #badassfish Java/Oracle Corporation/1.8)
> Content-Type: application/xml
> Content-Length: 95
> X-Frame-Options: SAMEORIGIN
> 
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>    <jaxbOutBean>
>       <age>41</age>
>    </jaxbOutBean>

as you can see also from tcpmon-new.png.

The output from marshalling the inbean to XML [JAXB.marshal(inBean, System.out);] is

> <jaxbInBean>
>     <lastname>Bond</lastname>
>     <birthday>1977-08-07T00:00:00.000+01:00</birthday>
> </jaxbInBean>

This is correct so far, but there seems to be a problem with converting it to JSON: The order of the fields in wrong (first birthday then lastname) as you can see in the request above. This seems to cause the JaxRS server to be unable to unmarshal the JSON correctly into a JaxbInBean class at the server side:

```
package org.my;

import javax.xml.bind.annotation.*;
import java.time.LocalDate;
import java.util.*;

//@XmlRootElement
public class JaxbInBean {
  @XmlElement(name = "lastname")
  public String famName;
  public Date birthday;
// Currently JAXB can't correctly marshal LocalDate (Date works)
//  public LocalDate birthday;
  public JaxbInBean() {} // JAXB needs default constructor
//  public JaxbInBean(String name, LocalDate born) {
  public JaxbInBean(String name, Date born) {
    this.famName = name;
    this.birthday = born;
  }
}
```

And here is the corresponding JaxRS server class:

```
package org.my;

import javax.ws.rs.*;
import javax.ws.rs.core.MultivaluedMap;
import java.time.temporal.ChronoUnit;
import java.time.*;

@Path("/ageSvc")
public class JaxRsPostService {
  /** Constructor */
  public JaxRsPostService() {
  }

  @POST
  @Path("/xmlpost")
  @Produces("application/xml")
//  @Consumes("application/xml")
  @Consumes("application/json")
  public JaxbOutBean ageCalc(JaxbInBean inBean) {
  
//  long age = inBean.birthday.until(LocalDate.now(), ChronoUnit.YEARS);
// Currently JAXB can't correctly marshal LocalDate (Date works)
    LocalDate dayOfBirth = LocalDateTime.ofInstant(Instant.ofEpochMilli(inBean.birthday.getTime()), ZoneId.systemDefault()).toLocalDate();
    long age = dayOfBirth.until(LocalDate.now(), ChronoUnit.YEARS);

System.out.println("FamName: " + inBean.famName);

    return new JaxbOutBean(inBean.famName, age);
  }
}
```

inBean.famName is null and this is why the returned XML only contains the age, but not the surname.

The same code worked with Glassfish 4.1, but does not work with Payara Server 5.192 #badassfish (build 115).

You can find the complete projects in the attachments.

It also seems that the transformation from a Java Date to XML or JSON does not work correctly. The Java date that I created was 1977-07-07, but the resulting XML (& JSON) date was 1977-08-07. This didn’t work in Glassfish 4.1 either.

I also couldn’t use the schemagen of Payara Server 5.192 #badassfish (build 115) to generate the xsd from JaxbInBean.java, which exits with an exception:

> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at com.sun.tools.jxc.SchemaGenerator.run(SchemaGenerator.java:166)
>         at com.sun.tools.jxc.SchemaGenerator.run(SchemaGenerator.java:91)
>         at com.sun.tools.jxc.SchemaGenerator.main(SchemaGenerator.java:82)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at com.sun.tools.jxc.SchemaGeneratorFacade.main(SchemaGeneratorFacade.java:60)
> Caused by: java.lang.NullPointerException
>         at com.sun.tools.jxc.SchemaGenerator$Runner.compile(SchemaGenerator.java:248)
>         ... 12 more

For my project I was using the schemagen of the current Java JDK 8 which worked well so far.

Finally it would be good if JaxB could marshal Java’s LocalDate; but this is of course not an issue.

## Expected Outcome

An expected outcome would be something like

> HTTP/1.1 200 OK
> Server: Payara Server  5.192 #badassfish
> X-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.192 #badassfish Java/Oracle Corporation/1.8)
> Content-Type: application/xml
> Content-Length: 95
> X-Frame-Options: SAMEORIGIN
> 
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>    <jaxbOutBean>
>       <surname>41</surname>
>       <age>41</age>
>    </jaxbOutBean>

## Current Outcome

TCPMON actually shows the following outcome:

> HTTP/1.1 200 OK
> Server: Payara Server  5.192 #badassfish
> X-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.192 #badassfish Java/Oracle Corporation/1.8)
> Content-Type: application/xml
> Content-Length: 95
> X-Frame-Options: SAMEORIGIN
> 
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>    <jaxbOutBean>
>       <age>41</age>
>    </jaxbOutBean>

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

   asadmin start-domain domain1

2 -**  Compile server class

3 -**  Package:
jar cvf ..\archive\jaxrs4.war .\

4 -** Deploy:
asadmin deploy archive\jaxrs4.war

5 -** Generate Schema:
schemagen JaxbInBean.java
schemagen JaxbOutBean.java

6 -** generate Java-Beans from XML-Schema:
xjc *.xsd

7 -** Compile client

8 -** Run client

### Samples
![tcpmon-new](https://user-images.githubusercontent.com/6097609/59919717-7be94a80-9428-11e9-92d3-e2a20fbe37ff.png)
![tcpmon-old](https://user-images.githubusercontent.com/6097609/59919778-a935f880-9428-11e9-9a78-24c28768eaeb.png)
[jaxrs4_c.zip](https://github.com/payara/Payara/files/3314239/jaxrs4_c.zip)
[jaxrs4.zip](https://github.com/payara/Payara/files/3314240/jaxrs4.zip)

## Environment ##

- **Payara Version**: 5.192 #badassfish (build 115)
- **Edition**:  Full 
- **JDK Version**:  1.8.0_151 - Oracle 
- **Operating System**: Windows 
- **Database**:  n.a.

**Comment by OndroMih** [comment]
As you're migrating from GlassFish 4, which is similar to Payara Server 4, I suspect you're seeing issues because of changes in Payara Server 5, specifically because of adopting Java EE 8, which brings a standard way of mapping between Java objects and JSON called JSON-B (JSON Binding).

Mapping Java objects to JSON using JAX-B is not standardized, and as such is prone to future changes. That exactly happened in Payara Server 5. By default, it no longer respects JAXB mappings and uses JSON-B mechanism and annotations. If your client uses a JAXB mapper (e.g. Moxy or Jackson), then the generated JSON is incompatible with what Payara Server 5 expects by default.

You should either:

* change you client code to use JSON-B mapper, e.g. [Yasson](https://github.com/eclipse-ee4j/yasson), which is also used internally by Payara Server
* or configure Payara Server 5 to use the JAX-B mapping, which was used by default in Payara Server 4 and GlassFish 4

You can find out more about migration from GlassFish 4 or Payara Server 4 to Payara Server 5 in this guide: https://info.payara.fish/payara-server-4-to-payara-server-5-migration

**Comment by tfeilhauer** [comment]
Hi Ondro,

thank you very much for your quick response! That should help.

I’m just wondering why Payara 5 is still including all the JAX-B stuff like schemagen & xjc and generates output that can be compiled but unfortunately doesn’t work correctly at runtime. Is it that Payara5’s JAX-B no longer supports JSON correctly? So the problem is just the JAX-B transformation to JSON and if I would use XML for the request format, the scenario should work, even with Payara 5? And if I want to use JSON for exchange format I need to use JSON-B. The nice thing with the old JAXB-mapping in Payara 4 was that I could easily change the exchange format from XML to JSON. This doesn’t seem to be supported anymore.

Best regards

- Thomas

 

 

Von: Ondro Mihályi [mailto:notifications@github.com] 
Gesendet: Freitag, 21. Juni 2019 17:02
An: payara/Payara
Cc: FEILHAUER Thomas; Author
Betreff: Re: [payara/Payara] JAXB does not generate correct JSON output (#4059)

 

As you're migrating from GlassFish 4, which is similar to Payara Server 4, I suspect you're seeing issues because of changes in Payara Server 5, specifically because of adopting Java EE 8, which brings a standard way of mapping between Java objects and JSON called JSON-B (JSON Binding).

Mapping Java objects to JSON using JAX-B is not standardized, and as such is prone to future changes. That exactly happened in Payara Server 5. By default, it no longer respects JAXB mappings and uses JSON-B mechanism and annotations. If your client uses a JAXB mapper (e.g. Moxy or Jackson), then the generated JSON is incompatible with what Payara Server 5 expects by default.

You should either:

*	change you client code to use JSON-B mapper, e.g. Yasson <https://github.com/eclipse-ee4j/yasson> , which is also used internally by Payara Server
*	or configure Payara Server 5 to use the JAX-B mapping, which was used by default in Payara Server 4 and GlassFish 4

You can find out more about migration from GlassFish 4 or Payara Server 4 to Payara Server 5 in this guide: https://info.payara.fish/payara-server-4-to-payara-server-5-migration
