### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by Luwin95** [payara/Payara#4063]
# Description #
----------

Hi everyone ! We are still experiencing ssl certificate error while deploying payara server v5.192. This time there are three certificates expired at the end of June 2019. The three aliases of the obsolete cert are utndatacorpsgcca, secomvalicertclass1ca, valicertclass2ca. We have applied the procedure described in this issue https://github.com/payara/Payara/issues/3038#issuecomment-413439878 to remove those obsolete certificates. By doing that we have also seen that a lot more of certificate will expire by the beginning of July (around July the 7th, 8th and 10th).
The workaround we used is not valid for a prod environment though and we would really appreciate if those certificates were removed in the next minor release.

## Expected Outcome

No severe log for The SSL certificate has expired

## Current Outcome

While deploying : The SSL certificate has expired (multiple times)

## Steps to reproduce 

1 -**  Start the domain

    ./asadmin start-domain payaradomain or start payara server on eclipse with payara tools

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: 1.8
- **Operating System**: Windows 10
- **Database**:

**Comment by peterpz1** [comment]
Common problem, all certs will some time expire. On our env we don't need any global CA, just our company ones, so I myself remove cacerts.jks file restore it with only s1as and glassfish-instance certs (needed for payara to work by itself) and I never have problem with expired certs. Also notice that expired certs do nothing wrong for the server, just a couple of warnings during the start.

**Comment by Luwin95** [comment]
Hi first of all thank you for your answer.
I agree with you that this problem does not provoke any dysfunction with the server. I have however two problems with this :
- For dev env : Using payara tools on eclipse, the error of cert make the logs malfunctioning (the console doesn't display any logs in eclipse after the certs error). I know the logs can be access from another location but debugging in eclipse is very hard without this feature.
- For prod env : The logs are polluted with one or many Severe errors at startup. Updating CA manually is not a possibility meaning at each update of payara i'll have to repeat the process of updating cacert.jks which is not applicable with our process of delivery.
