### ISSUE TITLE
unwanted automatic redirection to https (port 8181)

### ISSUE THREAD

**Issue by satinder-2000** [payara/Payara#4081]
I am developing a JEE project and trying to deploy in Payara 5.191 and 5.192. On both the servers, an http:// (port 8080) call on the browser get automatically redirected to secure https:// (port 8181). This gives a 'Privacy error' -Your connection is not private and NET::ERR_CERT_AUTHORITY_INVALID
Environment

- Payara Version: 5*
-Edition:Full
-JDK Version: 8 u201 - Oracle
-Operating System:Mac 10.13.6
- Database: MySQL8

**Comment by MeroRai** [comment]
Hi, @satinder-2000 could you check your project to see if it has been configured to redirect `http` to `https`. If it is a web application you will find something similar as following in your `web.xml` file:

```
  <security-constraint>
      <web-resource-collection>
        <web-resource-name>Viewpoint Secure URLs</web-resource-name>
        <url-pattern>/*</url-pattern>
      </web-resource-collection>
      <user-data-constraint>
        <transport-guarantee>CONFIDENTIAL</transport-guarantee>
      </user-data-constraint>
   </security-constraint>
```

Regards,
Mero Rai

**Comment by satinder-2000** [comment]
@MeroRai 
Indeed that was the case. All OK now.
Many Thanks.

**Comment by svendiedrichsen** [comment]
@satinder-2000 Can this be closed then?
