### ISSUE TITLE
Correct usage of WebappClassLoader.jarFilesLock /CUSTCOM-76

### ISSUE THREAD

**Issue by supersven** [payara/Payara#4099]
# Description #
----------

`WebappClassLoader` is not thread-safe regarding the `jarFiles` field.

I started my investigation because we have some (really few) Exceptions like this in our production environment (latest Payara 4):

```
 	java.lang.NullPointerException
	at org.glassfish.web.loader.WebappClassLoader.findResourceInternalFromJars(WebappClassLoader.java:2904)
	at org.glassfish.web.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2757)
	at org.glassfish.web.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2647)
	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1063)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1620)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.append(ThriftSender.java:49)
	at io.jaegertracing.internal.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:140)
	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:176)
	at java.lang.Thread.run(Thread.java:748)
```

`ThriftSender.append()` doesn't call `WebappClassLoader.loadClass()` directly, but instantiates an object; I think that what's looked for in the `WebappClassLoader`.

```java
  @Override
  public int append(JaegerSpan span) throws SenderException {
    if (process == null) {
      process = new Process(span.getTracer().getServiceName());  //  ThriftSender.java:49, part of the stacktrace above
[...]
```

```java
    private ResourceEntry findResourceInternalFromJars(String name,
                                                       String path) {

        ResourceEntry entry = null;
        JarEntry jarEntry = null;
        int contentLength = -1;
        InputStream binaryStream = null;

        if (!openJARs()){
            return null;
        }

        int jarFilesLength = jarFiles.length;

        for (int i=0; (entry == null) && (i < jarFilesLength); i++) {
            jarEntry = jarFiles[i].getJarEntry(path);

            if (jarEntry != null) {

                entry = new ResourceEntry();
                try {
                    entry.codeBase = getURL(jarRealFiles[i]);
                    String jarFakeUrl = getURI(jarRealFiles[i]).toString();
                    jarFakeUrl = "jar:" + jarFakeUrl + "!/" + path;
                    entry.source = new URL(jarFakeUrl);
                    entry.lastModified = jarRealFiles[i].lastModified();
                } catch (MalformedURLException e) {
                    return null;
                }

                contentLength = (int) jarEntry.getSize();
                try {
                    entry.manifest = jarFiles[i].getManifest();        // Line 2904 - NPE thrown here!
                    binaryStream = jarFiles[i].getInputStream(jarEntry);
                } catch (IOException e) {
                    return null;
                }

                // Extract resources contained in JAR to the workdir
                if (antiJARLocking && !(path.endsWith(".class"))) {
                    File resourceFile = new File
                        (loaderDir, jarEntry.getName());
                    if (!resourceFile.exists()) {
                        extractResources();
                    }
                }
            }
        }
```

Reasoning about how an NPE was possible in the marked line,  I found that the call to `findResourceInternalFromJars()` from `findResourceInternal()` is synchronized with `jarFiles` and not with `jarFilesLock`:

```java
    protected ResourceEntry findResourceInternal(String name, String path) {
[...]
        entry = findResourceInternalFromRepositories(name, path);

        if (entry == null) {
            synchronized (jarFiles) {
                entry = findResourceInternalFromJars(name, path);
            }
        }
[...]
        return entry;
    }
```

As it is the only place with a synchronization with `jarFiles` and `jarFiles` is not `final`, I think it's a bug (IMHO `jarFilesLock` should have been used).

While reproducing this case, I noticed that there are other accesses to `jarFiles` that should be guarded with `jarFilesLock`, too. I fact, I would guard all accesses, that index into this array.

### Reproduction

Please see https://github.com/supersven/reproduce-webclassloader-jarfiles-race

### Fix

Please see https://github.com/supersven/Payara/commit/16b40dddd0e28c4b4dc977370d3afdb2a9167391 as a base for discussion.

## Environment ##

- **Payara Version**: up to current master
- **Edition**: Full
- **JDK Version**: 8 OpenJDK
- **Operating System**: Mac

**Comment by svendiedrichsen** [comment]
@supersven I do also see the usage `jarFilesLock` for locking as the correct one. But I would rather like to see `jarFilesLock` being a `ReadWriteLock` assuming that the `jarFiles` member will only written once and read multiple times. The usage of `synchronized` is causing alot more contention than nessessary.

**Comment by svendiedrichsen** [comment]
@supersven I have created a fix using a ReentrantReadWriteLock to cover jarFiles access. Please take a look: https://github.com/svendiedrichsen/Payara/tree/rwlock-webappclassloader

**Comment by supersven** [comment]
Hey @svendiedrichsen ,

Thanks for taking a look and proposing an improvement! The idea with the `ReadWriteLock` sounds promising.

However, I'm not sure, if we don't miss `synchronized` cases, that don't belong to the `jarFilesLock` problem when we remove `synchronized` from public methods. So, I can't say for sure, if we don't break something else when we exchange them with the new `ReadWriteLock`.

Have you tried https://github.com/supersven/reproduce-webclassloader-jarfiles-race ?

**Comment by svendiedrichsen** [comment]
@supersven I have run your test successfully after making some adjustments to the locking. As far as your test goes I'm quite confident to say it is thread-safe. But I have to admit that for other cases there may be a chance of missing some cases.

**Comment by supersven** [comment]
Hey @svendiedrichsen ,

I'm a bit unsure how we should go on. Maybe you can create a pull request, so that me (and hopefully others) can take a close, dedicated look?

I would propose to separate the synchronization related changes from the refactorings (another PR?), because this issue is hard enough to understand ... :)

(BTW I don't have any access rights to the main repository, thus, at least one other developer has to take a look ... ;) )

**Comment by rdebusscher** [comment]
Fix currently under test. Internal issue is `CUSTCOM-76`

**Comment by rdebusscher** [comment]
There are several updates done on the Thread Synchronisation of WebappClassLoader. Please let me know if problem is still in the latest version.
Closing it for the moment.

Regards
Rudy
