### ISSUE TITLE
DAS can not communicate with instance because of SSLHandshakeException

### ISSUE THREAD

**Issue by RedeemerSK** [payara/Payara#4111]
# Description #

For newly created domains (other than pre-existing "domain1" and "production"), DAS can start but then can not communicate with created instances.

I've checked with instances created on both local CONFIG node (checked on Windows 10) and remote SSH nodes (CentOS).

I was debugging the issue and found that DAS is failing to communicate with instance because of "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target".

After debugging some more it turned out the problem is that DAS has in it's truststore (I assume it's filled only with certs from cacerts.jks) certificates (aliases s1as and glassfish-instance) that do not match those generated during new domain creation and used by instances for their admin ports, but default ones (same as in domain1). Therefore DAS does not trust instance's admin port SSL certificate.

----------

## Expected Outcome

After starting the instance, DAS can properly see instance is running and is able to manage it.

## Current Outcome

DAS sees instances as not running.

## Steps to reproduce (Only for bug reports) 

1 -**  Create new domain
2 -**  Start DAS of new domain
3 -**  Create new node (eg. local CONFIG node)
4 -**  Create new instance on the created node
5 -**  Start new instance
6 -**  Check status of the instance / try to eg. generate JVM report

### Samples

N/A

## Context (Optional)

I was evaluating payara 5.192 as a potential runtime for new modules.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: 8 u212 - Oracle
- **Operating System**: Windows / Linux
- **Database**: N/A

**Comment by RedeemerSK** [comment]
Proof of certs mismatch and comparison with how it looks in working payara 4.1

Payara 5 (not working):
```
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/domains/test_domain/config/keystore.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: bfdcafe
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/domains/test_domain/config/cacerts.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=localhost, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 51f9a700
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/domains/test_domain/config/keystore.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 3c11eb2a
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/domains/test_domain/config/cacerts.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=localhost-instance, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 14f2be02

[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/nodes/test_node/test_instance/config/keystore.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: bfdcafe
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/nodes/test_node/test_instance/config/cacerts.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=localhost, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 51f9a700
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/nodes/test_node/test_instance/config/keystore.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 3c11eb2a
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara5/glassfish/nodes/test_node/test_instance/config/cacerts.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=localhost-instance, OU=Payara, O=Payara Foundation, L=Great Malvern, ST=Worcestershire, C=UK
Serial number: 14f2be02
```

Payara 4.1 (working):
```
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/domains/test_domain/config/keystore.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 55385aeb
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/domains/test_domain/config/cacerts.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 55385aeb
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/domains/test_domain/config/keystore.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 1860506
[das_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/domains/test_domain/config/cacerts.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 1860506

[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/nodes/test_node/test_instance/config/keystore.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 55385aeb
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/nodes/test_node/test_instance/config/cacerts.jks -alias s1as | grep 'Serial\|Owner'
Owner: CN=das_hostname, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 55385aeb
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/nodes/test_node/test_instance/config/keystore.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 1860506
[instance_host]$ keytool -list -v -keystore #INSTALL_PATH#/payara41/glassfish/nodes/test_node/test_instance/config/cacerts.jks -alias glassfish-instance | grep 'Serial\|Owner'
Owner: CN=das_hostname-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
Serial number: 1860506
```

**Comment by rdebusscher** [comment]
Hi @RedeemerSK 

I think you did not specify the **nodehost** parameter when creating the node. The following commands will successful create and start an instance.

> create-domain test-domain
> start-domain test-domain
> create-node-config --nodehost=localhost test-node
> create-instance --node=test-node test-instance
> start-instance test-instance

I have noticed that the WebConsole (but also the asadmin command create-node-config) does not give an error in the case you forget the nodehost parameter value.

I have create the internal ticket PAYARA-4072 to solve this.

Regards
Rudy

**Comment by RedeemerSK** [comment]
Confirmed on Windows & CONFIG node on localhost.
Will confirm on CentoOS with remote SSH node during week.

**Comment by RedeemerSK** [comment]
Sorry for long delay.
Confirmed with remote SSH node too.

(Actually my DAS still can't see instance running, but debuging showed that's likely becasue of old JDK 8 version - NoSuchMethodError for some crypto stuff. I've confirmed that DAS and instance have established TCP connection and certificates in stores are correct.)

**Comment by rdebusscher** [comment]
Thx for confirmation
