### ISSUE TITLE
192 Micro : Context Root as part of filename not working

### ISSUE THREAD

**Issue by carlbradwell17** [payara/Payara#4144]
# Description #
----------

Part of the documentation describes how a context root can now (since 191) be set on the command line when starting Payara Micro:
`java -jar payara-micro.jar --deploy /home/user/example.war:hello-world`

In version 192. this never works, I've tried it with different war files, on Ubuntu and Windows, etc. 

Using the context root option works:
`java -jar payara-micro.jar --deploy /home/user/example.war --contextroot hello-world`

I have tried this in version 191 and it works as expected, so this issue is confined to 192.

## Expected Outcome

I should be able to deploy multiple applications and set the context root for each (hence why I want to do it was part of the deploy command and not set a single contextroot):
`java -jar payara-micro.jar --deploy /home/user/app1.war:one --deploy /home/user/app2.war:two`

## Current Outcome

Using the example listed in the documentation, the context root is always "/example", i.e. the filename.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: OpenJDK 8
- **Operating System**: Ubuntu 16.0.4

**Comment by khasunuma** [comment]
I reproduced it and reported as internal issue PAYARA-4070.

**Comment by smillidge** [comment]
Fixed by #4200
