### ISSUE TITLE
RolesAllowedRequestFilter throws NotAuthorizedException with invalid WWW-Authenticate

### ISSUE THREAD

**Issue by lunicon** [payara/Payara#4147]
Good day, I found some error in class fish.payara.microprofile.jwtauth.jaxrs.RolesAllowedRequestFilter
in module microprofile-jwt-auth.jar

```
  public void filter(ContainerRequestContext requestContext) throws IOException {
    if (this.rolesAllowed.length > 0 && !isAuthenticated()) {
      
      AuthenticationStatus status = this.securityContext.authenticate(this.request, this.response, AuthenticationParameters.withParams());
      
      if (status == AuthenticationStatus.NOT_DONE || status == AuthenticationStatus.SEND_FAILURE) {
        throw new NotAuthorizedException("Authentication resulted in " + status, new Object[0]);
      }
      
      if (status == AuthenticationStatus.SUCCESS && !isAuthenticated()) {
        throw new NotAuthorizedException("Authentication not done (i.e. no JWT credential found)", new Object[0]);
```

This exceptions create invalid response message        
Status Code: 401 Unauthorized        
WWW-Authenticate: Authentication not done (i.e. no JWT credential found)

Payara 5.192

**Comment by svendiedrichsen** [comment]
This the spec about the WWW-Authenticate header field: https://tools.ietf.org/html/rfc7235#section-4.1

**Comment by lunicon** [comment]
WWW-Authenticate have to be something like BASIC etc.. Which your app support. I think neet to use other constructor for error message instead header
