### ISSUE TITLE
JAX-RS applications without an Application subclass may return HTTP 404 when the web.xml has no jersey.config.server.provider.packages init-param

### ISSUE THREAD

**Issue by vargusz** [payara/Payara#4149]
# Description #
----------
On Payara Server 192 Full, JAX-RS applications without an `Application` subclass may return HTTP 404 when the `web.xml` has no `jersey.config.server.provider.packages` `init-param`.

The issue is probably related to the deployment process: if it works or fails initially, it will always behave the same way on subsequent requests until the application is redeployed or the server is restarted.

## Expected Outcome

According to [example 4.18](https://jersey.github.io/documentation/latest/deployment.html#deployment.servlet.3.pluggability.noapp) of the Jersey documentation, one can set up a JAX-RS application without an `Application` subclass. All you need to do is provide `javax.ws.rs.core.Application` as the `servlet-name` in the `web.xml` descriptor, and configure a `servlet-mapping`.

The expected outcome is that any `@Path` resources defined in the code will be autodiscovered, and the JAX-RS endpoints will be accessible.

## Current Outcome

This setup used to work on GlassFish 4, but sometimes fails on Payara 5.

The WAR is deployed successfully, but the JAX-RS endpoints may return HTTP 404. Other servlets present in the WAR continue to work as expected. No errors are printed to the `server.log`.

The issue seems to be nondeterministic, and the behavior is very similar to #3077: the exact same WAR sometimes works correctly, but may return 404 after being redeployed. However, there is no JAX-B involved here.

## Steps to reproduce

1. Create a skeleton Jersey project using the following Maven archetype:
```
mvn archetype:generate \
  -DarchetypeGroupId=org.glassfish.jersey.archetypes \
  -DarchetypeArtifactId=jersey-quickstart-webapp \
  -DarchetypeVersion=2.29
```
2. Remove the `jersey.config.server.provider.packages` `init-param` from the generated `web.xml`, as it's not mandatory.
3. Change the `url-pattern` of the `servlet-mapping` to `/*`. Please note that the Java code contains a JAX-RS resource as `@Path("myresource")`.
4. Build the Maven project using `mvn clean package`.
5. Deploy the resulting WAR on Payara 5 with `/` as the context root.
6. Try to access http://localhost:8080/myresource
7. If the resource returns HTTP 200 OK with _Got it!_ as the response body, undeploy the application and repeat from step 5.
8. Otherwise the resource returned HTTP 404 Not Found, and the issue has been successfully reproduced.

## Workaround

The workaround is to add the `jersey.config.server.provider.packages` `init-param` with the correct package name.

## Environment ##

- **Payara version**: 5.192 (but reproducible on earlier Payara 5 releases too)
- **Edition**: Full
- **JDK Version**: tested on OpenJDK 1.8.0_222 and Oracle JDK 1.8.0_201
- **Operating System**: Linux

**Comment by rdebusscher** [comment]
Hi,

When you do not want to use the `init-param` value in web.xml,  you need to use the Servlet 3 web.xml namespace. (the reproducer is using version 2.5)

I followed the following steps and have no issue on Payara 5.194.

1. Create skeleton with maven archetype
2. Define the 2 Jersey dependencies as provided since they are included in Payara.
3. Use the following web.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.1" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
    <servlet>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <url-pattern>/webapi/*</url-pattern>
    </servlet-mapping>
</web-app>

```

Regards
Rudy
