### ISSUE TITLE
Development request (node uptime) /CUSTCOM-187

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4169]
# Description #
----------

In node uptime the time is displayed in milliseconds, which is meaning nothing to nobody. It would be great to format node uptime to some human readably time.

![obraz](https://user-images.githubusercontent.com/41665450/63502887-bb86ee00-c4ce-11e9-8978-6beafe13acb7.png)

**Comment by smillidge** [comment]
Should be a quick change.

**Comment by smillidge** [comment]
Should be a quick change.

**Comment by peterpz1** [comment]
I would even try doing some pull request myself but one time I tried to understand how GUI is build and for now it is too much for me.

**Comment by fturizo** [comment]
Understood, @peterpz1. We have raised the internal issue `CUSTCOM-187` to implement this small enhancement. Keep in mind that there's no guarantee of a quick resolution due to the low priority of this issue.

**Comment by bbulk** [comment]
Hi @fturizo,
I already implemented this small enhancement in pull request #4442

**Comment by smillidge** [comment]
Fixed by #4442
