### ISSUE TITLE
Enhancement: Create a FilteringClassLoader for EJB applications

### ISSUE THREAD

**Issue by AntiEntropy** [payara/Payara#419]
Weblogic allows an application to specify classes to prefer to be loaded from jars in the EAR file before delegating to the parent classloader.

the relevent part of weblogic-application.xml looks like this:

    <prefer-application- packages >
        <package-name>org.apache.log4j.*</package-name>
        <package-name>antlr.*</package-name>
    </prefer-application-packages>

I'm looking for a similar feature in Glassfish/Payara for EJB applications.

Or, something similar to the glassfish-web.xml class-loader delegate="false" that could be specified in the glassfish-application.xml would also suffice.

**Comment by smillidge** [comment]
Thanks for the suggestion. Is glassfish-web.xml class-loader delegate working for you in the web application case?

**Comment by EvilAI** [comment]
Yes, that works for me in web applications.

**Comment by mikecroft** [comment]
This is fixed in #760 and documented here:
https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html
