### ISSUE TITLE
Payara 5.193 fail class javax.servlet.http.HttpServletRequest

### ISSUE THREAD

**Issue by fereso** [payara/Payara#4196]
Excuseme I have a project to use 
javax.servlet.http.HttpServletRequest

Into payara 5.192 was very easy move from glassfish 4.1.2 to payara 5.192
But to move to 5.193 fail this class
javax.servlet.http.HttpServletRequest
ATTACH IMAGE FROM PACKAGE OF PAYARA 5.193
![image](https://user-images.githubusercontent.com/26122418/64229178-b3578700-ceae-11e9-8835-9637f70a2695.png)

ATTACH IMAGE FORM PACKAGE OF PAYARA 5.192
![image](https://user-images.githubusercontent.com/26122418/64229215-d2eeaf80-ceae-11e9-9d76-d5900ddbcf2e.png)

Payara 5.192 have more jars that 5.193
is it correct?

**Comment by fereso** [comment]
Hi, I checked MANIFEST.MF in glassfish/lib/javaee.jar from payara 5.192 and 5.193

This is 5.192:
Manifest-Version: 1.0
GlassFish-ServerExcluded: true
Built-By: jonathan
Class-Path: 
../modules/javax.servlet-api.jar 
../modules/javax.annotation-api.jar 
../modules/javax.ejb-api.jar 
../modules/javax.transaction-api.jar 
../modules/javax.enterprise.deploy-api.jar 
../modules/javax.management.j2ee-api.jar 
../modules/javax.resource-api.jar 
../modules/jakarta.security.auth.message-api.jar 
../modules/javax.security.jacc-api.jar 
../modules/webservices-osgi.jar 
../modules/jaxb-osgi.jar 
../modules/jakarta.xml.bind-api.jar 
../modules/webservices-api-osgi.jar 
../modules/javax.xml.rpc-api.jar 
../modules/javax.xml.registry-api.jar 
../modules/javax.mail.jar 
../modules/jakarta.faces.jar 
../modules/javax.servlet.jsp-api.jar 
../modules/javax.el.jar 
../modules/javax.servlet.jsp.jstl-api.jar 
../modules/javax.persistence.jar 
../modules/javax.jms-api.jar 
../modules/hibernate-validator.jar 
../modules/cdi-api.jar 
../../mq/lib/jaxm-api.jar 
../modules/javax.ws.rs-api.jar 
../modules/javax.json.jar 
../modules/javax.websocket-api.jar 
../modules/javax.enterprise.concurrent-api.jar 
../modules/javax.batch-api.jar
Created-By: Apache Maven 3.6.0
Build-Jdk: 1.8.0_212



And this is   5.193 
Manifest-Version: 1.0
GlassFish-ServerExcluded: true
Built-By: jenkins
Class-Path: 
../modules/**jakarta**.servlet-api.jar 
../modules/javax.annotation-api.jar 
../modules/**jakarta**.ejb-api.jar 
../modules/**jakarta**.transaction-api.jar 
../modules/javax.enterprise.deploy-api.jar 
../modules/javax.management.j2ee-api.jar 
../modules/**jakarta**.resource-api.jar 
../modules/**jakarta**.security.auth.message-api.jar 
../modules/**jakarta**.security.jacc-api.jar 
../modules/webservices-osgi.jar 
../modules/jaxb-osgi.jar 
../modules/**jakarta**.xml.bind-api.jar 
../modules/webservices-api-osgi.jar 
../modules/javax.xml.rpc-api.jar 
../modules/javax.xml.registry-api.jar 
../modules/**jakarta**.mail.jar 
../modules/**jakarta**.faces.jar 
../modules/javax.servlet.jsp-api.jar 
../modules/javax.el.jar 
../modules/javax.servlet.jsp.jstl-api.jar 
../modules/**jakarta**.persistence.jar 
../modules/**jakarta**.jms-api.jar 
../modules/hibernate-validator.jar 
../modules/cdi-api.jar 
../../mq/lib/jaxm-api.jar 
../modules/**jakarta**.ws.rs-api.jar 
../modules/**jakarta**.json.jar 
../modules/javax.websocket-api.jar 
../modules/javax.enterprise.concurrent-api.jar 
../modules/javax.batch-api.jar
Created-By: Apache Maven 3.5.4
Build-Jdk: 1.8.0_212

I think that the problem is because payara 5.193 have 
references to **jakarta**
So, al references to jakarta. dont come in payara 5.193. or I dont watch on my netbeans and is it not in modules. 
Is it normal? 
Or there a error of compilation?

**Comment by khasunuma** [comment]
NetBeans has not supported Payara 5.193 (or later) yet. In Payara 5.193, some modules are renamed as you reported so that it becomes compatible with Jakarta EE 8.

**Comment by fereso** [comment]
Hi...
The problem is not netbeans. My doubt is, how can I get a Payara 5.193 with all packages? 
Why when I use payara 5.193  Do not I have all jars necessary to deploy projects?

**Comment by smillidge** [comment]
You do have all the jars. The Jakarta jars are equivalent to the javax jars just released via the Eclipse Foundation Jakarta working group. Java EE has migrated to the Eclipse Foundation and will be released as Jakarta EE

**Comment by fereso** [comment]
Understand... 
Some idea for compile project and recognize the new jars      
jakarta.xxxx.jar
?

**Comment by smillidge** [comment]
Depends how you are compiling in NetBeans. If you  are using maven just use the usual JavaEE 8 pom.
