### ISSUE TITLE
Domain created from production template not starts with jdk11

### ISSUE THREAD

**Issue by maksitom** [payara/Payara#4213]
# Description #
----------
Domain created from production template not starts with jdk11

## Expected Outcome

Domain created from production template starts without any problems

## Current Outcome

`Waiting for production2 to start .Error starting domain production2.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

-Djava.endorsed.dirs=/opt/glassfish/payara5_193/payara5/glassfish/modules/endorsed:/opt/glassfish/payara5_193/payara5/glassfish/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

## Steps to reproduce (Only for bug reports) 

1 -**  Create new production domain from template
`asadmin create-domain --domainproperties domain.adminPort=24848:domain.instancePort=28080:domain.jmxPort=28686:http.ssl.port=28181:java.debugger.port=29009:jms.port=27676:orb.listener.port=23700:orb.mutualauth.port=23920:orb.ssl.port=23820:osgi.shell.telnet.port=26666 --template /opt/glassfish/payara5/glassfish/common/templates/gf/production-domain.jar production2`

2 -**  Start created domain
`asadmin start-domain production2`

## Root problem:
JVM Options:
-Djava.ext.dirs=${com.sun.aas.javaRoot}/lib/ext${path.separator}${com.sun.aas.javaRoot}/jre/lib/ext${path.separator}${com.sun.aas.instanceRoot}/lib/ext
-Djava.endorsed.dirs=${com.sun.aas.installRoot}/modules/endorsed${path.separator}${com.sun.aas.installRoot}/lib/endorsed

in domain from template have not defined min and max JVM Versions like in default production domain

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Full
- **JDK Version**: Zulu: 11.33.21
- **Operating System**:  Centos

**Comment by khasunuma** [comment]
I can't also start a domain created from production template with JDK 11, but it's different cause. I attached `domain.xml` and `server.log` (zipped into `config-and-log.zip`)
[config-and-log.zip](https://github.com/payara/Payara/files/3603603/config-and-log.zip)
.

I use Payara Server 5.193 (Full) and Oracle JDK 11.0.4 on Windows 10.

**Comment by maksitom** [comment]
I made mistake and put wrong path to template file (from old payara). There is no problem. I close issue
