### ISSUE TITLE
MicroProfile Metrics API returns no data for vendor:system_cpu_load PAYARA-4147

### ISSUE THREAD

**Issue by sschellh** [payara/Payara#4230]
# Description #
----------

Since Payara Micro 5.193 the /metrics endpoint does not return data for the field vendor:system_cpu_load anymore. The value is always zero.

## Expected Outcome

Calling GET {baseUrl}/metrics/vendor returns the field vendor:system_cpu_load with a value > 0.

## Current Outcome

Calling GET {baseUrl}/metrics/vendor the field vendor:system_cpu_load is _always_ zero.

Also the naming of the field changed.
Before 5.193 it is vendor:system_cpu_load
Since 5.193 it is vendor_system_cpu_load
(not that the : was replaced by _)

## Steps to reproduce (Only for bug reports) 

Execute java -jar payara-micro-5.193.jar --deploy anyApplication.war
Visit http://localhost:8080/metrics/vendor

### Samples

Payara Micro 5.191
  vendor:system_cpu_load 0.15454493453568963
  
Payara Micro 5.192
  vendor:system_cpu_load 0.5629938578656155
  
Payara Micro 5.193
  vendor_system_cpu_load 0

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Micro
- **JDK Version**: Oracle Jdk, OpenJdk (Version 1.8)
- **Operating System**: Windows, Linux

**Comment by khasunuma** [comment]
I reproduced it. The data source that is "java.lang:type=OperatingSystem/SystemCpuLoad" in MBean indicates correct value, so it's certainly a bug. I reported it as an internal issue (PAYARA-4147).

Note that Payara Micro 5.193 supports MP Metrics 2.0 that introduces some breaking changes. It's not affected directly, but it seems a regression by some reason.
