### ISSUE TITLE
Hassle when using Java 11 and adding JAX-WS XML-related dependencies

### ISSUE THREAD

**Issue by robelcik** [payara/Payara#4242]
# Description #
----------

I would be nice to have JAX-WS XML-related dependencies included in Payara Micro or have a guide describing how to add them when using Java 11.

## Expected Outcome

It would be nice to have a simple way of using SOAP web services with Payara Micro and Java 11. Since the JDK 11 does not include required dependencies it would be nice if Payara Micro has them or if there is a manual describing the proper way of adding them manually.

## Current Outcome

My project contains client code for SOAP web services. When migrating it to Java 11 I found that some classes are missing. After trial-and-error I made it working by adding com.sun.xml.ws:rt and com.sun.org.apache.xml.internal:resolver as dependencies. There were enough for my project - I'm not sure if that's enough in general case.

However, those added dependencies had sub-dependencies to other modules. And some of those are already provided by Payara Micro. In order to have my .war slimmer I excluded some of those. But, since I don't know much about the subject (e.g. differences between versions, potential side-effects), I'm not sure if my result is "correct". That's why I'm asking for having those deps inside Payara or having a simple guide on how to add them in a proper way.

## Environment ##

- **Payara Version**: 5.193
- **Edition**: MIcro
- **JDK Version**: 11/Oracle
- **Operating System**: Windows
- **Database**: none

**Comment by OndroMih** [comment]
Hi, SOAP services are not supported by Payara Micro. How do you use SOAP with Payara Micro?
I would say that supporting SOAP in Payara Micro and hence including the classes missing in Java 11 is out of scope and this issue will be closed. Can you explain why it makes sense to support what you're doing?

**Comment by robelcik** [comment]
Hello,

As I wrote in "Current Outcome" section, my application contains a small SOAP client. It uses "@WebServiceClient" classes with "@WebEndpoint" methods generated by the service provider. The client code (given by the provider) contains all those classes, model classes (generated from XSDs), WSDLs, and so on - everything needed to run a client.

It works perfectly fine with Payara Micro 5.193 on Java 8, without any added libraries.

Should I stop using Payara Micro and migrate to Payara Full?

**Comment by smillidge** [comment]
It is not Payara MIcro that has changed it is the JDK. It is still possible to get the SOAP classes from the Eclipse Metro project if you really need them. You could easily build yourself a custom micro image containing the jars you need using the `--add-libs` command line combined with `--outputuberjar` command line option then keep your slimmer jar.
