### ISSUE TITLE
MP JWT: Status 401 - Unauthorized when not providing optional JWT Field "jti"

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#4269]
[testjwt.zip](https://github.com/payara/Payara/files/3712767/testjwt.zip)
(# Description #
----------
Hi.

I made an example project based on Adam Biens Tutorial "Authentication and Authorization with Payara and MicroProfile JWT" https://www.youtube.com/watch?v=ozQzsVxFfXU
It is attached.
The Problem with payara:
If I left out the optional claim "jti" (see https://tools.ietf.org/pdf/rfc7519.pdf 4.1.7. "jti" (JWT ID) Claim) in the jwt token, the payara does not authorize the user. 

## Expected Outcome
I would expect, when I left out an optional parameter, there is no problem with the authentication.

## Current Outcome
 Status 401 - Unauthorized.

## Steps to reproduce (Only for bug reports) 
see the attached zip. 
YOu can run the buildAndRun.sh (docker and maven required). The user is authorized (as expected). Now go to the jwt-token.json and delete the jti Key and value. Rerun the Script.  Status 401 - Unauthorized is raised.
This is not expected.

)

**Comment by rdebusscher** [comment]
Hi,

According the the MicroProfile JWT specification, this **jti** claim is required. See https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc

> jti
> Provides a unique identifier for the JWT. The identifier value MUST be assigned in a manner that ensures ....

And further down

> An example minimal MP-JWT in JSON would be:
> 
> {
>      "typ": "JWT",
>     "alg": "RS256",
>     "kid": "abc-1234567890"
> }
> {
>        "iss": "https://server.example.com",
>        "jti": "a-123",
>        "exp": 1311281970,
>        "iat": 1311280970,
>        "sub": "24400320",
>        "upn": "jdoe@server.example.com",
>        "groups": ["red-group", "green-group", "admin-group", "admin"],
> }

The MicroProfile JWT specification has some additional claims and defined some additional requirements on top of the 'standard' JSON Web Token specification.

So the Payara implementation behaves as expected according to the specification.
