### ISSUE TITLE
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by snukone** [payara/Payara#4276]
# Description #
----------

If we deploy our Microservice in Payara Micro 5.193, we get from time to time java.net.SockettimeoutExeptions when calling another Rest-Endpoint of a different Microservice via jax rs Client. For time to time means: when we restart payara, it can happen that the error occurs after one the restarts. When the error is occuring, it occurs till the next restart of the server. When calling the Rest-Endpoint of the second Microservice via CURL, we get a valid JSON-Response - immediatly, it takes about 1-2 seconds to get the response. IMPORTANT: If we restart the Payara Micro Instance of the first Microservice, which gets the 500 http status code, the Rest-Calls are working. Its only in some cases that the behavior is upcoming. We are running all the Microservices in an docker environment. Its poorly not possible to show the code or push the images so that you can direct test with them.

I am posting this Exception here, because i think its maybe in relation to the Payara Version 5.193. We switch to 5.193 two weeks ago. Since then we have this behavior. The problem is occuring in different microservices, not just at one.

What i also thought about are the dependencies - maybe there are transitive one that are conflicting with each other.

Also, that the loggername is fish.payara.microprofile.opentracing.jaxrs.JaxrsContainerRequestTracingFilter is not clear for me. We are not using request tracing. 

## Expected Outcome

 A valid JSON when calling the Rest Endpoint of another Microservice with HTTP Statuscode 200.

## Current Outcome

When calling the Rest-Endpoint of a Microservice, which is calling another Rest-Endpoint of a different Microservice, the GET is sometimes failing with status code 500. And its not just one single microservices where this happens, it happens randomly.

The sourcecode where the error happens of the first Microservice is as follows:

```
...
import io.openapitools.jackson.dataformat.hal.HALLink;

import javax.inject.Inject;
import javax.json.JsonObject;
import javax.ws.rs.client.Client;
import javax.ws.rs.core.MediaType;

public class Gateway {

  @Inject
  @Immutable
  Client client;

  public Daten getDaten() {
    LinkFactory linkFactory = new LinkFactory();
    HALLink link = linkFactory.domainLink("/test");
    JsonObject daten = client
        .target(link.getHref())
        .request(MediaType.APPLICATION_JSON)
        .get(JsonObject.class); // <-- HERE ITS FAILING
    return new Daten(daten);
  }

}
```

This is the stacktrace:

{"Timestamp":"2019-10-16T15:32:14.111+0200","Level":"SEVERE","Version":"","LoggerName":"fish.payara.microprofile.opentracing.jaxrs.JaxrsContainerRequestTracingFilter","ThreadID":"28","ThreadName":"http-thread-pool::http-listener(1)","TimeMillis":"1571232734111","LevelValue":"1000","Throwable":{"Exception":"javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: connect timed out","StackTrace":"javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: connect timed out\n\tat org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)\n\tat org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)\n\tat org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:743)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:205)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)\n\tat org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:741)\n\tat org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)\n\tat org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)\n\tat fish.payara.requesttracing.jaxrs.client.decorators.JaxrsInvocationBuilderDecorator.get(JaxrsInvocationBuilderDecorator.java:210)\n\tat Gateway.getDaten(Gateway.java:32)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)\n\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)\n\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)\n\tat org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)\n\tat org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)\n\tat org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:579)\n\tat com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)\n\tat org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)\n\tat org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)\n\tat org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)\n\tat org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)\n\tat org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)\n\tat org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)\n\tat org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)\n\tat org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)\n\tat org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)\n\tat org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)\n\tat org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)\n\tat org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.net.SocketTimeoutException: connect timed out\n\tat java.net.PlainSocketImpl.socketConnect(Native Method)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n\tat java.net.Socket.connect(Socket.java:589)\n\tat sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)\n\tat sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n\tat sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n\tat sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n\tat sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)\n\tat sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)\n\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)\n\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)\n\tat java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)\n\tat org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)\n\tat org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)\n\t... 70 more\n"}}

Some of the Dependencies we are using:

```
[INFO] +- io.openapitools.jackson.dataformat:jackson-dataformat-hal:jar:1.0.4:compile
[INFO] +- org.eclipse.microprofile:microprofile:pom:1.4:provided
[INFO] |  +- javax.enterprise:cdi-api:jar:1.2:provided
[INFO] |  |  +- javax.el:javax.el-api:jar:3.0.0:provided
[INFO] |  |  +- javax.interceptor:javax.interceptor-api:jar:1.2:provided
[INFO] |  |  \- javax.inject:javax.inject:jar:1:provided
[INFO] |  +- javax.json:javax.json-api:jar:1.0:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.2:provided
[INFO] |  +- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:jar:1.1:provided
[INFO] |  +- org.eclipse.microprofile.health:microprofile-health-api:jar:1.0:provided
[INFO] |  +- org.eclipse.microprofile.metrics:microprofile-metrics-api:jar:1.1:provided
[INFO] |  +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:1.0:provided
[INFO] |  +- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:1.1:provided
[INFO] |  \- org.eclipse.microprofile.opentracing:microprofile-opentracing-api:jar:1.1:provided
[INFO] |     \- org.apache.geronimo.specs:geronimo-atinject_1.0_spec:jar:1.0:provided
[INFO] +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.3:provided
[INFO] |  \- org.osgi:org.osgi.annotation.versioning:jar:1.0.0:provided
[INFO] +- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:jar:1.1.1:provided
[INFO] +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.9:compile
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.9:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jaxrs:jar:2.9.9:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr353:jar:2.9.9:compile
[INFO] +- com.sun.jersey:jersey-server:jar:1.19.4:test
[INFO] |  \- com.sun.jersey:jersey-core:jar:1.19.4:test
[INFO] |     \- javax.ws.rs:jsr311-api:jar:1.1.1:test
[INFO] +- org.glassfish.jersey.core:jersey-client:jar:2.27:test
[INFO] |  \- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b42:test
[INFO] +- org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.27:test
[INFO] |  \- org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.27:test
[INFO] +- org.glassfish.jersey.media:jersey-media-json-processing:jar:2.27:test
[INFO] |  +- org.glassfish:javax.json:jar:1.1:test
[INFO] |  \- org.glassfish:jsonp-jaxrs:jar:1.1.1:test
[INFO] +- org.glassfish.jersey.core:jersey-common:jar:2.27:test
[INFO] |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:test
[INFO] +- org.apache.commons:commons-lang3:jar:3.4:test
[INFO] +- com.google.guava:guava:jar:26.0-jre:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
```

## Steps to reproduce (Only for bug reports) 

It happens sporadically and we are not allowed to share our code :(

## Context (Optional)

If you think this hasnt anthing to do with payara micro im sorry for posting this here. Im not sure at the moment where the best place is to post this issue. We already tried to hard to trace the source of this error but we were not successful. Maybe some of you are aware of possibilities where the error can comes from. Our last possiblity would be a healthcheck to check if GET-Calls via jax-rs client are possible. But to know the source of the error would rather be nice.

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Micro
- **JDK Version**: JDK8
- **Operating System**: Linux / Mesos

**Comment by snukone** [comment]
Due to the fact, that the Exception is stating Network-Problems, we are testing currently the connectivity of the container were the server is running. Maybe the server cant access external URLs. This would mean that the docker daemon of one the hosts isnt working properly.

**Comment by snukone** [comment]
The error wasnt based on payara at all! It was in fact a docker issue.

Happy coding :)

**Comment by akshay-das** [comment]
@snukone Can you please explain more about this docker issue? I might be facing the same one.

**Comment by snukone** [comment]
Hi @akshay-das, it took i while till i remebered the Solution. We are running the container in an containerplattform. One of the agents had Problems With its docker deamon. The Plattform consist of about 40 Single Hostmachines (agents). It Took a while till I found out that one of them is responsible for the error meantioned above. A simple restart of the agent fixed the problem if i remember correctly.
