### ISSUE TITLE
Impossible to inject a datasource that contains an underscore (_) and no slash

### ISSUE THREAD

**Issue by wasadigi** [payara/Payara#4288]
# Description #
----------
I created a JDBC connection pool and a JDBC resource. Usually, I name my JDBC resources `jdbc/whatever`. But in this case, I used `what_ever`. The specific pattern is that there is an underscore and not slash in the datasource name.

We were able to work around the issue by renaming our data source, but wanted to capture this learning in the case other users have the idea to name their datasource xxx_yyy. 

## Expected Outcome

I should be able to inject my data source in my EJB with 

```
@Resource(name = "jdbc_whatever")
private DataSource dataSource;
```

## Current Outcome

It does not work. In the server log, I get:
```
payara        | Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Res-Ref-Env-Property: jdbc_wscalendar@javax.sql.DataSource@ resolved as: jndi: jdbc_whatever@res principal: null@mail: null
```

I tried several permutations:
* `jdbc/what_ever` works
* `whatever works`
* `what_ever` does not work

## Steps to reproduce (Only for bug reports) 

1 -**  Create a domain

2 -**  Add a connection pool and a JDBC resource with asadmin

```
create-jdbc-connection-pool --driverclassname com.mysql.jdbc.Driver --restype java.sql.Driver --property user=xxx:password=xxx:URL=jdbc\:mysql\://db\:3306/amt:useSSL=false:allowPublicKeyRetrieval=true amtpool
create-jdbc-resource --connectionpoolid amtpool jdbc_whatever
```

3 -**  Inject the datasource in a Stateless Session Bean

```
@Stateless
public class TestManager implements TestManagerLocal {
    @Resource(name = "jdbc_whatever")
    private DataSource dataSource;
    ...
}
```

4 -**  Deploy the app and see the error in the log files (and see that injection does not happen)

## Environment ##

- **Payara Version**: 5.183 (Docker image payara/server-full:5.183)
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Linux (Docker)
- **Database**: MySQL

**Comment by fturizo** [comment]
@wasadigi, it seems that the particular case that you are encountering, which is to use a JNDI reference with only an underscore character is not a valid use case for the current grammar used by JNDI. As such,  it is not recommended to use names that are compatible with the grammar, so it is better to use the `jdbc/` prefix for naming any JDBC resource to prevent this confusion. Considering the nature of the problem, we'll proceed to close this issue then.
