### ISSUE TITLE
Payara 5.193 The SSL certificate has expired

### ISSUE THREAD

**Issue by pagariyaalok** [payara/Payara#4295]
# Description #
----------

Running integration test and seeing message :  The SSL certificate has expired

## Current Outcome

00a1c2> [2019-10-31T23:53:35.782+0000] [] [SEVERE] [NCLS-SECURITY-05054] [javax.enterprise.system.security.ssl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1572566015782] [levelValue: 1000] [[
00a1c2>   The SSL certificate has expired: [
00a1c2> [
00a1c2>   Version: V3
00a1c2>   Subject: CN=UTN - DATACorp SGC, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
00a1c2>   Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5
00a1c2> 
00a1c2>   Key:  Sun RSA public key, 2048 bits
00a1c2>   modulus: 28268673816178652097323205892483557333571155870875470430960147296575080125058259576216678502943701783863235065864619513554332825256576232328090594008995653938402850832639909846660254240227871328870817423755670515240676922575555781981369246549012690884955359776531332666259760261360631995682094260285182867794701000430219975797941893404079475222143745688332320735114398825135169097291174452108993502788913943850837279188978684549502068499879944154157617599256436144641192788443262416163408036570340837806929138395134745754413204505641922381176732200396779902698082435830886530134629482115518533241525728911403361018543
00a1c2>   public exponent: 65537
00a1c2>   Validity: [From: Thu Jun 24 18:57:21 GMT 1999,
00a1c2>                To: Mon Jun 24 19:06:30 GMT 2019]
00a1c2>   Issuer: CN=UTN - DATACorp SGC, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
00a1c2>   SerialNumber: [    44be0c8b 500021b4 11d32a68 06a9ad69]
00a1c2> 
00a1c2> Certificate Extensions: 5
00a1c2> [1]: ObjectId: 2.5.29.19 Criticality=true
00a1c2> BasicConstraints:[
00a1c2>   CA:true
00a1c2>   PathLen:2147483647
00a1c2> ]
00a1c2> 
00a1c2> [2]: ObjectId: 2.5.29.31 Criticality=false
00a1c2> CRLDistributionPoints [
00a1c2>   [DistributionPoint:
00a1c2>      [URIName: http://crl.usertrust.com/UTN-DATACorpSGC.crl]
00a1c2> ]]
00a1c2> 
00a1c2> [3]: ObjectId: 2.5.29.37 Criticality=false
00a1c2> ExtendedKeyUsages [
00a1c2>   serverAuth
00a1c2>   1.3.6.1.4.1.311.10.3.3
00a1c2>   2.16.840.1.113730.4.1
00a1c2> ]
00a1c2> 
00a1c2> [4]: ObjectId: 2.5.29.15 Criticality=false
00a1c2> KeyUsage [
00a1c2>   DigitalSignature
00a1c2>   Non_repudiation
00a1c2>   Key_CertSign
00a1c2>   Crl_Sign
00a1c2> ]

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.30.0:start (test-image) on project microprofile: I/O Error: [appsvc-microprofile:latest]: Timeout after 20068 ms while waiting on url http://localhost:8080 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

fish.payara.maven.plugins version 1.0.1
payaraVersion 5.193

**Comment by rdebusscher** [comment]
Hi,

Based on the Payara Forum message, you are trying to run the integration test from this project 
https://github.com/Azure-App-Service/java/tree/dev/integration-test/microprofile-payara.

When I run that code (with Payara 5.191 or 5.193 version) both succeed.

There is indeed the expired certificate message, but that doesn't affect the execution (unless you would use that specific CertPlus certificate.)

So there must be some other error message in the log which would explain the timeout.

Rudy

**Comment by pagariyaalok** [comment]
Thanks for the confirmation. Actually the messages are printed as SERVER so wanted to double check. I’ll ignore this message.

[2019-11-04T19:49:00.580+0000] [] [SEVERE] [NCLS-SECURITY-05054] [javax.enterprise.system.security.ssl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1572896940580] [levelValue: 1000] [[
d23853>   The SSL certificate has expired: [
