### ISSUE TITLE
Duplicate classpath entries when using Extreme Classloading Isolation

### ISSUE THREAD

**Issue by rtwruck** [payara/Payara#4307]
# Description #
----------

When using `<whitelist-package>` in `glassfish-application.xml`, libraries from an EAR's /lib directory appear twice on the WebApp ClassLoader's class path, leading to issues like the well known

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/payara41/glassfish/domains/domain1/applications/my-application/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]]]
SLF4J: Found binding in [jar:file:/opt/payara41/glassfish/domains/domain1/applications/my-application/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]]]
```

where both entries reference the same JAR file.

## Expected Outcome

SomeClass.getClassLoader().getResources("org/example/config.properties") returns a single URL (or at least multiple unique URLs).

### WITHOUT `<whitelist-package>`:

- **SomeClassFromWARclassesDir**.getClassLoader().getResources("org/example/config.properties") returns **two identical** URLs,
- **SomeClassFromEARlibJar**.getClassLoader().getResources("org/example/config.properties") returns **a single** URL

when given a resource name that is contained in a JAR from EAR /lib.

### WITH any `<whitelist-package>`:

- **SomeClassFromWARclassesDir**.getClassLoader().getResources("org/example/config.properties") returns **two identical** URLs,
- **SomeClassFromEARlibJar**.getClassLoader().getResources("org/example/config.properties") returns **two identical** URLs

when given a resource name that is contained in a JAR from EAR /lib.

## Steps to reproduce (Only for bug reports) 

Deploy an EAR:
```
META-INF/MANIFEST.MF
META-INF/application.xml
META-INF/glassfish-application.xml
lib/my-library.jar
my-webapp.war
```
WAR contents (my-webapp.war):
```
META-INF/MANIFEST.MF
WEB-INF/classes/org/example/web/IndexServlet.class
```
JAR contents (my-library.jar):
```
META-INF/MANIFEST.MF
org/example/BackendService.class
org/example/config.properties
```

Call getResources("org/example/config.properties") on IndexServlet's ClassLoader and BackendService's ClassLoader.

Notes:

- It does not matter which package is specified in `<whitelist-package>`; I used `org.apache.taglibs` which is unrelated to the packages used in the test.
- The WAR was created with Maven's `skinnyWars` option and thus has a Class-Path entry in its MANIFEST.MF: `Class-Path: lib/my-library.jar`.

## Environment ##

- **Payara Version**: 5.193.1, 4.181
- **Edition**: Full
- **JDK Version**: 8 (Docker payara/server-full:5.193, payara/server-full:4.181)
- **Operating System**: Linux
- **Database**: n/a

**Comment by rtwruck** [comment]
**Workaround:**

Manually removing the `Class-Path` from the WAR's MANIFEST.MF fixes the problem when `<whitelist-package>` is active.

Without `<whitelist-package>`, this results in
```
java.lang.ClassNotFoundException: org.example.BackendService
```
as expected.

**Comment by rtwruck** [comment]
OK, it turns out to be more complicated than I thought :-(

First of all, "Extreme Classloading Isolation" only applies to `ClassLoader.loadClass()` but to none of its other methods. This means that with `<whitelist-package>` enabled, **you can still "see" all Classes** via `getResource("my/package/Some.class")` but `loadClass("my.package.Some")` will fail unless my.package is on the whitelist. **Resources from module JARs** will not be affected by `<whitelist-package>` and **still take precedence** over resources from JARs in EAR/lib.

Second, in the default setup **when** `<whitelist-package>` **is not enabled**, classes found in EAR/lib are loaded by the `EarLibClassLoader`. When two WARs use the same class, it will be loaded once and **both WARs use the same Class instance** - this is what you want.
In contrast, **when** `<whitelist-package>` **is enabled**, classes from EAR/lib, too, get loaded by the `WebappClassLoader` because the JARs are referenced in the manifest's `Class-Path` attribute. When two different WARs use the same class, it will be loaded by both WebappClassLoaders and **each WAR will use its own instance of the class.**

Third, when there is no `Class-Path` entry in the WAR's manifest and `<whitelist-package>` is enabled, **a class found in EAR/lib will not be loaded** by the WebappClassLoader because it's not on its classpath **and it will not delegate** to the EarClassLoader because the package is not on the whitelist, **thus classes from EAR/lib cannot be loaded**.
When a WAR is deployed as part of an EAR, whitelist checking should not be done by the WebappClassLoader but by the EarLibClassLoader.

--

Applied to the original bug report above:
- Seeing duplicate entries when querying the WebappClassLoader "works as designed", as they are present in the WebappClassLoader as well as the EarLibClassLoader - GlassFish did that, too.
- Duplicate entries when querying the ClassLoader of a class loaded from EAR/lib occurs because that ClassLoader is actually the WebappClassLoader and an indication that multiple WARs don't share Class instances from EAR/lib anymore - which breaks SLF4J among many other things.

**Comment by fturizo** [comment]
@rtwruck, I have tried to reproduce the issue that you reported but unfortunately I wasn't able to found any issues on release 5.194. Can you provide a complete reproducer (maybe a link to a GH repository) that showcases the error in detail? I'm afraid that without a reproducer we cannot offer any assistance for the moment.

**Comment by fturizo** [comment]
Closing this issue as there's no response from the original user.

**Comment by rtwruck** [comment]
Hi @fturizo,
I know it's been a while but I actually did manage to set up a reproducer along with a bunch of test cases and the actual patch that I made to fix this.

https://github.com/rtwruck/payaratest

Would you be able to take a look at the test cases? They are duplicated for testing with whitelisting disabled and enabled.
