### ISSUE TITLE
classloader favors modules/xxx.jar over xxx library in the ear / war (guava, jackson, etc.)

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#431]
This is an upstream bug: https://java.net/jira/browse/GLASSFISH-20850

**Comment by smillidge** [comment]
Strictly speaking this is not a bug unless it is a war file loading the classes and parent first delegation is correct except for war files. See #419 for an enhancement request we are looking at for ejb classloaders.

adding the below element into glassfish-web.xml should resolve the problem in war files. If this doesn't resolve it for a war then that's a bug.
```xml
<class-loader delegate="false" />
```

**Comment by lprimak** [comment]
The above is correct, however, here is another use case:
When JARs are put into <domain>/lib, the modules/xxx.jar erroneously takes precedence to <domain>/lib/xxx.jar, and there is nothing that can be done to prevent this, same as with .ear files.
This use case is fairly common with skinny WARs for development.

**Comment by lprimak** [comment]
This issue is fixed in the .162 release

The functionality is enabled with system property:
`fish.payara.classloading.delegate=false`
similar to configuration in glassfish-web.xml
Also, the functionality can be enabled in individual EAR files with the entry:
`<classloading-delegate>false</classloading-delegate>`
in glassfish-application.xml
