### ISSUE TITLE
[Question] How to correctly set the hazelcast management-center url for a payara micro instance

### ISSUE THREAD

**Issue by yacut** [payara/Payara#4318]
# Description #
I want to use the hazelcast management center with payara micro and I'm tring to set the right config for this. For hazelcast discovery I also use additional command line options, like `--clustername`, `--clustermode` etc. The only way for the "management center" I found was to set `----hzconfigfile hazelcast.xml`. Unfortunately, this overwrites the other configurations I have set before to hazelcast defaults (discovery, port etc.). Do I really need to pass on the full hazelcast config or I'm doing something wrong?

My hazelcast.xml looks like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd">
    <management-center enabled="true">http://hazelcast-mancenter:8080/hazelcast-mancenter/</management-center>
</hazelcast>
```

My start command looks like this:

```sh
java -jar ./payara-micro.jar \
  --deploy some.war \
  --hzconfigfile hazelcast.xml \
  --name instance-1 \
  --clustername my-cluster \
  --clustermode kubernetes:default,my-svc \
  --startport 6900
```

## Expected Outcome

Payara Micro starts in **kubernetes** cluster mode with cluster port **6900** and the hazelcast management center url is set to `http://hazelcast-mancenter:8080/hazelcast-mancenter/`

## Current Outcome
Payara Micro starts in **multicast** cluster mode with cluster port **5701** and the hazelcast management center url is set to `http://hazelcast-mancenter:8080/hazelcast-mancenter/`

## Environment ##
- **Payara Version**: 5.193.1
- **Edition**: Micro

**Comment by yacut** [comment]
@smillidge ping

**Comment by yacut** [comment]
related to https://github.com/payara/Payara/issues/4326

**Comment by smillidge** [comment]
To use management center you would need to pass in a fully configured hazelcast config file. Once you do that all other hazelcast settings on the command line are ignored.

**Comment by rdebusscher** [comment]
As indicated, when using the  `--hzconfigfile` option, all config related to Hazelcast must be set in the referenced file and command-line options (related to Hazelcast config) are ignored.
