### ISSUE TITLE
Slow instance start

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4319]
# Description #
----------

When instance is starting it prints start command to the log, and freezes for 2 minutes, then makes instance server log to be rolled and then starts properly. For example the old log was **instance_server.log**

And it had some data in it. When instance was starting it printed to this log:
`[2019-11-13T09:34:32.430+0100] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1573634072430] [levelValue: 800] [[
  JVM invocation command line:
/opt/glassfish/zulu8.38.0.13-ca-jdk8.0.212-linux_x64/bin/java
-cp
/opt/glassfish/payara5/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:MetaspaceSize=256m
-XX:+DisableExplicitGC
-XX:+UseStringDeduplication
-XX:MaxMetaspaceSize=2g
-XX:+IgnoreUnrecognizedVMOptions
-XX:+UseG1GC
-XX:MaxPermSize=512m
-XX:MaxGCPauseMillis=500
-Xms2g
-Xbootclasspath/p:/opt/glassfish/payara5/glassfish/lib/grizzly-npn-bootstrap-1.8.1.jar
-Xmx25g
-server
-javaagent:/opt/glassfish/payara5/glassfish/lib/monitor/flashlight-agent.jar
-Djava.security.auth.login.config=/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance/config/login.conf
-Dlog4j.configuration=file:////opt/glassfish/hod/log4j.properties
-Djavax.net.ssl.trustStore=/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance/config/cacerts.jks
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dpl.orangelabs.hod.applicationpath=/opt/glassfish/hod
-Dcom.sun.aas.instanceRoot=/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance
-Djava.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$-6s [%2$s] %5$s%6$s%n
-Dcom.sun.aas.installRoot=/opt/glassfish/payara5/glassfish
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=hod.corpnet.pl
-Djava.endorsed.dirs=/opt/glassfish/payara5/glassfish/modules/endorsed:/opt/glassfish/payara5/glassfish/lib/endorsed
-Djava.security.policy=/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance/config/server.policy
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Ducp.properties.file.path=/opt/glassfish/hod/ucp.properties
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Djava.ext.dirs=/opt/glassfish/zulu8.38.0.13-ca-jdk8.0.212-linux_x64/lib/ext:/opt/glassfish/zulu8.38.0.13-ca-jdk8.0.212-linux_x64/jre/lib/ext:/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true
-Djavax.net.ssl.keyStore=/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance/config/keystore.jks
-Dlogback.configurationFile=/opt/glassfish/hod/logback.xml
-Djava.library.path=/opt/glassfish/payara5/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-read-stdin
true
-asadmin-args
--host,,,pahod003,,,--port,,,14848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-local-instance,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--node,,,pahod002_node,,,pahod002_instance
-instancename
pahod002_instance
-type
INSTANCE
-verbose
false
-instancedir
/opt/glassfish/payara5/glassfish/nodes/pahod002_node/pahod002_instance
-asadmin-classpath
/opt/glassfish/payara5/glassfish/modules/admin-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]
`

Then the instance has been frozen for 2 minutes, afer that time it rolled this log, changing its name to:
instance_server.log_2019-11-13T09-36-53

And then started starting properly, printing to the instance_server.log:
`2019-11-13 09:36:53 INFO   [com.sun.enterprise.server.logging.LogManagerService postConstruct] Running Payara Version: Payara Server  5.191 #badassfish (build 94)`

The questions are:
1. Shouldn't log be rolled exactly then instance started starting?
2. Why instance is frozen for 2 minutes? For production environments it is unacceptable.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: zulu8.38.0.13-ca-jdk8.0.212-linux_x64
- **Operating System**: RHEL
- **Database**: MySQL

**Comment by rdebusscher** [comment]
Hi @peterpz1 

Can you give us some information about your environment to investigate the issue more.

- Does this occur when you startup Payara without an application or with an application already deployed on it?
- Did you made some changes to the configuration, if so which one. (and what is the size for example of the file instance_server.log_2019-11-13T09-36-53)
- Does your application, if it is already deployed, contain Singleton EJB beans which are initialised or CDI callback events for ApplicationScope (@Observes @Initialized(ApplicationScoped.class))
- Is there no other output between the 2 entries you mention? is there any indication in the additional entries about what takes up that time?

Thank you
regards
Rudy

**Comment by peterpz1** [comment]
I did some testing, because this was serious problem and it seems that we had wrongly assigned Xmx option. It was set to 70% of the OS RAM, causing it to use swap, which was really slowing everything. From what I see now additional memory apart from heap is over twice the heap size, so now we are testing settings on about 40% level and swap is not used, payara behaves properly...

**Comment by rdebusscher** [comment]
Hi @peterpz1

Good to hear you found the cause.

Regards
Rudy
