### ISSUE TITLE
Clustered / Versioned applications cannot be enabled on individual cluster instances

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#433]
Regression from GlassFish 3.1.2.2
This is an upstream bug: https://java.net/jira/browse/GLASSFISH-21198

**Comment by smillidge** [comment]
I am seeing subtly different behaviour. 

If I have a cluster test-cluster with two instances test1c test2c

If I have two versions of an application deployed.
app:1.0
app:2.0

deployed initially using
```shell
asadmin deploy --target test-cluster  -name app:1.0 app.war
asadmin deploy --target test-cluster --enabled false -name app:2.0 app.war
```

The version 1.0 application is available from both nodes.

If I then do
```shell
asadmin enable --target test1c app:2.0
```

The application is accessible on test1c but a 404 is given for test2c

If i then do
```shell
asadmin enable --target test2c app:2.0
```

The application is again available on both nodes.

**Comment by lprimak** [comment]
That behavior looks correct. My version has letters in it such as 2.1-stage this is not disallowed and is in GF examples. Perhaps this causes the difference. I'll re-test with numbered version only and let you know

**Comment by smillidge** [comment]
My understanding is that when the 2.0 version is enabled on test1c the 1.0 version should remain available on test2c.

**Comment by lprimak** [comment]
That's correct. Isn't this what you are seeing?  I'm not seeing this in my tests with letters in version numbers.

**Comment by lprimak** [comment]
Sorry, I misread your comments above. The above is the exact behavior I am seeing as well,
which is the issue at hand.  It doesn't matter what the version string looks like.
Right now, it's impossible to do rolling upgrades on GF 4.1

Thank you for looking at this issue.

**Comment by ratcashdev** [comment]
#270 is pretty much a duplicate as far as clusters as concerned, although it would not be bad if rolling updates would work on a standalone instance as well.

**Comment by lprimak** [comment]
Rolling upgrades work on GF 4.1 right now with standalone instances, just not with clusters. I don't see a reason why it wouldn't work the same with Payara.

**Comment by ratcashdev** [comment]
If that's true (somehow I could not achieve it, but will try again following the process outlined by @smillidge  without the 'target' option) then #270 could be simply closed. Will post back with my results.

**Comment by smillidge** [comment]
Standalone instances and versioned apps should work fine on Payara. In fact configuring standalone instances with Hazelcast web session clustering across the instances, by specifying the same Hazelcast configuration will also give HA web sessions similar to a "cluster". So full HA rolling updates are possible with standalone instances.

Problem is only cluster related as the version is disabled across all cluster instances rather than just the target cluster instance.

**Comment by ratcashdev** [comment]
Checked in 4.1.153. I can confirm, rolling updates in standalone instance works. #270 can be closed.
