### ISSUE TITLE
Pojos with the @Schema annotation will not be scanned if they are outsourced in a jar /CUSTCOM-67

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#4334]
# Description #
----------

To reuse certain pojos for rest responses we have outsourced them to jars. As soon as these are outsourced to jars, they are no longer scanned by Payara and are therefore not listed in the openapi file in the components -> schemas section.

## Expected Outcome

```
components:
  schemas:
    UserResponse:
      properties:
        name:
          type: string
          description: the username
          example: mustermann
      description: POJO that represents a user.
```

## Current Outcome

```
components:
  schemas:

```

## Steps to reproduce (Only for bug reports) 

1 -**  Put Pojo with @Schema Annotation in your projects classpath.
2 -**  Start Payara
3 -**  Call http://localhost:8080/openapi
The Schema is listet in components -> schemas section

4 -**  Now move this pojo to an external jar and import this jar.
5 -**  Start Payara
6 -**  Call http://localhost:8080/openapi
The schemas section is empty.

### Samples

```
    @GET
    @Path("/v2/find")
    @Consumes(MediaType.TEXT_PLAIN)
    @Produces(MediaType.APPLICATION_JSON)
    @Tag(name = "user", description = "Operations related to users.")
    @Operation(summary = "Find user by id.", description = "Find a specific User by Datenbase PK ID", operationId = "findById")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Successful, returning the Username.", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = UserResponseDto.class)))
    })
    public Response findById(@Parameter(description = "The database unique key.", required = true, example = "1", schema = @Schema(type = SchemaType.INTEGER)) @QueryParam("id") Integer id) {
      ...
    }
```

```
@Schema(name = "UserResponse", description = "POJO that represents a user.")
public class UserResponseDto {

    @Schema(name = "name", description = "the username", example = "mustermann")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

## Environment ##

- **Payara Version**: 5.193
- **Edition**:  Micro
- **JDK Version**: Amazon Corretto 8u222
- **Operating System**:  Docker / Linux

**Comment by rdebusscher** [comment]
Hi Lars,

Not all classes on the classpath are scanned for the annotation @schema as this is to resource intensive. Also the MicroProfile OpenAPI doesn't specify what classes needs to be scanned.

When referring to the class from within @APIResponse, this should be picked up but also here, the same issue as you described in #4331 can result in not showing the schema information.

    @GET
    @APIResponse(description = "Get the User information", content = @Content(mediaType = "application/json",
            schema = @Schema(implementation = UserResponseDTO.class)))
    public UserResponseDTO getUser() {
        return new UserResponseDTO();
    }

We will test again when the version 5.194 is released to verify if this issue is still present.

Regards
Rudy

**Comment by LarsBrenker** [comment]
Nothing has changed in version 5.194. The behavior is the same

**Comment by rdebusscher** [comment]
Hi @LarsBrenker 

I have created the internal issue `CUSTCOM-67` to fix this behaviour. 

Regards
Rudy

**Comment by smillidge** [comment]
Fixed by #4764

**Comment by LarsBrenker** [comment]
Unfortunately, I cannot confirm that the problem is resolved. An update to 5.2020.3 leads to the same problem. Then I saw that a parameter `mp.openapi.scan.lib = true` scans the external libs. However, this leads to a StackOverflowError when calling /openapi.

I didn't open a bug because the following bug has already been reported.
https://github.com/payara/Payara/issues/4818

**Comment by LarsBrenker** [comment]
I looked at it again in 5.2020.7 and noticed that it now works. To close the subject properly I just wanted to say that the problem doesn't seem to exist anymore
