### ISSUE TITLE
Possible WebappClassLoader leak (permgen issue)

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara#434]
While developing and regularly deploying instances on my local server, I am encountering OutOfMemory errors on the PermGen side of things. After examining the jvm with jvisualvm I can confirm that each redeploy causes an increment in the permgen size and forcing GC does not alleviate the problem.

Even with JDK 1.7 options -XX:+CMSPermGenSweepingEnabled and -XX:+CMSClassUnloadingEnabled enabled, the permgen size does not go down.

Close inspection via heapdump shows that for every deploy a new WebappClassloader is created(which is normal) but existing ones do not disappear(started flag is at false). and thus the heap continues to grow.

![permgen_issue](https://cloud.githubusercontent.com/assets/13536281/9757971/ffec165e-56e3-11e5-987b-8aa22e96a312.png)

Heapdump can be downloaded from https://www.dropbox.com/s/o10i4394g2aq5l9/heapdump-payara.zip?dl=0

**Comment by smillidge** [comment]
These classloaders seem to be held in Wicket-PageSavingThread through AmChartsSerializeHandler through a jackson databind ObjectMapper
![screenshot from 2015-09-10 13 47 30](https://cloud.githubusercontent.com/assets/939073/9788553/95f27cc2-57c2-11e5-9403-1f92b7e9f11b.png)

**Comment by dorpsidioot** [comment]
Strangely that should be auto-cleaned after undeployment, I will check where it gets stuck and why, since the ObjectMapper is completely standalone for the whole thing.

**Comment by dorpsidioot** [comment]
Disabled the Objectmapper and removed references for testing and it still retained heap, used classloader-leak-prevention(https://github.com/mjiderhamn/classloader-leak-prevention) and then I do not experience the leaks anymore.
I will be investigating this further to see if I find where the issue lies, if it's on my side then I can fix it here, if not I will come back to you guys with more information.

**Comment by dorpsidioot** [comment]
The classloader-leak-prevention does its job and forces the cleanup, now I am not sure where the problem lies, but I will investigate further.

**Comment by dorpsidioot** [comment]
Update: the problem no longer occurs when deploying, but when using auto-deploy or redeploy it persists, which is quite annoying while developing(encountering the permgen issue once every half an hour now).

**Comment by dorpsidioot** [comment]
Preliminary testing with pre-release build 154 seems to indicate fewer issues with leaks when using auto-deploy/redeploys, testing further in the next few days.

**Comment by dorpsidioot** [comment]
Can confirm closure of this issue, with the nightly builds the leaks are a thing of the past it seems. Only in debug mode does it still lock some files, but that has no impact on production.
