### ISSUE TITLE
Entities supplied via remote facade always null filled.

### ISSUE THREAD

**Issue by sgparry** [payara/Payara#4345]
# Description #
----------

I am hoping this is not an actual bug; that I am just missing a Payara configuration parameter somewhere that will persuade it to behave.

I am trying to write a collection of programs where data provided by a central EAR application can then be accessed both locally and remotely by a variety of clients via session facades. These clients could include

1. Other modules within the main EAR running on the same Payara instance.
2. Other WAR applications running on the same Payara instance, but not in the EAR.
3.  Applications running outside of the server e.g. via ACC or on another server

1 and 3 work fine, I can print data from the entity bean fetched via the session facade. Cool Beans!
2 exhibits very odd behavior. The session bean works fine and returns a non-null entity object. Unfortunately the object is completely empty, all fields are null. Is this a bug?

Please Help!

Test Code linked below.

## Expected Outcome

Building and running the attached app in Netbeans and navigating to:
[http://localhost:8080/MinEJBTest-extweb/EntityTestServlet](http://localhost:8080/MinEJBTest-extweb/EntityTestServlet)
Should yield:
```
Servlet EntityTestServlet at /MinEJBTest-extweb

Joe
```

## Current Outcome

```
Servlet EntityTestServlet at /MinEJBTest-extweb

null
```

## Steps to reproduce (Only for bug reports) 

1. Download and install Netbeans 11.0
2. Download, install and start MySQL 8.0.18
3. Download and extract MySQL connector/J 8.0.18
4. Download, extract and start Payara 5.193.1
5. Add connector/J to Payara:
`asadmin add-library <path-to>\mysql-connector-java-8.0.18.jar`
6. Clone the source code.
7. Run make_db.sql against MySQL.
8. Open and build MinEJBTest-entity project in NB
9. Open and build MinEJBTest-remote project in NB
10. Open and build MinEJBTest project in NB
11. Run MinEJBTest-ear project and navigate to [http://localhost:8080/MinEJBTest-web/EntityTestServlet](http://localhost:8080/MinEJBTest-web/EntityTestServlet) to confirm ear is running correctly - should be 'Joe'
12. Open build and run MinEJBTest-extweb and navigate to [http://localhost:8080/MinEJBTest-extweb/EntityTestServlet](http://localhost:8080/MinEJBTest-extweb/EntityTestServlet); look at last line of output - will be 'null'.

### Samples

[https://github.com/sgparry/MinEJB](https://github.com/sgparry/MinEJB)

## Context (Optional)

My objective here is to construct a central application serving business logic and data from a large database to a variety of separate client apps with the flexibility of them being located on the same or different servers. It should be possible to deploy the satellite apps without disturbing the central application.

## Environment ##

- **Payara Version**: 5.131.1.x
- **Edition**: Full
- **JDK Version**: Adopt OpenJDK 1.8.0_222-b10 (NB running AOJDK 11)
- **Operating System**: Windows 7
- **Database**: MySQL 8.0.16

My IDE is Netbeans 11.0 (11.1 and 11.2 EE wizards are broken). I am targeting Java 7 and Java EE 7 full profile throughout - although how I persuade Payara to honor the full profile part I am not 100% on.

**Comment by AleksNo** [comment]
Hi, maybe it is the same issue described here:
https://github.com/payara/Payara/issues/3996

If you do not use the fetchgroup-feature in Eclipselink then put:

<property name="eclipselink.weaving.fetchgroups" value="false"/>

in your persistence.xml and try again. :)

Greetings

**Comment by sgparry** [comment]
Thanks for the help @AleksNo - I will try this in the next couple of days and let you know how it goes.

**Comment by rdebusscher** [comment]
Reproducer from the Payara Forum thread https://groups.google.com/forum/#!topic/payara-forum/WJiRtzkz9Sw

[MinEJB.zip](https://github.com/payara/Payara/files/3910549/MinEJB.zip)

**Comment by sgparry** [comment]
The workaround seems to work, which suggests this is indeed related to #3996 . The use case is different so not sure if it counts as a duplicate. I have also produced a much simpler use case for reproducing the bug which I will post when I get a chance. I also believe I may have found another issue that I will post separately, that relates to how remote facades appear in JNDI, which I will post as a new issue once I have the proper shape of the problem.

**Comment by fturizo** [comment]
@sgparry, have you been able to verify if the problem is persisting on the latest release of Payara Server?

**Comment by fturizo** [comment]
@sgparry, have you been able to verify if the problem is still present in the current release? If we do not receive any updates soon, we'll proceed to close this issue then.

**Comment by fturizo** [comment]
Closing this issue as there's no response from the original user.
