### ISSUE TITLE
JAX-WS 'Test webservice' does not work /CUSTCOM-190

### ISSUE THREAD

**Issue by rlfnb** [payara/Payara#4350]
# Description #
----------

## Expected Outcome

http://localhost:8080/StupidWebService/StupidWebService?Tester
should show a page allowing me to call the web service

## Current Outcome

> Error generating artifacts for the following WSDL http://localhost:8080/StupidWebService/StupidWebService?WSDL
> 
> Possible causes can be invoking https when the application is not configured for security
> 

The root cause might be:

>   Payara Server  5.193.1 #badassfish (275) startup time : Felix (1,987ms), startup services(7,015ms), total(9,002ms)|#]
>   Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=LogNotifierConfigurationExecutionOptions{useSeparateLogFile=false} NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true, noisy=true}}}|#]
>   Network Listener JMS_PROXY_default_JMS_host started in: 6ms - bound to [/0.0.0.0:7676]|#]
>   Skipping registration of inhabitant for service reference [org.osgi.service.metatype.MetaTypeProvider] as the service object could not be obtained.|#]
>   JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi|#]
>   Loading application __admingui done in 617 ms|#]
>   Initializing Mojarra 2.3.9.payara-p3 for context ''|#]
>   Loading application [__admingui] at [/]|#]
>   Context path from ServletContext:  differs from path from bundle: /|#]
>   Invoking wsimport with http://localhost:8080/StupidWebService/StupidWebService?WSDL|#]
>   parsing WSDL...
> |#]
>   
> Generating code...
> |#]
>   
> Compiling code...
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:4: error: package javax.jws does not exist
> |#]
>   import javax.jws.WebMethod;
> |#]
>                   ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:5: error: package javax.jws does not exist
> |#]
>   import javax.jws.WebParam;
> |#]
>                   ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:6: error: package javax.jws does not exist
> |#]
>   import javax.jws.WebResult;
> |#]
>                   ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:7: error: package javax.jws does not exist
> |#]
>   import javax.jws.WebService;
> |#]
>                   ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:9: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.RequestWrapper;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:10: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.ResponseWrapper;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:19: error: cannot find symbol
> |#]
>   @WebService(name = "StupidWebService", targetNamespace = "http://jaxrspoc.mycompany.com/")
> |#]
>    ^
> |#]
>     symbol: class WebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:7: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.Service;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:8: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.WebEndpoint;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:9: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.WebServiceClient;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:10: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.WebServiceException;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:11: error: package javax.xml.ws does not exist
> |#]
>   import javax.xml.ws.WebServiceFeature;
> |#]
>                      ^
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:22: error: cannot find symbol
> |#]
>       extends Service
> |#]
>               ^
> |#]
>     symbol: class Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:20: error: cannot find symbol
> |#]
>   @WebServiceClient(name = "StupidWebService", targetNamespace = "http://jaxrspoc.mycompany.com/", wsdlLocation = "http://localhost:8080/StupidWebService/StupidWebService?WSDL")
> |#]
>    ^
> |#]
>     symbol: class WebServiceClient
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:26: error: cannot find symbol
> |#]
>       private final static WebServiceException STUPIDWEBSERVICE_EXCEPTION;
> |#]
>                            ^
> |#]
>     symbol:   class WebServiceException
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:67: error: cannot find symbol
> |#]
>       public StupidWebService getStupidWebServicePort(WebServiceFeature... features) {
> |#]
>                                                       ^
> |#]
>     symbol:   class WebServiceFeature
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:37: error: cannot find symbol
> |#]
>           @WebParam(name = "name", targetNamespace = "")
> |#]
>            ^
> |#]
>     symbol:   class WebParam
> |#]
>     location: interface StupidWebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:32: error: cannot find symbol
> |#]
>       @WebMethod
> |#]
>        ^
> |#]
>     symbol:   class WebMethod
> |#]
>     location: interface StupidWebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:33: error: cannot find symbol
> |#]
>       @WebResult(targetNamespace = "")
> |#]
>        ^
> |#]
>     symbol:   class WebResult
> |#]
>     location: interface StupidWebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:34: error: cannot find symbol
> |#]
>       @RequestWrapper(localName = "hello", targetNamespace = "http://jaxrspoc.mycompany.com/", className = "com.mycompany.jaxrspoc.Hello")
> |#]
>        ^
> |#]
>     symbol:   class RequestWrapper
> |#]
>     location: interface StupidWebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService.java:35: error: cannot find symbol
> |#]
>       @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://jaxrspoc.mycompany.com/", className = "com.mycompany.jaxrspoc.HelloResponse")
> |#]
>        ^
> |#]
>     symbol:   class ResponseWrapper
> |#]
>     location: interface StupidWebService
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:54: error: cannot find symbol
> |#]
>       @WebEndpoint(name = "StupidWebServicePort")
> |#]
>        ^
> |#]
>     symbol:   class WebEndpoint
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:66: error: cannot find symbol
> |#]
>       @WebEndpoint(name = "StupidWebServicePort")
> |#]
>        ^
> |#]
>     symbol:   class WebEndpoint
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:31: error: cannot find symbol
> |#]
>           WebServiceException e = null;
> |#]
>           ^
> |#]
>     symbol:   class WebServiceException
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:35: error: cannot find symbol
> |#]
>               e = new WebServiceException(ex);
> |#]
>                       ^
> |#]
>     symbol:   class WebServiceException
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:56: error: cannot find symbol
> |#]
>           return super.getPort(new QName("http://jaxrspoc.mycompany.com/", "StupidWebServicePort"), StupidWebService.class);
> |#]
>                  ^
> |#]
>     symbol:   variable super
> |#]
>     location: class StupidWebService_Service
> |#]
>   /tmp/jax-ws14817042957282565111tester/com/mycompany/jaxrspoc/StupidWebService_Service.java:68: error: cannot find symbol
> |#]
>           return super.getPort(new QName("http://jaxrspoc.mycompany.com/", "StupidWebServicePort"), StupidWebService.class, features);
> |#]
>                  ^
> |#]
>     symbol:   variable super
> |#]
>     location: class StupidWebService_Service
> |#]
>   27 errors
> |#]
>   compilation failed, errors should have been reported|#]
>   wsimport failed|#]
> 

### Samples

https://github.com/rlfnb/JaxWSPoC produces the WAR to reproduce the behavior above

## Environment ##

- **Payara Version**: 193.1
- **Edition**: Full
- **JDK Version**: OpenJDK11
- **Operating System**: Linux
- **Database**: not relevant

**Comment by fturizo** [comment]
Thank you for reporting this issue @rlfnb. It seems that the SOAP Web service tester endpoint is not working correctly when using JDK 11. I have escalated this issue to our engineering team with the internal ID `CUSTCOM-190`, so you can expect a solution in a future release.

**Comment by kovica** [comment]
I'm running Payara Full 5.194 on Ubuntu 18.04 with java:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

and get the same error. I've been trying to use Payara with Java 11 in production, but because of this had to go down to Java 1.8.
