### ISSUE TITLE
CUSTCOM-200 Unused timer var in HazelcastTimerStore.cancelTimersByKey

### ISSUE THREAD

**Issue by pzygielo** [payara/Payara#4356]
# Description #
----------
I have an issue with understanding 
https://github.com/payara/Payara/blob/c4f9338fed0a627999e3285760e12420605de73d/appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java#L267-L288
especially usage of `timers` and `timer` loop variable in https://github.com/payara/Payara/blob/c4f9338fed0a627999e3285760e12420605de73d/appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java#L277-L282

## Expected Outcome
`timer` is used in loop body

## Current Outcome
`timers` is used to get timer by the same `primaryKey` for `timers.size()` times from `pkCache` (`Map`). So I see it as it's getting the same `hzTimer` over and over.
As it is then placed (possibly, if `hzTimer.getTimedObjectPk().equals(primaryKey)` is satisfied which I do not know yet) in `timersToCancel` (`Set`) - then I think 
https://github.com/payara/Payara/blob/c4f9338fed0a627999e3285760e12420605de73d/appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java#L285 removes one timer only.

If it's all as it should be I will be fine with no detailed explanation.

**Comment by fturizo** [comment]
@pzygielo, since this issue is not a proper bug report, we'll proceed to close this issue. Feel free to raise a PR with the code changes you consider necessary. That way you can request direct assistance on how to correctly modify the code to suit your needs.

**Comment by pzygielo** [comment]
> Feel free to raise a PR with the code changes you consider necessary.

? Already there. Linked above your comment with green "open" button.

**Comment by fturizo** [comment]
My bad, I missed it. Many thanks for your contribution!
