### ISSUE TITLE
Getting 401 unauthorization error Jwt token is not generating its directly rendering into Authentication Entry point and displaying the message

### ISSUE THREAD

**Issue by syedwaseem68** [payara/Payara#4359]
Getting 401 unauthorization error Jwt token is not generating its directly rendering into Authentication Entry point and displaying the message. after login with UsernameOrMobilenumber it should generate the jwt token 

@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(
        securedEnabled = true,
        jsr250Enabled = true,
        prePostEnabled = true
)
public class SecurityConfig extends WebSecurityConfigurerAdapter {

            private  CustomUserDetailsService customUserDetailsService;

            @Autowired
            private JwtAuthenticationEntryPoint unauthorizedHandler;

    //  @Bean
            public JwtAuthenticationFilter jwtAuthenticationFilter(){
                return new JwtAuthenticationFilter();
            }

            @Bean
            @Override
            public AuthenticationManager authenticationManagerBean() throws Exception {
                return super.authenticationManagerBean();
            }
            public BCryptPasswordEncoder passwordEncoder(){
                return new BCryptPasswordEncoder();
            }

            @Override
            @Autowired
            public void configure(AuthenticationManagerBuilder authenticationManagerBuilder) throws Exception {

                authenticationManagerBuilder.
                        userDetailsService(userDetailsServiceBean())
                        //  userDetailsService(customUserDetails)
                        .passwordEncoder(passwordEncoder());
            }

            @Autowired
            public CustomUserDetailsService userDetailsServiceBean() throws  Exception{
                return  new CustomUserDetailsService();
            }

            @Override
            protected void configure(HttpSecurity http) throws Exception {
                System.out.println("inside the security config");
                http
                        .cors().and().csrf().disable()
                        .exceptionHandling().authenticationEntryPoint(unauthorizedHandler)
                        .and()
                        .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                        .and()
                        .authorizeRequests()
                        .antMatchers("*/auth/**").permitAll()
                        .antMatchers(HttpMethod.POST,"/auth/*").permitAll()
                        .antMatchers(HttpMethod.OPTIONS).permitAll()
                        .anyRequest()
                        .authenticated();
                System.out.println("outside the security config");
                http
                        .addFilterBefore(jwtAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class);

            }

}

----------------
  @PostMapping("/signin")
           @ApiOperation(value = "Logs the user in to the system and return the auth tokens")
            public ResponseEntity<?> authenticateUser(@ApiParam(value="The LoginRequest payload")
                                                                 @Valid @RequestBody LoginRequest loginRequest, HttpServletRequest request){

               System.out.println("Inside the Sign in");
               try {
                   Authentication authentication = authService.authenticateUser(loginRequest)
                           .orElseThrow(() -> new UserLoginException("Could't login user [" + loginRequest + "]"));

                CustomUserDetails customUserDetails= (CustomUserDetails) authentication.getPrincipal();
               logger.info("Logged in User returned [API]: " + customUserDetails.getMobileNo());

               SecurityContextHolder.getContext().setAuthentication(authentication);
               String jwt=jwtTokenProvider.generateToken((CustomUserDetails)authentication);

               if (jwt!=null && session==null){
                   session=request.getSession(true);
                   System.out.println(session);
                   session.setAttribute("tokenadded",jwt);
                   String tokenrecived= (String) session.getAttribute("tokenadded");
                   System.out.println(tokenrecived);
               }
               return ResponseEntity.ok(new JwtAuthenticationResponse(jwt));
               }catch (AuthenticationException e){
                   throw new BadCredentialsException("Invalid Mobilenumber / Username supplied");
               }

           }
-------------------
@Service
public class AuthService {

    private static final Logger logger = LoggerFactory.getLogger(AuthService.class);

        private final JwtTokenProvider jwtTokenProvider;
        private final UserService userService;
        private final AuthenticationManager authenticationManager;

    @Autowired
    public AuthService(JwtTokenProvider jwtTokenProvider, UserService userService,AuthenticationManager authenticationManager) {
        this.jwtTokenProvider=jwtTokenProvider;
        this.userService=userService;
        this.authenticationManager=authenticationManager;
    }

        public Boolean mobileAlreadyExists(String mobilenumber){
            return  userService.exitsByMobilenumber(mobilenumber);
        }
        public Boolean usernmaeAlreadyExists(String username){
            return  userService.exitsByUsername(username);
        }

        public Optional<Authentication> authenticateUser(LoginRequest loginRequest) {
            return Optional.ofNullable(authenticationManager.authenticate
                    (new UsernamePasswordAuthenticationToken(loginRequest.getMobileNumberOrUserName(),
                    loginRequest.getPassword())));
        }
        public String generateToken(CustomUserDetails customUserDetails) {
            return jwtTokenProvider.generateToken(customUserDetails);
        }
-------------------------------------------------------------
public class JwtAuthenticationFilter extends OncePerRequestFilter {

        private static final Logger logger= LoggerFactory.getLogger(JwtAuthenticationFilter.class);

        @Value("${app.jwt.header}")
        private String tokenRequestHeader;
        @Value("${app.jwt.header.prefix}")
        private String tokenRequestHeaderPrefix;

        @Autowired
        private JwtTokenProvider jwtTokenProvider;
        @Autowired
        private CustomUserDetailsService customerUserDetails;

        @Override
        protected void doFilterInternal(HttpServletRequest request,
                                        HttpServletResponse response,
                                        FilterChain filterChain) throws ServletException, IOException {

                try {
                        String jwt = getJwtFromRequest(request);

                        if (StringUtils.hasText(jwt) && jwtTokenProvider.validateToken(jwt)) {
                                String usermobile = jwtTokenProvider.getMobilenumberFromJWT(jwt);
                                UserDetails userDetails = customerUserDetails.loadUserByMobilenumber(usermobile);
                                UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken
                                        (userDetails, null, userDetails.getAuthorities());
                                authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                                SecurityContextHolder.getContext().setAuthentication(authentication);
                        }
                } catch (Exception ex) {
                        logger.error("Could not set user authentication in security context" + ex);
                }
                filterChain.doFilter(request, response);
        }
        private String getJwtFromRequest(HttpServletRequest httpServletRequest) {
                String bearerToken = httpServletRequest.getHeader("Authorization");
                if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer")) {
                        logger.info("Extracted Token: " + bearerToken);
                        return bearerToken.replace(tokenRequestHeaderPrefix,"");
                        //substring(7, bearerToken.length());
                }
                return null;
        }
-----------------------------------------------------------
@Component
public class JwtTokenProvider {

            private static final Logger logger = LoggerFactory.getLogger(JwtTokenProvider.class);

            @Value("${app.jwt.secret}")
            private String jwtSecret;

            @Value("${app.jwt.expiration}")
            private Long jwtExpirationInMs;

            @Value("${app.jwt.claims.refresh.name}")
            private String jwtClaimRefreshName;

            /**
             * Generates a token from a CustomUserDetails object. Embed the refresh token in the jwt
             * so that a new jwt can be created
             * @param CustomUserDetails
             */
            public String generateToken(CustomUserDetails CustomUserDetails) {

                Instant expiryDate = Instant.now().plusMillis(jwtExpirationInMs);

                return Jwts.builder()
                        .setSubject(CustomUserDetails.getMobileNo())
                        //(Long.toString(userPrincipal.getMobileNumber()))
                        .setIssuedAt(Date.from(Instant.now()))
                        .setExpiration(Date.from(expiryDate))
                        .signWith(SignatureAlgorithm.HS512, jwtSecret)
                        .compact();
            }
            /**
             * Generates a token from a CustomUserDetails object. Embed the refresh token in the jwt
             * so that a new jwt can be created
             */
            public String generateTokenFromMobilenumber(String mobilenumber) {
                Instant expiryDate = Instant.now().plusMillis(jwtExpirationInMs);
                return Jwts.builder()
                        .setSubject(mobilenumber)
                        .setIssuedAt(Date.from(Instant.now()))
                        .setExpiration(Date.from(expiryDate))
                        .signWith(SignatureAlgorithm.HS512, jwtSecret)
                        .compact();
            }
            /**
             * Returns the user id encapsulated within the token
             */
            // public Long getUserIdFromToken(String token){
            public String getMobilenumberFromJWT(String token) {
                Claims claims = Jwts.parser()
                        .setSigningKey(jwtSecret)
                        .parseClaimsJws(token)
                        .getBody();
                return String.valueOf(claims.getSubject());
                //parseLong(claims.getSubject());
            }
            /**
             * Validates if a token has the correct unmalformed signature and is not expired or unsupported.
             */
            public Boolean validateToken(String authToken) {
                try {
                    Jwts.parser().setSigningKey(jwtSecret).parseClaimsJws(authToken);
                    return true;
                } catch (SignatureException ex) {
                    logger.error("Invalid JWT Signature");
                } catch (MalformedJwtException ex) {
                    logger.error("Invalid JWT Token");
                } catch (ExpiredJwtException ex) {
                    logger.error("Expired JWT Token");
                } catch (UnsupportedJwtException ex) {
                    logger.error("Unsupported JWT Token");
                } catch (IllegalArgumentException ex) {
                    logger.error("JWT Claims String is Empty");
                }
                return false;
            }

            public Long getExpiryDuration() {
                return jwtExpirationInMs;
            }
}
-------------------------------------------------------------------
@Component
public class JwtAuthenticationEntryPoint implements AuthenticationEntryPoint {

    private static final Logger logger= LoggerFactory.getLogger(JwtAuthenticationEntryPoint.class);

            @Override
            public void commence(HttpServletRequest request,
                                 HttpServletResponse response,
                                 AuthenticationException authException) throws IOException, ServletException {

                logger.error("Responding with Unauthorized error.Message - {}" , authException.getMessage());
                response.sendError(HttpServletResponse.SC_UNAUTHORIZED,authException.getMessage());
            }
}

**Comment by rdebusscher** [comment]
Hi,

Can you indicate how the JWT token and Spring Framework interact with Payara in this. It is not clear what Payara code roles is in the 401 status code.

Regards
Rudy

**Comment by syedwaseem68** [comment]
Actually am working on creating jwt token for auth service using Mobilenumber Or Username and password, while hitting the login api am getting the bad credential error even though am passing the correct mobile number and password. After debugging i found this error "org.springframework.security.authentication.BadCredentialsException: Bad credentials" 
Note : Am not using any role to implemented the granted authority.

**Comment by rdebusscher** [comment]
Hi,

How is the login api protected, is it defined as JAX-RS service or is it defined within Spring? What framework is replying with the status 401?

According to the message, it looks like a misconfiguration in the  keys, issue in the signing, etc ... and the issue lies in the application code.

Regards
Rudy

**Comment by rdebusscher** [comment]
Any information on this?

**Comment by syedwaseem68** [comment]
Hi,

The issue is not resolved,

The issue was my jwt token not filter for unauthorised request.

Thanks & Regards,
Syed Waseem
9731062959

**Comment by syedwaseem68** [comment]
Sorry,

The issue is resolved**

Thanks & Regards,
Syed Waseem
9731062959

**Comment by syedwaseem68** [comment]
Thank you!

Thanks & Regards,
Syed Waseem
9731062959

**Comment by abinashgithub99** [comment]
how did you resolve this issue ?
can you please address the solution.

**Comment by Hari635** [comment]
please address the solution 
I too have the same issues
