### ISSUE TITLE
Payara-Web 5.194 Production domain.xml is Invalid

### ISSUE THREAD

**Issue by mzaum** [payara/Payara#4366]
# Description #
----------
The bundled domain.xml for the "production" domain with Payara-Web 5.194 is invalid XML.

File: /payara5/glassfish/domains/production/config/domain.xml
Line: 408 Missing closing `>`

`<jvm-options>[9|]--add-opens=java.base/java.util=ALL-UNNAMED</jvm-options`

## Expected Outcome

Has closing `>`.  Domain successfully starts.

## Current Outcome

Missing closing `>`.  Domain fails to start.

## Steps to reproduce (Only for bug reports) 

None needed.  Default packaged zip file contains the invalid domain.xml.

### Samples

N/A

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Web
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: N/A

**Comment by smillidge** [comment]
You are right. Not sure how that slipped through!

**Comment by dmatej** [comment]
Made in commit 5a77ae12edcb1419a8c68a67d6b3d979860023cc

**Comment by dmatej** [comment]
Created internal issue CUSTCOM-57
