### ISSUE TITLE
Improper thread usage

### ISSUE THREAD

**Issue by matheusdallrosa** [payara/Payara#4367]
I am making some experiments with the CompletableFuture  class and the AsyncContext on payara server. This is the code i'm currently using:

```
package learn;

import java.io.IOException;
import java.util.concurrent.CompletableFuture;

import javax.servlet.AsyncContext;
import javax.servlet.ReadListener;
import javax.servlet.ServletException;
import javax.servlet.ServletInputStream;
import javax.servlet.ServletOutputStream;
import javax.servlet.WriteListener;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = {"/async"}, asyncSupported = true)
public class AsyncProcessing extends HttpServlet {

	private static final long serialVersionUID = -535924906221872329L;
	
	public CompletableFuture<String> readRequestAsync(final HttpServletRequest req) {		
		
		final CompletableFuture<String> request = new CompletableFuture<>();
		final StringBuilder httpRequestData = new StringBuilder();
		try (ServletInputStream inputStream = req.getInputStream()){						
			inputStream.setReadListener(new ReadListener() {
				final int BUFFER_SIZE = 4*1024;
				final byte buffer[] = new byte[BUFFER_SIZE];
				
				@Override
				public void onError(Throwable t) {
					request.completeExceptionally(t);
				}
				
				@Override
				public void onDataAvailable() {
					System.out.println("----------------------------------------");
					System.out.println("onDataAvailable: " + Thread.currentThread().getName());
					try {
						while(inputStream.isReady()) {
		                  int length = inputStream.read(buffer);	                  
		                  httpRequestData.append(new String(buffer, 0, length));
		               }
		            } catch (IOException ex) { 
		            	request.completeExceptionally(ex);
		            }
				}
				
				@Override
				public void onAllDataRead() throws IOException {								
					request.complete(httpRequestData.toString());
				}
			});
		} catch (IOException e) {
			request.completeExceptionally(e);
		}						 		
		
		return request;
	}
	
	public CompletableFuture<String>  process(String httpRequest){		
		System.out.println("----------------------------------------");
		System.out.println("process: " + Thread.currentThread());
		
		try {
			Thread.sleep(30 * 1000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return CompletableFuture.completedFuture("hi");
	}
	
	public CompletableFuture<Integer> outputResponseAsync(String httpResponseData, HttpServletResponse resp){
		System.out.println("----------------------------------------");
		System.out.println("outputResponseAsync: " + Thread.currentThread().getName());
		
		CompletableFuture<Integer> total = new CompletableFuture<>();
		try (ServletOutputStream outputStream = resp.getOutputStream()){			
			outputStream.setWriteListener(new WriteListener() {
				final int BUFFER_SIZE = 4*1024;
				int alreadyWritten = 0;
				
				@Override
				public void onWritePossible() throws IOException {
					System.out.println("----------------------------------------");
					System.out.println("onWritePossible: " + Thread.currentThread().getName());
	               while(alreadyWritten < httpResponseData.length() && outputStream.isReady()) {		            		  		            		 	            		
					  final int lenghtToBeWritten = Math.min(
						BUFFER_SIZE, 
					  	httpResponseData.length()-alreadyWritten
					  );						 		            	  	            	 		            	 		            	
	            	  
	            	  outputStream.print(httpResponseData.substring(alreadyWritten, alreadyWritten+lenghtToBeWritten));
	            	  
	            	  alreadyWritten += lenghtToBeWritten;		            	  		            	 
	               }
	               if(alreadyWritten >= httpResponseData.length()) {
	            	   total.complete(alreadyWritten);
	               }
				}
				
				@Override
				public void onError(Throwable t) {
					total.completeExceptionally(t);
				}
			});
		} catch (IOException e) {
			total.completeExceptionally(e);
		}
		
		return total;
	}
		
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		System.out.println("----------------------------------------");
		System.out.println("doGet: " + Thread.currentThread().getName());
		final AsyncContext asyncContext = req.startAsync();
		readRequestAsync(req)
			.thenCompose(this::process)
			.thenCompose(httpResponseData -> outputResponseAsync(httpResponseData, resp))		
			.thenAccept(a -> asyncContext.complete());
	}
}

```
I'm running this code with the default configuration of the payara server 5.194, but i have changed only the thread-pool-1 to have Max Thread Pool Size = Min Thread Pool Size = 0 and changed 
http-thread-pool to have Max Thread Pool Size = Min Thread Pool Size = 1. So, with this configuration all of the thenCompose should use the same thread, because there is only one, and the thread should be blocked when i use Thread.sleep, therefore the following should be logged:

## Expected Outcome
2019-12-04T23:09:31.680-0300|INFO: doGet: http-thread-pool::http-listener-1
2019-12-04T23:09:31.736-0300|INFO: ----------------------------------------
2019-12-04T23:09:31.737-0300|INFO: process: http-thread-pool::http-listener-1

## Current Outcome
2019-12-04T23:09:31.680-0300|INFO: doGet: http-thread-pool::http-listener-1
2019-12-04T23:09:31.736-0300|INFO: ----------------------------------------
2019-12-04T23:09:31.737-0300|INFO: process: glassfish-web-async-thread-1

Where the thread glassfish-web-async-thread-1 is from? 

If i wait for the current request to finish and make it again i receive this other output:
2019-12-04T23:09:31.680-0300|INFO: doGet: http-thread-pool::http-listener-1
2019-12-04T23:09:31.736-0300|INFO: ----------------------------------------
2019-12-04T23:09:31.737-0300|INFO: process: glassfish-web-async-thread-1

If necessary i can upload the project to github, but as you can see the code is very simple, and i'm using the following environment:

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: 11 - Oracle. For the project and for the payara server.
- **Operating System**: Linux 
- **Database**: I'm not using a database.

**Comment by lprimak** [comment]
I believe this is all correct. ```req.startAsync()``` will start a new thread for processing async request, which is... async!

Never used async servlets before but what you are seeing makes sense.

**Comment by matheusdallrosa** [comment]
My point is that there is only one thread on the http-thread-pool, but the process method is logging:

```
2019-12-04T23:09:31.680-0300|INFO: doGet: http-thread-pool::http-listener-1
2019-12-04T23:09:31.736-0300|INFO: ----------------------------------------
2019-12-04T23:09:31.737-0300|INFO: process: glassfish-web-async-thread-1
```

Where does glassfish-web-async-thread-1 come from? 

I have checked [https://jakarta.ee/specifications/platform/8/apidocs/index.html?javax/servlet/http/HttpServletRequest.html](url) and there is nothing about creating new threads. Actually, i was thinking that the thenCompose would use the jvm common pool instead of the payara threads.

**Comment by matheusdallrosa** [comment]
And there is also another thing. If i wait for the request to finish and make another request i get the following:
`
2019-12-05T21:45:03.866-0300|INFO: doGet: http-thread-pool::http-listener-1(1)
2019-12-05T21:45:03.872-0300|INFO: ----------------------------------------
2019-12-05T21:45:03.873-0300|INFO: process: glassfish-web-async-thread-2
`
If i make it again:
`
2019-12-05T21:45:03.866-0300|INFO: doGet: http-thread-pool::http-listener-1(1)
2019-12-05T21:45:03.872-0300|INFO: ----------------------------------------
2019-12-05T21:45:03.873-0300|INFO: process: glassfish-web-async-thread-3
`
Notice that the number at the suffix of the glassfish web async thread is increasing, i have done it like 10 times and it made to glassfish-web-async-thread-10. As the name of the thread is changing i'm wondering if a new thread is being created. I would like to someone explain what is going on? : )

**Comment by chrjohn** [comment]
> The blocking operation completes in the asynchronous execution context in a different thread, which can generate a response or dispatch the request to another servlet.

From https://docs.oracle.com/javaee/7/tutorial/servlets012.htm

OK, this is JavaEE but I think it is still valid. How do you expect async work to be done if you do not spawn a new thread? ;)

**Comment by matheusdallrosa** [comment]
This is something i would like to know @chrjohn . How the payara server behaves in such situation when i'm trying to do async processing and there is no other thread. From my experiments i can say that it will create a new thread on every request, i then i would like to know if this is the real behaviour that payara server should have.

**Comment by smillidge** [comment]
Can you move this to the forum please? Github is a development tool so questions and clarifications are best on the forum while bug reports should be raised as Github issues.

**Comment by matheusdallrosa** [comment]
I didn't know there is a forum. Thank you.
