### ISSUE TITLE
Documentation for 5.194 does not list JDK 11 as supported /CUSTCOM-72

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#4370]
# Description #
----------

see title

## Expected Outcome

Documentation lists JDK 11 as supported platform

## Current Outcome

Missing JDK 11 as supported platform

## Steps to reproduce (Only for bug reports) 

https://docs.payara.fish/general-info/supported-platforms.html

**Comment by smillidge** [comment]
Yeah that is wrong and needs updating

**Comment by dmatej** [comment]
Created internal issue CUSTCOM-72
