### ISSUE TITLE
Question regarding microprofile-context-propagation

### ISSUE THREAD

**Issue by HMMurdock** [payara/Payara#4371]
# Description #
----------

Do payara/micro  support the microprofile-context-propagation api ?
https://github.com/eclipse/microprofile-context-propagation

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by svendiedrichsen** [comment]
Those kind of questions are best posted here first: https://groups.google.com/forum/#!forum/payara-forum

**Comment by smillidge** [comment]
Moved to forum
