### ISSUE TITLE
start-domain --debug=true does not display port number

### ISSUE THREAD

**Issue by pzygielo** [payara/Payara#4386]
`start-domain --debug=true` does not display port number

---

## Expected Outcome

As described in https://github.com/payara/Payara/blob/c2905122f21f49ed1455612bdc3aded5b1d1f2ce/nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/start-domain.1#L68-L70
I expect `asadmin start-domain --debug=true` to display port number used, i.e.:
```
Waiting for domain1 to start ............
Successfully started the domain : domain1
domain  Location: /tmp/payara5/glassfish/domains/domain1
Log File: /tmp/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Debugging is enabled.  The debugging port is: 9009
Command start-domain executed successfully.
```

## Current Outcome

```
Waiting for domain1 to start ..............
Successfully started the domain : domain1
domain  Location: /tmp/payara5/glassfish/domains/domain1
Log File: /tmp/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
```
with no info on debug port used. To discover port used one has to for example inspect `server.log` or `domain.xml`.

## Steps to reproduce

1. Start the domain (`asadmin start-domain --debug=true`)
1. Observe console output

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_232-b09)
- **Operating System**: Linux
- **Database**: n/a

**Comment by dmatej** [comment]
Created internal issue CUSTCOM-81

**Comment by garbi** [comment]
This issue is still opened, right? I am using Payara 6.2 and there is still no indication that the server was started in debug mode, nor any indication of the actual JPDA port being used.

**Comment by pzygielo** [comment]
This issue is closed as indicated by its Status: Closed.

It works in version fixed by linked PR - 5.201/set as milestone, and also in the latest 5.x: 5.2022.5. All with JDK8.

**The first 6 - 6.2021.1.Alpha1, also works when used with JDK 8 but not with JDK 11.**

The next 6.2022.1.Alpha2 requires Java 11 (and does not display port used by debugger).

**Comment by pzygielo** [comment]
With Java newer than 8, the option line is built as `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9009`, with port (9009) prefixed with host (`*:` here). This results again in port being discovered as -1 as code is not prepared for that part to be there. So this RE
https://github.com/payara/Payara/blob/26c504bb440432cfaa40e425730650945a23c823/nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java#L386 needs to be adjusted (and perhaps the comment in https://github.com/payara/Payara/blob/26c504bb440432cfaa40e425730650945a23c823/nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java#L371 updated).

**Comment by pzygielo** [comment]
- https://github.com/payara/Payara/pull/4633
