### ISSUE TITLE
Allow MDB to specify the resource adapter to use in the Activation Config

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#440]
Currently in Payara and GlassFish if an MDB wants to use a specific resource adapter it has to be specified in the glassfish-ejb.xml.

Add an ActivationConfigProperty to specify the resource adapter to use.

For example
```java
@MessageDriven(name = "testmdb", activationConfig = {
    @ActivationConfigProperty(propertyName = "destinationLookup", propertyValue = "jms/queue/MY.MAGIC.OUT"),
    @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue"),
    @ActivationConfigProperty(propertyName = "destination", propertyValue = "MY.MAGIC.OUT"),
    @ActivationConfigProperty(propertyName = "resourceAdapter", propertyValue = "activemq-rar-5.12.0")
    
})
```

**Comment by adrianofsp** [comment]
Hi.
Do you know how to increase the number of MDB sessions for consumers?
I need to increase de number of consumers, but I'm using de activemq as ResourceAdapter and I have only one consumer.

I tried maxSessions but is not allowed with activemq only with HornetMQ
Thanks.
Best Regards.

**Comment by smillidge** [comment]
You can add a deployment descriptor like below to your deployment to specify MDB pool size;
```xml
<glassfish-ejb-jar>
    <enterprise-beans>
        <ejb>
            <ejb-name>BeanName</ejb-name>
            <bean-pool>
                <steady-pool-size>6</steady-pool-size>
                <resize-quantity>1</resize-quantity>
                <max-pool-size>6</max-pool-size>
            </bean-pool>
        </ejb>
    </enterprise-beans>
</glassfish-ejb-jar>
```

**Comment by adrianofsp** [comment]
Unfortunately I'm using jboss eap 6.2
I'll check the jboss docs.
Thanks!
Em 1 de fev de 2016 7:43 PM, "Steve Millidge" <notifications@github.com>
escreveu:
