### ISSUE TITLE
eclipse plugin is not working with Payara 5.194.

### ISSUE THREAD

**Issue by Mehdi-HAFID** [payara/Payara#4406]
Hi,

Your eclipse plugin is not working with Payara 5.194.

When I try to start Payara with Eclipse 2019-09 it prints this error:
"Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'UseOpenJSSE'"
I have to start Payara from the command line.

Can you fix it please.

Regards.

## Environment ##

- **Payara Version**: 5.194 
- **Edition**: Full
- **JDK Version**: <!-- Oracle 8
- **Operating System**: Windows

**Comment by rdebusscher** [comment]
Hi @Mehdi-HAFID,

Can you please update to the latest version of the plugin, version 1.0.1?

Regards
Rudy.

**Comment by Mehdi-HAFID** [comment]
Yes that fix it. Thanks.
