### ISSUE TITLE
Injection doesn't work in exploded skinny EAR

### ISSUE THREAD

**Issue by JarekW** [payara/Payara#4410]
# Description #
----------

My application is packaged in EAR file. It has jar and war module inside it. It is in exploded format for development. I've set also the "skinnyWars" option. With this setup I can instantiate beans from jar inside war module, but not inject them.

It doesn't work when packaged like that:
```
module-ear/target/
├── example-ear/
│   ├── com.example-module-jar-1.0-SNAPSHOT.jar/
│   ├── com.example-module-web-1.0-SNAPSHOT.war/
```

Setup works when `<defaultLibBundleDir>lib</defaultLibBundleDir>` is added to maven-ear-plugin configuration. Then application is packaged like that:
```
module-ear/target/
├── example-ear/
│   ├── com.example-module-web-1.0-SNAPSHOT.war/
│   └── lib/
        └── com.example-module-jar-1.0-SNAPSHOT.jar/
```

I think this should work with the first setup, because classes from jar module are available to war module. I can instantiate them manually, but injection doesn't work. Injection does work in second setup though. Both setups works in Wildfly server.

## Expected Outcome

Injection from jar module in exploded application works when jar module is at the root of archive. 

## Current Outcome

Application cannot be deployed. There is an error:

```
Artifact module-ear:ear exploded: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type ExampleService with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.example.rest.Endpoint.exampleService
  at com.example.rest.Endpoint.exampleService(Endpoint.java:0)
 -- WELD-001408: Unsatisfied dependencies for type ExampleService with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.example.rest.Endpoint.exampleService
  at com.example.rest.Endpoint.exampleService(Endpoint.java:0)
. Please see server.log for more details.
```

## Steps to reproduce (Only for bug reports) 

1. Clone sample, minimal repository: https://bitbucket.org/JarekW/payara-exploded-inject-error/src/master/
2. mvn clean package
3. deploy exploded repository to payara

## Environment ##

- **Payara Version**: Payara Server 5.194
- **Edition**: Full
- **JDK Version**: 11 Oracle
- **Operating System**: Linux

**Comment by rdebusscher** [comment]
Hi @JarekW 

The default value for `<library-directory>` of application.xml is `lib` within Payara.

However, the Maven ear plugin unpacks the jar within the root of the EAR but doesn't set the `<library-directory>` in the generated application.xml file.

Hence there is a mismatch in locations and EAR doesn't deploy.

By setting
`<defaultLibBundleDir>/</defaultLibBundleDir>`
in the ear plugin configuration, the issue is fixed.

regards
Rudy

**Comment by JarekW** [comment]
Thank you for explaining
