### ISSUE TITLE
Authenticate /metrics endpoint

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4412]
# Description #
----------

How to add authentication to the `/metrics` endpoint?

**Comment by jGauravGupta** [comment]
Hi @ThomasSousa96,

You may enable the security of `/metrics` endpoint by invoking the following asadmin command:

`asadmin set-metrics-configuration --securityenabled=true --roles=sampleroles`

By default, Metrics endpoint binds to root context application which uses the default realm (`file`) of the server.

So by invoking the above command and adding the user credentials with the given group names to the `file` realm, authentication can be added to `/metrics` endpoint.

For more details: https://docs.payara.fish/documentation/microprofile/metrics.html

**Comment by ThomasSousa96** [comment]
Thanks you @jGauravGupta for help!

But how to create a user with username, password and roles?

The file that you say is the `config/keyfile` file? What the format?

How to make it for the `/health` and `/openapi` endpoints?

**Comment by smillidge** [comment]
@ThomasSousa96 these sort of questions should be moved to the Payara forum https://groups.google.com/forum/?nomobile=true#!forum/payara-forum as we like to keep this as an issue tracker
