### ISSUE TITLE
Unrecognized VM option 'UseOpenJSSE'

### ISSUE THREAD

**Issue by NagnathMasali** [payara/Payara#4417]
I am trying to deploy a war file on Payara 5 in Netbeans 8.2. 
The server doesn't start and displays the following error:

`Error: Could not create the Java Virtual Machine.`
`Error: A fatal exception has occurred. Program will exit.`
`Unrecognized VM option 'UseOpenJSSE'`

It always occurs when I create a new domain and try running it.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Windows
- **Database**: Oracle

**Comment by chrjohn** [comment]
See https://github.com/payara/Payara/issues/4407#issuecomment-571063823 for workaround.

**Comment by luis-caamano** [comment]
Solution to Payara 5.184 / Netbeans 8.2 / Java 8 Not launching Payara:

in file: 
<Install>\payara5\glassfish\domains\domain1\config\domain.xml

Search for the unrecognized option **UseOpenJSSE** and comment that tag.
Repeat for each occurrence.

Repeat as well for subsequent errors might appear.

Good Luck!
