### ISSUE TITLE
How to eval a Java EL Expression programmatically?

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4427]
# Description #
----------

I want programmatically eval a Java EL expression, using the application context with all managed beans. In other words I want eval a String like `Hello ${person.name}`. The `person` would be a bean annotated with `@Named("person")`. 

Other examples:

```java
String result = evalutator.eval("Hello ${person.name}");
```
```java
int age = evaluator.eval("${person.age}");
```
```java
int total = evaluator.eval("${person.foo + person.bar}");
```

How I can do it?

**Comment by smillidge** [comment]
Hi @ThomasSousa96 this is the issue tracker for the Payara project rather than a general help forum. Can you raise questions like this on the forum https://groups.google.com/forum/?nomobile=true#!forum/payara-forum.

Thanks
