### ISSUE TITLE
System property not recognized /CUSTCOM-151

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4428]
# Description #
----------

The `payaramicro.logPropertiesFile` system property is not recognized.

I searched this property in the code and I saw that it is used for something else:

https://github.com/payara/Payara/blob/ef0d18ff874a45209fdc85f5cbc6e6f591a6cc3c/appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java#L2203

## Expected Outcome

That the logging properties are be applied.

## Current Outcome

The system property is not recognized and the logging properties file is ignored.

## Steps to reproduce (Only for bug reports) 

1. Generate a uber jar using the maven plugin
2. Run the application with the system property

```sh
mvn clean package
``` 

### Samples

```sh
java -Dpayaramicro.logPropertiesFile=logging.properties -jar target/my-microbundle.jar
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: N/A

**Comment by smillidge** [comment]
Looks like a bug to me

**Comment by smillidge** [comment]
Created Internal Bug ID CUSTCOM-151
