### ISSUE TITLE
@ResourceDependencies must be on Renderer Class

### ISSUE THREAD

**Issue by chrert** [payara/Payara#444]
We just ported our application from regular Glassfish 4.1 to Payara 4.1.153 and ran into the problem that our JSF custom components were not rendered anymore.

Each of our custom components is configured with a renderer per `@FacesRenderer` annotation. However, the encode* and decode* methods of the renderer were not called.

We found out that the problem was the `@ResourceDependencies` annotation of the Component class. If we move the annotation from the component to the renderer, everything works as expected. 

Here's an example:

Component:
```java
@FacesComponent(createTag = true, namespace = "http://www.somenamespace.com/test", tagName = "testComponent")
@ResourceDependencies({
    @ResourceDependency(library = "multipleslider", name = "js/jquery.js", target = "head")
})
public class TestComponent extends UIInput {
    public TestComponent() {
        setRendererType(TestRenderer.RENDERERTYPE);
    }

    @Override
    public String getFamily() {
        return TestRenderer.FAMILY;
    }

    ...
}
```
Renderer:
```java
@FacesRenderer(componentFamily = TestRenderer.FAMILY, rendererType = TestRenderer.RENDERERTYPE)
public class TestRenderer extends Renderer {

    public static final String FAMILY = "com.test.components";
    public static final String RENDERERTYPE = "TestRenderer";

    @Override
    public void encodeBegin(FacesContext context, UIComponent component) throws IOException {
         // won't get called
    }
}
```

This setup won't work, but if you move the `@ResourceDependencies` from the component class to the renderer class it will!

**Comment by smillidge** [comment]
Can you try on the latest GlassFish promoted build http://download.oracle.com/glassfish/4.1/promoted/glassfish-4.1-b16.zip and see if you have the same problem. That should be using the same version of mojarra (JSF) a Payara.

Alternatively create a smple test case app on GitHub and we can look into it.

**Comment by smillidge** [comment]
Do you still have this problem on the latest Payara builds?

**Comment by mikecroft** [comment]
@chrert is this still an issue for you? If you have a simple test case to reproduce, that would help us move things along

**Comment by mikecroft** [comment]
I'm assuming, at this point, that there is no longer a problem. Feel free to reopen it if the issue is still there.
