### ISSUE TITLE
Suppressed exception when thrown at ParamConverter

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4447]
# Description #
----------

When a custom `ParamConverter` throw a exception in the `fromString` method. The exception is supressed by the server and it returns 404 error code.

## Expected Outcome

That print the stack trace to the default output and returns 500 error code.

## Current Outcome

The exception is supressed by the server and it returns 404 error code.

## Steps to reproduce (Only for bug reports) 

1. Create a custom `ParamConverter`;
2. Create a `ParamConverterProvider` that provides the custom `ParamConverter`;
3. Simulate a exception in the `ParamConverter.fromString` method. Example:

```java
public class CustomParamConverter implements ParamConverter<MyCustomType> {
    
    public MyCustomType fromString(String value) {
        return new MyCustomType(value.concat("test"); //Throws a NullPointerException when the value is null.
        //This exception is suppressed by the server and it returns 404 error code.
    }
}
```
4. Create a endpoint. Example:

```java
@Path("/test")
public class Test {

    @GET
    public String foo(@QueryParam("t") MyCustomType t) {
         return "foo";
    }

}
```
5. Access the endpoint without the `t` query param. Example: `localhost:8080/test`.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: N/A

**Comment by rdebusscher** [comment]
Hi @ThomasSousa96 

The behaviour you describe is the expected behaviour described in the JAX-RS specification.

See section 3.2 of the JAX-RS specification.

>A WebApplicationException thrown during construction of field or property values using any of the 5 steps listed above is processed directly as described in Section 3.3.4. Other exceptions thrown during construction of field or property values using any of the 5 steps listed above are treated as client errors: if the field or property is annotated with @MatrixParam, @QueryParam or @PathParam then an implementation MUST generate an instance of NotFoundException (404 status) 

The 5 steps which are mentioned are the possibilities to create the field or property, including the use of a ParamConverter.

So you ParamConverter implementation generates a NullPointerException during the construction of the @QueryParam and thus must a throw a NotFoundException (404 status) .

Regards
Rudy
