### ISSUE TITLE
Payara does not run on readonly filesystems

### ISSUE THREAD

**Issue by rlfnb** [payara/Payara#4448]
# Description #
----------

Payara does not run on read only filesystems

## Expected Outcome

From a hardening perspecitve: When I run Payara, I would like have an immutable container without having the need to allow writing to the file system.  

## Current Outcome

```
$ ./asadmin start-domain
java.nio.file.AccessDeniedException: /tmp/payara/payara5/glassfish/domains/domain1/logs/server.log.lck

```

`         <log-service log-rotation-limit-in-bytes="2000000" file="${com.sun.aas.instanceRoot}/logs/server.log">
`
log-service should understand stdout as target instead of/in addition to file to log to e.g. stdout as well.
Furthermore, the need for writing the domain.xml after startup should removed as well, maybe as a cli switch?

## Steps to reproduce (Only for bug reports) 

Download payara-5.194.zip
unzip payara-5.194.zip
chmod -R a-w payara5
cd payara5/bin/
./asadmin start-domain
java.nio.file.AccessDeniedException: /tmp/payara/payara5/glassfish/domains/domain1/logs/server.log.lck

## Context (Optional)

Its a core functionality to enable hardening systems running payara.

## Environment ##

- **Payara Version**: payara-5-194
- **Edition**: Full/maybe all others as well?
- **JDK Version**: OpenJDK11, but should not matter
- **Operating System**: Tested on Linux, should be the same for all others
- **Database**: No database needed to reproduce

**Comment by rdebusscher** [comment]
Hi,

Can you use symlinks in the <payara-home>/glassfish/domains directory pointing to writable systems?

Besides logging and configuration, the deployment also needs write access. So Payara Server can and will never run on an readonly filesystem.

Regards
Rudy.

**Comment by lprimak** [comment]
Domain needs to be on writable filesystem. Payara distribution itself can be in read-only filesystem. You can use —domaindir parameter to simplify the process with no symlinks

**Comment by rdebusscher** [comment]
Hi,

If you need more information, you can ask more information on using symlinks and the --domaindir on the [Payara Forum](https://groups.google.com/forum/#!forum/payara-forum).

Regards
Rudy
