### ISSUE TITLE
Illegal reflective access by fish.payara.microprofile.openapi.impl.model.util.AnnotationInfo /CUSTCOM-170

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#4449]
# Description #
----------

The following warnings appear when you start Payara Micro 5.194 with Java 11

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by fish.payara.microprofile.openapi.impl.model.util.AnnotationInfo (file:/tmp/payaramicro-rt3420083111219124935tmp/runtime/microprofile-openapi.jar) to field java.lang.reflect.Parameter.index
WARNING: Please consider reporting this to the maintainers of fish.payara.microprofile.openapi.impl.model.util.AnnotationInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

It is just a warning. Payara starts and works.

## Expected Outcome

The problem should be fixed in future releases to avoid false starts

## Current Outcome

See description.

## Steps to reproduce (Only for bug reports) 

1 -**  Start Payara with Rest Ressources

2 -**  Create Open API Document

http://localhost:8080/openapi

3 -**  See  console output

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by fish.payara.microprofile.openapi.impl.model.util.AnnotationInfo (file:/tmp/payaramicro-rt998873570193110858tmp/runtime/microprofile-openapi.jar) to field java.lang.reflect.Parameter.index
WARNING: Please consider reporting this to the maintainers of fish.payara.microprofile.openapi.impl.model.util.AnnotationInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2020-01-21T15:32:29.798+0100] [] [INFO] [] [fish.payara.microprofile.openapi.impl.OpenApiService] [tid: _ThreadID=31 _ThreadName=http-thread-pool::http-listener(2)] [timeMillis: 1579617149798] [levelValue: 800] OpenAPI document created.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: Amazon Corretto JDK 11u6
- **Operating System**: Docker for Windows / Debian Image

**Comment by rdebusscher** [comment]
Hi @LarsBrenker,

I reproduced the warning when using an annotation on a method parameter like @PathParam.

I created the internal issue `CUSTCOM-170` to fix this in a future version.

Thanks for this report

Regards
Rudy.

**Comment by smillidge** [comment]
Fixed by #4758
