### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by aligit** [payara/Payara#4456]
# Description #
----------
Unlike my colleagues with similar system configuration, my Payara startup speed is very slow. I run the server through Intellij Idea run and it takes around 26 seconds.

## Expected Outcome

The startup should take no longer than 15 seconds

## Current Outcome

It takes at least 26 seconds startup. This time increases overtime and reaches 1 minute.

## Context (Optional)
Trying to run a JSF monolith

## Environment ##

- **Payara Version**:  5.192 
- **Edition**: Server
- **JDK Version**: 8 u232 - OpenJDK
- **Operating System**: Linux
- **Database**: PostGres

**Comment by chrjohn** [comment]
Wow, that's an awful lot of information you provided there. ;) Maybe a log file from the startup process would come in handy. Moreover, what is the startup time without the application? There are applications which start up fast and ones that start up slow (the bigger ones).

**Comment by aligit** [comment]
Thank you @chrjohn 

Here is the application log

> [2020-01-27T09:47:15.539+0100] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114835539] [levelValue: 800] [[
>   Cannot find the resource bundle for the name com.sun.logging.enterprise.system.container.ejb for class org.glassfish.ejb.persistent.timer.TimerState using org.glassfish.main.ejb.ejb-full-container [133]]]
> 
> [2020-01-27T09:47:15.549+0100] [Payara 5.192] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114835549] [levelValue: 800] [[
>   [36] EJB Timers owned by this server will be restored when timeout beans are loaded]]
> 
> [2020-01-27T09:47:15.549+0100] [Payara 5.192] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114835549] [levelValue: 800] [[
>   <== ... Timers Restored.]]
> 
> [2020-01-27T09:47:16.008+0100] [Payara 5.192] [INFO] [] [org.glassfish.tyrus.servlet.TyrusServletContainerInitializer] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114836008] [levelValue: 800] [[
>   Registering WebSocket filter for url pattern /*]]
> 
> [2020-01-27T09:47:16.009+0100] [Payara 5.192] [INFO] [] [org.omnifaces.ApplicationInitializer] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114836009] [levelValue: 800] [[
>   Using OmniFaces version 3.4]]
> 
> [2020-01-27T09:47:16.176+0100] [Payara 5.192] [INFO] [] [org.glassfish.soteria.servlet.SamRegistrationInstaller] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114836176] [levelValue: 800] [[
>   Initializing Soteria 1.1-b01 for context '/bfabric']]
> 
> [2020-01-27T09:47:16.340+0100] [Payara 5.192] [INFO] [jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114836340] [levelValue: 800] [[
>   Initializing Mojarra 2.3.9.payara-p2 for context '/bfabric']]
> 
> [2020-01-27T09:47:17.263+0100] [Payara 5.192] [INFO] [] [org.primefaces.webapp.PostConstructApplicationEventListener] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114837263] [levelValue: 800] [[
>   Running on PrimeFaces 8.0.RC2]]
> 
> [2020-01-27T09:47:17.264+0100] [Payara 5.192] [INFO] [] [org.primefaces.extensions.application.PostConstructApplicationEventListener] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114837264] [levelValue: 800] [[
>   Running on PrimeFaces Extensions 8.0.RC1]]
> 
> [2020-01-27T09:47:18.820+0100] [Payara 5.192] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1580114809211] [timeMillis: 1580114838820] [levelValue: 800] [[
>   Loading application [bfabric-10.0.0-SNAPSHOT] at [/bfabric]]]
> 
> [2020-01-27T09:47:18.826+0100] [Payara 5.192] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1580114838826] [levelValue: 800] [[
>   Payara Server  5.192 #badassfish (115) startup time : Felix (1,302ms), startup services(29,617ms), total(30,919ms)]]
> 
> [2020-01-27T09:47:18.826+0100] [Payara 5.192] [INFO] [] [fish.payara.nucleus.cluster.PayaraCluster] [tid: _ThreadID=126 _ThreadName=Executor-Service-1] [timeMillis: 1580114838826] [levelValue: 800] [[
>   Data Grid Status 
> Payara Data Grid State: DG Version: 35 DG Name: development DG Size: 1
> Instances: {
>  DataGrid: development Instance Group: MicroShoal Name: server Lite: false This: true UUID: 1ca34fdc-e92d-4736-a2df-3b3475a9dacf Address: /130.60.81.141:4900
> }]]
> 
> [2020-01-27T09:47:18.829+0100] [Payara 5.192] [INFO] [] [fish.payara.nucleus.notification.NotificationService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1580114838829] [levelValue: 800] [[
>   Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=LogNotifierConfigurationExecutionOptions{useSeparateLogFile=false} NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true, noisy=true}}}]]
> 
> [2020-01-27T09:47:18.872+0100] [Payara 5.192] [INFO] [NCLS-CORE-00101] [javax.enterprise.system.core] [tid: _ThreadID=32 _ThreadName=RunLevelControllerThread-1580114809216] [timeMillis: 1580114838872] [levelValue: 800] [[
>   Network Listener JMS_PROXY_default_JMS_host started in: 0ms - bound to [/0.0.0.0:7676]]]
> 
> [2020-01-27T09:47:19.033+0100] [Payara 5.192] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=154 _ThreadName=Thread-18] [timeMillis: 1580114839033] [levelValue: 800] [[
>   JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi]]
> 
> [2020-01-27T09:47:19.212+0100] [Payara 5.192] [INFO] [] [org.jvnet.hk2.osgiadapter] [tid: _ThreadID=20 _ThreadName=FelixStartLevel] [timeMillis: 1580114839212] [levelValue: 800] [[
>   Skipping registration of inhabitant for service reference [org.osgi.service.metatype.MetaTypeProvider] as the service object could not be obtained.]]
> 
> [2020-01-27T09:47:19.358+0100] [Payara 5.192] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=53 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1580114839358] [levelValue: 800] [[
>   [9] timers deleted for id: 103554324675756032]]
> 
> [2020-01-27T09:47:19.362+0100] [Payara 5.192] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=53 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1580114839362] [levelValue: 1000] [[
>   The web application [/bfabric] created a ThreadLocal with key of type [com.sun.xml.bind.v2.ClassFactory$1] (value [com.sun.xml.bind.v2.ClassFactory$1@2f0e5255]) and a value of type [java.util.WeakHashMap] (value [{class com.sun.xml.ws.runtime.config.MetroConfig=java.lang.ref.WeakReference@256aca1d, class com.sun.xml.ws.runtime.config.TubeFactoryConfig=java.lang.ref.WeakReference@74e8f767, class com.sun.xml.ws.runtime.config.Tubelines=java.lang.ref.WeakReference@15dbb7c8, class javax.xml.bind.annotation.W3CDomHandler=java.lang.ref.WeakReference@489ad3dc, class java.util.ArrayList=java.lang.ref.WeakReference@3b53d2f0, class javax.xml.bind.annotation.adapters.CollapsedStringAdapter=java.lang.ref.WeakReference@8334932, class com.sun.xml.ws.runtime.config.TubelineDefinition=java.lang.ref.WeakReference@409eda0b, class com.sun.xml.ws.runtime.config.TubeFactoryList=java.lang.ref.WeakReference@5e84f5f7}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]
> 

Also only launching Payara server will take around 26 seconds

**Comment by chrjohn** [comment]
Two things: could you please attach log files. This makes them more readable. And secondly, the output you posted is only a few seconds long. Can you provide the file directly from the start?

**Comment by aligit** [comment]
My application Log

[server.log](https://github.com/payara/Payara/files/4117069/server.log)

Only Payara startup log

[server.log](https://github.com/payara/Payara/files/4117082/server.log)

**Comment by chrjohn** [comment]
Hmm, the second server starts in about 4 seconds. But it is from a different instance of Payara. The slow instance has Payara 5.192 on Oracle JDK. The "virgin" Payara has OpenJDK and Payara 5.194.

What happens if you deploy on that "virgin" Payara which is on a recent version?

Moreover, on the slow Payara you see over a minute time is spent here:

```
[2020-01-27T13:22:20.228+0100] [Payara 5.192] [INFO] [] [org.glassfish.soteria.cdi.CdiExtension] [tid: _ThreadID=54 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1580127740228] [levelValue: 800] [[
  Activating javax.security.enterprise.authentication.mechanism.http.CustomFormAuthenticationMechanismDefinition authentication mechanism from org.bfabric.manager.ConfManager class]]

[2020-01-27T13:23:30.239+0100] [Payara 5.192] [INFO] [] [fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl] [tid: _ThreadID=54 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1580127810239] [levelValue: 800] [[
  Clustered CDI Event bus initialized]]
```

I don't know exactly what happens there but it could be that there are network timeouts which lead to this huge time difference.

**Comment by aligit** [comment]
Thank you very much. The problem was that the wrong java version was picked up.
