### ISSUE TITLE
Profiler configuration incorrectly handles commas in profiler JVM options /CUSTCOM-185

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#4458]
# Description #
----------

I've never been able to use asadmin or admin console to configure YourKit java profiler to work with payara.  YJP uses commas to delimit the options list for the profiling agent, and asadmin and admin console don't account for the existence of commas in a single jvm-option for the profiler configuration.  This was a problem back in Payara v4, and Glassfish v2/3/4.

An example:

YJP would use a single jvm option that looks like this:
`-agentpath:/opt/java/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=disablestacktelemetry,disableexceptiontelemetry,probe_disable=*,delay=10000,sessionname=Payara`

Trying to specify this with asadmin create-profiler command doesn't seem to work because it assumes the properties are all name/value pairs, but YJP uses a jvm option which looks more like a switch than a name=value property, so this asadmin command fails:
`Invalid property syntax, missing property value: -agentpath`

Trying to create the profiler without properties and using `asadmin set` doesn't work since it interprets the commas in the jvm property as an asadmin delimiter which creates separate jvm options for each item separated by a comma.

Trying to create the profiler without properties and then using the admin console to add a single jvm option DOES work to create a single jvm option without parsing the commas, but that only works one time.  Afterward, if the profiler configuration is changed in the admin console (for example, to toggle the enabled/disabled) then the jvm-option is reparsed during that operation and separated into multiple jvm properties.

The workaround I've always used is to edit the domain.xml directly to add the profiler, never use the admin console to edit the profiler configuration, and only use asadmin to change the enabled flag to toggle the profiler agent on and off.
 
## Expected Outcome

A better outcome would be for asadmin and admin console to recognize and parse the options in a way that would allow commas to be specified within a single profiler jvm option.

The following is a correct and working domain.xml snippet (<profiler> element):
```
<java-config classpath-suffix="" debug-options="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009" system-classpath="">
  <profiler name="YourKit_Java_Profiler_2019.8-b137">
    <jvm-options>-agentpath:/opt/java/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=disablestacktelemetry,disableexceptiontelemetry,probe_disable=*,delay=10000,sessionname=Payara</jvm-options>
    <jvm-options>-Dcom.sun.enterprise.server.ss.ASQuickStartup=false</jvm-options>
  </profiler>
  <jvm-options>-server</jvm-options>
```

## Current Outcome

asadmin and admin console seem to want to generate the following <profiler> element:
```
<java-config classpath-suffix="" debug-options="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009" system-classpath="">
  <profiler name="YourKit_Java_Profiler_2019.8-b137">
    <jvm-options>-agentpath:/opt/java/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=disablestacktelemetry</jvm-options>
    <jvm-options>disableexceptiontelemetry</jvm-options>
    <jvm-options>probe_disable=*</jvm-options>
    <jvm-options>delay=10000</jvm-options>
    <jvm-options>sessionname=Payara</jvm-options>
    <jvm-options>-Dcom.sun.enterprise.server.ss.ASQuickStartup=false</jvm-options>
  </profiler>
  <jvm-options>-server</jvm-options>
```

## Steps to reproduce (Only for bug reports) 

1 - **Installation of YJP agent**

Strictly speaking, the agent isn't necessary to reproduce the problem, but one can download the no-cost profiling agent from https://www.yourkit.com/download/YourKit-JavaProfiler-2019.8-b137.zip and unzip to `/opt/java/YourKit-JavaProfiler-2019.8` path.

Note: the JVM option specifies the full path of the agent file.  If installing the agent to a different directory, the JVM option needs to reference that different directory, and must be readable by the same OS user running payara server.

2 - **Try configuring a profiler with asadmin or admin console**

Relevant asadmin commands would be `asadmin set` and `asadmin create-profiler`

Relevant admin console configuration can be done under Configuration -> server-config -> JVM Settings... Profiler tab... Enter profiler name and attempt to add the following JVM property:
```
-agentpath:/opt/java/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=disablestacktelemetry,disableexceptiontelemetry,probe_disable=*,delay=10000,sessionname=Payara
```

3 - After editing the profiler configuration, restart the server, reconnect to the admin console, go back to the profiler configuration, toggle the enabled flag, save and restart the server again and the jvm options will have been reparsed.  Occasionally the profiler configuration will show text saying there was a runtime exception, but this seems to be a different issue.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: zulu-11 Zulu11.37+17-CA (build 11.0.6+10-LTS)
- **Operating System**: CentOS-7
- **Profiler**: YourKit Java Profiler 2019.8-b137 linux-x86-64

**Comment by fturizo** [comment]
Greetings @phillipross, many thanks for reporting this issue. Interestingly while testing out this functionality on Payara Server 5.194 I found out that trying to create a profiler's configuration with JVM options is not working via the admin console. Trying to add JVM options (even if they are correctly formatted), will fail completely when doing this through the admin console. I've escalated the required fix to this behaviour via the internal issue `CUSTCOM-185`.

Now, regarding the ability of Payara Server to correctly parse Yourkit's Profiler JVM Options,  you can "fool" the server into accepting all corresponding JVM options in comma-separated format by using the following asadmin command:

    asadmin create-jvm-options --profiler=true --target=server-config "-agentpath\:/opt/java/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=disablestacktelemetry,disab
    leexceptiontelemetry,probe_disable=*,delay=10000,sessionname=Payara"

Notice that for the DAS to accept the full string, you need to escape the `:` character for defining the `-agentpath` setting and put the entire string in double quotes. Try to test this solution in your environment.

**Comment by phillipross** [comment]
thanks @fturizo I see now that the --profiler option for the create-jvm-options is something I didn't know about.  I'll test again with this and see what happens.

**Comment by phillipross** [comment]
After testing, I see that this does work... and installing and configuring the profiler via asadmin works fine.  It's just the admin console that is problematic.  Thanks again!
