### ISSUE TITLE
OpenIdContext caller name and caller groups always null even when SecurityContext caller principal name and isCallerInRole work

### ISSUE THREAD

**Issue by sharpedavid** [payara/Payara#4467]
# Description #

I'm integrating Payara with Keycloak using Payara's support for OpenID connect (described in https://blog.payara.fish/openid-connect-in-the-payara-platform-5.183). It's actually working nicely, but I see behaviour I don't understand that I think is a bug.

## Expected Outcome

The official blog post claims that "User claims, ID Token and the other authentication information can be accessed after a successful authentication from the fish.payara.security.openid.api.OpenIdContext." Two methods on the `OpenIdContext` class are `getCallerName` and `getCallerGroups`. After successfully authentication I would expect these methods to return the "username" and "roles" of the authenticated user.

## Current Outcome

`OpenIdContext.getCallerName` and `OpenIdContext.getCallerGroups` return null. However, authentication seems to have worked, and `SecurityContext.getCallerPrincipal().getName()` and `securityContext.isCallerInRole("somerole")` work as expected.

## Steps to reproduce

I configure the project as described in example in the Payara blog post, but I've added a JSF page and a web.xml file to declare security. Here is my project:

https://github.com/bcgov/moh-iam/tree/master/keycloak-javaee-example

So to reproduce the problem, I navigate to https://localhost:8181/KeycloakIntegrationExample/faces/newjsf.xhtml, which redirects me to Keycloak for authentication, and then back to https://localhost:8181/KeycloakIntegrationExample/callback, which prints some diagnostic information like this:

```
principal: javax.security.enterprise.CallerPrincipal@7635d80d

principal name: davidsharpe

caller name: null

caller groups: null

...

caller principal name: davidsharpe

isCallerInRole? PSDADMIN: true

isCallerInRole? FAKEROLE: false
```

This example works with my local Keycloak installation. To get that working I added a user in Keycloak, a client, some client roles, and changed the client role mapping to map to "groups", the default expected by `fish.payara.security.annotations.OpenIdAuthenticationDefinition`.

### Samples

https://github.com/bcgov/moh-iam/tree/master/keycloak-javaee-example

**NOTE:** I strongly expect that you can reproduce this bug with the [sample provided on the Payara blog post](https://github.com/javaee-samples/vendoree-samples/tree/master/payara/openid), which would avoid the need to involve an external OpenID provider like Keycloak. I tried to use that sample to demonstrate the bug, but I'm unable to build it. I filed another bug report for that [here](https://github.com/javaee-samples/vendoree-samples/issues/7).

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full/Web/Blue/Micro
- **JDK Version**: JDK 1.8 (OpenJDK from RedHat) (java-1.8.0-openjdk-1.8.0.191-1.b12.redhat.windows.x86_64)
- **Operating System**: Windows

**Comment by OndroMih** [comment]
Hi, I'll try to reproduce it against an external KeyCloack but it would be very helpful if you provided a self-contained reproducer which doesn't require installing Keycloak. If you would provide a reproducer based on Docker it would also help, e.g. using docker-compose.

**Comment by OndroMih** [comment]
As I commented in https://github.com/javaee-samples/vendoree-samples/issues/7, it's possible to build the project using an additional maven property.

Because Payara-Web 5.194 contains a bug and can't be used for tests, I also modified the top-level pom.xml to test on Payara-Full. I changed the artifact on line https://github.com/javaee-samples/vendoree-samples/blob/8dc074f33da068cd4a7895a809f709d17e118c55/pom.xml#L415 from `payara-web` to `payara`.

Then I executed tests with the following command:

```
mvn -Dpayara.version=5.194 -fae clean package
```

And only one of them tailed: `UseCookiesTest.testOpenIdConnect:91 Roles test failed.`

Can you have a look if this failed test reproduces your issue?

**Comment by sharpedavid** [comment]
> Can you have a look if this failed test reproduces your issue?

I will check this week and get back to you.

**Comment by sharpedavid** [comment]
I am able to run the tests as you describe, but I'm unsure if this reproduces my issue. Reading the [failing test code](https://github.com/javaee-samples/vendoree-samples/blob/master/payara/openid/src/test/java/fish/payara/security/oidc/test/OpenIdTestUtil.java#L98), it seems the test failed because it was able to access a page it expected should have been forbidden.

That said, I realized I can use these tests to demonstrate the issue. Just add a few lines to the existing https://github.com/javaee-samples/vendoree-samples/blob/master/payara/openid/src/main/java/fish/payara/security/oidc/client/Callback.java:

```java
package fish.payara.security.oidc.client;

import fish.payara.security.openid.api.OpenIdContext;
import java.io.IOException;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.security.enterprise.SecurityContext;
import java.security.Principal;

/**
 * @author Gaurav Gupta
 */
@WebServlet("/Callback")
public class Callback extends HttpServlet {
    
    @Inject
    private OpenIdContext context;
    
    @Inject
    private SecurityContext security;
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        
        // BEGIN Issue 4467 demonstration code
        System.out.println("context.getCallerName(): " + context.getCallerName());
        System.out.println("context.getCallerGroups(): " + context.getCallerGroups());
        
        System.out.println("security.getCallerPrincipal().getName(): " + security.getCallerPrincipal().getName());        
        Principal userPrincipal = request.getUserPrincipal();
        System.out.println("userPrincipal.getName()" + userPrincipal.getName());
       // END Issue 4467 demonstration code
        
        response.getWriter().println(context.getAccessToken());
    }
    
}
```

And rerun the tests. In the server log you will see the following output:

```
[2020-02-04T16:18:14.326-0800] [Payara 5.194] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=111 _ThreadName=admin-thread-pool::admin-listener(4)] [timeMillis: 1580861894326] [levelValue: 800] [[
  openid-client was successfully deployed in 1,046 milliseconds.]]

[2020-02-04T16:18:14.693-0800] [Payara 5.194] [INFO] [] [] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1580861894693] [levelValue: 800] [[
  context.getCallerName(): null]]

[2020-02-04T16:18:14.693-0800] [Payara 5.194] [INFO] [] [] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1580861894693] [levelValue: 800] [[
  context.getCallerGroups(): null]]

[2020-02-04T16:18:14.722-0800] [Payara 5.194] [INFO] [] [] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1580861894722] [levelValue: 800] [[
  security.getCallerPrincipal().getName(): sample_subject]]

[2020-02-04T16:18:14.722-0800] [Payara 5.194] [INFO] [] [] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1580861894722] [levelValue: 800] [[
  userPrincipal.getName(): sample_subject]]
```

I expected `context.getCallerName()` to return `sample_subject`, the same as the others. I expected `context.getCallerGroups()` to return the roles/groups if any, but perhaps there were none for this test.

(While this does seem like a bug, so I'm reporting it, I admit the impact seems low because there are obvious workarounds: just use the standard API.)

**Comment by sharpedavid** [comment]
I wonder if this has any relationship with https://github.com/payara/Payara/issues/3877. It seems it would "fix" `context.getCallerName()` at least, if not groups.

**Comment by OndroMih** [comment]
Hi @sharpedavid, when I modified the test case with your code, I see null values for getCallerName and getCallerGroups. But I don't see `sample_subject` as teh value of `security.getCallerPrincipal().getName()`. Actually, `security.getCallerPrincipal()` is null, which leads to a null pointer exception. Did I do something wrong?

**Comment by sharpedavid** [comment]
Thanks for trying, OndroMih. I'm not sure why you didn't get the same result, but I suggest you archive (or close) this for now. I will do as you suggested earlier and try to make a self-contained reproducer with Docker Compose, but that won't be for awhile as I'm busy and inexperienced with Docker.

**Comment by crazed-developer** [comment]
Hello Ondro,

So I'm testing out this OpenId together with Keycloak.

I seem to be able to authenticate okay, but the roles is not set on the Principal. (Like I see David struggles with)

The Keycloak JWT looks like this:

```json
{
 exp: 1585214155,
 iat: 1585213855,
 auth_time: 1585213855,
 jti: "41304394-4aca-4404-b55c-e161eed23c83",
 iss: "http://localhost:8180/auth/realms/quarkus",
 aud: "account",
 sub: "ee9b1890-38d8-4a0c-84cc-06976c38e476",
 typ: "Bearer",
 azp: "frontend",
 nonce: "cBWMJ0GiaHaNPxr7mKszAt4JPCwJ5SXf60Uw4jKS-9A",
 session_state: "12f2199e-72a4-44a5-b3fa-02f51d4eab6e",
 acr: "1",
 realm_access: {
  roles: [
   "offline_access",
   "uma_authorization",
   "AP-ADMIN"
  ]
 },
 resource_access: {
  account: {
   roles: [
    "manage-account",
    "manage-account-links",
    "view-profile"
   ]
  },
  frontend: {
   roles: [
    "AP-ADMIN"
   ]
  }
 },
 scope: "openid profile email",
 email_verified: false,
 preferred_username: "alice"
}.
```
I understand that the Roles/Groups collection name can be set using the:
- claimsDefinition = @ClaimsDefinition(callerGroupsClaim = "roles")
(Default is "groups")

However this fits pretty bad with the format of the json in the snippet above. Where it's two sections, and the second section has two "roles" collections.

**I wonder how the callerGroupsClaim should be defined (Is this not compatible with Keycloak?)**

I have not made examples, sorry.

Notes:
```java
@Inject
private OpenIdContext context;
...
context.getAccessToken().getClaims().get("preferred_username")
//equals
request.getUserPrincipal().getName()
```

**Comment by sharpedavid** [comment]
> However this fits pretty bad with the format of the json in the snippet above. Where it's two sections, and the second section has two "roles" collections.
> 
> **I wonder how the callerGroupsClaim should be defined (Is this not compatible with Keycloak?)**

Hi @crazed-developer, I can confirm that Keycloak and Payara are compatible. This bug report is more of a minor inconvenience or oddity where the API is returning a null when I expected a value, but the alternative API still works.

----

I think I can help your solve your issue though. The reason that role mapping isn't automatic is because OpenID Connect doesn't define "role" a standard claim/attribute, so there is no specification-defined way to handle it universally. 

Keycloak by default maps the client role to `resource_access.${client_id}.roles`, but this has nothing to do with OIDC: it's just want Keycloak decided to do. Payara supports configuration with `callerGroupsClaim`, but I don't think it supports the nested structure that Keycloak is capable of.

To integrate Keycloak with Payara, we configured a client role mapper in Keycloak. This allows us to tell Keycloak where to put client roles:

![image](https://user-images.githubusercontent.com/1767127/77673953-1b9fb000-6f48-11ea-8785-72edcadf2c5e.png)

Then the access token looks like this:

```json
{
  "jti": "9bfc0d8f-f512-40a1-9c8b-fd63797b612c",
  "exp": 1585242210,
  "nbf": 0,
  "iat": 1585241910,
  "iss": "http://localhost:8081/auth/realms/moh-users-realm",
  "aud": "account",
  "sub": "5b960d37-c7d7-4315-92b9-8fc927abbe55",
  "typ": "Bearer",
  "azp": "KeycloakIntegrationExample",
  "auth_time": 0,
  "session_state": "3541f596-145d-4460-9d60-6b02197097ba",
  "acr": "1",
  "allowed-origins": [
    ""
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "KeycloakIntegrationExample": {
      "roles": [
        "ADMIN"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "email_verified": false,
  "groups": [
    "ADMIN"
  ],
  "preferred_username": "davidsharpe",
  "email": "**************"
}
```

**Comment by crazed-developer** [comment]
Hi David,

Thanks a lot, this brought me forward very swiftly. 

You took your time and gave a clear example, thanks again.

Now.. looks like he logintocontinue is not supported, any experience with this?

Kind regards

Steffen

**Comment by sharpedavid** [comment]
@OndroMih I have a hunch this is going to be truly resolved (not just closed) by https://github.com/payara/Payara/pull/4659. It sounds similar. I'm commenting here for posterity. I don't need anything.
