### ISSUE TITLE
OpenIdAuthenticationDefinition javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier /FISH-84

### ISSUE THREAD

**Issue by sharpedavid** [payara/Payara#4469]
# Description #

I'm attempting to use Expression Language with a CDI Bean to configure OpenIdAuthenticationDefinition as described in the documentation here https://docs.payara.fish/documentation/payara-server/public-api/openid-connect-support.html.

> Additionally, the @OpenIdAuthenticationDefinition supports the use of expression language (EL) notation for dynamic configuration scenarios. This means that you can use any CDI bean properties to set the OpenID Connect configuration like this:

My problem is that I'm able to use EL in a WAR, but it often fails when I attempt to put the WAR in an EAR.

## Expected Outcome

I expect to be able to configure OpenIdAuthenticationDefinition using Expression Language with a CDI Bean in a WAR file in an EAR file.

I have linked to a complete example below in "Steps to Reproduce", but here is a brief demonstration:

```java
package ca.bc.gov.health.security;
import fish.payara.security.annotations.OpenIdAuthenticationDefinition;

@OpenIdAuthenticationDefinition(
       providerURI = "#{myConfigBean.myvalue}",
       clientId = "ElBugExample",
       clientSecret = "someSecret",
       redirectURI = "#{myConfigBean.myvalue}",
       scope = { "openid" }

)
public class KeycloakSecurityBean {
    
}
```

```java
package ca.bc.gov.health.security;

import javax.inject.Named;

@Named
public class MyConfigBean {
    
    private String myvalue = "mouse8";

    public String getMyvalue() {
        return myvalue;
    }
    
}
```

## Current Outcome

Sometimes the Expression Language look-up succeeds, and sometimes it fails. When it **fails**, it generates this error message:

`javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier 'myConfigBean'`

When it **succeeds**, it generates this error message:

`javax.ws.rs.ProcessingException: URI is not absolute`

This error message is expected in the successful case because I've intentionally used a bad URI because I don't want to complicate things by including an OpenId Provider.

## Steps to reproduce

https://github.com/sharpedavid/el-bug-example

See the README.md file for more details.

## Environment ##

- **Payara Version**: Payara Server 5.192
- **Edition**: Full
- **JDK Version**: Oracle JDK 8
- **Operating System**: Windows

**Comment by OndroMih** [comment]
Hi, I was able to reproduce very easily, thanks for the reproducer.
