### ISSUE TITLE
JNDI Resource injection is not working for application scoped resources

### ISSUE THREAD

**Issue by tschia** [payara/Payara#4473]
# Description #

I'm trying to use the `@Resource` annotation to inject an **application scoped** JNDI resource of type java.util.Properties
e.g)
```java
@Resource(name = "java:app/testApp/test_properties")
Properties testProperties
```

This works in Payara 5.193 but no longer works in Payara 5.194. 

**Note:** in Payara 5.194 global scoped resources appear to still work.
## Expected Outcome

I would expect to continue to be able to inject application scoped JNDI resources in Payara 5.194 using the @Resources annotation. 
There is a link to a full example in steps to reproduce but in short I would expect this block of code to not give a null pointer exception (where java:app/testApp/test_properties is an application scoped JNDI resource)

```java
@Named
public class SomeBean {
    
    @Resource(name = "java:app/testApp/test_properties")
    Properties testProperties;
    
    private String testProperty;
    
    @PostConstruct
    private void init() {     
        testProperty = testProperties.getProperty("testProperty");
    }

    public String getTestProperty() {
        return testProperty;
    } 
}
```

## Current Outcome

In this test case when attempting to access the properties object I get a null pointer exception. 
## Steps to reproduce (Only for bug reports) 

[https://github.com/tschia/TestProjects/tree/master/TestWebApp](https://github.com/tschia/TestProjects/tree/master/TestWebApp)

For Payara running on localhost:8080 you can deploy this application and navigate to 
http://localhost:8080/TestWebApp/resources/javaee8 to reproduce the error.

## Environment ##

- **Payara Version**: 5.194
- **Edition**:  Full 
- **JDK Version**: Oracle JDK 8
- **Operating System**: Windows

**Comment by chrjohn** [comment]
Did you try using `lookup` instead of `name`?
Might be related to https://github.com/payara/Payara/issues/4413#issuecomment-573706381

**Comment by tschia** [comment]
That works, thank you. It looks like it was the exact same issue as in #4413
