### ISSUE TITLE
When I do a restoration of glassfish to payara and start payara when opening the applications it shows me the following error java.lang.NullPointerException

### ISSUE THREAD

**Issue by fiermacc** [payara/Payara#4476]
El error es el siguiente, java.lang.NullPointerException al momento de migrar un servidor glassfish a payara y ver las aplicaciones migradas.

**Comment by OndroMih** [comment]
Please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. What you provided is not enough to understand what the problem is and how to fix it.

**Comment by fiermacc** [comment]
![gh](https://user-images.githubusercontent.com/33506990/74163720-8a77b280-4c01-11ea-90cf-a5d8d0317dc2.png)

**Comment by fiermacc** [comment]
> Por favor, ¿puede proporcionar un escenario simple de seguir para reproducir esto en la última versión? Idealmente, un reproductor debe seguir las reglas de SSCCE: http://www.sscce.org/ . Lo que proporcionó no es suficiente para comprender cuál es el problema y cómo solucionarlo.

Yes, Yes, the migrated glassfish is version 4 and copy it to a payara 5.194

**Comment by fiermacc** [comment]
> Por favor, ¿puede proporcionar un escenario simple de seguir para reproducir esto en la última versión? Idealmente, un reproductor debe seguir las reglas de SSCCE: http://www.sscce.org/ . Lo que proporcionó no es suficiente para comprender cuál es el problema y cómo solucionarlo.

Yes, yes, the migrated glassfish is version 4 and restore it on a payara server 5.194

**Comment by rdebusscher** [comment]
Hi,

Copying a domain from Glassfish 4 to Payara is not supported.

If you need support in your migration to Payara, you should consider [Payara Enterprise](https://www.payara.fish/support/).
