### ISSUE TITLE
Error in payara 

### ISSUE THREAD

**Issue by fiermacc** [payara/Payara#4483]
When I do a restoration of glassfish to payara and start payara when opening the applications it shows me the following error java.lang.NullPointerException
![gh](https://user-images.githubusercontent.com/33506990/74237409-42fd2f00-4cb2-11ea-8d9d-31f25ff0f03c.png)
(url)

**Comment by rdebusscher** [comment]
Hi,

What do you mean by `restoration of glassfish to payara`? Did you try to copy a Glassfish domain to a Payara Domain?

There are a few changes in the detection of the deployed application which might trigger a similar error.

Can you indicate
- From which Glassfish version did you start?
- Does it work when you remove the <application> entry in the config/domain.xml file and deploy the application again when Payara server is started.

Rudy

**Comment by rdebusscher** [comment]
This is a duplicate of #4476

**Comment by fiermacc** [comment]
> Hola,
> 
> ¿Qué quieres decir con `restoration of glassfish to payara`? ¿Intentaste copiar un dominio Glassfish a un dominio Payara?
> 
> Hay algunos cambios en la detección de la aplicación implementada que pueden desencadenar un error similar.
> 
> Puedes indicar
> 
> * ¿Desde qué versión de Glassfish comenzaste?
> * ¿Funciona cuando elimina la entrada en el archivo config / domain.xml y vuelve a implementar la aplicación cuando se inicia el servidor Payara?
> 
> Rudy

Yes, Yes, the migrated glassfish is version 4 and copy it to a payara 5.194.
