### ISSUE TITLE
[microprofile] Openapi - Implementation of TreeSet comparator is wrong. /CUSTCOM-197

### ISSUE THREAD

**Issue by Berger1994** [payara/Payara#4489]
The compartor implementation for the used TreeSet in the class `fish.payara.microprofile.openapi.impl.visitor.OpenApiWalker` ([here](https://github.com/payara/Payara/blob/a1dda93443b92f2c3ca54b8dbb1786a775727d5d/appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java#L120)) is wrong. It depends on how many classes are filled in the list. (the order has a problem too)

I created a simple test class with the same compartor and the result is false althoug the class is inside the tree.

```
public static void main(String... args) {
		Set<Class<?>> clazzes = new TreeSet<>((class1, class2) -> {
			System.out.print("Compare " + class1.getSimpleName() + " with " + class2.getSimpleName() + " | ");
			if (class1.equals(class2)) {
				System.out.println("0");
				return 0;
			}
			// Subclasses first
			if (class1.isAssignableFrom(class2)) {
				System.out.println("-1");
				return -1;
			}
			// Non contextual objects at the start
			if (!class1.isAnnotationPresent(ApplicationPath.class) && !class1.isAnnotationPresent(Path.class)) {
				System.out.println("-1");
				return -1;
			}
			// Followed by applications
			if (class1.isAnnotationPresent(ApplicationPath.class)) {
				System.out.println("-1");
				return -1;
			}
			// Followed by everything else
			System.out.println("1");
			return 1;
		});

		clazzes.add(String.class);
		clazzes.add(Long.class);
		clazzes.add(Number.class);

		System.out.println("------");
		System.out.println(clazzes.contains(String.class));
	}
```

Output:
```
Compare String with String | 0
Compare Long with String | -1
Compare Number with String | -1
Compare Number with Long | -1
------
Compare String with Long | -1
Compare String with Number | -1
false
```

The contains method have to work. Otherwise there are troubles with the openapi file generation ([example](https://github.com/payara/Payara/blob/37695197d289b1cc2dcf5750aa47682e38305e41/appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java#L1030))

**Comment by rdebusscher** [comment]
Hi @Berger1994,

I have created the internal issue `CUSTCOM-197` to track the verification, tests and inclusion of your request into a release.

Thank you for reporting this.

Thank you @Pscheidl for the PR.

Regards
Rudy.
