### ISSUE TITLE
Memory Leak in Payara 4.1.2.191 due to JDK-8168469

### ISSUE THREAD

**Issue by sterlp** [payara/Payara#4513]
# Description #
----------

Is Payara version 4.1.2.191 affected by the memory leak issue in the OpenJDK https://bugs.openjdk.java.net/browse/JDK-8168469?

## Expected Outcome

Not affected. Could you please provide the link to the branch to verify this?

## Current Outcome

Currently we see after the update using SSL the following memory footprint:

![image](https://user-images.githubusercontent.com/774984/74819255-618da680-5300-11ea-8a7b-de55e29053f3.png)

![image](https://user-images.githubusercontent.com/774984/74819270-694d4b00-5300-11ea-86b8-09bd5a1742a6.png)

Native Leak detected based on dynaTrace:
![image](https://user-images.githubusercontent.com/774984/74819594-eed0fb00-5300-11ea-8121-4c3410439c0d.png)

### Samples

Older version without OpenJDK seemed to be okay.

## Context (Optional)

Update to the most recent Payara 4 and OpenJDK

## Environment ##

- **Payara Version**: Payara Server  4.1.2.191.8 #badassfish (build 276)
- **Edition**: Full
- **JDK Version**: OpenJDK 64-Bit Server VM 25.232-b18 1.8.0_232
- **Operating System**: Linux 3.10.0-957.21.3.el7.x86_64 x86_64
- OpenSSL version ............. OpenSSL 1.0.2j  26 Sep 2016
- **Platform**: Linux 3.10.0-957.21.3.el7.x86_64, amd64

**Comment by rdebusscher** [comment]
Hi @sterlp,

Payara 4.1.2.191.8 is a customer only edition, so can you open this request through the Customer Support Channels?

Thank you
Rudy

**Comment by sterlp** [comment]
The problem is, that we don't have the source code // I raised the ticket.

**Comment by rdebusscher** [comment]
What I mean is that since this is related to a Customer only version of Payara, the issue must be reported through the Payara Support http://support.payara.fish.

**Comment by sterlp** [comment]
If somebody find this issue: Based on our load test a rollback to:

- Payara Version: 4.1.2.191.5
- OpenJDK Version 1.8.0_221

fixed the issue.

![image](https://user-images.githubusercontent.com/774984/75421968-ccac2e00-593b-11ea-9393-c54e5f1884fc.png)
