### ISSUE TITLE
Payara Server Issue

### ISSUE THREAD

**Issue by YiannisKar** [payara/Payara#4527]
[server.log](https://github.com/payara/Payara/files/4231028/server.log)
Hi, 

Could someone review my logs file and help me to understand the problem with Payara server.I installed it on netbeans 11 but i can't run it .

Thanks

**Comment by rdebusscher** [comment]
Hi,

I see the following message in the log

>  Shutting down server due to startup exception
java.net.BindException: Address already in use: bind

So there is already another process bound to one of the ports Payara needs.

This type of questions are better sent to the Payara Forum https://groups.google.com/forum/#!forum/payara-forum

Regards
Rudy

**Comment by chrjohn** [comment]
```
Shutting down server due to startup exception
java.net.BindException: Address already in use: bind
```

There already is another process listening on one of the ports that Payara is using. Check if you still have an instance running somewhere.
