### ISSUE TITLE
Error when trying to log in to the management console PAYARA 5.201

### ISSUE THREAD

**Issue by Crocetti** [payara/Payara#4544]
# Description #
----------
PAYARA VERSION 5.201 
Error when trying to log in to the management console

GET http://localhost:4848/theme/META-INF/com_sun_faces_ajax.js net::ERR_ABORTED 404 (Not Found)

infinit loop

## Expected Outcome

Enter the administrative console

## Current Outcome

infinit loop

## Steps to reproduce (Only for bug reports) 
http://localhost:4848

## Environment ##

- **Payara Version**: 5.201
- **JDK Version**: 1.8.0_231-b11
- **Operating System**: Windows 10
- Browse: Google Chrome Versão 80.0.3987.122 (Versão oficial) 64 bits
not user admin

**Comment by rdebusscher** [comment]
Hi,

When you upgrade from one version to another version, there are situations where you have to remove the cookies linked to the hostname (localhost in your case).

This is especially the case when you used the secure admin option before (Browsers doesn't allow the application to remove cookies using an HTTP call when cookies were set using https)

So clear all cookies and local data for localhost in the browser and try again.

Regards
Rudy
