### ISSUE TITLE
Rolling application upgrades - Anybody had any success?

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#455]
I am struggling to get rolling app upgrades working with Payara (and GlassFish)
but hitting a snag after snag.
Has anyone successfully gotten rolling upgrades to work?

What do I mean by rolling upgrades?
- Apache load-balancer (example) front-end with AJP links to Payara
- Clustering environment, where one node failure results in no visible downtime
- Application upgrades do not result in downtime or session loss

In my understanding, this is what's required:
- Versioned application deployment to a cluster
- instances are removed from the cluster, upgraded, and re-enable on the cluster on-by-one
- as versions get upgraded, session flows from one Payara instance to another, thus users don't notice and their session doesn't get lost

Here are some problems that I encountered so far:
- Session loss.  When upgrading all servers one-by-one, the session gets lost,
even when upgrading to the exact same WAR file, just with a different version.
This is with stock GF, haven't tried it on Payara with Hazelcast-based clustering
- EclipseLink errors such as "cannot cast com.my.Entity to com.my.Entity" after upgrades,
indicating some class loading issues with the in-place versioned upgrades
- ManagedEexcutor and Batch APIs don't work in versioned applications
- There is generally poor stability with enabling different versions of an app on an individual
cluster instance.

So my question is: Has anybody out there got the rolling upgrades to work?
If not this way I described above, Has anybody had success with rolling upgrades in JavaEE, no matter how specifically it's done?  And if yes, can you describe it?

**Comment by smillidge** [comment]
Some understanding of the use case would be useful as the same thing can be achieved in different ways. Some using versioned applications. Some with standalone-instances and hazelcast based session clustering.

If you could split out into multiple issues it is easier to manage for us within the development context.

Couple of comments;
1) You shouldn't lose session state when deploying versioned applications by default. However before determining why this happen you need to confirm that the session is replicating correctly across the cluster in the first place. Sometimes there is non-serializable data in a session which prevents cluster replication from working.

2) You mention removing instances from the cluster could you elaborate what that means. Taking a server out the cluster could lose all the session state.

3) It would be useful to have the Eclipselink error as a separate issue. If JPA objects are being retained in the session and then reaccessed then I could envisage this problem as on redeployment the classloader will change so a cast between two objects of the same class but loaded from different classloaders could cause this error

4) For each ManagedExectuor and JBatch error it would be good to have separate issues created so we can investigate.

**Comment by lprimak** [comment]
Thanks for looking at this, Steve.

The use case is very simple: allow for a single Payara/GF cluster to be up 100% of the time.  No downtime for node failures, no downtime or session loss for application upgrades.
I know there is "blue/green" deployment but that's not what I want because it basically substitutes one cluster for another, thus guaranteeing session loss during upgrades.  Also, blue/green deployment requires doubling of the resources during upgrades, because it requires maintenance of both "green" and "blue" cluster.

1) I worked very hard to make sure that everything is serializable and session state is replicated properly.  This has been working for years, and has survived multiple node failures in production without session loss.  This is not an issue.
The only time session loss becomes an issue is when doing rolling upgrades.

2) I just mean to remove it from load balancer / make it inaccessible to the LB, something like this:  
asadmin set instance_name.network-config.network-listeners.network-listener.ajp-listener-1.enabled=false

3) & 4)
Yes, it would be good to do this as separate issues, but before we go down this rabbit hold, I just want to know if someone has successfully implement this.  I have a funny feeling that there a lots, and lots of issues remaining to be discovered, and I really don't want to go a "new" rabbit hole before discovering a simpler / better way of doing rolling upgrades that someone has done before, something I have perhaps missed.

**Comment by lprimak** [comment]
more on 2)
This is done so during the app upgrade, the users don't get sporadic "page not found" errors while the application is underplayed

**Comment by smillidge** [comment]
I would look at the Payara Hazelcast based clustering. You can do blue green upgrades without session loss as the cluster is elastic. As long as the Hazelcast configuration for each instance is identical then they can join the "cluster" for web session purposes. You can even just add additional Hazelcast JVMs to hold session state.

If you are taking the node out the cluster loadbalancer you can just undeploy, restart and deploy without the need for application versioning and you should not lose session state with the Hazelcast clustering. 

Check out this video which demonstrates some of the resilience of the Hazelcast Session clustering.  While not a rolling restart it actually restarts all the cluster nodes without losing session persistence. https://www.youtube.com/watch?v=idifKBUhOsI

**Comment by lprimak** [comment]
Thanks, I will check out the Hazelcast-based clustering.
Seems like that has a good chance of working correctly.
Do you know of existing, working installations that do this?
I can't believe I am the first person that's trying to do this.
Any C2B2 customers using something like this successfully in production, for example?

**Comment by smillidge** [comment]
We have customers in production on the Hazelcast clustering.

**Comment by lprimak** [comment]
Great. 
And are they achieving rolling application upgrades without loss in availability or session loss?

**Comment by smillidge** [comment]
We'd need to check on that individually.

**Comment by ratcashdev** [comment]
I am using rolling upgrades without clustering with Payara 4.1.153. The results are quite ok, but not perfect. I have experienced the problem with ManagedExecutors with versions below 4.1.153 (see #438 ), but not with this one. However, during the execution of "asadmin enable myapp:1.2" the server returns 404 for some requests, which is not what I would expect.
In addition, monitoring is not able to work with versioned apps, it seems. See the attachment.
![monitoring_with_versions](https://cloud.githubusercontent.com/assets/2928922/10157381/ecda20b4-6689-11e5-97d1-39a097241d1c.JPG)

**Comment by lprimak** [comment]
Looks like there are very many issues with versioned applications,
and it's a seldom-used feature that it's not on radar and not being actively tested by anybody.
From what I've gathered with Steve's help (Thank you!) is that a better way to go wither standalone instances with Hazelcast or blue/green upgrades (also with Hazelcast) sessions.

**Comment by ratcashdev** [comment]
Does hazelcast still replicate session data even if standalone instanced are used, or we're supposed to put the data that are important into Hazelcast manually?
PS: I will open a separate issue for the monitoring problem above

**Comment by lprimak** [comment]
Yes it does, as long as the hazelcast MCast IP and port are the same.

There are many, many issues with versioned apps;
- monitoring (as you said)
- Batch / ExecutorSerivce
- most admin console functions don't work with verisioned apps,
who knows what else?

**Comment by phillipross** [comment]
App versioning was a great idea, but it seemed to have never been fully implemented/supported.
It would be a great feature to be have implemented/fixed/supported though. :+1:

**Comment by lprimak** [comment]
Indeed, Phillip,

However, it seems like a pretty big project to me.

**Comment by realityforge** [comment]
@lprimak There are many many many many other things that are either broken or different when using app versioning. Most of them seem in someway related to JNDI naming and defaults. 

We had significant problems using SOAP services, Singleton annotated services were bound to different urls based on whether the app was versioned or not. Jaxrs also had differences around handling of filters IIRC. Injection of resources was inconsistently handled - I believe due to differences in underlying JNDI names - such that sometimes the only way was to manually scan JNDI for candidate locations of resources and eliminate use of @Inject annotation and @EJB - most were painful to track down as we tended to only use versioned applications when we deployed to UAT or higher environments.

While it may have been a good idea I think it really should be removed as it never really worked and must be a large source of failures for new users.

**Comment by lprimak** [comment]
Man, I wish I would have these comments when I was starting to work on this stuff!
Hopefully this thread will be useful to someone in the future before they start going down this rabbit hole.

**Comment by dmatej** [comment]
We use cluster with dynamic reconfiguration turned off. Redeploy is done in the following steps:
0) Warn users about risk of outage and give them some time estimation
1) backup-domain
2) Run SQL scripts (schemas must be compatible with older app version)
3) Redeploy ear
4) Loadbalancing off for instance1
5) Restart instance1 with --sync=full or normal (it depends ...)
6) Loadbalancing on for instance1 and off for another instance ...
etc.
This works mostly without a session loss (but it is not guaranteed). After the restart of all instances everything works. Reverting changes is possible - from the backup, the only remaining problem are SQL scripts :-)
Upgrade is completed in 30 minutes on SPARC T5200 and in 4 minutes on Intel Xeon.

I did not try rolling updates because we still have some problems with redeploys generally.
- ClassCastException (did not see some time ...)
- Closed EntityManagerFactory (JTA) (fatal, restarting after redeploy always fixes the problem)
- Inconsistent Module State (clustered domain on slow multicore T5200 SPARC)(perhaps fixed in 4.1.1.154)
- starting instance hangs in 4.1.1.154 (now investigating why, only on cluster, restarting does not help)

**Comment by lprimak** [comment]
How do you turn off load balancing for a particular instance?
We have AWS ELB talking to 3 apache servers talking to the cluster instances via mod_prody_balancer/AJP,
and haven't found a way to disable a specific instances in Apache automatically.

**Comment by lprimak** [comment]
Success!
After weeks and weeks or debugging and sleepless nights, I finally achieved rolling upgrades without session loss.

Quick summary:
- Payara with Hazelcast clustering enabled
- Stand-alone instances
- Patched version of Weld - see https://issues.jboss.org/browse/WELD-2064
- override unique_id for EJBs on deploy 

Example: asadmin deploy --availabilityenabled --property org.glassfish.ejb.container.application_unique_id=3604480 --contextroot my app --target inst1 --name my-website..2015-10-10-prod 

I will elaborate more on this shortly.

**Comment by lprimak** [comment]
Here is a pull request for the Weld patch: https://github.com/weld/core/pull/1211

**Comment by lprimak** [comment]
Commit for Weld 2.2.16.Final (the version used tor latest Payara release is here)
https://github.com/flowlogix/core/commit/0ef9ea071008addd2ce822db237e6efb2accf3e7

**Comment by ratcashdev** [comment]
Impressive progress, lprimark. 
However, wound't it be better to define the delimiter as ':' (instead of the ..) for WELD so that the delimiter is in line with the version delimiter for Glassfish?

**Comment by lprimak** [comment]
The reason you have to use a different delimiter is that forces you to use GF application versioning, which is severely broken in GlassFish and Payara.  See some comments above, but the whole point is not to use application versioning but still get clustering and rolling upgrades while preserving sessions.

**Comment by lprimak** [comment]
Here are the latest patches to the current Payara to facilitate rolling upgrades:
Weld:
https://github.com/flowlogix/weld-core/tree/rolling-upgrade-patch-2.2.16
Payara: https://github.com/payara/Payara/pull/602

**Comment by ratcashdev** [comment]
@lprimak have a look on #702 and the linked pull request. I think that together with the already resolved tickets (#270, #433, #436 and #438) we're quite close in getting versioned apps work as intended.
For the last 6 months, i haven't had a problem with ManagedExecutors. Monitoring/Management in the GUI is fixed with #702. So the only 2 outstanding issues would be the problem with JBatch (which I don't have a test-case for) and the lost requests (this issue). I was wondering, if you could check these two, and, especially consider amending the patch so that it's using the original delimiter (the colon) for version in WELD. That would complete the picture, I guess.

**Comment by lprimak** [comment]
@ratcashdev I see that you (along with the Payara team) have done a lot of work to get this working better that it ever has.  That's fantastic.  

However, think there are a lot more than the aforementioned 2 remaining errors.
Perhaps most problems would be fixed with he 2 remaining problems, perhaps not, I am not sure.
If you read some of the earlier comments in this ticket, there are also problems with JNDI, timers, SOAP, ClassCastException with JPA, etc.

I can add another potential problem, which is the uniqueId: 
`--property org.glassfish.ejb.container.application_unique_id=3604480`
I am not sure if the EJB unique IDs work with the versioned apps, but perhaps the above command line snipped also needs to be added to deployment command.

I am very satisfied how Hazelcast-based clustering with standalone instances works in production, so my suggested course of action is to go with that setup.

**Comment by ratcashdev** [comment]
Some steps (or test cases) to reproduce those problems would be appreciated. Thing is, JNDI, TIMERS and JPA, Singletons and JAX-RS all works for me. To be more precise: they started working since 4.1.153. If there are corner cases where they don't, I'd love to see them.

**Comment by lprimak** [comment]
As I mentioned before, Hazelcast clustering with standalone instances works wonders for me.
Other issues are a compilation from multiple sources, and it would be quite a big project to take that on,
and it would have to fit into my work schedule, as you can understand.

**Comment by lprimak** [comment]
PR #1290 fixes a lot of session replication issues

**Comment by lprimak** [comment]
@ratcashdev @realityforge @phillipross I have tested all of the above issues with the upcoming Payara .171 version, and they all work now.  It's amazing how far this has come.
With .171, and some more enhancements that will go into the upcoming .172 version,
rolling upgrades will be an easy reality, even with versioned applications!

**Comment by ratcashdev** [comment]
so is there a particular nightly I could take to do my own independent tests?

**Comment by lprimak** [comment]
@ratcashdev http://www.payara.fish/upstream_builds

**Comment by ratcashdev** [comment]
Created a test project/harness. Using 4.1.1.171-SNAPSHOT #badassfish (build 116) I am still getting a lot of requests resulting in 404, 503 responses.
Test and usage here: https://github.com/ratcashdev/rolling-update-test

**Comment by lprimak** [comment]
Sounds like a bug in your test harness.
Has this program succeeded on any version of Payara, (or WildFly or Liberty Profile?)
I would suggest that you get it to work correctly on some app server, and see if it breaks in Payara in version application mode then.

**Comment by ratcashdev** [comment]
Will see about the bug and report back. However, the 404 and 503 responses in SYNC mode are definitely caused by the rolling update.

**Comment by lprimak** [comment]
I think you have to turn off the load balancing to the node that's being upgraded, while it's being upgraded, that's how I do it in production environments.  I think that's why you are getting 404 and 503 errors

**Comment by ratcashdev** [comment]
It's a stock payaradomain config, no changes, one node only. No clustering set up.

**Comment by ratcashdev** [comment]
Exception during async exception is now fixed. Since you mentioned clustering, you made me re-read the docs. Up until now, for whatever reason, I thought that rolling upgrade on a single, standalone node (no cluster) would yield: 
1. no lost requests, and
2. no lost sessions

This may have been a little too much to expect, however, this was my original objective.
In cases, where there is a sophisticated infrastructure available with a load-balancer and multiple app nodes, blue-green deployment already fulfills No2 and No1 was not a big issue for well designed apps employing Hazelcast).

Achieving No1 and No2 with just a single app-server  (no LB involved) would be a killer feature for those on the budget - hence my original interest.

**Comment by ratcashdev** [comment]
With the updated test project I can report the following:
1. lots of lost requests during `asadmin enable app:2`
2. lost session data. The value inside `sessionHolder` is lost on version upgrade.

**Comment by lprimak** [comment]
Yes, you cannot achieve this with one node,
however, you can achieve this with 2 nodes.
Blue/green doesn't fulfill the request because you would have to duplicate all your nodes, and can't upgrade them one-by-one.

Please see this blog:
http://blog.payara.fish/payara-server-rolling-upgrades

I'll be coming up with many simplification and improvements in the coming months as well
