### ISSUE TITLE
Better Certificate Management in Payara Server Administration Console

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4553]
# Description #
----------
Currently keystores within Payara need to be managed with keytool and as customers and operators are not that familiar with keytool, as it is a very low level utility, Payara should provide certificate management capabilities from within the management console.

Functionality that could be required;

- Removal of expired certificates via one click
- Browse the keystores within the console
- Delete selected certificates
- Add a certificate via cutting and pasting the certificate file text
- Add certificates in comment certificate formats

Management of certificates in the keystore would include management of both trust store and key store.

**Comment by smillidge** [comment]
Current features entering design
A set of asadmin commands for creating self-signed certificates and storing them in the Payara key & trust store.

Asadmin commands for adding / removing keys to the key & trust stores and warn of restarts being required.

Asadmin command to remove all expired certificates from the trust store.

Extensions:

    Automatically replace expired self-signed certificates
    Admin console User interface to view certificates in the store and CRUD
    asadmin command to copy JDK trust store certs into the Payara trust store.
    Better integration with Let's Encrypt.

**Comment by anowac01** [comment]
> Asadmin command to remove all expired certificates from the trust store.

It would be nice to have an asadmin command (or an option on this one) to remove _all_ the certificates (except for Payara's own self-signed certificates) from the truststore.   

My usecase is that I have domains that are only expected to connect to hosts using a specific internal CA, so I want to only trust that CA.

**Comment by smillidge** [comment]
Support for latest keystore types in the JDKs will also be added.
