### ISSUE TITLE
Optimised Docker Images for Payara Micro

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4554]
# Description #
----------

Currently our Payara Micro images are pretty simple. There are a number if things we can do optimise images including work on the core Payara Micro runtime.

Provide capabilities to "bake" an image including

- Preexpanded runtime environment
- Deployed application 
- Micro runtime configuration including post boot and preboot configuration
- Warmed up Class Data Sharing

**Comment by CarlosMOGoncalves** [comment]
I agree with this, the Payara Micro image should be expanded to allow for better configuration, at the very least similar to what is possible with the server. As it is today, either custom images built on top of Payara Micro will need a lot of configurations themselves or the temptation will be very strong to just load a JDK image and run the uber jar created by Micro.

**Comment by ejba** [comment]
Regarding "Micro runtime configuration including post boot and preboot configuration" improvement, I think that an example in the image's documentation would be enough. 

```
FROM payara/micro:5.201

ENV COMMANDS_DIR="/opt/payara/commands/"
ENV DEPLOY_DIR="/opt/payara/deployments"

COPY prepare-resources.txt ${COMMANDS_DIR}/preboot-command-file.txt
COPY ready-production-use.txt ${COMMANDS_DIR}/postboot-command-file.txt
COPY post-process-apps.txt ${COMMANDS_DIR}/postdeploy-command-file.txt

COPY target/ROOT.war "${DEPLOY_DIR}"

CMD ["--nocluster", \
"--deploymentDir", "/opt/payara/deployments",\
"--prebootcommandfile", "/opt/payara/commands/preboot-command-file.txt",\
"--postbootcommandfile", "/opt/payara/commands/postboot-command-file.txt",\
"--postdeploycommandfile", "/opt/payara/commands/postdeploy-command-file.txt"]
```

**Comment by smillidge** [comment]
Some  of this was released in 201 see https://blog.payara.fish/warming-up-payara-micro-container-images-in-5.201 although documentation needs to be better

**Comment by Herr-Sepp** [comment]
Please also consider revising the tag names. It's really a mess with the JVM and Payara versions right now.

See https://github.com/payara/Payara/issues/4733
