### ISSUE TITLE
Evaluate enhancing HK2 to be a full CDI implementation

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4558]
# Description #
----------
Evaluate enhancing HK2 to make it a full CDI implementation. This will enable the removal of Weld as the CDI implementation. This is envisaged to have benefits in speed of deployments and server footprint and performance. 

Initial focus on CDI lite initiatives and exploring potential of HK2 supporting AOT and GraalVM

**Comment by lprimak** [comment]
I would go the other way. Remove HK2 in favor of Weld completely. Not sure but RH probably will have build-time optimization and other improvements that are part of Quarkus that can be useful here

**Comment by CarlosMOGoncalves** [comment]
I see value in this feature for two reasons:
1 - Since HK2 is used as core in Payara, a progression towards full CDI implementation would surely relieve the overlapping usage of Weld, while hopefully keeping existing applications running without changes or with minimal ones.
2 - A competing implementation of a spec is always a good thing for the evolution of technology in general and Jakarta EE in particular.

**Comment by anthonyvdotbe** [comment]
@lprimak Quarkus doesn't use Weld, but a new, partial implementation of CDI called [ArC](https://github.com/quarkusio/quarkus/tree/master/independent-projects/arc)

**Comment by lprimak** [comment]
> @lprimak Quarkus doesn't use Weld, but a new, partial implementation of CDI called [ArC](https://github.com/quarkusio/quarkus/tree/master/independent-projects/arc)

Doubt it's brand new. Probably copy/paste relevant bits

**Comment by lprimak** [comment]
> I see value in this feature for two reasons:
> 1 - Since HK2 is used as core in Payara, a progression towards full CDI implementation would surely relieve the overlapping usage of Weld, while hopefully keeping existing applications running without changes or with minimal ones.
> 2 - A competing implementation of a spec is always a good thing for the evolution of technology in general and Jakarta EE in particular.

the issue is whether it's a good use of limited resources.

**Comment by smillidge** [comment]
Closing as will be reevaluated as part of our core Profile solution but will not make it into Payara 6
