### ISSUE TITLE
Approach to Jakarta EE 9 Support

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4565]
# Description #
----------
Payara platform will support Jakarta EE 9. 
Jakarta EE 9 bring in breaking changes in application apis.
This issue is to explore how we support Jakarta EE 9 in the Payara platform and whether we provide;
- direct backwards compatibility with old applications
- migration tooling for old applications
- dedicated runtime for Jakarta EE 9 applications and Jakarta EE 8 applications

**Comment by lprimak** [comment]
There ought to be away to rename packages at deploy time to support both packages seamlessly
