### ISSUE TITLE
Generated MP OpenAPI YAML contains duplicate tags /CUSTCOM-228

### ISSUE THREAD

**Issue by besza** [payara/Payara#4571]
# Description #
----------

Using the Microprofile OpenAPI `@Tag` annotation on a JAX-RS resource (class level) causes the generated OpenAPI document to contain duplicate tags.

## Expected Outcome

There should not be duplicates of the same tag in the OpenAPI document.

## Current Outcome

The generated OpenAPI document contains duplicate tags.  

## Steps to reproduce (Only for bug reports) 

Reproducer application is provided at [https://github.com/besza/payara-mp-openapi](https://github.com/besza/payara-mp-openapi).
## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full and Micro
- **JDK Version**: 1.8.0_241 Oracle
- **Operating System**: Windows
- **Database**: none

**Comment by rdebusscher** [comment]
Hi,

When the `@Tag` is used on the class and not on the method, it is indeed correct that the tag information is duplicated in the OpenAPI document.

Thanks for reporting this and I have created the internal issue `CUSTCOM-228` to solve this.

Regards
Rudy

**Comment by LarsBrenker** [comment]
@rdebusscher If I write @Tag with the same name in several methods, the Open API document also contains duplicate tags. Same mistake? Or is it different with methods?

**Comment by smillidge** [comment]
Fixed by https://github.com/payara/Payara/pull/4765
