### ISSUE TITLE
Making Clustered Singleton working as documented with Payara Micro Cluster /FISH-40

### ISSUE THREAD

**Issue by Andrew-Gr** [payara/Payara#4572]
# Description #
----------
I am trying to make use of [`@Clustered`](https://docs.payara.fish/documentation/payara-server/public-api/clustered-singleton.html) annotation with `@EJB` or `@ApplicationScoped` beans but in a vain. Can you please advise on this or update Examples Project so it can be more clear how to implement `@Clustered` feature in a cluster?

My test scenarios are based on the [Payara Clustered Singleton examples](https://github.com/payara/Payara-Examples/tree/master/javaee/clustered-singleton).
For all test scenarios:
1) I only add the class `SchedulerTest` as shown below
2) Build the project
3) Launching it as (on the same machine):
i) `java -jar payara-micro-5.201.jar --deploy d:\_2\Payara-Examples\javaee\clustered-singleton\target\clustered-singleton-1.0-SNAPSHOT.war --name i1 --port 8091`
ii) `java -jar payara-micro-5.201.jar --deploy d:\_2\Payara-Examples\javaee\clustered-singleton\target\clustered-singleton-1.0-SNAPSHOT.war --name i2 --port 8092`

I have prepared several test scenarios, will start with one of them:

## Code
```
@Clustered(callPostConstructOnAttach = false)
@Singleton
public class SchedulerTest implements Serializable {

    private Set<String> _eventHistoryList;

    @PostConstruct
    protected void init() {
        System.out.println(">>> INIT...");
        _eventHistoryList = new HashSet();
    }

    @Schedule(second = "*/5", minute = "*", hour = "*", info = "testSched1", persistent = true)
    public void testSched1() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd-HHmmss");
        String jobId = sdf.format(new Date());
        System.out.println(">> " + getEventHistoryList());
        if (!getEventHistoryList().contains(jobId)) {
            getEventHistoryList().add(jobId);
            System.out.println(">>>>> executing jobId: " + jobId);
        }
    }

    public Set<String> getEventHistoryList() {
        return _eventHistoryList;
    }
}
```

## Expected Outcome

According to the documentation:
> Persistent EJB Timers (which are the default) will work correctly with clustered singletons since they will only be executed in a single node of the cluster

It is expected that method `testSched1()` is to be executed only on one node in the cluster. Because that didn't happen - I have tried to add some manual synchronization, but that didn't help much as well.

## Current Outcome

Timer is executed on both cluster nodes. Also added manual sync doesn't help as well.
![test1](https://user-images.githubusercontent.com/16522951/76704625-3dfa2800-6715-11ea-8c51-34d8fea0358f.jpg)

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Micro
- **JDK Version**: Zulu 8.44.0.11-CA-win64
- **Operating System**:  Windows 10 x64 and Linux CentOS 7/8

**Comment by rdebusscher** [comment]
Hi Andrew,

I can confirm that the Persistent Timer feature no longer works on Payara Micro as indicated. I have created the issue `CUSTCOM-242` to fix this in a future version.

Thanks for reporting this issue.

Regards
Rudy.
