### ISSUE TITLE
@PreDestroy is not called on EJB in Payara Micro (is it by design or not?)

### ISSUE THREAD

**Issue by Andrew-Gr** [payara/Payara#4573]
# Description #
----------
`@PostConstruct` is called fine on the `@Startup` `@Singleton` EJB, but `@PreDestroy` is not called at all in the WAR-app deployed on the Payara Micro (when stopping by pressing Ctrl+C in CMD console).
Sample code snippet below:
```
@Startup
@Singleton
public class TestEjb {

    @PostConstruct
    public void init() {
        System.out.println(">> INIT TEST EJB");
    }

    @PreDestroy
    public void destroy() {
        System.out.println(">> DESTROY TEST EJB");
    }

}
```
## Workaround
[Workaround was found on the StackOverflow by using `@WebListener`.](https://stackoverflow.com/questions/60381558/payaramicro-does-not-call-predestroy-on-ejb-or-applicationscoped).
Looks like it works fine, but it means that some refactoring is to be done in order to move code from EJB's `@PreDestroy` methods to `@WebListener`'s `contextDestroyed` method (in case it will be confirmed that `@PreDestroy` should not be called in Payara Micro by design).

## Expected Outcome
`System.out.println(">> DESTROY TEST EJB");` to be triggered when stopping Payara Micro (by sending Ctrl+C).

## Current Outcome
`System.out.println(">> DESTROY TEST EJB");` is not triggered when stopping Payara Micro (by sending Ctrl+C).

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Micro
- **JDK Version**: Zulu 8.44.0.11-CA-win64
- **Operating System**: Windows 10 / Linux CentOS 7&8

**Comment by rdebusscher** [comment]
Hi Andrew,

I can confirm that @Predestroy isn't called. It is not intended by design but just a side effect of the fact that Payara Micro is just stopped and not undeploying the application (which triggers the predestroy call for EJB and CDI)

We can consider this feature in the Payara Enterprise product but have no short term plans for including this in the community product.

Regards
Rudy
