### ISSUE TITLE
Classes not found in exploded artifact when artifact is inside NTFS junction

### ISSUE THREAD

**Issue by CrazyCoder** [payara/Payara#4575]
Original report: https://youtrack.jetbrains.com/issue/IDEA-235358
Sample artifact: [exploded.zip](https://youtrack.jetbrains.com/api/files/74-818581?sign=MTU4NDY2MjQwMDAwMHwxMS0yMjN8NzQtODE4NTgxfEYwUUx2VVhxTU1LUXU3c0REa1o5am1EbmE3%0D%0AejRtdmpISFRrZ1lsVnFFQmsNCg%0D%0A&updated=1584412708115)

STR:

```
d:\dev\payara5\glassfish\bin>asadmin start-domain domain1
Waiting for domain1 to start ........
Successfully started the domain : domain1
domain  Location: D:\dev\payara5\glassfish\domains\domain1
Log File: D:\dev\payara5\glassfish\domains\domain1\logs\server.log
Admin Port: 4848
Command start-domain executed successfully.

d:\dev\payara5\glassfish\bin>asadmin
Use "exit" to exit and "help" for online help.
asadmin> deploy c:/work/attaches/rest-hello/out/artifacts/exploded
Application deployed with name exploded.
Command deploy executed successfully.
```

Expected:

http://localhost:8080/exploded/helloworld works.

Actual:

404, `server.log` contains the following:

```
[2020-03-16T19:35:24.724-0700] [Payara 5.201] [WARNING] [AS-WEB-UTIL-00035] [javax.enterprise.web.util] [tid: _ThreadID=134 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1584412524724] [levelValue: 900] [[
  Unable to load class com.example.HelloWorld, reason: java.lang.ClassNotFoundException: com.example.HelloWorld]]

[2020-03-16T19:35:24.726-0700] [Payara 5.201] [WARNING] [AS-WEB-UTIL-00035] [javax.enterprise.web.util] [tid: _ThreadID=134 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1584412524726] [levelValue: 900] [[
  Unable to load class com.example.MyApplication, reason: java.lang.ClassNotFoundException: com.example.MyApplication]]

[2020-03-16T19:35:24.727-0700] [Payara 5.201] [WARNING] [AS-WEB-UTIL-00035] [javax.enterprise.web.util] [tid: _ThreadID=134 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1584412524727] [levelValue: 900] [[
  Unable to load class com.example.MyApplication, reason: java.lang.ClassNotFoundException: com.example.MyApplication]]
```

If the app is packaged into `.war`, everything works fine, so the issue is specific to exploded artifact format.

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full/Web
- **JDK Version**: Oracle 8u241
- **Operating System**: Windows

**Comment by rdebusscher** [comment]
Hi,

I tried this on my laptop (MAC OS) and it works as expected. It might be a Windows only issue. I'll ask some of my team mates to verify this.

Regards
Rudy

**Comment by rdebusscher** [comment]
WAR in exploded form [exploded.zip](https://github.com/payara/Payara/files/4373975/exploded.zip)

**Comment by rdebusscher** [comment]
Hi,

2 of my colleagues with a Windows Machine have tested this and it is working as expected. No message and the Hello World message gets displayed in the browser.

**Comment by CrazyCoder** [comment]
@rdebusscher 

The issue was specific to the folder location. I've confirmed that it works with a normal folder, but fails when it's a directory junction (https://en.wikipedia.org/wiki/NTFS_links).

Could you please check again when `exploded` is a junction?

**Comment by rdebusscher** [comment]
Hi,

The Java File API isn't capable of handling NTFS links (junctions). So there is no easy solution for this except not using them.

We might consider this in the Payara Enterprise product.

Regards
Rudy

**Comment by CrazyCoder** [comment]
Tomcat, IntelliJ IDEA and other servers/apps do not have such issue.
