### ISSUE TITLE
Monitoring on versioned applications

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#461]
Using Payara 4.1.153
Monitoring is not able to work with versioned apps, it seems. See the attachment.
![monitoring_with_versions](https://cloud.githubusercontent.com/assets/2928922/10157381/ecda20b4-6689-11e5-97d1-39a097241d1c.JPG)

In addition while doing the "asadmin enable myapp:1.2" command, the server returns 404 for a number of requests, which is not what I would expect.

**Comment by devyoustice** [comment]
Let's deal with the missing components/monitoring as part of #702 and this issue should focus solely on the lost requests.

**Comment by ratcashdev** [comment]
Let's deal with the missing components/monitoring as part of #702 and this issue should focus solely on the lost requests.

**Comment by smillidge** [comment]
Fixed by #746
