### ISSUE TITLE
BOM missing property jakarta.transaction.cdi-api.version /CUSTCOM-261

### ISSUE THREAD

**Issue by ColdanR** [payara/Payara#4618]
# Description #
----------

Missing property jakarta.transaction.cdi-api.version in BOM
Importing BOM into a maven project with
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-bom</artifactId>
            <version>5.201</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
resulting in effektive POM
```
<dependency>
    <groupId>jakarta.transaction.cdi</groupId>
    <artifactId>jakarta.transaction.cdi-api</artifactId>
    <version>${jakarta.transaction.cdi-api.version}</version>
</dependency>
```
## Expected Outcome

Resolved version on dependency like
```
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
```

## Current Outcome

Property ${jakarta.transaction.cdi-api.version} is not resolved and dependency can not be managed without setting the property.

Please add the property jakarta.transaction.cdi-api.version with the correct version

## Steps to reproduce (Only for bug reports) 

1. Add BOM as managed dependency
2. Resolve to effective POM
3. Search for jakarta.transaction.cdi-api

## Context (Optional)

Currently not affecting myself

## Environment ##

- **Payara Version**: 5.201
- **Edition**: BOM
- **JDK Version**: 11.0.6; OpenJDK 64-Bit Server VM 11.0.6+10-LTS
- **Operating System**: Windows 10
- **Maven Version**: 3.6.3

**Comment by rdebusscher** [comment]
Hi,

Also the `jakarta.transaction.cdi:jakarta.transaction.cdi-api`artifact doesn't seems to exist at all. Only the javax one.

Searching more about this.

Thanks

Regards
Rudy

**Comment by rdebusscher** [comment]
Hi,

As mentioned, the `jakarta.transaction.cdi:jakarta.transaction.cdi-api` artifact doesn't exist and the 'old' javax equivalent contains only `@Transactional` which is available from the Jakarta EE API artifact.

So there is no need to have this dependency and will be removed in the next release.

Thanks for reporting

Regards
Rudy.

**Comment by rdebusscher** [comment]
Part of release 5.2020.2
