### ISSUE TITLE
Client mode debugging (server=no) doesn't work with JDK>=9 /CUSTCOM-264

### ISSUE THREAD

**Issue by CrazyCoder** [payara/Payara#4619]
47ea8c7f1a1eb532a224245bd9c2527ca85907d3 commit breaks client debug mode with IntelliJ IDEA.

This change assumes that Payara will always run in server debug mode and debugger will always listen on wildcard address.

This is not correct as user may want to run with `server=n` and specify the debug server port or `IP:PORT` explicitly which will no longer work with JDK >= 9.

User may also not want to bind on wildcard addresses. This change also makes it impossible to specify the bind address explicitly. Binding on wildcard interface by default is not secure.

More details are [available in YouTrack](https://youtrack.jetbrains.com/issue/IDEA-216528#focus=streamItem-27-4077777.0-0).

While macOS may tolerate `*:PORT` as the valid client address, it doesn't work on Windows.

**Comment by marcreichman** [comment]
This is covered in the linked JetBrains tickets, but just for clarity this bug inhibits the ability to start Glassfish in debug mode with a local server configuration in IntelliJ, for at least Payara 5.201 and possibly one or two back as well. The only workaround is clunky, requiring someone to start the debug server by hand and deploy with a “remote” debug config which makes for a long iteration cycle on debugging build changes.

**Comment by CrazyCoder** [comment]
I would just remove [this fragment](https://github.com/payara/Payara/blob/942a7d54edf6ba6d41421a25b38ac7c3981e8230/nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JavaConfig.java#L143):

```
        if(JDK.getMajor() >= 9
                && debugOptions.contains("address=")
                && !debugOptions.contains("address=*:")){
            debugOptions = debugOptions.replace("address=", "address=*:");
        }
```

**Comment by rdebusscher** [comment]
Part of release 5.2020.2
