### ISSUE TITLE
Payara 5.201 will not start with Amazon Corretto 8.252.09.1 after enable-secure-admin command

### ISSUE THREAD

**Issue by vogeldavid** [payara/Payara#4625]
# Payara 5.201 will not start with Amazon Corretto 8.252.09.1 after enable-secure-admin command #
----------

I can not run Glassfish 5.201 with Amazon Corretto 8.252.09.1 after entering enable-secure-admin command. 

- With openjdk-8u252-b09 or amazon-corretto-8.252 (Amazon Corretto 8.252.09.1) it will not work.
- With zulu-jdk8.0.252, openjdk-8u242 or amazon-corretto-8.242 it works fine.

 

## Expected Outcome

Payara 5.201 starts

## Current Outcome

Payara 5.201 does not start properly

## Steps to reproduce (Only for bug reports) 

Setup:

I have Ubuntu 16.04 lts, then I install openjdk-8u252-b09 and download glassfish server on zip file.

```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

`$unzip payara-5.201.zip`

```

$ payara5/bin/asadmin start-domain
Waiting for domain1 to start ......
Successfully started the domain : domain1
domain  Location: /opt/payara/payara5/glassfish/domains/domain1
Log File: /opt/payara/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
```

Set password for admin user
```
vogel@birdy:/opt/payara$ payara5/bin/asadmin change-admin-password
Enter admin user name [default: admin]>
Enter the admin password> 
Enter the new admin password> 
Enter the new admin password again> 
Command change-admin-password executed successfully.
```

Enable secure admin:
```
$ payara5/bin/asadmin enable-secure-admin
Enter admin user name> admin
Enter admin password for user "admin"> 
You must restart all running servers for the change in secure admin to take effect.
Command enable-secure-admin executed successfully.
```

Restart server will fail:
```
$ payara5/bin/asadmin restart-domain
NCLS-ADMIN-00010
NCLS-ADMIN-00010
...
```

server.log:
```
[2020-04-16T13:56:14.902+0200] [Payara 5.201] [WARNING] [NCLS-JMX-00007] [javax.enterprise.system.jmx] [tid: _ThreadID=124 _ThreadName=Thread-12] [timeMillis: 1587038174902] [levelValue: 900] [[
  Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = true} due to exception java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V]]

[2020-04-16T13:56:14.902+0200] [Payara 5.201] [WARNING] [] [sun.rmi.transport.tcp] [tid: _ThreadID=129 _ThreadName=RMI TCP Accept-8686] [timeMillis: 1587038174902] [levelValue: 900] [[
  RMI TCP Accept-8686: accept loop for [SSL: ServerSocket[addr=/0.0.0.0,localport=8686]] throws
java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V
        at sun.security.ssl.SSLSocketImpl.initHandshaker(SSLSocketImpl.java:1350)
        at sun.security.ssl.SSLSocketImpl.doneConnect(SSLSocketImpl.java:708)
        at sun.security.ssl.SSLServerSocketImpl.accept(SSLServerSocketImpl.java:353)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)
]]

[2020-04-16T13:56:14.907+0200] [Payara 5.201] [SEVERE] [] [] [tid: _ThreadID=129 _ThreadName=RMI TCP Accept-8686] [timeMillis: 1587038174907] [levelValue: 1000] [[
  Exception in thread "RMI TCP Accept-8686" ]]

[2020-04-16T13:56:14.908+0200] [Payara 5.201] [SEVERE] [] [] [tid: _ThreadID=129 _ThreadName=RMI TCP Accept-8686] [timeMillis: 1587038174908] [levelValue: 1000] [[
  java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V
        at sun.security.ssl.SSLSocketImpl.initHandshaker(SSLSocketImpl.java:1350)
        at sun.security.ssl.SSLSocketImpl.doneConnect(SSLSocketImpl.java:708)
        at sun.security.ssl.SSLServerSocketImpl.accept(SSLServerSocketImpl.java:353)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)
]]
```

## Environment ##

- **Payara Version**: 5.201
- **JDK Version**: openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
- **Operating System**: Ubuntu 16.04 lts

same Problem with 

- **JDK Version**:  openjdk version "1.8.0_252"
OpenJDK Runtime Environment Corretto-8.252.09.1 (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM Corretto-8.252.09.1 (build 25.252-b09, mixed mode)

**Comment by OndroMih** [comment]
Hi, @vogeldavid, 

This is an issue cause by a change in the private OpenJDK APIs that Payara Server relies on to provide enhanced TLS encryption required by HTTP/2. This only affects Java 8 because Java provides this enhanced TLS encryption out of the box since Java 9. 

Luckily, the same enhanced TLS encryption was just recently backported to Java 8 and it's present already in OpenJDK 8u252 and Corretto 8.252: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230977. So you can solve this issue by editing your domain.xml file to use the configuration for Grizzly NPN for Java 9 and newer instead of the configuration for Java 8.

To do this, follow these instructions:

* open domain.xml
* find the line `jvm-options>[1.8.0u191|1.8.0u500]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>`
* delete the above line and replace it with the 2 following lines:

```
        <jvm-options>[1.8.0u191|1.8.0u251]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>
        <jvm-options>[1.8.0u252|1.8.0u500]-Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-api.jar</jvm-options>
```

All should then work normally.

**Comment by vogeldavid** [comment]
Hi, @OndroMih 

Thank you very much.
your solution worked perfect for me.

**Comment by johnmanko** [comment]
Worked with Ubuntu 19.10 OpenJDK's package and Payara 5.201:

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~19.10-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by andytechdad** [comment]
@OndroMih Is there a plan to fix this in a payara release rather than hacking domain.xml files?

Thanks
Andy

**Comment by OndroMih** [comment]
Hi @andytechdad,

This is fixed now with #4656 and it will be part of the next release. The solution is basically to adjust the default domain.xml for Corretto 5.252 and OpenJDK 8u252 so that you don't have to hack it yourself. If you upgrade from an older Payara version, you still need to do those adjustments manually.

Good news is that this solution is stable and no later version of Java 8 will break this.

**Comment by gpbonillas** [comment]
> Hi, @vogeldavid,
> 
> This is an issue caused by a change in the private OpenJDK APIs that Payara Server relies on to provide enhanced TLS encryption required by HTTP/2. This only affects Java 8 because Java provides this enhanced TLS encryption out of the box since Java 9.
> 
> Luckily, the same enhanced TLS encryption was just recently backported to Java 8 and it's present already in OpenJDK 8u252 and Corretto 8.252: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230977. So you can solve this issue by editing your domain.xml file to use the configuration for Grizzly NPN for Java 9 and newer instead of the configuration for Java 8.
> 
> To do this, follow these instructions:
> 
> * open domain.xml
> * find the line `jvm-options>[1.8.0u191|1.8.0u500]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>`
> * delete the above line and replace it with the 2 following lines:
> 
> ```
>         <jvm-options>[1.8.0u191|1.8.0u251]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>
>         <jvm-options>[1.8.0u252|1.8.0u500]-Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-api.jar</jvm-options>
> ```
> 
> All should then work normally.

**Comment by gpbonillas** [comment]
> Hi, @vogeldavid,
> 
> This is an issue caused by a change in the private OpenJDK APIs that Payara Server relies on to provide enhanced TLS encryption required by HTTP/2. This only affects Java 8 because Java provides this enhanced TLS encryption out of the box since Java 9.
> 
> Luckily, the same enhanced TLS encryption was just recently backported to Java 8 and it's present already in OpenJDK 8u252 and Corretto 8.252: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230977. So you can solve this issue by editing your domain.xml file to use the configuration for Grizzly NPN for Java 9 and newer instead of the configuration for Java 8.
> 
> To do this, follow these instructions:
> 
> * open domain.xml
> * find the line `jvm-options>[1.8.0u191|1.8.0u500]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>`
> * delete the above line and replace it with the 2 following lines:
> 
> ```
>         <jvm-options>[1.8.0u191|1.8.0u251]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>
>         <jvm-options>[1.8.0u252|1.8.0u500]-Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-api.jar</jvm-options>
> ```
> 
> All should then work normally.

It worked for me. Perfect!. Thank you very much

**Comment by rdebusscher** [comment]
Part of release 5.2020.2
