### ISSUE TITLE
Persiste LocalDateTime with eclipselink 2.7.4 fails when value is null / CUSTCOM-268

### ISSUE THREAD

**Issue by brunogptavares** [payara/Payara#4636]
# Description #

When I try to persist an object with LocalDateTime with a value of null, I get an error.

The postgres column is "timestamp without time zone".

It's a bug in eclipselink:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=535431

## Expected Outcome

Should save the object with null in the field.

It's corrected in version 2.7.6 o eclipselink. 

## Current Outcome

Caused by: org.postgresql.util.PSQLException: ERROR: column "data_sync" is of type timestamp without time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 95
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)

### Samples

https://stackoverflow.com/questions/48658346/java8-localdate-jpa2-2-persisting-to-postgresqls-date-fails-when-localdate-is-n

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: 8 u241 - Oracle
- **Operating System**: Windows 
- **Database**: PostGres 9.6

**Comment by OndroMih** [comment]
Hi, @brunogptavares , according to the EclipseLink issue in bugzilla this is fixed in EclipseLink 2.7.6. Can you try replacing EclipseLink JARs in Payara's modules directory by the EclipseLink 2.7.6 JARs from maven: https://search.maven.org/search?q=g:org.eclipse.persistence ? All EclipseLink modules start with `org.eclipse.persistence`.

Then test if that fixes this problem.

**Comment by OndroMih** [comment]
We'll schedule upgrading to EclipseLink 2.7.6 in the future. Hopefully that will fix this issue.

**Comment by brunogptavares** [comment]
Hi @OndroMih, I replace the EclipseLink JARs and it works. Thanks

**Comment by fturizo** [comment]
Fixed in release *5.2020.2* referenced with the ID `APPSERV-109`
