### ISSUE TITLE
GlassFishProperties throws NPE if the Properties is null.

### ISSUE THREAD

**Issue by andrewhabib** [payara/Payara#4657]
# Description #
----------

The properties class org.glassfish.embeddable.GlassFishProperties could silently be corrupt if initialized with a null Properties object.

## Steps to reproduce (Only for bug reports) 

The following instantiation would not produce any warning...

```
java.util.Properties properties0 = null;
org.glassfish.embeddable.GlassFishProperties glassFishProperties1 = new org.glassfish.embeddable.GlassFishProperties(properties0);
```

However, when you try to use any of the GlassFishProperties, you'd get NullPointerException.
E.g.:
```
glassFishProperties1.setConfigFileURI("path/to/config/file");
```

Therefore, constructors of GlassFishProperties should check for a null Properties object
or at least document the above behavior in the documentation.

**Comment by rdebusscher** [comment]
Hi Andrew,

Do you want to a submit a PR for this improvement? You can find the CLA here : https://github.com/payara/Payara/blob/master/PayaraCLA.pdf.

Regards
Rudy

**Comment by andrewhabib** [comment]
Yes sure. But let's discuss how a fix should handle this case.
I see two different scenarios:

(1) Describe in the documentation that properties should not be null

(2) Or, check for properties being null and produce a warning or throw an NPE 

What do you think?

**Comment by rdebusscher** [comment]
Hi Andrew,

I would check the parameter and throw a IllegalArgumentException (or NullPointerException) and document it in the JavaDoc.

**Comment by bhanuunrivalled** [comment]
Hi , 

I update it . 

Please let me know the feedback .

Thanks,

**Comment by andrewhabib** [comment]
Thanks @bhanuunrivalled ! This looks good to me. 
@rdebusscher I will close the issue now.

**Comment by bhanuunrivalled** [comment]
Thank you @andrewhabib .   I had the similar issue :)
