### ISSUE TITLE
Micronaut war on payara 5 wont work because CDI scanning cant be disable

### ISSUE THREAD

**Issue by kbachl** [payara/Payara#4661]
# Description #
----------

Follow up report to a but originally filed against micronaut-servlet; It seems as payara 5.201 ignores implicit CDI scanning disabling

Steps see here: https://github.com/micronaut-projects/micronaut-servlet/issues/7

tried: 
- beans.xml with bean-discovery-mode="none"
- glassfish-web.xml with
```
<glassfish-web-app>
    <context-root>/</context-root>
    <scanning-exclude>*</scanning-exclude>
</glassfish-web-app>
```
- manually upload via admin console and there unticking the CDI Implicit scanning

## Expected Outcome

dont do any CDI scanning

## Current Outcome

CDI scanning happens, leading to exception

  Exception during lifecycle processing
java.lang.IllegalStateException: The return type of the lifecycle method [stop] must be void. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public io.micronaut.http.client.HttpClient io.micronaut.http.client.DefaultHttpClient.stop()] of type [METHOD]

## Steps to reproduce (Only for bug reports) 

Steps see here: https://github.com/micronaut-projects/micronaut-servlet/issues/7
(micronaut Hello-World project)

## Environment ##

- **Payara Version**: Payara Server 5.201 #badassfish (build 512)
- **Edition**: Full
- **JDK Version**:  OpenJDK 64-Bit Server VM Vendor: Private Build Version: 25.252-b09
- **Operating System**: ubuntu 18.04 lts
- **Database**: none

**Comment by rdebusscher** [comment]
Hi @kbachl,

The exception is not thrown by the CDI scanning when it creates the CDI bean definitions but by the deployment validator. There is a check if the WAR you want to deploy is actually a valid artifact. This check can't be disabled for the moment.

I see also other issues with the generated WAR file as it contains several Java EE dependencies like Servlet API, CDI API, etc ...  These shouldn't be included in the WAR file.

So the Micronaut support for WAR files and deployment on application server has issues.

**Comment by graemerocher** [comment]
There are no issues with Micronaut's WAR support. Micronaut supports both WAR deployment and runnable JAR execution. It is down to the user to switch the dependencies from `compile` scoped to `provided` scope in their build configuration when they switch from runnable JAR to WAR deployment, this is the same approach as Spring Boot and many other frameworks use.

The example application has not switched the dependencies to `provided` hence why they are included in the WAR when they shouldn't be.

Micronaut deploys fine to the most popular Servlet containers such as Tomcat, and Jetty so I have no idea why Payara is validating something that it shouldn't be validating but if it is and there is no way to disable it that is a Payara issue.

**Comment by OndroMih** [comment]
It's true that Payara Server could just ignore Micronaut methods with `@PreDestroy` because they're not methods of any EJB or CDI bean. However, if it can be easily fixed by removing the Micronaut JARs that are not intended for WAR deployment as @graemerocher suggests, it's bettor to follow his advice and remove them from your WAR, @kbachl.

Payara Server is only validating what's mandated by Java SE, see the Javadoc for `@PreDestroy` - https://docs.oracle.com/javase/10/docs/api/javax/annotation/PreDestroy.html. Currently it doesn't skip any method, even if CDI scanning is disabled. The method `io.micronaut.http.client.DefaultHttpClient.stop()` with `@PreDestroy` annotation fails the following rule and thus fails the deployment:

> The method defined on a non-interceptor class MUST HAVE the following signature:
> * void \<METHOD\>\(\)

**Comment by graemerocher** [comment]
Note that I am unsure it is possible to remove `javax.annotation` as it is not strictly part of CDI and Micronaut doesn't support CDI anyway. It supports only `javax.inject`

**Comment by smillidge** [comment]
@graemerocher  Looks like PreDestroy would be more compliant on close rather than stop on the DefaultHttpClient class as close just calls through to stop but has the correct signature.

**Comment by graemerocher** [comment]
Ok. this code has changed substantially on the `master` branch and no longer features that annotation on that method so I am not sure this would be an issue with Micronaut 2.x

**Comment by kbachl** [comment]
thank you all for looking into this
@graemerocher would it be ok to open up an issue specifically to have micronaut 2 compatible with payara server? We use payara on one server and would like to be able to deploy to it a micronaut app at a later time with micronaut 2 since we use micronaut as our new base technology layer for decoupled services... 

@OndroMih I now know that the war has things in it that shouldn't be, but to be fair: even that shouldn't break a deploy, should it?

**Comment by graemerocher** [comment]
@kbachl yes please go ahead. Servlet support can be found here https://github.com/micronaut-projects/micronaut-servlet/issues

**Comment by rdebusscher** [comment]
Closing as there is a PR in the Micronaut project to fix this issue. https://github.com/micronaut-projects/micronaut-core/commit/3aec28169eb463f276d37669e2d7ccbe2fd67b27
