### ISSUE TITLE
Injecting (@Inject) fails inside entity listeners when called from the context of an EJB @Startup bean

### ISSUE THREAD

**Issue by adam-waldenberg** [payara/Payara#4662]
# Description #
----------
Injecting a managed bean with `@Inject` fails inside any entity listeners registered with `@EntityListeners` when called from the context of an EJB `@Startup` bean.
## Expected Outcome
The bean should be injected.
## Current Outcome
When a life cycle event defined in an entity listener is triggered from a `@Startup` bean, injecting a managed bean inside that entity listener results in the bean reference containing the value `null`. Trying to inject the `BeanManager` also results in a `null` reference.

As an alternative, the bean can be looked up using `CDI.current().select(MyBean.class).get()`. This actually seems to work, but it results in the warning `No valid EE environment for injection of...` being logged to the Payara console.
## Steps to reproduce (with samples)
The issue is easily reproduced with the following code:
```
@Data
@Entity
@EntityListeners(RecordListener.class)
public class Record implements Serializable {
	@Id @GeneratedValue private int id;
}
```
```
public class RecordListener {
	@Inject
	private RecordDAO recordDAO;

	@Inject
	private BeanManager manager;

        @PostPersist
	private void afterPersist(Record record) {
                System.outprintln("recordDAO: " + recordDAO); /* prints null */
                System.outprintln("manager: " + manager); /* prints null */
	}
```
```
@Startup
@Singleton
public class Startuper {
        @Inject
        private RecordDAO recordDAO;

        @PostConstruct
        private void init() {
                /* Invokes @PostPersist in the entity listener */
                recordDAO.persist(new Record());
        }
}
```
Avoiding the `@Startup` annotation results in everything working as expected (`recordDAO` and `manager` get properly injected). I can only assume something related to CDI or JPA has not yet been fully initialized (in relation to entity listeners) when the call/triger comes from a `@Startup` bean as opposed to one annotated without `@Startup`.
## Environment ##

- **Payara Version**: 5.201
- **Edition**: Embedded
- **JDK Version**: Oracle and OpenJDK 1.8
- **Operating System**: Linux
- **Database**: MariaDB with Payara-bundled EclipseLink provider
- **Targeted JPA version**: 2.1/2.2 (same behavior)
- **Targeted CDI version**: 2.0

**Comment by rdebusscher** [comment]
Hi Adam,

Can you prepare a reproducer with the above code snippets and the main code which starts up the Payara Embedded version.

A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Best Regards
Rudy

**Comment by adam-waldenberg** [comment]
@rdebusscher If you like, I could do a minimal maven project with Arqullian + JUnit + Payara 5.201 embedded that shows the behavior?

**Comment by rdebusscher** [comment]
Hi @adam-waldenberg,

Arquillian and JUnit is optional. if we have a project which is compile-able and when main method is run the error is shown, is also enough.

Thanks
Regards
Rudy

**Comment by OndroMih** [comment]
Hi @adam-waldenberg, do you have a maven project that shows the behavior?

**Comment by adam-waldenberg** [comment]
Sorry. @OndroMih . This got bumped down on my todo-list. Will take a look at it asap.

**Comment by khasunuma** [comment]
Hi @adam-waldenberg, just a reminder. Please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. Otherwise we’ll have to close this issue.

**Comment by khasunuma** [comment]
Hi @adam-waldenberg, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us a reproducer for the latest version.
