### ISSUE TITLE
Determining Eclipselink version

### ISSUE THREAD

**Issue by marcreichman** [payara/Payara#4679]
Hello, I'm using Payara 5.201 and am trying to figure out the actual version of Eclipselink used.

Specifically is there a way to know if the PRs associated with this ticket are merged into the version in Payara?

https://github.com/eclipse-ee4j/eclipselink/issues/628

I'm seeing something working which shouldn't be and I don't quite understand and thought this could be the reason, but it seems too new so I'm not entirely clear.

Thank you!

**Comment by smillidge** [comment]
@marcreichman it is in the pom here https://github.com/payara/Payara/blob/9faed1ad435d16e54ac6b85a6f0d619dce40d54b/pom.xml#L157    
Version 2.7.6.payara-p1 based on eclipse link 2.7.6
