### ISSUE TITLE
Admingui crashes after timeout

### ISSUE THREAD

**Issue by andreasernst** [payara/Payara#468]
After the timeout for the admin gui, Payara crashes, you need to restart Payara, i clicked on the home button:

exception
javax.servlet.ServletException: java.lang.reflect.InvocationTargetException while attempting to process a 'beforeCreate' event for 'treeForm'.

root cause
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException while attempting to process a 'beforeCreate' event for 'treeForm'.

root cause
java.lang.reflect.InvocationTargetException

root cause
java.lang.NullPointerException

java.lang.NullPointerException
        at org.glassfish.admingui.common.util.GuiUtil.genId(GuiUtil.java:343)
        at org.glassfish.admingui.common.handlers.UtilHandlers.encodeId(UtilHandlers.java:1011)

**Comment by dorpsidioot** [comment]
Encountered the same issue in 154

**Comment by smillidge** [comment]
We are aware of this issue and we are currently working on fixing this.
