### ISSUE TITLE
letsencrypt.py script error

### ISSUE THREAD

**Issue by FiruzzZ** [payara/Payara#4685]
I am trying to run the script for 2nd time and all that it says is:
```
Attempting to deploy an EMPTY WAR to the ROOT context: [FAIL] Is the server up and running?
 Command '['./asadmin', 'deploy', '--name', 'le', '--force', '--contextroot', '/', PosixPath('/tmp/payara_le_war')]' returned non-zero exit status 1.

```
The cert is in the keystore.jks (checked with Keystore Explorer)
Payara is up and running, I didn't modify anything on the script or payara config, just deployed my Vaadin PWA app to check the https (it didn't that's why I am trying again)

- **Payara Version**: 5.201.x
- **Edition**: Full
- **JDK Version**: 8 OpenJDK
- **Operating System**: Linux mint

**Comment by khasunuma** [comment]
Please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by khasunuma** [comment]
Please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. Otherwise we’ll have to close this issue.

**Comment by FiruzzZ** [comment]
Sorry but I solved it by no using the py script and setting some "cron jobs". All that setup was in a VM that I don't have any more
