### ISSUE TITLE
Env variables with a dot are not visible in payara since 5.201

### ISSUE THREAD

**Issue by fschuerer** [payara/Payara#4689]
ENV variables with a dot in the name, like 'mp.openapi.filter' can't be overriden with docker -e since Version 5.201.  
If a change the CMD instruction in the DOCKERFILE
`CMD ${SCRIPT_DIR}/entrypoint.sh`
back to Version 5.194
`CMD ["scripts/entrypoint.sh"]`
it works as expected.

**Comment by fturizo** [comment]
Seems to be no longer an issue. Will proceed to close now.
