### ISSUE TITLE
How to obtain all relevant sources for debugging (e.g. for payara-embedded-all)?

### ISSUE THREAD

**Issue by bseiller** [payara/Payara#4698]
# Description #
----------
I need to debug rejarred/"internal" classes (e.g. org.apache.catalina.connector.Request) of a regular Payara instance with IntelliJ and have downloaded both the sources from here and the related patched projects from https://github.com/payara/Payara_PatchedProjects, added the latter to my local maven repository and did a mvn clean install with the former.

Also: Is there an easier way, for example by adding a dependency directly to my project that contains all (transient) dependencies (+sources) that are needed for debugging a given version of Payara?

## Expected Outcome
Running mvn source:jar for e.g. payara-embedded-all or distributions\payara should result in a *-sources.jar containing all sources, including the rejarred ones.

## Current Outcome
Running mvn source:jar for e.g. payara-embedded-all results in a jar that contains a single domain.xml and some metadata files.
A similar issue was opened for v4.1.1.163.0.1
https://github.com/payara/Payara/issues/1118

## Environment ##
- **Payara Version**: 5.201
- **JDK Version**: 8 Oracle
- **Operating System**: Windows

PS: Thank you for providing a shiny version of Glassfish!

**Comment by arjantijms** [comment]
For this I added an embedded source profile a while ago. If you build Payara with -Pembed-source It doesn't a best effort to create/fetch (and embed) source files for all dependencies. It wasn't 100% perfect yet, but should get you mostly there.

See: https://github.com/payara/Payara/blob/master/appserver/packager/pom.xml#L493

**Comment by bseiller** [comment]
I look into it, that seems exactly what I was hoping for!
And thank you for the fast reply
