### ISSUE TITLE
When creating Realm returns NullpointerException /FISH-197

### ISSUE THREAD

**Issue by aschacht** [payara/Payara#4702]
# Description #
----------

I am working through some tutorials and I have hit a wall. Trying to create a new realm in payara. These are the values i filled in:

Class Name: com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm
JAAS Context: jdbcRealm
JNDI: jdbc/youtube
User Table: t_user
User Name Column:username
Password Column: password
Group Table: t_usergroup
Group Table User Name Column: username
Group Name Column: groupname
When I hit ok to create the realm I receive this error
Creation of Authrealm JDBCRealm failed. java.lang.NullPointerException java.lang.NullPointerException 
That wasn't very helpful so I looked at the server logs and found this:
 RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/configs/config/server-config/security-service/auth-realm'; attrs = '{classname=com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm, name=JDBCRealm, property=jaas-context=jdbcRealm:datasource-jndi=jdbc\/youtube:user-table=t_user:user-name-column=username:password-column=password:group-table=t_usergroup:group-table-user-name-column=username:group-name-column=groupname:, target=server-config}']]

## Expected Outcome
Should be able to create a JDBCRealm when hitting ok.

## Current Outcome
when you hit ok you are presented with this message:
Creation of Authrealm JDBCRealm failed. java.lang.NullPointerException java.lang.NullPointerException 

## Steps to reproduce (Only for bug reports) 
1.log in to the admin console
2.scroll to configurations
3. select server-config
4.select security
5.select Realms
6.select new to add a new realm
7.fill in the form making sure to select JDBCRealm for the class name
8. hit ok

## Environment ##

- **Payara Version**: 5.201
- **Edition**: 
- **JDK Version**: 1.8.0_202
- **Operating System**: 
- **Database**: MySQL

**Comment by rdebusscher** [comment]
Hi @aschacht,

Looking deeper into this, it seems that a default for Message Digest is not getting the default value as mentioned in the Web Administration Console.

So by putting a value in that field (SHA-256 for storing hashed passwords, NONE if in plain text which is not recommended at all) the NullPointerException no longer appears.

The default encoding of the hashed password is correctly taken as HEX encoding.

I have created an internal ticket `FISH-197` to fix the issue with the default value for the Message Digest

Best Regards
Rudy

**Comment by smillidge** [comment]
Fixed by https://github.com/payara/Payara/pull/4748
