### ISSUE TITLE
MPCONFIG variable replacement in web.xml not working with secrets directory config provider

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#4709]
# Description #
----------

Microprofile config secrets directory provider doesn't seem to be available to dereference MPCONFIG variables in web.xml datasource configuration during deployment.

## Expected Outcome

When deploying an app that specified a datasource in web.xml descriptor, properties should be able to use MPCONFIG variable replacement for secrets defined by the secrets directory config provider.

## Current Outcome

Unfortunately, this used to work in payara v5.192 but later versions seem to fail when specifying the property values via the secrets directory config property.  Specifying via the environment variable config provider works, but not the secrets directory.

When specified via the secrets directory config provider, the properties ARE available after the application is deployed and the properties are accessed using the microprofile config api, so the issue seems to only be during deployment.

## Steps to reproduce (Only for bug reports) 

Create a datasource definition within a web.xml file and attempt to use MPCONFIG variables to specify the datasource properties.  Populating the microprofile config values via the secrets directory provider will result in failure to dereference the values when using Payara v5.193 or later.

### Samples

Reproducer: https://bitbucket.org/luminositylabs/payara-4709/src/master/reproducer-notes.md

## Environment ##

- **Payara Version**: Tested with versions 5.192 through 5.201
- **Edition**: Tested with payara-server-full
- **JDK Version**: Tested with Zulu 11.0.7 and JDKs in official payara-server-full docker images
- **Operating System**: Centos7, MacOS Mojave 10.14.x, and OSes in official payara-server-full docker images
- **Database**: Postgres v12

**Comment by AlanRoth** [comment]
Hi @phillipross, would you be able to provide a reproducer for the latest version of Payara Community? I was not able to get your reproducer working with the latest version.

**Comment by phillipross** [comment]
Absolutely.  I'll test with 5.2020.6 and see what the status is.  Thanks!

**Comment by AlanRoth** [comment]
Hi @phillipross, any updates on the status?

**Comment by phillipross** [comment]
I've not had a chance to add 5.2020.6 to the reproducer and test, but it's still in my queue and I'll get to it shortly. Thanks!

**Comment by AlanRoth** [comment]
Hi @phillipross, any updates?

**Comment by phillipross** [comment]
Hi @AlanRoth 

This past weekend I finally got around to addressing the reproducer.  It was broken due to a maven artifact groupId mismatch, but I've fixed that and got it working again.  I also realized the reproducer was quite old.  It was made during the v5.201 release and the more rapid release cadence for payara has since been instituted so the reproducer needs more updates to add v5.2020.x releases.  I've begun to do this and will push the changes later today.

The good news is that as I've been updating, I narrowed down the bug to a specific subset of payara releases, and it appears the bug has been fixed since v5.2020.4.  It looks like functionality broke in v5.193, stayed broken until v5.2020.3, and then was restored in 5.2020.4 and remains functional for the .5 and .6 releases.

I think we can close out this issue for now, and I'll add a comment after I push the updated reproducer.

Thanks!

**Comment by AlanRoth** [comment]
Hi @phillipross, 

If you believe the issue has been resolved then I will close this issue. A updated reproducer isn't necessary, we will take your word that it works, unless you believe it will be handy in the future in case this functionality breaks again. 

Thank you,
Alan

**Comment by phillipross** [comment]
Yep, I've updated the reproducer and will leave it in place for posterity.  The payara images for all affected versions are still available in docker hub so there's a chance somebody else using an older image might bump into this 😉
