### ISSUE TITLE
Jakarta EE 8 Web Profile compatibility for Payara Server 5.201 for Web Platform 

### ISSUE THREAD

**Issue by delassiops** [payara/Payara#4717]
# Description #
----------

When looking in https://jakarta.ee/compatibility i only found certification for full server

why the certification for Payara-Web 5.201 (Web Profile)  is missed

payara-web-5.201.zip

## Expected Outcome

Compatibility certification request for Payara Server for web Platform 

like https://github.com/eclipse-ee4j/jakartaee-platform/issues/119

**Comment by smillidge** [comment]
It is on our radar. We focused on Full Profile as that is what the majority of people use and that also covers tests for all the Jakarta EE specifications. Payara Web Profile is just a subset of the specifications and a repackaging of full with less modules.
