### ISSUE TITLE
asadmin command fail when using non-default port

### ISSUE THREAD

**Issue by Francois-Morin** [payara/Payara#4718]
# Description #
----------
I have a Glassfish domain running on 4848 port.
I have a Payara domain running on 5050 port.

When executing asadmin command on Payara, most of them fail with the message "Can not parse command metadata"

## Expected Outcome

Executed command should success

## Current Outcome

1 -**  List domains
 C:\payara5\bin>asadmin list-domains --long

_Can not parse command metadata_
_Can not parse command metadata_
DOMAIN                 ADMIN_HOST  ADMIN_PORT  RUNNING  RESTART_REQUIRED
domain1 - not used     localhost   4848        false    false
PayaraDomain           localhost   5050        true     false
production - not used  localhost   4848        false    false
Command list-domains executed successfully.

2 -**  List connection pools
C:\payara5\bin>asadmin list-jdbc-connection-pools

_Can not parse command metadata
Unknown error
Can not parse command metadata
Remote commands not fetched
Command list-jdbc-connection-pools failed._

## Context (Optional)

Running asadmin list-jdbc-connection-pools from Glassfish bin directory works as expected

## Environment ##

- **Payara Version**: 5.201 #badassfish (build 512)
- **Edition**: Full
- **JDK Version**: 11 u28 - OpenJDK
- **Operating System**: Windows
- **Database**:

**Comment by sgflt** [comment]
I do not see --port parameter. The command should be following:

`C:\payara5\bin>asadmin --port 5050 list-jdbc-connection-pools`

**Comment by Francois-Morin** [comment]
That's it ! I tried several option like --domain or --domaindir with no luck.
I was not aware of this --port option.
Than's for you help !
