### ISSUE TITLE
Local path in validation.xml.root property in published payara-bom-5.201.pom

### ISSUE THREAD

**Issue by pzygielo** [payara/Payara#4723]
Local path in `validation.xml.root` property in published [payara-bom-5.201.pom](https://repo.maven.apache.org/maven2/fish/payara/api/payara-bom/5.201/payara-bom-5.201.pom)
```xml
    <validation.xml.root>/home/andrew/Git/Payara/api/payara-bom/target/classes</validation.xml.root>
```

## Expected Outcome
Unresolved or no such property at all.

## Current Outcome
Property resolved to local path present.

**Comment by rdebusscher** [comment]
Hi,

Correct, but that property is not used in the BOM itself, so I do not see an immediate problem.  We use the BOM also internally and the property is used in some other pom.xml files of the Payara project and hence defined in a central place.

So is this property blocking you in some way, should we rename it (and use something like `payara.validation.xml.root` )?

best regards
Rudy

**Comment by pzygielo** [comment]
Thanks for checking.

>  is this property blocking you

No, it isn't. I just shared observation of slightly unexpected value present there. With confirmation that you know about it, I'm fine with its presence.
