### ISSUE TITLE
Payara response 200 in case of not found CallbackHandler

### ISSUE THREAD

**Issue by martin-aschenbach** [payara/Payara#4725]
# Description #
----------

If I define a custom CallbackHandler via "security.jaspic.config.ConfigHelper.CallbackHandler" and it is not found within [AuthMessagePolicy](https://github.com/payara/Payara/blob/master/appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jaspic/AuthMessagePolicy.java)
Payara responds with Status 200 and an empty response body.

## Expected Outcome

I would expect to receive a status 5xx.

## Environment ##

- **Payara Version**: 5.201
Running within a docker container:
[payara/server-full:5.201](https://hub.docker.com/layers/payara/server-full/5.201/images/sha256-e6a69aa317af9f22bdcd17fbabece16ab7ef36f2c37c614499528de61af0d959?context=explore)

**Comment by rdebusscher** [comment]
Hi,

Can you create a reproducer and sample application that demonstrate this behaviour.

Regards
Rudy

**Comment by OndroMih** [comment]
Hi @martin-aschenbach, please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by khasunuma** [comment]
Hi @martin-aschenbach, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.
