### ISSUE TITLE
asadmin> enable-monitoring --modules jvm fails on JDK 11 /FISH-229

### ISSUE THREAD

**Issue by berniegsfc** [payara/Payara#4726]
# Description #
----------

The asadmin enable-monitoring --modules jvm fails on JDK 11.  The same command works when payara is run on JDK 8.

## Expected Outcome

asadmin> enable-monitoring --modules jvm
Command enable-monitoring executed successfully.

## Current Outcome

asadmin> enable-monitoring --modules jvm
remote failure: Can't attach the agent to the JVM.
Command enable-monitoring failed.

## Steps to reproduce (Only for bug reports) 

Start payara on JDK 11 and issue the asadmin command
enable-monitoring --modules jvm

## Context (Optional)

I need to enable this to monitor heap space use.

## Environment ##

- **Payara Version**: 5.2020.2
- **Edition**: Full
- **JDK Version**: 11.0.7 AdoptOpenJDK
- **Operating System**: Linux
- **Database**: None

**Comment by rdebusscher** [comment]
Hi,

I have created the internal ticket `FISH-229` to investigate this further as this message appears because the JVM reports false when ATTACH_ON_DEMAND flag is queried.

Regards
Rudy

**Comment by rdebusscher** [comment]
This is solved in release 5.2021.5
