### ISSUE TITLE
Improve docker images tags

### ISSUE THREAD

**Issue by yacut** [payara/Payara#4733]
As a user I want to use docker image for specific  Payara and/or JDK version via Docker tags.

e.g. 
```sh
# Payara micro 5.2020.2 with jdk8
docker pull payara/micro:5.2020.2-jdk8

# Payara micro 5.2020.2  with jdk11
docker pull payara/micro:5.2020.2-jdk11

# Payara micro latest version with jdk8
docker pull payara/micro:latest-jdk8

# Payara micro latest version with jdk11
docker pull payara/micro:latest-jdk11
```

**Comment by yacut** [comment]
These docker images/tags are just a disaster. 

```sh
$ docker run payara/server-full:5.2020.3-jdk11 java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-linux64) (build 25.252-b14, mixed mode)
```

**Comment by sgflt** [comment]
Interesting. Mine output:

Status: Downloaded newer image for payara/server-full:5.2020.3-jdk11
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

**Comment by yacut** [comment]
It's not interesting, it's sad.

```sh
➜  docker inspect payara/server-full:5.2020.3-jdk11
[
    {
        "Id": "sha256:ef5dd6b03894d8ab03e5b2407a3ac1df089299bdbe9f0b930333c86a80f4920c",
        "RepoTags": [
            "payara/server-full:5.2020.3-jdk11"
        ],
        "RepoDigests": [
            "payara/server-full@sha256:58745ed1e5f172c2a1efe2f10ef5fac2fedefb35dd74067d15ae621755e2aa4d"
        ],
        ...
        "Created": "2020-07-20T09:18:02.399421556Z",
        ...
    }
]

➜  docker run payara/server-full:5.2020.3-jdk11 java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-linux64) (build 25.252-b14, mixed mode)

➜  docker pull payara/server-full:5.2020.3-jdk11
5.2020.3-jdk11: Pulling from payara/server-full
5bed26d33875: Already exists
f11b29a9c730: Already exists
930bda195c84: Already exists
78bf9a5ad49e: Already exists
31ed92d6b49a: Pull complete
dccfd94300a7: Pull complete
03e488024654: Pull complete
63003858d502: Pull complete
f8aaaf89c47f: Pull complete
f30283851b9b: Pull complete
Digest: sha256:083d24923dbc2b7f4f8743cb8aac9c6100fd3226f1fe77430ba10a9fd7d940ed
Status: Downloaded newer image for payara/server-full:5.2020.3-jdk11
docker.io/payara/server-full:5.2020.3-jdk11

➜  docker run payara/server-full:5.2020.3-jdk11 java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

➜  docker inspect payara/server-full:5.2020.3-jdk11
[
    {
        "Id": "sha256:ced0df4290fcfb720e15a96e3be72ba9c65a56fa72539bad212d55624b5eb3ac",
        "RepoTags": [
            "payara/server-full:5.2020.3-jdk11"
        ],
        "RepoDigests": [
            "payara/server-full@sha256:083d24923dbc2b7f4f8743cb8aac9c6100fd3226f1fe77430ba10a9fd7d940ed"
        ],
        ...
        "Created": "2020-07-21T08:46:50.783761927Z",
        ...
    }
]
```

Specifically this image was fixed today, but such problems should not happen at all. Please review the docker tags for Payara images so that this does not happen again. It would also be nice to see in the README what tags are available.

PS: if someone has a problem with this image in k8s, then make sure that your deployment [always pull](https://kubernetes.io/docs/concepts/containers/images/#updating-images) the image from the registry and restart the pod.

**Comment by Herr-Sepp** [comment]
@yacut I didn't want to open a new ticket but can you please change the title because this is not an improvement. The tags don't say anything about what is in the images at the moment. This is a breaking thing.


Tag : 
payara/micro:5.2020.2  >> is build with payara 5.201 and zulu11-jre NOT payara5.2020.2 and zulu8 what the tag suggests
payara/micro:5.2020.3 >> is build with payara 5.??? ( output: Payara Micro  5 #badassmicrofish (build ${build.number}_) and zulu11-**JDK** (why? this makes this image ~85 mb bigger)

So there is currently no JDK8 micro image from latest payara available.
Even better the 5.2020.2 tag was at first jre8 and switched to Jre11 >> that broke our buildchain.

And 5.2020.3 is not build with the dockerfile in this repository ([appserver/extras/docker-images/micro/src/main/docker/Dockerfile](https://github.com/payara/Payara/blob/8a7e001ad3832da3d2e6c1860283f3f78616becb/appserver/extras/docker-images/micro/src/main/docker/Dockerfile)) so it is even harder to track the changes from this image.


And this is not the first time the Images does not contain what the tags say.

**Comment by OndroMih** [comment]
Hi, we apologize that we uploaded a JDK8-based image to the 5.2020.3-jdk11 tag earlier. Thank you for spotting it and raising this issue. We simply made a mistake when we set up our build pipeline to also support JDK-11 based images. It's fixed now, the correct image is uploaded and all will be uploaded correctly to match the tags in the future.

However, I think it's a bit harsh to call the tags a disaster. It happened once, and only for a single JDK-11 based released and we fixed it soon. We offer the service for free and we try to do our best but mistakes can happen. If you'd like bullet proof stability and reliability, you can join the commercial Payara Enterprise program and sponsor what we do.

I think that the Docker tags are in a good shape now. The `latest` tag points to the latest jdk8-based tag. We don't publish a latest-jdk11 tag yet, we'll consider adding it in the future or switching to jdk11 for the latest tag. All the other tags contain what their name suggests.

**Comment by Herr-Sepp** [comment]
@OndroMih can you please look into the micro-Images ( https://github.com/payara/Payara/issues/4733#issuecomment-670527039) or should i open a new ticket for that?
