### ISSUE TITLE
Eclipse MicroProfile Config is caching the validation result

### ISSUE THREAD

**Issue by otaviojava** [payara/Payara#4736]
Payara Server 5.2020.2 (Full)

Hey Payara, is there any change in the Eclipse Config behavior?
It looks like we're caching the Eclipse Config result and I need to be lazy because I need the CDI Container on #Jakarta NoSQL

ps: It was working on the Payara 5.194 version.

**Comment by rdebusscher** [comment]
Hi Otavio,

Yes, we have introduced a cache for MicroProfile Config. You can read more about it in the documentation https://docs.payara.fish/community/docs/5.2020.2/documentation/microprofile/config.html#config-cache-duration-configuration

It can be disabled by
`./asadmin set-config-cache --duration=0`

Best Regards
Rudy

**Comment by otaviojava** [comment]
@rdebusscher 
Is there any Java parameter to disable this cache?

**Comment by rdebusscher** [comment]
@otaviojava 
There is no Java System property to disable the cache.
