### ISSUE TITLE
Payara EJB and JNDI

### ISSUE THREAD

**Issue by mlb1141** [payara/Payara#477]
In Payara 4.1.154, I created/deployed an EJB.  I was surprised when I went to the admin console that the ejb did not appear in the JNDI tab in either Custom or External.  Is this the way it is supposed to be?  Can I see the name of my ejbs anywhere?

**Comment by smillidge** [comment]
The console does not show general JNDI entries. The JNDI name of your EJB is created as described by the rules in the EJB specification and should also be printed in a log message on deployment. 

You can list jndi entries using the asadmin command
```shell
asadmin list-jndi-entries
```

**Comment by mlb1141** [comment]
Thanks for list-jndi-entries
