### ISSUE TITLE
Sort the list of nodes under "instances" and "configurations" / FISH-759

### ISSUE THREAD

**Issue by DeCaMil** [payara/Payara#4795]
# Description #
----------

In the UI, sort the list of entries under "Instances" and "configurations"
## Expected Outcome

The list of instances or configurations should be sorted by name.
When there are a large number of instances, it becomes time consuming scrolling through the list looking for the right name.

## Current Outcome
Currently, the list is in order of creation (probably the order in which they appear in the domain.xml)
## Environment ##

- **Payara Version**: 5.2020.2
- **Edition**: All
- **JDK Version**: Oracle 11.0.7
- **Operating System**: Windows Server 2016
- **Database**: Oracle 11g/19c, SQL Server 2016

**Comment by DeCaMil** [comment]
Here I created 3 instances in the order CCC, AAA, BBB and that's the order they appear under "Instances" in the UI.
With 3 instances, it's not an issue, but our production system has 24 instances and it can require scanning the entire list to find the correct instance.  The same behavior is seen under "Configurations". I think the same is true for "Applications", but I'll need to check my work system to confirm that.

[
<img width="231" alt="Screen Shot 2020-08-28 at 11 40 08 PM" src="https://user-images.githubusercontent.com/4065639/91627827-41fac900-e988-11ea-8541-ba12d6cf7805.png">
](url)

**Comment by AlanRoth** [comment]
Hi @DeCaMil, 

would you be able to make a PR with this tweak yourself? We recognise the usefulness of having an alphabetically sorted list, but we haven't had any reports with this issue - I have created an internal issue `FISH-759`, however keep in mind this will be a low priority issue and may take a while to be implemented, as our efforts are focused elsewhere currently. Hence it may be faster to make a PR yourself.

Thank you,
Alan
