### ISSUE TITLE
Could not find artifact fish.payara.extras:payara-embedded-all:jar:5.2020.3

### ISSUE THREAD

**Issue by kbendereleader** [payara/Payara#4801]
# Description #

Could not find artifact fish.payara.extras:payara-embedded-all:jar:5.2020.3

Maven repository contains version: 5.2020.2
https://mvnrepository.com/artifact/fish.payara.extras/payara-embedded-all

Release page: https://github.com/payara/Payara/releases/tag/payara-server-5.2020.3

**Comment by phillipross** [comment]
It simply takes some time to propagate.

https://search.maven.org/artifact/fish.payara.extras/payara-embedded-all

https://oss.sonatype.org/service/local/repositories/releases/content/fish/payara/extras/payara-embedded-all/5.2020.3/payara-embedded-all-5.2020.3.jar

**Comment by kbendereleader** [comment]
thx
