### ISSUE TITLE
Cannot start UserTransactions from standalone clients #2

### ISSUE THREAD

**Issue by riksweeney** [payara/Payara#4809]
# Description #
----------

Unfortunately I have to re-open issue #4322 as the bug is still present when running the example code provided. This bug is present in Community edition (5.2020.3).

## Expected Outcome

Looking up and starting a UserTransaction from a standalone client should complete successfully.

## Current Outcome

Starting the UserTransaction fails with the following stacktrace:

    MultiException stack 1 of 1
    java.lang.IllegalStateException: Service fish.payara.nucleus.requesttracing.RequestTracingService was started at level -2 but it has a run level of 10. The full descriptor is SystemDescriptor(
    implementation=fish.payara.nucleus.requesttracing.RequestTracingService
    name=requesttracing-service
    contracts={fish.payara.nucleus.requesttracing.RequestTracingService,org.jvnet.hk2.config.ConfigListener,fish.payara.monitoring.collect.MonitoringDataSource,fish.payara.monitoring.collect.MonitoringWatchSource}
    scope=org.glassfish.hk2.runlevel.RunLevel
    qualifiers={}
    descriptorType=CLASS
    descriptorVisibility=NORMAL
    metadata=runLevelValue={10}
    rank=0
    loader=org.glassfish.hk2.bootstrap.impl.Hk2LoaderPopulatorPostProcessor$1@2453f95d
    proxiable=null
    proxyForSameScope=null
    analysisName=null
    id=617
    locatorId=0
    identityHashCode=1119242936
    reified=true)
    at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.validate(AsyncRunLevelContext.java:422)
    at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:275)
    at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
    at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:759)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:771)
    at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:87)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.getRequestTracing(JavaEETransactionManagerSimplified.java:202)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.initJavaEETransaction(JavaEETransactionManagerSimplified.java:665)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.begin(JavaEETransactionManagerSimplified.java:926)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.begin(JavaEETransactionManagerSimplified.java:887)
    at com.sun.enterprise.transaction.UserTransactionImpl.begin(UserTransactionImpl.java:169)
    at TransactionTest.main(TransactionTest.java:31)

## Steps to reproduce

1. Download Community edition (5.2020.3) and extract to location of choice
2. Start the default domain with asadmin start-domain
3. Compile the following code using javac - cp .;c:\payara5\glassfish\lib\gf-client.jar TransactionTest.java

```
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.transaction.TransactionManager;
import javax.transaction.UserTransaction;

public class TransactionTest {

    public static void main (String[] args) {

        UserTransaction tx = null;

        TransactionManager tm = null;

        try {
            System.out.println ("Getting context");

            final Context context = new InitialContext ();

            System.out.println ("Getting UserTransaction");

            tx = (UserTransaction) context.lookup ("java:comp/UserTransaction");

            System.out.println ("Setting transaction timeout");

            tx.setTransactionTimeout (15);

            System.out.println ("Beginning transaction");

            tx.begin ();

            System.out.println ("Rolling back transaction");

            tx.rollback ();
        } catch (final Exception e) {
            e.printStackTrace ();
        }
    }
}
```

4. Run the code using java - cp .;c:\payara5\glassfish\lib\gf-client.jar TransactionTest

## Environment ##

- **Payara Version**: Community edition (5.2020.3)
- **Edition**: Full
- **JDK Version**: OpenJDK 11 2018-09-25, OpenJDK 8 1.8.0_232
- **Operating System**: Windows 10
- **Database**: Oracle

**Comment by OndroMih** [comment]
I've reproduced the exception on 5.2020.3. The same exception is raised for all Payara 5 versions since the first release 5.181. I cannot reproduce it with GlassFish 5.1. So Payara 5.181 must have introduced this issue, if it wasn't present even in Payara 4.

I'll check some examples how to run application client with Payara 5, it's possible that it's not meant to be used as you use it. If I confirm your scenario is valid, we'll accept the bug and will try to fix it.

**Comment by OndroMih** [comment]
by the way, the reproducer ends in an exception also against Payara 4.1.1.171 which is one of the first versions of Payara Server ever.

**Comment by riksweeney** [comment]
Cool, thank you for your assistance with this. Do let me know if you need any further information.

**Comment by OndroMih** [comment]
I've managed to refactor the reproducer so that the deployed app exposes a remote EJB which calls the transaction within the server and the client calls the EJB instead of accessing the `UserTransaction` object directly. This is very well documented in the GlassFish documentation here https://eclipse-ee4j.github.io/glassfish/docs/latest/application-development-guide/java-clients.html#beakw and works well also with Payara Server 5:2020.3.

Here's a working example: 
[reproducer-with-ejb.zip](https://github.com/payara/Payara/files/4972479/reproducer-with-ejb.zip)

So the problem seems to be only when the client accesses the `UserTransaction` object directly. Can you try the solution with calling an EJB? Would it be enough for you to continue what you need to do?

**Comment by riksweeney** [comment]
Yes, I think this will work for us! I've just been trying out a few things quickly and am able to start up a transaction successfully. Hopefully this will allow us to move up to Java 11 and modernise our code in the process (we still have some EJB2s knocking around the application).

Thank you for your swift response, feel free to close this issue :)
