### ISSUE TITLE
EJB Transaction created for TransactionAttributeType.NOT_SUPPORTED methods

### ISSUE THREAD

**Issue by mafaul** [payara/Payara#4826]
# Description #
----------

A method annotated with @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED) should not have anEJB transaction created for it. See:
https://javaee.github.io/javaee-spec/javadocs/javax/ejb/TransactionAttributeType.html#NOT_SUPPORTED

It seems to work correctly in Glassfish 5, but not in Payara. Payara creates a transaction, as if the annotation is ignored.

[payara server.log](https://github.com/payara/Payara/files/5052308/payara.server.log)
[glassfish server.log](https://github.com/payara/Payara/files/5052318/glassfish.server.log)

## Expected Outcome

**No EJB transaction so no rollback.**
Tested on Glassfish

[2020-08-10T10:24:09.994+0200] [glassfish 5.0] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=107 _ThreadName=admin-listener(4)] [timeMillis: 1597047849994] [levelValue: 800] [[
  timeoutTest was successfully deployed in 17,522 milliseconds.]]

[2020-08-10T10:25:00.021+0200] [glassfish 5.0] [INFO] [] [Facade1] [tid: _ThreadID=211 _ThreadName=__ejb-thread-pool1] [timeMillis: 1597047900021] [levelValue: 800] [[
  Starting runTest]]

[2020-08-10T10:25:08.023+0200] [glassfish 5.0] [INFO] [] [Facade1] [tid: _ThreadID=211 _ThreadName=__ejb-thread-pool1] [timeMillis: 1597047908023] [levelValue: 800] [[
  Done with runTest]]

## Current Outcome

**An EJB transaction that times out**
Tested on Payara

[2020-08-10T10:12:26.633+0200] [Payara 5.184] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=100 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1597047146633] [levelValue: 800] [[
  timeoutTest was successfully deployed in 5,051 milliseconds.]]

[2020-08-10T10:13:00.016+0200] [Payara 5.184] [INFO] [] [Facade1] [tid: _ThreadID=294 _ThreadName=__ejb-thread-pool5] [timeMillis: 1597047180016] [levelValue: 800] [[
  Starting runTest]]

[2020-08-10T10:13:08.016+0200] [Payara 5.184] [INFO] [] [Facade1] [tid: _ThreadID=294 _ThreadName=__ejb-thread-pool5] [timeMillis: 1597047188016] [levelValue: 800] [[
  Done with runTest]]

[2020-08-10T10:13:08.017+0200] [Payara 5.184] [WARNING] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=294 _ThreadName=__ejb-thread-pool5] [timeMillis: 1597047188017] [levelValue: 900] [[
  EJB5123:Rolling back timed out transaction [JavaEETransactionImpl: txId=15 nonXAResource=null jtsTx=null localTxStatus=4 syncs=[com.sun.ejb.containers.ContainerSynchronization@480fe38a]] for [Facade1]]]

## Steps to reproduce (Only for bug reports) 

1 - Run payara, open admin console
2 - Go to Transaction Service -> Transaction Timeout
3 - Change to 5 seconds (For this test)
4 - Save and restart Payara.
5 - Run the Sample app below (Deploy the timeoutTest.war file)
6 - Check log file

### Samples

[timeoutTest.zip](https://github.com/payara/Payara/files/5049761/timeoutTest.zip)

## Context (Optional)

We use @Schedule methods to do processing of data and would like the main schedule method not to have a transaction. We will create a transaction per record to process.

## Environment ##

- **Payara Version**: 5.184 and 5.201
- **Edition**: Full
- **JDK Version**: AWS Corretto jdk1.8.0_232 and AWS Corretto jdk1.8.0_242
- **Operating System**:  Windows
- **Database**: None

**Comment by mafaul** [comment]
Added log files of test running on Payara and Glassfish

**Comment by rdebusscher** [comment]
Hi,

I think you misinterpreted the value and the description of `NOT_SUPPORTED` value.

From the link you mention

>If a client calls with a transaction context,  the container suspends the association of the transaction context with the current thread before invoking the enterprise bean's business method.

So when the method is called, if there is a current transaction, the method is executed outside that transaction. But it says nothing about what should be done inside the method.

That is unspecified in the specification

>The container invokes an enterprise bean method whose transaction attribute NOT_SUPPORTED with an unspecified transaction context.

Payara has chosen to use 'normal' rules so that there is some consistency on how the platform works (and not many different rules depending on the different situations)

Hence, Glassfish and Payara are working correctly.

The specification has no option to define the transaction time per method (or bean). But Payara (Glassfish) has the option to define it with the tag `<cmt-timeout-in-seconds>` in the _glassfish-ejb-jar.xml_.

Regards
Rudy

**Comment by mafaul** [comment]
Hi Rudy,

Thank you for looking at this. I fully support consistency. I do however still think we should consider the following:

Table from https://docs.oracle.com/javaee/7/tutorial/transactions003.htm
![image](https://user-images.githubusercontent.com/12007706/90719934-e2305e00-e2b5-11ea-8ff4-10492cbd8cfc.png)

Is there a difference between `NOT_SUPPORTED` and `REQUIRES_NEW` when running Payara?

Technically Payara complies with the spec, so I will implement a workaround. 
Maybe the spec needs some additional clarification.

**Comment by rdebusscher** [comment]
Hi,

The main difference is that `REQUIRES_NEW` always starts a new transaction when the EJB method is entered and `NOT_SUPPORTED` only when there is some interaction with the database.

See code https://github.com/payara/Payara/blob/eeb16a19d9b0bb18572b8ecfb19fadc681f26175/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java#L140

Regards
Rudy

**Comment by mafaul** [comment]
Hi Rudy,

Thank you.

This example code gets executed (by the EJBTimerService) without any database interactions:
```
@Schedule(persistent = false, hour = "*", minute = "*", second = "0")
@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
public void runTest() {
        LOGGER.log(Level.INFO, "Starting runTest ");
}
```

An ejb transaction gets created for this invocation. (See log file)

[log.txt](https://github.com/payara/Payara/files/5129563/log.txt)

When EJBContainerTransactionManager.preInvokeTx (Thank you for the link above) is called for this invocation, the txAttr is 3 (TX_REQUIRED). 
I expect it to be 1 (TX_NOT_SUPPORTED) because of the "@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)" annotation on the method.

Am I correct to expect this result?

**Comment by rdebusscher** [comment]
Hi,

It is indeed strange that you see a different transaction attribute value as defined, but the end result is the same. The transaction that was active when the method starts is placed on hold until method is finished. Again, it does not say anything about the transaction inside the method, but what happens with the transaction what was in progress (before method was called).

Within Container Managed Transactions, every EJB method is transactional. Otherwise you need to define the bean as using the Bean Management Type ( `@TransactionManagement(TransactionManagementType.BEAN)` ) and use UserTransaction if you need transaction support.

Regards
Rudy

**Comment by mafaul** [comment]
Hi Rudy,

I respectfully disagree with you. In this example there is no transaction in progress (before method was called). The end result is not the same. The @TransactionAttribute annotation on a method describes what should happen inside the method too.

We are currently running a patched version of Payara with the following change, which resolved the issue for us.
https://github.com/mafaul/Payara/commit/7f4921b4246d995d9766a7b0969e14613a34ac1a

I am not confident enough to create a PR because I am afraid of possible scenarios that I don't know about that might not be supported.

Regards,
Max
