### ISSUE TITLE
Hazelcast node connect performance slow takes ~10s

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#4858]
# Description #
----------

When connecting to other Hazelcast-based nodes, the connection takes ~10s, which should not happen and is very slow

## Expected Outcome

Making connection should be almost immediate

## Environment ##

- **Payara Version**: 5-SNAPSHOT
- **JDK Version**: 8
- **Operating System**: Mac
- **Database**: None

**Comment by lprimak** [comment]
This is the NetBeans Profile data attaching Payara Micro to Server cluster
[NB-Profile-Data.zip](https://github.com/payara/Payara/files/5138953/NB-Profile-Data.zip)

**Comment by lprimak** [comment]
Looks like it's hitting some sleep statements inside Hazelcast

**Comment by lprimak** [comment]
Working on a solution this weekend

**Comment by lprimak** [comment]
There are two system properties that control the 'just delay' on the master node. They are describer here:
https://github.com/laszlocsomor/hazelcast-reference-manual/blob/d01054731d4def728e82eab730a10b8557d1101b/src/docs/asciidoc/system_properties.adoc
```hazelcast.wait.seconds.before.join``` and
```hazelcast.max.wait.seconds.before.join```

The former can be set to zero to alleviate the delays.
There is another issue with the Hazelcast code waiting multiple seconds to 'retry' the connection and should be fixed.

**Comment by lprimak** [comment]
I submitted an above issue to Hazelcast. I will also submit a PR to them so client-side delays (small) are alleviated

**Comment by lprimak** [comment]
Hz client-side PR https://github.com/hazelcast/hazelcast/pull/17428

**Comment by lprimak** [comment]
I've already got the delay down from ~10s to less than 1/2 second experimentally

**Comment by AlanRoth** [comment]
I will mark this issue as accepted since @lprimak is actively working on this on Payara's side.

**Comment by smillidge** [comment]
Micro is already using this system property https://github.com/payara/Payara/blob/f44fa70ead58ecc27281a465b53d637eee79c4f3/appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java#L1924

**Comment by lprimak** [comment]
There are more issues at hand here.
If you set that to zero, there are other problems joining the cluster that Hazelcast is aware of (https://payara.atlassian.net/browse/QACI-556)
Also, if micro is not a master node, obviously this wouldn't take effect, so just be aware of that

**Comment by smillidge** [comment]
Yeah I think I tried at the time to set to zero and sometimes the cluster didn't form.

**Comment by fturizo** [comment]
As this issue is internally tracked by QACI-556 (in charge of Lenny as well), there's no need to keep tracking this publicly here, so I'll proceed to close the issue

**Comment by lprimak** [comment]
Hazelcast 5.4 will have the ultimate fix for this issue
