### ISSUE TITLE
Default index.html says GF - not Payara?

### ISSUE THREAD

**Issue by stf-pay** [payara/Payara#4859]
# Description #
----------

oracle.com
--
GlassFish Server 3.1.2

To replace this page, overwrite the file index.html in the document root folder of this server. The document root folder for this server is the docroot subdirectory of this server's domain directory.

To manage a server on the local host with the default administration port, go to the Administration Console.

## Expected Outcome
payara.fish
--
Payara 5.2020

To replace this page, overwrite the file index.html in the document root folder of this server. The document root folder for this server is the docroot subdirectory of this server's domain directory.

To manage a server on the local host with the default administration port, go to the Administration Console.

## Current Outcome
oracle.com
--
GlassFish Server 3.1.2

To replace this page, overwrite the file index.html in the document root folder of this server. The document root folder for this server is the docroot subdirectory of this server's domain directory.

To manage a server on the local host with the default administration port, go to the Administration Console.

## Environment ##

- **Payara Version**: 5.2020.2
- **Edition**: Community
- **JDK Version**: openJDK11
- **Operating System**: Linux
- **Database**: mySQL

**Comment by smillidge** [comment]
I don't understand this issue. The default page on Payara says "Hello from Payara - your server is now running" see https://github.com/payara/Payara/blob/master/nucleus/admin/template/src/main/resources/docroot/index.html

**Comment by stf-pay** [comment]
Nevermind.
