### ISSUE TITLE
OpenAPI document container 'ejb-timer-service-app' server url /FISH-431

### ISSUE THREAD

**Issue by fschuerer** [payara/Payara#4877]
# Description #
----------

The OpenAPI document contains an "ejb-timer-server-app" server URL if a persistent EBJ timer is defined.  
No REST endpoint can be reached via this URL.

## Expected Outcome

```yml
openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
- url: http://localhost:8080/openapi-timer
  description: Default Server.
- url: https://localhost:8181/openapi-timer
  description: Default Server.
paths:
  /resources/sample:
    get:
      operationId: doit
      responses:
        default:
          description: Default Response.
          content:
            '*/*':
              schema:
                type: object
components: {}
```

## Current Outcome

```yml
openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
- url: http://localhost:8080/ejb-timer-service-app
  description: Default Server.
- url: https://localhost:8181/ejb-timer-service-app
  description: Default Server.
- url: http://localhost:8080/openapi-timer
  description: Default Server.
- url: https://localhost:8181/openapi-timer
  description: Default Server.
paths:
  /resources/sample:
    get:
      operationId: doit
      responses:
        default:
          description: Default Response.
          content:
            '*/*':
              schema:
                type: object
components: {}
```
## Steps to reproduce (Only for bug reports) 

Reproducer application is provided at https://github.com/fschuerer/openapi-timer

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Full
- **JDK Version**:  OpenJDK 11
- **Operating System**:  Windows 10

**Comment by rdebusscher** [comment]
Hi,

Thank you for reporting this issue and the reproducer. I have created the internal ticket `FISH-431` to solve this issue.

Best regards
Rudy

**Comment by fschuerer** [comment]
Hi Rudy,

thanks for your always quick reply.

Best regards 
Frank

**Comment by smillidge** [comment]
Fixed by https://github.com/payara/Payara/pull/4966
