### ISSUE TITLE
Command stop-domain failed with debugging enabled /FISH-440

### ISSUE THREAD

**Issue by lsa-shanghai** [payara/Payara#4888]
# Description #
----------
Command stop-domain failed with debugging enabled

## Expected Outcome
Can stop normally
## Current Outcome
./asadmin stop-domain domain1
Waiting for the domain to stop .......................................................
Timed out (60 seconds) waiting for the domain to stop.
Command stop-domain failed.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain -d domain1
    Waiting for domain1 to start .......................
    Successfully started the domain : domain1
    domain  Location: /Users/wang/payara5/payara5202004/glassfish/domains/domain1
    Log File: /Users/wang/payara5/payara5202004/glassfish/domains/domain1/logs/server.log
    Admin Port: 4848
    Command start-domain executed successfully.

2 -**  Stop the domain
   ./asadmin stop-domain domain1
   Waiting for the domain to stop .......................................................
  Timed out (60 seconds) waiting for the domain to stop.
  Command stop-domain failed.

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Full
- **JDK Version**: 11-openj9
- **Operating System**: Mac
- **Database**: PostGres/JavaDB

**Comment by khasunuma** [comment]
As I try to reproduce, the problem is only occurred on OpenJ9. On the other JVM such as Oracle JDK or Azul Zulu, `stop-domain` command properly works for the domain with debug option.

**Comment by khasunuma** [comment]
I raised the internal issue `FISH-440` to further investigate.

**Comment by rdebusscher** [comment]
This can't be reproduced anymore with newer version.

➜  bin java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
➜  bin ./asadmin start-domain --debug

Waiting for domain1 to start ..........................
Successfully started the domain : domain1
domain  Location: /Users/rubus/tools/payara5.2021.8/glassfish/domains/domain1
Log File: /Users/rubus/tools/payara5.2021.8/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
➜  bin ./asadmin stop-domain
Waiting for the domain to stop .
Command stop-domain executed successfully.
