### ISSUE TITLE
Internal Error 500 Exception Report: Payara Server 5.201 #badassfish logs

### ISSUE THREAD

**Issue by J-Vin** [payara/Payara#4894]
# Description #
----------
HTTP Status 500 - Internal Server Error
type Exception report

messageInternal Server Error

descriptionThe server encountered an internal error that prevented it from fulfilling this request.

(SIDE NOTE*Nothing seems to work for me like it should and I do not know how to correctly report these errors in all the different sites and .... each require. Hoping this error will help bring some enlightenment and next steps for correction. Unfortunately, I have no idea what thus means and have few accessible resources to help)

Payara Server 5.201 #badassfish

## Expected Outcome
Submit application for emergency assistance on url
https://www.shelbycountytn.gov/3647/Covid-19-Resident-Relief-Fund-Applicatio

(*which I notice is missing and 'n' ending 'applicatioN')

## Current Outcome

ERROR REPORT: 

"exception

javax.servlet.ServletException: viewId:/index.xhtml - View /index.xhtml could not be restored.
root cause

javax.faces.application.ViewExpiredException: viewId:/index.xhtml - View /index.xhtml could not be restored.
note The full stack traces of the exception and its root causes are available in the Payara Server 5.201 #badassfish logs."

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by charleech** [comment]
Hi,

IMHO, the `javax.faces.application.ViewExpiredException` may not relate to the `Payara` nor any `application server`, but the `JSF` itself.

BalusC gave an intensive explanation starting from the fundamental to the how to handle it at https://stackoverflow.com/questions/3642919/javax-faces-application-viewexpiredexception-view-could-not-be-restored

**Comment by rdebusscher** [comment]
Hi,

Is it correct that you as a user are experiencing this problem with the application but that you did not develop it?  The ViewExpiredException is indeed, as mentioned, most of the time a problem on how the JSF application is developed and nicely explained by BalusC. 

Please contact the website owners to get your issue resolved.

Best Regards
Rudy
