### ISSUE TITLE
javax.persistence.query.timeout seems to be without function using eclipselink

### ISSUE THREAD

**Issue by sterlp** [payara/Payara#4895]
# Description #
----------

Using javax.persistence.query.timeout to set the default timeout is ignored using eclipse link. Changing to hibernate, it works as expected and documented.

## Expected Outcome

The value javax.persistence.query.timeout is used to set the timeout on the JDBC datasource. Timeout exception is thrown after the given timeout.

## Current Outcome

javax.persistence.query.timeout is ignored using eclipse link. No timeout exception is thrown.

## Steps to reproduce (Only for bug reports) 

1. configure javax.persistence.query.timeout in the persistence xml
2. execute a query which takes longer as the defined value
3. query wil not be aborted

### Samples

https://github.com/sterlp/training/tree/master/jee-interceptor

Example is configured to use hibernate right now. It works.
Change to eclipse link and it stops working.

## Environment ##

- **Payara Version**: Payara Server 5.201
- **Edition**: Full
- **JDK Version**: jdk1.8.0_251.jdk
- **Operating System**: Mac
- **Database**: PostGres

**Comment by charleech** [comment]
Hi,

Regarding to the `pom.xml` at https://github.com/sterlp/training/blob/master/jee-interceptor/pom.xml, it uses the **EclipseLink** version `2.5.2`. But the https://www.eclipse.org/eclipselink/api/2.5/org/eclipse/persistence/config/QueryHints.html does no has `javax.persistence.query.timeout`.

While the  `javax.persistence.query.timeout` is existed at both of https://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/config/QueryHints.html and https://www.eclipse.org/eclipselink/api/2.7/org/eclipse/persistence/config/QueryHints.html

The **Payara** version `5.2020.4` also includes the **EclipseLink** version `2.7.6` as well.

IMHO, we should update the **EclipseLink** to the same version of the **Payara**.

**Comment by rdebusscher** [comment]
Hi,

The javax.persistence.query.timeout is an optional hint in the specification as you can read in section 3.10.10 of JPA 2.2 spec.

> Portable applications should not rely on this hint. Depending on the persistence provider and database in
> use, the hint may or may not be observed.

EclipseLink seems to implement this in a proprietary way of a Query Timeout as described on this page https://www.eclipse.org/eclipselink/documentation/2.4/jpa/extensions/q_jdbc_timeout.htm

See also these QueryHints docs page 
https://www.eclipse.org/eclipselink/api/2.7/org/eclipse/persistence/config/QueryHints.html#QUERY_TIMEOUT

Best Regards
Rudy

**Comment by sterlp** [comment]
Hello Guys,

well based on the doc of eclipse link javax.persistence.query.timeout is supported since 2.1. I found only a reference to a bug in the older version, concerning the unit:
https://www.ibm.com/support/pages/apar/PI53372

Anyway I tried the custom parameters as you suggested and yeah the solution is somehow in between. Setting this values:
```
      <property name="javax.persistence.query.timeout" value="30"/>
      <property name="eclipselink.query.timeout.unit" value="MILLISECONDS"/>
```

Fixes the issue. The funny part is, that the QueryHints of the Query stays empty, despite it is honored, as long as the persistence.xml is used.

Setting the values on the EntityManager -- means for one session despite for everything -- is ignored for some reason:
```
public class ConnectionTimeoutInterceptor implements Serializable {
    @PersistenceContext EntityManager em;    
    @AroundInvoke
    public Object execute(InvocationContext ctx) throws Exception {
            em.setProperty("javax.persistence.query.timeout", 10);
            em.setProperty("eclipselink.query.timeout.unit", "MILLISECONDS");  // added for eclipse link support
            return ctx.proceed();
    }
```

But I think now, it is more an eclipselink issue and not a payara issue. I checked the code `EntityManagerWrapper` which looks good to me.

`.setHint("eclipselink.jdbc.timeout", 1)`  seem to work. Means it can be set on query level. Is there a way to provide a custom wrapper for the EntityManager in Payara?

Thanks

Paul

**Comment by sterlp** [comment]
I created the issue for eclipselink: https://github.com/eclipse-ee4j/eclipselink/issues/912

If you guys agree, that this is rather an eclipselink issue than a payara issue please feel free to close this ticket. Thanks for the support so far.

**Comment by sterlp** [comment]
> Hi,
> 
> Regarding to the `pom.xml` at https://github.com/sterlp/training/blob/master/jee-interceptor/pom.xml, it uses the **EclipseLink** version `2.5.2`. But the https://www.eclipse.org/eclipselink/api/2.5/org/eclipse/persistence/config/QueryHints.html does no has `javax.persistence.query.timeout`.
> 
> While the `javax.persistence.query.timeout` is existed at both of https://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/config/QueryHints.html and https://www.eclipse.org/eclipselink/api/2.7/org/eclipse/persistence/config/QueryHints.html
> 
> The **Payara** version `5.2020.4` also includes the **EclipseLink** version `2.7.6` as well.
> 
> IMHO, we should update the **EclipseLink** to the same version of the **Payara**.

This example uses "provided" as scope -- means I use the version of eclipselink provided by the container. As you can see, I even removed the jar totally. The version responding is:

Eclipselink Version: Eclipse Persistence Services - 2.7.4.payara-p2

**Comment by rdebusscher** [comment]
Closing this as a working solution is found and issue opened at EclipseLink project.

Thanks
Rudy
