### ISSUE TITLE
payara running in docker consumes steadily NonHeap memory

### ISSUE THREAD

**Issue by rsoika** [payara/Payara#4901]
Running an application in payara micro on kubernetes I made the observasion that the memory consumed by the container increases steadily. This behaviour is independent form the application. So even if you start an empty server

    $ docker run -p 8080:8080 payara/micro
    
    $ docker stats

you can see that the memory consumed by the container is increasing permanently.

After investigating more time into this issue I see that the metric _base_memory_usedNonHeap_bytes_ is increasing but never decreasing. This explains maybe the memory consumption.
Changing the heap sizes (which is not the problem here) or changing the garbage collector did not change the behaviour. I played around with several settings. But _base_memory_usedNonHeap_bytes_ is always increasing

I would not say this is a problem of payara itself because I observer exactly the same behaviour with Wildfly (see discussion [here](https://groups.google.com/g/wildfly/c/6FaM6q9EF2Y)). But it may also not be related to the jdk because wildfy is running with openjdk 11.0.8 and payara with openjdk 1.8.0_262

Maybe I am on the wrong track by observing only the metric _base_memory_usedNonHeap_bytes_? But this seems to me be the only indicator explaining the memory consumption of the container. I found also this discussion which looks to me addressing the same issue: https://bugzilla.redhat.com/show_bug.cgi?id=1715029

Practically this means, setting a memory limit in kubernetes leads after some days to a situation where the container is killed and restated by the kubernetes scheduler. 

I am not the expert in OS or JDK so I am unable to describe the problem in a better way. But the observation is very obvious.  Maybe you can address this issue in a better place as I still don't have the impression that Payara itself is the cause of the problem. 

If I can do some other time of tests please let me know.

**Comment by rdebusscher** [comment]
Hi Ralph,

From what I read in the referenced bug issue of RedHat, using `WeakReference`s holding native objects seems the cause (or major contributor, to it). Within the Payara codebase, we have several usages of `WeakReference`s but did not check if any of them holds native objects. (but it likely is as it is used in a class related to a classloader.)

Since Java 8 uses by default already the Parallel GC, the 'solution' indicated in the report will not work.

Rudy

**Comment by rsoika** [comment]
Hi Rudy,

yes, I also think that the Parallel GC does not really solve the problem. Currently I observe that the memory consumption in my application running on Payara in Kubernetes increases by about 5MB per day. That could be tolerated somehow. And I still have the hope that the memory increase will slow down at some point. 
But I am surprised that this problem does not generally attract more attention, since it should appear in different application server scenarios. 

Ralph

**Comment by rsoika** [comment]
My observations were totally wrong. The payara server behaves absolutely correctly and uses the memory resources allocated to it. It will not grab more memory as defined by the limits.

I am sorry to have raised this issue in a false way here.
