### ISSUE TITLE
Redeploying war/ear on cluster fails

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara#492]
When deploying an application(war or ear) for the second time on a cluster, the deployment fails with messages that certain parts already exist (virtual server already has a xxx module loaded at...) or are greeted with the 'Error linking in security policy - Inconsistent module state' message in the cluster's logs.

It happens with both simple projects and big projects. Checking the force redeploy checkbox does nothing. We have to restart the cluster instances to alleviate the issue, which kind of beats the purpose of having a cluster. We encounter the issue both at the instances -> applications -> undeploy and also when undeploying via the applications of the DAS.

What's strange is that we don't even get undeployment messages in the nodes when undeploying an application and timers seem to continue running.

**Comment by dorpsidioot** [comment]
Disabling application works, re-enabling them works as well. It's only when undeploying that it looks like the application still runs on the server.

**Comment by dmatej** [comment]
Have you tried also version 4.1.1.154? It seems better, we had the same problem in 4.1.152 ...

**Comment by dorpsidioot** [comment]
Didn't have the issue in 4.1.153, but there we encountered issues with redeploying after a certain time, so upgraded to 4.1.154 and then this issue appeared.

**Comment by smillidge** [comment]
OK thanks we'll investigate.

**Comment by dorpsidioot** [comment]
Will see if we can deploy a snapshot version to our cluster for testing. Is it possible to simply copy the domain.xml from the current to new version to upgrade or is there a preferred upgrade path?

**Comment by smillidge** [comment]
I would wait at the moment as our Jenkins is being temperamental so the pull request hasn't been incorporated yet.
