### ISSUE TITLE
Manage multi-tenant jdbc connection pool in Payara 

### ISSUE THREAD

**Issue by shywei** [payara/Payara#4922]
# Description #
----------
Is there a way to manage(add/delete) the payara JDBC connection pools in java code instead of the server console page?
We have a primary database which stores the connect info of many tenant databases in a springboot project. We need to dynamicly create connection of different database depands on the tenant id.
I used to use the Hikari datasource pool like below:
```
HikariDataSource dataSource = new HikariDataSource();
dataSource.setJdbcUrl("jdbc:postgresql://xxx.xxx.xxx.xx:5432/db");
dataSource.setPoolName(xxx);
dataSource.setUsername(xxx);
dataSource.setPassword(xxx);
dataSource.setDriverClassName(xxx);
```
But how can I make this with the payara JDBC connection pool?
A hard way I can imagine is prepare connection pool for all of the databases in the payara server admin page, and use the tenant id as pool name， then use JNDI to find the proper pool in java code. But this way is too inefficient and requires frequent maintenance.
Any advice?

**Comment by rdebusscher** [comment]
Hi,

You can create the connection pool as indicated and add it to JNDI at startup. This way you loose of course many benefits that Payara offers.

The configuration within the Web Administration console (or when using the command line) can refer to environmet variables. (https://docs.payara.fish/community/docs/5.194/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html)  That way you can use the same setup for all customers but change the tenant id for each of them via a env variable.

If the above does not fit your requirements, can you describe more in detail what you want to achieve.

Best Regards
Rudy

**Comment by svendiedrichsen** [comment]
Eclipselink might also offer a solution to multi-tenancy: https://www.eclipse.org/eclipselink/documentation/2.7/solutions/multitenancy001.htm

**Comment by MeroRai** [comment]
Hi @shywei,

Due to the lack of activity form you, I am closing this issue immediately. If the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Server Community edition and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
