### ISSUE TITLE
Rest client extension ignores metrics annotation extension 

### ISSUE THREAD

**Issue by tatarbogdan** [payara/Payara#4938]
# Description #
----------
Adding metrics annotations on rest client registration 
  ```
  @RegisterRestClient(configKey = "backendClient")
  public interface BackendService {
  
    @GET
    @Path("users/{id}")
    @Counted
    UserDTO getUser(@PathParam("id") UUID id);
}
```
will have no result in generating metrics for the defined rest client.

## Expected Outcome

I would expect the /metrics endpoint to return things like
```
# TYPE application_BackendService_getUser_total counter
application_BackendService_getUser_total 1
```
## Current Outcome

No metrics are generated for the defined rest client.
### Samples

Register a simple custom rest client and annotated one of its methods with a metric specific annotations like `@Counted`
## Context (Optional)

This is probably caused by the order in which the `fish.payara.microprofile.metrics.cdi.extension.MetricCDIExtension` and `org.glassfish.jersey.microprofile.restclient.RestClientExtension` are doing their job. 
It seems that `org.glassfish.jersey.microprofile.restclient.RestClientExtension` is first observing the rest client registration, and it does this before `fish.payara.microprofile.metrics.cdi.extension.MetricCDIExtension` observers the metrics annotations, and as a consequence the `MetricsAnnotationBinding` annotation is not added on the interface that `org.glassfish.jersey.microprofile.restclient.RestClientExtension` is collecting. Because of this missing annotation `MetricsAnnotationBinding`, metrics interceptors like `fish.payara.microprofile.metrics.cdi.interceptor.CountedInterceptor`, will not be find as suitable, and they will not generate any metrics.
## Environment ##

- **Payara Version**: 5.2020.3
- **Edition**: Micro 
- **JDK Version**: 11
- **Operating System**: Mac
- **Database**:

**Comment by AlanRoth** [comment]
Hi @tatarbogdan, can you firstly try to reproduce this issue in the latest release `5.2020.6` otherwise, can you provide a simple to follow scenario on how to reproduce this issue? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by AlanRoth** [comment]
Hi @tatarbogdan, are you able to provide a reproducer?

**Comment by AlanRoth** [comment]
Hi @tatarbogdan, I will unfortunately close this issue due to a lack of reproducer and inactivity. Thank you.
