### ISSUE TITLE
asadmin create-protocol different to GUI create-protocol

### ISSUE THREAD

**Issue by tbugfinder** [payara/Payara#498]
Hello,

it looks like the CLI create-protocol does not create all required values.
If a protocol is created within the GUI some code is added.

```xml
          <protocol name="http-listener-80compareCLI"></protocol>
          <protocol name="http-listener-80compareGUIcreated">
            <http default-virtual-server="server">
              <file-cache></file-cache>
            </http>
          </protocol>


Thanks,

**Comment by smillidge** [comment]
Can you confirm the version of Payara you are using as this sounds similar to https://github.com/payara/Payara/issues/371

**Comment by smillidge** [comment]
Also can you give us the full asadmin create-protocol command you ran?

**Comment by tbugfinder** [comment]
create-protocol http-listener-80compareCLI

**Comment by tbugfinder** [comment]
Payara 4.1.1.154 build 270

**Comment by tbugfinder** [comment]
It's similar to #371 but not the same as I did not refer to a security enable protocol.

**Comment by smillidge** [comment]
OK thanks for the clarification we will try and reproduce here

**Comment by smillidge** [comment]
If you want to create an HTTP Listener from the CLI just run the command below and this creates the listener and the protocol in one go.
```shell
./asadmin create-http-listener --listeneraddress 0.0.0.0 --listenerport 8084 --default-virtual-server __asadmin test-listener
```

**Comment by smillidge** [comment]
If you want to create each step separately then you need to run the commands below
```shell
./asadmin create-protocol test
./asadmin create-http --timeout-seconds 60 --default-virtual-server server test
./asadmin create-network-listener --address 0.0.0.0 --listenerport 8010 --protocol test test-listener
```

**Comment by tbugfinder** [comment]
Isn't GUI and CLI inconsitent in that case ?
If a new protocol is created using GUI shouldn't it be the same as creating it using CLI ?

**Comment by smillidge** [comment]
It's more that the GUI is more limited, it can only create HTTP protocols whereas the CLI is more general.
