### ISSUE TITLE
asadmin delete-jvm-options fails with vendor specific options

### ISSUE THREAD

**Issue by TeroPihlaja** [payara/Payara#4999]
# Description #
----------

Removing vendor specific JVM options is not possible with asadmin

Specifically: ```[Azul-1.8.0.222|1.8.0.260]-XX:+UseOpenJSSE```

## Expected Outcome

JVM option is removed.

## Current Outcome

JVM option is not removed and error is shown:
```No jvm-options were deleted (perhaps they never existed in the configuration)```

## Steps to reproduce (Only for bug reports) 

```
docker run -it -d payara/server-full:5.2020.6
docker exec -it <container id> /bin/bash

asadmin --port 4848
asadmin> list-jvm-options
...
-XX:+UseOpenJSSE   --> JDK versions: min(Azul-1.8.0.222), max(1.8.0.260) (Inactive on this JDK)
...
asadmin> delete-jvm-options "-XX:+UseOpenJSSE"
Enter admin password for user "admin">
No jvm-options were deleted (perhaps they never existed in the configuration)
Command delete-jvm-options executed successfully.
asadmin> delete-jvm-options "[Azul-1.8.0.222|1.8.0.260]-XX:+UseOpenJSSE"
Enter admin password for user "admin">
No jvm-options were deleted (perhaps they never existed in the configuration)
Command delete-jvm-options executed successfully.
asadmin> list-jvm-options
...
-XX:+UseOpenJSSE   --> JDK versions: min(Azul-1.8.0.222), max(1.8.0.260) (Inactive on this JDK)
...
```

## Environment ##

- **Payara Version**: 5.2020.6
- **Edition**: Full
- **JDK Version**: openjdk version "1.8.0_262"
- **Operating System**: Linux + Docker

**Comment by AlanRoth** [comment]
Hi @TeroPihlaja, I was able to delete the option by specifying `-XX\\:+UseOpenJSSE`, most importantly escaping the colon.

`delete-jvm-options "-XX\\:+UseOpenJSSE"`

Let me know if it works for you also.
Thank you,
Alan

**Comment by AlanRoth** [comment]
Hi @TeroPihlaja, I will assume the command is fine for you and it was just misconfiguration - I will be closing this issue as the command works fine.

**Comment by TeroPihlaja** [comment]
Yes. I think so.
