### ISSUE TITLE
Publish an embedded-all artifact to Maven Central?

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#50]
Hi,

We are starting to investigate Payara and we have not found the equivalent of the "glassfish-embedded-al" artifact that that is deployed to Maven Central at [1]. It is useful to have this artifact so we can do some local integration testing against it before moving to the next stage.

[1] http://mvnrepository.com/artifact/org.glassfish.main.extras/glassfish-embedded-all/4.1

**Comment by johndevs** [comment]
Any news on this? 

Would love to embed the webprofile but don't really want to manually download the libs in a otherwise full maven project.

**Comment by smillidge** [comment]
Prep work has just been pulled to switch the group id.

We'll figure out how to push to maven central next.

**Comment by realityforge** [comment]
Great work

**Comment by johndevs** [comment]
@smillidge Great! :+1:

**Comment by phillipross** [comment]
:+1:   +1 for getting the embedded artifacts into maven central

**Comment by MSzturc** [comment]
+1

**Comment by dmatej** [comment]
+1 (or +1000 if I could ;) )

**Comment by smillidge** [comment]
it's on it's way just working through the maven central process

**Comment by phillipross** [comment]
Thanks!  Actually... quick question... are you only planning to publish embedded-all?  Ideally, it would be nice to have payara-embedded-all, payara-embedded-web, and payara-micro in maven central.

It really would be nice to have the "all" & "web" distro zips in maven central as well... but it appears that they still are installed with groupId=org.glassfish.main.distributions, which may be a hurdle.  I believe getting the full distros into maven repos would make it a little more elegant for getting full support for Payara within the arquillian project too.

**Comment by Pandrex247** [comment]
We are indeed putting up all three embedded releases (all, web, and micro) onto Maven Central.

We don't currently have anything planned for putting the full distribution zips up on Maven Central, though if you'd like them up there please feel free to raise an issue for it to see if anybody else wants it as well. And you're right they are still under the `org.glassfish` groupId, so we'd have to change it to our own before we could upload them.

**Comment by smillidge** [comment]
Hi this is there now. 
See http://www.payara.co.uk/using_payara_embedded_and_payara_micro_with_mav

**Comment by realityforge** [comment]
Woohoo!
