### ISSUE TITLE
NPE when get result from JCache - @CacheResult 

### ISSUE THREAD

**Issue by ciment7** [payara/Payara#5000]
# Description #
----------

Hi,

I`m running war application on payara 5.201 (Jakarta EE 8). Sometimes (usually when the application is under heavy load) I got this exception:

```
caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.getJndiNameEnvironment(ComponentEnvManagerImpl.java:161)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.createInvocationContext(JavaEEContextUtilImpl.java:222)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.setInstanceComponentId(JavaEEContextUtilImpl.java:190)
	at fish.payara.nucleus.hazelcast.PayaraHazelcastSerializer.read(PayaraHazelcastSerializer.java:73)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
```

This exception I get when I hit cache by JCache API - @CacheResult. I use multiple payara nodes clustered with multicast options.

This is my snippet of code:
```
 @CacheResult
    public MyObject getScheduleById(@CacheKey Long myObjectId) {
        ...
        
    }

```

## Expected Outcome

It should never throw exception :)

## Current Outcome
Less than 1% of all requests finish with exception.

## Steps to reproduce (Only for bug reports) 

When the cache is under heavy load. 

## Environment ##

- **Payara Version**: 5.201
- **Edition**:  Full
- **JDK Version**: java-11-openjdk-11.0.8.10-0.el8_2.x86_64
- **Operating System**: Linux (Centos 8)

**Comment by AlanRoth** [comment]
Hi @ciment7, can you please try to reproduce this issue in the latest version of Payara Community? (5.2020.6) Please also provide a reproducer ideally following the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by lprimak** [comment]
I think this will be fixed when this PR (or it's subsets) are merged: https://github.com/payara/Payara/pull/4762

**Comment by ciment7** [comment]
> Hi @ciment7, can you please try to reproduce this issue in the latest version of Payara Community? (5.2020.6) Please also provide a reproducer ideally following the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

yes of course, I will try to reproduce this bug on the latest version of Payara Community. I will notify you then. Thanks.

**Comment by AlanRoth** [comment]
Hi @ciment7, do you have any updates on the status of the reproducer?

**Comment by lprimak** [comment]
https://github.com/payara/Payara/pull/5010 should fix this issue

**Comment by ciment7** [comment]
> Hi @ciment7, do you have any updates on the status of the reproducer?

Hi, I can`t reproduce NPE on my local machine or test environment. I don`t have any idea how to reproduce NPE. I wrote stress test, but without the exceptions.

**Comment by AlanRoth** [comment]
Hi @ciment7, 

Without a way of reproducing this issue reliably, I will have to close it. @lprimak believes #5010 will resolve this issue, so I recommend to wait until that is implemented and released and to try to see if it alleviates your problems. 

Feel free to reopen the issue if you find a simple way of reproducing the problem.

Thank you,
Alan
