### ISSUE TITLE
Payara closing JarFiles that are in use

### ISSUE THREAD

**Issue by vootelerotov** [payara/Payara#5001]
# Description #
----------
As described in #4414,  Payara calls `JarFileUtils.closeCachedJarFiles` in multiple places to close JAR files that have been left open.

The method `JarFileUtils.closeCachedJarFiles` affects the whole JVM and does not try to determine why a JAR file is open.

This can cause JARFiles that are in use by a webapp to be shut down by Payara.

A pull request #4441 tried to alleviate a specific issue caused by this, but this does not fix the general problem.

## Steps to reproduce

[payara-repro-app.zip](https://github.com/payara/Payara/files/5573392/payara-repro-app.zip)

1. Build the Maven project attached.
2. Start vanilla copy of Payara Community Edition 5.2020.6
3. Deploy `crashing-app` from the repro app.
4. Make a request against the context of `crashing-app`
5. Deploy `app-that-causes-crashing` while the request is in progress.

This should result in following exception:
```
[#|2020-10-12T10:36:02.815+0300|WARNING|Payara 5.2020|javax.enterprise.web|_ThreadID=102;_ThreadName=http-thread-pool::http-listener-1(4);_TimeMillis=1602488162815;_LevelValue=900;|
  StandardWrapperValve[com.test.CrashingServlet]: Servlet.service() for servlet com.test.CrashingServlet threw exception
java.lang.RuntimeException: java.lang.IllegalStateException: zip file closed
	at com.test.CrashingServlet.doGet(CrashingServlet.java:30)
...
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.access$200(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:519)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
	at com.test.CrashingServlet.doGet(CrashingServlet.java:24)
	... 30 more
```

## Context

I stumbled upon this as part of my work on JRebel. We run our test suites on Payara. This involves deploying a quite large quantity of webapps on a server and this issue causes instability in our tests.

I do understand the issues around re-deployment on Windows, as described in #4414 . And I would be much less surprised if this issue happened when I tried to redeploy app-that-causes-crashing.

However:

1. Is the forceful closure of JarFiles really needed during deployment of the application? Perhaps this could be delayed until undeployment?
2. As I understand this, closing the cached Jarfiles fixes an issue that only affects Windows. Considering the side-effects, this seems like a net negative on Unix. If my understanding is correct, then perhaps this could be limited to only Windows?

## Environment ##
Reproduced on Payara Community Edition:
- **Payara Version**: 5.2020.6

**Comment by AlanRoth** [comment]
Hi @vootelerotov, I have not been able to reproduce this error with your reproducer. Can you confirm my steps are correct?

1. Deploy `crashing-app-1.0-SNAPSHOT.war` on Payara 5.2020.6
2. Using Insomnia, perform a `GET` request to `http://localhost:8080/crashing-app-1.0-SNAPSHOT`
3. Meanwhile the request is running, deploy `app-that-causes-crashing-1.0-SNAPSHOT.war`

The app seems to remain online after deploying the second app and I eventually see the 'OK' message.

Thank you,
Alan

**Comment by vootelerotov** [comment]
Hey @AlanRoth , thanks for having a look.

The steps you listed are correct. And I just confirmed that it reproduces on my machine.

Additional information:
OS: `Debian Unstable (SMP Debian 5.8.14-1, kernel: 5.8.0-3-amd64)`
JDK: `OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-1-b10)`

Also reproduces with JDK 11: `OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1)`

**Comment by vootelerotov** [comment]
We ran into this exception also in our Jenkins cluster, running Ubuntu 18.04.

So this should not be `Debian Unstable` specific.

**Comment by AlanRoth** [comment]
Hi @vootelerotov, I'm still having trouble reproducing it, the only thing I can recommend is to try using the latest Zulu OpenJDK. Do you believe you could submit a PR to fix this yourself? Or perhaps do you have an alternative reproducer I could try?

**Comment by AlanRoth** [comment]
Hi @vootelerotov, any updates on how we should proceed?

**Comment by AlanRoth** [comment]
Hi @vootelerotov, 

I will be closing the issue due to inactivity and I was not able to reproduce the issue with your reproducer. If the issue still persists, please feel free to reopen the issue.

Thank you for your understanding,
Alan
