### ISSUE TITLE
For some possible BATCHSTATUS states, there is no STARTTIME available

### ISSUE THREAD

**Issue by pythonmeister** [payara/Payara#5018]
# Description #
----------

For some states not starttime information is availabe:

![image](https://user-images.githubusercontent.com/48514286/100746878-97a89c80-33e1-11eb-8f6e-835f5f0607c1.png)

## Expected Outcome

I would expect that the start time information should always be available, at least as soon as the state STARTED is reached.

## Current Outcome

See above.

- STARTED: no information
- STARTING: no information
- FAILED: no information

## Steps to reproduce (Only for bug reports) 

None.

## Environment ##

- **Payara Version**: 5.2020.4
- **Full**: Full
- **JDK Version**:11u8 AdoptOpenJDK
- **Operating System**:  Linux
- **Database**: PostgreSQL

**Comment by AlanRoth** [comment]
Hi @pythonmeister, please check this in the latest community version, 5.2020.6, or the upcoming version 5.2020.7.

**Comment by pythonmeister** [comment]
I upgraded to 5.2020.6, at least this one came up so far:
![image](https://user-images.githubusercontent.com/48514286/100802787-512b6000-342a-11eb-979d-d42684a354e4.png)

**Comment by pythonmeister** [comment]
Since the upgrade I also did not see any occurrences of jobs hanging in STARTED or STARTING stage as before, which was the reason to open this ticket. As we processed several hundred batch jobs so far, this seems to fix that problem as well.

**Comment by AlanRoth** [comment]
Hi @pythonmeister,

If you're happy with using 5.2020.6+ then I will close the issue.

Thank you,
Alan

**Comment by pythonmeister** [comment]
Not quite: as you can see from the screenshot, a failed job has no start time, which makes no sense, as it has an end time. I do think this is inconsistent and should be fixed.

**Comment by pythonmeister** [comment]
Here now a case with state COMPLETED, but no start time:
![image](https://user-images.githubusercontent.com/48514286/100893523-bbd8ac00-34bb-11eb-8bf8-fe64b5725c5f.png)

**Comment by AlanRoth** [comment]
Hi @pythonmeister, that does indeed look like a bug, however we would need to know what conditions are required to reproduce this.

Thank you,
Alan
