### ISSUE TITLE
Enhance JSR107 integration to support java.util.Optional

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5026]
# Description #
----------
Imagine code that returns mostly constant values which construction takes noticeable amount of time.

`Optional<NotACheapValue> calculateNotACheapValue(SomeParametersUsedInConstruction p)`

We know that JSR107 may help us reduce time of call transparently:

```
@CacheResult(name = "not-a-cheap-value-cache")
Optional<NotACheapValue> calculateNotACheapValue(SomeParametersUsedInConstruction p)
```

Sadly this implementation won't work because:
1) Hazelcast does not allow nulls as values
2) programmers know Optional and know that it may simplify API and code flow in constrast with null handling
3) Hazelcast enforces keys and values to be serializable, because of network transfer 

So java.util.Optional is not serializable to prevent misuse, but this "optimization" successfuly prevents negative caching. Even if Optional is used as return type as expected.

## Expected Outcome

Optional.empty() or filled optional cached transparently.

## Current Outcome
2020-12-02T20:47:57.474+0100] [Payara 5.2020.6] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=426 _ThreadName=http-thread-pool::http-listener-1(7)] [timeMillis: 1606938477474] [levelValue: 900] [[
  StandardWrapperValve[applicationAdd]: Servlet.service() for servlet applicationAdd threw exception
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'java.util.Optional'

## Context (Optional)

If there will be consensus to implement enhancement, I am going to do it.
## Environment ##

- **Payara Version**: 5+

**Comment by lprimak** [comment]
Would PayaraValueHolder help you in this case?

**Comment by sgflt** [comment]
If you mean implementation of support of java.util.Optional, then probably yes.
If you mean change of API to `PayaraValueHolder calculateNotACheapValue(..)` then no. It changes semantic of Optional.

By the way, I see linked hazelcast issue and I am thinking about native Hazelcast support of Optional. Aren't they going to implement it natively?

**Comment by jerrinot** [comment]
@sgflt fancy sending a pull request directly to upstream Hazelcast?

Given Hazelcast currently does not support `Optional` serialization at all I don't see any compatibility issue => we should be able to include it in 4.2.

**Comment by sgflt** [comment]
@jerrinot sure, clonig hazelcast repo and starting IDE :-) I need just some time to check how is code structured and how it works.

**Comment by lprimak** [comment]
@sgflt would using PayaraValueHolder, which supports NULLs solve your immediate issue vs. using Optionals?

I am not saying that Optional isn't an interesting feature, but I am trying to solve your immediate problem pragmatically

**Comment by lprimak** [comment]
Also, would this help at all?
Upcoming OmniFaces 3.9 will have a Lazy object: https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/util/Lazy.java

**Comment by AlanRoth** [comment]
Hi @sgflt, can I close this issue as it has been taken to Hazelcast?

**Comment by sgflt** [comment]
Hi @AlanRoth of course.

@lprimak PayaraValueHolder has pretty different API, Omnifaces are not needed. It is sufficient to temporarly create own Optional (marked as deprecated) that is serializable and preserves API until next release of Hazelcast.

**Comment by AlanRoth** [comment]
I will close the issue, however feel free to continue the conversation with @lprimak on this issue if you wish.
