### ISSUE TITLE
Feature Request: MP-JWT public key location respects HTTP cache headers / FISH-868

### ISSUE THREAD

**Issue by ghunteranderson** [payara/Payara#5027]
# Description #
----------
Hello again! A feature request this time. 🙂 

This use case applies to MP-JWT with an HTTP(S) public key location. When SignedJWTIdentityStore.java verifies a token, it makes an HTTP request to the public key endpoint to fetch the public keys. This happens every time that service verifies a token. That can quickly turn into a lot of requests for the same data.

IDPs have an option to provide HTTP cache directives on the public key endpoint in hopes of clients using it. I can see multiple benefits to Payara following the max-age directive:
1. Reduced load on the network
2. Reduced load on the IDP
3. Reduced latency to verify a token. This benefit compounds if multiple upstream service calls are required to complete the user's request.
4. Increased fault tolerance to isolated failed network request.

One edge case that I think this feature would need to handle is if the IDP does not use a long enough delay between when a new public key is published and when the new private key is used to sign tokens. A Payara instance could have a "fresh" copy of the public key cache based on the max-age header but start seeing new key IDs on JWTs. One solution would be to force a cache refresh when JWTs with unrecognized key IDs are received.

An alternative solution with similar benefits: Any public key loaded from `mp.jwt.verify.publickey.location` could be cached with a TTL set by a proprietary config in `payara-mp-jwt.properties`. This has the added benefit of decreasing disk IO load when the public key is on the file system and gives the developer control over how long the cache should be active.

## Expected (Requested) Outcome

Payara's MP-JWT implementation would cache public keys fetched over HTTP until
1. The cache expires
2. A new key ID is introduced that doesn't exist in cache

## Current Outcome

Every request that uses MP-JWT will re-load the public key even if it requires an additional network call.

## Environment ##

- **Payara Version**: 5.2020.6
- **Edition**: any
- **JDK Version**: OpenJDK 11
- **Operating System**: any
- **Database**: n/a

**Comment by AlanRoth** [comment]
Hi @ghunteranderson, I have created a internal ticket `FISH-868`, this feature does seems like a good idea!

It may be a while before our engineering team gets around to implementing this, is there any possibility you could attempt to implement this feature yourself and submit a PR as a community contributor? 

Thank you,
Alan

**Comment by ghunteranderson** [comment]
Hi @AlanRoth!

Thanks for the quick response. I'll see what I can get together this weekend. 🙂

**Comment by AlanRoth** [comment]
Closing the issue as PR has been merged, thank you for your contribution
