### ISSUE TITLE
Option to use systemd instead of init.d when creating a service - FISH-895

### ISSUE THREAD

**Issue by simdevmon** [payara/Payara#5052]
# Description #
----------

When Payara is installed as a service on a Linux system, the service is created using **init.d**, which is considered as outdated and most distributions rely on **systemd** instead. 

`./asadmin create-service --serviceuser myuser mydomain`

Therefore it would be nice to have an option to register the service using systemd instead of init.d

## Expected Outcome

systemd service.

## Current Outcome

init.d service.

### Samples

Something similar to this:

```
[Unit]
Description="Payara Service"
After=network.target
StartLimitIntervalSec=0

[Service]
Type=forking
# PIDFile=/run/nmc_payara.pid
EnvironmentFile=-{{ Install_Path }}/bin/environment
WorkingDirectory={{ Install_Path }}/payara5/bin
Restart=no
TimeoutSec=300
Restart=always
RestartSec=20
GuessMainPID=True
User={{ __my_user }}
ExecStart=java -XX:+IgnoreUnrecognizedVMOptions -jar {{ Install_Path }}/payara5/glassfish/lib/client/appserver-cli.jar start-domain mydomain
ExecStop=java -XX:+IgnoreUnrecognizedVMOptions -jar {{ Install_Path }}/payara5/glassfish/lib/client/appserver-cli.jar stop-domain mydomain

[Install]
WantedBy=multi-user.target
```

## Environment ##

- **Payara Version**: 5.2020.6
- **Edition**: Full
- **JDK Version**: OpenJDK 11.0.9
- **Operating System**: Linux

**Comment by MeroRai** [comment]
Hi @simdevmon,

Thank you for rasing this improvement. I have created an internal issue `FISH-895`, however, I will stress that this improvement request may take a long time before it is worked on by our engineering team, due to the sheer number of requests and our priority being customer requests. For this reason, if it is possible I would encourage you to attempt to implement this improvement yourself.  You can read more on contributing to Payara here: https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

Best regards,
Mero

**Comment by MeroRai** [comment]
Hello @simdevmon, starting today we are introducing some relevant changes to our Github Issues Community Policy, which you can read [here](https://github.com/payara/Payara/blob/master/SUPPORT.adoc). The most significant change is that we want to introduce open votes for all suggested enhancements and improvements to the Payara Platform, like the one described in this issue. To this effect, we are going to transition this issue to Voting status and gauge the community interest in your proposal. We know that previously we accepted your request and escalated it to our Platform Development team, but after careful deliberation and analysis, we want to improve our community engagement in a way that’s productive and relevant for our overall user community. We hope that you understand this decision.

**Comment by aubi** [comment]
Hello, this issue is already solved:
https://github.com/payara/Payara/pull/5450
