### ISSUE TITLE
Payara 6 alpha 1 Jakarta EE 9 Compatible Implementation

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#5055]
Make Payara 5 a Compatible Implementation of Jakarta EE 9. We have delivered initial Jakarta EE 9 support. Extend use of the Eclipse Transformer to transform Jakarta EE 9 applications back to Jakarta EE 8 applications as they are functionally equivalent and deploy on the current 5.x server stream.

**Comment by rdebusscher** [comment]
Payara 5 cannot pass the TCK due to 'hardcoded' package names and version numbers in the TCK.

With the help of the Eclipse Transformer, Jakarta EE 9.x applications can be used on Payara 5 (since they are transformed)
