### ISSUE TITLE
5.1.183 version web-glue.jar not working in 4.1.1.163 version

### ISSUE THREAD

**Issue by sivadhatra** [payara/Payara#5064]
# Description #
----------

I'm using Payara 4.1.1.163 version and access logs are not getting deleted after exceeding max-files-history limit. I saw that this issue is resolved in Payara 5.x version. But, because of dependency issues, we can't upgrade Payara server to 5.x version. So, I tried keeping 5.1.183 payara version web-glue.jar in our Payara 4.1.163 version but it's not working. Could someone please possible reason behind this. 

## Expected Outcome

Server should start with limiting access logs files

## Steps to reproduce (Only for bug reports) 
Server started without any errors but access logs are not getting purged

## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by MeroRai** [comment]
Hi @sivadhatra,

The Payara Platform 4 has entered into "Maintenance" lifecycle in February 2019. This means the quarterly updated has stopped – so there are no new features, enhancements, or APIs added. To continue receiving new features and enhancements, you’ll have to upgrade to Payara Platform 5.

Although the Payara Platform 4 has gone into Maintenance, Payara Enterprise Customers of the Payara Platform will continue to receive support for legacy applications, OpenJDK support, backported fixes and platform certifications along with monthly security updates as well as access to our support services. If you are interested in Payara Enterprise, please contact Payara Sales at sales@payara.fish. You can also learn more about Payara enterprise here: https://www.payara.fish/enterprise/.

Finally, as a community user, you can continue to receive suggestions to resolve any issues with Payara Platform 4 through the [Payara Google Forum](https://groups.google.com/g/payara-forum).

Best regards,
Mero Rai

**Comment by sivadhatra** [comment]
Hi @MeroRai 
We are facing issue with Access logs not getting purged. Our code runs on multiple servers and upgrading to 5.x version is not viable option at the moment. I saw there is change in only 1 file for resolving this issue(https://github.com/payara/Payara/pull/2824/files). So, I tried placing latest versions of web-glue jar in present Payara server. However, server is not starting by throwing some errors. Another approach I followed is by building Payara server from payara4 version here -> https://github.com/payara/Payara/tree/Payara4 which has the fix for Access logs issue.  But I faced similar server startup issue.
So, Could you please help me in providing some work around here to resolve this issue.

**Comment by MeroRai** [comment]
Hi @sivadhatra,

As I have mentioned on my previous comment, the Payara Platform 4 has entered into "Maintenance" lifecycle in February 2019. This means only Payara Enterprise Customers will continue to receive support for Payara Platform 4 version releases. If the issue is urgent for you, please contact Payara Sales at sales@payara.fish. You can also learn more about Payara enterprise here: https://www.payara.fish/enterprise/.
