### ISSUE TITLE
wsdeploy fails with jdk 11 - FISH-976

### ISSUE THREAD

**Issue by berniegsfc** [payara/Payara#5067]
# Description #
----------

With JDK 11, wsdeploy fails with the error
> com.sun.tools.javac.Main is not available in the classpath

## Expected Outcome

No error and a war file is produced.

## Current Outcome

> error : com.sun.tools.javac.Main is not available in the classpath

The next to last line of 2020.5/payara5/glassfish/bin/wsdeploy is 

>     exec "$JAVA" $WSIMPORT_OPTS -cp "$AS_INSTALL_LIB/webservices-osgi.jar:$AS_INSTALL_LIB/jakarta.xml.rpc-api.jar:$AS_INSTALL_LIB/jaxb-osgi.jar:$JAVAX_MAIL_JAR:$JAVA_HOME/lib/tools.jar:$AS_INSTALL_LIB/jakarta.jws-api.jar:$AS_INSTALL_LIB/webservices-api-osgi.jar:$AS_INSTALL_LIB/jakarta.activation-api.jar" com.sun.xml.rpc.tools.wsdeploy.Main "$@"

but $JAVA_HOME/lib/tools.jar (which contains the missing class) does not exist in JDK 11.

## Steps to reproduce (Only for bug reports) 

> wsdeploy -o target.war myapp.war

## Environment ##

- **Payara Version**: 5.2020.5
- **Edition**: Full
- **JDK Version**: Zulu11.43+21-CA (build 11.0.9+11-LTS)
- **Operating System**: RHEL 7.9
- **Database**: None

**Comment by MeroRai** [comment]
Hi @berniegsfc,

I have reproduced the issue in our current release of Payara community release. The issue is not related to JDK 11 specifically as I could reproduce it using JDK 8. 

I have now escalated it to our engineering team and created an internal issue `FISH-976` to track it. Thank you for your assist.

**Comment by berniegsfc** [comment]
wscompile has the same problem.

**Comment by MeroRai** [comment]
This is no longer an issue in the latest releases of Payara Server.
