### ISSUE TITLE
Deployment group 500 error always

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#5069]
# Description #
----------

We have environment configured to be using deployment group + nodes/instances to provide services behind load balancer. The problem is that every instance is responding with HTTP 500 error for every URL different than URL with the deployed app. Root url should provide payara welcome page, instead:

![obraz](https://user-images.githubusercontent.com/41665450/103007841-6df01a80-4534-11eb-8691-7dcfb378761e.png)

The same for not existing app - there should be 404, but is 500:
![obraz](https://user-images.githubusercontent.com/41665450/103007879-7b0d0980-4534-11eb-8c69-ca1a1bfbbc06.png)

I spent whole today trying to enable more logs in the logging.properties to catch something, because when there is a 500 error there is nothing logged. But with no luck. If I enable all JULI logging to FINESET level instances even doesn't start (they hang up). I was able to enable grizzly logs but there was nothing wrong there.

Please help - why there is an 500 error in such env? This time to reproduce it, it is quite easy - just create some deployment group env and try to hit HTTP port with some request...

On the other hand the domain which is responsible for managing deployment group is working properly:
![obraz](https://user-images.githubusercontent.com/41665450/103008091-db03b000-4534-11eb-8b78-8fe7e5ad4fbb.png)

## Environment ##

- **Payara Version**: 5.2020.7 (but earlier are affected too - I'm sure this was working properly in 5.191 because we are trying to update from it and then it was ok (it also worked on JDK8)
- **Edition**: Full
- **JDK Version**: zulu11.43.55-ca-jdk11.0.9.1-linux_x64
- **Operating System**:  Linux

**Comment by peterpz1** [comment]
Closing this issue, as it is surely our config issue

**Comment by peterpz1** [comment]
FYI. The problem was because of changing the path for the server logs in (server-config -> "Logger Settings" -> "Log File:"). The log path in (server-config -> Virtual Servers -> server -> "Log File:") was not changed. Since the whole folder didn't exist Virtual Server was not able to log anything and this resulted in strange 500 error. After fixing the paths problem disappeared. You might think about securing it somehow - either add some logs in the server.log or enable Virtual Server to create catalogs and file for logging...

**Comment by sgflt** [comment]
Tested  5.2020.7 on openjdk 11.0.9 and without 500. It probably depends on another specific configuration.
