### ISSUE TITLE
[Enhancement] Be able to use default values in data source definitions when translating values / FISH-992

### ISSUE THREAD

**Issue by cfiguera** [payara/Payara#5079]
# Enhancement request #
----------

When declaring database connections using the <data-source> descriptor in web.xml, we can use environment variables using ${ENV=xxxxx} or MicroProfile properties through ${MP_CONFIG=xxxxx}.

Right now the existing behavior is that if the environment variables are not setted, the application is not deployed due to a database connection error. There are many projects where, for example, the database schema is never modified or test environments where we want non-secret values to be used by default if the environment variables are not setted (i.e: admin/admin).

That is why I think it's interesting to be able to set default values, if the environment variables are not informed, to simplify the deployment of applications especially in local or test environments. This default value could be declared after a colon, as other programming languages do.

### Samples

For example, this configuration:

```
<data-source>
        <name>java:app/mydb</name>
        <class-name>org.postgresql.ds.PGSimpleDataSource</class-name>
        <server-name>${ENV=DB_HOSTNAME}</server-name>
        <port-number>5432</port-number>
        <database-name>${ENV=DB_SCHEMA}</database-name>
        <user>${ENV=DB_USER}</user>
        <password>${ENV=DB_PASSWORD}</password>
</data-source>
```
could be

```
<data-source>
        <name>java:app/mydb</name>
        <class-name>org.postgresql.ds.PGSimpleDataSource</class-name>
        <server-name>${ENV=DB_HOSTNAME:localhost}</server-name>
        <port-number>5432</port-number>
        <database-name>${ENV=DB_SCHEMA:myschema}</database-name>
        <user>${ENV=DB_USER:admin}</user>
        <password>${ENV=DB_PASSWORD:admin}</password>
</data-source>
```

## Tested environment ##

- **Payara Version**: 5.2020.8-SNAPSHOT
- **Edition**: Full
- **JDK Version**: 8u271 - Oracle
- **Operating System**: Ubuntu 18.04
- **Database**: Postgres 9.6

**Comment by AlanRoth** [comment]
Hi @cfiguera, this seems like a good idea! Are you able to implement this feature yourself and submit a PR to our repo? We'll be more than happy to review it! You can leave it to us to pick up, but due to the high volume of community enhancement requests, it may take a while. I have created `FISH-992` to track this request. Thank you.

**Comment by cfiguera** [comment]
Hi @AlanRoth, I have created a PR for this enhancement, it is the first one I create (I hope not the last), hopefully everything is fine and it can be merged soon. Very happy to contribute to this project!

**Comment by lprimak** [comment]
Great job everyone. I have been looking forward to a feature like this for awhile personally
