### ISSUE TITLE
Can't access admin console at localhost:4848 from payara-micro

### ISSUE THREAD

**Issue by BenHunt-io** [payara/Payara#5100]
# Description #
----------

The documentation states, that you are able to access the admin console in payara micro. From the section on way to run admin commands "Send the administration commands from a Payara Server’s DAS".

I'm not able to access the admin console. The logs on server startup don't indicate that there is a console available at 4848 either.

## Expected Outcome
The server should start up an admin console on the port 4848 and display that to the user in the server logs.

## Current Outcome

No admin console is deployed. 

## Steps to reproduce (Only for bug reports) 

1.  mvn clean package
2. java -jar target/test-microbundle.jar

### Samples

https://github.com/BenHunt-io/test

## Environment ##

- **See POM in example project**: 

`$ java -version
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment 20.11-(Zulu-11.43+55-linux_x64)-Microsoft-Azure-restricted (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM 20.11-(Zulu-11.43+55-linux_x64)-Microsoft-Azure-restricted (build 11.0.9.1+1-LTS, mixed mode)
`
`$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /mnt/c/Program Files/maven/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /usr/lib/jvm/zulu-11-azure-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"
`

**Comment by MeroRai** [comment]
Hi @BenHunt-io,

Payara Micro doesn't have it's own Admin Console. Asadmin commands can be sent from the Payara Server DAS to Payara Micro instances that are running within the same data grid as the DAS. You can read more regarding this on https://docs.payara.fish/community/docs/5.2020.7/documentation/payara-micro/asadmin/send-asadmin-commands.html
