### ISSUE TITLE
NPE in OpenAPI around visitPost() parameter type discovery / FISH-1083

### ISSUE THREAD

**Issue by peculater** [payara/Payara#5119]
# NPE in OpenAPI around visitPost() parameter type discovery
----------

For certain methods annotated with `@POST` that take a POJO as a parameter, hk2 can't figure out the type of that parameter and throws a NullPointerException when the /openapi endpoint is requested.  I've got this reproducible if the class that has the annotated method extends an abstract class with the parameter type as a generic.

Full repro example at https://github.com/peculater/payara-openapi-post-npe . 

## Expected Outcome

OpenAPI document shows the correct parameters for the POST method
```
paths:
    ...
    post:
      operationId: sayMessage
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/PostablePojo'
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
```

## Current Outcome

The first call results in a NullPointerException that surfaces as a 500 Internal Server Error.  Subsequent requests show

```
paths:
    ...
    post:
      operationId: sayMessage
      responses: {}
```

## Steps to reproduce (Only for bug reports) 

https://github.com/peculater/payara-openapi-post-npe

### Samples

https://github.com/peculater/payara-openapi-post-npe

## Context (Optional)

Love Payara, love what you're up to, super into using microprofile and openapi.  :-)

## Environment ##

- **Payara Version**: 5.2020.7, first noticed on 5.2020.3, probably earlier than that.
- **Edition**: Full, Web, and Micro
- **JDK Version**: 8 and 11
- **Operating System**: Linux
- **Database**: N/A

**Comment by AlanRoth** [comment]
Hi, thank you for the detailed reproducer, I have been able to reproduce the issue on 5.2021.1. I have created an internal ticket `FISH-1083`.
