### ISSUE TITLE
Update usages of EclipseLink

### ISSUE THREAD

**Issue by dmatej** [payara/Payara#512]
1) GF4 still uses JPA1 persistence.xml (minor thing, but ...)
2) NPE in EclipseLink 2.6.1 - only logged, but it seems finally does not make problems and I hope it should be fixed in 2.7.0. I could not find any solution how to get rid of that stacktrace ...
http://stackoverflow.com/questions/32142789/nullpointer-in-log-during-first-connection-to-database
3) Target server in persistence.xml does not change anything, because it is overriden in class PersistenceUnitLoader (this is a corrent solution - platform is then declared even for deployed applications).
So the only update is in that class, because EclipseLink now supports Glassfish and SunAS9 is deprecated now:
```
         final String ECLIPSELINK_SERVER_PLATFORM_CLASS_NAME_PROPERTY = "eclipselink.target-server"; // NOI18N
         props.put(ECLIPSELINK_SERVER_PLATFORM_CLASS_NAME_PROPERTY,
-                System.getProperty(ECLIPSELINK_SERVER_PLATFORM_CLASS_NAME_PROPERTY, "SunAS9")); // NOI18N
+                System.getProperty(ECLIPSELINK_SERVER_PLATFORM_CLASS_NAME_PROPERTY, "Glassfish")); // NOI18N
```
Result with temporarily set more verbose logging:
```
+ <property name="eclipselink.logging.level" value="FINEST"/>
```
```
[2015-11-05T09:05:57.786+0100] [Payara 4.1] [FINEST] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151105/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.properties] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1446710731051] [timeMillis: 1446710757786] [levelValue: 300] [[
  property=eclipselink.target-server; value=Glassfish; translated value=org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform]]
```
But the NPE still remained because it seems the platform is detected before parsing of persistence.xml ... I will report it to EclipseLink ...

**Comment by dmatej** [comment]
I will try 2.7.0-SNAPSHOT but I'm not sure if it is not too big step with more side effects ...
https://bugs.eclipse.org/bugs/show_bug.cgi?id=463629

**Comment by smillidge** [comment]
We currently use a patched EclipseLink in Payara therefore it should be possible for us to patch the NPE problem into that version.

**Comment by dmatej** [comment]
I tried it with the snapshot, but it seems it is not better - eclipselink logs exception and THEN parses the tagetServer value. I think they should clear what behavior is correct and what is the reason to make it such complicated.
But for Payara this is not a big problem because eclipselink only logs the exception and continues.
