### ISSUE TITLE
Update EclipseLink dependency to 2.7.8

### ISSUE THREAD

**Issue by Werner-Botha** [payara/Payara#5124]
# Description #
----------

All versions of eclipselink can deadlock, this causes applications to become unresponsive.  eclipse link have found and enabled deadlock monitoring on this pull request: https://github.com/eclipse-ee4j/eclipselink/pull/927

this fix was introduced in 2020 December release, version 2.7.8 of eclipselink. 
This will allow us to monitor any deadlocks and the cause of it, as well as add timeouts to prevent the system from becoming unresponsive.

The current payara eclipselink version is 2.7.7 if I'm not mistaken. We would appreciate it a lot if you are able to upgrade to version 2.7.8 of eclipselink

Kind regards

## Expected Outcome

Deadlock monitoring should work and log to a log file

## Current Outcome

System becomes unresponsive due to unknown deadlocks

## Steps to reproduce 

These attributes can be added to the persistence.xml to allow logging and timeouts on deadlocked cache threads.

<property name="eclipselink.concurrency.manager.waittime" value="40000"/>
<property name="eclipselink.concurrency.manager.maxsleeptime" value="40000"/>
<property name="eclipselink.concurrency.manager.maxfrequencytodumptinymessage" value="120000"/>
<property name="eclipselink.concurrency.manager.maxfrequencytodumpmassivemessage" value="300000"/>
<property name="eclipselink.concurrency.manager.allow.readlockstacktrace" value="false"/>
<property name="eclipselink.concurrency.manager.allow.concurrencyexception" value="true"/>
<property name="eclipselink.concurrency.manager.allow.interruptedexception" value="true"/>

This Pull request also includes a example of how to replicate a deadlock in the L2 cache
https://github.com/eclipse-ee4j/eclipselink/pull/927

## Environment ##

- **Payara Version**: 5.202.4
- **Edition**: Server
- **JDK Version**: Amazon Correto 1.8.0 275
- **Operating System**: Linux / Windows
- **Database**: PostGres

**Comment by mafaul** [comment]
It seems like eclipselink 2.7.8 might not have all the fixes, we might need to wait for the next release of eclipselink 2.7.x
See: https://github.com/eclipse-ee4j/eclipselink/pull/1009

**Comment by AlanRoth** [comment]
Hi @Werner-Botha, upgrading to EclipseLink 2.7.8+ will be part of our periodic dependencies upgrade, however, I do not have a timeline I can provide to when that will be.

Thank you for your understanding,
Alan
