### ISSUE TITLE
MPCONFIG variable substitution does not enforce useful error messages / FISH-1079

### ISSUE THREAD

**Issue by poikilotherm** [payara/Payara#5126]
Using `{MPCONFIG=...}` in supported places for variable substitution has no option to make a lookup mandatory. In case some variable is not present, things might fail without a clear error message.

## Expected Outcome

An example:
Using a `DataSourceDefinition` requires user, password etc. If the user cannot be resolved via `{MPCONFIG=my.db.user}`, a `NoSuchElementException` should be thrown to fail the deployment early, stating that the property is missing and it needs to be added.

If failing seems like to harsh, at least there should be a clear log message that the value is empty or null, so people can actually see that sth. is missing.

## Current Outcome

In case of the example above, log messages will indicate that the login at the database didn't work. But it will not be clear why it failed (empty username property).

## Context (Optional)

It would be necessary to refactor [`TranslatedConfigView`](https://github.com/payara/Payara/blob/ccd387de97e8fd9d15768f475d1c9a1c6c5000ed/nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java#L149).

Either be extending it to have two options, making the lookup optional or required. Or by refactoring to warn about empty values that have been requested from the view. The warning is definitely much easier to implement and does not introduce new substitution patterns.

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**: Full
- **JDK Version**: 11
- **Operating System**: Linux
- **Database**: PostgreSQL

**Comment by poikilotherm** [comment]
I just created a little PR to outline the logging approach to this. It's small, but should be useful now that we have the default option (#5079 / #5089 / FISH-992)

**Comment by AlanRoth** [comment]
Hi Poikilotherm, thank you for submitting a PR, I have created `FISH-1079`.
