### ISSUE TITLE
Payara Server 5.2021.1 fails with JDK 15

### ISSUE THREAD

**Issue by Blacktron** [payara/Payara#5127]
# Description #
----------

Unable to run application using Payara Server 5.2021.1 with JDK 15.

## Expected Outcome

Run application server successfully.

## Current Outcome

Unable to start the server, it gets stuck as below:
[2021-02-13 11:41:27,830] Artifact Payroll:war: Waiting for server connection to start artifact deployment...
Detected server admin port: 4848
Detected server http port: 8080
Attempting to start domain1.... Please look at the server log for more details.....

## Steps to reproduce (Only for bug reports) 

1. Create a sample JavaEE project using JDK 15
2. Configure Payara Server 5.2021.1 as run configuration
3. Run the application

## Environment ##

- **Payara Version**: 5.2021.1
- **Edition**: Full
- **JDK Version**: OpenJDK 15.0.2_7
- **Operating System**: Windows
- **Database**: MySQL

**Comment by pzygielo** [comment]
https://docs.payara.fish/community/docs/5.2021.1/general-info/supported-platforms.html

**Comment by lprimak** [comment]
Thanks @pzygielo
