### ISSUE TITLE
RejectedExecutionException when running scheduled task

### ISSUE THREAD

**Issue by dtsitses** [payara/Payara#5128]
# Description #
----------

I'm on Payara 5.2020.7 and occasionally get a RejectedExecutionException when attempting to run the scheduled task below.

```
@PersistenceContext(unitName = "myPersistenceContextName")
    protected EntityManager em;

@Schedule(hour="4", persistent=false)
public void trimUndoStack_KitchenDisplayScreens() throws Exception {
    em.createNamedQuery("pct_trim_UndoStack_KitchenDisplayScreens")
        .setParameter(1, undoStackDepth_kitchenDisplayScreens)
        .executeUpdate();
}
```

The subject query is just a call to a native procedure on MySQL
```
@NamedNativeQueries({
	@NamedNativeQuery(name="pct_trim_UndoStack_KitchenDisplayScreens", query="{call pct_trim_UndoStack_KitchenDisplayScreens(?)}")
})
```

## Expected Outcome

The scheduled task should execute without a problem, consistently.

## Current Outcome

The scheduled task sometimes executes correctly, but sometimes it raises the following exception:

```
SEVERE: doSelect exception 
java.util.concurrent.RejectedExecutionException: The thread pool's task queue is full, limit: 256 
    at org.glassfish.grizzly.threadpool.AbstractThreadPool.onTaskQueueOverflow(AbstractThreadPool.java:470) 
    at org.glassfish.grizzly.threadpool.SyncThreadPool.execute(SyncThreadPool.java:82) 
    at org.glassfish.grizzly.threadpool.GrizzlyExecutorService.execute(GrizzlyExecutorService.java:137) 
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.executeIoEvent(WorkerThreadIOStrategy.java:77) 
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:66) 
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:391) 
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:360) 
    at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:324) 
    at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:255) 
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) 
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) 
    at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce (Only for bug reports) 

I cannot replicate the issue consistently, it occurs sometimes.

1 - Create a web application and schedule a task using the code I have provided above.
2 - Deploy the application
3 - create a client that will send requests to the server at regular intervals, to use up the server's thread pool? I don't really know the condition that might trigger the issue, I haven't been able to figure it out.
4 - experiment with different intervals of the scheduled task, until you can replicate the Exception I posted above

## Context (Optional)

This is an EJB / JPA web application. The scheduled task invokes a native procedure on MySQL to trim the size of some temp tables. The interface to the database is mysql-connector-java-5.1.42-bin.jar

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**:  Full
- **JDK Version**: Oracle JDK 1.8.0_281
- **Operating System**: OS X 10.15.7
- **Database**: MySQL 5.7.23 (MySQL Community Server (GPL))
- **JDBC Driver**: mysql-connector-java-5.1.42-bin.jar

**Comment by AlanRoth** [comment]
Hi @dtsitses, can you provide a simple reproducer application for us to use, running on 5.2021.1? Thank you.

**Comment by dtsitses** [comment]
Hi @AlanRoth, I can't reproduce the issue reliably, I am not able to supply a reproducer app unfortunately.

**Comment by lprimak** [comment]
I don't see how these issues are at all related.
`@Schedule` thread pool is not the same as Grizzly thread pool, which is what the stack trace shows.

**Comment by dtsitses** [comment]
The exception was written in the log right after the scheduled task was executed (e.g., trimUndoStack_KitchenDisplayScreens()). It could be a coincidence.

**Comment by lprimak** [comment]
There may be some other interactions... for example, does this method block all other method processing in the app somehow and thus causing Grizzly to block and run out of operations when new web requests are coming in?
Debugger / thread dump can be helpful here.

**Comment by lprimak** [comment]
Also, if this method is taking a long time and is part of a `@Singleton` this may happen. Try making this `@Stateless` so it doesn't lock the whole application, and move it out into a separate class from anything else

**Comment by dtsitses** [comment]
It is in a `@Stateless` class. Also the system was idle with very little work to do, it's a test system. `trimUndoStack_KitchenDisplayScreens()` probably had no work to do.

I assumed the scheduled task was the culprit but I think you are right, the timing was probably a coincidence. I just scanned the log and found that this exception has also been recorded in other random times when `trimUndoStack_KitchenDisplayScreens()` did not run.

**Comment by lprimak** [comment]
Maybe it's a DDOS attack?

**Comment by dtsitses** [comment]
Its unlikely, it’s my development system on my localhost and my home firewall does not let in outside traffic.

Btw, outside this odd exception that appears sometimes in the logs, the system continues to respond. I don’t know if that would still be the case in a production load.

**Comment by smillidge** [comment]
A hint would be the thread name of the thread dumping the stack. It's not in your snippet.

**Comment by dtsitses** [comment]
I cleared the log last night and went to bed. This is what it looked like this morning (attaching server.log)
[server.log](https://github.com/payara/Payara/files/6054028/server.log)

Btw, I disconnect my machine from the WiFi overnight.

**Comment by AlanRoth** [comment]
Hi @dtsitses, how would you like to proceed? We're not able to accept your issue without being able to reproduce it. We also welcome you to submit a PR to fix the issue if you know what may be the culprit. Thank you.

**Comment by dtsitses** [comment]
Hi Alan,

I do see the issue regularly in my logs, so the problem does exist. I’ll update this ticket with any more info I discover later on. I don’t have any more clues about it at the moment.

**Comment by AlanRoth** [comment]
Hi @dtsitses, have you been able to investigate any clues on this ticket?
