### ISSUE TITLE
Authorization Service not starting

### ISSUE THREAD

**Issue by Awordes** [payara/Payara#5134]
On payara-5.2021.1 starting with jdk1.8.0_201 do not starting Authorization Service with custom login realm. I add realm in server-config Security and enable Default Principal To Role Mapping. But when payara starting, in logs no information about Authorization Service and realms loading.

My domain.xml:

```
  <security-configurations>
    <authentication-service default="true" name="adminAuth" use-password-credential="true">
      <security-provider provider-name="adminSpc" name="spcrealm" type="LoginModule">
        <login-module-config control-flag="sufficient" module-class="com.sun.enterprise.admin.util.AdminLoginModule" name="adminSpecialLM">
          <property name="config" value="server-config"></property>
          <property name="auth-realm" value="admin-realm"></property>
        </login-module-config>
      </security-provider>
      <security-provider provider-name="adminFile" name="filerealm" type="LoginModule">
        <login-module-config control-flag="sufficient" module-class="com.sun.enterprise.security.auth.login.FileLoginModule" name="adminFileLM">
          <property name="config" value="server-config"></property>
          <property name="auth-realm" value="admin-realm"></property>
        </login-module-config>
      </security-provider>
    </authentication-service>
    <authorization-service default="true" name="authorizationService">
      <security-provider provider-name="simpleAuthorizationProvider" name="simpleAuthorization" type="Simple">
        <authorization-provider-config name="simpleAuthorizationProviderConfig" support-policy-deploy="false"></authorization-provider-config>
      </security-provider>
    </authorization-service>
  </security-configurations>
```

.....

```
<auth-realm classname="com.sun.enterprise.security.auth.realm.file.FileRealm" name="admin-realm">
          <property name="file" value="${com.sun.aas.instanceRoot}/config/admin-keyfile"></property>
          <property name="jaas-context" value="fileRealm"></property>
        </auth-realm>
        <auth-realm classname="com.sun.enterprise.security.auth.realm.file.FileRealm" name="file">
          <property name="file" value="${com.sun.aas.instanceRoot}/config/keyfile"></property>
          <property name="jaas-context" value="fileRealm"></property>
        </auth-realm>
        <auth-realm classname="com.sun.enterprise.security.auth.realm.certificate.CertificateRealm" name="certificate"></auth-realm>
        <auth-realm classname="ru.git.gkh.sec.GkhRealm" name="GkhRealm">
          <property name="jaas-context" value="GkhRealm"></property>
        </auth-realm>
```

....
`
<jvm-options>-Djava.security.auth.login.config=${com.sun.aas.instanceRoot}/config/login.conf</jvm-options>
`
.....

What it mean and how to enable Authorization Service with my custom realm?
Thank you.

**Comment by AlanRoth** [comment]
Hi @Awordes, are you able to provide a reliable reproducer application that showcases your issue? Please use the latest version, 5.2021.1. Thank you.

**Comment by Awordes** [comment]
Hi @AlanRoth, I got this issue before deployng app. As far as I understand, the initialization of the authorization service should occur at the start of the payara, even without the application. I can provide the domain where I get the issue.

**Comment by AlanRoth** [comment]
Hi @Awordes, what do you expect to be logged? Can you check that the authorization service is available after starting Payara?

**Comment by Awordes** [comment]
Hi @AlanRoth.
I have an application that worked on version 4.1.1.171. When porting an application to version 5.2021.1, I received an authorization error. Studying the logs, I noticed that in the fourth payara there is such a log that occurs before the application is deployed at the start of the share:

```
09.02.2021 12:12:46.398 INFO  javax.enterprise.bootstrap - Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
09.02.2021 12:12:57.230 INFO  javax.enterprise.security.services - Authorization Service has successfully initialized.
09.02.2021 12:12:57.246 INFO  j.enterprise.system.core.security - Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
09.02.2021 12:12:57.254 INFO  o.g.h.s.s.BackingStoreFactoryRegistry - Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry
09.02.2021 12:12:57.256 INFO  j.enterprise.system.core.security - Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
09.02.2021 12:12:57.261 INFO  j.enterprise.system.core.security - Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.
09.02.2021 12:12:57.273 INFO  j.enterprise.system.core.security - Realm [GkhRealm] of classtype [ru.git.gkh.sec.GkhRealm] successfully created.
09.02.2021 12:12:57.273 INFO  o.g.h.s.s.BackingStoreFactoryRegistry - Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry
09.02.2021 12:12:57.274 INFO  f.p.h.h.s.HazelcastBackingStoreFactory - Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast
09.02.2021 12:12:57.298 INFO  javax.enterprise.system.core - Grizzly Framework 2.3.27 started in: 27ms - bound to [/0.0.0.0:8080]
09.02.2021 12:12:57.310 INFO  javax.enterprise.system.core - Grizzly Framework 2.3.27 started in: 1ms - bound to [/0.0.0.0:8181]
09.02.2021 12:12:57.324 INFO  javax.enterprise.system.core - Grizzly Framework 2.3.27 started in: 1ms - bound to [/0.0.0.0:4848]
09.02.2021 12:12:57.365 INFO  javax.enterprise.system.core - Grizzly Framework 2.3.27 started in: 2ms - bound to [/0.0.0.0:3700]
```
I am interested in launching a realm `GkhRealm`.

But in the fifth, there is no launch of the authorization service, which I believe is the reason why the authorization does not work for the application.

Yes, I check the authorization on the application. But as far as I understand, the launch of the authorization service should occur at the start of the payara.

**Comment by AlanRoth** [comment]
Hi @Awordes, 

We can't accept your issue without a reliable reproducer. I understand that you are experiencing issues with the authorization service, but it seems like you require more intensive support which we cannot offer here. If you wish, you can consult the community on the [Payara Forum](https://groups.google.com/g/payara-forum) or speak with our sales department about a potential Enterprise license. 

Thank you,
Alan

**Comment by AlanRoth** [comment]
Hi @Awordes, do you have any updates on this issue?

**Comment by Awordes** [comment]
Hi @AlanRoth, no, I have same issue. I use the community version and cannot get the Enterprise license, so I cannot get more information on my problem....

**Comment by AlanRoth** [comment]
Hi @Awordes, I will recommend having a look at the [Payara Forum](https://groups.google.com/g/payara-forum) in that case, if you are able to provide clear reproduction steps for the issue you are facing, I'll be happy to investigate, otherwise, my hands are tied.

Thank you for your understanding,
Alan

**Comment by Awordes** [comment]
Hi @AlanRoth , if you do the opposite, Can you provide a case in which authorization works as it should?

**Comment by AlanRoth** [comment]
Hi @Awordes, 

I notice that the Authorization service is not reported as successfully initialized in any Payara 5 version, this is probably due to the many security service changes and how they are logged in Payara 4 and Payara 5. You may notice in Payara 5.2021.1 that it now reports 'Security Service(s) started successfully' instead. I do not believe there have been any breaking changes that have been introduced that stop the Authorization service from starting, only that the way the successful initialization of the Security Service being logged has changed. I believe the reason your custom authentication realm may not be working is due to those changes between Payara 4 and Payara 5, you may be missing some configuration. However, this would require further investigation.

If you require any examples you can have a look at [Payara Examples](https://github.com/payara/Payara-Examples) or [Vendoree samples](https://github.com/javaee-samples/vendoree-samples/tree/master/payara).

You can download our [Authentication & Authorization guide](https://www.payara.fish/page/authentication-and-authorization-stores-in-payara-platform/?hsCtaTracking=1e4c6b99-f75d-431c-827a-3e939e6af8e6%7Cc928e470-68d7-4d66-8841-654b2d5c1f8e), check out our[ Securing a REST service](https://blog.payara.fish/securing-a-rest-service) blog, as well as our [Payara Server 4 to Payara Server 5 Migration Guide](https://info.payara.fish/payara-server-4-to-payara-server-5-migration).

Thank you for your understanding,
Alan
