### ISSUE TITLE
Default return value for @CacheResult overwrites existing value

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara#515]
Reproduction steps:

1. Build the [rest-jcache](https://github.com/mikecroft/Payara-Examples/tree/master/rest-examples/rest-jcache) Payara Example
2. Spin up a couple of Payara Micros
    * nohup java -jar /opt/payara/payara-micro-prerelease.jar --autoBindHttp --deploy rest-jcache.war &
    * `GET` returns "No Value" which is the default:
    ```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @CacheResult(cacheName = "rest-jcache")
    public String getJSON(@PathParam("key") @CacheKey String key ) { 
        return "No Value";
    } 
    ```
3. `PUT` some data into the cache
    * `GET` returns the new value for key
4. Spin up another Payara Micro
    * `GET` now returns "No Value" again (from all cluster members)

These steps are simplified from the way I did it, which was to have instances across two AWS EC2 instances which clustered via TCP joiner. I will hopefully get everything uploaded to a repo for easy reproduction soon.

**Comment by smillidge** [comment]
This is a bug in the rest-jcache example @PathParam should be @QueryParam see https://github.com/payara/Payara-Examples/pull/21
