### ISSUE TITLE
Web service endpoint deployment events listener sometimes it starts other times it doesn't

### ISSUE THREAD

**Issue by banuelosvaquera** [payara/Payara#5150]
# Description #
----------

I'm doing a migration from Glassfish 3.12 to Payara 5.2021.1 after deploying my ear everything works correctly, however when restarting the service, sometimes the application endpoints are not loaded and an http 404 is shown. no error in server.log, the application runs correctly the logs it generates write correctly only the wsdl does not load showing the http 404.

Comparing the server.log of when it starts and when I do not find that when it does not start, these messages do not appear:
[2021-03-04T10:59:35.671-0600] [Payara 5.2021.1] [INFO] [AS-WSMETROGLUE-10010] [javax.enterprise.webservices.metroglue] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1614877148374] [timeMillis: 1614877175671] [levelValue: 800] [[
  Web service endpoint deployment events listener registered successfully.]]

[2021-03-04T10:59:39.465-0600] [Payara 5.2021.1] [INFO] [AS-WSMETROGLUE-10001] [javax.enterprise.webservices.metroglue] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1614877148374] [timeMillis: 1614877179465] [levelValue: 800] [[
  Loading WS-TX Services. Please wait.]]

## Environment ##

- **Distribution**: Payara Server 5.2021.1 #badassfish (build 2818)
- **JDK Version**: jdk-11.0.8
- **Operating System**: Wndows Server 2016 Std

**Comment by MeroRai** [comment]
Hi @banuelosvaquera, 

Please, can you provide a simple to follow scenario of how to reproduce this on the latest release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by MeroRai** [comment]
Hi @banuelosvaquera, since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition at that point in time.
