### ISSUE TITLE
Class Not Found Exception - IIOPSSLSocketFactory

### ISSUE THREAD

**Issue by mlb1141** [payara/Payara#516]
I am trying to use JNDI in a standalone client to lookup an EJB deployed on the Payara server.  I am getting a "RunTimeException" Orb initialization error"  which was "Caused by: java.lang.ClassNotFoundException: org.glassfish.enterprise.iiop.impl.IIOPSSLSocketFactory".  I have included "fish.payara.extras:payara-embedded-all" from MavenCentral.I have also included my local file Payara/payara41/glassfish/modules(\*\*/javax\*.jar; jsf-api.jar, and security.jar) files.  In addition I have included Payara/payara41/glassfish/lib/\*.jar files.  Any thoughts on what I might be doing wrong will be greatly appreciated.

**Comment by smillidge** [comment]
IIOPSSLSocketFactory is in Payara/payara41/glassfish/modules/orb-iiop.jar

**Comment by smillidge** [comment]
Strictly you should add the  Payara/payara41/glassfish/lib/gf-client.jar for your standalone client classpath. However DO NOT MOVE the jar as in its Manifest  Classpath entry it references all the other jars it needs.

**Comment by smillidge** [comment]
Fixed by #552
