### ISSUE TITLE
asadmin create-password-alias is very slow when there are many aliases created / FISH-1311

### ISSUE THREAD

**Issue by AngelTG2** [payara/Payara#5167]
# Description #
asadmin create-password-alias works well with few aliases. The problem arises when there are many aliases in domain-passwords file.
In my case, I've more than 800 aliases in domain-passwords file (mainly database password)
When I run asasdmin create-password-alias takes more than 4 minutes to finish.

## Steps to reproduce ## 
1.- Create a test domain
```
asadmin create-domain test  (default admin and master password)
asadmin start-domain test
asadmin login
```

2.- Create 800 password alias. 

```
#!/bin/bash
PWFILE=/var/tmp/aspwfile.txt
echo "AS_ADMIN_ALIASPASSWORD=test" > $PWFILE
for ALIAS in {1..800}
do
   echo $(date +"%Y%m%d %H:%M:%S") - Alias ${ALIAS}
   asadmin --passwordfile $PWFILE create-password-alias alias_${ALIAS}
done
echo $(date +"%Y%m%d %H:%M:%S") - Fin
rm $PWFILE
```

The response time grows up when there are more aliases.
As you can see in the log file attached, the creation of the first aliases ends in few seconds (2 or 3 seconds). With 50 alias ends in 20 seconds. With 100 alias ends after 35 second. With 200 takes 1 minute. And After 800 takes 4 minutes.

I've attached a zip with the script, the domain-passwords file and the log file.
[test.zip](https://github.com/payara/Payara/files/6169824/test.zip)

## Environment ##

- **Distribution**: Server Full Profile (5.2021.1)
- **JDK Version**: OpenJDK 11
- **Operating System**: CentOS 7

**Comment by svendiedrichsen** [comment]
@AngelTG2 Did you ever try to use a command file? You could create this file in your loop containing the `create-password-alias` commands and have a single `asadmin` call using this file. To my knowledge `asadmin` does a network call which always causes some delay for establishing the connection.

**Comment by AngelTG2** [comment]
@svendiedrichsen Thanks you for your suggestion. The spended time is a little less, but not significant.
The growth is quite linear, but the expected result is to be the same time for all requests.
If I add a password alias, I expect it should be independent if 10 aliases or 800 were created before. In the test, if there were 10 aliases created ends in 2 seconds, but if there were 800 ends after 4 minutes.
The real problem is not getting a static domain password file with 800 aliases, but creating password aliases when I need it. If I have 800 aliases and I need to create 1 new password aliases, it takes more than 4 minutes (regardless of using asadmin multimode )

**Comment by AlanRoth** [comment]
Hi @AngelTG2, I have been able to confirm this behaviour, however, this is expected behaviour inherited from Glassfish, and is not considered a bug as the command is functioning properly - performance is acceptable for more reasonable amounts of password aliases.

I have re-tagged the issue as an enhancement as you are requesting an improvement in performance. I will remind you that 800 password aliases are an extreme case in any environment, such requirements would better be suited in a separate store to manage the passwords in that case.

Feel free to garner attention to the issue to encourage votes, or if you believe you can implement a solution feel free to raise a PR,
Thank you for your understanding,
Alan

**Comment by smillidge** [comment]
This is a function of how create-password-alias works. Basically for safety purposes when an update to the keystore is made e.g. adding a new password alias. The keystore is duplicated and each existing entry is copied into the new duplicate and then written to disk. As this happens each time you create a new alias I would expect to this to grow linearly. The reason is to provide a backup of the keystore which can be restored in case there is a failure in the update.

**Comment by svendiedrichsen** [comment]
How about having a command `create-password-aliases` which accepts a file with a number of aliases and create them in one go?

**Comment by AlanRoth** [comment]
Hi @svendiedrichsen if that is a feature you'd like then feel free to raise your own enhancement request, or up vote this issue.

**Comment by AngelTG2** [comment]
@svendiedrichsen, In my case I don't have a list of password aliases to create simultaneously. I usually create 3 or 4 password aliases per month, so in my case I don't get any improvement if I use a list of aliases to create it.

**Comment by AngelTG2** [comment]
@smillidge, Thanks for the information

I've traced writeKeyStoreSafe and I've seen that the line that consumes most of the time is line 302
https://github.com/payara/Payara/blob/b263fb8b7eab9fee664cd8b0a9457ed3dc96cdd0/nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/PasswordAdapter.java#L302

If I understand the writeKeyStoreSafe method of PasswordAdapter class this is what it runs:
1.- If keyfile exists:
  1.1.- Duplicate keystore in newKeyStore using a masterPassword (consumes most of the time)
  1.2.- Rename keyfile to keyfile.save
  1.3.- Write newKeystore to keyfile
  1.4.- Update pwdStore and masterPassword
  1.5.- If step 1.3 fails try to rename keyfile.save to keyfile
  1.6.- Delete keyfile.save
2.- If keyfile doesn't exist then write keystore to keyfile

The key is inserted in pwdStore before this method is called, so exceptions related to adding a new key in pwdStore are not checked in this method.
I'm not sure, but It seems that step 1.1 (duplicate keyStore - line 302) is only usefull if masterPassword is changed.
If the newKeyStore object is only created when the masterpassword is changed, it seems that the result is the same and the security of writeKeyStoreSafe method is nof affected.

If line 302 is replaced with these lines the alias is created only in 2 seconds instead 4 minutes.
```
final KeyStore newKeyStore;        	
if (Arrays.equals(masterPassword, this.masterPassword)) {
  newKeyStore = this.pwdStore;
} else {
  newKeyStore = duplicateKeyStore(masterPassword);
}
```

**Comment by smillidge** [comment]
That seems reasonable as the biggest risk of corruption is with a changed masterPassword as the domain would be inoperable. Do you want to make a PR and I can review?

**Comment by AngelTG2** [comment]
Thanks @smillidge 
I've just create a PR

**Comment by smillidge** [comment]
@AlanRoth as we have a PR can you create a JIRA reference and tag the correct target Enterprise and Community releases.
