### ISSUE TITLE
Bug Report: Load of REST application is very slow (120 seconds) when there are many password aliases created / FISH-1315

### ISSUE THREAD

**Issue by AngelTG2** [payara/Payara#5177]
# Description #
----------
I've several applications with REST services. The load of each application takes more than 120 seconds.
I've seen that the problem is that I've more than 800 password aliases created. If I empty domain-password file then the application loads in less than 1 second.

## Steps to reproduce ## 
I've attached a zip file than includes: test.war, test.java and a domain-password file with 800 aliases.
[test.zip](https://github.com/payara/Payara/files/6220346/test.zip)

1. Create and start test domain (`asadmin create-domain test; asadmin start-domain test`)
2. Deploy sample application (`asadmin deploy test.war`). It takes only **544ms**.
```
[2021-03-29T09:44:46.228+0200] [Payara 5.2021.1] [INFORMACIÓN] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617003886228] [levelValue: 800] [[

  Loading application [test] at [/test]]]

[2021-03-29T09:44:46.334+0200] [Payara 5.2021.1] [INFORMACIÓN] [] [javax.enterprise.system.core] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617003886334] [levelValue: 800] [[
  test was successfully deployed in 544 milliseconds.]]
```
3. Create 800 password aliases (takes many hours) or copy the attached domain-password file
```
#!/bin/bash
PWFILE=/var/tmp/aspwfile.txt
echo "AS_ADMIN_ALIASPASSWORD=test" > $PWFILE
for ALIAS in {1..800}
do
   asadmin --passwordfile $PWFILE create-password-alias alias_${ALIAS}
done
rm $PWFILE
```
4. Redeploy test application (`asadmin deploy --force test.war`). It takes **133.186ms**.
```
[2021-03-29T09:49:57.832+0200] [Payara 5.2021.1] [INFORMACIÓN] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617004197832] [levelValue: 800] [[
  Loading application [test] at [/test]]]

[2021-03-29T09:49:57.902+0200] [Payara 5.2021.1] [INFORMACIÓN] [] [javax.enterprise.system.core] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617004197902] [levelValue: 800] [[
  test was successfully deployed in 133.186 milliseconds.]]
```

The problem is when the application is loading. If I divide the deploy in several phases, the loading takes **2m12.324s**.

```
$ asadmin undeploy test
$ asadmin deploy --target domain test.war

[2021-03-29T09:50:41.870+0200] [Payara 5.2021.1] [INFORMACIÓN] [] [javax.enterprise.system.core] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617004241870] [levelValue: 800] [[
  test was successfully deployed in 142 milliseconds.]]

$ time asadmin create-application-ref --target server test
[2021-03-29T09:53:23.369+0200] [Payara 5.2021.1] [INFORMACIÓN] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=181 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1617004403369] [levelValue: 800] [[
  Loading application [test] at [/test]]]

 real    2m12.324s
 user    0m3.295s
 sys     0m0.483s
```
## Environment ##

- **Distribution**: Server Full Profile (5.2021.1)
- **JDK Version**: OpenJDK 11
- **Operating System**: CentOS 7

**Comment by AlanRoth** [comment]
Hi @AngelTG2, having 800 password aliases is a very taxing process, as all of them have to be encrypted and decrypted on use, this is why you are seeing a performance hit on deploying your application.

Having so many password aliases is an extreme case, the usual amount is ~30. I understand you may have a specific use case, but the fix would either be to store the passwords in plaintext or using a faster encryption algorithm - which both may compromise the security of the server.

Thank you for raising the issue and thank you for your understanding,
Alan

**Comment by AngelTG2** [comment]
@AlanRoth , I'm sorry for writing a comment in a closed issue. Please, tell me if you prefer I open a new issue.

I've found a possible solution for this issue that not compromise the security of the server.
The problem is related to Microprofile OpenAPI. When the application is registered in OpenApi, the config of Microprofile is read and use all the config sources to load all properties. PasswordAliases are included in these config sources, so all aliases are read and, in my case, take more than 2 minutes. 
I think I have 2 ways to resolve the problem:
1.- Disable passwordAlias config source. I have only found a way to change the ordinal but not disable it. Is there a way to disable a config source?
2.- Disable OpenAPI. I don't use OpenAPI, so in my case this could be a solution. The problem is that even if OpenAPI is disabled, OpenAPI Service register the app. It seems than disabling OpenAPI only affect the accesibility of the /openapi url.
Is necessary to load OpenAPI Engine when OpenAPI is disabled?

Line 114 ends loading microprofile config and in my case takes more than 120 seconds

https://github.com/payara/Payara/blob/1874949a73b79f10289373d87f4af051d5ee7da5/appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java#L114

The register of the application in OpenAPI could be done only if OpenAPI is enabled changing the previus line by the following:
```
if (this.enabled) {
    documents.put(applicationId, new OpenAPISupplier(applicationId, contextRoot, archive, classLoader));
}
```
With 30 password aliases the time reduction is not significant, but In my case, the REST application is loaded only in 2 seconds instead 120 seconds. I've 12 REST application, so the startup of the server is reduced in more than 1300 seconds.

**Comment by AlanRoth** [comment]
Hi @AngelTG2,

Don't worry about commenting on a closed issue, seems like you have some valuable information to add.

I don't believe there is a way of disabling a config source. I can re-open your issue as an enhancement request, and if you wish you can submit a PR for the openapi change.

Thank you,
Alan

**Comment by AngelTG2** [comment]
Thank you @AlanRoth,
I've just submit a PR
