### ISSUE TITLE
Upstream bug: Eclipselink ignores timeout unit when calling execute update

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5183]
# Description #
----------
Bug almost 6 years hidden, but has been revealed by change of default timeout unit from SECONDS to MILLISECONDS.

Fix is straight forward - update dependency on eclipselink to fixed version.

## Context

See https://github.com/eclipse-ee4j/eclipselink/issues/1056

**Comment by AlanRoth** [comment]
Hi @sgflt,

Sadly due to the lack of votes I will be closing your issue.

However, eclipselink in Payara has received component upgrades since you have opened the issue, you could confirm if it is now using the fixed version.

Thank you,
Alan

**Comment by sgflt** [comment]
Fixed by https://github.com/eclipse-ee4j/eclipselink/pull/2161
