### ISSUE TITLE
how to delete "general" jndi entry

### ISSUE THREAD

**Issue by mlb1141** [payara/Payara#519]
I have a jndi entry that I can see when I do the following command:
asadmin list-jndi-entries
It is not an "external" or "custom" jndi entry; therefore it does not  show up in the admin console.
If I run asadmin list-jndi-resources, nothing is listed.
Is there a way for me to delete this "general" jndi  entry.

**Comment by smillidge** [comment]
Could you tell us what the general entry is. There are a lot of internal entries that Payara keeps. The console only displays custom or external jndi entries that you create through the console or via the CLI.

**Comment by mikecroft** [comment]
@mlb1141 can you paste the output of `asadmin list-jndi-entries` and tell us which entry you wanted to delete?

**Comment by mikecroft** [comment]
@mlb1141 I'm going to assume that this is no longer an issue for you. I haven't been able to reproduce it. Please reopen this with the output of `asadmin list-jndi-entries` and we'll look into it.
