### ISSUE TITLE
Web admin console says "GlassFish(tm)" in top panel instead of "Payara(tm)"

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#520]
The top panel of the Web admin console of Payara 4.1.1.154 says "GlassFish(tm)", while it certainly should read "Payara(tm)"! :-)

**Comment by smillidge** [comment]
Try shift-refresh if you've just been using GlassFish.

**Comment by mkarg** [comment]
Thank you for this tip! It solves the issue! :-)
