### ISSUE TITLE
Bug Report:  ClassCastException when calling protected SOAP Web service: class com.sun.xml.ws.message.saaj.SAAJHeader cannot be cast to class com.sun.xml.ws.security.opt.impl.outgoing.SecurityHeader

### ISSUE THREAD

**Issue by JeeDevUser** [payara/Payara#5203]
# Description #
----------
I just generated (via wsimport tool) a Java client code, in order to call protected SOAP Web service.  When running code on the Payara community, 5.2020.5,  the following problem happens:

**class com.sun.xml.ws.message.saaj.SAAJHeader cannot be cast to class com.sun.xml.ws.security.opt.impl.outgoing.SecurityHeader**

## Expected Outcome ##

running code without ClassCastException

## Current Outcome ##
`javax.xml.ws.WebServiceException: **java.lang.ClassCastException: class com.sun.xml.ws.message.saaj.SAAJHeader cannot be cast to class com.sun.xml.ws.security.opt.impl.outgoing.SecurityHeader (com.sun.xml.ws.message.saaj.SAAJHeader and com.sun.xml.ws.security.opt.impl.outgoing.SecurityHeader are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @360e0886)** at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processRequest(SecurityClientTube.java:222) at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106) at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020) at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989) at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847) at com.sun.xml.ws.client.Stub.process(Stub.java:433) at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161) at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78) at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) at com.sun.proxy.$Proxy424.preuzmiPromenePodatakaOPrivrednimSubjektima(Unknown Source) at apr_ws_update_timer.PreuzmiPPOPrivSubjektima.preuzmiPromene(PreuzmiPPOPrivSubjektima.java:76) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588) at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408) at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4817) at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665) at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834) at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615) at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163) at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundTimeout(SystemInterceptorProxy.java:145) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888) at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833) at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615) at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81) at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888) at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833) at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375) at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4789) at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4777) at com.sun.ejb.containers.BaseContainer.callEJBTimeout(BaseContainer.java:4027) at com.sun.ejb.containers.EJBTimerService.deliverTimeout(EJBTimerService.java:1208) at com.sun.ejb.containers.EJBTimerService.access$000(EJBTimerService.java:96) at com.sun.ejb.containers.EJBTimerService$TaskExpiredWork.run(EJBTimerService.java:1927) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
`

## Environment ##

- **Distribution**: Payara community , 5.2020.5
- **JDK Version**: 11
- **Operating System**:  Windows  and Linux

**Comment by AlanRoth** [comment]
Hi @JeeDevUser, can you please test on the latest Payara Server Community version 5.2021.2? Can you also provide clear reproducer steps or an application we can use to reproduce your issue?

We are not able to work on your issue without these,
Thank you,
Alan

**Comment by JeeDevUser** [comment]
@AlanRoth , any news regarding this?

**Comment by OndroMih** [comment]
Hi @JeeDevUser , if you have a reproducer which you can't share with us, it's better if you become a Payara Enterprise customer. We only support community issues over public channels. 

Can you try using a self-signed certificate and see whether you can reproduce the same issue? Then you could attach a reproducer that doesn't contain any sensitive info and we could investigate. We can't provide community support without a public reproducer.

**Comment by AlanRoth** [comment]
Hi @JeeDevUser, thank you for your patience, are you able to proceed with @OndroMih suggestions?

Thank you,
Alan

**Comment by JeeDevUser** [comment]
Hi, @AlanRoth, @OndroMih 

And thanks for respoponse.
I found what was a problem, for a detail, you can take look at:

https://groups.google.com/g/payara-forum/c/U5bjetOPw4M

In a few words, I just removed  content of the 
**webservices-osgi.jar\META-INF\services\** folder
I think this is a Payara problem, which should be fixed in some way, since my solution looks like a dirty hack.
Best regards,...

**Comment by AlanRoth** [comment]
Hi @JeeDevUser, 

Thank you for investigating this issue. Before we accept your bug report and create an internal issue, would you be able to provide a sample application that is able to reproduce your bug?

**Comment by JeeDevUser** [comment]
@AlanRoth,
**"...or clear steps that are able to reproduce your bug.."**

- This is actually simple:
1. Choose any uName/pass protected SOAP web service
2. Use Java wsimport tool, in order to generate Java service client
3. in order to provide username/pass to the web service,  implement the 
   javax.xml.soap.SOAPHeader
     and
   javax.xml.ws.handler.HandlerResolver
   
   as described, for example, here  :
   http://informatictips.blogspot.com/2013/09/using-message-handler-to-alter-soap.html
   
Finally, call some of WS methods, for example in the EJB TImer, and deploy to Payara.
That;s all.

**Comment by AlanRoth** [comment]
Hi @JeeDevUser,

The steps are still a little ambiguous, can you provide a sample application that clearly shows the error?

If you would like us to implement and create our own reproducers, please consider a Enterprise license - we can then perform much more in-depth investigation for you.

Thank you,
Alan

**Comment by JeeDevUser** [comment]
Hi @Alan,
Sure I can, if yuo provide me with one protected SOAP service. I have one,
but I am not allowed to share certficate and credentials obtained from
service provider.

Regarding enterprise licence, it is to expensive for us. BTW, I found
workarround already, probably I will blog about this somewhere.

So, do you know one free online protected SOAP service? If so, I will make
sample application for you

Best regards, ...

sre, 28. jul 2021. 15:27 Alan ***@***.***> је написао/ла:

**Comment by AlanRoth** [comment]
Hi @JeeDevUser,

Thank you for the quick reply! However, I sadly cannot provide that, and I am afraid without a reproducer for your issue from you we cannot proceed with the investigation.

Let me know how you wish to proceed,
Thank you,
Alan

**Comment by JeeDevUser** [comment]
Hi @Alan,
If I found such one WS, I will make test application, and let you know.
Meanwhile, this issue can be closed, I will reopen him eventually.

Best regards,....


sre, 28. jul 2021. 18:17 Alan ***@***.***> је написао/ла:

**Comment by AlanRoth** [comment]
Hi @JeeDevUser,

Thank you for your understanding, as you say, please open a new issue when you are ready.

Thanks,
Alan
