### ISSUE TITLE
Bug Report:  Metrics for AMX MBeans not visible under /metrics endpoint

### ISSUE THREAD

**Issue by agatarychter** [payara/Payara#5234]
# Description #
----------

After activating JMX Bean Monitoring, some metrics for JMX Bean Values are not visible under /metrics endpoint. 

## Expected Outcome ##

The expected outcome should include JMX bean values metrics listed under following link: https://docs.payara.fish/enterprise/docs/5.20.0/documentation/user-guides/monitoring/mbeans.html

for example:

TYPE vendor_http_connection_pool_http_numconn gauge
HELP vendor_http_connection_pool_http_numconn Total Number of connections handled
vendor_http_connection_pool_http_numconn 6

## Current Outcome ##
Current outcome includes only 18 basic metrics:
base_classloader_loadedClasses_count gauge						
base_classloader_loadedClasses_total_total counter						
base_classloader_unloadedClasses_total_total counter						
base_cpu_availableProcessors gauge						
base_cpu_systemLoadAverage gauge						
base_gc_time_total counter						
base_gc_total_total counter						
base_jvm_uptime_seconds gauge						
base_memory_committedHeap_bytes gauge						
base_memory_committedNonHeap_bytes gauge						
base_memory_maxHeap_bytes gauge						
base_memory_maxNonHeap_bytes gauge						
base_memory_usedHeap_bytes gauge						
base_memory_usedNonHeap_bytes gauge						
base_thread_count gauge						
base_thread_daemon_count gauge						
base_thread_max_count gauge						
vendor_system_cpu_load gauge						

## Steps to reproduce ## 

Use following configuration asadmin to enable amx configuration (asadmin):
1.
set configs.config.server-config.amx-configuration.enabled=true
set configs.config.server-config.monitoring-service.module-monitoring-levels.jvm=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.connector-service=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.connector-connection-pool=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.jdbc-connection-pool=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.web-services-container=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.ejb-container=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.thread-pool=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.http-service=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.security=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.jms-service=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.jersey=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.transaction-service=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.jpa=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.web-container=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.orb=HIGH
set configs.config.server-config.monitoring-service.module-monitoring-levels.deployment=HIGH

2. Call /metrics endpoint (e.g. localhost:8080/metrics)

## Environment ##

- **Distribution**: Payara Micro 2020.4 
- **JDK Version**: Java 11
- **Operating System**: Windows

**Comment by thehpi** [comment]
Setting monitoring levels will not cause the statistics to show up in /metrics.
It will show up when you use a JMX client to query the statistics.

Typically you would use [jmxexporter](https://github.com/prometheus/jmx_exporter) to query jmx and convert it to prometheus output, which is the same format /metrics will produce.

If you want the jmx statistics to show up under /metrics you can use [Custom Vendor Metrics](https://docs.payara.fish/enterprise/docs/5.20.0/documentation/microprofile/metrics/vendor-metrics.html#templating-metrics-amx-mbeans). 

I also advise to use the set-monitoring command to boot amx and the set-monitoring-level command to set the levels, e.g.

set-monitoring-configuration --dynamic=true --monitoringserviceenabled=true --amxenabled=true --target=server-config
set-monitoring-level --target=server-config --module jdbcConnectionPool:threadPool:httpService --level HIGH:HIGH:HIGH

good luck!

**Comment by agatarychter** [comment]
Hello, thank you for the answer. I've looked at the custom vendor metrics, but they require putting the metrics.xml file under config directory in Payara directories. We are using the payara jar and do not have the access to the config directory without unpacking it.  Is there another place where I could put the metrics.xml file so that it is visible for Payara and taken into consideration ? 
I know that for custom domain.xml there is a --domainconfig argument. Is there something similar for metrics.xml file?

**Comment by thehpi** [comment]
No this is not supported in payara micro. For payara server an extension was written which can expose JMX bean values through metrics. (See https://blog.payara.fish/expose-jxm-bean-values-through-microprofile-metrics)

**Comment by AlanRoth** [comment]
Hi @agatarychter, do you wish to submit an enhancement request to allow you to use the metrics.xml with Payara Micro?

Thank you,
Alan

**Comment by agatarychter** [comment]
Hi @AlanRoth - what do you mean by an enhancement request? Can I ask the Payara team for the new feature, for example the possibility to provide the custom metrics file with --metricsconfig=<path>, just like it works with domain.xml?
Or do you mean that I can create the pull request ? Because currently I don't have any ready implementation that would handle that issue. 

Thank you, 
Agata

**Comment by AlanRoth** [comment]
Hi @agatarychter, 

To clarify you can ask the Payara team to implement this feature, your request will be voted on by the community and if it receives enough votes at the end of the month then the Payara team will escalate and implement the feature.

You also have the option to create the implementation yourself - we will keep the issue open while you create a solution - which in some cases is faster. 

Thank you,
Alan

**Comment by agatarychter** [comment]
Should I make some official request or can I just write it here? Additionally - how long can it take for that feature to get implemented?

**Comment by AlanRoth** [comment]
Hi @agatarychter,

A new request is fine, I'm also able to convert this issue to a enhancement request.

I cannot provide an accurate time that the feature will be resolved in, as that is determined by the sprint goals and issue priority of the development team.

I will close this issue as you have a new open issue, you can carry on the discussion on that issue.

Thank you,
Alan
