### ISSUE TITLE
Bug Report: "Unable to locate CDIProvider" when deploy exploaded war (PayaraMicro).

### ISSUE THREAD

**Issue by Empressia** [payara/Payara#5252]
# Description #
----------

I ~~deploy exploaded war and~~ call "CDI.current()".
I got the log below.

```
java.lang.IllegalStateException: Unable to locate CDIProvider
	at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
	at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	……
```

~~There is no problem when deploy as a war file.~~

## Expected Outcome ##

I can get CDI instance when call "CDI.current()".

## Current Outcome ##

```
java.lang.IllegalStateException: Unable to locate CDIProvider
	at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
	at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	……
```

## Steps to reproduce ## 

1. create HttpServlet like below.
	```java
	@WebServlet(urlPatterns="/*")
	public class TestServlet extends HttpServlet {
		public void doGet(HttpServletRequest request, HttpServletResponse response) {
			CDI.current();
		}
	}
	```
2. create beans.xml.
3. ~~build and deploy it as exploaded war.~~
    run java fish.payara.micro.PayaraMicro with --deploy option.
4. call the servlet.

* Test Project (Windows)
    * https://github.com/Empressia/TestPayaraMicroCDI01
        * OK
            1. open terminal
            2. gradlew start ~~<- deploy war file~~
            3. http://localhost:8080/ <- ok
        * NG
            1. open with visual studio code
            2. gradlew start2 ~~run in visual studio code <- deploy exploaded war~~
            3. http://localhost:8080/ <- ng

## Environment ##

- **Distribution**: Micro "fish.payara.extras:payara-micro:5.2021.3"
- **JDK Version**: 11 OracleJDK
- **Operating System**: Windows 10 Pro 64bit

**Comment by Empressia** [comment]
I am sorry. Instead of "uploaded war",
the mainClass specification may be a problem... .

**Comment by Empressia** [comment]
i update first comment.

**Comment by avpinchuk** [comment]
This is not a Payara bug.

From command line everything works as expected.

The problem is in your Gradle classpath setup.

**Comment by Empressia** [comment]
@avpinchuk 

Thank you.  
I specified that the classpath should be only a jar of pyara-micro, and it worked.

I reconfigured my Test Project.
