### ISSUE TITLE
Bug Report:  Microprofile Health and Metrics endpoints not working with custom endpoint

### ISSUE THREAD

**Issue by agatarychter** [payara/Payara#5256]
# Description #
----------

Hello,
I am trying to customize the endpoint for Microprofile health and metrics in the domain.xml file. I've specified the following configurations:
 <microprofile-metrics-configuration endpoint="status/v1/metrics"/>
  <metrics-health-check-configuration endpoint="status/v1/health"/>

The problem is when have something else on endpoint /status - the metrics and healths are not visible then and I get the 404 error code. When I change the endpoint to e.g. status2/v1/metrics everything works.

## Expected Outcome ##

Our business case is to have metrics and healths visible under the provided endpoints + have other resources available under the root endpoint, e.g. /status/v1/ping.

## Steps to reproduce ## 

1.Change endpoints for health and metrics in domain.xml. 
2.Display some other resources under the same root endpoint
3. Call the health/metrics endpoint

## Environment ##

Distribution: Payara Micro 2020.4
JDK Version: Java 11
Operating System: Windows

**Comment by shub8968** [comment]
Hi @agatarychter,

Can you please share the configuration of domain.xml? And also, the code which you are using?

**Comment by karwasinski** [comment]
Hi @shub8968 ,
I'm writing on behalf of @agatarychter 
the configuration:
            <microprofile-metrics-configuration endpoint="status/v1/metrics"/>
            <metrics-health-check-configuration endpoint="status/v1/health"/>

[domain-local-NONE-CI.xml](https://github.com/payara/Payara/files/6522265/domain-local-NONE-CI.txt)
[ApplicationConfig.txt](https://github.com/payara/Payara/files/6522301/ApplicationConfig.txt)

**Comment by shub8968** [comment]
Hi @karwasinski,

Can you please share the proper reproducer?  Please make sure to use the latest release version Payara Micro 5.2021.3.  Also, It is not at all recommended to change the domain.xml explicitly.
