### ISSUE TITLE
Enhancement: Enable customizing metrics.xml file in Payara Micro

### ISSUE THREAD

**Issue by agatarychter** [payara/Payara#5257]
# Description #
----------
I would like to have a possibility to specify the custom metrics.xml file in Payara Micro, so that I can see e.g. JMX metrics under /metrics endpoint. 
Please look at the bug report and discussion: https://github.com/payara/Payara/issues/5234.

## Expected Outcome

The expected outcome is to be able to specify the custom metrics.xml file and provide it it Payara Micro.

## Current Outcome

Customizing the metrics.xml file is only possible in Payara Server after putting the metrics.xml file in the config directory of Payara.

## Alternatives

It would be convenient either be able to provide the custom metrics.xml file path as the program argument. Or - have a place in the project's classpath where Payara Micro would look for the metrics.xml file

## Environment
Distribution: Payara Micro 2020.4
JDK Version: Java 11
Operating System: Windows

Thank you in advance. 
Agata

**Comment by MeroRai** [comment]
Hi @agatarychter,

Thank you for raising the enhancement request, as you know, it will be submitted to voting by the community and accepted if it is the most voted issue this month. We encourage you to rally support for your issue if you wish.

**Comment by fturizo** [comment]
@agatarychter,

It seems that after submitting this issue for community vote there was not a proper reception nor interest in the feature requested, so we'll proceed to close this issue due to lack of interest.
