### ISSUE TITLE
Bug Report:  Remote CDI Events not triggered when observers reside in an .ear

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/Payara#5262]
# Description #
----------

Hello there,

There is an issue when using Remote CDI Events and the target observer resides in a module (let's say a .war) inside an .ear.

I have found this when trying to implement a simple observer in an .ear project running on Payara Server 5.2020.6 that listens to an event that was sent from another .war running in a Payara Micro 5.2020.6 instance. Both in the same Data Grid, discovered by domain.

Eventually I tried it with both 5.2021.1 and 5.2021.3 and the same behaviour happens (not triggering the observer, that is), although the reason varies a bit, which I will try to describe here.

## Expected Outcome ##

Any CDI Observer, either in an @ApplicationScoped CDI bean or a @Singleton EJB, that resides in a module of an .ear should receive the @Inbound event.

## Current Outcome ##

- When the .ear is deployed to **5.2020.6**:

because on **ClusteredCDIEventBusImpl.java** when trying to execute **event.getQualifers()** (line175) it will eventually reach PayaraClusteredCDIEventImpl.getQualifiers()

```
public Set<Annotation> getQualifiers() {
        if (qualifiers == null) {
            try {
                qualifiers = qualifiersPayload.getValue();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(PayaraClusteredCDIEventImpl.class.getName()).log(Level.INFO, "Unable to deserialize qualifiers received on the event ignoring...", ex);
            }...
```
And throw a ClassNotFoundException on **qualifiersPayload.getValue()** (fish.payara.micro.cdi.Outbound)
No CDI event is triggered.

---------------

- When the .ear is deployed to **5.2021.1 - 5.2021.3**: 

```
2021-05-21T11:35:20.739+0100|WARNING: [10.30.194.120]:4900 [development] [4.2] Error while logging processing event
java.lang.IllegalArgumentException: IllegalJndiNameEnvironment : env
	at com.sun.enterprise.deployment.util.DOLUtils.getModuleName(DOLUtils.java:899)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.isLoaded(JavaEEContextUtilImpl.java:156)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.access$700(JavaEEContextUtilImpl.java:69)
	at fish.payara.appserver.context.JavaEEContextUtilImpl$InstanceImpl.isLoaded(JavaEEContextUtilImpl.java:307)
	at fish.payara.appserver.context.JavaEEContextUtilImpl$InstanceImpl.isValidAndNotEmpty(JavaEEContextUtilImpl.java:324)
	at fish.payara.appserver.context.JavaEEContextUtilImpl$InstanceImpl.pushContext(JavaEEContextUtilImpl.java:237)
	at fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.eventReceived(ClusteredCDIEventBusImpl.java:141)
	at fish.payara.appserver.micro.services.PayaraInstanceImpl.receiveMessage(PayaraInstanceImpl.java:223)
	at fish.payara.nucleus.eventbus.TopicListener.onMessage(TopicListener.java:83)
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:151)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228)
```

This happens in 5.2021.3 because on line 141 of **ClusteredCDIEventBusImpl.java** when trying to push the Context:
```
 try(Context ctx = ctxUtil.pushContext()) {
            managedExecutorService.submit(() -> {
                try (final Context ctx1 = ctxUtil.setApplicationClassLoader()) {
                    // create the set of qualifiers for the event
                    // first add Inbound qualifier with the correct properties
                    Set<Annotation> qualifiers = new HashSet<>();
                    Serializable eventPayload = event.getPayload();
```
the **JavaEEContextUtilImpl.java** will eventually try to verify whether the component is loaded (line 156) and then a static function will be called in **DOUTils.java** to get the module name:

```
public static String getModuleName(JndiNameEnvironment env) {

    String moduleName = null;

    if (env instanceof EjbDescriptor) {
      // EJB component
      EjbDescriptor ejbEnv = (EjbDescriptor) env;
      EjbBundleDescriptor ejbBundle = ejbEnv.getEjbBundleDescriptor();
      moduleName = ejbBundle.getModuleDescriptor().getModuleName();
    } else if (env instanceof EjbBundleDescriptor) {
      EjbBundleDescriptor ejbBundle = (EjbBundleDescriptor) env;
      moduleName = ejbBundle.getModuleDescriptor().getModuleName();
    } else if (env instanceof WebBundleDescriptor) {
      WebBundleDescriptor webEnv = (WebBundleDescriptor) env;
      moduleName = webEnv.getModuleName();
    } else if (env instanceof ApplicationClientDescriptor) {
      ApplicationClientDescriptor appEnv = (ApplicationClientDescriptor) env;
      moduleName = appEnv.getModuleName();
    } else if (env instanceof ManagedBeanDescriptor) {
      ManagedBeanDescriptor mb = (ManagedBeanDescriptor) env;
      moduleName = mb.getBundle().getModuleName();
    } else {
      throw new IllegalArgumentException("IllegalJndiNameEnvironment : env");
    }

    return moduleName;

  }
```
However, by this time, if we are running a .war it will be an instance of **WebBundleDescriptor**, but if the application is deployed inside a .ear it will rather be an **com.sun.enterprise.deployment.Application** which is not one of the choices here, throwing an exception.

No CDI observer is triggered.

## Steps to reproduce ## 

I have created two very small projects in this public repositories:
[WAR](https://github.com/CarlosMOGoncalves/payara-test-war)
[EAR](https://github.com/CarlosMOGoncalves/payara-test-ear)

Project **payara-test-war** has a simple Payara Micro 5.2021.3 application (called remotewar, creativity wasn't bright when doing this) with an endpoint to trigger an **Outbound** event. It also has **two listeners to Inbound** events, one CDI and another EJB. I use the maven plugin to configure the Domain Data Grid, so this might need to be changed to connect to the server.

Project **payara-test-ear** has an .ear ready to be deployed to a 5.2021.3 server. The ear contains a small .jar (just tests) and a .war that also has a simple endpoint that triggers and **Outbound** event and **two listeners to Inbound** events. All events are Strings for ease of use. There is also a separate .war called observers that is used as a comparing artifact with two listeners to Inbound events.
This ear was created with the j2ee simple archetype, hence the naming.

1. Start a Payara Community Server 5.2021.3
2. Start the Uber Jar of the Payara Micro project. I always use the maven payara plugin on Eclipse.
3. Connect both to Data Grid
4. Deploy observers.war into Server
5. Trigger endpoint on Payara Micro
6. It should print "Triggered remotely on XXX from observers project" twice, one for the CDI bean and another for the EJB
7. Now remove that war from the Server
8. Deploy the ear to the Server
9. Trigger endpoint on Payara Micro
10. It should throw exception (and not print anything at all)
11. BONUS: deploy both the ear and the war to the server and it should print the messages on the .war and throw exception on the .ear, but this depends on the order of the deployment (don't remember which order, likely the .war first)

**NOTE:** I think the **5.2020.6** issue might not be connected with the one in **5.2021.1+** which is why I also put it here. 

## Environment ##

- **Distribution**:  Server Full Profile - Community Edition from 5.2020.6 to 5.2021.3
- **JDK Version**: 1.8.0_282 - AdoptOpenJDK
- **Operating System**: Windows 10

**Comment by lprimak** [comment]
I believe this is fixed in 5.2021.4 (soon to be released). Feel free to reopen this issue if not

**Comment by CarlosMOGoncalves** [comment]
Thanks Lenny,
Will check it as soon as it is released.

**Comment by lprimak** [comment]
@CarlosMOGoncalves Unfortunately this will not make it into the .4 release, and will have to wait for .5

**Comment by CarlosManuel-FF** [comment]
It's a pity, but I will wait for the .5. 
It is likely not going to take long anyway. 
Cheers.

**Comment by CarlosMOGoncalves** [comment]
It's a pity, but I will wait for the .5.
It is likely not going to take long anyway.
Cheers.
