### ISSUE TITLE
Hard-coded values in OAuth2AuthenticationMechanism (response_type, response.status)

### ISSUE THREAD

**Issue by luisdanielmesa** [payara/Payara#5264]
# Description #
----------

I was trying to use the built-in OAuth2 support mechanism but it seems that the response_type is [hard-coded as ```code```](https://github.com/payara/Payara/blob/f09ab68879c194857f61c97d17ea69b38fc089d8/appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java#L254), and there is no way to configure this in the @OAuth2AuthenticationDefinition
----------

## Expected Outcome ##

To be able to configure the ```response_type``` as "Assertion" to connect to [Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)

## Current Outcome ##

"[OAUTH-001] Error occurred authenticating user: Unknown error caused by Unknown" because the response status [is not 200](https://github.com/payara/Payara/blob/f09ab68879c194857f61c97d17ea69b38fc089d8/appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java#L215) from the server but a 307 (temporary redirect)

## Steps to reproduce ## 

[Register an app](https://app.vsaex.visualstudio.com/app/register) and configure @OAuth2AuthenticationDefinition with the resulting information.

## Environment ##

- **Distribution**: All
- **JDK Version**: All
- **Operating System**: All

**Comment by luisdanielmesa** [comment]
PS: I tried creating my own HttpAuthenticationMechanism, AuthenticationDefinition annotation, Oauth2AuthenticationMechanismhandler, etc... but it became a nightmare trying to fight the default OAuth2AuthenticationMechanism with @Specializes and @Alternative, configuring beans.xml, etc... I'm not experienced enough to do it, and I thought it was way overkill to create all that to be able to control a simple String.

**Comment by shub8968** [comment]
Hi @luisdanielmesa,

respone_type = "code" is configured as per rfc6749. You can refer more from here -https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1 

If you wish you can submit an enhancement request in the same regard.

Thanks,
Shubham

**Comment by OndroMih** [comment]
Hi @luisdanielmesa,

I you may also try using the OpenID Connector with Azure. This connector supports specifying the responseType: https://docs.payara.fish/community/docs/documentation/payara-server/public-api/openid-connect-support.html

You may as well consider submitting a pull request for the OAuth2 connector to allow changing the default value if needed. The affected code is here: https://github.com/payara/ecosystem-security-connectors/blob/f821c25f17811400f8cd7699c42643ac1b75346e/oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java#L258.

**Comment by shub8968** [comment]
Hi @luisdanielmesa,

You can have a discussion pertaining to it on Payara Forum - https://groups.google.com/g/payara-forum
