### ISSUE TITLE
The SSL certificate has expired

### ISSUE THREAD

**Issue by andreasernst** [payara/Payara#527]
Payara Server 4.1.1.154 #badassfish (build 270)

Please remove this cert:

  Version: V3
  Subject: CN=GTE CyberTrust Root 5, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 2048 bits
  modulus: 23741889829347261660812437366387754385443431973861114865490414153884050331745811968523116847625570146592736935209718565296053386842135985534863157983128812774162998053673746470782252407673402238146869994438729551246768368782318393878374421033907597162218758024581735139682087126982809511479059100617027892880227587855877479432885604404402435662802390484099065871430585284534529627347717530352189612077130606642676951640071336717026459037542552927905851171460589361570392199748753414855675665635003335769915908187224347232807336022456537328962095005323382940080676931822787496212635993279098588863972868266229522169377
  public exponent: 65537
  Validity: [From: Fri Aug 14 16:50:00 CEST 1998,
               To: Thu Aug 15 01:59:00 CEST 2013]
  Issuer: CN=GTE CyberTrust Root 5, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US
  SerialNumber: [    01b6]

**Comment by smillidge** [comment]
Thanks for the heads up we'll remove it.

**Comment by smillidge** [comment]
We can't find this certificate as we think it has already been removed. Which domain are you using?

**Comment by andreasernst** [comment]
Hhmm, ok this could be, the domain is from GlassFish 4.1.x and later moved to Payara.

**Comment by Siscon-Ng** [comment]
how do I remove it? I am having the same problem with a migrated glassfish domain!
