### ISSUE TITLE
Bug Report:  microprofile metrics annotation @SimplyTimed is not picked up in subclasses

### ISSUE THREAD

**Issue by thehpi** [payara/Payara#5277]
# Description
--------------------

I created two plugins (MyPlugin1 and MyPlugin2) which I inject using 

    @Inject Instance<Plugin> plugins;

Both plugins are extending BasePlugin which has the main 'execute' method which calls the method
'run' which are implemented in the plugin subclasses. These 'run' methods have the @SimplyTimed 
annotation.

The is that the metrics are not collected for the 'run' methods.

If the plugin does not use a subclass (MySimplePlugin) and the 'execute' method has the @SimplyTimed
annotation then it works ok.

Also when another bean in injected and called in the plugin subclasses (MyBean) then the metrics
are collected fine in that bean.

## Expected Outcome

I would expect the @SimplyTimed annotation to work on any CDI managed bean/method.

## Current Outcome

The metrics output does show lines indicating the annotation was found but the actual metric
values are not increased. So it looks like the registration is done, but the interceptor responsible
for increasing the values is not executed.

## Steps to reproduce (Only for bug reports) 

See [reproducer](https://github.com/thehpi/payara-microprofile-metrics-problem-subclass)

- install java
- install docker
- install docker-compose
- install maven

Build

    ./build.sh

Start payara

    docker-compose up -d

Confirm the error

    ./test.sh

    my-plugin-1: This is plugin One
    my-plugin-1: This is plugin One
    my-plugin-2: This is plugin Two
    application_nl_hans_service_MyBean_run_total{_app="test-rest"} 3
    application_nl_hans_service_MyPlugin1_run_total{_app="test-rest"} 0
    application_nl_hans_service_MyPlugin2_run_total{_app="test-rest"} 0
    application_nl_hans_service_MySimplePlugin_execute_total{_app="test-rest"} 1

Again

    ./test.sh

    my-plugin-1: This is plugin One
    my-plugin-1: This is plugin One
    my-plugin-2: This is plugin Two
    application_nl_hans_service_MyBean_run_total{_app="test-rest"} 6
    application_nl_hans_service_MyPlugin1_run_total{_app="test-rest"} 0
    application_nl_hans_service_MyPlugin2_run_total{_app="test-rest"} 0
    application_nl_hans_service_MySimplePlugin_execute_total{_app="test-rest"} 2

As you can see MyBean is called in all three plugins. MySimplePlugin is called once and metrics work ok.
Buth the other two plugins which are subclasses, it doesn't work.

## Environment ##

- **Payara Version**: 5.2021.3
- **Edition**: Payara Full
- **JDK Version**: 1.8.0_275 OpenJDK
- **Operating System**: Mac
- **Database**: n/a

**Comment by shub8968** [comment]
Greetings @thehpi,

I have opened a pull request in the same reproducer. With those changes, `@SimplyTimed` annotation is successfully picked up. The reason in your case it is not getting picked up depends upon the use case of `instance` which can be found in the [documentation](https://javaee.github.io/javaee-spec/javadocs/javax/enterprise/inject/Instance.html) -

> In certain situations, injection is not the most convenient way to obtain a contextual reference. For example, it may not be used when:

> the bean type or qualifiers vary dynamically at runtime, or
> depending upon the deployment, there may be no bean that satisfies the type and qualifiers, or
> we would like to iterate over all beans of a certain type.

Further attaching the screenshot of evidence that I have collected.
![Screenshot (78)](https://user-images.githubusercontent.com/36557492/123127479-f14ce300-d467-11eb-9d23-d816929209a0.png)

**Comment by thehpi** [comment]
Thanks, but I don't see any pull request in the [reproducer](https://github.com/thehpi/payara-microprofile-metrics-problem-subclass)

**Comment by shub8968** [comment]
My Bad. @thehpi please check it now.

**Comment by thehpi** [comment]
Hi Shubham,

I see you removed my super class BasePlugin and injected the bean in the subclass. I know this works, actually this is the workaround that I'm using in my project.

What I was looking for is an explanation, or even beter documentation, about why the @SimplyTimed doesn't work in this case.

The documentation you're referring to is about Instance. The injection works fine, Instance is doing its work perfectly, only @SimplyTimed is not working. If you can point me to the documentation of MP metrics where it is explained why this doesn't work I would be grateful. 

Of course it could be that there is no documentation about this case because it's a bug.

**Comment by smillidge** [comment]
If you are calling a method on a direct reference i.e. `this` from within the super-class there is no way the SimplyTimed Interceptor is going to fire. To do that you need to go via an Injected variable as that will be a proxy to the real object and can therefore intercept the call. This is the way Interceptors work so not sure there is anything we can do about that.
