### ISSUE TITLE
Rest Api Call with access token from azure

### ISSUE THREAD

**Issue by markusg80** [payara/Payara#5285]
i try to call a rest api from an android app. The rest api is running on a payara server. on the payara server i configured all the azure parameter with the @OpenIdAuthenticationDefinition annotation. with this config i was able to login directly on the web app on the payara server. when i now get a access token from azure (yes my android app registration has permission for exposed api on the web api app registration) and call the restapi with authorization header and bearer token value the payara server give me a redirect to the login page of azure. the rest api is decorated wit @RolesAllowed. is it possible to use azure authentication with payara-api with just a bearer token or is there a session needed because you save some information inside the session?

**Comment by shub8968** [comment]
Hi @markusg80,

We have our community forum for discussion pertaining to this. If you think it is a possible bug, please provide us with the proper reproducer in the accordance with issue template. 
Link to community forum - https://groups.google.com/g/payara-forum
