### ISSUE TITLE
The link to the release notes in `README.txt` is incorrect.

### ISSUE THREAD

**Issue by ahamana** [payara/Payara#5287]
# Description #
----------

The link to the release notes in `README.txt` is incorrect.

## Expected Outcome ##

https\://docs.payara.fish/docs/5.2021.4/release-notes/release-notes-2021-4.html

## Current Outcome ##

https\://docs.payara.fish/docs/5.2021.4/release-notes/release-notes-2020-7.html

## Steps to reproduce ## 

1. Download the Payara Community Edition from https://repo1.maven.org/maven2/fish/payara/distributions/payara-ml/5.2021.4/payara-ml-5.2021.4.zip.
3. See the `README.txt` included in the downloaded one.

**Comment by AlanRoth** [comment]
Hi @ahamana, thank you for bringing it to our attention. This is caused be a oversight when incrementing our versions in our release scripts.

This will be fixed before the next release. 

I will close this issue as we have all the information required.

Apologises about the inconvenience,
Thank you,
Alan

**Comment by ahamana** [comment]
Hi @AlanRoth, 

On [5.2021.5](https://repo1.maven.org/maven2/fish/payara/distributions/payara-ml/5.2021.5/payara-ml-5.2021.5.zip), README.txt has two links to the release notes, one is correct, but another is still incorrect.

> Make sure to also check the Payara Server 5.2021.5 Release Notes as they contain important information: https://docs.payara.fish/docs/5.2021.5/release-notes/release-notes-2020-7.html

> Payara Server 5.2021.5 Release Notes: https://docs.payara.fish/docs/5.2021.5/release-notes/release-notes-2021-5.html

This issue need not to be reopened.

Thanks,
A.Hamana
