### ISSUE TITLE
Glassfish 4.1.1 does not properly implement Bean Validation

### ISSUE THREAD

**Issue by sekmiller** [payara/Payara#529]
We want to upgrade our application to use Glassfish 4.1.1, but we are unable to do so because our application uses Bean Validation and it's not working properly.  The issue is being tracked here
https://java.net/jira/browse/GLASSFISH-21440 , but it doesn't seem to have gotten any attention.
Here is a link to the tracking of the issue in our application: https://github.com/IQSS/dataverse/issues/2628

**Comment by pdurbin** [comment]
https://java.net/jira/browse/JERSEY-2888 seems to indicate that the issue might actually be in EclipseLink ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=463169 ).

@phillipross and I have been discussing this at https://javabot.evanchooly.com/logs/%23glassfish/2015-11-17

He thinks it might be a packaging problem. I'm really not sure.

**Comment by smillidge** [comment]
The GlassFish 21440 bug is not in Payara

**Comment by smillidge** [comment]
Specifically we patched Eclipselink a while back. You can get the patched jars from our Patched Projects repo on Github

**Comment by pdurbin** [comment]
@smillidge thanks for the reply! In https://github.com/IQSS/dataverse/issues/2628#issuecomment-158077013 I described how this morning I attempted to switch our application (Dataverse) from Glassfish 4.1 to Payara 4.1.1.154. During the setup of our application I did not see the bean validation errors @sekmiller reported with Glassfish 4.1.1. It's probably safe to close this issue.

(Unfortunately, while setup of our application completed successfully, Payara does not yet seem to be a drop in replacement for us. As part of that comment, I updated the full server.log containing the exceptions I'm seeing when I try to visit the homepage or log in.)

**Comment by smillidge** [comment]
Does the behaviour differ from GlassFish 4.1.1? If so please raise a separate GitHub issue for the error you are seeing.

**Comment by pdurbin** [comment]
@smillidge yes we are seeing different behavior so I just opened #532 per your request.

To sum up:

- Glassfish 4.1: works
- Glassfish 4.1.1: doesn't work. Bean Validation problems when our setup scripts run: https://github.com/IQSS/dataverse/issues/2628#issuecomment-158197478
- Payara 4.1.1.154: doesn't work. We are able to run our setup scripts but then we can't load the homepage or log in (and who knows what else). Details and server.log in #532.

**Comment by smillidge** [comment]
I'm wondering if GlassFish 4.1.1 is just failing before Payara. Can you copy the patched Eclipse jars from Payara to GlassFish 4.1.1 so you can get passed the setup and then see if you get the same Jersey issue with 4.1.1?

**Comment by pdurbin** [comment]
@smillidge I very much appreciate you helping us try to migrate from Glassfish 4.1! Having to patch [Grizzly](http://guides.dataverse.org/en/4.2.1/installation/shibboleth.html#apply-grizzly-1787-patch) and [Weld](http://guides.dataverse.org/en/4.2.1/installation/prerequisites.html) is a drag and we'd like to simplify the installation for people who run our application. That's why I opened https://github.com/IQSS/dataverse/issues/2628 in the first place. Plus https://java.net/jira/browse/GLASSFISH-21343 drives me crazy. :)

I'm pretty snowed under right now so I don't think I'll have time in the near future to try the test you're suggesting but I'll keep it in my back pocket. Thanks!
