### ISSUE TITLE
Enhancement: Update Yasson to 1.0.7+ / FISH-5705

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/Payara#5290]
# Description #
----------

Hello everyone,

Is is possible to upgrade Yasson to a later version on Payara 5?

I have bumped into a bug in the currently available version (1.0.6) and I was told it has been fixed in 1.0.7 and above.

Thanks

## Expected Outcome

Using a newer version would allow me to use custom serializers from within other custom serializers.

## Current Outcome

Currently this is not easily possible because the code flow won't allow it.

## Alternatives

Well, you could apply the same fix in the Payara patched project, but I think this is not needed because the fix seems to be available right now.

## Context

The issue that originated this was [this](https://github.com/eclipse-ee4j/yasson/issues/497)

**Comment by AlanRoth** [comment]
Hi @CarlosMOGoncalves, 

Thank you for raising the enhancement request, as you know, it will be submitted to voting by the community and accepted if it is the most voted issue this month. We encourage you to rally support for your issue if you wish.

We can also explore the possibility of backporting the fix to Yasson 1.0.6.

Thank you,
Alan

**Comment by CarlosMOGoncalves** [comment]
Hello @AlanRoth,

Thanks for the response. I am familiar with the voting steps for this and I hope people can support it.

Nevertheless, since Yasson is an important component for Payara, being the JSONB implementation, wouldn't you consider it a "natural" update?

I am not familiar with the complete implications of updating it, but I think that versions 1.0.7 and 1.0.8 are mostly about bug fixes (I can't find the exact release notes on their repository but I am assuming 2.x is for JakartaEE 9+ namespace and 1.0.x is for JakartaEE 8).

Wouldn't it be possible a simple update? 
I don't think there really is a need to backport it.

Cheers

**Comment by AlanRoth** [comment]
Hi @CarlosMOGoncalves, 

We would have upgraded to later versions at some point naturally. We recently upgraded to Yasson 1.0.6 which introduced a breaking change that required extensive effort to manage - especially for Enterprise as we promise backwards compatibility.

If the upgrade is just bug fixes, I'm sure it can be accommodated at some point, possibly sooner if there is a community desire for it.

However, from what I know there have not been any recent plans to upgrade Yasson.

Thank you,
Alan

**Comment by CarlosMOGoncalves** [comment]
Well, I suspected it wouldn't be so simple after all :).

Anyway, thanks for the information. 
Let's see if this gets any traction from the community then.

Cheers

**Comment by AlanRoth** [comment]
Hi @CarlosMOGoncalves,

Thank you for your patience, your issue is the top voted issue, well done!

I have raised `FISH-5705` to keep track of this issue.

Thank you,
Alan

**Comment by CarlosMOGoncalves** [comment]
Hello @AlanRoth,

Thanks a lot, those are great news,

Cheers

**Comment by AlanRoth** [comment]
Hi @CarlosMOGoncalves,

#5458 / FISH-5705 has been resolved, and will be included in the next release. I will close this ticket.

Thank you,
Alan

**Comment by CarlosMOGoncalves** [comment]
Wow, nice.
Thanks Alan!
