### ISSUE TITLE
Bug Report:  Disabling TLS 1.0

### ISSUE THREAD

**Issue by aaron-cur** [payara/Payara#5300]
# Description #
----------
will disabling the TLS property under the http settings disable just TLS 1.0 or all TLS communication?

https://docs.payara.fish/community/docs/5.2021.1/documentation/payara-server/server-configuration/http/protocols/ssl-options.html#configuration-ssl-tls

## Expected Outcome ##

Based on documentation I would expect disabling this property would disable all TLS communication since 1.1 and 1.2 properties indicate configuration will be ignored if TLS is disabled.

## Current Outcome ##

disabling TLS property appears to just disable TLS 1.0 while leaving 1.1 and 1.2 active.

## Steps to reproduce ## 

disable TLS property on payara server and watch the traffic using a tool like  Zenmap

## Environment ##

- **Distribution**: Payara 5.2021.1
- **JDK Version**:JDK 11.0.10
- **Operating System**: Windows

**Comment by fturizo** [comment]
@aaron-cur, disabling the TLS property will explicitly disable the TLSv1.0 version of the protocol and not affect other versions. We'll proceed to close this issue as this is not a proper bug report. Keep in mind to raise questions in the official Payara Forum as instructed in the GH's interface and only raise issues here for specific bug reports or enhancement requests.

**Comment by aaron-cur** [comment]
I raised this because documentation indicates disabling this property will cause the settings for TLS 1.1, 1.2, and 1.3 will be ignored.

Thank you for the clarification.
