### ISSUE TITLE
Application Client Java Web Start Compability Issue

### ISSUE THREAD

**Issue by neftalyluis** [payara/Payara#531]
I created a Java EE "Enterprise Application Client" from Netbeans 8.02 (with not code changes) and deployed it to Payara 4.1.1.154 using Java 1.8 u 31.

I have replaced the s1as certificate with a signed one.

If I try and launch the Application Client I get the message "Application Blocked by Java Security", 

Reason: The Java security settings have prevented this application from running. You may change this behavior in the Java Control Panel. I get the same result from the glassfish control panel or javaws (1.8 u31).

Adding my site to the Exception Site List does not work.
It looks like the problem is between the newer Java Web Start clients and the Payara auto-generated JNLP file .

If I install a java 1.7 u25 or earler javaws (Java Web Start 10.21.2.11 or earlier). I can start the application client and it will run in the java 1.8 u31 environment.

**Comment by smillidge** [comment]
Do you have a simple test case we could use?

**Comment by neftalyluis** [comment]
Here:

https://dl.dropboxusercontent.com/u/47436164/enterpriseapplication-0.1-SNAPSHOT.ear

**Comment by smillidge** [comment]
Thanks we've got it

**Comment by smillidge** [comment]
I checked your jar and I believe to work on Java 8 in web start it must be signed and the permissions in the manifest must match the permissions requested in the JNLP file. See https://www.java.com/en/download/help/jcp_security.xml Medium security level was removed from JDK 8u20 onwards

**Comment by neftalyluis** [comment]
I've just added the same permissions(all-permissions) in the manifest as with the jnlp and its giving the same error.

Also i've checked that the generated jar got signed by Glassfish (using the property jar-signing-alias in the deploy command) with an self-signed cert, and that's true, so i don't know why JWS keeps rejecting the app.

Another option is using a custom JNLP but i don't know how to embed the ACC

**Comment by fturizo** [comment]
Greetings @neftalyluis, as @smillidge pointed out, the Medium security level was removed on JDK 8 onwards. This means that when the client VM is trying to execute the application client through JNLP, the JVM security manager will block the execution unless the application's JAR file is signed with a valid SSL cert that can be verified by an external CA (self-signed certs are not good enough). If possible can you also try to execute you application client with version 7 of the JDK?

**Comment by neftalyluis** [comment]
Yes, I've tried with version 7 and it does execute the application, 

As you pointed out, we needeed to use a cert verified.

You can close this issue, thank you all for your time guys (:

**Comment by fturizo** [comment]
No problem @neftalyluis, many thanks for the quick reply. I'll close the issue then.
