### ISSUE TITLE
`CollectionLeafResource`'s method uses @GET annotation but @Path is missing

### ISSUE THREAD

**Issue by oneturkmen** [payara/Payara#5313]
`CollectionLeafResource` class uses JAX RS annotations, but misses `@Path` which is necessary for the resource to be picked up. Otherwise, 404 is returned.

Link:
https://github.com/payara/Payara/blob/5017a460aae0bf382f0a0255c84594f14fcb46bc/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java#L146

**Comment by shub8968** [comment]
https://github.com/payara/Payara/issues/5316
