### ISSUE TITLE
Bug Report:  cli ./asadmin add-library command not synch lib to all payara server instances

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#5321]
# Description #
----------

When use CLI add-library to add a lib to domain, the added library will stay in /u01/app/payara5/glassfish/domains/production/lib

if after libs added, create new node and add new payara server instances, the already added libs will be copy over to the newly added payara server instances, it can be found in such server instance's lib directory, for example /u01/app/payara5/glassfish/nodes/localhost-production/payaraServer1/lib and/or remote node's server instance as well.

but if libs were added (or updated and re-added) after payara server instances create, the newly added (or updated) libs only stay in domain lib (not synch to payara server instances).

is that a normal process (expected) or a design issue, Please confirm it. 

## Expected Outcome ##

once libs added or updated to domain by CLI add-library, it will synch to all Payara server instances ASAP.

## Current Outcome ##

Not synch at all.

## Steps to reproduce ## 

As above summary description

## Environment ##

- **Distribution**: 
- Payara community edition 5.2021.4
- **JDK Version**: 
- JDK-11.0.0
- **Operating System**: 
- Centos 8

**Comment by smillidge** [comment]
Only a normal synch will occur when you start an instance and this will not synch libs.

Try 

`asadmin start-instance --sync full  <instance-name>`

Note the forum is better for asking questions. https://groups.google.com/g/payara-forum
