### ISSUE TITLE
Bug Report: cannot apply default values in @DataSourceDefinition URL via variable expansion/FISH-5676

### ISSUE THREAD

**Issue by poikilotherm** [payara/Payara#5322]
# Description #
----------

With IQSS/dataverse#7701 we moved to Payara 5.2021.4 and hoped for the default values for our `@DataSourceDefinition`.
While testing the deployment, issues where experienced. If you do not set the variable (via system property or env var), the default value is getting applied, but data source allocation & deployment fails.

## Expected Outcome ##

When using a `@DataSourceDefinition` with
```
url = "jdbc:postgresql://${MPCONFIG=db.host:localhost}:${MPCONFIG=db.port:5432}/${ENV=DB_NAME:dvn}"
```
and none of these settings around, the allocation and deployment should work fine with the defaults given.

## Current Outcome ##

For unknown reasons, this fails with
- `RAR5103 : Error setting java bean value : [...]]]` (where "..." is the first default value used from the URL string)
- `Exception : javax.resource.ResourceException: Access denied to execute this method : setURL`
- due to illegal access at:
  ```
  java.lang.reflect.InvocationTargetException
      [...]
      com.sun.gjc.common.DataSourceObjectBuilder.constructDataSourceObject(DataSourceObjectBuilder.java:118)
   ```

This is failing with both `${MPCONFIG}` and `${ENV}`, but again: if you make the referenced keys available, they are getting used flawless.

## Steps to reproduce ## 

1. Goto https://github.com/poikilotherm/reproducer-payara-mpconfig-seturl and clone
2. Use `mvn -Parq-payara-managed verify` to execute integration test using Arquillian Payara Managed.  
   (Shoutout and kudos to @lprimak for [the handy extension](https://github.com/payara/ecosystem-arquillian-connectors/tree/master/environment-setup))
3. Logs can be found at `target/payara5/glassfish/domains/domain1/logs/server.log`
4. Play around by setting vars in `src/main/resources/system-properties.properties` and `src/main/resources/environment-variables.properties`

Note that I also set `fish.payara.log-jdbc-calls` within the DSD to a nonsense default value. This is not taken into account. No idea if this is due to the failing connection when setting the properties or if non-included #5272 (3 days after Payara 5.2021.4) is causing this to be ignored.

## Environment ##

- **Distribution**: Server Full
- **JDK Version**: 11, OpenJDK & Adopt
- **Operating System**: Linux

**Comment by shub8968** [comment]
Hi, @poikilotherm,

I can reproduce this issue. I have raised an internal issue with JIRA FISH-5676. It may take a while to fix the issue. You are free to submit a PR to fix this issue if you feel confident to do so. Thanks.

**Comment by poikilotherm** [comment]
Hey @shub8968 @lprimak @Pandrex247 

I pushed an update to the reproducer, updating it to test with latest 5.2021.8 release. The error persists. :crying_cat_face: 

Any chance this might be given a look? Thank y'all very much!

Best, Oliver

**Comment by shub8968** [comment]
Hi, @poikilotherm,

I have updated JIRA `FISH-5676` mentioning your concern. 

Thanks, Shubham

**Comment by poikilotherm** [comment]
Thank you @kalinchan for fixing this!!! :smile:
