### ISSUE TITLE
Bug Report:  Payara micro: setting SSL trustStore / keyStore manually 

### ISSUE THREAD

**Issue by jimgarrett123** [payara/Payara#5347]
# Description #
----------

I'm using the Payara Micro as an embedded web server and am calling it from within a Linux container.  In my scenario I need to be able to configure the SSL Truststore manually upon starting the web server.  I've tried all the documented procedures to accomplish this.  For example, I've configured a JAVA_OPTIONS parameter to include "Djavax.net.ssl.trustStore=<keystore-location> -Djavax.net.ssl.trustStorePassword=<password>" and included this on the command line when running the fat jar.  This didn't work.

I also attempted to use the JAVA_ARGS command to pass in the "--sslPort 8443 --systemproperties <location to properties file>", this didn't work either.

Is there something I'm missing?  Is there another way that provides for this?

## Expected Outcome ##

I'd like to be able to pass in the ssl truststore when starting the embedded web server.

## Current Outcome ##

When I run the embedded web server and then examine the certificate of the SSL connection, it still conveys using the embedded Payara certificate

## Steps to reproduce ## 

Create a fat jar implementation of the Payara web server.  Then run this from the command line and provide a keystore.jks containing your public and private key.  Then examine the SSL connection and see what cert is conveyed.

## Environment ##

- **Distribution**: Micro Embedded
- **JDK Version**: JDK v 8
- **Operating System**: Red Hat Enterprise Linux

**Comment by MeroRai** [comment]
Hi @jimgarrett123, sorry for the late reply but this sounds more like a question than an actual issue. Please, submit all your questions to the official Payara Community Google Forum (https://groups.google.com/forum/#!forum/payara-forum) to receive assistance. We’ll proceed to close this issue.
