### ISSUE TITLE
Bug Report:  Application not being auto deployed - Docker - Payara Server 5.2021.6 / FISH-5701

### ISSUE THREAD

**Issue by tikonza** [payara/Payara#5391]
# Description #
----------
1. I have created a docker image from a Dockerfile as below:

FROM payara/server-full
COPY bwbportal.war $DEPLOY_DIR

2. I have created a Docker image as below:

docker build -t bwbportal .

3. I am running the container as below

D:\dockerdeploy>docker run -i --rm --name bwbportal -p 54848:4848 -p 58080:8080 -p 58181:8181 bwbportal

## Expected Outcome ##

I am expecting that the application should be auto-deployed by payara

## Current Outcome ##

The application is not being auto deployed

## Steps to reproduce ## 

1. Created a Dockerfile to as follows:

FROM payara/server-full
COPY bwbportal.war $DEPLOY_DIR

2. Then i run the build command as follows:

docker build -t bwbportal .

3. Then I executed the docker run command as follows:

D:\dockerdeploy>docker run -i --rm --name bwbportal -p 54848:4848 -p 58080:8080 -p 58181:8181 bwbportal

4. Here is the log displayed after the run command:

[Entrypoint] running /opt/payara/scripts/init_1_generate_deploy_commands.sh
Adding deployment target /opt/payara/deployments/bwbportal.war to post boot commands

[Entrypoint] ignoring /opt/payara/scripts/init.d/*

Executing Payara Server with the following command line:
/usr/lib/jvm/zulu8-ca-amd64/bin/java
-cp
/opt/payara/appserver/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:+UseContainerSupport
-XX:MaxRAMPercentage=70.0
-Xbootclasspath/a:/opt/payara/appserver/glassfish/lib/grizzly-npn-api.jar
-Xss512k
-server
-javaagent:/opt/payara/appserver/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/opt/payara/appserver/glassfish/domains/domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/opt/payara/appserver/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/opt/payara/appserver/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.security.policy=/opt/payara/appserver/glassfish/domains/domain1/config/server.policy
-Djava.endorsed.dirs=/opt/payara/appserver/glassfish/modules/endorsed:/opt/payara/appserver/glassfish/lib/endorsed
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/opt/payara/appserver/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/opt/payara/appserver/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/opt/payara/appserver/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/lib/jvm/zulu8-ca-amd64/lib/ext:/usr/lib/jvm/zulu8-ca-amd64/jre/lib/ext:/opt/payara/appserver/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.h2.Driver
-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true
-Djava.library.path=/opt/payara/appserver/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-prebootcommandfile
/opt/payara/config/pre-boot-commands-final.asadmin
-upgrade
false
-read-stdin
true
-postbootcommandfile
/opt/payara/config/post-boot-commands-final.asadmin
-domainname
domain1
-domaindir
/opt/payara/appserver/glassfish/domains/domain1
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--user,,,admin,,,--passwordfile,,,/opt/payara/passwordFile,,,--secure=false,,,--terse=false,,,--extraterse=false,,,--echo=false,,,--interactive=false,,,--autoname=false,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara/appserver/glassfish/domains,,,domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/opt/payara/appserver/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false

Launching Payara Server on Felix platform
Aug 24, 2021 11:28:40 AM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@36627446 in service registry.
Reading in commandments from /opt/payara/config/pre-boot-commands-final.asadmin

#!## LogManagerService.postConstruct : rootFolder=/opt/payara/appserver/glassfish
#!## LogManagerService.postConstruct : templateDir=/opt/payara/appserver/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/opt/payara/appserver/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/opt/payara/appserver/glassfish/domains/domain1/config/logging.properties
[#|2021-08-24T11:28:43.410+0000|INFO|Payara 5.2021.6|javax.enterprise.logging|_ThreadID=18;_ThreadName=RunLevelControllerThread-1629804523311;_TimeMillis=1629804523410;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  5.2021.6 #badassfish (build 4579)|#]

[#|2021-08-24T11:28:43.413+0000|INFO|Payara 5.2021.6|javax.enterprise.logging|_ThreadID=18;_ThreadName=RunLevelControllerThread-1629804523311;_TimeMillis=1629804523413;_LevelValue=800;_MessageID=NCLS-LOGGING-00010;|
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter|#]

[#|2021-08-24T11:28:44.059+0000|INFO|Payara 5.2021.6|org.glassfish.ha.store.spi.BackingStoreFactoryRegistry|_ThreadID=18;_ThreadName=RunLevelControllerThread-1629804523311;_TimeMillis=1629804524059;_LevelValue=800;|
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry|#]

[#|2021-08-24T11:28:46.726+0000|INFO|Payara 5.2021.6|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629804523314;_TimeMillis=1629804526726;_LevelValue=800;|
  Hazelcast Instance Bound to JNDI at payara/Hazelcast|#]

[#|2021-08-24T11:28:46.726+0000|INFO|Payara 5.2021.6|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629804523314;_TimeMillis=1629804526726;_LevelValue=800;|
  JSR107 Caching Provider Bound to JNDI at payara/CachingProvider|#]

[#|2021-08-24T11:28:46.727+0000|INFO|Payara 5.2021.6|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629804523314;_TimeMillis=1629804526727;_LevelValue=800;|
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager|#]

[#|2021-08-24T11:28:46.934+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804526934;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-1 started in: 16ms - bound to [/0.0.0.0:8080]|#]

[#|2021-08-24T11:28:46.952+0000|INFO|Payara 5.2021.6|org.hibernate.validator.internal.util.Version|_ThreadID=18;_ThreadName=RunLevelControllerThread-1629804523311;_TimeMillis=1629804526952;_LevelValue=800;|
  HV000001: Hibernate Validator 6.1.5.Final|#]

[#|2021-08-24T11:28:47.281+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804527281;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-2 started in: 8ms - bound to [/0.0.0.0:8181]|#]

[#|2021-08-24T11:28:47.329+0000|WARNING|Payara 5.2021.6|org.glassfish.grizzly.config.GenericGrizzlyListener|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804527329;_LevelValue=900;|
  HTTP/2 (enabled by default) is unsupported with port unification and will be disabled for network listener admin-listener.|#]

[#|2021-08-24T11:28:47.361+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804527361;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener admin-listener started in: 10ms - bound to [/0.0.0.0:4848]|#]

[#|2021-08-24T11:28:47.363+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804527363;_LevelValue=800;_MessageID=NCLS-CORE-00087;|
  Grizzly 2.4.4 started in: 3,513ms - bound to [http-listener-1:8080, http-listener-2:8181, admin-listener:4848]|#]

[#|2021-08-24T11:28:47.440+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=25;_ThreadName=RunLevelControllerThread-1629804523803;_TimeMillis=1629804527440;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener iiop-service started in: 9ms - bound to [/0.0.0.0:3700]|#]

[#|2021-08-24T11:28:47.600+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527600;_LevelValue=800;_MessageID=NCLS-CORE-00017;|
  Payara Server  5.2021.6 #badassfish (4579) startup time : Felix (2,627ms), startup services(4,293ms), total(6,920ms)|#]

[#|2021-08-24T11:28:47.606+0000|INFO|Payara 5.2021.6|fish.payara.nucleus.cluster.PayaraCluster|_ThreadID=70;_ThreadName=Executor-Service-4;_TimeMillis=1629804527606;_LevelValue=800;|
  Data Grid Status
Payara Data Grid State: DG Version: 4 DG Name: development DG Size: 1
Instances: {
 DataGrid: development Name: server Lite: false This: true UUID: 0e1a7ed0-987b-4659-a9d0-3c83656b50ad Address: /172.17.0.2:4900
}|#]

[#|2021-08-24T11:28:47.624+0000|INFO|Payara 5.2021.6|fish.payara.nucleus.notification.NotificationService|_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527624;_LevelValue=800;|
  Payara Notification Service bootstrapped.|#]

[#|2021-08-24T11:28:47.645+0000|INFO|Payara 5.2021.6|monitoring-console-core|_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527645;_LevelValue=800;|
  Bootstrapping Monitoring Console Runtime|#]

[#|2021-08-24T11:28:47.697+0000|INFO|Payara 5.2021.6|monitoring-console-core|_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527697;_LevelValue=800;|
  Starting monitoring data collection for server|#]

[#|2021-08-24T11:28:47.702+0000|INFO|Payara 5.2021.6|monitoring-console-core|_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527702;_LevelValue=800;|
  Starting monitoring watch collection for server|#]

[#|2021-08-24T11:28:47.853+0000|INFO|Payara 5.2021.6|javax.enterprise.system.jmx|_ThreadID=116;_ThreadName=Thread-20;_TimeMillis=1629804527853;_LevelValue=800;_MessageID=NCLS-JMX-00024;|
  Creating a SecureRMIServerSocketFactory @ 0.0.0.0 with ssl config = GlassFishConfigBean.org.glassfish.grizzly.config.dom.Ssl|#]

[#|2021-08-24T11:28:47.856+0000|WARNING|Payara 5.2021.6|javax.enterprise.system.jmx|_ThreadID=116;_ThreadName=Thread-20;_TimeMillis=1629804527856;_LevelValue=900;_MessageID=NCLS-JMX-00020;|
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults|#]

[#|2021-08-24T11:28:47.865+0000|INFO|Payara 5.2021.6|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1629804523310;_TimeMillis=1629804527865;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener JMS_PROXY_default_JMS_host started in: 14ms - bound to [/0.0.0.0:7676]|#]

[#|2021-08-24T11:28:47.884+0000|INFO|Payara 5.2021.6||_ThreadID=1;_ThreadName=main;_TimeMillis=1629804527884;_LevelValue=800;|
  Reading in commandments from /opt/payara/config/post-boot-commands-final.asadmin|#]

[#|2021-08-24T11:28:47.889+0000|WARNING|Payara 5.2021.6|javax.enterprise.system.jmx|_ThreadID=116;_ThreadName=Thread-20;_TimeMillis=1629804527889;_LevelValue=900;_MessageID=NCLS-JMX-00020;|
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults|#]

[#|2021-08-24T11:28:47.919+0000|INFO|Payara 5.2021.6|javax.enterprise.system.jmx|_ThreadID=116;_ThreadName=Thread-20;_TimeMillis=1629804527919;_LevelValue=800;_MessageID=NCLS-JMX-00025;|
  SSLServerSocket /0.0.0.0:8686 and [SSL: ServerSocket[addr=/0.0.0.0,localport=8686]] created|#]

[#|2021-08-24T11:28:48.172+0000|INFO|Payara 5.2021.6|javax.enterprise.system.jmx|_ThreadID=116;_ThreadName=Thread-20;_TimeMillis=1629804528172;_LevelValue=800;_MessageID=NCLS-JMX-00005;|
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi|#]

[#|2021-08-24T11:28:52.995+0000|INFO|Payara 5.2021.6|org.jvnet.hk2.osgiadapter|_ThreadID=15;_ThreadName=FelixStartLevel;_TimeMillis=1629804532995;_LevelValue=800;|
  Skipping registration of inhabitant for service reference [org.osgi.service.metatype.MetaTypeProvider] as the service object could not be obtained.|#]
  
5. Here is how I checked to see if the application has been deployed automatically.  
  
COMMAND 1 - login in to the container shell
 
C:\windows\system32>docker exec -it bwbportal /bin/bash

COMMAND 2 - Checking container environmental variables

payara@fe75584ec9ec:~$ env
LC_ALL=en_US.UTF-8
PAYARA_ARGS=
LANG=en_US.UTF-8
DEPLOY_PROPS=
HOSTNAME=fe75584ec9ec
PREBOOT_COMMANDS_FINAL=/opt/payara/config/pre-boot-commands-final.asadmin
JAVA_HOME=/usr/lib/jvm/zulu8-ca-amd64
HOME_DIR=/opt/payara
PWD=/opt/payara
POSTBOOT_COMMANDS=/opt/payara/config/post-boot-commands.asadmin
HOME=/opt/payara
DEPLOY_DIR=/opt/payara/deployments
ADMIN_USER=admin
DOMAIN_NAME=domain1
PREBOOT_COMMANDS=/opt/payara/config/pre-boot-commands.asadmin
JVM_ARGS=
MEM_XSS=512k
TERM=xterm
PASSWORD_FILE=/opt/payara/passwordFile
ADMIN_PASSWORD=admin
CONFIG_DIR=/opt/payara/config
SCRIPT_DIR=/opt/payara/scripts
SHLVL=1
LANGUAGE=en_US:en
POSTBOOT_COMMANDS_FINAL=/opt/payara/config/post-boot-commands-final.asadmin
MEM_MAX_RAM_PERCENTAGE=70.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/payara/appserver/bin
PAYARA_DIR=/opt/payara/appserver
_=/usr/bin/env

COMMAND 3 - Changing directory to payara home directory

payara@fe75584ec9ec:~$ cd $PAYARA_DIR

COMMAND 4 - Listing contents of  payara home directory

payara@fe75584ec9ec:~/appserver$ ls

bin  glassfish  h2db  META-INF  mq  README.txt

COMMAND 5 - Changing directory to bin directory in payara home

payara@fe75584ec9ec:~/appserver$ cd bin

COMMAND 6 - running payara list-applications command to show list of deployed applications
asadmin list-applications
Do you trust the above certificate [y|N] -->y
Enter admin user name> admin
Enter admin password for user "admin">
Nothing to list.
No applications are deployed to this target server.
Command list-applications executed successfully.
## Environment ##

- **Distribution**:  Server Full Profile 
- **JDK Version**:  openjdk version "1.8.0_282"
- **Operating System**: Windows

**Comment by rdebusscher** [comment]
Fix released as part of 5.2021.7.

**Comment by tikonza** [comment]
I tested and its indeed working.

Thank you!
