### ISSUE TITLE
Bug Report:  xml header for jpa 3 not transformed in 5.2021.6/FISH-5678

### ISSUE THREAD

**Issue by eduarddrenth** [payara/Payara#5404]
# Description #
----------

When deploying a ee9 jpa 3 application to payara containing a persistence.xml with a jpa 3 header you will run into an error:

```javax.persistence.PersistenceException: No Persistence provider for EntityManager named```

## Expected Outcome ##

Persistence provider available

## Current Outcome ##

```javax.persistence.PersistenceException: No Persistence provider for EntityManager named```

## Steps to reproduce ## 

deploy app with persistence.xml containing this xml header:

```<persistence xmlns="https://jakarta.ee/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.0">```

## Environment ##

- **Distribution**: 5.2021.6-jdk11
- **JDK Version**: openjdk version "11.0.11" 2021-04-20
- **Operating System**: 5.11.0-34-generic #36~20.04.1-Ubuntu SMP

**Comment by eduarddrenth** [comment]
thanks, I'll test in due time

**Comment by rdebusscher** [comment]
The fix for this was released as part of 5.2021.8 (October 2021)
