### ISSUE TITLE
Bug report: Unable to connect securely to database for connection pooling

### ISSUE THREAD

**Issue by shivinm** [payara/Payara#5424]
Hey all, 
We are using Payara version 5.2021.4 and Payara's database connection pooling. 

We are unable to make a secure connection a MariaDB instance in Amazon RDS service by setting flag **useSSL=true** in the connection properties. 

The connector library in Payara is `mysql-connector-java-5.1.49-bin.jar` which is compatible with MariaDB version `10.3.23`. MaraDB is SSL enabled

```

mysql> SHOW VARIABLES LIKE 'have_ssl';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| have_ssl      | YES   |
+---------------+-------+
```

<img width="1401" alt="Screen Shot 2021-09-24 at 3 02 12 PM" src="https://user-images.githubusercontent.com/5727055/134739637-eb7d6ed0-3c29-4a6a-b18d-379b48401ae3.png">

On a PIng Test: 
<img width="1438" alt="Screen Shot 2021-09-24 at 3 02 29 PM" src="https://user-images.githubusercontent.com/5727055/134739646-3b20738f-8eb0-4dda-95d1-d401f3717040.png">

From `server.log`

```
[2021-09-24T21:03:21.660+0000] [Payara 5.2021.4] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.allocator] [tid: _ThreadID=70 _ThreadName=http-thread-poo\
l::http-listener-1(1)] [timeMillis: 1632517401660] [levelValue: 900] [[
  RAR5038:Unexpected exception while creating resource for pool apipool. Exception : javax.resource.spi.ResourceAllocationException: Connection could not be allocated because: Communications\
 link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]]
```

NOTE 1: When we set  `useSSL=false` in Payara, the connection works

NOTE 2: Importing the PEM certificate file (from https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html ) into `cacerts.jks` keystore and setting `verifyServerCertificate=true` does not help

NOTE 3: When we try connecting to the same database from a SQL client (like DBeaver) and select `Connect using SSL`, the connection works, so it looks like an issue with Payara's database connection logic specifically.

Is this a known bug in Payara? Any idea if we are doing something wrong?  

Not able to find much documentation on this online, so help is appreciated.

**Comment by shub8968** [comment]
Hi @shivinm,

You have mentioned that you have installed the PEM file in the KeyStore. Can you confirm which keystore, the Java one (=the wrong one) or Payara one? Payara Connection pool cannot be the issue here, it just uses the driver and the configuration parameters.  It t seems to be a driver issue. I recommend you using the recent version of the driver. (5.1 is more then 4 years old)

**Comment by smak03** [comment]
Hi @shivinm 
Greetings!

Can you please let me know in case your problem is resolved or not?
I am facing the same issue with payara6.

So, it would be appropriated if you can let me know if you are able to resolve the issue.

Regards,
Sagar Makwana.
