### ISSUE TITLE
Bug Report:  Environment variable substitution mechanism does not work in asadmin stop-domain

### ISSUE THREAD

**Issue by dxinid** [payara/Payara#5439]
# Description #
----------

I have payara version **4.1.2.174**.
I want to have the admin port in an environment variable defined in asenv.conf. 
I have also several other environment variables (ports mainly) that are defined in this configuration file.

So I set this variable to:
ASADMIN_LISTENER_PORT=4848

In the domain.xml I have defined the defined as shown below.

<network-listener protocol="admin-listener" port="${ASADMIN_LISTENER_PORT}" name="admin-listener" thread-pool="admin-thread-pool" transport="tcp"></network-listener>

When using **asadmin start-domain** all enviroment variables are set and the ports in domain.xml get the corresponding values in asenv.conf and payara starts normally.
But when I run **asadmin stop-domain** it seems  all of the environment variables are not set. 
This leads to the error: 
**Cannot find admin port in domain.xml file**

## Expected Outcome ##

Based on the fact that the enviroment variables defined in asenv.conf are normally processed in domain.xml during the 
start of the server (asadmin start-domain) I would expect the same behavior during the stop process.

## Current Outcome ##

When I run **asadmin stop-domain** it seems that all of the environment variables are not set. 
This leads to the error: 
**Cannot find admin port in domain.xml file**

## Steps to reproduce ## 

[1] Define variable ASADMIN_LISTENER_PORT=4848 in  glassfish4/glassfis/config/asenv.conf
[2] Change the admin port in the domain.xml
i.e 
<network-listener protocol="admin-listener" port="${ASADMIN_LISTENER_PORT}" name="admin-listener" thread-pool="admin-thread-pool" transport="tcp"></network-listener>
[3] Go to glassfish4/bin and run:
  [3.1] ./asadmin start-domain
  [3.2] ./asadmin stop-domain
asadmin cli prints **Cannot find admin port in domain.xml file is shown**

## Environment ##

- **Distribution**: 
-  Server Full Profile payara version **4.1.2.174**.
- **JDK Version**: 
- Open JDK 8
- **Operating System**: 
- Linux

**Comment by AlanRoth** [comment]
Hi,

Please check if this issue exists in the latest Payara Community version, the Payara4 version you are using is not publicly supported.

Thanks,
Alan
