### ISSUE TITLE
Bug Report: ACC is missing lots of Jersey libraries

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5464]
# Description #

Apparently the following modules (at least, possibly more) are missing in the ACC created by `package-appclient`:
* jersey-hk2.jar
* jersey-media-json-binding.jar
* jersey-media-jaxb.jar
* jersey-media-json-jackson.jar
* jersey-media-json-processing.jar
* jersey-media-moxy.jar
* jersey-media-multipart.jar
* jersey-media-sse.jar
* jersey-mp-rest-client.jar
* (possibly more)

Due to that, a CAR module running the in the ACC will fail e. g. when it is using JAX-RS Client API (which in turn tries to startup Jersey Client which in turn is missing its HK2 binding).

The cause of this seems to be that those modules are not listed in `MANIFEST.MF` of `gf-client.jar`.

BTW, there also seem to be excess JARs found in the ACC which I assume are not needed by the ACC:
* jersey-server.jar
* jersey-container-servlet-core.jar
* (possibly more)

Those are not assumed to impose any downsides, but produce a bigger bundle to ship as actually needed.

## Expected Outcome ##

ACC should contain *all* needed client modules, but not server modules.

## Current Outcome ##

ACC is missing a list of needed client modules, like the ones listed above, and some server modules.

## Steps to reproduce ## 

`package-appclient -verbose`

## Environment ##

- **Distribution**: Server Full Profile 5.2021.7
- **JDK Version**: Zulu 8
- **Operating System**: Windows

**Comment by mkarg** [comment]
# Workaround

Copying the needed modules manually from the installed Payara host's `modules` folder into the standalone client's ACC's `modules` folder.

**Comment by fturizo** [comment]
@mkarg, I've discussed this issue internally with our product management team and the consensus is that the ACC is not a priority of the Payara Platform roadmap at the moment and so we're not going to implement this fix. 

Feel free to implement a PR with your suggested changes.
