### ISSUE TITLE
Bug Report: Microsoft Defender claims war-util.jar as infected with trojan

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5466]
Since today Microsoft Defender claims war-util.jar to be infected with trojan Trojan:Script/Oneeva.A!ml. As a result, it effecively removes the file war-util.jar from the original location, hence Payara will not work anymore. This happens for 5.2021.7 and 5.2021.8.

Is there a quick workaround for this issue or do we have to wait until Team Payara called Microsoft to get on a Whitelist?

**Comment by mkarg** [comment]
Seems this is known since long time https://stackoverflow.com/questions/63646808/payara-server-5-2020-4-trojanscript-oneeva-aml so can Team Payara please ask Microsoft to put the file an the Whitelist?

**Comment by AlanRoth** [comment]
Hi @mkarg,

Thanks for raising this issue, this was reported directly to Microsoft in September 2nd 2020, and upon further testing was considered resolved.

I will investigate further, as I am not aware of any changes to this file that may have triggered WD false positives again.

Thank you,
Alan

**Comment by mkarg** [comment]
Thanks, Alan, for checking this!
