### ISSUE TITLE
Bug Report:  RWLockDataStructure may leave a read lock /FISH-5858

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#5496]
# Description #
----------

The class RWLockDataStructure has a flawed lock handling which may result in a read lock not being unlocked. This freezes any thread trying to get a write lock.

https://github.com/payara/Payara/blob/master/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java

The method removeAll() clears the resources list outside of write lock (line 204).  Which seems redundant anyway.

```
    public void removeAll() {
        writeLock.lock();
        try {
            Iterator it = resources.iterator();
            while (it.hasNext()) {
                handler.deleteResource((ResourceHandle) it.next());
                it.remove();
            }
        } finally {
            writeLock.unlock();
        }
        resources.clear(); // redundant and removes eventually freshly created resources without properly deleting
    }
```

If this happens while some other thread calls the method getResource() (at line 118) then the resulting IndexOutOfBoundsException prevents unlocking the currently held read lock. The code is lacking some finally block to unlock the readlock.

```
    public ResourceHandle getResource() {
        readLock.lock();
        for(int i=0; i<resources.size(); i++){
            ResourceHandle h = resources.get(i); // this will cause an exception if the code above has cleared the list
            if (!h.isBusy()) {
                readLock.unlock();
                writeLock.lock();
                try {
                    if (!h.isBusy()) {
                        h.setBusy(true);
                        return h;
                    } else {
                        readLock.lock();
                        continue;
                    }
                }finally {
                    writeLock.unlock();
                }
            } else {
                continue;
            }
        }
        readLock.unlock(); // this should be in a finally block to prevent lost read locks
        return null;
    }
```

## Expected Outcome ##

All aquired locks will always be unlocked.

## Current Outcome ##

If the aquired read lock is not returned in case an exception is thrown at line 118 the RWLockDataStructure stays read locked and the server starts to block all threads trying the aquire a write lock.

## Steps to reproduce ## 

As always with race conditions it is not that simple to predictably provoke this situation. But the code is simple enough to spot the problem.

## Environment ##

- **Distribution**: 5.2020.5 Full
- **JDK Version**: OpenJDK 11
- **Operating System**: Linux

**Comment by fturizo** [comment]
@svendiedrichsen, thanks for catching this up. I understand that trying to reproduce this might be a bit difficult due to the nature of how connection pool threading works, but do you have a specific scenario in mind that might help understand the race condition that you are patching?

**Comment by svendiedrichsen** [comment]
@fturizo While doing performane tests for a migration from Oracle to Postgres we were experiencing some server freezes. Simillar to this bug report: https://stackoverflow.com/questions/62214204/issues-with-postgres-connections-pool-on-payara-glassfish

A thread dump revealed all threads except 1 were waiting on a lock in the above mentioned class. The thread which owned the lock, the only one running, didn't have the lock statement in its thread dump.

We were above 400 req./sec. when this started to appear after some minutes. But we have seen it quite regularly below this mark after some more time.

**Comment by fturizo** [comment]
@svendiedrichsen, thanks for clearing it up. Would it be possible for you to share a copy of the thread dump that helped you identify the issue so we can use it as evidence of the problem in question?

**Comment by svendiedrichsen** [comment]
@fturizo I will ask our Ops Team for the thread dump and attach it here when I get it.

**Comment by svendiedrichsen** [comment]
@fturizo this is the thread dump which shows the locking problem. The lock on which most threads are waiting for is `5ad7eb53` which is owned by Thread `t@353` which itself does not have the lock in its threaddump.

[threaddump-1636631066418.txt.zip](https://github.com/payara/Payara/files/7537525/threaddump-1636631066418.txt.zip)

**Comment by svendiedrichsen** [comment]
@fturizo the class  RWLockDataStructure could use a major rework. The locking seems too restrictive for such a heavily accessed component.

**Comment by fturizo** [comment]
Thanks for sharing the thread dump, @svendiedrichsen. I have escalated your contribution to our Platform Development team so that they can review it and provide their input. The dump clearly shows that there are several blocked threads waiting for the read lock, which will never be released, so there's enough evidence of the issue. 

I do agree with you with a rework to the class, but it would require proper planning and discussion due to the class being instrumental in how JDBC resources behave internally, but I'll pass the sentiment to our Platform Development team nonetheless.
