### ISSUE TITLE
Bug Report:  alternative docroots cease working after some time

### ISSUE THREAD

**Issue by maartenl** [payara/Payara#5498]
# Description #
----------

I have war files deployed using Payara Microprofile on a Docker image with GraalVM. One of the war files (deployed on the root path) has alternative docroots assigned in the glassfish-web.xml file.

I'm sorry I don't have any more information, but I welcome advice on how to be able to provide more debugging information.

(I'm also not convinced that it might not be a Docker problem, but I'm just not sure.)

https://github.com/maartenl/Land-of-Karchan/blob/master/karchan/src/main/webapp/WEB-INF/glassfish-web.xml

## Expected Outcome ##

Static files on the filesystem can be accessed using the URLs defined in the glassfish-web.xml in the alternative docroots.

## Current Outcome ##

Payara Microprofile returns 404. File not found.

## Steps to reproduce ## 

- create a war file,
- add a glassfish-web.xml file
- add alternative docroots to the glassfish-web.xml file
- deploy the war file using Payara microprofile - GraalVM docker image
- wait (one week or two) for the problem to arise that static files can no longer be accessed.

## Environment ##

- **Distribution**: 
payara-micro-5.2021.1.jar 

- **JDK Version**: 
- openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

- **Operating System**: 
- CentOS Linux 7 (Core) (a Jelastic Docker image base)
https://hub.docker.com/repository/docker/maartenl22/jelasticgraaljdk11
https://github.com/maartenl/jelasticgraaljdk11

**Comment by shub8968** [comment]
Hi @maartenl,

Will you be able to share the proper reproducer app? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it. If you think you need help or advice, please feel free to open a discussion on our community forum - https://forum.payara.fish/ .

**Comment by maartenl** [comment]
I'm going to close this issue, until I have more information.

It doesn't seem to be related to the alternative docroots, but more related to my code and the storing of static files in the war itself.
