### ISSUE TITLE
Version the Download artifacts

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#55]
On the current Payara download site (http://www.payara.co.uk/downloads), the artifacts are without a version (i.e. payara.zip rather than payara-4.1.114.zip). This makes it a lot easier to integrate into Chef ( #51 ) and other configuration management tools if the names of the artifacts can be derived from the version of the artifact.

**Comment by smillidge** [comment]
Can we get the Jenkins build to add on the version and build-id to the zip files when moving onto the website please?

Also can we rename the download zips on the website?

**Comment by Pandrex247** [comment]
The main release zips have now been renamed to included the version number (e.g. payara-4.1.144.zip), and the pre-release builds have been appended with "prerelease" (e.g. payara-web-prerelease.zip).
