### ISSUE TITLE
ClassCastException while casting DefaultJwtParserBuilder to JwtParserBuilder

### ISSUE THREAD

**Issue by monor001** [payara/Payara#5504]
# Description #
----------

 I use Auoth2 Authentification Mechanism in a Batch Framework in order to authenticate the technical user. The Batch Mechanism has its part where the authentication code get parsed to a valid JWT. 

## Current Outcome ##

 I am using jjwt-api and jjwt-impl liberaries version 0.11.2; in order to parse to a valid JWT. During this parsing process, the following exception is always thrown:
java.lang.ClassCastException: io.jsonwebtoken.impl.DefaultJwtParserBuilder cannot be cast to io.jsonwebtoken.JwtParserBuilder. 

## Expected Outcome ##

 I have tested this liberary with normal unit test framework and it's working fine. So i expect that parsing is performed normally under Payara. 

## Steps to reproduce ## 

 Well its hard to describe this because its a bit complex System i am using currently. But if necessary i would give a general idea depending on request. 

## Environment ##

- **Distribution**:  Server Full Profile  
- **JDK Version**:  JDK 8 
- **Operating System**:  Windows

**Comment by shub8968** [comment]
Hi @monor001,

We don't investigate bug reports unless we have a reproducer that’s provided by the user who reports the defect. Kindly update the issue with a reproducer that ideally follows the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by shub8968** [comment]
closing due to no response.
