### ISSUE TITLE
Errors when building Payara source  

### ISSUE THREAD

**Issue by BreDenro** [payara/Payara#5509]
# Description #
----------

I am trying to build Payara, but it always fails. It is not my system, since I can build other Java code from github without problems.

## Expected Outcome ##

The build completes and no errors

## Current Outcome ##

I use the current Java 17 version and get this:

[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:4.1.0:manifest (default-manifest) on project scattered-archive-api: Execution default-manifest of goal org.apache.felix:maven-bundle-plugin:4.1.0:manifest failed.: ConcurrentModificationException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :scattered-archive-api

Then I use the previous Java version (11) and I get a different error:

[ERROR] Failures: 
[ERROR]   DirWatcherTest.itemsFoundAsTheyAreAdded:93->assertTrue:163 root item should be found
[ERROR]   DirWatcherTest.itemsFoundIfRootDoesNotExist:122->assertTrue:163 root item should be found
[ERROR]   DirWatcherTest.itemsFoundIfTwoLevelsDoNotExist:141->assertTrue:163 root item should be found
[INFO] 
[ERROR] Tests run: 127, Failures: 3, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Payara Project 5.2021.10-SNAPSHOT .................. SUCCESS [  0.147 s]
[INFO] Nucleus Grizzly jars Combining 5.2021.10-SNAPSHOT .. SUCCESS [  0.881 s]
[INFO] Public APIs of Glassfish 5.2021.10-SNAPSHOT ........ SUCCESS [  1.906 s]
[INFO] GlassFish Nucleus Common modules 5.2021.10-SNAPSHOT  SUCCESS [  0.030 s]
[INFO] Common Utilities 5.2021.10-SNAPSHOT ................ FAILURE [  5.197 s]

With this same Java version I also try 
mvn clean install -DskipTests

But still the build stops very quickly with this error 

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project payara-api: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

I also tried this

mvn clean install -DskipTests -Dmaven.javadoc.skip=true

And again the build stops with an error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project healthcheck-cpool: Compilation failure: Compilation failure: 
[ERROR] /Users/breno/java/Payara/nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java:[165,22] reference to Module is ambiguous
[ERROR]   both interface com.sun.enterprise.config.serverbeans.Module in com.sun.enterprise.config.serverbeans and class java.lang.Module in java.lang match
[ERROR] /Users/breno/java/Payara/nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java:[167,26] reference to Module is ambiguous
[ERROR]   both interface com.sun.enterprise.config.serverbeans.Module in com.sun.enterprise.config.serverbeans and class java.lang.Module in java.lang match
[ERROR] -> [Help 1]

## Steps to reproduce ## 

git clone https://github.com/payara/Payara.git
mvn install

or

mvn clean install -DskipTests

or

mvn clean install -DskipTests -Dmaven.javadoc.skip=true

## Environment ##

- **Distribution**: 5.2021.10-SNAPSHOT, but I also try other tags, same problem
- **JDK Version**: 17 and 11
- **Operating System**: Mac, but I also tried on Linux, same problem

**Comment by lprimak** [comment]
You need JDK 8 to build Payara, JDK 11 & 17 not supported for building (yet)

**Comment by shub8968** [comment]
Thanks, @lprimak for answering.

**Comment by BreDenro** [comment]
@lprimak, thanks for your answer. That was really unexpected. How does this work? I don't understand how if something doesn't compile for JDK 11 or JDK 17 can work on JDK 11 or JDK 17.

I shall create a new issue to support this anyway, but your answer would still be appreciated.
