### ISSUE TITLE
Support for MicroProfile 5.x

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara#5521]
MicroProfile 5.0 will be the first release of MicroProfile supporting the _jakarta_ namespace.

Payara Server 6 and Payara Micro 6 will support (pass the TCK) the MicroProfile Umbrella specifications.

- Config
- Metrics
- Health
- Fault tolerance
- JWT
- OpenAPI
- OpenTracing
- RestClient

**Comment by smillidge** [comment]
Released in Payara 6 alpha 2
