### ISSUE TITLE
Enhancement: CDI annotation scanning is very slow /FISH-5938

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5530]
# Description #
----------
After upgrade of some library that uses kotlin-sdk dependency the deployment started timeouting.
Thread dumps navigated me to WeldUtils and I have identified really inefficient implementation of annotation scanner.

## Expected Outcome
Successful deployment after a few seconds.

## Current Outcome

Timeout after 600 seconds and still deploying...

## Alternatives
I will create PR with enhancement.

## Context
Some kotlin annotations are very cyclic and this causes milions of scans of the same annotation set.

**Comment by sgflt** [comment]
Test case available at https://github.com/sgflt/payara-test-case/commit/0cdedfb651a247a43ccea63842f05e93d392dd16

**Comment by fturizo** [comment]
Your community contribution will soon be reviewed by the Platform Development team, many thanks!
