### ISSUE TITLE
java.lang.NoSuchMethodError: org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by bugeaud** [payara/Payara#554]
Running latest Paraya 4.1.1.154 (build 270) "out of the box", and trying lates Hibernate OGM, will raise the following :

Infos:   OGM000001: Hibernate OGM 5.0.0.Alpha1
Grave:   java.lang.NoSuchMethodError: org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V
	at org.hibernate.internal.NamedQueryRepository.checkNamedQueries(NamedQueryRepository.java:149)

On a regular GF 4.1.1, updating to the latests jboss-logging.jar in glassfish\modules semmed to fixed the issue.
Doing the same on Paraya does not do so ...

**Comment by bugeaud** [comment]
Here is an extract of the dependencies I used :
    
    <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.hibernate.ogm</groupId>
            <artifactId>hibernate-ogm-bom</artifactId>
            <version>5.0.0.Alpha1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>

<dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.4</version>
            <scope>provided</scope>
        </dependency>
        
<dependency>
    <groupId>org.hibernate.ogm</groupId>
    <artifactId>hibernate-ogm-mongodb</artifactId>
</dependency>

<dependency>
  <groupId>com.fasterxml.jackson.jaxrs</groupId>
  <artifactId>jackson-jaxrs-json-provider</artifactId>
  <version>2.6.3</version>
</dependency>
</dependencies>

**Comment by smillidge** [comment]
Can you give us a simple war as a test case that demonstrates the error occurring?

**Comment by bugeaud** [comment]
For instance https://github.com/bugeaud/dualquiz/ to display the dummy helloworld message.

The fail happen at start/deploy time.

**Comment by OndrejM** [comment]
@smillidge I've built a sample application for myself giving the same NoSuchMethodError on both Glassfish and Payara 4.1.1.154. However, updating to the latest jboss-logging.jar fixed the problem in both Glassfish and Payara. I'm not sure what was the exact build of the Payara, as I'm not at the computer, but it was downloaded as docker image payaradocker/payaraserver:4.1.1.154.

**Comment by smillidge** [comment]
OK @bugeaud can you try cleaning out the osgi-cache after updating the  jboss-logging.jar. The osgi-cache is located at <domain-root>/osgi-cache  for example
/opt/payara41/glassfish/domains/domain1/osgi-cache

**Comment by bugeaud** [comment]
@smillidge clean out has fixed the issue. Tnx ! I did not had to do this on regular GF FYI. I consider this as closed altough the update of the artefact might worth investingating.

**Comment by mahgtavares** [comment]
Hi, I'm having the same issue, and the folder osgi-cache do not exists in C:\Program Files\glassfish-4.1.1\glassfish\domains\domain1

Am I in the wrong folder? Could be another thing?

**Comment by smillidge** [comment]
Payara 162 (the latest release) has an upgraded JBoss logging jar.

The osgi-cache folder will be in the domain folder so if you use domain1 then it will be in the domain1 folder. If you use a custom domain then it will be in the custom domain folder under C:\Program Files\glassfish-4.1.1\glassfish\domains\

The osgi-cache directory will only be there if you have started the server once.

**Comment by OndrejM** [comment]
Payara 162 also provides an option to give precedence to classes in your application over the classes delivered with the server. In case you have these problems also with Payara 162 and later versions, you may want to turn this feature on. Look into the [docs for more detail](https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html) (the section 5 at the end provides a summary if you don't want to read whole documentation page :wink: )

**Comment by gorannovotny** [comment]
Payara 162 has an upgraded jboss-logging.jar to version 3.3.0.Final but payara-micro 162 jboss logging classes are not updated.

**Comment by OndrejM** [comment]
@gorannovotny I checked Payara Micro 162 and it contains JBoss Logging 3.3.0.Final - the sae as Payara Server 162. I also checked the class files and they seem to be the same as in Payara Server.

What makes you think that Payara Micro has an older version of jboss logging classes?

**Comment by gorannovotny** [comment]
First, i had a problem with payara micro 162 and hibernate ( with debugf
).  There was no such problem with payara full 162.
Then, i compared payara-micro jar and  jboss-logging-3.3.0.Final.jar from
maven repository.
In payara-micro-4.1.1.162.jar in /org/jboss/logging/ directory almost all
files are different.

**Comment by OndrejM** [comment]
Thanks @gorannovotny, on a second look you are right.

The metadata in payara-micro.jar (META-INF/maven/org.jboss.logging/pom.xml) claim that the version of jboss logging is 3.3.0.Final - the same as in Payara Server. When I compared the class files, there are the same files in both, but amost all of them have different size. Those, which have different size, have an old timestamp 2012-02-02, while those which are the same have also the same timestamp as in Payara Server (2015-05-28).

@gorannovotny, would you create a separate issue, as this one is closed already, and it is not the same thing?

**Comment by OndrejM** [comment]
The issue with older version of jboss-logging in Payara-Micro will be fixed in 163 release due in August. 

It was a problem of packaging, where an older version of jboss logging bundled with  hibernate-validator.jar was picked up before the newer version.

**Comment by lprimak** [comment]
Both Payara Micro and the Payara domain should contain the classloading preference by default: https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html

**Comment by OndrejM** [comment]
I created a separate issue #955 for Payara Micro and embedded as this one is closed.

**Comment by MadhaviLReddy** [comment]
**Need help, Hibernate4 logging is not happening with Glassfish5:**
We are migrating our application to Hibernate4.3.11, Spring4.3.11 and we deploy on to GlassFish5. Along with this we also upgraded our logging framework to log4j2 by adding dependencies for log4j-1.2-api:2.10.

After the up-gradations  the application is working fine and the logs are generated except for Hibernate.

Tried following to solve Hibernate logging issue:
Hibernate4 onwords uses jboss-logging framework, hence we added latest version of jboss-logging which is 3.3.1.Final.
Still the logging is not happening because Glassfish5 comes up with its own jboss-logging.jar(which is again 3.3.1.Final) in the modules. Some how glassfish/modules/jboss-logging.jar is loaded very much before the web module jars are loaded. The Jboss-logging framework tries to identify which logging framework to use by checking the classpath.
At the time when glassfish/modules/jboss-logging.jar is loaded log4j-1.2-api.jar is not yet available for the class loader hence it is not able to find the log4j2 framework on the classpath. Hence the logging is defaulting to JDK logging.

Is there a way to tell Glassfish to load  log4j-1.2-api.jar along with jboss-logging.jar? Can we add log4j-1.2-api.jar in the glassfish/modules?

To solve this we tried adding glassfish-web.xml with<class-loader delegate="false" />element in it. This solves the issue but we are not very sure if this approach has any side issues as the document says: "It's safe to set this to false only for a web module that does not interact with any other modules."

Looking for some help to check if there is any other way to solve our issue. Please help.

**Comment by michaelranaldo** [comment]
Hi @MadhaviLReddy ,

Would you please open a [new issue](https://github.com/payara/Payara/issues/new) with your information? 

If you could also include a way of reproducing your issue on Payara Server that would be appreciated.

If it is an urgent issue which you would require immediate help from our engineers, I'd recommend that you have a look at our [support packages](https://www.payara.fish/support).

**Comment by MadhaviLReddy** [comment]
Thank you Michael for the response, the issue is with Glassfish5 and not with Payara Server. Can you please guide me where I can ask or raise an issue for Glassfish5.

**Comment by michaelranaldo** [comment]
Hi @MadhaviLReddy ,

Issues for GlassFish 5 can be raised on [their GitHub repository](https://github.com/javaee/glassfish/issues/new).

Again, applications which work on GlassFish will also work on Payara Server, so feel free to give us a try if you continue to have issues :)

**Comment by Raj1071** [comment]
I am facing the JBoss issue in WebSphere server, it's not able to read JBoss logging

**Comment by anshulsood2006** [comment]
I was able to resolve the issue by upgrading the hibernate-core jar version to 5.4.1.Final

	<dependency>
		<groupId>org.hibernate</groupId>
		<artifactId>hibernate-core</artifactId>
		<version>5.4.1.Final</version>
	</dependency>
