### ISSUE TITLE
Enhancement: Support partial configuration files

### ISSUE THREAD

**Issue by rsoika** [payara/Payara#5565]
I want to make a suggestion regarding the possibility to run payara with partial configuraiton files.

I use Payara with Docker in many projects. Mostly I need to add JDBC Pools and security config.

To build a new Docker image I have to customize the domain.xml file and add this customized file in my Dockerfile. So I have to maintain the full domain.xml file.

It would be fine if payara provides a similar feature like OpenLiberty that I only provide the config part I am interesting in in a separate partial-domain.xml file. During startup payara is merging the content. So for example a JDBC config file would simple look like this:

 

```xml
 <?xml version="1.0" encoding="UTF-8" ?>
<domain>
    <resources>
		<!-- my database -->
		<jdbc-connection-pool datasource-classname="org.postgresql.ds.PGSimpleDataSource" name="my-db" res-type="javax.sql.DataSource">
	      <property name="Url" value="jdbc:postgresql://db/my-db"></property>
	      <property name="Password" value="adminadmin"></property>
	      <property name="User" value="abc"></property>
	    </jdbc-connection-pool>
	    <jdbc-resource pool-name="my-db" jndi-name="jdbc/my-db"></jdbc-resource>
    </resources>
    <servers>
        <server name="server" config-ref="server-config">
            <resource-ref ref="jdbc/my-db"></resource-ref>
        </server>
    </servers>
</domain>
```

The database resource is merged into the origin domain.xml file by payara.

In this way users could easily upgrade the payara version. Currently it is necessary to copy the new domain.xml file and customize it again.

What do you think about that feature?

**Comment by smillidge** [comment]
Have you thought about just defining the datasource in the deployed application as an alternative?

If that doesn't work for you could you describe the use case in more detail?

**Comment by lprimak** [comment]
I always liked how Payara had a single configuration, and disliked how WildFly / JBoss (for example) had a whole bunch of subdirectories with partial configuration files.
The JBoss / WildFly way of doing things was always confusing to me, leading to a lack of understanding of the whole configuration of the server.

As Steve said above, the thrust of the effort should be self-contained configuration within the application.

IMHO "partial" configurations ala JBoss is a bad idea.

**Comment by rsoika** [comment]
What did you mean with 

>  defining the datasource in the deployed application as an alternative

I am developing a Workflow Engine based on Jakarta EE ([Imixs-Workflow](https://www.imixs.org)) . I do not make any assumptions about the target database in my implementation. My Implementation just injects a persistence context. 

```java
	@PersistenceContext(unitName = "org.imixs.workflow.jpa")
	private EntityManager manager;
```

This context can be mapped in the persistence.xml of any web application using my workfow-engine library. 
And the resulting artefact (a web application) can than be deployed into any Jakarta EE runtime.

This was always my understanding of adapting Jakarta EE - writing independent modules. I don't want to configure my Database in my code like this is done in many Spring projects....

**Comment by lprimak** [comment]
then you don't have to worry about it! Problem solved

**Comment by rsoika** [comment]
No, I don't think that my problem is solved. To configure payara running my application I need to define for example a jdbc-connection-pool to connect to my Oracle, PostgreSQL or what ever. 
Running with the official Docker image in a Kubernetes environment, I need to provide a full domain.xml file with all the configuration details regarding to the corresponding Payara release - even if I only want to configure the jdbc-pool.

In OpenLiberty for example I can provide one additional xml file just containing this specific jdbc resource. And during startup the OpenLiberty server merges this configuration to its main configuration. That means I can easily change the release without the customizing full the domain.xml file. 

And it is not just the database - this was one typical example. My application need a mail resource to connect to a specific mail host and of course a security realm based on individual environments (ldap, database, jaspi,.....)

**Comment by rsoika** [comment]
@svendiedrichsen I think I know all this already.  

Imagine you have a web application requesting a JDBC Pools named 'jdbc/my-db'. 

Now you want to run this war file with payara docker. So you would do a Docker file like this:

```
FROM payara/micro:5.2021.10-jdk11
COPY ./target/*.war ${DEPLOY_DIR}
```

But this will not work because you need to configure the database pools 'jdbc/my-db' in Payara.

I don't think this is possible with Custom Scripts? Or how do you solve this. My only solution is to copy a customize domain.xml file into my docker image:

```
FROM payara/micro:5.2021.10-jdk11
COPY ./domain.xml /opt/payara/appserver/glassfish/domains/domain1/config
COPY ./target/*.war ${DEPLOY_DIR}
```

and of course I am working with enviornment variables too.

**Comment by svendiedrichsen** [comment]
I think you should be using the PREBOOT and POSTBOOT command files which contain `asadmin` commands to configure the server: https://docs.payara.fish/community/docs/documentation/ecosystem/docker-images/server-image-overview.html#configuration

**Comment by rsoika** [comment]
But the asadmin command is only working if the server is up and running - so it is not useabel for PREBOOT (do you aggree?)
The the POSTBOOT command I guess is to late if I place the war file into the DEPLOY_DIR. 

So my deployment must be also via asadmin - correct?

**Comment by svendiedrichsen** [comment]
Yes, I agree. PREBOOT is not working for your task. I'm not sure about POSTBOOT and if the POSTBOOT does not also mean PREDEPLOY. But if you do the deployment in the same script you have the most control over the order in which things happen.

**Comment by aubi** [comment]
I do normally asadmin commands in POSTBOOT, this is part of my Dockerfile:
```
RUN echo 'add-library /tmp/postgresql-42.2.8.jar' > $POSTBOOT_COMMANDS
RUN echo 'create-jdbc-connection-pool --datasourceclassname org.postgresql.ds.PGSimpleDataSource ...
RUN echo 'ping-connection-pool dbPool' >> $POSTBOOT_COMMANDS
RUN echo 'create-jdbc-resource --connectionpoolid dbPool jdbc/my-db' >> $POSTBOOT_COMMANDS
```
I think this is doing exactly what you want.

**Comment by rsoika** [comment]
The solution posted from @aubi is the variant I was not aware of - especially for the Docker scenario I think this is a genial simple approach. You need no extra files and you don't need to start the server in a extra image-build phase. We do this extra   "start-configure-shutdown" build cycle in OpenShift with the Source-To-Image concept. And this is an very clumsy way to provide a Docker image. Just adding the POSTBOOT commands in the Dockerfile is much smarter!
Should not this be part of the mentioned [doc page](https://docs.payara.fish/community/docs/documentation/ecosystem/docker-images/server-image-overview.html#configuration) too?

**Comment by fturizo** [comment]
@rsoika, while we appreciate your suggestion in implementing partial configuration files, it is not a feature that we consider in supporting as their use cases are limited and as explained by other users, would require a tremendous amount of effort. As suggested, there are other ways to achieve what you attempt to do, but this is not the right channel to discuss them. Please, kindly raise a topic on the [Payara Forum ](https://forum.payara.fish/c/technical-discussion/10) to seek further assistance.

We'll proceed to close this issue then.
