### ISSUE TITLE
Bug Report:  Payara Connection pool not working for Mariadb jdbc connector

### ISSUE THREAD

**Issue by kazablock** [payara/Payara#5574]
# Description #
----------

Hi team, I are using payara-micro:5.2021.7 for one of our microservices connecting to mariadb and using [java 8 connector 2.7.5](https://mariadb.com/downloads/connectors/connectors-data-access/java8-connector). In my testing i observed that when using the org.mariadb.jdbc.MariaDbPoolDataSource as datasource class and javax.sql.ConnectionPoolDataSource as restype and steady-pool-size and max-pool-size as 40 only 8 connections are created in Database end. Same behaviour is shown in Payara Server 5.2021.7 (Full) also.

## Expected Outcome ##

Specified no of connections should be created and it should be validated in DB end by using "show processlist;" command.

## Current Outcome ##

Currently only 8 connections are created in DB end no matter what is the steady and max pool size. 

## Steps to reproduce ## 

1.  Download latest payara server full. 
2. Add the [java 8 connector 2.7.5](https://mariadb.com/downloads/connectors/connectors-data-access/java8-connector) jar in glassfish/domains/domain1/lib.
3.  Run the following docker compose file of mariadb by docker-compose up
[docker-compose.yml.zip](https://github.com/payara/Payara/files/7917860/docker-compose.yml.zip)
4.  Add new jdbc connection pool via admin ui, set Resource Type as javax.sql.ConnectionPoolDataSource, Datasource Classname as org.mariadb.jdbc.MariaDbPoolDataSource and in AdditionalProperties Password as mypass, User as root, URL as jdbc:mariadb://localhost:3307/mysql. set Initial and Minimum Pool Size , Maximum Pool Size as 40. Create jdbc resource for it with name test-maria-pool. Ping to see if everything is working.
5. Deploy the sample application (mvn clean package and asadmin deploy path/to/war)
[simple-hello.zip](https://github.com/payara/Payara/files/7917848/simple-hello.zip)
6. The application won't deploy and fails with `Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: No connection available within the specified time (option 'connectTimeout': 30,000 ms)`
7. Validate no of connections created by logging into db by exec into container and using mariadb -u root -pmypass to login and  show processlist to view connections. 
8. Only 8 new connections are created not 40 .

 

`
## Environment ##

- **Distribution**: payara-micro:5.2021.7 and payara-full:5.2021.7
- **JDK Version**: OpenJDK 1.8
- **Operating System**:  Windows / Linux / Mac

**Comment by shub8968** [comment]
Hi @kazablock,

Please use `org.mariadb.jdbc.MariaDbDataSource`  in order use the pool in Payara Server. The application is getting deployed. Please configure the datasource properties properly. https://github.com/payara/Payara/issues/2747

**Comment by kazablock** [comment]
Hi @shub8968 
Yes the application deploys with org.mariadb.jdbc.MariaDbDataSource but the required no of connections were not created in DB end with this when i am using Mariadb Galera cluster.

**Comment by shub8968** [comment]
Hi @kazablock,

I was not able to verify it. If you want support on the Clustered arrangement, then I'd recommend considering Payara Enterprise.
