### ISSUE TITLE
Payara, Eclipse and Glassfish tools

### ISSUE THREAD

**Issue by mlb1141** [payara/Payara#558]
I am running Payara 4.1.1.154 and Eclipse Mars on Windows 10.  I have had several bouts of Payara Server start up hanging at 69% when starting from Eclipse.  I have re-installed both Payara and Eclipse several times.  The most recent installation of Eclipse, I do not think I re-installed Glassfish tools.  Do you recommend installing Glassfish tools with Payara and Eclipse?

**Comment by mikecroft** [comment]
This is a recurring issue with GlassFish tools. There is an open issue #370 to track this, so we'll keep the discussion there rather than splitting it over 2 issues.

**Comment by mikecroft** [comment]
To answer the final question, though, I would recommend reinstalling GlassFish tools. I believe that that is the most likely place for the error to be occurring.

**Comment by mlb1141** [comment]
Thanks Mike.
