### ISSUE TITLE
Enhancement: Update JNA in order to work with Apple Silicon (aarm64e) architecture / FISH-6578

### ISSUE THREAD

**Issue by skiedrowski** [payara/Payara#5581]
# Description #
----------

Update JNA (https://github.com/java-native-access/jna, `net.java.dev.jna:jna`) in order to work with Apple Silicon (aarm64e) architecture.

## Expected Outcome

`pom.xml`->`jna.version` used is 5.10.0
Payara Embedded contains jna in Version 5.10.0.

## Current Outcome

jna.version is 5.2.0 (and 4.5.2 for libpam4j)

## Context

I am using payara embedded (5.2020.6 and 5.2021.10) in Tests. It is a very simple solution to provide JakartaEE Spec implementations matching the server side implementation to unit and integration tests.
I am also using Vaadin Testbench which uses JNA for license validation. 
Now there are two JNA Versions in my test classpath: the one contained in payara-embedded (5.2.0) and the one provided by vaadin testbench (5.7.0). License validation fails on Apple Silicon (aarm64e) if V5.2.0 is used (see https://github.com/vaadin/testbench/issues/1308).

5.2.0 predates Apple Silicon (Release Dec. 2018)

**Comment by AlanRoth** [comment]
Hi @skiedrowski 

Thank your for the request, it will be submitted to community voting and accepted if it is the most voted issue at the end of a month. We encourage you to rally support for your request.

Thank you,
Alan

**Comment by lprimak** [comment]
@JamesHillyard do you need me to make the PR for Payara 6 or will this be imported at some point ?

**Comment by JamesHillyard** [comment]
@lprimak No need to make the Payara 6 port, I have already ported over the changes and am testing now - I'll link the PR to this issue & the Payara 5 PR shortly
