### ISSUE TITLE
Bug Report:  EJB applications get stuck in "application is not yet initialized" state after a domain restart

### ISSUE THREAD

**Issue by BLXDEV** [payara/Payara#5610]
# Description #
----------

We are deploying complex applications on Payara 5.2021.10. The application binaries are EARs and include EJB, servlet and web modules. When shutting down and restarting the Payara domain, the applications fail to properly re-initialize. Accessing an application's web page results in the following message: "HTTP Status 500 - The application is not yet initialized". Applications get stuck in this state indefinitely.

## Expected Outcome ##

Restarting the domain should result in applications being reloaded and, after the deployment completes, the web pages should become available for browsing.

## Current Outcome ##

On Payara 5.2021.10 stopping and starting the domain results in applications' web pages returning "HTTP Status 500 - The application is not yet initialized" in perpetuity.

This may be related to module cache corruption on shutdown, because deleting osgi-cache, session-store and generated subfolders in the domain folder after domain shutdown seemingly fixes the issue and results in applications loading properly on the next startup.

## Steps to reproduce ## 

1. Deploy an application, which has an EJB and a web component
2. Verify that application's web pages load properly in the browser
3. Shut down the Payara domain with asadmin stop-domain
4. Restart the Payara domain with asadmin start-domain
5. Wait long enough for the server and deployed applications to finish initializing (2-3 minutes)
6. Access the application's web page. The browser will display "HTTP Status 500 - The application is not yet initialized" message. Attempting to access the same page at a later time (after minutes, hours, or days) results in the same outcome.

Per additional testing, the issue is also present in Payara 5.2021.9, but is not present in 5.2021.3

## Environment ##

- **Distribution**: Payara 5.2021.10 Full Profile
- **JDK Version**: JDK 11 (Zulu 11.48.21) or JDK 17 (Zulu 17.32.13)
- **Operating System**: Windows 10

**Comment by shub8968** [comment]
Hi @BLXDEV,

Can you provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it. If you are looking for running a mission-critical applications and want support, kindly consider using Payara Enterprise.

**Comment by shub8968** [comment]
Closing as reproducer is not available.
