### ISSUE TITLE
Bug Report: Stream closes abruptly over HTTP/2 protocol

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5612]
# Description #

Under heavy load, Payara CE 5.2021.8 abruptly closes some HTTP/2 streams.

## Expected Outcome ##

Payara will never abruptly close HTTP/2 streams. Client will consume all streams without problem.

## Current Outcome ##

Some streams stay open, some are getting closed. As a result, the consumer reports unexpected end of stream on some of the streams.

## Steps to reproduce ## 

Provide JAX-RS resource method simply returning arbitrary JSON files.

Let JAX-RS (or cURL, or Chrome, ...) client fire thousands of **parallel** GET requests on that resource method using several threads.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: Azul Zulu 11
- **Operating System**: Windows

**Comment by AlanRoth** [comment]
Hi @mkarg,

Thanks for raising a bug report. 

Can you test your reproducer on the latest Payara Platform 5.2021.10 release and can you attach your reproducer application to the issue so we can confirm the bug on our end?

Thanks,
Alan

**Comment by mkarg** [comment]
@AlanRoth Sure will do that in the next weeks.

**Comment by AlanRoth** [comment]
Hi @mkarg,

Any updates?

Thank you,
Alan

**Comment by mkarg** [comment]
Unfortunately this is really hard to reproduce! Running our complete application (huge EAR) the problem does happen sporadically, as soon as *Chrome or Edge* fires *real lots* of **interwoven** GETs (no problem with **sequential** GETs). It happens even if using huge numbers of threads or huge queue size. But as soon as using a simple Java SE based client, the software runs stable! So apparently Chrome and Edge do more agressive things than the new Java SE 11 HTTP Client framework. Within Chrome / Edge debug view we see that it does nothing particularly special. It simply starts hundreds of GETs at the same time, all running well, but just one of hundreds fails because the server closed the HTTP channel while that single one still waited for the response. Once we redo the same, it works well, until some fine day it happens again. So I assume that the HTTP server inside of Payara "forgot" to wait for that open request. Also, it does **not** fail when using HTTP/2 without TLS. Or in other words: **It fails only when TLS is enabled**. Sorry that I cannot tell you more. It is a showstopper for us, but it is impossible to write a reproducer. Until there is a solution, what we do is to disable HTTP/2 if TLS is in use. This slows down the overall application, but at least it works stable.

**Comment by AlanRoth** [comment]
Hi @mkarg,

I'm sorry to hear this is having such an impact on your application, however we're not able to move forward without being able to reproduce the issue you are facing, as at the moment we do not have enough information to create a fix.

Due to the nature of not being able to reproduce the issue, I will be closing it - however please don't hesitate to reopen the issue or create a new issue if you find any more information on how to reproduce the problem.

Ultimately, If you require a urgent investigation and fixes, I would recommend a Payara Enterprise license.

Thank you,
Alan
