### ISSUE TITLE
Enhancement: Support `asadmin create-service --serviceuser` option on Windows

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5613]
# Description #
----------

Running services as `root` (Linux) / `Local System` (Windows) implies a dramatic security risk.

For Linux, `asadin create-service` provides a `--serviceuser` option to remedy this risk.

The same option shall get enabled for Windows, too, effectively allowing use of a [Virtual Account](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts#bkmk-virtualserviceaccounts) (`NT SERVICE\<servicename>`) instead of `Local System`. Windows knows *virtual* accounts since Windows 7 / Windows 2008 R2; the operating system creates such account *on-the-fly simply by using it*, so there is no good reason to *not* support this security feature.

## Expected Outcome

`asadmin create-service --serviceuser <UID>` installs a Windows Service running as user `<UID>` when running on Windows. 

## Current Outcome

`asadmin create-service --serviceuser <UID>` prints the message `The serviceuser parameter is only supported on Linux.` when running on Windows.

## Alternatives

Subsequently reconfigure the created service using operating system service control commands, e. g. `sc config <servicename> obj= <UID>`.

## Context

N/A

**Comment by shub8968** [comment]
Hi @mkarg,

Thank you for submitting the enhancement request, it will be submitted to community voting and would be accepted if it is the most voted issue at the end of a month. We encourage you to rally support for your request. 

Kind Regards,
Shubham

**Comment by fturizo** [comment]
@mkarg,

It seems that after submitting this issue for community vote there was not a proper reception nor interest in the feature requested, so we'll proceed to close this issue due to lack of interest.
