### ISSUE TITLE
Bug Report: 5.2022.1 missing on maven central

### ISSUE THREAD

**Issue by Herr-Sepp** [payara/Payara#5617]
# Description #
----------

[https://mvnrepository.com/artifact/fish.payara.extras/payara-micro](https://mvnrepository.com/artifact/fish.payara.extras/payara-micro)
[https://mvnrepository.com/artifact/fish.payara.api/payara-bom](https://mvnrepository.com/artifact/fish.payara.api/payara-bom)
[https://mvnrepository.com/artifact/fish.payara.api/payara-api](https://mvnrepository.com/artifact/fish.payara.api/payara-api)

are missing the new 5.2022.1 Release.
Is there a new location now or is it just missing currently?

**Comment by AlanRoth** [comment]
Hi @Herr-Sepp,

Thank you for raising attention to the problem, I have informed the QA/CI team and they are working on resolving the issue.

The artefacts should be available at some point today.

Thank you,
Alan
