### ISSUE TITLE
Bug Report: Cannot start Windows Service with service account

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5620]
# Description #
----------

It is impossible to start Payara 5 as a Windows Service using a service account.

## Expected Outcome ##

Payara 5 should boot as a Windows Service using a service account.

## Current Outcome ##

Windows' service controller fails to start Payara 5 as a Windows Service. There is not even a reason told in the Windows event log.

## Steps to reproduce ## 

Unpack Payara 5 to `c:\payara5`.

Run `asadmin create-service`.

Execute `SC config domain1 obj= "NT SERVICE\domain1"` to use as service account instead of `LocalSystem`.

Execute `ICACLS c:\payara5 /SETOWNER "NT SERVICE\domain1" /T /L /Q` to set the owner of all Payara 5.

Execute `ICACLS c:\payara5 /RESET /T /L /Q` to replace explicit grants by implicit ownership.

Execute `NET START domain1`, then wait for the service to be started.

## Workaround ##

Start and stop the Service once initially (hence: as `LocalSystem`) *before* setting the account to `NT SERVICE\domain`.

## Environment ##

- **Distribution**: Full Profile
- **JDK Version**: 11 (Azul Zulu)
- **Operating System**: Windows

**Comment by mkarg** [comment]
I can reproduce this on both, Windows Server 2019 and Windows Server 2022.

I noticed that starting the service as `NT SERVICE\domain1` creates some files in a `c:\payara5` subfolder *not* having `domain1` as its owner, and not even having that account granted any access rights. Also I noticed that simply creating those files upfront does fix the problem. And last but not least, simply using an "already working" backup of the complete `c:\payara5` folder does *not* fix the problem, which proofs that the service wrapper apparently is creating *other* (non-file) resources elsewhere, too (I assume in the Windows Registry; and I assume in a registry path where only `LocalSystem` may do this).

**Comment by shub8968** [comment]
Hi @mkarg,

Payara server by design is not meant to start as windows services with a service account. Your enhancement request #5613 is successfully submitted to voting in this regard. If you want support on it we recommend you to consider Payara Enterprise.

Thanks,
Shubham

**Comment by mkarg** [comment]
Can you please elaborate on the intention behind this design choice? It implies a huge security risk.
