### ISSUE TITLE
Enhancement: Upgrade Jackson to 2.12.6 or 2.13.1

### ISSUE THREAD

**Issue by robelcik** [payara/Payara#5641]
# Description #

Upgrade Jackson to 2.12.6, as currently used version contains known (possible) DoS vulnerability.

## Expected Outcome

Jackson upgraded to the latest 2.12.x

## Current Outcome

Currently used Jackson contains a known possible DoS vulnerability:
https://github.com/FasterXML/jackson-databind/issues/3328
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698

In December, I reported it to security@payara.fish but I have not got any reply.
In February, I added related post to forum.payara.fish but I have not got any reply.
That's why I'm submitting a request here.

## Alternatives

Upgrade Jackson to the latest 2.13.x

**Comment by AlanRoth** [comment]
Hi @robelcik,

It appears we haven't received any emails for Jackson vulnerabilities to our security@payara.fish inbox in December, we apologise about that, we actively monitor and aim to investigate all security requests.

We are investigating the impact of the vulnerability that you have shared.

Thank you,
Alan

**Comment by AlanRoth** [comment]
Hi @robelcik,

The server itself should not be vulnerable as Jackson does not seem to be used to process any arbitrary user input - deployed applications may be affected.

I have raised `FISH-6067` to keep track of the resolution of this issue.

Thank you,
Alan

**Comment by robelcik** [comment]
Thank you, @AlanRoth!

**Comment by robelcik** [comment]
Hello.
There are new findings in that area, which suggest using 2.13.x rather than 2.12.x.
* https://github.com/FasterXML/jackson-databind/issues/2816
* https://github.com/FasterXML/jackson-databind/commit/50cb997188e532e2ef9ba229d8d6bf9c91be3bd0
* https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244

**Comment by AlvinYueChao** [comment]
`2.13.x` and `2.12.6` not work for the below issue
https://github.com/FasterXML/jackson-databind/issues/2816

**Comment by AlanRoth** [comment]
Hi @robelcik,

We have upgraded Jackson to 2.12.6, it will be available in the next Community and Enterprise releases.

Thank you,
Alan

**Comment by robelcik** [comment]
Thank you, guys!

@JamesHillyard: As for now, 2.13.2 is the latest greatest.
