### ISSUE TITLE
Bug Report:  enable-secure-admin failing on Payara6 (JDK17 bug?)

### ISSUE THREAD

**Issue by sjaenick** [payara/Payara#5651]
Hi,

just installed payara-6.2022.1.Alpha2 and successfully created a domain, but when 
trying to secure the server, the `enable-secure-admin` command didn't work as
expected:

```
asadmin> enable-secure-admin
Enter admin password for user "admin"> 
Command enable-secure-admin not found. 
Check the entry of command name. This command may be provided by a package that is not installed.
Closest matching local and remote command(s): 
    enable-secure-admin
    enable-secure-admin-internal-user
    enable-secure-admin-principal

Command enable-secure-admin failed.
```

Interestingly, the command is still listed in the error message.

JDK 17.0.2:

```
IMPLEMENTOR="Oracle Corporation"
JAVA_VERSION="17.0.2"
JAVA_VERSION_DATE="2022-01-18"
LIBC="gnu"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.foreign jdk.incubator.vector jdk.internal.le jdk.internal.opt jdk.internal.vm.ci jdk.internal.vm.compiler jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:300cb6175534 open:git:6f0f42630eac"
```

**Comment by sjaenick** [comment]
Errors in server.log:

[server.log](https://github.com/payara/Payara/files/8252693/server.log)

**Comment by sjaenick** [comment]
Works on jdk-11.0.13

**Comment by OndroMih** [comment]
This is caused by a problem in the Felix OSGi runtime, the underlying cause is:

```
java.lang.IllegalStateException: Unknown protocol: http
    at org.apache.felix.framework.URLHandlersStreamHandlerProxy.parseURL(URLHandlersStreamHandlerProxy.java:373)
    at java.base/java.net.URL.<init>(URL.java:703)
```
Payara 6 Alpha 2 uses Felix version 6.0.2 but it was already updated to 7.0.1 in the Payara6 branch: https://github.com/payara/Payara/blob/master/nucleus/pom.xml#L163. I tried with GlassFish 7 milestone, which already uses Felix 7 and it doesn't give the error, all works there. So I think this issue is already solved by upgrading Felix to 7.x

**Comment by sjaenick** [comment]
> Payara 6 Alpha 2 uses Felix version 6.0.2 but it was already updated to 7.0.1 in the Payara6 branch: https://github.com/payara/Payara/blob/master/nucleus/pom.xml#L163. I tried with GlassFish 7 milestone, which already uses Felix 7 and it doesn't give the error, all works there. So I think this issue is already solved by upgrading Felix to 7.x

Would it make sense to directly update Felix to 7.0.3, then?
