### ISSUE TITLE
Exception in asadmin web GUI after session timeout

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#5652]
It was reported by me some time ago and there was some improvement on that but there still are the erorrs when the session is timed out:
![image](https://user-images.githubusercontent.com/41665450/158398211-73df5d34-4012-42e3-aa4c-d71fe91c614c.png)
After ENTER in URL:
![image](https://user-images.githubusercontent.com/41665450/158398301-80de6d3d-8efa-40c3-a739-c06badec69c6.png)
ENTER and redirects propertly:
![image](https://user-images.githubusercontent.com/41665450/158398387-77d5cba2-755d-4934-a9cb-efd90c2b7ea7.png)

The old behaviour was that Payara was stuck on NPE and I had to remove cookie. Now it happens such way that 2x refreshes of the page resolves the issue.

Log:
[log.log](https://github.com/payara/Payara/files/8254148/log.log)

As I've wrote there was some issue on that some time ago which improved things a bit, but I'm not able to find it now (don't know why).

**Comment by MeroRai** [comment]
Hi, since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition at that point in time.
