### ISSUE TITLE
Bug Report: PROPFIND fails when TLS is enabled

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5670]
# Description #
----------

The verb `PROPFIND` (part of WebDAV) fails when TLS is enabled and Payara was rebooted since deployment of the EAR, but only if the EAR also contains a `@WebService`.

## Expected Outcome ##

There should not be any restriction on the accepted verbs, either with or without TLS, either with or without `@WebService` in the same EAR.

## Current Outcome ##

TLS disabled or no `@WebService` contained in the same EAR: `PROPFIND` verb is successfully propagated and processed by JAX-RS.

TLS enabled and `@WebService` contained in the same EAR: Payara blocks with 501 and the following explanation in the response entity:

```
...
Method PROPFIND is not defined in RFC 2068 and is not supported by the Servlet API 
...
```

## Steps to reproduce ## 

* Deploy an EAR containing a WAR containing a JAX-RS resource having `@PROPFIND @PATH("myresource")`  annotated method, where `@PROPFIND` is defined as a JAX-RS custom extension for the verb `"PROPFIND"`.
* Restart Payara Domain
* `curl -X PROPFIND https://localhost:8080/myresource`

## Workaround ##

* Redeploy the EAR after each reboot.

Strange but true, `PROPFIND` works even with TLS unless the reboot is performed.

## Environment ##

- **Distribution**: Server Full Profile 5.2022.1 (also confirmed to fail on 5.2021.9 and 5.2021.8 but not checked with other version)
- **JDK Version**: 11 - Azul
- **Operating System**: Windows

**Comment by mkarg** [comment]
This is really an urgent problem for us, as we like to ship Payara bugfixes ASAP. I would really appreciate if you could fix this! Thanks! :-)

**Comment by mkarg** [comment]
(and no, certainly it is not an option to switch off TLS)

**Comment by mkarg** [comment]
Tested 5.2021.9 - fails already, hence the bug was added between 5.2021.8 and 5.2021.9. Maybe this helps with searching?

**Comment by mkarg** [comment]
Would be great if anybody could comment on this whether there is a simple workaround we could apply until a real bugfix is published?

**Comment by mkarg** [comment]
Possibly related to https://github.com/payara/Payara/issues/5602.

**Comment by AlanRoth** [comment]
Hi @mkarg,

Can you attach a sample reproducer application for us to investigate?

Thank you,
Alan

**Comment by mkarg** [comment]
As a workaround we have remove the `@WebService` annotation, so while this is severe it is not urgent anymore. Hence I have planned to provide a reproducer in June.
