### ISSUE TITLE
Bug Report:  Canot launch Ear by java web start

### ISSUE THREAD

**Issue by ostermannBernd** [payara/Payara#5712]
# Description #
I have an enterprise application, which is deployed by Netbeans 13 to Payara 5.2022.1. I can run it from Netbeans and by app client. If  I tried to launch it from the admin console the app is not launched but a file x-app-client  is downloaded. This file is a jnlp file. If I start it by Javaws I got the following exception in the java web start console:
java.io.IOException: Cannot run program "C:\Program Files\Java\jre1.8.0_321\bin\jp2launcher.exe": CreateProcess error=206, Filename or extension are too long.

## Expected Outcome ##
The app should be launched or at least the cause of the exception should be issued, which gave concrete hints would was wrong.

## Current Outcome ##
The app is not launched; an exception was issued:
java.io.IOException: Cannot run program "C:\Program Files\Java\jre1.8.0_321\bin\jp2launcher.exe": CreateProcess error=206, Filename or extension are too long.

## Steps to reproduce ## 
Create an enterprise application with stateless bean with Netbeans 13. Deplloa to the payara server. In the admin console got to applications and select the just deploay application. Go to modules and components. Click the launch button. A file x-app-client will be downloaded.
Run the jnlp file by Javaws

## Environment ##

- **Distribution**:  Payare server 5.2022.1
- **JDK Version**: jdk1.8.0_311
- **Operating System**: Windows 10
[OopsWeb-app-client,txt](https://github.com/payara/Payara/files/8490993/OopsWeb-app-client.txt)

- **Netbeans Version**:  13

**Comment by fturizo** [comment]
@ostermannBernd, I'm afraid that we can't assist with this issue, as Java Web Start support is not covered by our Community support guidelines.  Java Web Start has been officially deprecated starting on Java 9 and is no longer part of the JDK so there's no point in us supporting it in any capacity. 

To keep using it on JDK 8 and Payara Server 5.x, I heavily recommend that you get a Payara Enterprise subscription to get you the assistance you need.
