### ISSUE TITLE
Enhancement: multi platform docker builds/FISH-7821

### ISSUE THREAD

**Issue by IvoNet** [payara/Payara#5715]
# Description #
----------

I am an avid user of the docker image payara/server-full and would love to have a native build for the aarch64 (linux/arm64/v8) architecture. 

## Expected Outcome

something like my own build where you can see amd64 and arm64 builds available
<img width="488" alt="image" src="https://user-images.githubusercontent.com/741238/164303503-cabdfe99-3b5e-4d35-9771-7dfa7e67ab81.png">

## Current Outcome

currently only amd64 builds are created which leads to emulation on an aarch64 computer and has a significant performance hit.

## Alternatives

I've created my own [image](https://hub.docker.com/r/ivonet/payara) but I would love to use the official version in one of my JakartaEE [archetypes](https://ivonet.github.io/archetype/). 

## Context

Creating a multi platform build is not all that hard and has the benefit of being native and therefore much faster. I've even created a small blog about it [here](https://www.ivonet.nl/2022/04/10/docker-multi-platform-build-with-buildx/) if that helps.

**Comment by lprimak** [comment]
Also, perhaps base it on Alpine Linux so the images are smaller?

**Comment by IvoNet** [comment]
Hmm, I do not know if I agree with the Alpine comment. When you have installed all you need the images will probably be not as different in size as you might think.

**Comment by shub8968** [comment]
Hi @IvoNet,

Thank you for the request, it will be submitted to community voting. I would be accepted if it is the most voted issue at the end of a month. 

Thanks

**Comment by lprimak** [comment]
> When you have installed all you need the images will probably be not as different in size as you might think.

@IvoNet isn't this the *definition* of over-engineering?
Would't your case be solved by layering a custom image? 
IMHO I would think so

**Comment by IvoNet** [comment]
> @IvoNet isn't this the _definition_ of over-engineering?
> Would't your case be solved by layering a custom image?
> IMHO I would think so

@lprimak I do not understand what you mean? Alpine is small but...

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/741238/165690675-dcdbae54-8b53-42ed-aaed-299ac5a9c54e.png">

If you want to install Payara on an Alpine it already needs to be an Alpine with Java installed, so the image is already about 180Mb larger.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/741238/165690362-7e140516-18cf-4dd0-845c-ae5b7111df62.png">

Then you need to install and configure Payara on it and it becomes even bigger with about 200Mb.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/741238/165692148-402bdcb7-2311-47ad-9390-1ddbbe4fd981.png">

At that point, you can do the math (3 + 180 + 200 = 383) and look at the image as created by Parara, and think .... hmm they have done a good job :-) while not using an Alpine base.

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/741238/165691726-511bab83-36aa-4432-9d43-3a2edb05f3e4.png">


It has nothing to do with over-engineering, but a decision of stability and what users use the most.

**Comment by IvoNet** [comment]
> Still think you can save ~100MB with Alpine

If you really want this issue. Please create your own issue and don't try to take over mine which in effect is a totally different request.

**Comment by phillipross** [comment]
I'll vote for any issues regarding official multiplatform images 😁

**Comment by marko-lazic** [comment]
Seems like docker-maven-plugin release [0.40.0 (2022-05-29)](https://github.com/fabric8io/docker-maven-plugin/releases/tag/v0.40.0): now supports 

- Multi-architecture images using buildx (https://github.com/fabric8io/docker-maven-plugin/issues/1502) @chonton

**Comment by pratikpparikh** [comment]
Can this be please introduced for payara docker images?

**Comment by MichaelVoelkel** [comment]
I think it's somewhat urgent? On macOS ARM you cannot even use this Docker image because FileWatcher will fail

**Comment by HoschiAndre** [comment]
I think it comes to end with Payara, the ARM Technologie is around for ~ 2 years now ... mmhhh ... How long will it take to update Jakarta 11 when it comes. Long boot up time, not much of dev tools. I thought Quarkus is just a hype, but I start to think differently. Sorry Payara.

**Comment by MichaelVoelkel** [comment]
To be honest, I'm just trying to get _any_ framework running with M1 at the moment using Docker and then hoping to publish at my K8s cluster, but no success so far (I was out of the Java game for quite some years).
I mean, apparently they voted it up this month, so that's nice. But it's true that ARM is not new and everyone working with a MBP has it, so that not working is no longer tolerable any longer for any tool out there in IT

**Comment by shub8968** [comment]
Hi @IvoNet,

It has been escalated to the Platform Development team with internal Jira as `FISH-7821`.

**Comment by mbmschares** [comment]
Can we get an update on this?

**Comment by lprimak** [comment]
FYI: I built a multi-platform Payara docker image here: https://hub.docker.com/repository/docker/lprimak/payara-full/general

**Comment by IvoNet** [comment]
> FYI: I built a multi-platform Payara docker image here: https://hub.docker.com/repository/docker/lprimak/payara-full/tags

That's nice but a bit of documentation to go along with it would be nice. I have one too but I want an official one :-)

**Comment by lprimak** [comment]
Build scripts for my images are here: https://github.com/lprimak/infra/tree/main/scripts/cloud/docker
