### ISSUE TITLE
Enhancement: Rebuild Patched EclipseLink w/ASM 9.3+

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#5716]
# Description #
----------
Relates to #5659
Fixed by https://github.com/payara/patched-src-eclipselink/pull/20

Tried running an app on Java 18 / 19 and Payara 2022.2 and it failed due to older ASM inside the patched EclipseLink.
It needs to be rebuilt with the latest asm to support Java 18 and 18

**Comment by shub8968** [comment]
Hi @lprimak,

Thank you for the request, it will be submitted to community voting. It would be accepted if it is the most voted issue at the end of a month. Also, you are free to submit the PR for the same.

Thanks,
Shubham

**Comment by marcreichman** [comment]
FWIW this also causes an issue trying to pull up the admin console on JDK 19-ea.

**Comment by lprimak** [comment]
This is fixed in the latest community head
