### ISSUE TITLE
Bug Report: Keeping MicroProfile properties on redeploy

### ISSUE THREAD

**Issue by dstango** [payara/Payara#5731]
Keeping MicroProfile properties on redeploy in Payara-Server full
----------
It looks like there's no way to keep application properties, especially MicroProfile properties, on redeploy. I tried to check the boxes “Keep state” and “Preserve Application Scoped Resources” in the redeploy form, but to no avail.
Actually I’m most interested in keeping the properties when redeploying from maven with the cargo-plugin.

I’m aware about the MicroProfile properties on the server level, but as this server is used by different applications that might use the same property-names, I’m not too happy to define them there.

## Expected Outcome

Redeploy an already deployed application and keep the state of the application MicroProfile properties. This could be enabled by a special option in the redeploy dialog.
The same option should be available for asadmin and the cargo plugin.

## Current Outcome

Redeploying an application deletes all previously defined MicroProfile properties.

## Alternatives

If keeping the old property values is not feasible it could be an alternative to make asadmin/cargo capable of setting MicroProfile-properites explicitly on (re)deploy.

## Context

This request in our context is for applications that is running on a full "traditional" payara server, in preparation to later probably transition towards docker-based payara instances that then can be configured via environment properties etc. But until then (it will take some time) redeployment is taking more manual effort than I'd like to have.

**Comment by JamesHillyard** [comment]
Hi @dstango,

I have been able to successfully reproduce this issue using asadmin on Payara Server 5.2022.2, and this actually looks like a bug.

Please, can you provide a simple to follow scenario how to reproduce this using maven-cargo-plugin on the latest release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by dstango** [comment]
Hi @JamesHillyard,

thanks for confirming the issue!

I would like to provide an SSCCE-example, yet I don't know what the expected outcome should be -- would you say keeping the MicroProfile properties should be default behavior for any redeploy, or only if some (not-yet-existing) flag were set?

**Comment by JamesHillyard** [comment]
Hi @dstango,

I think it would be best if a not-yet-existing flag were set to keep the MicroProfile properties on redeploy

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @dstango,

Have you been able to put together a short, simple to follow scenario using maven-cargo-plugin so I can verify and reproduce this issue?

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @dstango,

Since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition at that point in time. If you are able to reproduce it, please include a full easy to follow reproducer.

Thanks,
James

**Comment by dstango** [comment]
Hi James, 
sorry, I was on vacation. Will see to provide something soon. 
Thanks, 
Dirk
