### ISSUE TITLE
Bug Report:  Race condition within deployment prevents successful deployment

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#5775]
# Description #
----------
In a rare (1/20) case, on multi-core Mac M1 (Arch64)  deployment fails
Unfortunately this error doesn't produce an exception which makes it even harder to trace:

Log:
```
[2022-03-09T11:06:35.957-0600] [Payara 5.2022.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=122 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1646845595957] [levelValue: 1000] [[
  File source doesn't exist]]
```

Traced to this line, which is the exception origination, but not necessarily the true cause of the bug:
https://github.com/payara/Payara/blob/cbd34c8084073a862b7e36607d3cc27878b30cc2/nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java#L942

## Expected Outcome ##
App deploys every time

## Current Outcome ##
App deploys successfully 19/20th of the time

## Steps to reproduce ## 
Hard to reproduce. Currently happens in a CI system where more than one run occurs simultaneously.

Suggested first steps: 
- Add the file name that's missing to the log.
- Print out the exception rather that one-line log

## Environment ##

- **Distribution**: Full
- **JDK Version**: Zulu 17.0.3
- **Operating System**: Mac M1 Arch64 16-core

**Comment by lprimak** [comment]
Any applications will do, and yes only on M1 machine.
However, that was only 16-core machine I have access to so it's probably not CPU-specific

**Comment by JamesHillyard** [comment]
Hi @lprimak,

Due to the fact this bug isn't able to be consistently reproduced, and unfortunately at this time we do not have the resources to test or reproduce bugs on Apple M1 hardware, we will not be able to review or fix this bug. 

If there is a large desire from the community to have Apple M1 hardware support on Payara we may re-review this. Alternatively if you wish you can submit a PR with a fix!

Thanks,
James

**Comment by lprimak** [comment]
Please reopen this. I’ll fix it in due time.

**Comment by lprimak** [comment]
was able to consistently reproduce with 10 parallel Jenkins runners on the same CPU

**Comment by lprimak** [comment]
Turned out that the issue was that multiple instances of Payara would share the temp directory and would trample each other in tests.
Setting temp directory to a unique location fixed the problem
