### ISSUE TITLE
Bug Report:  Payara Hazelcast EncryptionReplacer.java Inline Comments in hazelcast-config.xml

### ISSUE THREAD

**Issue by sabediniaol** [payara/Payara#5813]
# Description #
----------

Load the example <config-replacers> EncryptionReplacer snippet
you can find that here: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.xml

Above that node you will see

Format of a variable is:
        $ PREFIX { STRING_TO_BE_REPLACED }      e.g. $ENC{nnPgTqJCcCQ=:23000:B4y/nlp6M0t3q6YiKImW+w==}

Payara 5.39.0 Attempts to decrypt $ENC{nnPgTqJCcCQ=:23000:B4y/nlp6M0t3q6YiKImW+w==}

Throws the following exception:
Unable to decrypt variable nnPgTqJCcCQ=:23000:B4y/nlp6M0t3q6YiKImW+w==
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

## Expected Outcome ##

Comments in the hazelcast-config.xml shouldn't be parsed

## Workaround

Delete e.g. $ENC{nnPgTqJCcCQ=:23000:B4y/nlp6M0t3q6YiKImW+w==} from the xml comment section

## Environment ##

- **Distribution**: 5.39.0 Server Enterprise
- **JDK Version**: Java 8 (OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-macosx) (build 1.8.0_282-b08))
- **Operating System**:  MAC 12.2.1

**Comment by shub8968** [comment]
Hi @sabediniaol,

Can you provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by fturizo** [comment]
Closing this issue as we had no response from the user.
