### ISSUE TITLE
Bug Report:  Payara 5.2022.2 Can not deploy modules to context-root "/"

### ISSUE THREAD

**Issue by KoalatyCode** [payara/Payara#5848]
# Description #
Hello, here is the environment (env1) I am running that does NOT work: 
Payara 5.2022.2
Windows Server 2019 Enterprise LTSC
Apache Netbeans 14
JDK 17

here is the environment (env2) I am running that DOES work: 
Payara 5.2022.2
Windows 10 Enterprise 2016 LTSB
Apache Netbeans 14
JDK 17

----------

On env1 I have brand new installs of everything, including windows. When I try to deploy my web application though Netbeans it does not deploy. On env2 I have the same new setup, but I have had previous versions of glassfish server (4.1.1) and netbeans 8.1 installed.

## Expected Outcome ##

The expected outcome is that the module deploys to the Payara server on context path "/"

Working server: 
![image](https://user-images.githubusercontent.com/19292765/179014844-4e7afb9e-480c-4f9d-8a2f-fea90c2e8692.png)
![image](https://user-images.githubusercontent.com/19292765/179015343-da8ab6f2-0a82-4295-9205-d48d5e84c671.png)

## Current Outcome ##

The current outcome is that the server can not deploy the module giving an error: 
SEVERE:   Exception while loading the app : java.lang.Exception: Virtual server __asadmin already has a web module __admingui loaded at / therefore web module (module_name) cannot be loaded at this context path on this virtual server
 ![image](https://user-images.githubusercontent.com/19292765/179014910-6c7e4a2a-7842-490c-be7a-f84c64471e46.png)
![Capture1](https://user-images.githubusercontent.com/19292765/179014718-7ed4cf40-9e8b-4fb8-8066-531ace583640.PNG)

## Environment ##

- **Distribution**: Payara 5.2022.2 
- **JDK Version**: DK 17
- **Operating System**:  Windows Server 2019 LTSC

**Comment by JamesHillyard** [comment]
Hi @KoalatyCode,

Could you please share the sample application you are using here or a small reproducer so I can investigate this further. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to investigate this issue.

Thanks,
James

**Comment by KoalatyCode** [comment]
The issue was caused by data tables including its own jquery in a js source. Thanks!
