### ISSUE TITLE
Payara Micro can't be stopped and restarted in the same process

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#588]
Bootstrapping Payara Micro, stopping it then boot strapping it again results in 
```java
java.lang.IllegalStateException: Payara Micro is already running, calling bootstrap now is meaningless
```

**Comment by abhirockzz** [comment]
There are 2 scenarios here

1. Invoking PayaraMicro.getInstance().shutdown() - this would give you a BootstrapException with a ‘Already bootstrapped’ message. The actual source is the following - https://github.com/payara/Payara/blob/8a403bf75d3734e564a9fb95d60498987cc4287e/nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishRuntime.java

Upon further examination, I found the that calling Glassfish.dispose (from shutdown method in PayaraMicroRuntime does not suffice). Calling GlassFishRuntime.shutdown() internally calls dispose on the GlassFish instance. Currently, the instance of  GlassFishRuntime is encapsulated within the PayaraMicro class and is not available to PayaraMicroRuntime which hinders a clean shutdown. 

2. Calling a shutdown on PayaraMicroRuntime instance which is obtained using PayaraMicro.getInstance().bootStrap() [This prompts the exception which Stevel mentioned]

The GlassFish instance (‘runtime’ variable in the PayaraMicro) needs to be set to null after the completion of shutdown method. This will clear the exception mentioned in the issue

**Comment by smillidge** [comment]
Thanks abhi for the analysis. Do you fancy putting together a pull request ;-)

**Comment by abhirockzz** [comment]
Sure. Let me try and look into this further

**Comment by smillidge** [comment]
Thanks that would be awesome. You will need to sign a CLA though see https://github.com/payara/Payara/blob/master/Contributing.md
