### ISSUE TITLE
Bug Report: create-password-alias --passwordfile includes trailing whitespace

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5887]
# Description #
----------

In case the used password file contains trailing whitespace, it is getting included as part of the password value.

This is rather unexpected and not documented anywhere.

## Expected Outcome ##

Any trailing whitespace is expected to be excluded from the password value.

## Current Outcome ##

Any trailing whitespace is included in the password value.

## Steps to reproduce ## 

```bash
echo "AS_ADMIN_ALIASPASSWORD=foo   " > x
asadmin create-password-alias --passwordfile x Y
```

Let an arbitrary component consume a custom property set to `${ALIAS=Y}` and print the length of the value into the log.

The expected result is 3, but it will be 6.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: 11 - Zulu
- **Operating System**: Any

**Comment by JamesHillyard** [comment]
Hi @mkarg,

This behaviour is consistent throughout Payara's password aliases feature, and not exclusive to using a password file. After discussing this with the development team, we agreed as a space is a valid password character we won't change how this feature works internally.

You rightly said this is not documented anywhere, so I have raised an internal issue to document this behaviour.

We hope that you understand,

Best Regards,
James

**Comment by mkarg** [comment]
Just to be sure you understood the problem: We talk about *trailing* space here. You guys *really* think a blank at the *end* of a password should be a valid character? The problem you open with this decision is: ON Windows, the `ECHO` command *automatically* adds whitespace at the end, so you will *always* have an **unintentional** whitepspace in your password. This is very annoying. Effectively, you cannot create whitespace-less password files in Windows.
