### ISSUE TITLE
Bug Report:  Missing dependency in payara-api / FISH-6510

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#5920]
# Description #
----------

A few days ago we switched from Payara 5.2021.10 to 5.2022.3.

Since we use OpenIdConnect, we imported the payara api. Unfortunately, this has apparently not been the same since version 5.2022.1.

The @OpenIdAuthenticationDefinition annotation and the OpenIdContext class no longer exist in the API.

It looks like at least the security-connectors-api dependency is missing.

Unfortunately, since I can't find any information in the documentation as to whether something has changed and what to use instead, I assume that there is an error in the API or that the documentation has not been adjusted.

Can you please check if the documentation needs to be adjusted or the API needs to be improved?

## Expected Outcome ##

Information in the documentation about what should be used instead or the Payara API provides all required dependencies again

## Current Outcome ##

The @OpenIdAuthenticationDefinition annotation and the OpenIdContext class no longer exist in the API.
Hence compile errors in the classes that use the OpenIdAuthenticationDefinition annotation and the OpenIdContext class

## Environment ##

- **Distribution**: Server Full Profile / Server Web Profile / Micro / Embedded
- **JDK Version**: 11
- **Operating System**: Linux

**Comment by pioneer2k** [comment]
this one can be used for that

			<dependency>
				<groupId>fish.payara.security.connectors</groupId>
				<artifactId>security-connector-oidc-client</artifactId>
				<version>2.4.0</version>
			</dependency>

**Comment by JamesHillyard** [comment]
Hi @LarsBrenker,

Thank you for raising this issue, I have been able to reproduce this using the latest version of the Payara-API. We have raised the internal issue `FISH-6510` to resolve this immediately. Please note this issue will not be present in the release notes, instead a member of the Payara team will update you when this issue has been resolved.

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @LarsBrenker,

This issue has been resolved and the 5.2022.4 version of the Payara API will be correct. In the meantime I recommend you  include the security connectors as an extra dependency, as suggested by @pioneer2k. 

As a reminder Payara Community is focused on innovation and breaking changes such as these do occur, if you require stability for a critical environment, I would strongly recommend a Payara Enterprise subscription.

Best Regards,
James
