### ISSUE TITLE
Bug Report:  Memory leak in JavaEETransactionManagerSimplified

### ISSUE THREAD

**Issue by krzysztof-osiecki** [payara/Payara#5938]
# Description #

I know its not a Payara class however it seems to me like its affecting payara, and have best hopes to get support here :)

We have an app that runs on Payara and has a bunch of scheduled quartz jobs running. After 25 days of continous running we've noticed that the app consumes 95% of heap so we took a heap dump and after analyzing it it shows that its queue in SheduledThreadPoolExecutor that is retaining bilions (116 bilions in our case) RunnabeScheduledFutures.
After further search we've discovered that said executor is scheduledTransactionManagerExecutor from JavaEETransactionManagerSimplified.

Executor does not have the property to remove on cancel set, instead there is a code in the constructor to set future to remove canceled tasks after certain ammount of cancelation:
```
    public JavaEETransactionManagerSimplified() {
        transactions = new ThreadLocal<>();
        localCallCounter = new ThreadLocal<>();
        delegates = new ThreadLocal<>();
        scheduledTransactionManagerExecutor = new ScheduledThreadPoolExecutor(
            Math.min(Runtime.getRuntime().availableProcessors(), 3)
        );
        if (getPurgeCancelledTtransactionsAfter() > 0) {
            purgeScheduledTransactionsFuture = scheduledTransactionManagerExecutor.scheduleAtFixedRate(
                    this::purgeCancelledTransactionTimeouts, 5, 5, TimeUnit.SECONDS
            );
        }
    }```
We have this property set in our domain.xml like so 
```
       <transaction-service automatic-recovery="true" tx-log-dir="${com.sun.aas.instanceRoot}/logs" timeout-in-seconds="300">
        <property name="xaresource-txn-timeout" value="300"></property>
        <property name="purge-cancelled-transactions-after" value="500"></property>
      </transaction-service> ```

> 

hovewer when the constructor is called this property is equal to 0, which makes sense for it is not set anywhere before, so the future is not created. The property is read properly with our value 500 in initProperties() method with 
```
                 String v = txnService.getPropertyValue("purge-cancelled-transactions-after");
                if (v != null && v.length() > 0) {
                    purgeCancelledTtransactions = Integer.parseInt(v);
                }
```
however the future is not created there after reading that, so the cleanup is non existant. Cancelled task pille up over time.

I'm not sure if it is something on our end with our config, however looking at the class i dont see how it is ever supposed to work. The property read in constructor is not set before and only chance for it to work is with a custom manager that overrides it.
Should we do that and write our own manager or is there something we should configure in domain.xml to use different manager?

## Expected Outcome ##

Cleaning cancelled tasks

## Current Outcome ##

Not cleaning cancelled tasks

## Steps to reproduce ## 

i hope are clear in the description

## Environment ##

- **Distribution**: Payara Community 5.2022.3
- **JDK Version**: azul 11.0.14.1
- **Operating System**: Windows 10

**Comment by JamesHillyard** [comment]
Hi @krzysztof-osiecki,

Thank you for raising this issue, although it would appear there is no bug in Payara specifically here. In that case I would recommend you opening a discussion on the Payara Forum: https://forum.payara.fish/ where myself and other community members can discuss this issue with you. 

If I'm mistaken, could you please provide a full reproducer application, a reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. This will greatly help us to offer you better support with this issue.

Thanks,
James

**Comment by krzysztof-osiecki** [comment]
Hi @JamesHillyard Yes i'd say you are correct, i've created account however i cannot post for now. Recived message that my account requires review by a staff member, as soon as it will happen i will open this as a discussion.

**Comment by JamesHillyard** [comment]
Hi @krzysztof-osiecki,

Thank you for getting back to me promptly, it's much appreciated. I will send a message internally for this to be done ASAP for you!

Thanks,
James

**Comment by krzysztof-osiecki** [comment]
@JamesHillyard it was really quick thank, but just after attempting to post i was suspended again, seems my behavior looks bot-like :P i guess it will be resolved in time :)

**Comment by krzysztof-osiecki** [comment]
@JamesHillyard it's done, thx! Link to the discussion in case anyone interested stumbles upon this https://forum.payara.fish/t/memory-leak-in-javaee-transaction-manager-simplified/449

**Comment by JamesHillyard** [comment]
Thank you for raising this on the forums with more details, it's much appreciated. I'm also glad to hear you were able to access the forums successfully. I will proceed to close this issue now and continue this discussion on the Payara Forums.

Thanks,
James
