### ISSUE TITLE
Eclipselink with OracleChangeNotificationListener throws  java.lang.ClassNotFoundException: oracle.jdbc.dcn.DatabaseChangeListener

### ISSUE THREAD

**Issue by luisdanielmesa** [payara/Payara#5981]
### Brief Summary

When using the property ``eclipselink.cache.database-event-listener`` in ``persistence.xml`` set to ``org.eclipse.persistence.platform.database.oracle.dcn.OracleChangeNotificationListener`` or to ``DCN`` server startup fails with an exception ``java.lang.ClassNotFoundException: oracle.jdbc.dcn.DatabaseChangeListener``.

`Caused by: java.lang.ClassNotFoundException: oracle.jdbc.dcn.DatabaseChangeListener
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1212)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1606)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1522)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 59 more`

**Removing** the property allows the app to start normally.

I'm using Oracle 19.3.0 SE2 in a docker container locally as a test environment.
Oracle JDK 11.0.8
Payara 5.2022.3
persistence.xml
``<persistence version="2.2" ...``

I'm evaluating Payara Server Full with the hopes of being able to deploy using Payara Micro in a Kubernetes cluster afterwards.

### Expected Outcome

I would expect the server to start without an  exception.

[eclipse-ee4j/eclipselink persistence.xml example](https://github.com/eclipse-ee4j/eclipselink/blob/31abc3c8d559cf3ae0c8ba29231871d4910fd140/jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.dcn/src/main/resources/META-INF/persistence.xml)

[eclipse-ee4j/eclipselink](https://github.com/eclipse-ee4j/eclipselink/tree/31abc3c8d559cf3ae0c8ba29231871d4910fd140/jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.dcn)

### Current Outcome

![image](https://user-images.githubusercontent.com/1198204/195980982-e2a92d85-9186-4c0d-bdb9-ade78b5025c0.png)

### Reproducer

1. Create a simple project that uses EclipseLink JPA in conjunction with an Oracle database
2. Here's a [list of autogenerated projects](https://github.com/search?l=Java&q=AbstractFacade&type=Code)
3. Add the above-mentioned property to the ``persistence.xml``
4. Deploy to Payara Server Full 5.2022.3 (I'm testing in full locally, to try to use Micro in a Kubernetes cluster in the final deployment)
[Tried many examples](https://github.com/search?q=eclipselink.cache.database-event-listener&type=code)

### Operating System

Windows 10 Pro

### JDK Version

Oracle JDK 11.0.8

### Payara Distribution

Payara Server Full Profile

**Comment by luisdanielmesa** [comment]
If I'm missing something or made a mistake somewhere, you can point me to a working example of the usage of this property within the context of Payara's repackaged Eclipselink (2.7.9.payara-p2) and close the issue. Thanks!

**Comment by felixif** [comment]
Hi [luisdanielmesa](https://github.com/luisdanielmesa),

I created this sample application on the same environment as described in your issue, in order to try to reproduce the errors that you encountered. I was able to persist the object in the database with no issues and no errors/warnings from Payara Server. 

I attached in this message a .zip archive with my project, please let me know if it works for you.

[oracle-demo.zip](https://github.com/payara/Payara/files/9838137/oracle-demo.zip)

**Comment by luisdanielmesa** [comment]
Hi, thanks for taking the time to make the demo. Unfortunately I'm using EclipseLink as stated in the title. I have created a small project to reproduce.

1. Check the code and compile it
2. Deploy it into Payara.
3. Hit [the employee endpoint](http://localhost:8080/resources/employee)
4. Check it works
5. Edit persistence.xml and uncomment the ```eclipselink.cache.database-event-listener``` line.
6. Go to step 1
[oracle-change-notification.zip](https://github.com/payara/Payara/files/9842422/oracle-change-notification.zip)

**Comment by felixif** [comment]
Hi @luisdanielmesa,

Thank you very much for reporting this issue, I was able to reproduce it using your project. I have raised a Jira issue with the internal id `FISH-6653`. We always encourage you to contribute, so if you feel confident to do you please raise a PR and a member of the development team will gladly review the changes. If not, we will pick this issue up in the future.

Thanks,
Felix

**Comment by smillidge** [comment]
Have you added the Oracle JDBC driver containing  oracle.jdbc.dcn.DatabaseChangeListener to you server classpath?

**Comment by luisdanielmesa** [comment]
Hi, I have it inside my packaged app. I also tried placing it in several locations as per: [this post](https://groups.google.com/g/payara-forum/c/U9YvqQBXtMM) but it seems in neither of the locations it got picked up... 

I did not try the `add-library` command because I'm not very familiar with it and wanted to have all non-provided dependencies inside my packaged application. I'm testing multiple servers and I tried to make it as portable as I could to ease my testing.

I also tried your answer to [this question](https://stackoverflow.com/questions/32899120/how-do-i-add-jdbc-drivers-and-configure-jdbc-resources-in-payara-micro) but the examples you linked are not accessible and then I didn't try the other answers when I got a little discouraged.

**Comment by luisdanielmesa** [comment]
I've been digging and I've gotten as far as checking [osgi.properties](https://github.com/payara/Payara/blob/9ccc6c47f2e1fa67841612f9235fc8b2c78ca30a/nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties#L102)
Which location(s) are supposed to be supported to place the ojdbc driver? I just want to test in different locations, but I don't want to try randomly.

**Comment by luismesa-io** [comment]
Is there any update on this? Is there a way I can help?

**Comment by lprimak** [comment]
Have you seen / implemented this: https://docs.payara.fish/community/docs/documentation/payara-server/classloading.html

You would need to do both payara-web.xml with delegate set to false *and* the system property to turn it off globally

**Comment by luismesa-io** [comment]
Hi @lprimak thank you for the answer. I thought I was adding a library that Payara didn't contain. Can you explain why turning off class-loading delegation solves this issue? Maybe I'm missing something. Thank you again.

**Comment by lprimak** [comment]
Does it work? The article has all the answers that I have :) I think EclipseLink includes some oracle stuff so it clashes unless you turn off delegation

**Comment by luismesa-io** [comment]
I haven't been able to make it work, BUT I was able to find this, which implies this whole thing cannot be done since oracle/jdbc/dcn is Sealed: 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/122157274/219054127-acda0f9c-4118-43d3-bdb2-496cad4b5342.png">

**Comment by luismesa-io** [comment]
I tried adding: 
```XML
<class-loader delegate="false"/>
```
but I still get the ```java.lang.NoClassDefFoundError: oracle/jdbc/dcn/DatabaseChangeListener``` error.

**Comment by lprimak** [comment]
Did you also include the system property `fish.payara.classloading.delegate` to false? You need to do both

**Comment by luismesa-io** [comment]
I just tried that, but I still get the error, don't worry and thanks for the help, I'll just use Debezium and get the change capture that way... I still think I was on the right track checking [this](https://github.com/payara/Payara/blob/9ccc6c47f2e1fa67841612f9235fc8b2c78ca30a/nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties#L102)
<img width="611" alt="Screenshot 2023-02-16 211054" src="https://user-images.githubusercontent.com/122157274/219476612-5ae953a3-ea91-4b44-9f96-c4ad7d0f2a25.png">
<img width="1075" alt="Screenshot 2023-02-16 211128" src="https://user-images.githubusercontent.com/122157274/219476691-0e61996d-c8a5-4490-9156-48f03f116992.png">
<img width="537" alt="Screenshot 2023-02-16 211008" src="https://user-images.githubusercontent.com/122157274/219476752-e6a755d6-a51d-4ecf-b86d-5da23fc4a5cf.png">

**Comment by lprimak** [comment]
Did you put your JDBC driver into <domain>/lib directory? And make sure it's not anywhere else in your project as a dependency? If it is, it will "block" the right classes from loading.

**Comment by luisdanielmesa** [comment]
I was wondering if anyone had found a way to make this work. I couldn't. Seems the classloading is a bit sketchy now, because you might also need to delegate the classloading for other libraries. It happened to me recently when using Jackson. It wouldn't work if I had delegate=false
