### ISSUE TITLE
Bug Report: Unable to start instance on JDK 11.0.16 and higher

### ISSUE THREAD

**Issue by mirozitnansky** [payara/Payara#5987]
### Brief Summary

Domain server fails to synchronize application to local instance since specific zulu 11 version. Instance is not started after error message.

Payara 5.2022.3, domain1 configuration, default-config copy local instance created.
Specific Java 11 version configured by modifing \glassfish\config\asenv.bat by line
`set AS_JAVA=c:\Program Files\Zulu\zulu11.56.19-ca-jdk11.0.15-win_x64\`

### Expected Outcome

When domain server is started with jdk zulu11.56.19-ca-jdk11.0.15-win_x64,  command to start-instance with already deployed application works fine
```
 .\asadmin.bat start-instance --sync full inst1
Removing all cached state for instance inst1.
Attempting to start inst1.... Please look at the server log for more details.....
The instance, inst1, was started on host localhost
Command start-instance executed successfully.
```
Last message in domain server.log states
`[2022-10-19T18:00:13.144+0200] [Payara 5.2022.3] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=134 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1666195213144] [levelValue: 800] [[
  Removing all cached state for instance inst1.
Attempting to start inst1.... Please look at the server log for more details.....]]`

[server-zulu11.56.19.log](https://github.com/payara/Payara/files/9822422/server-zulu11.56.19.log)

### Current Outcome

When domain server is reconfigured to version zulu11.58.15-ca-jdk11.0.16-win_x64, or any newer version for that matter,  command to start instance with deployed application fails with _Null pointer exception_
```
.\asadmin.bat start-instance --sync full inst1
remote failure: Could not start instance inst1 on node localhost-domain1 (localhost).

Command failed on node localhost-domain1 (localhost): Removing all cached state for instance inst1.
Command start-local-instance failed.

CLI802 Synchronization failed for directory applications, caused by:
  java.lang.NullPointerException

To complete this operation run the following command locally on host localhost from the Payara Server install location C:\payara\2022.3:

 lib/nadmin  start-local-instance --node localhost-domain1 --sync full --timeout 120 inst1
Command start-instance failed.
```
Domain server.log states nothing more than console output.
`[2022-10-19T18:31:25.111+0200] [Payara 5.2022.3] [INFO] [] [] [tid: _ThreadID=167 _ThreadName=stderr] [timeMillis: 1666197085111] [levelValue: 800] [[
    java.lang.NullPointerException]]`
[server-zulu11.58.15.log](https://github.com/payara/Payara/files/9822457/server-zulu11.58.15.log)

How should we configure logger to get more details from domain server?

### Reproducer

Only way to reproduce this, would by to provide you with specific WAR file. But that WAR work just fine with older jdk.
Also WAR works fine when is deployed first time to instance.
Problem occurs only on starting instance when domain does synchronization activities. To me it seem to be a bug domain app which is triggered with "newer" jdk.

### Operating System

Windows 10, Windows Server 2016, Centos 7

### JDK Version

zulu11.58.15-ca-jdk11.0.16

### Payara Distribution

Payara Server Full Profile

**Comment by kalinchan** [comment]
I believe this is the same issue raised by a customer already (FISH-6566) - if I am correct, I have already fixed this issue [here](https://github.com/payara/Payara/pull/5986) and the fix will be in the next version of Payara Community.

**Comment by JamesHillyard** [comment]
> I believe this is the same issue raised by a customer already (FISH-6566) - if I am correct, I have already fixed this issue [here](https://github.com/payara/Payara/pull/5986) and the fix will be in the next version of Payara Community.

This is very possible, @mirozitnansky could you please confirm if the application you are deploying contains a JSON file? The internal issue, FISH-6566, which my colleague has referenced addresses a NullPointerException when starting an instance with an application deployed which contains a JSON file.

Best Regards,
James

**Comment by mirozitnansky** [comment]
After removal of json schemas (which are json files) from WAR, deployment works as expected even on latest zulu11.60.19.

**Comment by felixif** [comment]
Hi mirozitnansky,

Thank you for reporting the issue. The bug will be fixed in the next Payara release.
