### ISSUE TITLE
[Payara 5.191] [GRAVE] [] [org.glassfish.admingui] [tid: _ThreadID=166 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1666207080544] [levelValue: 1000] [[   RestResponse.getResponse() gives FAILURE.  endpoint = 'https://localhost:4848/management/domain/resources/ping-connection-pool.json';

### ISSUE THREAD

**Issue by EloyFl** [payara/Payara#5988]
### Brief Summary

[Payara 5.191] [GRAVE] [] [org.glassfish.admingui] [tid: _ThreadID=166 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1666207080544] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'https://localhost:4848/management/domain/resources/ping-connection-pool.json';

### Expected Outcome

[Payara 5.191] [GRAVE] [] [org.glassfish.admingui] [tid: _ThreadID=166 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1666207080544] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'https://localhost:4848/management/domain/resources/ping-connection-pool.json';

### Current Outcome

[Payara 5.191] [GRAVE] [] [org.glassfish.admingui] [tid: _ThreadID=166 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1666207080544] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'https://localhost:4848/management/domain/resources/ping-connection-pool.json';

### Reproducer

PING JDBC

### Operating System

Centos 7

### JDK Version

JDK 1.8

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @EloyFl 

Can you please test your issue on the latest version of Payara Community edition 5.2022.3 and confirm if this error still occurs?

Thank you,
Elif

**Comment by fturizo** [comment]
We'll proceed to close this issue due to inactivity.
