### ISSUE TITLE
Bug Report: https/2 active but not working on full 5.2022.3 / OpenJDK 17.0.2 (build 17.0.2+8)

### ISSUE THREAD

**Issue by james16694** [payara/Payara#6012]
### Brief Summary

Hi, we have http/2 enabled but when we check loading via Chrome + other 3rd parties they all say http/2 isn't available. We have http/2 + http/2 push enabled, and we are using SNI.

          <protocol name="http-listener-2" security-enabled="true">
            <http xpowered-by="false" compressable-mime-type="text/html,text/xml,text/plain,application/json" max-connections="250" http2-push-enabled="true" default-virtual-server="server" compression="on">
              <file-cache max-age-seconds="180" enabled="true"></file-cache>
            </http>
            <ssl sni-enabled="true" classname="com.sun.enterprise.security.ssl.GlassfishSSLImpl" cert-nickname="s1as"></ssl>
          </protocol>

Please let us know if you need any further information. We aren't tied to using OpenJDK 17 we upgraded from 8 due to the known page loading issue but we have been asked to enable http/2. We also tried 11 but sometimes were seeing semi-page loads. If there is a more suitable version combination we can try that no problem.

Thanks

### Expected Outcome

Pages sent via http/2.

### Current Outcome

Pages sent via http/1 with http/2 not available.

### Reproducer

https://www.apd.co.uk

On calling the URL resources are being send using http/1.

### Operating System

Centos 7.9.2009

### JDK Version

OpenJDK 17.0.2 (build 17.0.2+8) (java.net)

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi James,

If you think it is a bug then kindly provide us with a sample reproducer. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. If you are looking for support or running mission critical system then kindly consider [Payara Enterprise](https://www.payara.fish/enterprise/).

**Comment by james16694** [comment]
Hi Shubham,

We think it’s a bug but we don’t understand your guidelines so you can close the ticket – someone else that does can re raise the issue.

Thanks,

James
