### ISSUE TITLE
Bug Report: Payara Micro 5.2022.4 starts with corrupt ipv6-like host address and fails

### ISSUE THREAD

**Issue by pioneer2k** [payara/Payara#6016]
### Brief Summary

We are running Payara Micro 5.2022.4 on Ubuntu 20.04.5 (on GitHub Actions Runners) and when it starts it prints out a weird host-address and fails to start:
"Instance Configuration": {
        "Host": "fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4",
INFO: Payara Micro running on host: fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4 port: 8080

Payara Micro URLs:
http://[fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4]:8080/test

When running under Windows everything is working fine.
When running on all previous Payara Versions everything is working fine.

### Expected Outcome

Payara should start on a valid host name or IP address like:

    "Instance Configuration": {
        "Host": "fv-az369-388.1aditw1bi5nuhloczxc0ixisfg.gx.internal.cloudapp.net",
        
        Payara Micro URLs:
http://fv-az369-388.1aditw1bi5nuhloczxc0ixisfg.gx.internal.cloudapp.net:8080/test

### Current Outcome

"Instance Configuration": {
        "Host": "fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4",
INFO: Payara Micro running on host: fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4 port: 8080

Payara Micro URLs:
http://[fe80:0:0:0:181a:c8ff:fe55:da45%veth3f685e4]:8080/test

### Reproducer

move from Payara Micro 5.2022.3 to 5.2022.4

### Operating System

Ubuntu 20.04.5

### JDK Version

zulu-openjdk-alpine:17.0.5-jre-headless

### Payara Distribution

Payara Micro

**Comment by pioneer2k** [comment]
After realizing, that the same issue exists for us with Payara 5.2022.5, I invested some time to find a workaround. The versions 5.2022.4 and 5.2022.5 are working well on our DEV-Machines and on our Production Runtime Environment, but not on our CI/CD System GitHub Actions. 
When adding these settings to the VM on GitHub Actions everything works fine:
-Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Addresses=true -Djava.net.preferIPv4Stack=true

So if you think this this is unrelated to Payara you can close this issue. Even if these options are of course not necessary with Payara 5.2022.3.

**Comment by felixif** [comment]
Hello @pioneer2k,

Thank you for your finding. I am not very familiar with GitHub Actions, but I could try reproducing this issue in order to confirm if something was broken in the last 2 releases. A reproducer would be very useful.

**Comment by pioneer2k** [comment]
@felixif thank you for your response. Obviously I am not able to do that myself. If I build a simple GitHub Actions pipeline and start Payara Micro with a simple WAR, then everything works fine. Regardless which Payara version I use.
But in my original pipeline there are happening many things before Payara is started and it's very likely that some of these steps have an influence. But the effort will be very high to figure out which step can cause that.
So I can live with that workaorund.
If you want please close the issue.

**Comment by felixif** [comment]
Hi @pioneer2k,

Ok, I understand why a reproducer is not really viable in this situation. Regardless, I think the workaround you found is very useful information, and we could use it at least to create a KB article or blog post. With your permission, I could raise this up in our next meeting and update you on what has been decided, and after that, I can close the issue.

**Comment by pioneer2k** [comment]
Hi @felixif , of course. Please make it so.
