### ISSUE TITLE
Downloading document files face low speed

### ISSUE THREAD

**Issue by oaleem** [payara/Payara#606]
I am using gf 4.1 bundle 13. My application is jee based. When my application download any word,pdf file of size less then 100 mb it gets download in seconds. or minutes. But if the file is above 150 mb it takes 1 hour. I am on windows server. I can see GF is not auto scaling to the optimize level in windows. How ever simple ssh connection and ftp file transfer for files works fine.

**Comment by abhirockzz** [comment]
It is not exactly clear what the problem is (at least to me). It is hard to determine from the description as to how the problem is related to GF auto scaling etc. Some description of the application itself might be helpful. An executable test artifact (WAR/EAR) would be perfect

**Comment by mikecroft** [comment]
This was addressed outside the issue. We suspected that it was an environment/network/other issue since it worked fine when downloading from one server, but not from another, but that was never proven.
