### ISSUE TITLE
Build Eclipselink Cache Coordination provider (L1)

### ISSUE THREAD

**Issue by ke5stl** [payara/Payara#608]
Aside from Eclipselink's use of L2 shared cache (which another ticket addresses), there is another mechanism, which allows one instance of Eclipselink to tell other application instances (eg: in a cluster environment) that certain objects that may have been pulled in to the local L1 cache that they have become out of date.

Currently, Eclipselink supports (out of the box) RMI, JMS and JGroups for this functionality.  However, Eclipselink does provide the ability to add other implementations.

It would be great to have a Hazelcast provider for this, so that potentially, Hazelcast can be used for both L1 cache coordination *and* L2 cache.

**Comment by phillipross** [comment]
:+1:

**Comment by smillidge** [comment]
Sounds interesting. Definitely one to look into.

**Comment by ke5stl** [comment]
here is a link to the eclipselink cache coordination examples page:

https://wiki.eclipse.org/EclipseLink/Examples/JPA/CacheCoordination

**Comment by mikecroft** [comment]
Closing as this is also addressed by #165
