### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#61]
Is there any short term plans for docker support in payara? We are looking at moving towards docker within the next few months, with the hope to have rolled it out in all non-production environments by the end of January and production soon after. 

Our current plan of attack is to use a combination of Chef+Packer to build the images. We will enhance the existing [glassfish](https://github.com/realityforge/chef-glassfish) cookbook and combine it with some automation around packer. This of course is just a plan and we change directions when we actually start implementing it.

Is anyone interested in working on this together?

**Comment by mamboking** [comment]
We just started using the official glassfish image as our base image.  It would be great if we had a Payara one instead.

**Comment by realityforge** [comment]
Hi,

I have finally got some time allocated to try and get this completed. The way we have decided to go is to bake a few images;
* One base image with glassfish/payara bits on it. (See [busybox-glassfish](https://hub.docker.com/u/realityforge/busybox-glassfish/))
* One base image with a single glassfish domain defined. (See [busybox-glassfish-domain](https://registry.hub.docker.com/u/realityforge/busybox-glassfish-domain/))
* One base image with a single OpenMQ broker instance defined.

From these base image we would then configure them using a declarative json description of the broker instance or glassfish domain. This json format would be roughly derived from the chef-glassfish cookbook (See #51). 

To achieve this we have decided to extract the logic from chef-glassfish cookbook and re-write it with extensive tests. You can see the start of progress towards this at [redfish](https://github.com/realityforge/redfish). After we have got redfish to a further state of evolution, the plan would be to re-write chef-glassfish in terms of redfish.

So I just thought I would note what strategies we are trying. Also long term I would be interested in moving it under the payara project itself if this approach is successful.

**Comment by smillidge** [comment]
Initial Docker images are up. We welcome comments.

https://hub.docker.com/u/payaradocker/

**Comment by making** [comment]
@smillidge Is there Dockerfile? I'd like to know how to configure.

**Comment by making** [comment]
Sorry, found https://github.com/payara/docker
