### ISSUE TITLE
Bug Report: ConfigProperty Inject broken after restart while using Hashicorp Secrets

### ISSUE THREAD

**Issue by markusweisssiemens** [payara/Payara#6113]
### Brief Summary

If I inject a config property from a "Hashicorp Secrets Config Source":

@Inject
@ConfigProperty(name="firstname")
private String firstname;

into a CDI bean and deploy the WAR file it's working. Once the server is restarted it's broken and shows an error:

 org.glassfish.deployment.common.DeploymentException: CDI definition failure:Exception List with 1 exceptions:
Exception 0 :
javax.enterprise.inject.spi.DeploymentException: Deployment Failure for ConfigProperty firstname in class org.test.vault.BusinessService Reason No value present
	at fish.payara.microprofile.config.cdi.ConfigCdiExtension.validateInjectionPoint(ConfigCdiExtension.java:106)

### Expected Outcome

The ConfigProperty should be successfully read also if the server is just restarted.

### Current Outcome

The deployment fails because of the Exception:

org.glassfish.deployment.common.DeploymentException: CDI definition failure:Exception List with 1 exceptions:
Exception 0 :
javax.enterprise.inject.spi.DeploymentException: Deployment Failure for ConfigProperty firstname in class org.test.vault.BusinessService Reason No value present

### Reproducer

- Run a vault server with a secrets engine kv version 2 and create a secret with key firstname and a value you like
- Configure your Payara (tested with 5.2022.4 and 5.2022.2) in the MicroProfile section to access this secrets engine
- Deploy attached WAR from the ZIP [vaulttest.zip](https://github.com/payara/Payara/files/10195943/vaulttest.zip) file via administration console and check if page http://localhost:8080/vaulttest/hello shows you a message "We say Hello ---value given to key firstname---"
- stop-domain
- start-domain
- check server.log for error "...DeploymentException: Deployment Failure for ConfigProperty firstname in class ..."

### Operating System

Windows 10 Pro

### JDK Version

Java version: 11.0.16, vendor: Azul Systems

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi @markusweisssiemens,

Instead of war, would you be kind enough to share the sources of the complete reproducer app?

**Comment by markusweisssiemens** [comment]
Hi @shub8968 ,

sure. Attached you find the maven project.
[vaulttest-src.zip](https://github.com/payara/Payara/files/10256780/vaulttest-src.zip)

**Comment by shub8968** [comment]
Hi @markusweisssiemens,

I tried reproducing it on recent Payara release but I am unable to reproduce. I tried reproducing it using it in a containerized environment.
