### ISSUE TITLE
Bug Report: HTTP2 getRequestURL not the same as HTTP1

### ISSUE THREAD

**Issue by mafaul** [payara/Payara#6123]
### Brief Summary

Request.getRequestURL() returns local IP / name of server, instead of the browser URL  that was used.

This is only an issue when using http2, and when using a load balancer (like AWS ELB).

((HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest()).getRequestURL().toString();

On Payara 6.2022.2, using Jakarta EE 10., Java 17.

This issue seems very similar:
https://github.com/payara/Payara/issues/2614

### Expected Outcome

Request.getRequestURL() should return the URL that was entered into the browser, like it does when using http1.

### Current Outcome

We have to disable http2, since resources cannot load properly over http2 because it is trying to get some resources from a private URL behind a firewall.

### Reproducer

I will try and get a reproducer packaged.

### Operating System

AWS Linux 2 and Win 2019

### JDK Version

Zulu 17 aarch64 and Corretto 17 x64

### Payara Distribution

Payara Server Web Profile

**Comment by mafaul** [comment]
![image](https://user-images.githubusercontent.com/12007706/208227071-7d633b72-1750-4ce7-a3c9-42cad57c7577.png)

**Comment by mafaul** [comment]
Ok, so the 'host' header is not part of http2 anymore.
https://httpwg.org/specs/rfc7540.html#HttpRequest

**Comment by roberto-cisternino** [comment]
Grizzly should look for the authority header in HTTP/2
