### ISSUE TITLE
Bug? When payara6 with hibernate manipulating a database with name containing hyphen,  name below the hyphen are ignored

### ISSUE THREAD

**Issue by Hiroaki-Inomata** [payara/Payara#6125]
### Brief Summary

I am new to Payara.
The other day, I created a database named "dolphorca-front" with postgresql and registered it in payara's connection pool.
I tried using hibernate to create some tables in "dolphorca-front" database, but they were created in "dolphorca" database.
I think that when payara6 and hibernate manipulate a database with names containing hyphen, they ignore the names below the hyphen.

### Expected Outcome

It worked fine in wildfly27.

### Current Outcome

Payara6 did not work in jakartaee10 - java17 environment.

### Reproducer

See Brief Summary

### Operating System

MacOS Monterey

### JDK Version

Zulu JDK 17

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi @Hiroaki-Inomata,

Can you provide a complete reproducer app with steps on how to reproduce the reported scenario? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.
