### ISSUE TITLE
Bug Report: Could not build Payara 6 with JDK 17

### ISSUE THREAD

**Issue by harry-xm** [payara/Payara#6126]
### Brief Summary

Payara 6 does not build with JDK 17.

The `java.util.ConcurrentModificationException` is likely related to https://github.com/FasterXML/oss-parent/issues/27.

### Expected Outcome

Build success.

### Current Outcome

```
BUILD FAILURE

[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:4.1.0:manifest (default-manifest) on project scattered-archive-api: Execution default-manifest of goal org.apache.felix:maven-bundle-plugin:4.1.0:manifest failed.: ConcurrentModificationException -> [Help 1]
```

### Reproducer

With JDK 17 and Maven 3.8.6:

```
git checkout Payara6
mvn clean install -DskipTests
```

### Operating System

macOS 13.1

### JDK Version

Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)

### Payara Distribution

Payara Server Full Profile, Payara Micro

**Comment by shub8968** [comment]
Hi @harry-xm,

Payara 6 from sources can only be built using Java 11 currently.
