### ISSUE TITLE
Bug Report: Entities that are events do not always roll back

### ISSUE THREAD

**Issue by RInverid** [payara/Payara#6137]
### Brief Summary

When an Entity is in a transaction, and is then fired as an event, and an exception occurs in the listener, the transaction is not always rolled back.

A second listener is required that is named exactly the same as the listener that throws the exception, otherwise this bug doesn't occur.

The bug doesn't show up for every deploy, and every time you redeploy the app there is a chance of the bug occurring. If it does occur, it occurs on every call for that deploy.

### Expected Outcome

an exception thrown in an EJB should cause a transaction to be rolled back.

### Current Outcome

The transaction isn't consistently rolled back.

### Reproducer

[reproducer.zip](https://github.com/payara/Payara/files/10344384/reproducer.zip)

This project contains a script called reproduce.sh, which sets up a local environment, and runs mvn verify 10 times. every verify deploys, runs an IT test which verifies the expected behaviour (a rollback), and undeploys. if there is a test failure, it prints & stops.

Since behaviour is consistent per deploy, but differs between deploys, this test method is neccesary.

EDIT:
Apparently the cargo plugin used for auto deploying & undeploying doesn't work on every machine - as an alternative to uing mvn verify this bash script can be run in a loop:
`asadmin --port=14848 undeploy testProject ; asadmin --port=14848 deploy --upload=true target/testProject.war; curl -s http://localhost:18080/testProject/api/event-exception; echo`

Where the output 'Success' means expected behaviour, and an error means the issue is present.

### Operating System

MacOS

### JDK Version

OpenJDK 11.0.17

### Payara Distribution

Payara Docker Image

**Comment by RInverid** [comment]
After some outside help, it seems the issue is that multiple beans (in this case, event listeners) with the same name isn't allowed according to the spec, but Payara allows this. One of the beans with the same name sort-of fails initialization and causes weird behaviour like transactions not rolling back.

**Comment by shub8968** [comment]
Hi @RInverid,

The reproducer is not running correctly
![Screenshot (423)](https://github.com/payara/Payara/assets/36557492/8687840c-fdc0-483f-9ccf-bb97dd47b542)
![Screenshot (424)](https://github.com/payara/Payara/assets/36557492/9bba4e86-2748-44e2-a2f7-72fea7aee5e3)
.
