### ISSUE TITLE
Bug Report: Stuck threads after update Payara Community Server from version 2020.2 to 2022.5

### ISSUE THREAD

**Issue by alebordig** [payara/Payara#6139]
### Brief Summary

After we updated the Payara Community Server from version 2020.2 to 2022.5, the virtual server eventually stop answering HTTP requests (It seems to happen approximately two days after restarting payara fish due to a previous "freezing").

Using "Health Status - Stuck Threads" feature and analyzing server.log, it seems the http-listener-2 get "stucked" permanently trying to log, as the example below:

```
'']', [status=WARNING, message='Stuck Thread: "http-thread-pool::http-listener-2(32)" daemon prio=5 Id=146317 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b3ce311
	at java.base@11.0.17/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b3ce311
	at java.base@11.0.17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.17/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.17/java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:367)
	**at com.sun.enterprise.web.logger.FileLoggerHandler.publish(FileLoggerHandler.java:164)
	at java.logging@11.0.17/java.util.logging.Logger.log(Logger.java:979)
	at com.sun.enterprise.web.VirtualServer$1.log(VirtualServer.java:953)
	at java.logging@11.0.17/java.util.logging.Logger.doLog(Logger.java:1006)**
```

If we try to access the same virtual server URL again (in another web browser tab), another http-listener-2 got stuck.
Only by restarting payara or recreating the virtual server, the http-listeners are released.

I'm attaching the server.log summary here:
[server.log_summarized.txt](https://github.com/payara/Payara/files/10362983/server.log_summarized.txt)

### Expected Outcome

No stuck threads events on the virtual server due to logging concurrency.

### Current Outcome

Every few days (we observed around 2 days), we need to restart payara (or recreate the virtual server) due http-listener-2 stuck threads apparently caused by Virtual Server logging.

### Reproducer

Unfortunately, we have not found any specific reason or steps that raise this particular situation, in a way to reproduce this situation in a predictive way.
Seems some thread race condition or deadlock trying to get some resource.

### Operating System

CentOS Linux release 7.9.2009 (Core)

### JDK Version

openjdk version "11.0.17" 2022-10-18 LTS OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS) OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)

### Payara Distribution

Payara Server Full Profile

**Comment by fturizo** [comment]
Greetings @alebordig, Payara Platform 5 Community support has ended as of last year, please make sure to migrate your applications to Payara Platform 6 and convert them to Jakarta EE 10 and then confirm if this issue affects your environment,

If you encounter any issues or have trouble transforming your applications and migrating them to Payara Platform 6 and if you want to remain on Payara Platform 5, you may consider acquiring a [Payara Enterprise subscription](https://www.payara.fish/enterprise/).

**Comment by fturizo** [comment]
Greetings @alebordig, as we didn't receive any updates on this issue we'll proceed to close it.

**Comment by mzaum** [comment]
I know this bug is closed, and Payara 5 community is no longer supported, but for anyone reading this bug report, this bug first appears in Payara 5.2021.7.  I ran into this exact issue and was able to reliably reproduce it under heavy load on Payara 5.2021.7+.  Payara 5.2021.6 is unaffected.  If I had to guess, it is probably related to FISH-81 #5369 but I haven't dove into it completely.
