### ISSUE TITLE
Bug Report: Error in calling SOAP web service

### ISSUE THREAD

**Issue by mmsaber** [payara/Payara#6147]
### Brief Summary

I have deployed a WAR file with SOAP endpoints and created a handler to detect any call for all web services that the client may call. I want to detect the nonexistent web service but unfortunately, I am getting errors on Payara only if I deployed the WAR file on any other application server it works as expected the error has been logged by the handler,

### Expected Outcome

**Request:** 
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.jaxws.demo.jcg/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getBooks>
         
         <bookId>1</bookId>
      </ser:getBooks>
   </soapenv:Body>
</soapenv:Envelope>

**Response:**
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><S:Body><S:Fault xmlns:ns3="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Client</faultcode>
<faultstring>Cannot find dispatch method for {http://service.jaxws/}getfBook</faultstring>
</S:Fault>
</S:Body>
</S:Envelope>

### Current Outcome

**Request:** 
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.jaxws.demo.jcg/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getBooks>
         
         <bookId>1</bookId>
      </ser:getBooks>
   </soapenv:Body>
</soapenv:Envelope>

**Response:**
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
   <S:Body>
      <S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
         <faultcode>S:Server</faultcode>
         <faultstring>java.lang.NullPointerException</faultstring>
      </S:Fault>
   </S:Body>
</S:Envelope>

### Reproducer

Deploy any SOAP web service and try to call it using SOAPUi, it works great for example the **web method name is: getBook**
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.jaxws.demo.jcg/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getBook>
         
         <bookId>1</bookId>
      </ser:getBook>
   </soapenv:Body>
</soapenv:Envelope>

 then try to change the web method name for example try to call **getBooks not getBook**
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.jaxws.demo.jcg/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getBooks>
         
         <bookId>1</bookId>
      </ser:getBooks>
   </soapenv:Body>
</soapenv:Envelope>

### Operating System

Windows 11

### JDK Version

JDK-1.8

### Payara Distribution

Payara Server Full Profile

**Comment by felixif** [comment]
Hi @mmsaber,

Could you please specify the Payara Server version, the JDK minor version and the JDK vendor? We would also need a proper reproducer in order to be able to verify the issue and escalate it. Thank you for reporting the issue!

Best regards,
Felix

**Comment by felixif** [comment]
Hello @mmsaber,

As we have not received any update on this issue, we will proceed to close it for now.
