### ISSUE TITLE
Bug Report: Missing docker images for Payara 6.2022.2

### ISSUE THREAD

**Issue by TheOnlyAl** [payara/Payara#6152]
### Brief Summary

The Tags for Payara 6.2022.2 seem to be missing on dockerhub.

For example: https://hub.docker.com/r/payara/server-full/tags?page=1&name=6.2022.2

### Expected Outcome

The image tags should exist.

### Current Outcome

No image tags exist.

### Reproducer

https://hub.docker.com/r/payara/server-full/tags?page=1&name=6.2022.2

### Operating System

-

### JDK Version

-

### Payara Distribution

Payara Docker Image

**Comment by shub8968** [comment]
Hi @TheOnlyAl,

I have escalated this to the platform development team as `FISH-6968`.

**Comment by shub8968** [comment]
Closed
