### ISSUE TITLE
Bug Report: Image 5.2022.5 - Admin-Realm missing while creating different Auth-Realm 

### ISSUE THREAD

**Issue by sveneppe** [payara/Payara#6208]
### Brief Summary

I found that the default admin realm is no longer present when I create other auth realms (JDBCRealm) using a post-boot-command script.
The container boots without errors, but when switching to the login UI of the DAS, "No realm admin-realm" is logged twice and a login with the normal user ID admin / admin is not possible. 

### Expected Outcome

If I create a new auth-realm within a post-boot-command-script, I expect that the admin-realm has not been deleted. It should be possible to log on to the DAS.

### Current Outcome

It's not possible to login.

### Reproducer

1. create a post-boot-command file with the creation of a new realm: 
1.1 My version: (some parts changed) create-auth-realm --classname=com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm --property=jaas-context=jdbcRealm:datasource-jndi=jdbc\/test-db:user-table=public.table:user-name-column=name:password-column=password:group-table=public.realmgroup_realmuser:group-table-user-name-column=realmusers_name:group-name-column=realmgroup_name:digest-algorithm=SHA-256:charset=UTF-8: --target=server-config Test-Realm
2. mount the file on the POSTBOOT_COMMAND_FILE_PATH.
3. start the Docker container with payara-full/5.2022.5 
4. Switch to the login view 
5. log should output: No realm admin-realm
6. Authorization with admin/admin not possible

----

Current workaround solving issue:

Recreated admin-realm with post-boot-command-script and default admin-realm configuration:
(create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --property=file=${com.sun.aas.instanceRoot}/config/admin-keyfile:jaas-context=fileRealm: admin-realm)

All other realm-creations works as expected. 
Authentication with default credentials is possible.

### Operating System

Windows 10 Pro

### JDK Version

Zulu JDK 8u352

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Greetings @sveneppe,

Payara Platform 5 Community support has ended, please migrate your environment to Payara Platform 6 and verify if this issue affects its current release. 

If you encounter any issues or have trouble transforming your applications and migrating them to Payara Platform 6 and if you want to remain on Payara Platform 5, you may consider acquiring a [Payara Enterprise subscription](https://www.payara.fish/enterprise/).

Thank you,
Elif
