### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ashwinivijayakumar07** [payara/Payara#6210]
### Brief Summary

When we restart Payara full on our servers, we repeatedly get 404 errors when we try to connect to our webservices deployed on the servers.

The only way we were able to fix this was restarting payara couple of times or in some instances uninstalling and installing payara again. But these solutions were a hit or a miss, i.e., it does not work consistently.

The payara version is: 5.45.0-1 and we are seeing this issue since we upgraded to jdk 11, it used to work well on lower jdk versions.

### Expected Outcome

<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
   <S:Body>
      <ns2:XXXXXXMessageResponse xmlns:ns2="http://XXXXXX.XXXXX.com/" xmlns:ns3="http://fault.common.XXXXXX.XXXXX.com/">
         <return>
            <status>Success</status>
         </return>
      </ns2:XXXXXXMessageResponse >
   </S:Body>
</S:Envelope>

### Current Outcome

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <title>Payara Server Enterprise  5.45.0 #badassfish - Error report</title>
      <style type="text/css">
         
      </style>
   </head>
   <body>
      <h1>HTTP Status 404 - Not Found</h1>
      <hr/>
      <p>
         <b>type</b>
         Status report
      </p>
      <p>
         <b>message</b>
         Not Found
      </p>
      <p>
         <b>description</b>
         The requested resource is not available.
      </p>
      <hr/>
      <h3>Payara Server Enterprise  5.45.0 #badassfish</h3>
   </body>
</html>

### Reproducer

.

### Operating System

Red Hat Enterprise Linux Server, Version - "7.9"

### JDK Version

11

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
You are using Payara Enterprise Edition. If you are an existing enterprise customer, kindly raise the ticket through the official support portal otherwise it is a breach of our official Payara Enterprise License.
