### ISSUE TITLE
Bug Report: no logging from payara-web in kubernetes

### ISSUE THREAD

**Issue by eduarddrenth** [payara/Payara#6238]
### Brief Summary

When deploying payara/server-web:5.2022.5-jdk17 to kubernetes logging stops:

- `kubectl logs <pod>` does not show logging after the last (JMX) startup line
- with `cat server.log` via `kubectl -exec it <pod> -- bash` logging stops even sooner

### Expected Outcome

logging to stdout and server.log is shown

### Current Outcome

logging is not shown

### Reproducer

deploy a war on payara/server-web:5.2022.5-jdk17, run in k8s

### Operating System

k8s kubernetes

### JDK Version

jdk 17 from payara/server-web:5.2022.5-jdk17

### Payara Distribution

Payara Server Web Profile

**Comment by eduarddrenth** [comment]
I'll see what I can do, the app isn't jakarta/ee10 yet, but I may be able to deploy another app. Also this issue may be for kubernetes.

**Comment by fturizo** [comment]
We'll proceed to close this issue due to inactivity.
