### ISSUE TITLE
README changes: "Thank you for downloading GlassFish Server Open Source Edition 4.1!"

### ISSUE THREAD

**Issue by quipsy-karg** [payara/Payara#625]
Currently the file payara41\README starts with the following line:

_Thank you for downloading **GlassFish Server Open Source Edition** 4.1!_

This is not nice. It certainly should read instead:

_Thank you for downloading **Payara** 4.1!_

**Comment by mikecroft** [comment]
Thanks, Markus, it looks like the whole README needs updating.
