### ISSUE TITLE
Windows service is named  "domain1 GlassFish Server"

### ISSUE THREAD

**Issue by quipsy-karg** [payara/Payara#628]
Payara registers Windows services under the following name

   _domain1 **GlassFish** Server_

with a description of

   _**GlassFish** Server_

This is not nice. Certainly it should be "**Payara**" in both places. :-)

**Comment by mikecroft** [comment]
Just double checked my change - I changed the service name, but not the description, so that will need a new pull request too

**Comment by smillidge** [comment]
Fixed by #794
