### ISSUE TITLE
Bug Report: Jakarta EE 10 project not running on Payara 6 server using Eclipse IDE

### ISSUE THREAD

**Issue by ojuschugh1** [payara/Payara#6288]
![error 4](https://github.com/payara/Payara/assets/79078267/36df1ee7-5e4d-457a-a63b-1b6651dd7a2f)
### Brief Summary

Hi Everyone,
For the last few days, I was trying to run the Eclipse cargo-tracker application (maven project based on Jakarta EE 10 ) on Payara 6 server in Eclipse IDE. I was encountering the same error message every time, I try to run the application after starting the server of Payara 6 when I click on the run as on server option, It gives a Server Error message that the selection is not within the module.

On Investing the problem with fellow contributors I found that the Eclipse IDE does not support the new Jakarta EE 9/10 now, so the run as in the project context menu does not work.
​
The Link to repository-:https://github.com/OmniFish-EE/cargotracker/tree/omnifish-jee10

The steps to run the project on the local machine are provided in Readme.MD file.

Below I have attached the error message I am getting.

IDE-Eclipse ide for Enterprise Java and Web Developers.
Payara 6 server-Full Profile
JDK-17

Thanks and Regards

### Expected Outcome

Jakarta EE 10 project properly working on Payara 6 server using Eclipse IDE

### Current Outcome

Currently Jakarta EE 10 project is not properly working on Payara 6 server using Eclipse IDE

### Reproducer

Try the following steps to deploy manually.

mvn package -DskipTests to package the application into a war.
Run payara by asadmin start domain1
Copy the war to payara6\glassfish\domains\domain1\autodeploy

Thanks and Regards

### Operating System

Windows 10

### JDK Version

17

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @ojuschugh1 , 

Because this is an ecosystem issue, I will close this issue and continue on [ecosystem support](https://github.com/payara/ecosystem-support/issues/68).

Thank you,
Elif

**Comment by ojuschugh1** [comment]
Hi @Elifzeynepedman ,

Sure, Thanks for the help.

Thanks and Regards
