### ISSUE TITLE
Bug Report:  Zero EJB in payara 5.28 version on Enterprise Application 

### ISSUE THREAD

**Issue by vaibhavbsingh-hw-dev** [payara/Payara#6290]
### Brief Summary
 gf5 deploy
Deploying application hwApp to domain1 domain
remote failure: Error occurred during deployment: Exception while deploying the app [hwApp] : Invalid ejb jar [togglz.jar]: it contains zero ejb. 
Note: 
1. A valid ejb jar requires at least one session, entity (1.x/2.x style), or message-driven bean. 
2. EJB3+ entity beans (@Entity) are POJOs and please package them as library jar. 
3. If the jar file contains valid EJBs which are annotated with EJB component level annotations (@Stateless, @Stateful, @MessageDriven, @Singleton), please check server.log to see whether the annotations were processed properly.. Please see server.log for more details.
Command deploy failed.

### Expected Outcome

Application should deployed successfully

### Current Outcome

deployment is failing

### Reproducer

Its our enterprise project where suddenly we start seeing this error. and slowly this error caught up other developers.

### Operating System

Mac Os Ventura version 13.4

### JDK Version

openjdk 11.0.18 2023-01-17 LTS OpenJDK Runtime Environment Zulu11.62+18-SA (build 11.0.18+10-LTS) OpenJDK 64-Bit Server VM Zulu11.62+18-SA (build 11.0.18+10-LTS, mixed mode)

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi @vaibhavbsingh-hw-dev,

I am closing the issue since you have raised it for the Enterprise version of Payara. If you are an existing Payara Enterprise user, kindly raise the issue through the Support Portal. If not then, kindly stop using the Enterprise version as it's a breach of the Enterprise user agreement, and further actions can be taken.
