### ISSUE TITLE
Bug Report: Suspected WebappClassLoader Leak 

### ISSUE THREAD

**Issue by kelvinlukhee** [payara/Payara#6301]
### Brief Summary

We are currently using payara version 5.2022.5.

We noticed an increase in memory usage after each redeployment of our web application and thus we spent some time in investigating it. We captured the heap dump of the payara server after redeployment. We found that the instance of `WebappClassLoader` from the last deployment was not garbage collected, holding most of the resources with it.  

We tried to find out which GC root was holding a reference to it and prevented the destruction of the classloader. The screenshot attached below shows our finding. It looks like a cached request in the DefaultWorkerThread's cache is holding a reference to the classloader. However, we have searched online and looked into the codes, and yet failed to find a way to tell it to evict the cache.  

![image](https://github.com/payara/Payara/assets/135788011/3c949dfa-9c43-4058-a765-2e76e6ef381f)

### Expected Outcome

The old `WebappClassLoader` instance shall be garbage collected to recover the memory held by objects of the last instances 

### Current Outcome

The old `WebappClassLoader` instance remains alive and prevented the garbage collection of other objects.

### Reproducer

To be provided later

### Operating System

Centos 6.5

### JDK Version

Oracle JDK 1.8.202

### Payara Distribution

Payara Server Web Profile

**Comment by kalinchan** [comment]
Hi @kelvinlukhee,

It looks like you are running Payara Community 5 which is out of support.

Are able to test this issue on the current release of Community 6?
