### ISSUE TITLE
Bug Report: implicitCdiEnabled property is not working

### ISSUE THREAD

**Issue by IchBin** [payara/Payara#6308]
### Brief Summary

In testing out our applications on Payara6, it would seem that the implicit CDI property is not being honored. Any application where we are using the spring framework is throwing the error that "CDI is not available" on deployment.  In order to get past this issue we need to disable implicit CDI. We would like to set this up in our scripted deployments.

### Expected Outcome

Adding the --property implicitCdiEnabled=false to the deployment command should disable implicit CDI. 

### Current Outcome

After adding the --property implicitCdiEnabled=false to the deploy command, the "CDI is not available" error persists.

### Reproducer

So far any web application using SpringMVC framework has this error.

### Operating System

MacOS

### JDK Version

JDK17

### Payara Distribution

Payara Server Full Profile

**Comment by felixif** [comment]
Hello @IchBin,

Unfortunately, Payara Platform Community does not benefit from support for deployment issues encountered on Spring Framework/Spring Boot issues. Please consider acquiring a Payara Enterprise subscription to receive proper support.

**Comment by IchBin** [comment]
Thought I was doing a nice thing by taking the time to report an issue. Guess I won't be doing that if "We don't fix problems unless the customer pays us." is the response.

We have a work around so not a big deal to us.

**Comment by bacr01** [comment]
Hello @IchBin,

I have the same problem. Could you provide your work around, please?

Best regards

**Comment by bacr01** [comment]
Adding the beans.xml worked for me. Thank you!
