### ISSUE TITLE
Bug Report: (Hazelcast) Node creation failed by [using in-correct hazelcast-config.xml]

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6312]
### Brief Summary

To "conceptual prove" Payara 6 will work with hazelcast data grid by hazelcast-config.xml. I developed a pilot OSGi jar that include a simple Object say "Audit". it comes with backend database store (MapStore) and DataSerializableFactory implementation. 

Then add the jar to Payara domain by [./asadmin add-library ThssJPAOGSiLib-1.0.jar]

Then add map section and data-serializable-factories such as: 

<img width="714" alt="Screenshot 2023-06-22 at 11 33 16 am" src="https://github.com/payara/Payara/assets/11171226/a29d5032-bccc-4d4a-9f65-0041ce573405">

<img width="1238" alt="Screenshot 2023-06-22 at 11 34 48 am" src="https://github.com/payara/Payara/assets/11171226/7b2759b3-02ee-4cbf-b906-5ec08ec73fa1">

Then restart domain, payara load "hazelcast-config.xml" from $PAYARA_DOMAIN/config and create hazelcast node properly.

But, the previous bug, DAS admin_UI is not start properly

After "conceptual proven", I started develop a staging project with more business objects and put it into hazelcast-config.xml by modified package structure and implementation. The new configure as:

<img width="781" alt="Screenshot 2023-06-22 at 11 42 06 am" src="https://github.com/payara/Payara/assets/11171226/b73a1b04-5597-45d1-9983-0f396a231566">

<img width="1299" alt="Screenshot 2023-06-22 at 11 43 00 am" src="https://github.com/payara/Payara/assets/11171226/ffd41165-1098-45bf-a871-380ba00a8621">

To avoid pilot and staging version “cross infection”. I removed whole payara6 directory and re-create it from scratch to clean install a brand new production domain. Re-configure everything and add all related libs and custom developed OSGi compatibility jars.

upload hazelcast-config.xml to $PAYARA_DOMAIN/config and restart domain. 

Hazelcast load configure file hazelcast-config.xml properly, but hazelcast node not create. error message find from attachment server.log
[server.log](https://github.com/payara/Payara/files/11827941/server.log)

### Expected Outcome

Brand new created Payara 6 will load hazelcast-conf.xml from $PAYARA_DOMAIN/config and create hazelcast node properly or report current hazelcast-config.xml related error.

### Current Outcome

New created brand new Payara6 loaded current domain configure in $PAYARA_DOMAIN/config directory and also using previous pilot version's DataSerializableFactory as well. It is trying find com.longz.thss.lib.thssjpaogsilib.factory.AuditDataSerializableFactory that declared in pilot version.

### Reproducer

Follow Brief summary to reproduce it.

My guess is. When Payara 6 domain restart, it trying to load hazelcast declared object or entity from local file system backup to restore it back. If it is true, Payara should be able to provide a function to clean that backup.

Any idea? Please advise!

### Operating System

Rocky Linux 9

### JDK Version

Oracle JDK 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by kalinchan** [comment]
Hi @cidylong, 

This is not a supported use case as it doesn't follow the guidelines of any other Jakarta EE applications.

We do not support the use of the Data Grid/Hazelcast with OSGi modules
