### ISSUE TITLE
Bug Report: Payara server instances not starting/stopping after its created.

### ISSUE THREAD

**Issue by shre7989** [payara/Payara#6321]
### Brief Summary

Payara Community Version: 5.2021.9
OS: MacOS Monterey (12.6)

I created a deployment group using the admin console (:4848) named test-deployment-group.
I then created three instances using the admin console. (test-instance-1, test-instance-2, test-instance-3).

When I start the deployment group, it gives me a loading screen and then it closes down (nothing happens - no updates).
Then when I try to close or deleted those test-instances it tells me to stop those instances first, even if the instance status is closed as per the info dialog that opens up when you click on that specific instance tab. 

The instance logs are empty. I checked the /domains/domain1 directory with no new folders for the instance I created. I do not know if there is supposed to be new directories for each instance under the domain. Nothing on the payara server documentation that can clear my doubts. 
### Expected Outcome

I expected all the instances under the deployment group to be started when I start it using the admin console (:4848). This info should visually show up in the admin console, the instances under the deployment group must have a green circle indicating that the instance has been started.

### Current Outcome

When I start the deployment group, the instances are not started and is not visually indicated in the instances info under the deployment group in the admin console. When I try to delete those test-instances I get an error bar in the gui indicating that the instances should be stopped before deleting it. 

When I try to stop the instance (test-instance-1) using asadmin. It says that there is already a process using the admin port 24855, which is the configured port for test-instance-1. I then tried to lookup port 24855 on browser using localhost:24855, and I get a screen (like the auth page for admin console) saying "Administration console not available".

I can kill the process thats running on the said ports the instances are connected to, and then I am able to delete the instances through the admin console, however I think the information about wether an instance has started or stopped must be visually indicated in the admin console UI. Currently it does not change its status from stopped.

**Instance not starting:**
![Screen Shot 2023-06-26 at 10 01 03 AM](https://github.com/payara/Payara/assets/55064602/362643a6-86a4-4084-aa61-9fb9ca1335ae)

**Instance delete error:**
![Screen Shot 2023-06-26 at 10 01 46 AM](https://github.com/payara/Payara/assets/55064602/258a835a-b633-44b5-bc6d-1ff5528faba9)

**No Admin Console:** 
![Screen Shot 2023-06-26 at 9 59 08 AM](https://github.com/payara/Payara/assets/55064602/0744e914-bf79-43bd-aae5-c7553c809e87)

### Reproducer

1.  Install Payara Community Platform 5.2021.9
2. Start the default domain in payara by doing `./asadmin start-domain domain1`.
3. Give an admin user name and password when prompted.
4. Login to the admin console at localhost:4848
5. Login with the username and password you created.
6. Click on deployment groups menu option in the left side bar.
7. Create a new deployment group and give it any name.
8. Now click the name of the deployment group you created which is now a submenu under the deployment groups menu.
9. Click on the instances tab on the top right header panel.
10. Click on new, and create a new instance and name it anything you want.
11. Now click on your deployment group name again under the deployment group menu.
12. Click on start deployment group.
13. Nothing happens, and the instances under that deployment group also is not visually indicated as started.
14. Now try to delete the instance or the deployment group using the appropriate sub-menus.
15. It will shoot out an error saying that the instance must be stopped before it is deleted when the admin console has not indication of the instances actually starting.

### Operating System

MacOS Monterey (12.6)

### JDK Version

openjdk 11.0.9.1 2020-11-04 LTS

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Greetings @shre7989 

Payara Platform 5 Community support has ended, please migrate your environment to Payara Platform 6 and verify if this issue affects its current release.

If you encounter any issues or have trouble transforming your applications and migrating them to Payara Platform 6 and if you want to remain on Payara Platform 5, you may consider acquiring a [Payara Enterprise subscription](https://www.payara.fish/enterprise/).

Best Regards,
Elif
