### ISSUE TITLE
Bug Report: Payara fails to respond with wildcard generics/FISH-7666

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#6343]
### Brief Summary

Payara fails to respond with wildcard generics due to this bug in Jersey: https://github.com/eclipse-ee4j/jersey/issues/5328.

### Expected Outcome

Applications running fine on Payara 5 should run fine on Payara 6.

### Current Outcome

Applications which are running fine on Payara 5 are failing on Payara 6.

### Reproducer

See https://github.com/eclipse-ee4j/jersey/issues/5328.

### Operating System

any

### JDK Version

Zulu JDK 17

### Payara Distribution

Payara Server Full Profile

**Comment by mkarg** [comment]
This bug is a **showstopper** for the migration of existing applications from Payara 5 to Payara 6.
This bug is fixed in Jersey since version **3.1.3**.
I like to urge the Payara team in include **Jersey 3.1.3** to get rid of this showstopper as soon as 3.1.3 is available on Maven Central (will pop up there in the next few days).

**Comment by mkarg** [comment]
Jersey 3.1.3 is now available on Maven Central.

**Comment by shub8968** [comment]
Hi @mkarg,

I've escalated the issue with internal JIRA `FISH-7666 `.

**Comment by mkarg** [comment]
This issue is open since several weeks and I wonder why?

**Comment by mkarg** [comment]
Three more weeks gone. Any news?

**Comment by mkarg** [comment]
"Ping" :-)

**Comment by mkarg** [comment]
@shub8968 As the actual solution is provided by Jersey for several months, I really wonder why the Payara team does neither integrate it nor even respond to this issue an *any* way since August. Could someone of the Payara team please outline a plan when there will be a Payara 6 CE release containing that fixed Jersey version?

**Comment by mkarg** [comment]
Three more weeks without at lease *any* comment from the Payara team. Could you *please* briefly tell us the current situation? Thanks! :-)

**Comment by mkarg** [comment]
@smillidge Steve, I doubt it is your team's intension to keep existing solutions unused for months, so I would kindly ask you to ask someone of your team to post a brief decision about this issue. Thanks a lot! 🙏

**Comment by smillidge** [comment]
Jersey upgrade is scheduled for one of the next releases so that should fix it.

**Comment by mkarg** [comment]
I would be happy if it could be included in 6.2023.12.

**Comment by mkarg** [comment]
I confirm that I am unable to reproduce the bug anymore using Payara 6.2024.3. 😄 

*Possibly the bug was fixed earlier, but I had no time to check older versions of Payara 6.*
