### ISSUE TITLE
Bug Report: Payara-6, list-applications not work at all

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6370]
### Brief Summary

deployed ejb application can't be list by run [bin/asadmin list-applications]

### Expected Outcome

deployed application can be list out by run asadmin command

### Current Outcome

There is nothing list out

### Reproducer

Deploy applications by run [$PAYARA_HOME/bin/asadmin --password-file deploy --force=true --target APPDG --enabled=true --type ejb --name EjbJar /home/payara/software/ejb/EjbJar-1.0-SNAPSHOT.jar]

Verify it by check instance log, it is working fine, application jar files can found under domain/applications/__internal/EjbJar

but when I run [$PAYARA_HOME/bin/asadmin --passwordfile /home/payara/config/payaraPW.txt list-applications]. there is nothing list out.
<img width="1150" alt="Screenshot 2023-08-19 at 9 08 14 am" src="https://github.com/payara/Payara/assets/11171226/0681e60c-d857-447d-9a82-1f0b37d9225f">

As result, I can't undeploy it from command line in terminal 

### Operating System

Rocky Linux 9

### JDK Version

Oracle JDk 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi @cidylong,

I am unable to reproduce it. Kindly provide the reproducer app. Thanks.

![image](https://github.com/payara/Payara/assets/36557492/5694d257-e95f-4812-8271-54a8bf41d77d)

**Comment by cidylong** [comment]
@shub8968 , I tested again this morning. I found totally different result from command line (asadmin) and __admingui as attached:
<img width="1131" alt="Screenshot 2023-09-06 at 10 23 08 am" src="https://github.com/payara/Payara/assets/11171226/ad5fc022-6064-4377-89d0-72306aa1104a">
<img width="2008" alt="Screenshot 2023-09-06 at 10 24 27 am" src="https://github.com/payara/Payara/assets/11171226/c7c30e5e-c5d3-44b4-9ebd-8a92d3a79b50">
