### ISSUE TITLE
Bug Report: load primefaces as lib will cause __admingui failure

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6372]
### Brief Summary

This issue (Issue #6306) was reported in payara-6.2023.5-7, and it is still here.

The main issue is, when primefaces-13.0.0.jar was loaded into domain, then restart domain, DAS server started properly but admin gui application __admingui will failure to start.

### Expected Outcome

__admingui will dependent on mojarra instead of other jsf implementation.

### Current Outcome

When other jsf implementation (such as primefaces) was load as lib,  __admingui failed to load

### Reproducer

configure payara-6.2023.5 or newer version.

add primefaces-12.0.0.jar or newer version as lib

restart payara domain.

__admingui failed.

<img width="2113" alt="Screenshot 2023-08-20 at 12 58 42 pm" src="https://github.com/payara/Payara/assets/11171226/5c8b0687-b2da-4a5e-9cf4-d71ce13837d1">

### Operating System

Rocky Linux 9

### JDK Version

Oracle idk 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by lprimak** [comment]
You need the `-jakarta` classifier of PrimeFaces, the one that uses Jakarta 9+ namespace

**Comment by cidylong** [comment]
This issue is talking about add primefaces as domain lib, it will cause __admingui failure.

Yeah. I already used it in my web application. 

And this
<img width="418" alt="Screenshot 2023-08-20 at 2 53 40 pm" src="https://github.com/payara/Payara/assets/11171226/c314f635-0c1c-40e1-897b-5964830a28f8">
 is the piece of my pom.xml

**Comment by svendiedrichsen** [comment]
> This issue is talking about add primefaces as domain lib, it will cause __admingui failure.
> 
> Yeah. I already used it in my web application.
> 
> And this <img alt="Screenshot 2023-08-20 at 2 53 40 pm" width="418" src="https://user-images.githubusercontent.com/11171226/261831587-c314f635-0c1c-40e1-897b-5964830a28f8.png"> is the piece of my pom.xml

The stacktrace states that the javax.faces... class is missing. Which IMO suggests that you haven't put the jakarta version of primefaces into the domain lib.

**Comment by cidylong** [comment]
@svendiedrichsen , sorry, I was confused, in my understanding, payara-6 will support jarkata.faces.context.X name space and it will not dependent on javax.faces.context.X.

Otherwise, please advise!

**Comment by lprimak** [comment]
I think you are still confused. Please re read the thread carefully.

**Comment by svendiedrichsen** [comment]
> @svendiedrichsen , sorry, I was confused, in my understanding, payara-6 will support jarkata.faces.context.X name space and it will not dependent on javax.faces.context.X.
> 
> Otherwise, please advise!

@cidylong I am talking about the primeface lib you put into the domain lib. Not the (provided) dependency from your app pom. I seems you have put the primefaces version referencing the javax.faces... namespace into the domain lib. But you should have put the primefaces version referencing the jakarata.faces... namespace there.

**Comment by cidylong** [comment]
@svendiedrichsen , I had added primefaces to payara domain lib as common type [$PAYARA_HOME/bin/asadmin --password file add-library --type common /home/payara/software/lib/primefaces-13.0.0.jar], seems there is no way to use parameters to let payara to load this lib with extension "-jarkata". 

Please advise!

**Comment by svendiedrichsen** [comment]
There is no specific parameter to be used. Either the primefaces version you deploy uses the javax.faces or the jakarta.faces namespace. Have you ever tried not putting it in the domain/lib folderbut have deployed with your app? Does that work?

**Comment by cidylong** [comment]
I had added it to $PAYARA_DOMAIN/lib by run [$PAYARA_HOME/bin/asadmin --passwordfile add-library --type common /home/payara/software/lib/primefaces-13.0.0.jar] and then use it by every individual applications (such as: EJBs and WARs) through pom.xml dependency with <classifier>  and <scope> tags (as above attached).

It works fine in my EJB applications, which means EJB applications will use jarkata.faces.context.X name space properly over pom.xml dependency configure. 

I will test WAR application later, I believe it will works fine as well.

**Comment by cidylong** [comment]
@svendiedrichsen , this is most likely __admingui application class loader issue. I mean __admingui web application should be able to handle multiple JSF implementations in the lib path and only dependents on Mojarra implementation (as it is proposed).

**Comment by svendiedrichsen** [comment]
@cidylong Thanks for testing. Could you please check that the jar that you succesfully tested with you application is the same, and I mean _literally_ the same, you put into the domain/lib folder?

**Comment by cidylong** [comment]
@svendiedrichsen , Yes. I had double checked.  After I loaded the lib, primefaces-13.0.0.jar is seating in $PAYARA_DOMAIN/lib.

**Comment by svendiedrichsen** [comment]
@cidylong we seem to talk past each other all the time. 

As @lprimak stated there are two different versions of the primefaces library since version 10.0.0-RC2. One using the javax.faces namespace and one using the jakarta.faces namespace. Please make sure that you put the one using the jakarta.faces namespace into the domain/lib folder.

**Comment by cidylong** [comment]
@svendiedrichsen , probably I have to build primefaces lib from sources by using -jarkata options? 

please reply to confirm it.

**Comment by svendiedrichsen** [comment]
No, this version already exists. You should be able, as @lprimak wrote earlier, to use the classifier _jakarta_ in a application build. The jar that will used then should be the jakarta version and you should be able to find under WEB-INF/lib af this application. You can then use this version for the domain/lib of the payara.

**Comment by svendiedrichsen** [comment]
> you have much patience @svendiedrichsen :)

Thank you. But I'm afraid this was my last try. If this doesn't cut it I'm out of words.

**Comment by cidylong** [comment]
@lprimak , @svendiedrichsen , Thank you for your advice. 

I had find it from my MacOS local maven repository, location is: /Users/cidylong/.m2/repository/org/primefaces/primefaces/13.0.0/primefaces-13.0.0-jakarta.jar

I will test it later.

**Comment by Elifzeynepedman** [comment]
Greetings @cidylong,

I will close this issue as it seems that there are no errors. If you require further assistance please navigate to [Payara Forum](https://forum.payara.fish).

Best Regards,
Elif

**Comment by cidylong** [comment]
@Elifzeynepedman . Hi Elif. I just tested it again. The issue is still here, I will raise another issue.
