### ISSUE TITLE
Request for payara Forum to have a central community place

### ISSUE THREAD

**Issue by kbachl** [payara/Payara#638]
Hello,

after now having had some time with payara i really find it nice. What I miss is a central place where you can discuss all topics around payara. Therefore I would request to get some kind of forum, maybe to make it easy to start a simple google group?

**Comment by phillipross** [comment]
:+1:

**Comment by smillidge** [comment]
Happy to but will enough people post?

**Comment by kbachl** [comment]
IMHO its not a question of posts - you also can put there sticky topics like: 
- whats special about payara?
- when to use domain1 and when to use payaradomain and the differences between these
etc;

**Comment by kbachl** [comment]
PS: why is c2b2.co.uk routed to a domain seller?

**Comment by smillidge** [comment]
Which url as it works for me?

**Comment by kbachl** [comment]
http://c2b2.co.uk/defaultsite

**Comment by kbachl** [comment]
![c2b2](https://cloud.githubusercontent.com/assets/451927/12698868/cf0a5146-c7a8-11e5-8b54-7da4e3d460af.png)

**Comment by kbachl** [comment]
You seem to have some problem, see DNS trace:

Trace DNS Delegation

Tracing DNS delegation for "c2b2.co.uk":
Loading root server list (static data):
-> a.root-servers.net (198.41.0.4)
-> b.root-servers.net (192.228.79.201)
-> c.root-servers.net (192.33.4.12)
-> d.root-servers.net (128.8.10.90)
-> e.root-servers.net (192.203.230.10)
-> f.root-servers.net (192.5.5.241)
-> g.root-servers.net (192.112.36.4)
-> h.root-servers.net (128.63.2.53)
-> i.root-servers.net (192.36.148.17)
-> j.root-servers.net (192.58.128.30)
-> k.root-servers.net (193.0.14.129)
-> l.root-servers.net (199.7.83.42)
-> m.root-servers.net (202.12.27.33)
Sending request to "k.root-servers.net" (193.0.14.129)
Received referral response - DNS servers for "uk":
-> nsa.nic.uk (156.154.100.3)
-> nsb.nic.uk (156.154.101.3)
-> nsc.nic.uk (156.154.102.3)
-> nsd.nic.uk (156.154.103.3)
-> dns1.nic.uk (213.248.216.1)
-> dns2.nic.uk (103.49.80.1)
-> dns3.nic.uk (213.248.220.1)
-> dns4.nic.uk (43.230.48.1)
Sending request to "nsd.nic.uk" (156.154.103.3)
Received referral response - DNS servers for "c2b2.co.uk":
-> ns-uk.1and1-dns.biz (no IP address)
-> ns-uk.1and1-dns.com (no IP address)
-> ns-uk.1and1-dns.org (no IP address)
-> ns-uk.1and1-dns.co.uk (no IP address)
Attempting to resolve DNS server name "ns-uk.1and1-dns.biz" (details not logged)
Resolved DNS server name "ns-uk.1and1-dns.biz" to IP address 217.160.81.3
Sending request to "ns-uk.1and1-dns.biz" (217.160.81.3)
Received authoritative (AA) response:
-> Answer: A-record for c2b2.co.uk = 54.247.191.20

**Comment by mikecroft** [comment]
RE: having a forum - I can see the benefit. We have Stackoverflow for Q&A, but they're crazy strict about the definition of that, so a really useful question from someone can be closed just because it opens a discussion instead of having a single right/wrong answer.

Stackoverflow has become *the* place for Q&A, though, and there isn't one place I think of when I think "forum". Where would you suggest? Just Google Groups, or are there others?

**Comment by kbachl** [comment]
google groups was just a suggestion - the reason for google would be that usually anyone got some kind of google account and they are quite well vs. spamers.... managing a forum also can be a lot of work and I see a google group as a simple "entry" to start... no one knows how big the interest will be in the end....

**Comment by andreasernst** [comment]
+1

**Comment by davewinters** [comment]
+1. A google group would be very useful. I am sure there are other ways also.

**Comment by Quix0r** [comment]
I'm neutral to this, one way it will give "ordinary" administrators a place to go and ask for community-help, in other way, they may be "scared" of signing up with github? What is your opinion? Are here some admins around?

**Comment by pvdh** [comment]
I don't think it is about being scared by github, but right now I'm wondering "is the problem I'm having an issue?" Feels wrong to raise an issue when I'm wondering about something which might turn out to be an issue but is likely a misunderstanding.
Still searching for the place to ask my questions. ;-)

**Comment by juangon** [comment]
:+1:

**Comment by smillidge** [comment]
We are currently thinking of setting up Gitter what do you think?

**Comment by juangon** [comment]
Hmm as what I see there are no threads in Gitter, so it's more like slack or a chat when everyone talks under the same timeline. IMHO I would prefer a "classic" forum where people creates threads, and then each of them is managed separately, instead of all together (I see it a little bit chaotic).

**Comment by cyberoblivion** [comment]
I just happened on this thread while looking for a forum to post a question to.

http://www.discourse.org/ is pretty amazing just a suggestion.

Currently it is suggested to use Stackoverflow?

**Comment by mikecroft** [comment]
I would love to use discourse, but it's not a particularly viable option for us at the moment. The pricing model they have is too much to justify for us and we just don't have the staff to invest in managing even more infrastructure than we already do.

It's been very high on my list of priorities to have a proper community place for a long time now, to foster discussions and a more back-and-forth style Q&A than StackOverflow. We don't really have anyone who could moderate any forum like that, though, hence our current preference for Gitter.

Opening up a Gitter community would now allow us to have multiple topics, which would probably fit what we need. This doesn't mean that Gitter would be the final and only thing we would have, but it would mean we can always add another forum-style place at a later date as we continue to grow.

**Comment by kbachl** [comment]
Really nice to see my suggestion got so much attention lately. Regarding the "gitter": i had a look at it and I somehow don't see how this translates to a forum like place. They self claim them as "chat and networking platform" and I see them as some kind of web-IRC service IMHO.

I've looked at discourse and some other kind of free hosted forums (e.g.: https://www.proboards.com/ ; https://vanillaforums.com/ ) but they either costs money or they are limited. And I can understand that the amount of resources you want to put into it is limited.

That brings me back to my initial suggestion to use https://groups.google.com - what would be wrong with that? 

PS: can anyone tell me if payara already supports HTTP2?

**Comment by jerrinot** [comment]
:+1: for Google Groups Forum.

**Comment by mikecroft** [comment]
Hello all,

We have created a Google Groups forum. The reason this took so long is that there was no-one to "own" it. To keep the Payara Source code rigidly open source, we, as Payara Services Ltd., don't own the source - we have the Payara Foundation which owns all the rights etc. The Payara Foundation was set up purely as an entity to keep all the legal bits like that separate from us.

As far as the forum was concerned, we felt that it didn't feel "right" for a commercial entity to be running this sort of a community-focused place, so the Payara Foundation, as a not-for-profit entity, felt like the right place to keep it.

We have now launched the [Payara Foundation website](http://www.payara.org/) so now have somewhere to link from.

You can reach the forum from the Foundation's homepage or directly:
https://groups.google.com/forum/#!forum/payara-forum

**Comment by OndrejM** [comment]
@Quix0r, I saw you reacted with a confused emoji :) The legal stuff is also confusing for us, but is necessary.

In simple words, the Payara opensource project (the source code) is now owned by the Payara Foundation, which is similar to e.g. the Apache foundation or the Eclipse foundation, but much smaller.

The foundation website [payara.org](payara.org) is an entry portal for the community resources. You can access all the following from the site:
 - sources (on github)
 - downloadables 
 - documentations (on gitbooks)
 - mailing list / forum (at google groups)

On the other hand, [payara.fish](payara.fish) site is provided by the company, which contribute heavily to the opensource project and provide commercial support. On payara.fish site, you can find much more additional free resources (blog posts, handbooks, ...) and also information about commercial services. But if anything happens to the company, the Payara foundation will still own the source code and most of the resources, so that the opensource project can live on.

**Comment by andreasernst** [comment]
Great news!

**Comment by Quix0r** [comment]
I abused it abit for being sad, because of Google (remember, the NSA scandal?). But well, maybe I'm to paranoid. ;-) And there is a way of a decentralized forum, using Friendica (they are here on Github, too): https://github.com/friendica/friendica/

**Comment by OndrejM** [comment]
OK, I misunderstood :)

To be honest, google groups was also not the first option to us. We had a long internal discussion over all the options. But then we chose google groups because it is easy to manage and for anyone easy to join and follow. Accessibility concerns were finally preferred to security and any other concerns, as this is meant to be an open forum.

**Comment by Quix0r** [comment]
Btw. the website http://www.c2b2.co.uk/ loads fine (some middleware software) here. Seems some DNS problems on @kbachl side.

**Comment by OndrejM** [comment]
The following URL doesn't work though: [http://c2b2.co.uk/](http://c2b2.co.uk/) (cc @smillidge)

**Comment by lprimak** [comment]
Works for me.  Maybe it's a regional DNS issue or a timing issue

**Comment by kbachl** [comment]
@Quix0r and the rest: you are about 11 months too late ;)

**Comment by OndrejM** [comment]
The URL  http://c2b2.co.uk/ now works for me too :+1:

**Comment by OndrejM** [comment]
@kbachl I saw now your question in the comment "can anyone tell me if payara already supports HTTP2?"

The answer is that Payara Server doesn't support HTTP2 yet. However, it might be soon, as Payara uses Grizzly, which already [implements beta HTTP2 support](https://java.net/projects/grizzly/lists/users/archive/2017-01/message/6). We plan to test it in Payara Server and see how we can make it work.

**Comment by kbachl** [comment]
@OndrejM thank you for the update; Meanwhile I went on to reverse-proxy our glassfish with nginx and even there HTTP2 isn't yet as good as it should be; There are still bugs that got fixed recently and the TLS and cipher enforcement lead to problems with various Firefox versions (esp. ESR ones) - so we ended up dropping the usage of http2 now and went back to http1.1....
