### ISSUE TITLE
Bug Report: admin console fails when starting from intellij

### ISSUE THREAD

**Issue by eduarddrenth** [payara/Payara#6387]
### Brief Summary

https://localhost:4848/login.jsf fails to load after starting payara-web 6.2023.8 from intellij 2023.2.1

when starting same payara from netbeans or commandline the admin console loads fine.

configuring in intellij as glassfish or payara server makes no difference

### Expected Outcome

console loading

### Current Outcome

console does not load, browser console shows:
![image](https://github.com/payara/Payara/assets/10200360/594ab5f4-98bf-4a98-906f-bdb357f50c75)

don't know if the google post is the problem, probably not

### Reproducer

change admin password

install intellij with payara plugin, configure payara server, start it, browse to admin console

### Operating System

ubuntu 22.04.3

### JDK Version

17.0.5 from ubuntu

### Payara Distribution

Payara Server Web Profile

**Comment by Elifzeynepedman** [comment]
Hi @eduarddrenth,

Because this is an ecosystem issue, can you raise this on this repo please https://github.com/payara/ecosystem-support/issues?  I will close this issue and support for this will be continued from Ecosystem Support. 

Thanks
