### ISSUE TITLE
ejb-timer-service-app generates timers without being asked

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#639]
Hi,

is there something special about ejb-timer-service-app? It seems to be pre-installed in the server but is not listed when I call "asadmin list-applications" or on the admin console. However, the app seems to generate timers every once in a while. The installed domain is now several months old and on startup I get:

`Loading application [ejb-timer-service-app] at [/ejb-timer-service-app]`
and then
`[107] EJB Timers owned by this server will be restored when timeout beans are loaded`

After another restart I now got:
`[123] EJB Timers owned by this server will be restored when timeout beans are loaded`

I never even used that application and am also not using timers in my application. So I don't know where the timers come from. Is it safe to delete the application from the domain-dir/applications directory?

This is on payara-4.1.152.1

Thanks in advance and best regards,
Chris

**Comment by smillidge** [comment]
You can't remove the EJB Timer application as it is part of the EJB Timer subsystem. The message you are seeing is when the EJB Timer subsystem is loading persistent timers from the database on boot. Something must be adding persistent timer entries to the EJB Timer database to get this message.

**Comment by chrjohn** [comment]
Thank you, I have now identified the source of the timers. They were created in a special part of our application which I did not take into account. Sorry for the confusion. We will now create the timers non-persistent.
If I'm not mistaken I can remove the old timers by connecting to the internal Derby DB?
Thanks

**Comment by smillidge** [comment]
Hi, no problem. Yes you can delete the persistent timers from the internal Derby database.
