### ISSUE TITLE
Bug Report: "add-opens=java.base/java.io" is missing in Micro 6.2023.9/ FISH-7817

### ISSUE THREAD

**Issue by Herr-Sepp** [payara/Payara#6406]
### Brief Summary

Your fix https://github.com/payara/Payara/pull/6371 does not work for Payara Micro.
You need to add it into MANIFEST.MF too.

This is what MANIFEST.MF in Micro 6.2023.9 looks like:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.12
Created-By: 11.0.14.1+1-LTS (Azul Systems, Inc.)
Bundle-SymbolicName: fish.payara.micro
Main-Class: fish.payara.micro.PayaraMicro
Start-Class: fish.payara.micro.impl.PayaraMicroImpl
Add-Exports: java.base/jdk.internal.ref jdk.naming.dns/com.sun.jndi.dn
 s java.naming/com.sun.jndi.ldap
Add-Opens: java.base/jdk.internal.loader java.base/java.lang java.base
 /java.net java.base/java.nio java.base/java.util java.base/sun.nio.ch
  java.management/sun.management jdk.management/com.sun.management.int
 ernal java.base/sun.net.www.protocol.jrt java.base/sun.net.www.protoc
 ol.jar java.naming/javax.naming.spi java.rmi/sun.rmi.transport java.l
 ogging/java.util.logging
```

the "Add-Opens" sections is missing _java.base/java.io_

### Expected Outcome

Start Payara Micro successfull

### Current Outcome

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private static java.lang.ClassLoader java.io.ObjectInputStream.latestUserDefinedLoader() accessible: module java.base does not "opens java.io" to unnamed module @4bbfd6a

### Reproducer

--

### Operating System

--

### JDK Version

17

### Payara Distribution

Payara Micro

**Comment by kalinchan** [comment]
Hi @Herr-Sepp,

I have been able to reproduce this issue and have raised FISH-7817.
