### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by hep-canoy** [payara/Payara#6437]
### Brief Summary

Payara Admin Console on Payara Server 5.2021.8 #badassfish (build 4671) has no JNDI tab.
![image](https://github.com/payara/Payara/assets/102788721/e7745f1a-5484-4e1b-9078-cc89c5ecd712)

I dont have the authority to use new payara, so i am trying to find a way to make JNDI tab appears on the admin console.

### Expected Outcome

I tried to redownload the payara with the same version and it has JNDI
![image](https://github.com/payara/Payara/assets/102788721/8b386243-9fd7-494e-a4e0-330464db727d)

### Current Outcome

This is the "about" page of the payara server along with the admin console
![image](https://github.com/payara/Payara/assets/102788721/31d4894e-a63d-446c-9ff5-311c51469e19)

### Reproducer

It is a special case and does not have a way to reproduce

### Operating System

Linux

### JDK Version

Payara Server 5.2021.8 #badassfish (build 4671)

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @hep-canoy,

Payara Platform 5 Community support has ended, please migrate your environment to Payara Platform 6 and verify if this issue affects its current release.

If you encounter any issues or have trouble transforming your applications and migrating them to Payara Platform 6 and if you want to remain on Payara Platform 5, you may consider acquiring a [Payara Enterprise subscription](https://www.payara.fish/enterprise/).

Best Regards,
Elif
