### ISSUE TITLE
Bug Report: [JDK21] MultiRelease JAR in EAR (with Lucene)/FISH-7959

### ISSUE THREAD

**Issue by ctabin** [payara/Payara#6452]
### Brief Summary

Hello,

We are checking our application (Jakarata EE10 with payara-embedded-all 6.2023.9) with the JDK21. All seems to run smoothly except for [Lucene](https://lucene.apache.org/), which does not find a class during its lookup:

```
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.store.MemorySegmentIndexInputProvider
        at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:807)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:689)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:2869)
        at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:422)
```

All the libraries related to Lucene are included in our EAR.

This works fine with the JDK17 because the *lucene-core* dependency was not a multi-release JAR before JDK19. However, since then there are some classes in `META-INF/versions` and the lookup in Payara fails.

```
META-INF/services/
META-INF/services/org.apache.lucene.analysis.TokenizerFactory
META-INF/services/org.apache.lucene.codecs.Codec
META-INF/services/org.apache.lucene.codecs.DocValuesFormat
META-INF/services/org.apache.lucene.codecs.KnnVectorsFormat
META-INF/services/org.apache.lucene.codecs.PostingsFormat
META-INF/services/org.apache.lucene.index.SortFieldProvider
META-INF/versions/
META-INF/versions/19/
META-INF/versions/19/org/
META-INF/versions/19/org/apache/
META-INF/versions/19/org/apache/lucene/
META-INF/versions/19/org/apache/lucene/store/
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
META-INF/versions/20/
META-INF/versions/20/org/
META-INF/versions/20/org/apache/
META-INF/versions/20/org/apache/lucene/
META-INF/versions/20/org/apache/lucene/internal/
META-INF/versions/20/org/apache/lucene/internal/vectorization/
META-INF/versions/20/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.class
META-INF/versions/20/org/apache/lucene/internal/vectorization/PanamaVectorizationProvider.class
META-INF/versions/20/org/apache/lucene/store/
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
META-INF/versions/21/
META-INF/versions/21/org/
META-INF/versions/21/org/apache/
META-INF/versions/21/org/apache/lucene/
META-INF/versions/21/org/apache/lucene/store/
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
```

### Expected Outcome

The lookup of the classes inside Lucene should work fine.

### Current Outcome

It crashes with a `ClassNotFoundException`.

### Reproducer

You will find a reproducer [here](https://github.com/ctabin/gf-test-lucene).

### Operating System

Linux Debian

### JDK Version

OpenJDK 21

### Payara Distribution

Payara Embedded All

**Comment by ctabin** [comment]
I also checked my reproducer with GlassFish 7.0.9 => this works fine, so it is indeed something related in how Payara handles the ClassLoader of the EAR.

**Comment by shub8968** [comment]
Hi @ctabin,

[As documented](https://docs.payara.fish/community/docs/General%20Info/Supported%20Platforms.html#_supported_java_virtual_machines), currently supported versions for Payara Platform of JDK are JDK 11 and JDK 17.

**Comment by ctabin** [comment]
Hi @shub8968,

Thanks for your feedback. However, let me argue:
- MultiRelease Jar exist since JDK 9. We hit this problem with JDK21, but if Lucene used a MultiRelease JAR prior to JDK17 (event JDK11), the same problem would be hit. Hence, even if the JDK21 is not (yet) officially supported, shouldn't it be fixed anyway ? Any other dependency that provide a MultiRelease JAR with JDK11/JDK17 will generate the same error.
- As far as I can tell, this is the only blocker we have to use Payara with the JDK21 so I guess the official support is not so far away :wink:

I would gladly help and submit a PR to fix this if I can get some hint where to look at.

**Comment by ctabin** [comment]
Hi @shub8968,

As stated, this is not related to JDK21 and I was able to provide a [fix](https://github.com/payara/Payara/pull/6460).
Is it possible to get someone to review it ?
Thanks !

**Comment by breakponchito** [comment]
this is still in progress
