### ISSUE TITLE
Bug Report: [GitHub] Release notes markdown broken

### ISSUE THREAD

**Issue by ctabin** [payara/Payara#6455]
### Brief Summary

Hi,

This is not a bug about Payara itself, I'm just reporting that the [release notes](https://github.com/payara/Payara/releases/tag/payara-server-6.2023.10) since 6.2023.8 are somewhat broken.

### Expected Outcome

The markdown links should be correctly rendered. The proper format should be: `[FISH-7454](https://github.com/https://github.com/payara/Payara/pull/6428) Add --timeout argument to the start-domain command`.

### Current Outcome

The links are broken because `[https://github.com/https://github.com/payara/Payara/pull/6428[FISH-7454]] Add --timeout argument to the start-domain command` is invalid markdown.

### Reproducer

Just check the latest [release notes](https://github.com/payara/Payara/releases/tag/payara-server-6.2023.10) on GitHub.

### Operating System

N/A

### JDK Version

N/A

### Payara Distribution

Payara Server Full Profile

[FISH-7454]: https://payara.atlassian.net/browse/FISH-7454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by felixif** [comment]
Hello @ctabin,

The team has been informed and the issue has been fixed. Thank you for reporting the issue!

Best regards,
Felix

**Comment by ctabin** [comment]
Hi @felixif,

Still, a little [typo](https://github.com/payara/Payara/releases/tag/payara-server-6.2023.11) in the latest release notes (and the worst, the link to my profile :sweat_smile:)

**Comment by JamesHillyard** [comment]
Hi @ctabin - Sorry about that, I've fixed the link again and will raise this as a reccuring issue for our processes to be checked
