### ISSUE TITLE
Bean-pool unexpected behavior

### ISSUE THREAD

**Issue by vkalayda** [payara/Payara#646]
Hi all.

Looks like impossible to control the number of concurrently executed threads on a stateless bean.

Lets consider following case - out application communicate with billing platform, but billing have some limitations - number of concurrent requests (5 for instance).
So, in this case we can to achieve this ("we hope to achieve :)") with bean pool for BillingDelegateBean for instance.

Lets consider following vendor specific "glassfish-ejb-jar.xml" deployment descriptor:

```xml
<?xml version="1.0"`encoding="UTF-8"?>
<!DOCTYPE glassfish-ejb-jar PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 EJB 3.1//EN"`"http://glassfish.org/dtds/glassfish-ejb-jar_3_1-1.dtd">
<glassfish-ejb-jar>
    <enterprise-beans>
        <ejb>
            <ejb-name>BillingDelegateBean</ejb-name>
            <bean-pool>
                <steady-pool-size>2</steady-pool-size>
                <resize-quantity>1</resize-quantity>
                <max-pool-size>5</max-pool-size>
            </bean-pool>
        </ejb>
    </enterprise-beans>
</glassfish-ejb-jar>
```

But it doesn't works at all, no guarantee that will be instantiated only 5 BillingDelegateBean classes by EJB container.

Futhermore, max-wait-time-in-millis was depricated

https://docs.oracle.com/cd/E19798-01/821-1750/beauq/index.html

So it looks like long time ago application server was able to provide this behavior, but it was depricated :(

After googling i found many posts about "How to control the number of concurrently executed threads"
- http://www.adam-bien.com/roller/abien/entry/do_we_need_stateless_session

>  With pools you can throttle the concurrency, because most (all I know) application servers allow you the configuration of max number of instances. You can control the concurrency of every bean type (Boundary) in a fine grained way. This is important for the avoidance of DoS attacks and dealing with legacy resources.
- https://java.net/nonav/projects/glassfish/lists/users/archive/2011-03/message/585

It looks like misunderstanding, because many people expect this behavior, but it dosn't work at all, this is terrible. And i don't know alternative how to solve this problem in EJB - Java EE way.

From glassfish documentation - "GlassFish Application development guide - Pooling and Caching"

> Note that the steady-pool-size and max-pool-size parameters only govern the
> number of instances that are pooled over a long period of time. They do not
> necessarily guarantee that the number of instances that may exist in the JVM at a given
> time will not exceed the value specified by max-pool-size. For example, suppose an
> idle stateless session container has a fully-populated pool with a steady-pool-size of
> 10. If 20 concurrent requests arrive for the EJB component, the container creates 10
> additional instances to satisfy the burst of requests. The advantage of this is that it
> prevents the container from blocking any of the incoming requests. However, if the
> activity dies down to 10 or fewer concurrent requests, the additional 10 instances are
> discarded.

"The advantage of this is that it prevents the container from blocking any of the incoming requests." 

In my opinion this is not advantage, at now this is unexpected behavior, i think container should be able to provide some blocking mechanisms in some cases.

**Comment by vkalayda** [comment]
You can reproduce this behavior with this project 
https://github.com/vkalayda/ee-glassfish-ejb-stateless-limit-pool-size

Execute following command:
> ab -n 100 -c 10 http://localhost:8080/ee-glassfish-ejb-stateless-limit-pool-size/resources/test/invokeDelegate

in console you can see "OVERFLOW" message

Also, i create the same project with WebLogic Server deployment descriptor
> https://github.com/vkalayda/ee-weblogic-ejb-stateless-limit-pool-size

And all works fine on WebLogic server

**Comment by vkalayda** [comment]
The same behavior with Message Driven Bean

**Comment by smillidge** [comment]
Thanks for the ideas. I will mark this as an enhancement request as it will be new functionality. Are you saying you have tested MDBs and they exhibit the same behaviour?

**Comment by vkalayda** [comment]
Yes, with MDB the same situation.

Thank you guys!!!

**Comment by smillidge** [comment]
Thanks for the update

**Comment by abhirockzz** [comment]
As you might already know, EJB pooling is not a standardized feature as such and vendors are free to implement different attributes in different ways. I am surprise this currently does not work in Payara.
Regarding your statement: "And i don't know alternative how to solve this problem in EJB - Java EE way"
There is a way of a achieving this (via Interceptors). [Here is a minimalistic example](https://gist.github.com/abhirockzz/c5d57f1ecb3f20d202bb) (nothing non-standard about this and hence it should be portable)

**Comment by vkalayda** [comment]
Thank you for your comment about this issue.

I review your interceptor and it's OK if you want to put restriction on number of instances. 
But i need achieve behavior when delays will be occurs when no instance in pool to handle request,
i wrote about "max-wait-time-in-millis" for this purpose.

By the way i think if "max-wait-time-in-millis" = 0 then delaying will be occurs until one of instances will be free to handle request.

So i can't call Thread.sleep in accordance to this http://www.oracle.com/technetwork/java/restrictions-142267.html
> create or manage threads

In my opinion i need some options provided by application server to do this.

**Comment by abhirockzz** [comment]
Ok. I noticed in your example, that BillingServer is a Singleton (I am assuming it is so in your actual environment as well) and you have a BillingDelegateBean (which is Stateless) which injects it. Now the problem is that because 'max-wait-time-in-millis' is deprecated, there is no way to 'wait' for availability of an instance of a stateless bean (at least from what I know). There might be other possible solutions which involve handing off the processing to a queue etc., but that would make the process asynchronous.
The only other option I can think of is to be able to invoke the BillingServer directly using CONTAINER managed concurrency and leverage the [@AccessTimeout](http://docs.oracle.com/javaee/7/api/javax/ejb/AccessTimeout.html) annotation. Of course you would need to carefully design your class to and apply appropriate concurrency semantics using [@Lock](http://docs.oracle.com/javaee/7/api/javax/ejb/Lock.html)annotation

**Comment by mikecroft** [comment]
Internal issue id `PAYARA-1065`

**Comment by lprimak** [comment]
Hi, @vkalayda 

I have a production application running and specifying bean-pool for MDBs works as designed.
Now, I have not looked at your project but MDB pool works.  I will try to replicate with ```@Stateless``` soon, but the odds are it will work as well.

**Comment by lprimak** [comment]
@vkalayda I wrote a simple reproducer.  You are right about the @Stateless beans not working correctly.  MDBs do work correctly.  Will try to figure out how to fix the @Stateless bean pool

**Comment by vkalayda** [comment]
@lprimak 

Hello, MDB do not work correctly too. You can see it in VisualVM, number of instances will be higher than in the configuration. 

I will try to provide sample project to reproduce this behaviour on MDB.

**Comment by lprimak** [comment]
@vkalayda number of instances may be higher, but only one instance is dispatched, concurrently at one time, which I have confirmed numerous times.

**Comment by lprimak** [comment]
@vkalayda here is the project I am working with, so we are on the same page: https://github.com/flowlogix/Payara-ejbpool

**Comment by lprimak** [comment]
@vkalayda Indeed the pool functionality works exactly as you described in the initial comment on this issue, which was a surprise to me.  I also thought for years that the number of beans in the pool governed the maximum concurrent request that is processed by the server.

For MDBs, however, this is governed by the JMSRA implementation (and not the pooling code)
so the MDBs work correctly, limiting the number of concurrent message processing MDB instances to the number specified in ```max-pool-size``` element.

**Comment by lprimak** [comment]
With PR #1163 ```max-wait-time-in-millis``` has been de-deprecated. 
As you said, @vkalayda, if its specified and zero, the container will wait for the next instance indefinitely, and otherwise specifies the time to wait for the resource.

This affects maximum concurrent requests, not total number of beans allocated.

**Comment by lprimak** [comment]
I updated https://github.com/flowlogix/Payara-ejbpool to demo the issue

**Comment by lprimak** [comment]
```<max-pool-size>``` controls maximum number of concurrent requests
```<max-wait-time-in-millis>``` has been de-deprecated:
- -1 (default): current behavior is unchanged, unlimited instances can be created, configured amount is cached/pooled
- 0: new behaviour - wait indefinitely for resource to be acquired, only configured amount of beans may be concurrently executed
- 1+: (milliseconds) max wait time to wait for a bean instance, otherwise throw the exception

This behaviour used to exist in GlassFish, but was deprecated because this code got too much of a mess.
I refactored / cleaned it up and was able to re-introduce this feature with minimum fuss.

Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-ejb-jar PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 EJB 3.1//EN" "http://glassfish.org/dtds/glassfish-ejb-jar_3_1-1.dtd">
<glassfish-ejb-jar>
  <enterprise-beans>
    <ejb>
      <ejb-name>PooledStatelessBean</ejb-name>
      <bean-pool>
          <max-pool-size>1</max-pool-size>
          <max-wait-time-in-millis>0</max-wait-time-in-millis>
          <!--<steady-pool-size>1</steady-pool-size>-->
      </bean-pool>
    </ejb>
    <ejb>
      <ejb-name>PooledMDB</ejb-name>
      <bean-pool>
          <max-pool-size>1</max-pool-size>
          <resize-quantity>1</resize-quantity>
      </bean-pool>
    </ejb>
  </enterprise-beans>
</glassfish-ejb-jar>
```
