### ISSUE TITLE
NCLS-DEPLOYMENT-00009 error with embedded v4.1.x and lambda

### ISSUE THREAD

**Issue by zappee** [payara/Payara#647]
Hi,

I have a problem with embedded glassfish server v4.1.x and lambda expression.
Could you please read this topic on [stackoverflow.com](http://stackoverflow.com/questions/35230667/glassfish-embedded-v4-1-1-and-lambda
)?

I tried to use Payara embedded full, but I got same error.
I used this maven dependency:

```
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-embedded-all</artifactId>
    <version>4.1.152.1</version>
    <type>jar</type>
    <scope>test</scope>
</dependency>
```

**Comment by smillidge** [comment]
Any chance you can create a simple project on GitHub as a test case? Does the same EJB jar fail on deploying to Payara Server or just on embedded

The latest Payara Embedded should be 4.1.1.161.

**Comment by zappee** [comment]
Hi,

I have created a simple test application: https://github.com/zappee/lambda-web-demo.git

**Comment by zappee** [comment]
any good news?

**Comment by smillidge** [comment]
Sorry with the 161 release We've not had time to try your test case.

**Comment by smillidge** [comment]
Hi thanks this is reproducible. The jar is failing to deploy on embedded with the Lambda expression. The hidden error is;
`
java.lang.ArrayIndexOutOfBoundsException: 52264 at org.objectweb.asm.ClassReader.readClass(ClassReader.java:2015) at org.objectweb.asm.ClassReader.accept(ClassReader.java:469) at org.objectweb.asm.ClassReader.accept(ClassReader.java:425) at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:145) at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96) at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:336) at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:381) at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:284) at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:130) at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127) at com.megha.testejbproject.NewSessionBeanTest.setUpClass(NewSessionBeanTest.java:28) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164) at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110) at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175) at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
`

**Comment by smillidge** [comment]
should be fixed by #700

**Comment by zappee** [comment]
Does the latest payara-embedded-all-prerelease.jar on Pre-Release Builds download page contains this fix? (http://www.payara.fish/upstream_builds)

I really want to use lambda with embedded Payara.

**Comment by smillidge** [comment]
It's build by our Jenkins and contains everything merged in so it should.

**Comment by zappee** [comment]
I am going to try it. Thx!

**Comment by zappee** [comment]
It works like a charm.
Thanks for the fix.

**Comment by smillidge** [comment]
Good news
