### ISSUE TITLE
Bug Report: unable to connect SSL enabled RDS instance through payara6

### ISSUE THREAD

**Issue by smak03** [payara/Payara#6555]
### Brief Summary

Hi all,
I am using payara 6.2023.9 server for my web application.
As discussed in www.github.com/payara/Payara/issues/5424 - I have SSL enabled RDS instance as well as local db with have_ssl - Yes.
Also we tried to create a connection by adding 
1. Userssl - true 
2. Verify server certificate - true/false
But not succeed yet.

Also, we tried by adding global-bundle.pem file into payara's cacerts.jks but that too not worked.

Apart from that we are using jdk 17
And mysql-connector-java-8.0.29.

Much appropriate if someone can guide me through.

Thanks in advance.

Regards,
Sagar Makwana

### Expected Outcome

I should be able to connect with SSL enabled RDS instance through my web application.

### Current Outcome

Getting below error - 
Internal exception - java.swl.SQLException: Error in allocating a connection. Cause : connection could not be allocated because: Communication link failure.

### Reproducer

Same as mentioned in issue #5424

### Operating System

Linux

### JDK Version

17

### Payara Distribution

Payara Server Full Profile

**Comment by smak03** [comment]
@artur-mal 
Can you please help me for this ?

**Comment by artur-mal** [comment]
Thank you for using the Payara Community Server. We appreciate your feedback and interest in our product.

However, this service is only for reporting bugs in Payara Server that involve fully sustainable reproducers. 

For configuration issues, please seek help on the Payara Community Forum, where you can ask questions and get answers from other users and experts. Alternatively, you can consider a Payara Enterprise Subscription, which offers premium support and services for Payara products.
