### ISSUE TITLE
Using new eclipselink version 4.0.2

### ISSUE THREAD

**Issue by DirkMunder** [payara/Payara#6568]
### Brief Summary

The migration of a Webapplication from 6.2023.3 to 6.2023.4 failed during deployment due to eclipselink version 4.0.1.
New eclipselink version 4.0.2 is available. Upgrade component.

### Expected Outcome

No deployment error.

### Current Outcome

WARNUNG:   Unsupported deployment descriptors element schemalocation value https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd.
SCHWERWIEGEND:   Exception while invoking class org.glassfish.persistence.jpa.JPADeployer prepare method
SCHWERWIEGEND:   Exception while preparing the app
SCHWERWIEGEND:   Exception during lifecycle processing
jakarta.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.1.payara-p1.v202304041433): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [com.eisenbahntechnik.tosPU] failed.
Internal Exception: java.lang.StackOverflowError
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2150)
    at org.eclipse.persistence.internal.jpa.E

### Alternatives

Use 6.2023.3 until component upgrade to version eclipselink version 4.0.2.

**Comment by Elifzeynepedman** [comment]
Hi @DirkMunder ,

Could you please conduct a test using the most recent version of Payara, specifically version 6.2024.2?

Best Regards,
Elif

**Comment by DirkMunder** [comment]
Sorry, I'm not experienced in that.

**Comment by Elifzeynepedman** [comment]
Hi @DirkMunder,

Unfortunately, our support efforts are primarily focused on the most current version of our software. This means we might not be able to provide the detailed assistance you're seeking for version 6.2023.3.  If you upgrade to 6.2024.2, we would be more than happy to assist you.

However, for comprehensive support and solutions tailored to 6.2023.3, you may consider acquiring a [Payara Enterprise subscription](https://www.payara.fish/enterprise/).

Thank you,
Elif
