### ISSUE TITLE
No fish.payara.api:payara-api maven artifact for version 6.2023.11

### ISSUE THREAD

**Issue by jbndbc** [payara/Payara#6574]
### Brief Summary

[Maven repository](https://mvnrepository.com/artifact/fish.payara.api/payara-api) does not contain artifact

`fish.payara.api:payara-api:6.2023.11`

### Expected Outcome

`fish.payara.api:payara-api:6.2023.11` can be used as a dependency in a maven pom.xml

### Current Outcome

`fish.payara.api:payara-api:6.2023.9` is the latest version that can be used as a dependency in a maven pom.xml

### Reproducer

[Maven repository](https://mvnrepository.com/artifact/fish.payara.api/payara-api)

### Operating System

all

### JDK Version

all

### Payara Distribution

Payara Micro

**Comment by pzygielo** [comment]
- #6547

**Comment by artur-mal** [comment]
https://docs.payara.fish/community/docs/Technical%20Documentation/Public%20API/Overview.html

https://mvnrepository.com/artifact/fish.payara.api/payara-bom
