### ISSUE TITLE
Bug Report: Arquillian adapter does not pass system properties to tests

### ISSUE THREAD

**Issue by tandraschko** [payara/Payara#6589]
### Brief Summary

Currently i reactivate all integrationtests of DeltaSpike and it seems that the system properties are available in `@Deployment` but not in the single tests.
In DeltaSpike we pass the CDI container and version to the arqullian tests ("cdicontainer.version" system property) and skip some tests because they are broken in different Weld versions.
For Payara this is done via surefire-plugin:
https://github.com/apache/deltaspike/blob/master/deltaspike/parent/code/pom.xml#L898

### Expected Outcome

Its available in both ln58 and ln79:
 https://github.com/apache/deltaspike/blob/master/deltaspike/modules/partial-bean/impl/src/test/java/org/apache/deltaspike/test/core/api/partialbean/uc008/ClassLevelInterceptorTest.java#L58

### Current Outcome

Its only available in `@Deployment` but not in the single tests.

I even tried to add it additionaly via:

```
    <container qualifier="payara-build-managed">
        <configuration>
            <property name="payaraHome">${arquillian.payara_home}</property>
            <property name="adminPort">24848</property>
            <property name="properties">cdicontainer.version=weld-5.0.1</property>
            <property name="serverSystemProperties">cdicontainer.version=weld-5.0.1</property>
        </configuration>
    </container>
```

### Reproducer

clone deltaspike and run the build via:

`mvn clean install -Ppayara-build-managed`

It should not reach the workaround https://github.com/apache/deltaspike/blob/master/deltaspike/modules/partial-bean/impl/src/test/java/org/apache/deltaspike/test/core/api/partialbean/uc008/ClassLevelInterceptorTest.java#L82
but it does

### Operating System

Windows/Linux

### JDK Version

Correto 17

### Payara Distribution

Payara Server Full Profile

**Comment by lprimak** [comment]
Hi, Thomas,

There is a separate arquillian module available to propagate system properties into the container (and thus remote tests)
```
 <dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>environment-setup</artifactId>
    <version>${payara.arquillian.container.version}</version>
    <scope>test</scope>
</dependency>
```

It uses Arquillian remote extensions to propagate values of property files to remote tests.

For an example, see https://github.com/payara/MicroProfile-TCK-Runners/blob/f0f7cd316a59c359a2d6e4481a2cf7182e449ef2/MicroProfile-Config/src/test/resources/system-properties.properties#L2

Hope this helps.

**Comment by fturizo** [comment]
Greetings @tandraschko,

As mentioned by @lprimak, the `environment-setup` module should help you propagate system properties into the container adapter. We have noticed that this module is not documented in our official Ecosystem tools, so we'll proceed to document its usage for this specific use case.

As there are no follow-up actions, we'll proceed to close this issue.
