### ISSUE TITLE
#505 is not fixed when TxType is REQUIRES_NEW

### ISSUE THREAD

**Issue by MasatoshiTada** [payara/Payara#667]
I'm very happy with Payara 4.1.1.161 released.
I wrote issue https://github.com/payara/Payara/issues/505 .
I tried Payara 4.1.1.161, and I saw this bug is fixed when TxType is `REQUIRED`.

But, it seems this bug is NOT fixed when TxType is `REQUIRES_NEW`.
Could you try my test program again?
https://github.com/MasatoshiTada/TransactionalSample-Doma/blob/master/src/main/java/com/example/jdbc/JdbcCdiRequiresNewTestDao.java

**Comment by mikecroft** [comment]
Hi, thanks for raising that again, we'll take a look.

**Comment by smillidge** [comment]
This is reproducible but only when using a Datasource. When used with a JPA EntityManager the transaction is rolled back correctly.

**Comment by MasatoshiTada** [comment]
Thank you so much!
