### ISSUE TITLE
Update payara-arquillian-container.version to 3.0 in pom.xml

### ISSUE THREAD

**Issue by stbischof** [payara/Payara#6722]
### Brief Summary

pom.xml uses payara-arquillian-container version to 3.0.alpha6 should be updates to latest released non alpha version

### Expected Outcome

updated to released payara-arquillian-container version 3.0

### Current Outcome

non

### Alternatives

3.0.alpha7
3.0.alpha8

**Comment by Elifzeynepedman** [comment]
Hi @stbischof,

I successfully tested payara-arquillian-container version 3.0, and it works seamlessly on my end.

Could you please provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Thank you,
Elif

**Comment by stbischof** [comment]
PR:

https://github.com/payara/Payara/pull/6723


Sorry but i can't and will not visit a site witu an invalid https certificate.

Sind we are talking about updating your own dependencies i am a but surprised about what you are expecting

**Comment by Elifzeynepedman** [comment]
Hi @stbischof,

Many thanks for your contribution.

To process your contribution we require that you fill out and sign the official Contributor License Agreement (CLA) as per our [contribution policies](https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md). Please download the [CLA form](https://github.com/payara/Payara/blob/master/PayaraCLA.pdf) and submit it to cla@payara.org as soon as possible. 

Once the document is processed by our legal team, we’ll continue with the review of your contribution.

Thank You,
Elif
