### ISSUE TITLE
Problems on deployment of OSGi hybrid bundles (ClassNotFoundException - IIOPSSLSocketFactory)

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#673]
Please see attached minimal MDB. Works on payara 4.1.152.1 but fails on 4.1.1.161
It works when deployed as normal JAR, but deployed as OSGi bundle there are exceptions thrown (same as in #516 and #535)

Deployment with:
`asadmin deploy --type osgi payarabug-0.0.1-SNAPSHOT.jar`

NB: it also works when first deploying as normal JAR, then undeploy, then deploy as OSGi bundle. So please deploy to a freshly started instance.

Prerequisites: you need to have a connection factory and test queue:
`asadmin create-jms-resource --restype=javax.jms.QueueConnectionFactory --enabled=true ConnectionFactory`
`asadmin create-jms-resource --restype=javax.jms.Queue --enabled=true queue/test`

The bean is just this:
```
package payarabug;

import javax.annotation.Resource;
import javax.ejb.MessageDriven;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.QueueConnectionFactory;

@MessageDriven( mappedName = "queue/test" )
public class PayaraBugMDB
    implements MessageListener {

    @Resource( name = "ConnectionFactory" )
    private QueueConnectionFactory queueConnectionFactory;

    

    public void onMessage( final Message msg ) {
        System.out.println( "XXX onMessage()" );
    }

}

```

Attached is the JAR file (renamed as ZIP).
[payarabug-0.0.1-SNAPSHOT.zip](https://github.com/payara/Payara/files/140753/payarabug-0.0.1-SNAPSHOT.zip)

**Comment by smillidge** [comment]
Confirmed this is caused by #552. #552 was to prevent classloader leaks when bootstrapping the ORB. ORB threads inherit the current context classloader.

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please
