### ISSUE TITLE
virtual server default web app doesn't work with root context until virtual server is disabled and reenabled.

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara#674]
1. Create a virtual server
2. Deploy an EAR (may need multiple WARs inside)
3. Set a WAR within the EAR to be the default web app
4. The root context doesn't load and the WAR only loads when you go to its web.xml configured context root
5. Disable/enable the virtual server (without restarting the actual server)
6. The root context now works correctly.

Only tested in GF 4.1.1

**Comment by fturizo** [comment]
@mikecroft , any progress on this issue?

**Comment by mikecroft** [comment]
No progress yet, @fturizo, I've assigned @michaelranaldo since I think he'll have more time to try to reproduce the issue.

**Comment by MattGill98** [comment]
Unless I'm doing something wrong, it seems to work for me. These are the commands I used:

Create the virtual server:
`create-virtual-server --hosts=${com.sun.aas.hostName} test`

Configure protocols for new listener:
`create-protocol test-listener-protocol`
`create-http --defaultVirtualServer=test test-listener-protocol`

Create listener:
`create-network-listener --protocol=test-listener-protocol --listenerport=5050 --enabled=true test-listener`

Deploy application:
`deploy /home/matt/git/reproducer/ear-test.ear`

Set default application from ear:
`set configs.config.server-config.http-service.virtual-server.test.default-web-module=ear-test#ear-test-web-1.0-SNAPSHOT.war`

Application deploys as default context root on localhost:5050.

**Comment by mikecroft** [comment]
Good enough for me! :+1:
