### ISSUE TITLE
Bug Report: Schema2BeansProcessor in payara-web does not support JDK 17

### ISSUE THREAD

**Issue by Jle-github** [payara/Payara#6748]
### Brief Summary

After updating the maven-compiler-plugin from version 3.8.1 to 3.13.0 using JDK17 the compiler shows a warning:
LEVEL: WARNING, MESSAGE: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.schema2beansdev.Schema2BeansProcessor' less than -source '17'

For me it looks like that org.netbeans.modules.schema2beansdev.Schema2BeansProcessor does only support JDK7 as its annotated with "@SupportedSourceVersion(SourceVersion.RELEASE_7)".
This problem only occurs if i add fish.payara.extras:payara-embedded-web:6.2024.5 to a maven project and configure the maven-compiler-plugin in pom with version 3.13.0.

### Expected Outcome

The class org.netbeans.modules.schema2beansdev.Schema2BeansProcessor supports JDK 17 and no compiler warning is shown using fish.payara.extras:payara-embedded-web:6.2024.5 as dependency.

### Current Outcome

maven-compiler-plugin with version 3.13.0:
LEVEL: WARNING, MESSAGE: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.schema2beansdev.Schema2BeansProcessor' less than -source '17'

### Reproducer

Create a new maven based project and add fish.payara.extras:payara-embedded-web:6.2024.5 as dependency.
Use JDK 17 for compiler and the maven-compiler-plugin with version 3.13.0

### Operating System

Windows 10 Pro

### JDK Version

OpenJdk 17

### Payara Distribution

Payara Embedded Web

**Comment by artur-mal** [comment]
I couldn't reproduce the issue.
Could you share your reproducer? Also, are you using an IDE or the command line to compile your project?

**Comment by Jle-github** [comment]
Hi, here are the steps to reproduce it:
1) Install OPEN JDK 17
2) Install Maven 3.9.7
3) mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5
4) Add this dependency to your pom.xml:
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-embedded-web</artifactId>
    <version>6.2024.9</version>
</dependency>

5) mvn clean install -DskipTests

Now in the build logs you will find this warning:
"[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.schema2beansdev.Schema2BeansProcessor' less than -source '17'"
