### ISSUE TITLE
Cannot find resource bundle com.sun.logging.enterprise.resource.corba

### ISSUE THREAD

**Issue by quipsy-karg** [payara/Payara#678]
Since we moved from Payara 4.1.1.154 to 4.1.1.161 the following message appears in ACC's console:

```
Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.corba for class org.glassfish.enterprise.iiop.impl.GlassFishORBManager using java.net.URLClassLoader@1d44bcfa
```

**Comment by jjeennddaa** [comment]
Same problem (payara 4.1.1.161.1):
Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.corba for class org.glassfish.enterprise.iiop.impl.GlassFishORBManager using org.glassfish.main.orb.iiop [25]

**Comment by niblings** [comment]
I also found the same message (payara 4.1.1.161.1)
```
SEVERE|Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.corba for class org.glassfish.enterprise.iiop.impl.GlassFishORBManager using org.glassfish.main.orb.iiop [222]
SEVERE|Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.resourceadapter for class org.glassfish.resources.javamail.deployer.MailResourceDeployer using org.glassfish.main.resources.javamail-runtime [136]
SEVERE|Cannot find the resource bundle for the name com.sun.logging.enterprise.system.core.naming for class org.glassfish.resources.javamail.naming.MailNamingObjectFactory using org.glassfish.main.resources.javamail-runtime [136]
SEVERE|Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.resourceadapter for class org.glassfish.resources.deployer.CustomResourceDeployer using org.glassfish.main.resources.runtime [252]
SEVERE|Cannot find the resource bundle for the name com.sun.logging.enterprise.system.core.naming for class com.sun.enterprise.container.common.impl.JavaModuleNamingProxy using org.glassfish.main.common.container-common [62]
```

**Comment by OndrejM** [comment]
The error messages seem to be related to fixing and heavy refactoring of Payara logging mechanism in #502. There is still some more work to do to finish fixing the logging mechanism.

However, the error messages might also indicate problems in other subsystems of Payara server, which were not visible before. The refactoring in logging mechanism turned on logging SEVERE messages for inconsistent states, and the above messages are given exactly for these cases.

**Comment by OndrejM** [comment]
After deeper analysis, the errors are not critical at all, probably should be only warnings or even fine priority. They just mean that a translation bundle has not been found for given logger. At worst case a translation for a specific key is not found, potentially leading to confusing error messages.

@dmatej, as you contributed fixes to issue #502, may you have a look into the error messages in this issue? There are probably some missing message bundles for log messages.  Meantie, maybe we can at least lower the severity of the messages?

**Comment by dmatej** [comment]
@OndrejM There were many similar problems even before. I have fixed only several of them, those that I have seen. I don't have an idea how to check all bundles and their dependencies because everything depends on actually used classloader. Maybe if many people contributed and wrote many many tests ...

I think the best philosophy is to use only bundles in the same package. It seems to me that root of all problems is recent continuous refactoring and moving classes from package to package, but bundles were still on the same place.

These things should be fixed iteratively one by one.
My code only allowed to provide mechanism how to get to bundle in another package and visible for another classloader.

**Comment by OndrejM** [comment]
@dmatej The logging system is really not in a good shape. I appreciate all the work you've done in an effort to improve it. Payara team will continue with the improvements, although additional help from the community is always welcome :)

There was only a small nuisance with error messages added lately, as they had too high severity and started confusing others. smillidge just lowered their severity to INFO.

**Comment by dmatej** [comment]
I have seen, but it is really an error. The solution is not so complicated, but it takes too much time. Look at the #714 - I have fixed another bunch of logs (and I hope it is without bugs).
I do fulltext search for all message keys in bundle, move them where they are used, sometimes I remove some hack someone did to get the right message.

The error message means that the bundle was not found, file does not exist in any expected subtree.
I know it is unpleasant for the users, but it seems to me like an empty catch block if you lower the level :-) (okay, I know, there are more acute problems)
