### ISSUE TITLE
Enhancement: TOML Config Source for MicroProfile Config /FISH-9198

### ISSUE THREAD

**Issue by poikilotherm** [payara/Payara#6822]
### Brief Summary

I would like to be able to use a TOML file as a source for configuration values. This is a standard feature for SmallRye and should be included in Payara, too.

### Expected Outcome

Just configure a source and read away that TOML file!

### Current Outcome

I'm stuck with adding such a config source to the application, which does not allow me to provide values for early init stuff like `${MPCONFIG=...:...}` variable replacements.

### Alternatives

Implement a fake JDBC driver to read TOML files. 

[Been there, done that: gdcc/jdbc-conffile-driver](https://github.com/gdcc/jdbc-conffile-driver) Works, but is hacky. Also: a config source that reads a local file can be updated on change and doesn't need 60 secs default caching! But this will require more control over what's going on, which is just not possible with the JDBC workaround.

### Context

As with the DirConfigSource (#5006 / #5007), I would be willing and able to create a pull request and donate the necessary code. If accepted, we should talk about the location for this config source (`fish.payara.microprofile.config.extensions` vs `fish.payara.nucleus.microprofile.config.source`) and potentially about using a different caching strategy for it.

**Comment by artur-mal** [comment]
The proposed enhancement has been submitted for an open vote.

**Comment by poikilotherm** [comment]
Hi @artur-mal !

It looks like this is a community wanted feature with 22 votes ATM.

What are the next steps? Is a community contribution welcome?

Cheers,
Oliver

**Comment by Pandrex247** [comment]
We've raised an internal issue to track this enhancement with the ID of FISH-9198.

**Comment by DS-INRAE** [comment]
Hello, @Pandrex247 are there any news on the status or priority of this enhancement ? :slightly_smiling_face:

**Comment by kalinchan** [comment]
This is currently being implemented and is targeted to be in the 6.2024.11 release.

**Comment by poikilotherm** [comment]
Great news! Keep up the good work! Woohoo! 🥰🥳

**Comment by kalinchan** [comment]
Hi @poikilotherm, I have made the PR to support TOML, feel free to test the changes. 😄
