### ISSUE TITLE
Bug Report: Incorrect payara instance status

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#6912]
### Brief Summary

We have payara DAS server with one instance. We execute instance start, either on CLI or GUI:
`
[glassfish@napmst08 payara5.2022.3]$ /opt/glassfish/productionTvRcv/payara5.2022.3/payara5/glassfish/bin/asadmin --port 4848 --user admin --passwordfile /opt/glassfish/productionTvRcv/payara5.2022.3/payara5/glassfish/bin/passwordFile start-instance napmst08_instance
Waiting for napmst08_instance to start ...............
Successfully started the instance: napmst08_instance
instance Location: /opt/glassfish/productionTvRcv/payara5.2022.3/payara5/glassfish/nodes/napmst08_node/napmst08_instance
Log File: /opt/glassfish/productionTvRcv/pms/logs/instance_server.log
Admin Port: 24848
Command start-local-instance executed successfully.
The instance, napmst08_instance, was started on host 126.201.150.172
Command start-instance executed successfully.
`

The log confirms:
```
2024-08-27 13:55:30 INFO   [com.sun.enterprise.v3.admin.cluster.NodeUtils runAdminCommandOnNode] Waiting for napmst08_instance to start ...............
Successfully started the instance: napmst08_instance
instance Location: /opt/glassfish/productionTvRcv/payara5.2022.3/payara5/glassfish/nodes/napmst08_node/napmst08_instance
Log File: /opt/glassfish/productionTvRcv/pms/logs/instance_server.log
Admin Port: 24848
Command start-local-instance executed successfully.
```
But the GUI still reports instance to be down:

![obraz](https://github.com/user-attachments/assets/c31554b2-9ba3-4f75-bd98-aab3579310c2)

We are not sure that this is really an issue, maybe it is misconfig. But there are no error logs in DAS server.log, so I would be grateful for help on this topis. How DAS is checking the instance status?

### Expected Outcome

GUI reporting instance do be UP.

### Current Outcome

GUI reporting instance do be DOWN.

### Reproducer

Don't have it now.

### Operating System

EuroLinux 9.4

### JDK Version

zulu17.34.19-ca-jdk17.0.3-linux_x64

### Payara Distribution

Payara Server Full Profile

**Comment by artur-mal** [comment]
Could you attempt to reproduce the issue using the latest Payara Community version (6.2024.8)?

**Comment by peterpz1** [comment]
We already have diagnoze and the fix. Issue was server misconfig in the routing table, which prevented Payara from proper communication with the instance (instance is the SSH one). But I still have some doughts:
1. PING in the node was working OK, so I thought that network is ok.
2. This causes me to think that instance status is checked using totally different method and SSH might be working, but still establishment of the instance status might be distrubed.
3. I'm not sure that the errors in comunication should all be mapped to the DOWN status of the instance without any logs / warnings on gui.
