### ISSUE TITLE
CDI 1.0 / 1.1 - can it be switched into payara?

### ISSUE THREAD

**Issue by kbachl** [payara/Payara#692]
Hello,

I hope that hijacking the issues is ok for this topic. We, as many others, are still on GF3 and can't simply migrate to GF4/ Payara as our app uses CDI deeply... sadly CDI 1.0 / 1.1 / 1.2 are not very comptabile meaning e.g. we would need a new seam solder etc. 

While the upgrading of our apps will still take some time I wondered if it would be possible to replace the current weld version with a weld 1.1.x one in payara?

Or is weld used by payara internally?

Best, KB

**Comment by smillidge** [comment]
Weld isn't used by Payara internally, in that none of the server code uses Weld. However I have know idea whether you can just replace the JBoss Weld version without any other code changes in the server. Try it and let me know how you get on.

**Comment by kbachl** [comment]
ok, I tried to replace the weld-osgi bundles as well as the integration bundles; but it seems other osgi bundles depend on weld 2.2 and have a reqirement for weld > 2.2.0 baked in;

so it is not possible to downgrade the CDI implementation
