### ISSUE TITLE
GFFileHandler: dont call rotate() before getting maxHistoryFiles (PAYARA-1105)

### ISSUE THREAD

**Issue by dreamIt-de** [payara/Payara#696]
We have a custom formatter:
com.sun.enterprise.server.logging.GFFileHandler.formatter=com.acme.logformat.JsonFormatter
and 
com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles=0

At startup of the payara, the log file is rotated before maxHistoryFiles is evaluated and the default value of 10 is taken. This results in old log files to be deleted.
The rotation is called from GFFileHandler.java:392
We have the requirement to store all log files for some years.

We use payara-4.1.152.1

**Comment by OndrejM** [comment]
Hi @dreamIt-de,
I'm sorry for a late response.
I was finally able to reproduce this issue finally. Payara server forces file rotation when it detects a custom log formatter, and this is before the configuration is completely loaded.

We're you able to work around the problem meantime?
We will try to fix this, but if you are able to help with a pull request or any helpful information, we would appreciate it!

**Comment by dreamIt-de** [comment]
Hi @OndrejM Thank you for looking into the issue. 
At the moment we are working around the issue with a cron job which moves the log files in an other directory before the glassfish deletes them.
