### ISSUE TITLE
Can one of the admins verify this patch?

### ISSUE THREAD

**Issue by kingjay66** [payara/Payara#6999]
Can one of the admins verify this patch?

_Originally posted by @payara-ci in https://github.com/payara/Payara/issues/1109#issuecomment-249413680_

**Comment by kalinchan** [comment]
What is the issue?

**Comment by fturizo** [comment]
@kingjay66, please refrain from opening issues unrelated to bug reports or enhancement requests in the future. 

We're not sure why you raised this issue that references an 8-year-old pull request, but if you want to make an official report of the bug that the PR solved please do so using the official template.
