### ISSUE TITLE
$AS_INSTALL_LIB/endorsed directory not created

### ISSUE THREAD

**Issue by FireballDWF** [payara/Payara#701]
$AS_INSTALL_LIB/endorsed directory exists for glassfish 4.1.1 but not in Payara+4.1.1.161
Does Payara change where replacements for endorsed files should go?  Omitted by mistake?  Or on purpose?

**Comment by smillidge** [comment]
Hi. 

Endorsed jars are configured in the domain.xml to be here;
```shell
-Djava.endorsed.dirs=${com.sun.aas.installRoot}/modules/endorsed${path.separator}${com.sun.aas.installRoot}/lib/endorsed
```

I'm not sure why the Payara install doesn't have the ${com.sun.aas.installRoot}/lib/endorsed directory it's not by design so you can still add jars in there if needed.

**Comment by OndrejM** [comment]
I suppose that `endoresed` directory is not inside Payara server installation because it is empty and git does not version empty directories. Glassfish is versioned in SVN, which does store empty directories. But the functionality should be the same, as @smillidge already confirmed.
