### ISSUE TITLE
Payara not showing modules for versioned application PAYARA-670

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#702]
Mostly related to #455 and slightly #445.
Glassfish is not able to list the deployed modules when using versioned applications.
See the attached screenshots:
![versioneddeployment](https://cloud.githubusercontent.com/assets/2928922/13747256/b24e480c-e9f7-11e5-85f2-1bd3b6fb0168.PNG)
expected:
![expected](https://cloud.githubusercontent.com/assets/2928922/13747258/b35186a6-e9f7-11e5-8e6a-3dc8c50933ac.PNG)

I was wondering, if this is not a simple path mistake? Note the different between the colon in the application's name, and the ~ (tilde) that is used in the app's path on the filesystem.

**Comment by devyoustice** [comment]
#461 seems to be duplicate (and sorry, i forgot about that one). I do think we've got more relevant information here, than there. As #461 also deals with lost requests, I suggest to focus on the lost request as part of #461 and with components/monitoring as part of this issue.

**Comment by ratcashdev** [comment]
#461 seems to be duplicate (and sorry, i forgot about that one). I do think we've got more relevant information here, than there. As #461 also deals with lost requests, I suggest to focus on the lost request as part of #461 and with components/monitoring as part of this issue.

**Comment by ratcashdev** [comment]
Couple of findings:
1. The component listing seems to be just a GUI problem, because the REST management services work find. E.g. 
`GET http://localhost:4848/management/domain/applications/application/versionedSampleApp:1/list-sub-components` works just fine and I get the necessary components

2. The json response from the REST resource includes the following:
```
"commandLog": [
            "list-sub-components --modulename versionedSampleApp:1"
        ]
```
whereas the correct command-line is:
`asadmin list-sub-components --appname="versionedSampleApp:1" versionedSampleApp` i.e. without the ":1" version suffix, and without --modulename (the latter being not even understood by the cli)

This hints to the fact that the GUI is not propely stripping the version from the app-name when used as module-name.

However, it also seems that for different REST endpoints, the expected style of the module-name is varying. 
Examples:
* AppUtil.getSnifferListOfModule(), that is `/applications/application/{appName}/module/{moduleName}`  expects the appName and the moduleName both with the version included.
* ApplicationHandlers.getSubComponents(), that is `/applications/application/{appName}/get-context-root.xml?modulename={moduleName}` expects the appname with version and the moduleName w/o version
* ApplicationHandlers.getSubComponentDetail(), that is `/applications/application/{appName}?appname={appName}&id={moduleName}` expects the appname with version and the moduleName w/o version

**Comment by ratcashdev** [comment]
For now, I can see two different approaches to fix this:
1. Fix the REST clients. Currently identified 2 files, ApplicationHandlers and MonitoringHandlers.java. However, it's clear there will be more, somewhere in .inc files the usage of which is beyond me, unfortunately.
2. Fix the REST resources so that they properly strip out the version suffix from the moduleName where needed. This may be a simpler approach with less hunting.

**Comment by ratcashdev** [comment]
One more possibility is to ensure that the contents of the `HandlerContext` is properly set up (that is, moduleNames won't contain version suffixes), but given the various expectations of the REST services, that may not be such a good idea, after all.

**Comment by ratcashdev** [comment]
It seems also some of the REST resources responses contain invalid values. Specific case:
`management/domain/applications/application/{appName}:1/module`
returns the following:
```
{
    "message": "",
    "command": "module",
    "exit_code": "SUCCESS",
    "extraProperties": {
        "commands": [],
        "methods": [
            {
                "name": "GET"
            },
            {}
        ],
        "childResources": {
            "{appName}:1": "http://localhost:4848/management/domain/applications/application/{appName}:1/module/{moduleName}:1"
        }
    }
}
```

**Comment by ratcashdev** [comment]
The linked pull request is basically approach No2: "Fix the REST resources so that they properly strip off the version suffix from the moduleName where needed."

**Comment by smillidge** [comment]
Thanks for all the work and analysis
