### ISSUE TITLE
Bug Report: Please update mojarra version / FISH-9992

### ISSUE THREAD

**Issue by mnyakushev** [payara/Payara#7025]
### Brief Summary

There is bug in `Mojarra 4.0.7.payara-p1` included in last version of Payara Server CE (6.2024.10 from Oct 09, 2024).
https://github.com/eclipse-ee4j/mojarra/issues/5512

Please update mojarra version.

### Expected Outcome

Mojarra version updated.  Bug https://github.com/eclipse-ee4j/mojarra/issues/5512 fixed

### Current Outcome

Bug is present in last version of Payara Server CE (6.2024.10 from Oct 09, 2024).

### Reproducer

Reproducer from this issue https://github.com/eclipse-ee4j/mojarra/issues/5512

### Operating System

Windows 11

### JDK Version

Java version: 21.0.4, vendor: BellSoft

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @mnyakushev,

I was able to reproduce the issue and I have escalated this to the platform development team as `FISH-9992`.

Thank you,
Elif
