### ISSUE TITLE
Bug Report: ClassLoader leak when Timer Service is used

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#7078]
### Brief Summary

I have noticed that any application that uses `@Scheduled` or programmatic equivalents,
basically any application that touches `TimerService` doesn't unload properly, caused by `ClassLoader` leak

### Expected Outcome

Application undeploys cleanly

### Current Outcome

Leaks are detected

### Reproducer

Not yet.

### Operating System

Any

### JDK Version

Any

### Payara Distribution

Payara Server Full Profile, Payara Server Web Profile, Payara Micro, Payara Embedded All, Payara Embedded Web, Payara Docker Image

**Comment by lprimak** [comment]
I will see if I can provide a PR for this

**Comment by felixif** [comment]
Hello @lprimak,

Thank you for reporting this issue. As there is no reproducer, I will wait for the PR to be made and afterwards I will close this issue, as the issue will be tracked via the PR itself.

Thank you again for contributing to the source code!

Have a great day,
Felix Ifrim

**Comment by felixif** [comment]
Hello @lprimak,

I see that the [PR](https://github.com/payara/Payara/pull/7032) made for #7031 contains the fix for this issue as well. So, if the fix is there, I will mark this issue as accepted, close it, and continue the discussion about both bug fixes on the PR itself.

Thank you,
Felix
