### ISSUE TITLE
Enhancement: Payara should use Jandex to speed up CDI deployments

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#7079]
### Brief Summary

CDI deployment speed could use improvement

Jandex is much faster than using class scanning, because it's done at build time and can be cached.
Using Jandex could speed to deployment by orders of magnitude.
Jandex indexes should be used and / or cached for all internal Payara CDI extensions

### Expected Outcome

Jandex is used for all CDI modules, including internal ones.

### Current Outcome

Jandex is not used

### Alternatives

None

**Comment by artur-mal** [comment]
The proposed enhancement has been submitted for an open vote.

**Comment by lprimak** [comment]
I'll probably get a PR going on this one as well

**Comment by artur-mal** [comment]
@lprimak , could you kindly confirm if you plan to implement the enhancement you suggested?
If so, I will proceed with closing this issue.

**Comment by lprimak** [comment]
Yes, this will be my last one for the year :)

**Comment by artur-mal** [comment]
Thank you for the confirmation.

**Comment by lprimak** [comment]
I have started working on this issue.
It's way too early for a PR, but you can follow progress on at https://github.com/flowlogix/Payara/tree/jandex-deploy

https://github.com/flowlogix/Payara/tree/jandex-deploy

**Comment by lprimak** [comment]
If anyone is interested to try a (very) early version with deploy optimizations, you can download a build here: https://nexus.hope.nyc.ny.us/repository/maven-releases/fish/payara/distributions/payara/6.2025-jandex-4/payara-6.2025-jandex-4.zip

**Comment by lprimak** [comment]
Update on the progress:

Dependencies of this issue ballooned from a 3-day project to a 8-month behemoth. What this means is that I won't have any time to work on this til probably 2026 or later.
I am going to put this work on hold to more concentrate on some strategic things that I need to do.
If anyone is interested to accelerate this work, please contact me to discuss.

Just to reiterate, I am not going abandon this (I never abandon anything) but currently the timing issues are not in this issues favor.
