### ISSUE TITLE
useBundledJSF flag makes ServletContainerInitializer get an empty class set and breaks Mojarra 2.2.11 and up

### ISSUE THREAD

**Issue by ubench-tdv** [payara/Payara#710]
We tried updating our Mojarra version in our application from 2.2.10 to 2.2.12. I was surprised that the application did not work anymore after the update. 

Digging a little deeper into the code it seems that from Mojarra version 2.2.11 (+) the Mojarra library does not handle the annotation scanning by itself anymore but relies on the container to provide the classes which contain annotations.

In 2.2.10, it was

`
 public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls) {
 if (null == scanner)
 { scanner = new JavaClassScanningAnnotationScanner(sc); }
 return scanner.getAnnotatedClasses(urls);
 }
`

In 2.2.11, it is:
`
public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls)
{ HashMap<Class<? extends Annotation>, Set<Class<?>>> annotatedMap = new HashMap<Class<? extends Annotation>, Set<Class<?>>>(); createAnnotatedMap(annotatedMap, (Set<Class<?>>) sc.getAttribute(ANNOTATED_CLASSES)); return annotatedMap; }
`

Where ANNOTATED_CLASSES is set in the FacesListener:

`public void onStartup(Set<Class<?>> classes, ServletContext servletContext)`

Following the discussion on https://java.net/jira/browse/JAVASERVERFACES-3957. The Mojarra team clearly states: " it should be passing in a non empty set of classes."

When the flag "useBundledJSF"  in glassfish-web.xml is set to true, the set of classes is empty and this has the effect that no annotated bean can be found.

**Comment by OndrejM** [comment]
Hi,

Are you trying to deploy an application with a newer version of Mojarra packaged inside your application?
It seems that Mojarra 2.2.11 does not support that out of the box and requires to initialize it with a set of classes. This is not an issue with Payara server. Mojarra team clearly decided that mojarra requires to supply the set of classes instead of doing it itself.

It should be possible to retrieve set of annotated classes from CDI bean manager and pass it to mojarra. If you give me some time, I can provide you more hints how to do it.

**Comment by ubench-tdv** [comment]
Hi,

Thank you for having a look at this.

If you look at the API on 

'https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContainerInitializer.html'

it says:

    'c - the Set of application classes that extend, implement, or have been annotated with the class types specified by the HandlesTypes annotation, or null if there are no matches, or this ServletContainerInitializer has not been annotated with HandlesTypes'

If you look at the source of FacesInitializer in Mojarra 2.2.12 you can see the following HandleTypes are registered:

'@HandlesTypes({
      ManagedBean.class,
      FacesComponent.class,
      FacesValidator.class,
      FacesConverter.class,
      FacesBehaviorRenderer.class,
      ResourceDependency.class,
      ResourceDependencies.class,
      ListenerFor.class,
      ListenersFor.class,
      UIComponent.class,
      Validator.class,
      Converter.class,
      Renderer.class,
      FacesBehavior.class,
      PhaseListener.class,
      FaceletsResourceResolver.class,
      Resource.class,
      NamedEvent.class
})
'
So it should not pass an empty set of classes.

Now to answer your questions.

In my test I used the same version of Mojarra in my .WAR as it is on the path under glassfish\modules (2.2.12). When I replace \glassfish\modules and the library in my .WAR with the 2.2.10 version everything works fine. The reason I'm using glassfish-web.xml with:

'
<property name="useBundledJsf" value="true" />
<class-loader delegate="false" />
'

is that it also needs to be deployed on Glassfisg 3.1.2.14. Up until Mojarra 2.2.10 this works fine. I didn't test it with CDI, I used the JSF annotations:

'
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "myBean")
@ViewScoped
...
'

**Comment by mulderbaba** [comment]
@OndrejM & @ubench-tdv 
[Attached](https://github.com/payara/Payara/files/190642/annotation-class-scan.zip) is the project source for the reproducer. After deploying the war built from it, request for: localhost:8080/annotation-class-scan-1.0-SNAPSHOT/index.jsf. You should be seeing Mojarra version printed on the page. 
When you upgrade the Mojarra dependency to 2.2.11, you will see the version is going to disappear.
I think I might have a solution for this, will keep you guys posted.

**Comment by mikecroft** [comment]
Internal defect ID - `PAYARA-718`

**Comment by ubench-tdv** [comment]
Dear,
  
 I will not be in the office until Monday the 11th of April.
  
 For urgent issues, please contact servicedesk@ubench.com.
  
 Regards,
  
 Tim De Vos

**Comment by smillidge** [comment]
Fixed by #727
