### ISSUE TITLE
Bug Report: Broken Link on Payara Community 6.2024.12 Release Notes

### ISSUE THREAD

**Issue by mpredli01** [payara/Payara#7144]
### Brief Summary

This link, https://docs.payara.fish/community/docs/Release%20Notes/Release%20Notes%206.2024.12.html, results in a 404.  This is odd because previous links corresponding to the release notes have worked in the past (I write a paragraph on the Payara Platform monthly release in my InfoQ Java weekly news roundups).

After doing some digging, I came across this link: https://docs.payara.fish/community/docs/6.2024.12/Release%20Notes/Release%20Notes%206.2024.12.html.  Notice the extra 6.2024.12 in the middle of the URL.  Substituting the respective month in the URL for previous releases, they all work.  Is this something new?  Please advise.  Thanks!

### Expected Outcome

The release notes are displayed.

### Current Outcome

An HTTP 404 is displayed.

### Reproducer

Use this link: https://docs.payara.fish/community/docs/Release%20Notes/Release%20Notes%206.2024.12.html to reproduce.

### Operating System

macOS Catalina

### JDK Version

JDK 21

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @mpredli01,

The correct link for the release notes is:
https://docs.payara.fish/community/docs/6.2024.12/Release%20Notes/Release%20Notes%206.2024.12.html.

This is intentional, as the URL structure includes the release version (e.g., 6.2024.12) as part of the path, helping organize documentation more effectively.

Best Regards,
Elif

**Comment by JamesHillyard** [comment]
@mpredli01 The reason for this change is that URLs that do not contain the version number default to the latest version of Payara released. As of the previous release, that is now Payara 7.2024.1.Alpha3 (Payara 6.2024.12 also released in December 2024, but the docs default is the highest version number).

Therefore any URLs without a version number will now default to the Payara 7 documentation, which does not include the Payara 6 release notes giving you a 404. This same scenario happened when Payara 6 released too.

If you select a Payara version from the version selector on the Payara Docs website you will notice the version number appended to the URL  and the release notes for that version and all **minor versions** before it are present.

Hopefully that makes more sense on why the URL structure changed

**Comment by mpredli01** [comment]
Thanks, @JamesHillyard, for that explanation!  I certainly appreciate it!
