### ISSUE TITLE
Log4j failure in Payara 4.1.1.161.1

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#721]
Hi there,
I have a problem with Log4j and Payara  4.1.1.161 and  4.1.1.161.1.

In these versions of application server, Log4j is not able ro produce log file as it did until version 4.1.1.154. I did not check other type of logging.

Can you check this issue please?

Best regards.

Meph

**Comment by mikecroft** [comment]
Hi Meph,

Do you have a test case that we could use to reproduce the problem? Am I right in assuming that the logs are not produced at all, or are they just incorrect?

Thanks,
Mike

**Comment by Mephysto666** [comment]
Hi Mikecroft,
actually I have a my own library with some log4j implementation.

Before 161 version my ejb-application was able to produce a log file (redevoserver.log) in the same directory of server.log via my library. After migration to 161 Payara version this file is not produced any more. Log4j version is 1.2.17 and if it can be helpful I can provide you configuration or library.

Regards.

Meph

**Comment by mikecroft** [comment]
Yes, thank you, that would be very helpful! If we can get the issue reproduced here then we can have something reliable to test against when writing a fix.

Mike

**Comment by arochamo** [comment]
Mephysto666, version 161 is known having issue with log. I'm using 161.1 together with Log4J 2.2 and seems working fine.

**Comment by Mephysto666** [comment]
Hi Mikecroft,
I attached my lib, it is configured to produce a file named redevoserver.log in Payara logs library. If you need the code I can provide it.


You can use library in this manner:

LogHelper.getLogHelperObject().warn("Exception in PriceComparator", ex);
.getLogHelperObject().debug("Value non trasformabile: "+value);

It is a singleton class


Bye.

Meph


[redevolib.zip](https://github.com/payara/Payara/files/185900/redevolib.zip)

**Comment by mulderbaba** [comment]
@Mephysto666 
thanks for your code, I created a maven-ized webapp out of it by decompiling your classes. I did some simple refactorings on throwing exception part in class PgStoredExecutor. Rest of the code was OK. I also added necessary dependencies into pom.xml. Sample webapp also contains a web service call, which simulates call to your LogHelper class. Just deploy [log4j-test.zip](https://github.com/payara/Payara/files/187063/log4j-test.zip) onto Payara and request for localhost:8080/ws/TestEJB?Tester. After requesting URL, you can call the op WS operation by clicking op button.
I couldn't reproduce your problem with my derivative sampler. redevoserver.log file is created with no problem under payaradomain/logs.
Let me know log4j-test works for you or not. Thanks.

**Comment by Mephysto666** [comment]
Hi mulderbaba, when I try to deploy the the zip, I get this error:

Archive type of C:\Users\developer\AppData\Local\Temp\log4j-test5239679530427234445.zip was not recognized


Many thanks.

Meph

**Comment by mulderbaba** [comment]
@Mephysto666 
the log4j-test.zip is just the source of the project I added its war version
[log4j-test-1.0-SNAPSHOT.zip](https://github.com/payara/Payara/files/188623/log4j-test-1.0-SNAPSHOT.zip) (just rename zip to war before deploying to Payara Server.) let us know how that works. thanks.

**Comment by baldodavi** [comment]
Dears @mulderbaba and @mikecroft , I'm a Mephysto666 collegue.
I've run the war @mulderbaba sent us and as you can see in attached image redevoserver.log do not appear in log folder. In server.log logs appear regularly. Hope my feedback help.
![payarascreen](https://cloud.githubusercontent.com/assets/5796817/14032811/b7154676-f215-11e5-905e-9b6e1edc6fc4.JPG)

**Comment by mulderbaba** [comment]
thanks for the feedback @baldodavi, have you tried with a clean installation of Payara Server?

My reproducing steps are:
1. download Payara Server 4.1.1.161.1 from https://s3-eu-west-1.amazonaws.com/payara.co/Payara+Downloads/Payara+4.1.1.161.1/payara-4.1.1.161.1.zip.
2. start payaradomain and see Welcome to Payara Server 4.1.1.161.1 #badassfish (build 63) on Admin Console.
3. Deploy log4j-test-1.0-SNAPSHOT.war
4. request for WS via url: http://localhost:8080/ws/TestEJB?Tester
5. check redevoserver.log is created under payaradomain/logs

@mikecroft, I'm on Mac and as I see it @baldodavi is using Windows, can you give the war a try on Windows also? 

Thanks guys.

**Comment by mikecroft** [comment]
@mulderbaba sure, I'll give that a go

**Comment by mikecroft** [comment]
@baldodavi @Mephysto666 I tested the sample uploaded by @mulderbaba with Payara 161.1 and the `redevoserver.log` appears in the domain logs directory as expected.

Can you confirm you're using the very latest version of Payara Server?

**Comment by Mephysto666** [comment]
Hi Mike,
Both me and David are using latest Payers release, yesterday I also update
jdk to the latest version, but the result is the same.

The only try remains to us to do is starting from a clean Payara
installation.

In the next few days I will try this scenario and I will report all news.

Many thanks.

Meph

**Comment by baldodavi** [comment]
@mikecroft @mulderbaba thanks for support.
I've installed last version in a new Virtual Machine with a clean system in windows system. I'm happy to say you redevolog appear. @Mephysto666 going to try again on linux next week, probabily on thursday, monday is holiday in Italy.

Thanks again, David.

**Comment by mulderbaba** [comment]
that's great to hear @baldodavi. keep us updated with your next try-out @Mephysto666.

**Comment by mulderbaba** [comment]
@Mephysto666 any luck with the try-out?

**Comment by Mephysto666** [comment]
Ho Mert,
unfortunately I was not able to execute any try. I hope to report my
results in next few days.

Best regards.

Meph

**Comment by Mephysto666** [comment]
Yes Mike.

With payara r162, our library works correctly.

Thank you very much.

Meph
