### ISSUE TITLE
Different Charset on DAS and Cluster-Nodes

### ISSUE THREAD

**Issue by PascalBru** [payara/Payara#723]
I'm running a Cluster with two nodes and an DAS.
On the DAS when i call Charset.defaultCharset() i get UTF-8 in the nodes i get US-ASCII.

The property file.encoding was not set by me. What am i doing wrong?

**Comment by mikecroft** [comment]
Are the nodes local or remote? What version are you seeing this in?

**Comment by PascalBru** [comment]
The nodes are remote and set up via create-node-ssh. The used version is 4.1.153

**Comment by mikecroft** [comment]
Can you confirm whether or not the result is the same with local instances? E.g. a new standalone instance?

**Comment by PascalBru** [comment]
Running of local instances was not tried yet. Running the same code on the instance named **server** on the DAS is working fine. Also an an different server which a standalone instance i get UTF-8

**Comment by PascalBru** [comment]
I hava done some research on my issue and have written two class for testing
The class SSHTest is using the same framewark than payara to manage there nodes via ssh and the class TestCharset makes an output of the charset.

With this i have the same result than on the nodes. Could you please try it on your servers that i can be sure if its a failure of our server config or of the ssh-Framwork.

[SSHTest.txt](https://github.com/payara/Payara/files/190621/SSHTest.txt)
[TestCharset.txt](https://github.com/payara/Payara/files/190622/TestCharset.txt)

**Comment by mikecroft** [comment]
Hi @PascalBru I finally got round to giving this a go. I used the trilead-ssh2-repackaged.jar from Payara Server 153 and got UTF-8 from both classes. I tried two different remote servers with the SSHTest class too.

Are you still finding this to be a problem? It doesn't look like there is an issue with the trilead SSH library.

**Comment by PascalBru** [comment]
Very strange but then it must be a very strange config on our servers.
 I will close the issue.

THX for your help!
