### ISSUE TITLE
Payara micro: setting SSL trustStore / keyStore manually

### ISSUE THREAD

**Issue by jacksonps4** [payara/Payara#729]
It seems that when deploying a WAR file in Payara Micro, the Java system properties `javax.net.ssl.trustStore` / `javax.net.ssl.keyStore` seem to be ignored in favour of a keystore and truststore within the payara-micro.jar itself. It would be great to be able to override these when required much as you can in full Payara or Glassfish domains.

**Comment by phillipross** [comment]
:+1:

**Comment by mikecroft** [comment]
How are you setting those system properties? In code or in the commandline with `-Djavax.net.ssl.keyStore` etc?

**Comment by jacksonps4** [comment]
I set them via the command line. If you add javax.net.debug=ssl, the list of trusted certificates remains the same regardless of whether or not the trust store location is passed in on the command line.

**Comment by jacksonps4** [comment]
[empty-truststore-testcase.zip](https://github.com/payara/Payara/files/194936/empty-truststore-testcase.zip)
I've attached a test-case. It contains a README.MD which details how to run it.

This is a simple WAR application which attempts to connect to https://github.com.

The example truststore contains only a single certificate and hence HTTPS connections to most sites should fail as the certification path is incomplete. 

If you run the same in Payara Micro attempting to override the trustStore with system properties, the connection still succeeds.

**Comment by smillidge** [comment]
Thanks for the test case this is reproducible

**Comment by smillidge** [comment]
Internal tracking JIRA tracking number PAYARA-693
