### ISSUE TITLE
mysql connection pool creation problem

### ISSUE THREAD

**Issue by kissoid** [payara/Payara#737]
when i try to create mysql connection pool, i gen an error message.
payara version : 4.1.1.161.1
mysql driver version : 5.1.23
![payara mysql connection poll error](https://cloud.githubusercontent.com/assets/5863512/14232234/bc902254-f9ab-11e5-822e-6d67d8df82f6.png)

**Comment by andreasernst** [comment]
I got as Resource Type always: javax.sql.DataSource, not javax.sql.ConnectionPoolDataSource.

**Comment by kissoid** [comment]
actually, i have tried with all resource types. when i created connection pool in standart glassfish 4.1, i had no problem but with payara server, i always got thsi error. maybe, reason is the turkish locale and language settings. i will check it. generally, ı and İ characters are problem in Java.
![payara mysql connection poll error2](https://cloud.githubusercontent.com/assets/5863512/14234570/ce1879d4-f9ee-11e5-8d1d-529a7eb65db1.png)

**Comment by mulderbaba** [comment]
@kissoid looks like the error is coming from the Hibernate Validator (with error code HV000039). Can you specify the version of Hibernate Validator that you have in your application's classpath?

**Comment by smillidge** [comment]
I couldn't reproduce this and could create the connection pool fine.

**Comment by kissoid** [comment]
i tried in 3 different computer.  only the first one have problem. there are no problem at others. i think problem related with configuration on that machine. I will check it. Thanks.

**Comment by kissoid** [comment]
hi,
i saw the same problem in my friend and then i detected the reason of this problem. 
i live in Turkey and my computer language is Turkish. problem about it. when i convert my computers language to English, my problem is resolved.
Biggest problem of Turkish language in programming languages is "i" and "ı" characters. I want to explain it.
In Turkish language, lowercase "i" = uppercase "İ" and lowercase "ı" = uppercase "I"

**Comment by mulderbaba** [comment]
@kissoid you are right, I reproduced this while defining a connection pool PostgreSQL on a machine with Turkish locale. this is definitely a lowercase "i" issue.

**Comment by mulderbaba** [comment]
created internal issue PAYARA-1119 to track this request

**Comment by mulderbaba** [comment]
I went through the details on this and found the culprit on hibernate-validator itself. Filed a [ticket](https://hibernate.atlassian.net/browse/HV-1140) and sent a [PR](https://github.com/hibernate/hibernate-validator/pull/566) to them. So there is nothing we can do for this at the moment. Please provide system env. properties to your server like `-Duser.language=en -Duser.country=US` while starting it. When hibernate-validator fixes the problem, we'll see if we can integrate it with the latest release of hk2, since hk2 employs the hibernate-validator stuff under the hood.
