### ISSUE TITLE
Unwrapping principal interferes with JASPIC's register session

### ISSUE THREAD

**Issue by arjantijms** [payara/Payara#751]
I unfortunately found a problem with the solution as committed for https://github.com/payara/Payara/issues/290. In case a custom principal is used AND the JASPIC 1.1 "javax.servlet.http.registerSession" directive is used, the groups (and possibly any credentials) are not restored as they should be.

This happens because the protocol for "javax.servlet.http.registerSession" requires [getting the Principal from the `HttpServletRequest` and then feeding it back to the handler in a SAM](http://arjan-tijms.omnifaces.org/2013/04/whats-new-in-java-ee-7s-authentication.html#RegisterSession). Subsequently [BaseContainerCallbackHandler#processCallerPrincipal](https://github.com/payara/Payara/blob/master/appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jmac/callback/BaseContainerCallbackHandler.java#L374) checks if the type is `WebPrincipal`. 

If this is not the case, no "reuse" will take place.

Now I'm the first to admit this "getting principal from request and feeding it back" is a little brittle, but that's how it works in JASPIC 1.1.

What I guess what needs to happen is that when in a SAM's validateRequest method the unwrapping should *not* take place. There are a few characteristics one can check for, e.g. if the principal has reference equality to `org.apache.catalina.Session#getPrincipal`, but perhaps the more robust way is setting a request attribute to indicate we're in a SAM:

    //JSR 196 is enabled for this application
    try {
         context.fireContainerEvent(ContainerEvent.BEFORE_AUTHENTICATION, null);
         ((HttpServletRequest)request.getRequest()).setAttribute("...", true);
         result = validate(request, response, config, authenticator, calledFromAuthenticate);
     } finally {
         ((HttpServletRequest)request.getRequest()).removeAttribute("...");
         context.fireContainerEvent(ContainerEvent.AFTER_AUTHENTICATION, null);
     }

Any other mechanism like the internal *notes* may work as well, as long as the `getUserPrincipal()` can internally check for it.

What do you think? I've asked Ron Monzillo if he has any opinion on this matter and let you know as soon as he replies.

cc @Circkumflex 

p.s. I originally commented on https://github.com/payara/Payara/issues/290, but since that issue is already closed it's perhaps better to open a new issue.

**Comment by smillidge** [comment]
Is there a test case application that demonstrates the problem? I like to step through what's going on.

**Comment by arjantijms** [comment]
Yes, I added a test for this case here: https://github.com/javaee-samples/javaee7-samples/tree/master/jaspic/register-session

You can deploy the war from that sub-module manually as well. This test shows the two requests that demonstrate the problem: https://github.com/javaee-samples/javaee7-samples/blob/master/jaspic/register-session/src/test/java/org/javaee7/jaspic/registersession/RegisterSessionCustomPrincipalTest.java#L49

I'm also using a temp hack for Soteria here to get the unwrapped request: https://github.com/javaee-security-spec/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/cdi/AutoApplySessionInterceptor.java#L102

That last one more or less demonstrates that the register session feature works again with the non unwrapped request.

**Comment by smillidge** [comment]
You suggested "What I guess what needs to happen is that when in a SAM's validateRequest method the unwrapping should not take place. " However isn't this brittle because a write of a SAM may expect that they get back their custom principal or am I missing something?

**Comment by smillidge** [comment]
This could be very tricky to fix as if we always unwrap the WebPrincipal to give the custom principal then Payara can't control what the principal contains as it is a custom class. This means we have no context. I'll dig deeper it's possible we can "find" the original WebPrincipal in the BaseContainerCallBackHandler if the instance passed to us is not a WebPrincipal

**Comment by smillidge** [comment]
OK I think I have a fix and that is adding the original WebPrincipal to the Security Context in addition to the wrapped principal for the duration of the authentication callback. In that way the callback handler can find a web principal if it is present.

**Comment by arjantijms** [comment]
>However isn't this brittle because a writer of a SAM may expect that they get back their custom principal or am I missing something?

It's may be brittle indeed, but the entire construct is already a bit brittle in the spec itself. 

The question is what the guarantees are when the SAM does ``request#getUserPrincipal`` without having invoked the handler yet. The SAM developer knows this is not a "normal" user principal. I.e. the SAM can't use the normal logic ``userPrincipal == nulll -> not authenticated, userPrincipal != null -> authenticated``. The != null means here "there is an object available that can be used as signal for the container to restore the previous saved identity". Note that at this point ``request#isUserInRole`` is not expected to work either, since the SAM hasn't actually authenticated yet.

You *could* perhaps speculate that the SAM has to treat ``request#getUserPrincipal` as an opaque object only used to signal the container and not as an actual principal.

I admit, I don't know if this is correct, but that was the original reasoning behind the suggestion ;)

I quickly looked at the current fix:

```
if (principal != null && !(principal instanceof WebPrincipal)) {
    Principal additional = SecurityContext.getCurrent().getAdditionalPrincipal();
    if (additional != null) {
        principal = additional;
    }
}
```

I don't have all the Payara source available now to check it, but at a quick glance, what happens now when there's this additional principal available, and the SAM chooses not to put the principal from request#getUserPrincipal into the callback, but a new (different) custom principal?

Maybe I've got it wrong, but at a hunch I'd feel it should perhaps be something like:

```
if (principal != null && !(principal instanceof WebPrincipal)) {
    Principal additional = SecurityContext.getCurrent().getAdditionalPrincipal();
  
    if (additional != null && ((WebPrincipal)additional).getCustomPrincipal() == principal) {

        // There is a saved principal available, and its wrapped principal has reference
        // equality with the principal the SAM provides us here. This is the signal
        // to fully restore the previously saved authenticated identity
        principal = additional;
    }
}
```

Would that make sense?

**Comment by smillidge** [comment]
Yep that equality check makes it more robust
