### ISSUE TITLE
Upgrade Weld to 2.2.4.Final or newer

### ISSUE THREAD

**Issue by pdurbin** [payara/Payara#76]
https://developer.jboss.org/message/883410#883410

http://transcripts.jboss.org/channel/irc.freenode.org/%23weld-dev/2014/%23weld-dev.2014-11-06.log.html#t2014-11-06T14:52:17

**Comment by pdurbin** [comment]
> Just out of interest did Weld 2.2.4 fix the problem for you?

@smillidge it is **very** difficult to assess if the problem is actually fixed or not. All I can say as of this writing is that we have not see a recurrence of the scrambled session bug since we upgraded to Glassfish 4.1 and then patched it with Weld 2.2.4 as I mentioned at https://github.com/IQSS/dataverse/issues/647#issuecomment-69036235

For obvious reasons, we are highly motivated to not push to production until we have some level of confident that the mixed up session bug does not recur. We don't want a situation like http://www.macrumors.com/2015/01/29/itunes-connect-developer-issue/

If anyone has any tips on reproducing the bug, please let me know!

**Comment by realityforge** [comment]
The problem seems to have been fixed for us. It occurred for us when certain runtime exceptions were generated where a CDI session scoped bean was on the stack and called from JSF.
