### ISSUE TITLE
ServletContainerInitializer annotation scanning is broken in embedded Payara

### ISSUE THREAD

**Issue by fcaputo** [payara/Payara#780]
We have a JSF application, where the set of classes passed to com.sun.faces.config.FacesInitializer#onStartup differs from standard Payara to embedded Payara. 
The embedded Payara gets a set of 116 classes while the standard Payara gets 156 classes. 
Especially classes annotated with @FacesRenderer, which extend javax.faces.render.Renderer are not passed to the FacesInitializer in embedded mode.

**Comment by dreamIt-de** [comment]
Works fine with embedded payara-4.1.152.1
Does not work with embedded payara-4.1.1.161.1

**Comment by mulderbaba** [comment]
@fcaputo, are you doing any configuration in glassfish-web.xml? like: <property name="useBundledJsf" value="true" />

**Comment by fcaputo** [comment]
@mulderbaba, we don't have a glassfish-web.xml. We use the payara's JSF version.

**Comment by mulderbaba** [comment]
@fcaputo I see that embedded payara-4.1.152.1 depends on Mojarra 2.2.10 and embedded payara-4.1.1.161.1 depends on 2.2.12.

from Mojarra version 2.2.11 (+) the Mojarra library does not handle the annotation scanning by itself anymore but relies on the container to provide the classes which contain annotations.

In 2.2.10, it was
```
public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls) { if (null == scanner) { scanner = new JavaClassScanningAnnotationScanner(sc); } return scanner.getAnnotatedClasses(urls); } 
```
In 2.2.11, it is:
```
public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls) { HashMap<Class<? extends Annotation>, Set<Class<?>>> annotatedMap = new HashMap<Class<? extends Annotation>, Set<Class<?>>>(); createAnnotatedMap(annotatedMap, (Set<Class<?>>) sc.getAttribute(ANNOTATED_CLASSES)); return annotatedMap; } 
```
Where ANNOTATED_CLASSES is set in the FacesListener:
```
public void onStartup(Set<Class<?>> classes, ServletContext servletContext)
```
I'll dig into more about the Renderer issue that you have. If you have a [SSCCE](http://sscce.org)'d reproducer that'd be great to start with.

**Comment by mikecroft** [comment]
Hi @fcaputo is this still a problem?

**Comment by mikecroft** [comment]
I'm going to assume you got around this issue @fcaputo and close it here. If you're still seeing this problem in the latest version of Payara Server and have a reproducer (http://sscce.org/), please feel free to reopen this.

**Comment by fcaputo** [comment]
I still have the problem.

**Comment by mikecroft** [comment]
Hi @fcaputo - that is covered by issue #1456
