### ISSUE TITLE
create-node-ssh fail on Payara 4.1.161.1

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#781]
Hi there,
I am trying to create a payara cluster and I get an error during creation of a remote node:

`Successfully connected to payara@10.0.0.150 using keyfile /home/payara/.ssh/id_rsa Created installation zip /opt/payara411.161.1/glassfish/domains/payaradomain/config/glassfish3762412225175776690.zip Successfully connected to payara@10.0.0.150 using keyfile /home/payara/.ssh/id_rsa Copying /opt/payara411.161.1/glassfish/domains/payaradomain/config/glassfish3762412225175776690.zip (115972475 bytes) to 10.0.0.150:/opt/payara411.161.1/ Installing glassfish3762412225175776690.zip into 10.0.0.150:/opt/payara411.161.1/ jar command failed while installing glassfish on host 10.0.0.150. Command output bash: jar: command not found Command install-node-ssh failed. Remote command output: bash: jar: command not found`

The problem seems due to jar command, but it is in payara $PATH:

```
payara@payara-2:/opt/payara/glassfish$ ssh 10.0.0.150
Linux payara-1 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Apr 26 21:51:31 2016 from payara-2.local
payara@payara-1:~$ jar
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...
Options:
    -c  create new archive
    -t  list table of contents for archive
    -x  extract named (or all) files from archive
    -u  update existing archive
    -v  generate verbose output on standard output
    -f  specify archive file name
    -m  include manifest information from specified manifest file
    -n  perform Pack200 normalization after creating a new archive
    -e  specify application entry point for stand-alone application 
        bundled into an executable jar file
    -0  store only; use no ZIP compression
    -P  preserve leading '/' (absolute path) and ".." (parent directory) components from file names
    -M  do not create a manifest file for the entries
    -i  generate index information for the specified jar files
    -C  change to the specified directory and include the following file
If any file is a directory then it is processed recursively.
The manifest file name, the archive file name and the entry point name are
specified in the same order as the 'm', 'f' and 'e' flags.

Example 1: to archive two class files into an archive called classes.jar: 
       jar cvf classes.jar Foo.class Bar.class 
Example 2: use an existing manifest file 'mymanifest' and archive all the
           files in the foo/ directory into 'classes.jar': 
       jar cvfm classes.jar mymanifest -C foo/ .
```

So, I can not understand why node creation fails. Can you help me please?

In the attachment you can find my settings for the operation.

Thanks in advance.

Meph
![screenshot from 2016-04-26 22-10-03](https://cloud.githubusercontent.com/assets/3337127/14832688/bacc9d14-0bfb-11e6-9b00-dd83af170e96.png)

**Comment by mikecroft** [comment]
Can you check in the logs to see what Java is used when the server starts?

You're looking for a `NCLS-GFLAUNCHER-00005` message that begins something like:
```
  JVM invocation command line:
/usr/lib/jvm/java-8-oracle/bin/java
```

You could also check (or set) `AS_JAVA` in `....payara41/glassfish/config/asenv.conf` to make sure it's picking up the JDK and not the JRE.

Assuming that all is as it should be - what commands are you using to create your new node so that we can reproduce accurately?

**Comment by Mephysto666** [comment]
Hi Mike,
I did set manually AS_JAVA in asenv.conf as it can be see in log:

`JVM invocation command line: /opt/jdk1.8.0/bin/java`

In remote machine, jdk is installed in the same path.




I do not know which is exact command because I am using Payara GUI to execute node creation, but this is an extract of server.log:

```
Successfully connected to payara@10.0.0.150 using keyfile /home/payara/.ssh/id_rsa
Created installation zip /opt/payara411.161.1/glassfish/domains/payaradomain/config/glassfish1265487399037637756.zip
Successfully connected to payara@10.0.0.150 using keyfile /home/payara/.ssh/id_rsa
Copying /opt/payara411.161.1/glassfish/domains/payaradomain/config/glassfish1265487399037637756.zip (115972475 bytes) to 10.0.0.150:/opt/payara411.161.1/
Installing glassfish1265487399037637756.zip into 10.0.0.150:/opt/payara411.161.1/
jar command failed while installing glassfish on host 10.0.0.150. Command output bash: jar: command not found

Command install-node-ssh failed.

Remote command output: bash: jar: command not found
```


Can I make log more verbose?

Ask me any other question.

Bye.

Meph

**Comment by Mephysto666** [comment]
Hi,
any news about this issue?

Is there an alternative way to create a cluster?

I need to test this feature as soon as possible.

Thanks in advance.

Meph

**Comment by fturizo** [comment]
Hello @Mephysto666, we're sorry it took us a while to get back to you again with this issue. Is the issue still persisting on your environment? Have you tried to create a cluster with the new releases of Payara Server? If the problem still persists let us know.

**Comment by Mephysto666** [comment]
Ho Fabio,
I have not tried anymore to create a cluster by this way and actually I
don't need a cluster for my environment. So, I'm sorry but I can't execute
any test at the moment. Probably, in the future I will do them.

I can't answer your question.

Many thanks.

Meph

**Comment by fturizo** [comment]
Not a problem, I'll close this issue then. If the problem reappears feel free to reopen it so we can resume the discussion.

**Comment by aouaneWalid** [comment]
Hello,

I have the same problem : 

Remote command output: bash: jar: command not found !!!!

Created installation zip /root/payara5/glassfish/domains/domain1/config/glassfish1438835555654677484.zip
Successfully connected to root@10.198.228.240 using keyfile /root/.ssh/id_rsa
Copying /root/payara5/glassfish/domains/domain1/config/glassfish1438835555654677484.zip (146575218 bytes) to 10.198.228.240:/root/payara5
Installing glassfish1438835555654677484.zip into 10.198.228.240:/root/payara5
jar command failed while installing glassfish on host 10.198.228.240. Command output bash: jar: command not found

Command install-node-ssh failed.

Remote command output: bash: jar: command not found]]

**Comment by marcoradavelli** [comment]
I had a similar issue, and the points 3- and 4- of this thread were what I was missing to solve the issue: https://stackoverflow.com/a/54731807/5538923 , i.e., create a symbolic link in /usr/bin that points to the jar executable:
3- check witch jar executable shell was trynig to execute : $ which jar /opt/java-jdk/jdk1.8.0_201/bin/jar 4- Now create a symbolic link to the jar executable file frome /usr/bin directory # cd /usr/bin/ # ln -s /opt/java-jdk/jdk1.8.0_201/bin/jar # which jar /usr/bin/jar
