### ISSUE TITLE
Payara Blue on IBM JDK invalid JVM options

### ISSUE THREAD

**Issue by ondruska** [payara/Payara#801]
Version 162 still has these default JVM options:
-XX:MaxPermSize=192m
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
They are silently ignored on IBM JDK 7, 7.1, 8. These options are specific to Oracle JDK. I manually remove those in configuration script. Can they be removed from default Payara Blue?

**Comment by mikecroft** [comment]
I've created internal issue PAYARA-795 to follow up on this.

**Comment by smillidge** [comment]
Fixed by #852
