### ISSUE TITLE
No LoginModules configured for jdcbRealm on Payara Micro

### ISSUE THREAD

**Issue by paolizq** [payara/Payara#804]
Hello,

I'm trying to configure security with a jdbc realm on an application bundled up as an uber jar with payara micro (4.1.1.162), but I just can't seem to get it to work. I've packaged a domain.xml with the pool and jdbc resource configuration in the uber jar and I get "No LoginModules configured for jdbcRealm", when I try to login with a user who is assigned to the correct group.

I already deployed my application using the full payara server and it works. So I don't know what I could be doing wrong or what steps I might be missing to get this to work on payara micro. Do you have any ideas?

**Comment by paolizq** [comment]
I've been digging around a little bit and found out that the problem is that while trying to load the login.conf file `System.getProperty("java.security.auth.login.config");` returns `null`.

Now I just need to figure out why.

Hints are welcome and very appreciated! ;)

**Comment by paolizq** [comment]
java.security.auth.login.config is missing from payara-boot.properties

**Comment by smillidge** [comment]
Does adding that system property on the command line fix the problem? The latest Payara Micro also has a system properties command line option https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/payara-micro.html#131-payara-micro-command-line-options which you can pass a file to.

**Comment by paolizq** [comment]
Yes, it fixes the problem. 

I will try it with the command line option to provide an extra file and report back. However, I think the property should be included out of the box. Otherwise there are files in the payara micro jar that are somewhat superfluous.

**Comment by smillidge** [comment]
Yeah we'll investigate and fix it. Thanks for finding a solution.

**Comment by paolizq** [comment]
Quick update: it works with --systemProperties

**Comment by smillidge** [comment]
Internal issue number PAYARA-803

**Comment by softwaredevease** [comment]
Hi,

I'm using Payara Server 171, connected via NetBeans 8.2. My JDBC realm is created via the Admin Domain Console web UI. When a web application tried to authenticate with this realm, server is giving a similar error.

WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: No LoginModules configured for (jdbcRealmName)

Am I missing something?
