### ISSUE TITLE
Failure building payara-micro on Windows 7 / 8.1

### ISSUE THREAD

**Issue by sknitelius** [payara/Payara#811]
When building payara-micro (`mvn clean install -DskipTests`), I get the following error on two separate systems: 

```
[ERROR] Failed to execute goal org.jvnet.maven-antrun-extended-plugin:maven-antr
un-extended-plugin:1.43:run (default) on project payara-micro: An Ant BuildExcep
tion has occured: The following error occurred while executing this line:
[ERROR] C:\Users\sknitelius\projects\Payara\appserver\extras\embedded\payara-mic
ro\build.xml:59: The following error occurred while executing this line:
[ERROR] C:\Users\sknitelius\projects\Payara\appserver\extras\embedded\payara-mic
ro\build.xml:125: problem opening C:\Users\sknitelius\projects\Payara\appserver\
extras\embedded\payara-micro\target\packager_jars\payara41\glassfish\modules\hea
lthcheck-core.jar: Negative seek offset
```

Maven: 3.3.9
Java: 1.8.0_60

**Comment by mulderbaba** [comment]
@sknitelius are you going with `mvn clean install -f appserver/extras/embedded/pom.xml` ?

**Comment by sknitelius** [comment]
@mulderbaba tried both `appserver/extras/embedded/pom.xm`l and `appserver/extras/embedded/payara-micro/pom.xml`. 

Strikes me as strange that two sepearte machines, one with an entirely new clean setup should have the same issue.

Will have to check on the healthcheck-core.jar later tonight.

**Comment by sknitelius** [comment]
@mulderbaba I can open health-check.core without a problem with 7zip.

**Comment by sknitelius** [comment]
Attached is the healthcheck-core JAR from my maven repository (had to zip it, because github wouldn't accept it otherwise).

[healthcheck-core-4.1.1.163-SNAPSHOT.zip](https://github.com/payara/Payara/files/261922/healthcheck-core-4.1.1.163-SNAPSHOT.zip)

**Comment by sknitelius** [comment]
@mulderbaba When looking in the `payara-micro/target/package_zips` healthcheck-core.zip looks
 fine, however in `payara-micro/target/packager_jars/payara41/galassfish/modules/` healthcheck-core.jar is brocken (size 0 bytes).

Zip from `target/packager_zips`
[healthcheck-4.1.1.163-SNAPSHOT.zip](https://github.com/payara/Payara/files/261955/healthcheck-4.1.1.163-SNAPSHOT.zip)

**Comment by Pandrex247** [comment]
@sknitelius Are you by chance doing a build on Windows? We've got an issue raised internally that builds for Payara Micro are failing on Windows with this exact error.

**Comment by sknitelius** [comment]
@Pandrex247 yes both machines are on windows 7 / 8.1.

**Comment by smillidge** [comment]
Change was merged
