### ISSUE TITLE
Payara Server 4.1.1.161.1 Issue : Server loads the application twice before deploying it

### ISSUE THREAD

**Issue by rajsinhak** [payara/Payara#819]
I am running into some weird issue, the server is loading the application twice before it's get's deployed. the problem with this is that, there are application data which are loaded at the start-up . when I see the log it shows the execution of the Query twice . currently application is using based on following technology
JSF 2.X, EJB, JPA, CDI and Primeface. 
For Loading application data I have a class as @Singleton and @Startup and using @postconstruct annotation in that class. As per my understanding this should not effect the deployment life cycle
I have attached the server log for the reference. 

[server.zip](https://github.com/payara/Payara/files/267494/server.zip)

**Comment by OndrejM** [comment]
I see that there are 2 applications being started and both of them have some entities. The application names are *DMSLightBaseApp* and *dmslight*. Both of them include entities and use the same package (`th.fujitsu.dmslight.entities.`), there are even some entities with completely identical names in both applications, such as `th.fujitsu.dmslight.entities.TbRCustomerInvH`.

You can check which applications are deployed using `asadmin list-applications` or via the admin console in the browser.

Can you undeploy all the applications and deploy your application again to see if the query is execued only once?

**Comment by rajsinhak** [comment]
Hi Ondrej,
Thanks for you reply, 
Yes there are two applications are been deployed with some identical class names. One DMSLightBaseApp is based on Jersey Framework and dmslight is based on JSF Framework. 
If you can see the log you can noticed that DMSLightBaseApp was loaded only once but dmslight is loaded twice before applications get deployed !!
However, As per your suggestions, I have Undeployed all the applications and tried deploying dmslight only. At first deployment it was absolutely perfect (application gets loaded only once). But when i restarted the application the issue persists again. 
if i am not wrong this is what server doing right now when i say RUN (Re-Deploy) on application, The server first loads all the deployed application and after that it gets disconnected and then it again loads the application on which i have said RUN. 
Just to check my theory, i tried deploying DMSLightBaseApp first and then said RUN (Re-Deploy) and encountered the same issue. 
As we are near about to complete our First Phase , and we would be using Payara Server on Production. Then in that case we cannot relay on the Re-Deployment Thread of Payara Server. We always have to undeploy and then need to deploy it again. Please correct me if i am not wrong !!

**Comment by OndrejM** [comment]
Could you describe how you deply the application when you say RUN? Do you deploy from and IDE, or using Payara admin console, or from command line?

Could it be that the server is being restarted before the dpeloyment? It would then mean that the application is first started upon server restart and then restarted after redeployment...

**Comment by rajsinhak** [comment]
i used to say run from the IDE NetBeans. 
Yes, you are right. the server is being restarted before the deployment when i say RUN from the IDE. Where as i have checked the redeploy option from the Payara Admin Console and works perfectly fine. and the logs shows exact what it has to be (The first step itself is disconnect) :)
Info:   uploadFileName=dmslight-1.0-SNAPSHOT.war
Info:   ================== availabilityEnabled  skipped
Config:   disconnect
Then Continue loading the application

**Comment by OndrejM** [comment]
It is strange that the server is being restarted when doing deployment from Netbeans, I wouldn't expect that. But that would explain why the app is executed twice - first on Payara startup (the previously deployed version) and then after the deployment. It should not happen in production though. 

If the issue is resolved, please close it.

**Comment by rajsinhak** [comment]
Thanks for the response. Yes it's strange that Netbeans handle the payara server life cycle differently.
Now we have migrated it to the production and things seems to be ok so far . Thanks for your support
