### ISSUE TITLE
payaradomain - Web Service Tester Fails to load

### ISSUE THREAD

**Issue by fouched** [payara/Payara#824]
Hi

I have a simple Stateless bean SOAP web service, when deploying in the payaradomain it fails to load the built-in Web Service Tester page of the service. In essence the following error occurs:
Failed to read schema document 'xjc.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property.

My fix for this was to change domain.xml adding in:
<jvm-options>-Djavax.xml.accessExternalSchema=all</jvm-options>

I am running payara-4.1.1.162

Not sure if you would like this option to be available in the payaradomain, it is in domain1, but thought it is worth reporting.

**Comment by mulderbaba** [comment]
Reproducer project: [wstestertest.zip](https://github.com/payara/Payara/files/274944/wstestertest.zip)

**Comment by smillidge** [comment]
Internal defect number PAYARA-802

**Comment by smillidge** [comment]
Fixed by #831
