### ISSUE TITLE
remote EJB lookup from Tomcat to Payara

### ISSUE THREAD

**Issue by zappee** [payara/Payara#830]
Hi,

Sorry for the new question but It would be great if you can help me. I think you are the most qualified guys in this topic.

The post is on stackoverflow: [http://stackoverflow.com/questions/37366816/remote-ejb-lookup-from-tomcat-to-payara-glassfish](http://stackoverflow.com/questions/37366816/remote-ejb-lookup-from-tomcat-to-payara-glassfish)

Thnks,

**Comment by vkalayda** [comment]
Why do you want to interoperate with payara server via IIOP ? 
I think will be simpler communicate between servers with REST (JSON) for instance.

**Comment by fturizo** [comment]
Hi @zappee, according to your SO question, the best way to comunicate to to a remote EJB that lives in a Payara Sever from an standalone application or a non-EJB compliant server is to use the `payara-embedded-all` JAR that contains the necessary classes to execute EJB calls trough IIOP. Here are the Maven GAV coordinates:

```
<dependency>
   <groupId>fish.payara.extras</groupId>
   <artifactId>payara-embedded-all</artifactId>
   <version>4.1.1.162</version>
   <type>jar</type>
</dependency>
```

I setup a simple web application and deployed it to Tomcat 8 using this dependency but unfortunately it couldn't be deployed since it got the following error:

```
17-Jun-2016 21:41:57.614 SEVERE [http-nio-8084-exec-4] org.apache.catalina.core.StandardContext.startInternal Error during ServletContainerInitializer processing javax.servlet.ServletException: java.lang.InstantiationException: org.glassfish.tyrus.server.TyrusServerConfiguration
	at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:88)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5170)
...
```

I'll review this with the development team and let you know when I have more information.

**Comment by zappee** [comment]
Thank you for your help. I really appreciate it.

**Comment by fturizo** [comment]
Hi @zappee, I have raised an issue for our development team to evaluate and see if it's possible to deploy a Payara Embedded powered application into Tomcat. I'll update you when we have more information on a possible fix.

**Comment by fturizo** [comment]
Hi @zappee, The Dev team has come back to me and it seems that many artifacts shipped with Tomcat conflict directly with some components in Payara Embedded and fixing this could prove complicated. Considering that you are basically enhancing Tomcat with Payara's artifacts, would it be possible for you to migrate directly to Payara Server Full edition (to use Remote EJBs)? I think that could help you in this case.

**Comment by zappee** [comment]
I need to use a separated servlet container for security reason. What I did is I use json communication (restful) instead of remote ejb call. According to my experience remote ejb call can be complicated and i am going to be avoid that in the future.

My solution works but I am not satisfied with the speed because the marshaling/unmarshaling process.

Thanks a lot @fturizo

**Comment by lprimak** [comment]
@zappee Why don't you use two instances of Payara, one for a servlet container and one for the EJB container, running separate applications on both.  I would think this would satisfy your security requirements.
One could even be web profile, and one full profile (for EJBs)

**Comment by zappee** [comment]
Hey, this is a very good point. I always think about Payara as a EE server... It is my mistake, i know.
I will search for documents how to disable the unnecessary modules and use the 2nd Payara as a simple web container.

Thanks a lot for this idea!

**Comment by fturizo** [comment]
@zappee , since you want a light web container, you can also use [Payara Micro](https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/payara-micro.html) to host a simple application; this way you won't have to worry about disable unnecessary modules.

**Comment by zappee** [comment]
I like Payara. It is so elegant: java -jar payara-micro.jar --port 2468 ;)

Thx!

**Comment by fturizo** [comment]
Glad to hear that! I'll be closing this issue now.
