### ISSUE TITLE
What is the best practice approach to upgrading Payara and domains?

### ISSUE THREAD

**Issue by dazed19** [payara/Payara#833]
I've looked around, but can't see any stated way of upgrading Payara version and maintaining domain configuration.  

In a trial (in Linux) I have taken the approach of

- unzipping payara zip in a parallel directory 
- copying domain files into new payara domains directory
- re-pointing symbolic link to /usr/glassfish to reference new version

Domains start ok and apps run, but I notice a NullPointerException in the logs.  This appears to relate to HTTP Monitoring ("target=org.glassfish.web.admin.monitor.HttpServiceStatsProvider@75b27e94").  This doesn't appear critical (from cursory look) i.e. I can still get HTTP metrics via asadmin.

I can't reproduce this in a new domain - and in comparing the domain.xml files I notice a number of "new feature" differences.

So my question is - is there an approved way of upgrading an existing payara domain file rather than copying?

**Comment by mikecroft** [comment]
You've raised this at just the right time, I'm just in the middle of putting together proper documentation on this.

What you've described is almost what we would recommend for this, though you don't need to move directories around so much.

The `asadmin start-domain` subcommand has a `--domaindir` option which allows you to specify the location of a domain directory. So you could have a directory structure like this:

```
/opt/payara/154/payara41/....
/opt/payara/161/payara41/....
/opt/payara/162/payara41/....
/opt/payara/domains/myDomain
/opt/payara/nodes/myLocalNode
```

Then you could start your domain with whatever version of Payara you wanted:

```
/opt/payara/154/payara41/bin/asadmin start-domain --domaindir /opt/payara/domains myDomain
      ...or:
/opt/payara/162/payara41/bin/asadmin start-domain --domaindir /opt/payara/domains myDomain
```
*Note: the `--domaindir` option specifies the parent directory for your domain...so where you would store all of your domains. There is then a space and then the name of the domain you want to start - domain1 is still the default*

You can start nodes in the same way:

```
/opt/payara/162/payara41/bin/asadmin start-local-instance --nodedir /opt/payara/nodes myLocalNode
```

I do need to follow up on this to make sure that there aren't any incompatibilities between Payara versions and if there are any ways around this. If this is the case, then the "ideal" solution would be to script the creation of your domain.

The process I've described would be my preferred solution, though, so I'll look to find a way to make it work without errors if I can.

**Comment by dazed19** [comment]
Mike hi

Thanks for your response - I will have a look at that feature.  Although, as I referenced, I did see an error in the logs - which, in my mind, are down to a (slight) incompatibility between existing and expected config versions.

One thought (for your consideration) - in a java development I am doing I am using [Flyway](https://flywaydb.org/) to help manage database schema changes in line with application code changes.  It struck me that a similar approach could be applied here - by that I mean config format deltas defined alongside Payara version (add node, change element attribute) as an asset of the Payara.   Then when a new version of payara is run against a config file it would get "migrated" to be new version compatible.  Something like that would be awesome!

**Comment by smillidge** [comment]
I'm not aware of any domain.XML schema changes that should cause an error on upgrading. If there are then these should be raised as issues.

**Comment by mikecroft** [comment]
Hi again, I've just been trying this out. I managed to start a 144 domain with 162 without any issues, though I did have to clear out the `osgi-cache` in the domain directory first.

Have you already used and configured the healthcheck service in your domain? My thought is that there may be a minor incompatibility between 161 and 162 since (by default) there is no change to the standard domain.xml

**Comment by dazed19** [comment]
To be clear I'm moving from 153 to 162.  I'll see if I can reproduce and will then raise an issue - I asked the question here in case I was doing something wrong and had missed an upgrade step.

**Comment by dazed19** [comment]
Hi

Checking back in logs I see the same NullPointerException error before I attempted upgrade (and I did the upgrade inside a VMWare Snapshot which I reverted) so this isn't caused by upgrade but pre-existing.  I'll raise a separate issue.
