### ISSUE TITLE
config path is the defualt directory for my application deployed to Payara 4.162

### ISSUE THREAD

**Issue by themaster5** [payara/Payara#848]
I wonder why the below code in any application deployed to Payara refers to payara configuration path?

Any help please ?

File f = new File(".");
System.out.println(getAbsolutePath()); 
// prints payara41162/glassfish/domains/payaradomain/config/

Regarding the environment,
I use NetBeans 8.1, JDK 8, Maven, and CentOS 6.5 as the operating system.

**Comment by lprimak** [comment]
This is how it always was with GlassFish and Payara as well.  Is there any problem associated with that?

**Comment by themaster5** [comment]
Yes, the issue stated on https://java.net/jira/browse/GLASSFISH-21539 

I'm not able to add SOAP handler because the server always search for the handler file "handler-chain.xml" and couldn't find it.

I don't know how to solve this issue.

**Comment by lprimak** [comment]
You should put that file anywhere in the application's CLASSPATH.
By convention it goes into META-INF and used like this:
```@HandlerChain(file = "META-INF/handlers.xml")```
If using maven, it goes into ```src/main/resources/META-INF``` directory

**Comment by themaster5** [comment]
Thanks the issue has been solved now.
