### ISSUE TITLE
Mojarra 2.3 integration for Payara 5 could use Tyrus SPI jar

### ISSUE THREAD

**Issue by arjantijms** [payara/Payara#853]
For integrating Mojarra 2.3 with Payara 5, we've created an SPI jar. See https://github.com/jsf-spec/mojarra/tree/master/spi/websocket-activation/tyrus

This jar can be used as-is (include it in /modules) or if more convenient be used as an example. With the SPI jar present, the so called "fake endpoint" for web socket is not needed anymore,

**Comment by smillidge** [comment]
Do we just drop this into the modules directory and it will just work or do we need to do some integration?

**Comment by arjantijms** [comment]
It's a simple drop in the modules directory. It works as-is for Glassfish & Payara.

btw, we have been trying for some time to get the jar published in maven (central) but have not been successful yet. The problem is that none of the current Mojarra maintainers (including Oracle employees) have sufficient right to stage via maven.java.net. Hopefully we can get it published soon via that route, otherwise I'm going to try it via Bintray.

**Comment by arjantijms** [comment]
@smillidge 

We've finally been able to publish the SPI artefacts (many thanks to our friend Zhijun at Oracle). The SPI jar can be found in Maven central here: http://repo1.maven.org/maven2/org/glassfish/mojarra/tyrus-mojarra-activator/2.3.0-m06/

The dependency is:

```
<dependency>
    <groupId>org.glassfish.mojarra</groupId>
    <artifactId>tyrus-mojarra-activator</artifactId>
    <version>2.3.0-m06</version>
</dependency>
```

Note that for this release the Mojarra main version (m07) and the SPI (m06) don't exactly match. We're still thinking about whether we should increase the version of the SPI even when nothing changed just to keep it in sync with the Mojarra main version.

**Comment by mikecroft** [comment]
Fixed by #930

**Comment by smillidge** [comment]
the PR doesn't integrate the activator

**Comment by OndrejM** [comment]
Is there anything more to do with this issue after the PR #930? What about the activator?

**Comment by mikecroft** [comment]
@arjantijms is this still an issue given the new Payara 5 branch?
