### ISSUE TITLE
System property substitutions in descriptor files

### ISSUE THREAD

**Issue by jbndbc** [payara/Payara#858]
Hi.

From this thread (https://java.net/nonav/projects/glassfish/lists/users/archive/2008-03/message/1027) it seems like Glassfish a long time ago had the ability to do system property substitutions in descriptor files.

This would be a very cool feature to reintroduce, since we (just like the original mail thread poster) would be able to deploy the same application to different servers with server specific jms selectors without having to tamper with the artifact.

**Comment by smillidge** [comment]
I know this works for datasources is there something specific you have tried and failed with. For example the following annotations work to define a datasource with system property substitution and with password aliasing.
```java
@DataSourceDefinition(name="java:global/ExampleDataSource",
      className="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource",
      user="${mysql.user}",
      password="${ALIAS=mysql-db-password}",
      databaseName="mysql",
      serverName="localhost",
       properties= {"fish.payara.log-jdbc-calls=true", "fish.payara.sql-trace-listeners=fish.payara.examples.payaramicro.datasource.example.CustomSQLTracer"}
   )
```
In a similar fashion in a web.xml descriptor this works
```xml
<data-source>
     <name>java:global/ExampleDataSource</name>
     <class-name>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</class-name>
     <server-name>localhost</server-name>
     <port-number>3306</port-number>
     <database-name>mysql</database-name>
     <user>${mysql.user}</user>
     Example of how to use a Payara specific custom connection pool setting 
     <password>${ALIAS=mysql-db-password}</password>
    </data-source>
    -->
```

**Comment by jbndbc** [comment]
I have an ejb-jar.xml where I would like to do 

<activation-config-property>
    <activation-config-property-name>messageSelector</activation-config-property-name>
     <activation-config-property-value>source = '${jms.selector}'</activation-config-property-value>
 </activation-config-property>

but this does not seem to work with -Djms.selector=...

**Comment by fturizo** [comment]
Greetings @jbndbc, we're sorry it took a while for us to get back to you on this issue. From my understanding you need that Payara Server parses and filter system properties in the standard and proprietary _deployment descriptors_, correct? Are you still in need for this feature? If so please let us know to propose an enhancement request.

**Comment by jbndbc** [comment]
Yes, from our point of view this would still be a very useful feature to have.

**Comment by fturizo** [comment]
Thanks for the quick reply @jbndbc. I've created an enhancement request so our developers can look it up. We'll get back to you once we have more information. The internal ID of this request is **PAYARA-1255**

**Comment by mikecroft** [comment]
This feature is released in 172
