### ISSUE TITLE
Add support to configure hazelcast partition groups

### ISSUE THREAD

**Issue by OndrejM** [payara/Payara#870]
Hazelcast provides easy-to-configure mechanism of grouping members into bigger partitions to prevent replicas being stored in a cluster member on the same system.

Hazelcast partitioning defaults to having a partition per member, and replicas can be stored in any other member. Payara could support configuration of partition groups, as decribed in [hazelcast documentation](http://docs.hazelcast.org/docs/3.3/manual/html-single/hazelcast-documentation.html#partition-grouping). 

It is possible to define adavanced partitioning using hazelcast XML configuration file, but this cannot be combined with the configuration on domain.xml. Therefore at least support for `HOST_AWARE` partitioning would be very nice, as it is just a single configuration option.

**Comment by fturizo** [comment]
@OndrejM, any progress on this issue? Should we create the enhancement request on JIRA

**Comment by OndrejM** [comment]
@fturizo I think no progress has been made. We may create a JIRA for the developers.

**Comment by smillidge** [comment]
Created PAYARA-1343 for this
