### ISSUE TITLE
Conflicting Java version requirements between Windows Service and asadmin

### ISSUE THREAD

**Issue by jmutawa** [payara/Payara#879]
Hello,
I downloaded Payara 162 yesterday and liked what I saw so far, but noticed a strange issue:
I am running Windows 10 64bit, and have both JDK 7 and 8 installed, with 8 as the default.
The Windows Service created by `asadmin create-service` doesn't start, the error in domain1Service.err.log says:

`Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.`

Changed the registry key only, still with JDK 8, and now the service works. Then using the `asadmin` again to do anything else results in the opposite Java version requirement:
`Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.7', but '1.8' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.`

**Comment by OndrejM** [comment]
Hi @jmutawa, the error is not coming from the asadmin command, but from the Java itself. I got the same error when I executed plain `java -version` in command line, with java 8 and setting CurrentVersion to 1.7. It seems that CurrentVersion registry value must match the version returned by `java -version`.

When I executed java using full path, e.g. `"C:\Program Files\Java\jre8\bin\java.exe" -version`, I did not get the error.

Asadmin command uses plain `java` command by default, but there is not reason why it would want to execute different version of java for `create-service` than for any other command.

It could help to set path to Java for the asadmin command. You can do that in file `glassfish\config\asenv.bat` - by setting AS_JAVA variable.

**Comment by jmutawa** [comment]
Hello @OndrejM, it is an issue of multiple Java installations and not conflicting requirement between Payara components. I removed JDK+JRE 7 and now everything works.

Thank you very much, you can close the issue.

**Comment by HemantPekhale** [comment]
Copy java.exe javaw.exe javaws.exe from %JAVA7_HOME%\bin folder and replace with them in C:\ProgramData\Oracle\Java\javapath. In my case this solved the issue but if that's not the same case for you then also replace the three files in  C:\Windows/System32 folder.
