### ISSUE TITLE
Is there a way to reopen the connection pools to database without needing to restart all server?

### ISSUE THREAD

**Issue by OndrejM** [payara/Payara#887]
I've seen people asking the following question:

> if I need to restart a database server, Payara detect the lost of connection pools or a manual way to reopen the connection pools to database without needing to restart all server.

**Comment by smillidge** [comment]
Use connection checking in the datasource configuration

**Comment by edilmar** [comment]
If I configure 600 seconds for checking, I need to wait this time for the next check.
I would like to know some CLI or Console Admin way to reopen the connection instantaneously,
in a situation where, for example, I would need to restart the database server and I want to
restart the database pools in Payara server at this moment.

**Comment by lprimak** [comment]
@edilmar I believe the "flush connection pool" functionality will do just that.

**Comment by smillidge** [comment]
You can also enable connection validation in the administration console as this will check a connection before handing it out of the pool and if it is broken it will reconnect to the database.

See http://blog.payara.fish/an-introduction-to-connection-pools-in-payara-server

**Comment by OndrejM** [comment]
I think all is explained in the blog post in smillidge's comment. Especially in the comments below the blog post.

To summarize, there are 2 ways to renew stuck connections:
- setup a connection checker, which will renew stuck connections automatically (in the specified interval)
- flush and renew all connections manually (will drop all connections, even those that are OK - suitable after DB was manually restarted)

Both the options are available via asadmin and admin web console.

**Comment by mikecroft** [comment]
Would it be worth documenting this? Perhaps as another [user-guide](https://github.com/payara/Payara-Server-Documentation/tree/next/documentation/user-guides)?

**Comment by OndrejM** [comment]
Definitely. I think that many posts on blog.payara.fish are worth to make it into a user-guide too :)
