### ISSUE TITLE
@PersistenceContext doesn't work for beans created by CDI extensions

### ISSUE THREAD

**Issue by pa314159** [payara/Payara#900]
Having a class that has an EntityManager field injected via &#64;PersistenceContext

```
class SomeClass
{
    @PersistenceContext(unitName="PU")
    EntityManager em;
}
```

Assume the class is not packed in a CDI archive, but added by a CDI extension in the `AfterTypeDiscovery` phase

```
void afterTypeDiscovery( BeanManager bm, @Observes AfterTypeDiscovery event )
{
    final AnnotatedType<?> type = bm.createAnnotatedType( SomeClass.class );

    event.addAnnotatedType( type, type.getJavaClass().getName() + "#" );
}
```

The problem is that the EntityManager is always `null` on Payara - it works on Wildfly-10.

There is a project demonstrating this issue at https://github.com/pa314159/persistence-ext-issue

**Comment by smillidge** [comment]
Just wondering is it still broken if you add the bean during the BeforeTypeDiscovery phase?

**Comment by pa314159** [comment]
Updated [demo project](https://github.com/pa314159/persistence-ext-issue) with `BeforeBeanDiscovery` and `AfterBeanDiscovery` phases

- it fails for `BeforeBeanDiscovery`
- it works for `AfterBeanDiscovery`

However, the `AfterBeanDiscovery` phase doesn't help in my project since I need to perform bean discovery before...

**Comment by mikecroft** [comment]
Confirmed the bug and created `PAYARA-1200`

**Comment by smillidge** [comment]
jenkins test please
