### ISSUE TITLE
Slow sql logger with miliseconds

### ISSUE THREAD

**Issue by ionutursuleanu** [payara/Payara#901]
It will be useful to be able to configure the slow sql logger below 1 second. A query witch returns only one row, without using an index, it usually takes less than 1 second, but way more than with the expected index (500ms vs 50ms, for example).

**Comment by mikecroft** [comment]
I've created internal enhancement request `PAYARA-859` for this. I'm not sure how feasible this would be - I think the reason why it was implemented this way was to reduce the load on the server. I think the feature was originally intended to be used in production, so a difference of miliseconds is unlikely to point to any real issue which needs to be dealt with.

I think @smillidge wrote the feature, though, so maybe he can comment?

**Comment by smillidge** [comment]
Pretty easy to do, although backward compatibility would need to be handled for existing configurations

**Comment by smillidge** [comment]
Fixed by #924
