### ISSUE TITLE
ManagedThreadPool - threads are not interrupted on application undeployment

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#909]
This is on payara-4.1.1.162
I was playing around with threads from a ManagedThreadPool and was asking myself if it possible for Payara to interrupt the created threads on application undeploy.
When I start a thread which is then doing some lengthy processing and undeploy the application, the thread is still doing its work and is only stopped when the processing is finished. Is that intended? I would expect that the container tries to interrupt all threads that were created by the ManagedThreadPool.

On another note: I noticed that the ManagedExecutorService has a hung-task-threshold. However, when the time expires there is a message in the log but the task is not stopped by Payara. Is this only an informational message?

Thanks in advance and best regards,
Chris.

**Comment by mikecroft** [comment]
Sorry, this one seems to have fallen down the cracks. It's my understanding that your assumptions here are correct; Payara will not interrupt threads on application undeploy and that message is indeed informational only.

@smillidge can you confirm?

**Comment by smillidge** [comment]
It is not possible to stop a thread processing in Java. It may be possible to interrupt the thread but the application would need to be able to handle the interrupt, if it is in the middle of processing interrupting it won't make any difference.

**Comment by michaelpaesold** [comment]
Actually, I think it's not a bad idea to interrupt the threads, it might help in some situations, especially if this is a documented behaviour.

The deprecation note to `Thread.stop()` actually says that one should use some variable to indicate that a thread should stop it's work, and `Thread.interrupt()` should be used to wake up waiting threads.

> If the target thread waits for long periods (on a condition variable, for example), the `interrupt` method should be used to interrupt the wait.

On a quick look I didn't find anything, but is there some state that a managed thread chould check whether it should cancel its work?

**Comment by chrjohn** [comment]
IMHO the thread should run in a while loop like this:
`while (!Thread.interrupted()) {
...
}`

In http://download.oracle.com/otn-pub/jcp/concurrency-1_0-fr-spec/EE-Concurrency-Utilities-1.0-fr.pdf section 3.4.4 it says

> When a ManagedThreadFactory instance is stopped, such as when the component that created it is
stopped or when the application server is shutting down, all threads that it has created using the
newThread() method are interrupted.

**Comment by fturizo** [comment]
@chrjohn, did you test that assertion with a sample application using a managed `ManagedThreadFactory`? It would help us understand the use case a bit better.

**Comment by chrjohn** [comment]
Hi @fturizo ,
I have also tested with a `ManagedThreadFactory` but there seems to be no difference whether I am using a managed ThreadFactory, Pool or ExecutorService. I have created a simple test case that sleeps for 30 seconds. When you try to undeploy the application or stop the server inside the 30 seconds it does not work as intended. The server is waiting for the 30 seconds to elapse instead of interrupting the threads of the application or managed thread factory. See https://github.com/payara/Payara/issues/909#issuecomment-261262880

The test case is attached. Please rename to jar and deploy using
`asadmin deploy --type osgi payarabug-909-0.0.1-SNAPSHOT.jar`

[payarabug-909-0.0.1-SNAPSHOT.zip](https://github.com/payara/Payara/files/682323/payarabug-909-0.0.1-SNAPSHOT.zip)

Prerequisite: please create a test queue beforehand:
`asadmin create-jms-resource --restype=javax.jms.Queue --enabled=true queue/test`

Then just send a message to that queue (doesn't matter which type of message). It will then trigger the PayaraBugWorker EJB and give output similar to this:

```
[2017-01-03 14:50:26,803] [INFO ] [unknown.jul.logger] [logging output pump] [#1] PayaraBugMDB.onMessage() START
[2017-01-03 14:50:26,817] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ....PayaraBugWorker.work()
[2017-01-03 14:50:26,819] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ....interrupted=false
[2017-01-03 14:50:26,819] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ....Starting thread...
[2017-01-03 14:50:26,819] [INFO ] [javax.enterprise.concurrent] [concurrent/__defaultManagedThreadFactory-Thread-2] [#1] Job submitted for com.macd.payarabug-909_0.0.1.SNAPSHOT likely during deployment. Continuing...
[2017-01-03 14:50:26,820] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ........task run() and sleeping 30 seconds
[2017-01-03 14:50:56,821] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ........finished sleeping
[2017-01-03 14:50:56,822] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ....thread finished
[2017-01-03 14:50:56,822] [INFO ] [unknown.jul.logger] [logging output pump] [#1] ....interrupted=false
[2017-01-03 14:50:56,823] [INFO ] [unknown.jul.logger] [logging output pump] [#1] PayaraBugMDB.onMessage() END
```

The PayaraBugWorker bean is just this:

```
package payarabug;

import javax.annotation.Resource;
import javax.ejb.Stateless;
import javax.enterprise.concurrent.ManagedThreadFactory;

@Stateless( mappedName = "PayaraBugWorker" )
public class PayaraBugWorker {

    @Resource
    private ManagedThreadFactory managedThreadFactory;

    
    public void work() {
        System.out.println( "....PayaraBugWorker.work()" );
        final Runnable task = new Runnable() {
            
            @Override
            public void run() {
                System.out.println( "........task run() and sleeping 30 seconds" );
                try {
                    Thread.sleep( 30000 );
                } catch ( InterruptedException e ) {
                    System.out.println( "........Thread was interrupted " + e.getMessage() );
                    Thread.currentThread().interrupt();
                }
                System.out.println( "........finished sleeping" );
            }
            
        };
        Thread myThread = managedThreadFactory.newThread( task );
        try {
            try {
                System.out.println( "....interrupted=" + myThread.isInterrupted() );
                System.out.println( "....Starting thread..." );
                myThread.start();
                myThread.join();
                System.out.println( "....thread finished" );
            } catch ( InterruptedException e ) {
                System.out.println( "....Thread was interrupted " + e.getMessage() );
                Thread.currentThread().interrupt();
            }
        } finally {
            System.out.println( "....interrupted=" + myThread.isInterrupted() );
        }

    }
}

```

Please tell me if you need any more information.
Thanks,
Chris.

**Comment by chrjohn** [comment]
I don't know if this is the correct place to look for the code but there is this: http://grepcode.com/file/repo1.maven.org/maven2/org.glassfish/javax.enterprise.concurrent/1.0/org/glassfish/enterprise/concurrent/ManagedThreadFactoryImpl.java which has a stop() method which interrupts all threads. But I cannot find something similar in the Payara code repository (or looking in the wrong place). I would have expected that the Glassfish code should also be present in the Payara repository?!
Thanks,
Chris.

**Comment by chrjohn** [comment]
Hi @fturizo ,
thanks for your reply.
Unfortunately, there is no use interrupting the threads in the Activator lifecycle's events or in the PreDestroy method since these methods are only called after 30 seconds (i.e. when the sleep period is over). I was looking for a container provided solution which will interrupt the threads.

> When a ManagedThreadFactory instance is stopped, such as when the component that created it is
> stopped or when the application server is shutting down, all threads that it has created using the
> newThread() method are interrupted.

I don't have much insight into the Payara code so here is what I would expect after having read the above:
If I am not mistaken, then "the component that created it" would be my application, right? And "create" means injected or looked up via JNDI? Since there should be no other way for my application to **create** a ManagedThreadFactory.
Isn't there any context information associated with my application? So that Payara could know which threads were created in the context of my application and only interrupt these?
Again, this is my naive way of looking at this. :)

Thanks,
Chris.

**Comment by fturizo** [comment]
Hi @chrjohn.

In this case when speaking about managed resources like the injected `ManagedThreadFactory` or other resources with the `@Resource` annotation, these resources are created by the application server in order to be used by multiple components of separate enterprise applications. When you are injecting the factory in your EJB, the server might have created this resource beforehand for it to be used by other components or may have created it recently for your component to be used. In this case the lifecycle of the component is the responsibility of the application server. In this case the spec is right and you can't force the factory to "stop" when the application is un-deployed or shutdown.

You don't need to wait until the threads sleep period is over to stop them. After creating a new thread in the method gather them on a collection that is persisted on your application on a `@Singleton` bean, and on it's `@PreDestroy` method iterate through this collection to call the Thread.interrupt method. This way the threads should stop sleeping and can be finished accordingly.

Hope my suggestion's clear enough.

**Comment by chrjohn** [comment]
Hi @fturizo ,
your suggestion is clear enough. I was just hoping to get along without any more application overhead. But on the other hand that is probably what I have asked for when using threads directly.

So the only way I could stop some lengthy message processing is to spawn a new thread from the onMessage() method and interrupt it after a given time. All other things I tried with transaction timeouts, Futures etc. aborted the transaction but the EJB still continued its work in the background.

So for me the only thing left open is that the application server should interrupt ALL threads that were returned from the factory when the server is stopped. But that is not happening, although there is a stop() method in the ManagedThreadFactoryImpl which will interrupt all threads if called.

Thanks,
Chris.

**Comment by fturizo** [comment]
Hi @chrjohn. 

If the use case is to delegate a lengthy message processing task a to new thread from the **MDB**, I recommend to annotate the  `PayaraBugWorker.work` method with `@Asynchronous` instead. This way you won't have to worry about thread management and can easily handle the result using a Future object (get the result, cancel the task, etc.).

**Comment by chrjohn** [comment]
Hi @fturizo ,
the use case is to delegate the message processing to a new thread that can be **interrupted**. We have some problems every once in a while that EclipseLink's ConcurrencyManager is hanging in kind of a livelock and we had to bounce the server otherwise the system would hang in that state forever.

As stated above:
> All other things I tried with transaction timeouts, Futures etc. aborted the transaction but the EJB still continued its work in the background.

Using Future.get() with `@Asynchronous` doesn't do the trick as it is hanging until the sleep period is over. (this was one of the first things I tried ;))
Using only `@Asynchronous` allows me to undeploy the application but the spawned thread is not interrupted and still running in the background which must not happen.

Thanks again,
Chris.

**Comment by fturizo** [comment]
Hello @chrjohn 

I understand the need to interrupt the threads in order to prevent leaks and concurrency issues when un-deploying the application. You can store the `Future `objects in a singleton bean and on its `PreDestroy `method call the `boolean cancel(boolean mayInterruptIfRunning) ` method to interrupt all running tasks. This should guarantee you that all resources all cleaned up when un-deploying the application.

**Comment by chrjohn** [comment]
Hi @fturizo , thanks for your suggestions. This sounds like a good workaround to achieve the desired behaviour.

Still, the application server should interrupt all threads from the ManagedExecutorService/ThreadFactory on shutdown of the server. But I can live with the workaround for now. ;)

Best regards,
Chris.

**Comment by fturizo** [comment]
Hi, @chrjohn. No problem. However, as you mention the threads SHOULD be interrupted in the case of  **server's shutdown**. I'll look into this a bit and if try to reproduce the bug you mention for this case.

**Comment by fturizo** [comment]
Hello @chrjohn, sorry it took me this much to give a reply to this issue. After some testing using the `ThreadFactory` with servlets and CDI beans, I can confirm that the threads are getting interrupted/killed when the server is shutdown, so I'm closing the issue for the moment, if you find a test case when this is not true, feel free to reopen this issue and we can resume the work on it.

**Comment by chrjohn** [comment]
Hi @fturizo , actually I've already attached a test case earlier. However, I will try to reproduce with payara 171 and let you know how it goes.
Thanks,
Chris.
