### ISSUE TITLE
Maven deployment on payara-full-server

### ISSUE THREAD

**Issue by mit-skramer** [payara/Payara#923]
In one of the recent blog entries (http://blog.payara.fish/payara-micro-maven-deployer-demo) we have seen the possibility to deploy maven artifacts directly from the repository to payara-micro-server. My question is, is this even possible for payara-full-server (running as a stand-alone-server on some development machine)? Our goal is to avoid discontinued maven-glassfish-plugin for this purpose.

**Comment by mikecroft** [comment]
There is no Payara specific plugin, but you can use the Cargo plugin to [deploy using the REST interface](https://github.com/arun-gupta/couchbase-javaee/issues/7#issuecomment-163538550):

>  if you go to https://localhost:4848/management/domain/applications/deploy you'll get a basic HTML form wrapper for the REST interface.
> 
> The only required property is id, which is indicated by the asterisk next to it. Unintuitively, id in this case means the path to the WAR you want to POST and deploy. You'll probably also want to target it to the default server as well so, based on the example in that blog, you'd have something like this:
> 
> ```
> curl -s -S \
>     -H 'Accept: application/json' -X POST \
>     -H 'X-Requested-By: dummy' \
>     -F id=@/path/to/application.war \
>     -F target=server \
>     -F force=true \
>     http://localhost:4848/management/domain/applications/application
> ```

Here's an example that @OndrejM did a while back:
https://github.com/arun-gupta/couchbase-javaee/pull/9/files

**Comment by smillidge** [comment]
We should add some documentation on this and/or a blog.

**Comment by OndrejM** [comment]
Good idea to document this. I created an internal ticket PYSVC-75 for it.

**Comment by mit-skramer** [comment]
@mikecroft Thanks a lot, that solved my problem.
