### ISSUE TITLE
JSR107 Javadocs should be linked from the root GitHub page

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara#942]
There is a link to the Payara Micro API javadoc, but no link to the jsr107 javadoc here:
http://payara.github.io/Payara/appserver_API/New%20folder/payara-appserver-modules_api/payara-jsr107_api/site/apidocs/

**Comment by mikecroft** [comment]
Assigned @OndrejM since he did the work for the latest GitHub page

**Comment by OndrejM** [comment]
The linked javadoc contains only javadoc for Payara specific API related to JCache. I will also add link JCache JSR 107 javadoc which is posted on JSR 107 Github mirror:  http://www.javadoc.io/doc/javax.cache/cache-api/1.0.0

**Comment by mikecroft** [comment]
yep, based on the repo it looks like the only extra Javadoc there is for Payara right now. Thanks!

**Comment by mikecroft** [comment]
Change merged
