### ISSUE TITLE
404 Error page title still says "GlassFish v4"

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara#949]
Line 107:
https://github.com/payara/Payara/blob/581a087c6e28e04c191387739756a3820aab9bf9/nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/HttpUtils.java#L107

**Comment by smillidge** [comment]
Created internal Bug ID PAYARA-946

**Comment by smillidge** [comment]
Fixed by #976
