### ISSUE TITLE
Wrong version of Mimepull included in the modules folder

### ISSUE THREAD

**Issue by Erates** [payara/Payara#954]
I'm using Payara 162 and have a REST service running on the server. It uses the FormDataParam and FormDataContentDisposition classes provided by jersey-media-multipart. Now when trying the REST service, I get an exception that the method org.jvnet.mimepull.MIMEMessage.close() does not exist.

After some digging around I think I have found the cause. In the modules directory is jersey-media-multipart.jar included, which is version 2.22.1. This uses mimepull version 1.9.6. But when I look at the version of mimepull that is included in the modules directory, I see that that version is 1.9.4. When I look at that code I can confirm that that version does not include the "close" method.

Fix it by updating the mimepull version included in the modules folder to 1.9.6.

**Comment by mikecroft** [comment]
Probably one for @Pandrex247 - I just checked the latest pre-release build and it's 1.9.4 in there too. I'm not sure where it gets pulled from in the build.

**Comment by smillidge** [comment]
Looks pretty easy to fix I've raised an internal issue PAYARA-930

**Comment by Erates** [comment]
Awesome! Any idea when this get's released?

**Comment by mikecroft** [comment]
The 163 release is due out in the second week of August (providing testing goes well). Keep an eye on twitter [@payara_fish](https://twitter.com/payara_fish) and our blog http://blog.payara.fish/ for the announcement!

**Comment by mikecroft** [comment]
Actually, if you can't wait till then, it looks like the fix has already been merged into upstream so you could download a pre-release build and it would probably be in there now:
http://www.payara.fish/upstream_builds

**Comment by Erates** [comment]
Well, I think I might try the pre-release on my local machine. I've only started development so if I'll use the pre-release, I can continue developing.

Our release is not before end of august, so that won't be a problem. 

Thanks Payara Team!!

**Comment by Erates** [comment]
I can confirm that the bug is fixed when I use the pre-release. Great work!
