### ISSUE TITLE
Race condition when deploying immediately after restart.

### ISSUE THREAD

**Issue by pdudits** [payara/Payara#985]
As mentioned in #871, a race condition exists when an application is being deployed before all other applications are loaded. Usual manifestation of this is following:

````
C:\>asadmin restart-instance inst1 && asadmin deploy --target inst1 --force issue-871.jar
inst1 was restarted.
Command restart-instance executed successfully.
issue-871 disabled failed
An error occurred during replication
Failure: Command disable failed on server instance inst1: remote failure: Application not registered
Command deploy failed.
````

A PR that waits for applications to be loaded for InstanceDeploy and Disable commands follows.

**Comment by mikecroft** [comment]
Assigned @smillidge for now since @Pandrex247 isn't around. Needs someone to verify @pdudits commit
