### ISSUE TITLE
Ctrl + C interrupt to stop Payara Micro from command line

### ISSUE THREAD

**Issue by PeterWippermann** [payara/Payara#989]
The [Micro documentation](https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/payara-micro.html#61-stopping-an-instance-from-the-command-line) states that from the CLI you can only stop Payara Micro by killing its process.

I know that you can find the PID of Payara's JVM with `jps`.
However, to make handling a little easier - especially when taking one's first steps with Payara Micro - it would be nice to have support for `Ctrl + C` to stop the server.

**Comment by PeterWippermann** [comment]
I just learned that Payara eventually stops after sending `Ctrl + c`!
But that behaviour doesn't seem to be deterministic on my machine. Sometimes I have to hit the combination three times in a row, sometimes it just works right away?! Do you see any reason why the server shouldn't stop immediately?

In any case, two minor improvements:

- there should be a log message on StdOut saying that the SIGINT has been received and shutdown is beginning.
- The documentation linked above should be updated.

**Comment by PeterWippermann** [comment]
I also noticed that the logging behaviour after SIGINT isn't always the same:
````
[2016-08-03T00:06:29.478+0200] [Payara Micro 4.1] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1470175589478] [levelValue: 800] Payara Micro  4.1.1.162 #badassmicrofish (build ) ready in 7587 (ms)

JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]

C:\sprint\payara-micro>
````

compared to

````
`[2016-08-02T23:56:02.561+0200] [Payara Micro 4.1] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1470174962561] [levelValue: 800] Payara Micro  4.1.1.162 #badassmicrofish (build ) ready in 7609 (ms)

[2016-08-03T00:05:50.715+0200] [Payara Micro 4.1] [INFO] [] [com.hazelcast.instance.Node] [tid: _ThreadID=28 _ThreadName=hz.ShutdownThread] [timeMillis: 1470175550715] [levelValue: 800] [10.144.71.79]:5900 [development] [3.6.2] Running shutdown hook... Current state: ACTIVE

JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]

C:\sprint\payara-micro>
````

Does this imply that the Hazelcast node isn't reliably shut down?

**Comment by mikecroft** [comment]
This could well be a quirk of `SIGINT` handling in Windows. I've never experienced a delay on Linux. I don't think that the output after killing indicates any problem with Hazelcast, it's embedded in Payara Micro, so if that dies then Hazelcast goes with it.

**Comment by PeterWippermann** [comment]
So, will you update the docs, @mikecroft ?

**Comment by mikecroft** [comment]
I'll need to look into this a bit more and confirm the behaviour. What version of Windows are you using? Is this your local machine or a server? And what version of Java?

**Comment by PeterWippermann** [comment]
I'm on Windows 10 and Java 1.7u79. This is my local machine, so no delay through any remote communication :-)

I'd be happy already, if you just mention in the docs that Ctrl + C is still working. Just because at the moment the docs explicitly say: 

> The only way to shut down an instance from the command line is to find the process ID of the Payara Micro instance, and send a kill signal to it.

**Comment by mikecroft** [comment]
Internal issue ID to modify the docs: `PYSVC-186`

**Comment by mikecroft** [comment]
Fixed in current docs:
https://docs.payara.fish/documentation/payara-micro/stopping-instance.html
